### ISSUE TITLE
`mini.surround`: typo in docs

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#1001]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

"setction" here: https://github.com/echasnovski/mini.surround/blob/a0dbc2285d774a96b27b3cbe58eca89a39bf74f9/doc/mini-surround.txt#L281

**Comment by echasnovski** [comment]
Thanks for noticing! Should be fixed on latest `main`.
