### ISSUE TITLE
Inconsistent spaces in mini.splitjoin

### ISSUE THREAD

**Issue by justus2510** [echasnovski/mini.nvim#1002]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

splitjoin

### Description

I like to format my function calls such that the arguments are all indented to the opening parenthesis. However, this style seems to introduce inconsistent spaces when joining.

I was able to easily fix this using a hook:
```
local function comma_fixup(split_positions)
    local line = vim.api.nvim_get_current_line()
    local new_line = {}
    for i = 1, #line do
        table.insert(new_line, line:sub(i, i))
        if line:sub(i, i+1):match(",[^%s]") then
            table.insert(new_line, " ")
        end
    end
    new_line = table.concat(new_line)
    vim.api.nvim_set_current_line(new_line)
end

require("mini.splitjoin").setup({
    join = { hooks_post = {comma_fixup} },
})
```

### Neovim version

0.10.0

### Steps to reproduce

1. Format a function call like this (all arguments lined up):
```
func(a,
     b,
     c,
     d)
```
2. Join/Toggle the lines.

### Expected behavior

`func(a, b, c, d)`

### Actual behavior

`func(a,b, c,d)`

**Comment by echasnovski** [comment]
Thanks for the issue!

This is an intended and [documented](https://github.com/echasnovski/mini.nvim/blob/35422e90b0de232245e2b1d3b3737a7c419d377b/doc/mini-splitjoin.txt#L478-L482) behavior. The idea is that it is consistent with common case of splitting function call (like `f(a, b, c)`) or an array without initial padding (like `[a, b, c]`).

The suggested way to account for that is indeed with custom hooks.

Closing as not planned.
