### ISSUE TITLE
Work with motions

### ISSUE THREAD

**Issue by bogdan-the-great** [echasnovski/mini.nvim#1008]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Hi.

Which-key shows motions with visual (`v`), change (`c`) and yank (`y`) keys.

![image](https://github.com/echasnovski/mini.nvim/assets/37738748/da2e0322-743e-4472-8874-341f62f9c2a8)

Is this something wanted?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> Is this something wanted?

I'd happy to include this kind of functionality in 'mini.clue', but its design doesn't work well in these cases. The main issue here is that those keys change mode and are not a start of those motion/textobject keys. The best effort of tackling this was done in #442, but as 'mini.clue' is particularly hacky it doesn't seem to be a good idea to disturb it any further.

Closing as not planned.
