### ISSUE TITLE
add motion that move cursor to first/last line of the paragraph?

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1014]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

---

### Description

the `{` and `}` motion move cursor to blank line

but sometimes it's useful to move cursor to the first/last non-blank line of the paragraph (e.g. when using blockwise-visual mode)

[Vim: How to jump to first/last line of the current paragraph?](https://stackoverflow.com/questions/4836944/vim-how-to-jump-to-first-last-line-of-the-current-paragraph)

i hope that mini can add this feature

maybe mini.motions? :)

here is how I implemented it:

```
local function paragraph_border_line_p(lnum)
	if lnum == 1 then
		return true
	end
	if lnum == vim.fn.line('$') then
		return true
	end
	if vim.fn.getline(lnum) ~= '' and vim.fn.getline(lnum - 1) == '' then
		return true
	end
	if vim.fn.getline(lnum) ~= '' and vim.fn.getline(lnum + 1) == '' then
		return true
	end
	return false
end

function paragraph_border_backward_lnum(lnum)
	if lnum == 1 then
		return lnum
	end
	if paragraph_border_line_p(lnum - 1) then
		return lnum - 1
	end
	return paragraph_border_backward_lnum(lnum - 1)
end

function paragraph_border_forward_lnum(lnum)
	if lnum == vim.fn.line('$') then
		return lnum
	end
	if paragraph_border_line_p(lnum + 1) then
		return lnum + 1
	end
	return paragraph_border_forward_lnum(lnum + 1)
end

function paragraph_border_backward()
	local line_number_current = vim.fn.line('.')
	local line_number_destination = paragraph_border_backward_lnum(line_number_current)
	vim.cmd(tostring(line_number_destination))
end

function paragraph_border_forward()
	local line_number_current = vim.fn.line('.')
	local line_number_destination = paragraph_border_forward_lnum(line_number_current)
	vim.cmd(tostring(line_number_destination))
end

vim.keymap.set({'n', 'v'}, '(', paragraph_border_backward)
vim.keymap.set('o', '(', 'V(')
vim.keymap.set({'n', 'v'}, ')', paragraph_border_forward)
vim.keymap.set('o', ')', 'V)')
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Unfortunately, I don't think there will be a good place for this in 'mini.nvim'.

There is no plans for 'mini.motions' or something like it. Maybe if there are more non-trivial motions that can be fit in the same module nicely.

Closing as "probably not planned, but will keep in mind".
