### ISSUE TITLE
Add a new colorscheme for Terminal mode in mini.statusline

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1019]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

Hi. Is it be possible to add 'MiniStatuslineModeTerminal' to mini.statusline and treat terminal mode specially as with normal, insert etc since terminal mode is pretty common.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

There is [`MiniStatuslineModeOther`](https://github.com/echasnovski/mini.nvim/blob/d187614ecee84ef8d7456339ed7ce1160d054310/doc/mini-statusline.txt#L57) just for that.

Closing as not planned.
