### ISSUE TITLE
mini.surround: Incorrect default config.search_method value in help page.

### ISSUE THREAD

**Issue by vunhatchuong** [echasnovski/mini.nvim#1032]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

In `README` the default value for `config.search_method` is [cover](https://github.com/echasnovski/mini.surround/blob/main/README.md?plain=1#L188). In the code it's also [cover](https://github.com/echasnovski/mini.surround/blob/main/lua/mini/surround.lua#L701) but in help page it's [cover_or_next](https://github.com/echasnovski/mini.surround/blob/main/doc/mini-surround.txt#L654).

### Neovim version

0.10.0

### Steps to reproduce

.

### Actual behavior

.

**Comment by echasnovski** [comment]
Thanks for noticing!

I'll fix it once I am at "main" machine.

**Comment by echasnovski** [comment]
Should be fixed on latest `main`.
