### ISSUE TITLE
mini.completion: boolean flag on configuration for enabling / disabling autocompletion

### ISSUE THREAD

**Issue by HicaroD** [echasnovski/mini.nvim#1036]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Before `mini.completion`, I've used `nvim-cmp` and `coq-nvim` for autocompletion. On both plugins, they have a configuration for disabling autocompletion, so I could trigger it with some keybinding when needed because I don't really like the completion window popping up on my screen while I type.

I've implemented and tested this feature on a local fork and it worked pretty nice. I am wondering if you guys would accept a PR from me.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This can already be (virtually) done [by setting a very large delay](https://github.com/echasnovski/mini.nvim/blob/072ef026a538cf4a9dedba56ad8eecffa9e9abb6/doc/mini-completion.txt#L175-L176). This can also be done to implement toggling.

Closing as not planned.
