### ISSUE TITLE
[mini.completion] info window position conflicts with `noice.nvim`?

### ISSUE THREAD

**Issue by leaysgur** [echasnovski/mini.nvim#1040]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

(Sorry, I'm not sure this is bug or not and should be reported here or not but,)
When using `mini.completion` with `noice.nvim`, `info` window is not rendered properly.

### Neovim version

0.10.0

### Steps to reproduce

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
	local lazyrepo = "https://github.com/folke/lazy.nvim.git"
	vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

vim.opt.number = true

require("lazy").setup({
	{
		"folke/noice.nvim",
		dependencies = { "MunifTanjim/nui.nvim" },
		opts = {
			-- popupmenu = { enabled = false },
		},
		event = "VeryLazy",
	},

	{
		"neovim/nvim-lspconfig",
		dependencies = {
			{ "williamboman/mason.nvim", config = true },
			"williamboman/mason-lspconfig.nvim",
		},
		config = function()
			require("mason-lspconfig").setup_handlers({
				function(server)
					require("lspconfig")[server].setup({})
				end,
			})
		end,
	},

	{
		"echasnovski/mini.completion",
		opts = {
			window = {
				info = { border = "double" },
			},
		},
	},
})
```

### Expected behavior

It should be rendered properly.

Disabling `noice.nvim`'s `popupmenu` seems to fix this issue.

![image](https://github.com/echasnovski/mini.nvim/assets/6259812/1d1c1676-db95-41c7-a0ad-53057619602d)

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/6259812/a2dc2f63-7503-4f18-b195-33c77905e3cd

**Comment by echasnovski** [comment]
Thanks for the issue!

> Disabling `noice.nvim`'s `popupmenu` seems to fix this issue.

Indeed, this is a suggested solution here. The 'mini.completion' module works only with built-in completion popup.

Closing as not planned.
