### ISSUE TITLE
mini.icons not loaded as dependency for oil.nvim

### ISSUE THREAD

**Issue by Rasmus-Bertell** [echasnovski/mini.nvim#1048]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icons

### Description

Having mini.icons as the dependency for oil.nvim doesn't work without adding `opts = {}` to the dependency spec so it's not lazy loaded.

### Neovim version

NVIM v0.10.0

### Steps to reproduce

See https://github.com/stevearc/oil.nvim/issues/445 for steps to reproduce. 

### Expected behavior

I would expect plugin dependencies to work without adding extra options to them.

### Actual behavior

Oil opens the folder without any icons.

**Comment by echasnovski** [comment]
Installing and enabling any of 'mini.nvim' modules is treated as user's responsibility. All it should require for users is to call `require('mini.icons').setup()`. How they do that (especially if it is lazy loaded), is not a 'mini.nvim' issue.

Closing as not a 'mini.nvim' issue.
