### ISSUE TITLE
saip excluding trailing whitespace

### ISSUE THREAD

**Issue by GregoryShields** [echasnovski/mini.nvim#1056]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Please forgive me if I'm just not smart enough to configure mini.surround on my own.

But can someone help me out with how to configure the plugin to surround the text of a paragraph and exclude trailing whitespace? I add two spaces at the end of my paragraphs for purposes of Markdown, so when I try to surround a paragraph, for instance, with quotation marks, the ending quotation mark is placed after those two trailing spaces instead of up against the period at the end of the paragraph.

If for some reason this is not configurable, then I would think that pretty much everyone would like to see this. However, I'm pretty sure I just can't understand how to configure the existing plugin. I find the documentation to be particularly difficult to understand or even obtuse, but maybe it's just me.

Thanks in advance.

**Comment by echasnovski** [comment]
My initial response was going to suggest using appropriate "paragraph without trailing whitespace" textobject (instead of `ip`). For example, created with 'mini.ai'. This approach is still valid and will work.

However, I *think* there is a special handling of first line indent (which is essentially a leading whitespace) when adding surrounding. So if there is, it is reasonable to add a special handling of trailing whitespace at the last line.

I'll take a closer look once I have access to a fully functioning Neovim instance.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Ignoring trailing whitespace on last line indeed makes it more symmetrical. This should now be part of `main` branch.

**Comment by GregoryShields** [comment]
Thanks!

I'm sorry to say though that after updating to the latest version, I still don't know how to create and/or execute a command that will surround a single paragraph while excluding trailing spaces so that the surround character at the end is up against the text rather than being placed after a space or two.

I'd be happy to use the appropriate "paragraph without trailing whitespace" textobject (instead of ip) to do this, but I'm a bit lost. I'm sure it's in the documentation, but the concepts involved here haven't penetrated my skull yet. And when you say, "For example, created with 'mini.ai'," I really don't know what you mean there.

It appears that you have implemented what you call "a special handling of trailing whitespace at the last line", but again I'm pretty well lost as to how to use it. I do realize that I should read the documentation, but as I said, I'm having a little trouble with grokking the concepts. Any help would be appreciated.

Thanks again.

**Comment by echasnovski** [comment]
> I'm sorry to say though that after updating to the latest version, I still don't know how to create and/or execute a command that will surround a single paragraph while excluding trailing spaces so that the surround character at the end is up against the text rather than being placed after a space or two.

What did you try? It should work with `saip` followed by surrounding identifier, same as you mention in the title.

Here is a screencast (red background highlights trailing whitespace and comes from 'mini.trailspace'):

https://github.com/user-attachments/assets/b314c751-b841-46c5-a477-509629636aad

> I would also like to mention that I've observed that `mini.surround` seems to interpret multiple paragraphs not separated by a blank line as being all one paragraph.

This is not 'mini.surround' that does this, but Neovim itself. See `:h ip` and `:h paragraph`.
