### ISSUE TITLE
Surround keymap broken

### ISSUE THREAD

**Issue by Lukalukito** [echasnovski/mini.nvim#1058]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

surround

### Description

mini surround keymaps are not working after last update. before, s will show which-key and wait for next action (add, delete ...) but now it just uses nvims default s action( replacing current char going into insert mode). I am not sure if this has to do anything with which-key or my settings, but all i did is update every plugin with lazy.nvim. if this is a which-key problem i'll report there

### Neovim version

0.10.0

### Steps to reproduce

i have no idea what to put here

### Expected behavior

mini.surround default keymap (s) opens which-key (like before, without any configuration needed)

### Actual behavior

surround keymap doesn't get registered so nvim uses default action.

**Comment by echasnovski** [comment]
>  if this is a which-key problem i'll report there

There was no big updates in 'mini.surround', yet there was a big update in 'folke/which-key.nvim'. As everything still works without which-key, I think it is safe to assume the problem is not inside 'mini.surround'.

**Comment by Lukalukito** [comment]
thanks. will report it there too

**Comment by yavorski** [comment]
@Lukalukito  DId you report it, I am having the same issue?

**Comment by yavorski** [comment]
@echasnovski I deleted all my plugins and left only `mini.surround` with default configuration.
Pressing just <kbd>s</kbd> in normal or visual mode is not indicating that another key is needed to continue it just delete the character or selected text and puts neovim in insert mode.


```bash
nvim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

<details>
<summary> <code>:verbose map s</code> - click to expand</summary>

```vim
        Last set from Lua (run Nvim with -V1 for more details)
n  sfn         * <Lua 78: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Find next right surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  srn         * <Lua 77: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Replace next surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sdn         * <Lua 76: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Delete next surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  shl         * <Lua 75: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Highlight previous surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sFl         * <Lua 74: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Find previous left surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sfl         * <Lua 73: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Find previous right surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  srl         * <Lua 72: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Replace previous surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sdl         * <Lua 71: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Delete previous surrounding
        Last set from Lua (run Nvim with -V1 for more details)
x  sa          * :<C-U>lua MiniSurround.add('visual')<CR>
                 Add surrounding to selection
        Last set from Lua (run Nvim with -V1 for more details)
n  sn          * <Lua 70: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:892>
                 Update `MiniSurround.config.n_lines`
        Last set from Lua (run Nvim with -V1 for more details)
n  sh          * <Lua 69: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Highlight surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sF          * <Lua 68: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Find left surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sf          * <Lua 67: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Find right surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sr          * <Lua 66: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Replace surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sd          * <Lua 65: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Delete surrounding
        Last set from Lua (run Nvim with -V1 for more details)
n  sa          * <Lua 64: ~/.local/share/nvim/lazy/mini.surround/lua/mini/surround.lua:1252>
                 Add surrounding
        Last set from Lua (run Nvim with -V1 for more details)
Press ENTER or type command to continue
```

</details>

**Comment by echasnovski** [comment]
> Pressing just s in normal or visual mode is not indicating that another key is needed to continue it just delete the character or selected text and puts neovim in insert mode.

Yes, nor it should indicate. Neovim waits for 'timeoutlen' milliseconds if it is not sure which mapping user wants to activate. After they pass, it executes the input as is.

What value of 'timeoutlen' do you have set? See it via `:=vim.o.timeoutlen`.

**Comment by yavorski** [comment]
> What value of 'timeoutlen' do you have set? See it via `:=vim.o.timeoutlen`.

1000 

> **Edit**: If occasional `s` bothers too much, consider [following documented advice](https://github.com/echasnovski/mini.nvim/blob/eb19e8442edd63b033c36daf8d29c0158c9f1eb9/doc/mini-surround.txt#L570-L574).

Thanks, I will try the suggestion!

**Comment by echasnovski** [comment]
> > What value of 'timeoutlen' do you have set? See it via `:=vim.o.timeoutlen`.
> 
> 1000

Then inputting any mapping sequence should not have delays more than one second between each adjacent keys. If you press `s` and do nothing for more than a second, it will execute `s`. If you press `<Leader>` and do nothing for more than a second, it will execute the `<Leader>` as is.

This is how Neovim works regarding mappings (without 'folke/which-key.nvim' or 'mini.clue').

**Comment by Lukalukito** [comment]
I haven't reported it yet. I just set notimeout option so it will wait forever for next key( without displaying whichkey) but that's ok for now
