### ISSUE TITLE
Weird conflicting behavior with `dial.nvim`

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#1059]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

I am using `dial.nvim` alongside `mini.clue` and have recently noticed that `<C-a>` in visual mode doesn't work. In normal mode `<C-a>` works, and `<C-x>` work in both modes.

When I comment out `g` triggers, it works again.

I have also opened similar issue with `dial.nvim`: https://github.com/monaqa/dial.nvim/issues/94

MWE:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    "monaqa/dial.nvim",
    {
        "echasnovski/mini.clue",
        opts = function()
            return {
                triggers = {
                    { mode = "n", keys = "g" },
                    { mode = "v", keys = "g" }
                }
            }
        end
    }
}

require("lazy").setup(plugins, { root = root .. "/plugins", })

vim.keymap.set("n", "<C-a>", function()
    print("n <C-a>")
    require("dial.map").manipulate("increment", "normal")
end)
vim.keymap.set("v", "<C-a>", function()
    print("v <C-a>")
    require("dial.map").manipulate("increment", "visual")
end)
vim.keymap.set("n", "<C-x>", function()
    print("n <C-x>")
    require("dial.map").manipulate("decrement", "normal")
end)
vim.keymap.set("v", "<C-x>", function()
    print("v <C-x>")
    require("dial.map").manipulate("decrement", "visual")
end)
```

### Neovim version

0.10.0

**Comment by echasnovski** [comment]
Thanks for the issue!

I believe monaqa/dial.nvim#95 should resolve this. Using `:normal! ...` instead of `:normal ...` is indeed a preferred way to execute some default Normal mode functionality.

Closing as not really an issue with 'mini.clue'.
