### ISSUE TITLE
'MiniPick.builtin.grep_live' with 'rg' not showing any result

### ISSUE THREAD

**Issue by lrntgr** [echasnovski/mini.nvim#1071]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Since commit 42100d8,  the `grep_live` function does not show any item to pick from when using the `rg` tool.  

The bug seems to be introduced by ` '--field-match-separator=\\0'` argument added on line 3224 (in pick.lua): applying 
[42100d8_patch.txt](https://github.com/user-attachments/files/16315694/42100d8_patch.txt) patch is fixing the problem.

### Neovim version

0.10.0

### Steps to reproduce

1. `echo "foo" > bar && nvim bar`
2. Run comand `:lua require('mini.pick').builtin.grep_live({ tool = 'rg' })`
3. Type "foo"

### Expected behavior

   - match line `bar:1:1:foo` is shown
   - Info view indicates:
   ```
   Total items   | 1
   Matched items | 1
   Marked items  | 0
   Current index | 1
   ```

### Actual behavior

   - no match
   - Info view indicates:
   ```
   Total items   | 0
   Matched items | 0
   Marked items  | 0
   Current index | -
   ```

**Comment by lrntgr** [comment]
Actually, the ` --field-match-separator` argument is not recognized by `rg` (?):
```bash
$ rg --version
ripgrep 11.0.2
# ...
$ rg foo --field-match-separator='\0'
error: Found argument '--field-match-separator' which wasn't expected, or isn't valid in this context
# ...
$ rg --help | rg 'field-match'
$ # empty result
```

**Comment by echasnovski** [comment]
Thanks for the issue!

The 11.0.2 version is [almost 5 years old](https://github.com/BurntSushi/ripgrep/releases/tag/11.0.2). Installing newer version should fix this.

That said, adding minimum supported version is probably a good idea.

Closimg as not an issue with  'mini.pick'.

**Comment by echasnovski** [comment]
Minimal supported version seems to be [13.0.0](https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0), which is 3 years old. I think it is old enough to not even be documented.

**Comment by lrntgr** [comment]
> Minimal supported version seems to be [13.0.0](https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0), which is 3 years old. I think it is old enough to not even be documented.

Ubuntu 20.04 LTS package repository is [pointing at 11.0.2](https://packages.ubuntu.com/focal/utils/ripgrep).  
You're right, it's old, but still supported until April 2025: might happen to other users.

**Comment by echasnovski** [comment]
> > Minimal supported version seems to be [13.0.0](https://github.com/BurntSushi/ripgrep/releases/tag/13.0.0), which is 3 years old. I think it is old enough to not even be documented.
> 
> Ubuntu 20.04 LTS package repository is [pointing at 11.0.2](https://packages.ubuntu.com/focal/utils/ripgrep). You're right, it's old, but still supported until April 2025: might happen to other users.

I see, thanks for clarifying.

Although there is nothing wrong in keep using something that is not broken, I think trying to support only the latest LTS version is a better approach here (as is the case with 'mini.deps' and 'mini.diff' which have explicit Git version check to make it work on Ubuntu 22.04). 

Besides, in this particular case there is no reasonable way to support both ":" and "\0" delimiters. Making breaking change is painful, but I believe is necessary here.

**Comment by lrntgr** [comment]
> Although there is nothing wrong in keep using something that is not broken, I think trying to support only the latest LTS version is a better approach here (as is the case with 'mini.deps' and 'mini.diff' which have explicit Git version check to make it work on Ubuntu 22.04).
> 
> Besides, in this particular case there is no reasonable way to support both ":" and "\0" delimiters. Making breaking change is painful, but I believe is necessary here.

Agreed: using a recent version of `rg` is the solution.  
Still, an explicit info would be helpful for the user to understand why `grep_live` is not working:
- a documented minimum version
- a dynamic error message (?)

**Comment by pkazmier** [comment]
I was bit by this today when I upgraded Mini. While I saw the breaking change notices, I was expecting something different, but it did not work. Had I not been subscribed to all mini issues/discussions/etc... I would not have realized it was my version of `rg`, which was this btw:

```
ripgrep 13.0.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

So, I upgraded and life was good again.

```
ripgrep 14.1.0

features:-simd-accel,+pcre2
simd(compile):+SSE2,+SSSE3,-AVX2
simd(runtime):+SSE2,+SSSE3,+AVX2

PCRE2 10.42 is available (JIT is available)
```

**Comment by echasnovski** [comment]
> ```
> ripgrep 13.0.0
> -SIMD -AVX (compiled)
> +SIMD +AVX (runtime)
> ```

This is really strange because 13.0.0 version has necessary option available (judging by the release notes). And as far as I can tell, nothing in newer release notes indicate that its behavior had issues after the initial release.

**Comment by pkazmier** [comment]
So, I just built 13.0.0 from source, to share what I see:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/f74641bf-4d8a-4ec0-8292-d77af9b0c8bb">

Then I built 14.0.0, and it works:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/60d1a1a6-eaa3-4b1a-bf66-0dbab8763bfa">

**Comment by echasnovski** [comment]
> So, I just built 13.0.0 from source, to share what I see:
> ... 
> Then I built 14.0.0, and it works:
> ... 

Ah, I see, thanks! Both the `rg` option and picker work, it's just that 13.0.0 doesn't seem to use "true" null character. I'll take a look, but don't think it will be resolved on 'mini.pick' side.

**Comment by pkazmier** [comment]
To be clear, I was not asking for you to resolve, but I do agree with @lrntgr that something needs to be documented. As I mentioned, I read the commit messages, saw the breaking change this morning, excited to test only to find broken behavior (as I was on 13). My first instinct was to go look at the commit message again to see if I missed something that I was supposed to do—nothing. And it was only because I read all things mini that I saw this thread and knew it had to be my rg version.

**Comment by echasnovski** [comment]
So... After more `man rg` reading, some trial and error later I think there is a more robust way of using the `--field-match-separator` option. Initially 'mini.pick' used `--field-match-separator=\\0` while the `--field-match-separator \\x00` form proved to work starting from `rg` version 13.0.0. This now should be fixed on latest `main`.

@pkazmier, thanks for the initial note about the difference between 13.0.0 and 14.0.0. I wouldn't be comfortable having to strictly rely on 14.0.0 as it was released less than 8 months ago.

That said, I still think that adding that `rg` needs to be at least 13.0.0 is a bit too much because it is more than 3 years old. **If** the minimum version ended up being 14.0.0, then I'd for sure add the version requirement.
