### ISSUE TITLE
Trailspace: make functions available through module

### ISSUE THREAD

**Issue by gsinclair** [echasnovski/mini.nvim#1072]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

trailspace

### Description

When I run `MiniTrailspace.trim()` in my config, the LSP complains that `MiniTrailspace` is an unknown global variable.

It would be nice to be able to do `require('mini.trailspace').trim()` instead.

Hmmmm.... so I just tried it, and I can! Awesome!

So now my feature request is to mention this in the docs.

**Comment by pkazmier** [comment]
It is [documented](https://github.com/echasnovski/mini.nvim/blob/eee6fb8efbeb5d792215de9a0bc9282603aa9fcc/doc/mini.txt#L80) already.

**Comment by gsinclair** [comment]
Thank you!

I have read a *lot* of documentation of specific mini modules, but haven't looked at the overall mini.nvim documentation for a long time.

**Comment by pkazmier** [comment]
> I have read a _lot_ of documentation of specific mini modules

Yes, me too, and I still miss things! 😄

**Comment by echasnovski** [comment]
> When I run `MiniTrailspace.trim()` in my config, the LSP complains that `MiniTrailspace` is an unknown global variable.
> 
> It would be nice to be able to do `require('mini.trailspace').trim()` instead.

Yes, indeed for `MiniTrailspace` to be available, calling module's `setup()` is a must. This is assumed to be the only way to create that global variable.
