### ISSUE TITLE
Support setting 'winbar' option in statusline module

### ISSUE THREAD

**Issue by leath-dub** [echasnovski/mini.nvim#1074]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

statusline

### Description

It would be nice to be able to use the api of `mini.statusline` to set with 'winbar' option.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

If support for 'winbar' will be part of 'mini.nvim', it will be as a separate module. As I think for not trivial cases (like showing only file name in winbar in case of global statusline), data displayed in statusline and winbar are different.

Closing as not planned.
