### ISSUE TITLE
In WSL2 :Git commit results in error in sockconnect

### ISSUE THREAD

**Issue by stkr** [echasnovski/mini.nvim#1078]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.git

### Description

In a wsl2 bash, issuing `:Git commit` from within neovim results in a timeout + sockconnect error after a few seconds.

### Neovim version

0.10.0

### Steps to reproduce

in a wsl2 bash:
```
git init
touch a.txt
git add a.txt
nvim -nu minimal.lua
```
in nvim:
```
:Git commit
```

[minimal.lua.zip](https://github.com/user-attachments/files/16334623/minimal.lua.zip)
[version_info.txt](https://github.com/user-attachments/files/16334571/version_info.txt)
[checkhealth.txt](https://github.com/user-attachments/files/16334560/checkhealth.txt)

### Expected behavior

commit message is opened for editing in existing nvim instance

### Actual behavior

error with the following message is displayed:
```
(mini.git) PROCESS REACHED TIMEOUT
(mini.git) Error detected while processing /tmp/nvim.stefan/erSj6H/0:
line    6:
E5108: Error executing lua Vim:connection failed: connection refused
stack traceback:
^I[C]: in function 'sockconnect'
^I[string ":lua"]:1: in main chunk
```

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I don't have access to Windows machine, so I can not reproduce/debug/fix this. I am afraid the origin of this might be similar to #636, i.e. "pipe" not working on Windows.
At the moment, I am inclined to just document that this 'mini.git' function does not work on Windows and fixing it is welcome. But I'll try to see if I can at least ask somebody to reproduce this.

**Comment by stkr** [comment]
Thanks for the incredibly quick response!

I did a bit more investigations after the hint about pipes. It seems that there is a discrepancy about pipe creation between platforms. On linux, nvim creates a pipe in /run/usr/*/nvim.proc*. On windows, nvim creates a pipe at \\.\pipe\nvim.*, on wsl it does not (v:servername is empty).

However, pipes are workable on wsl2 too, the `:Git commit` command works fine when starting nvim giving a pipe name on command-line with `nvim -nu minimal.lua --listen /tmp/nvim-pipe`. Might be just the default pipe creation is missing in wsl2 build. But I believe that's not a topic for here.

**Comment by echasnovski** [comment]
Hmm... That's an interesting information. To be honest, the whole inter-process cooperation (in any module, not only 'mini.git') was mostly done by trial and error. So I am not sure how to proceed here. Especially without access to WSL2 for me.

If you'll find a reasonable fix that can be applied conditionally on platform (like based on `vim.loop.os_uname()` or similar), I'll gladly add it.

**Comment by stkr** [comment]
Some more googling and experimenting revealed it's actually caused by a WSL bug with permissions/ownership of the run directory: https://github.com/microsoft/WSL/issues/11542, https://github.com/microsoft/WSL/issues/9689, and others. Nvim tries to create the pipe also on WSL but can't for permission problems - the directory where it wants to put the pipe is not accessible.

Nothing at all wrong with the plugin, I guess this can be closed. Sorry for the wrong report, and thanks for the hint with the pipes.

**Comment by echasnovski** [comment]
No problem at all. Thanks for investigating and (more or less) confirming the real issue.

Closing as not a 'mini.git' issue.
