### ISSUE TITLE
Add and aborting mechanism to the `hooks.pre` for `MiniComment`

### ISSUE THREAD

**Issue by RaafatTurki** [echasnovski/mini.nvim#108]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

MiniComment

### Description

Hey, this opens the door to workflows like aborting visual commenting when the start and end of the visual range reside in different filetypes.

The hacky work around would be to return "%s" but that's not actually aborting anything and a change that does nothing gets inserted into the undo history.

I suggest passing an `abort` function into the pre hook, calling it should stop any further code execution:
```lua
  MiniComment.config = {
    hooks = {
      pre = function(abort) end,
    }
  }
```

lmk what you think.

**Comment by echasnovski** [comment]
Interesting idea. Do you often encounter need for this?

I wonder if a better design would be to call hooks safely with `pcall()` and stop further execution in case of an error.

**Comment by RaafatTurki** [comment]
> Interesting idea. Do you often encounter need for this?

Yes I mostly encounter it with filetypes like `svelte`, `vue`, and `html` with embedded `css` or `js`.

> I wonder if a better design would be to call hooks safely with pcall() and stop further execution in case of an error.

Maybe that's a sound choice but that means if I wanted to abort I'd have to cause a error, It's a good thing to have but I don't think it's how we should abort.

**Comment by echasnovski** [comment]
> Yes I mostly encounter it with filetypes like `svelte`, `vue`, and `html` with embedded `css` or `js`.

I see. Do you use something like [JoosepAlviste/nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring)?

> That means if I wanted to abort I'd have to cause a error right?, It's a good thing to have but I don't think it's how we should abort.

That is the idea. The only downside I see to this is that "true" errors will be ignored. At the moment I like this more than calling hooks with arguments.

**Comment by echasnovski** [comment]
> That's my concern as well.
Why is calling a hook with an argument discouraged?
Btw I was the guy who requested passing session data as an argument into session hooks, Did those cause an issue?

Yeah, I remember that. Hello :)
I don't particularly like the idea of supplying an `abort` argument.

Maybe even better idea might be to allow hooks return value. If it is true-ish, then continue execution. Stop otherwise.

**Comment by RaafatTurki** [comment]
Yes I like that more, to better bullet proof this lets have a constant say
```
MiniComment.ABORT = "MiniCommentABORT"
```
And if that's returned we abort.

**Comment by echasnovski** [comment]
> Yes I like that more, to better bullet proof this lets have a constant say
> 
> ```
> MiniComment.ABORT = "MiniCommentABORT"
> ```
> 
> And if that's returned we abort.

That seems to only complicate things without obvious gain. It would make sense to add a specially recognized return value only if something special will be done with it. Having false-ish value mean "stop execution" seems to be good and intuitive enough.

I'll work on this in a couple of days.

**Comment by echasnovski** [comment]
Thanks again for suggestion!
It should be implemented in latest `main`: if hook returns `false` then any further actions are terminated.
