### ISSUE TITLE
mini.hipatterns throws a "buffer not found" error if the buffer no longer exists

### ISSUE THREAD

**Issue by onsatoci** [echasnovski/mini.nvim#1080]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.hipatterns

### Description

An error is thrown if a buffer is deleted before apply_highlighter_pattern callback gets called.

```
Error executing vim.schedule lua callback: .../share/nvim/lazy/mini.hipatterns/lua/mini/hipatterns.lua:1017: Invalid buffer id: 8
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        .../share/nvim/lazy/mini.hipatterns/lua/mini/hipatterns.lua:1017: in function 'get_line'
        .../share/nvim/lazy/mini.hipatterns/lua/mini/hipatterns.lua:945: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Neovim version

0.10.0

### Steps to reproduce

1. create some large files that contain a match: 
```bash
rm /tmp/bigfile1.js /tmp/bigfile2.js; for i in {0..10000}; do echo "function test() { console.log('hello'); }" >> /tmp/bigfile1.js; done; echo "// TODO zzz" >> /tmp/bigfile1.js; cp /tmp/bigfile1.js /tmp/bigfile2.js
```
2. add a keymap to swap between them fast:
```lua
local alter = true
vim.keymap.set("n", "n", function()
  if alter then
    vim.cmd("e /tmp/bigfile1.js")
  else
    vim.cmd("e /tmp/bigfile2.js")
  end
  alter = not alter
  vim.cmd("set bufhidden=wipe")
end)
```
3. spam the key

### Expected behavior

no error

### Actual behavior

yes error

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce (although the error seems to come from not the latest 'mini.hipatterns' version).

There is a [check for valid buffer](https://github.com/echasnovski/mini.nvim/blob/23669ab7abc2cd10f9a5166de07400bb34eaecda/lua/mini/hipatterns.lua#L909) which is done prior to actually adding highlights. Which in some extreme cases seem to be not enough, as later actual highlighting is done separately asynchronously for better non-blocking.

Adding extra check there might be good enough, as it has quite low performance burden.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main` (be sure to update 'mini.nvim' / 'mini.hipatterns').

The repro from this issue also uncovered a similar problem in 'mini.git' for non Git buffers, so double thank you :)
