### ISSUE TITLE
mini.convert plugin to handle conversion of colors between hsv, rgb and hex, conversion of sizes, etc

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1081]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.convert

### Description

Hi again! Is something like https://github.com/cjodo/convert.nvim a valid feature request which can be incorporated as part of the mini.nvim suite.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Although I can see how this can be useful for *some* day-to-day work, this doesn't look like a necessary feature for a good all-round editing experience.

On the other hand, there might be a good place for it in the [planned 'mini.cycle'](https://github.com/echasnovski/mini.nvim?tab=readme-ov-file#planned-modules) (or similar name). I'll try to think about it during that module development (which does not yet have high priority, I am afraid).

Closing as "maybe planned as part of another module".
