### ISSUE TITLE
[mini.git] filetype is set incorrectly for ":Git show"

### ISSUE THREAD

**Issue by dhananjaylatkar** [echasnovski/mini.nvim#1084]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.git

### Description

`:Git show <commit> <file>`
Opens <file> diff at commit but filetype of buffer is set to filetype of input <file>.

Filetype is set to `git` when <file> is not given.

### Neovim version

0.10

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Git show <commit> <file>`

### Expected behavior

"show" buffer should have "git" filetype

### Actual behavior

explained above

**Comment by echasnovski** [comment]
Thanks foe the issue!

I can reproduce. The idea is for `show` to [rely on `vim.filetype.match()`](https://github.com/echasnovski/mini.nvim/blob/657ef75b52a548090fb7906735517b7ddbf39e88/lua/mini/git.lua#L1132), but I *think* there is something strange is going here. I'll take a look.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main`.

It indeed was an issue with filetype detection. It is done *after* buffer name is set which always ends with a Git command used. So in case of `:Git show HEAD file.lua` it had name ending with 'show HEAD file.lua' which `vim.filetype.match()` deduced to be a Lua file. This is a useful behavior in case of command like `:Git show HEAD:file.lua` but indeed is counter-intuitive for `:Git show HEAD file.lua`.

At the same time, the plain `:Git show HEAD` did not match based on buffer name and reached the stage of matching by buffer content to correctly produce "git" filetype. So the rather appropriate solution here seems to force first trying to detect "git" filetype based on the buffer content and only then fall back to `vim.filetype.match()`.
