### ISSUE TITLE
[mini.ai] delete argument does not keep space

### ISSUE THREAD

**Issue by gbcreation** [echasnovski/mini.nvim#109]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

When deleting the last argument of an argument list, the space character before the closing list character is deleted also.

### Neovim version

0.7.2

### Steps to reproduce

With this argument list : `{ a, b }` (`^` is cursor position, `daa` is keymap for delete argument) :

### Expected behavior

```
{ a, b } ==daa==> { a } // OK, space kept after 'a'
     ^
```

### Actual behavior

```
{ a, b } ==daa==> { a} // KO, no space after 'a'
     ^
```

**Comment by echasnovski** [comment]
I thought about this case during implementation. Both then and currently I am not sure if this is a good behavior.

Couple of questions:
- This, of course, should also be the case for the first argument?
- If there is more than one space, would you expect to ignore all of them?
- Would you also expect `vaa` to ignore whitespace?

**Comment by gbcreation** [comment]
> - This, of course, should also be the case for the first argument?

Yes, the first argument should be processed the same way : `{ a, b }` => `{ b }`. 

> - If there is more than one space, would you expect to ignore all of them?

I think it's probably better, yes.

> - Would you also expect `vaa` to ignore whitespace?

Yes

I used Targets.vim previously and it has the following behavior:
- spaces before the first argument are ignored
- spaces after the last argument are ignored
- spaces between arguments are taken into account

Examples:

```
{    a,    b    } ==daa==> {    b    }
     ^

{    a,    b    } ==daa==> {    a    }
           ^

{    a,    b    } ==vaa==> {    a,    b    }
     ^                          ------       // selection

{    a,    b    } ==vaa==> {    a,    b    }
           ^                     ------      // selection
```

**Comment by echasnovski** [comment]
Thanks again for the issue. Should be fixed on latest `main`. It now should ignore left whitespace in first argument, right whitespace on last argument, but include them in case of a single argument (useful to converge into `{}`; use `ia` to not include whitespace).

It proved to be far more challenging than it should be, but I think I managed to find compromise by consciously ignoring one quite rare edge case (whole whitespace last argument, like in `f(xx,   )`).

**Comment by gbcreation** [comment]
That works perfectly. Thank you for the update.

**Comment by tobiwild** [comment]
Hi. Also coming from targets.vim and I noticed that this behaviour is different:

Expected behaviour:
```
{    a,    b    } ==vaa==> {    a,    b    }
     ^                          ------       // selection
```

Behaviour in mini.ai:
```
{    a,    b    } ==vaa==> {    a,    b    }
     ^                          --           // selection
```

So deleting the first argument via `daa` in
```
items = append(items, item)
```
leads to
```
items = append( item)
```
having this would make more sense IMO:
```
items = append(item)
```

**Comment by echasnovski** [comment]
> ...
> leads to
> 
> ```
> items = append( item)
> ```
> 
> having this would make more sense IMO:
> 
> ```
> items = append(item)
> ```

I kind of both agree and disagree. To me, when designing this, an argument is "a region inside balanced bracket between allowed not excluded separators". An `a` version here is an argument with corresponding separator. As there should be symmetry breaking in terms of whitespace, this is a behavior ended up in final version. But I do agree that it is annoying sometimes.

I think there was an attempt to fix this, but I could come up only with such complicated approaches, that I decided to apply KISS here and endure suffering.

**Comment by tobiwild** [comment]
OK, I guess I‘ll get used to it, thanks!

**Comment by tobiwild** [comment]
FYI: I am now using the following custom solution:

```lua
local cache = {}

local is_span_inside_spans = function(span, spans)
  for _, s in ipairs(spans) do
    if s[1] <= span[1] and span[1] <= s[2] then
      return true
    end
  end
  return false
end

-- Work with argument textobject ----------------------------------------------
local arg_get_separators = function(s, sep_pattern, exclude_regions)
  -- Get all separators
  local seps = {}
  s:gsub('()%s*' .. sep_pattern .. '%s*()', function(l, r)
    table.insert(seps, { l, r - 1 })
  end)
  if #seps == 0 then
    return { { 1, 1 }, { s:len(), s:len() } }
  end

  -- Remove separators that are in "excluded regions": by default, inside
  -- brackets or quotes
  local forbidden = {}
  local add_to_forbidden = function(l, r)
    table.insert(forbidden, { l + 1, r - 2 })
  end

  for _, pat in ipairs(exclude_regions) do
    local capture_pat = string.format('()%s()', pat)
    s:gsub(capture_pat, add_to_forbidden)
  end

  local res = vim.tbl_filter(function(x)
    return not is_span_inside_spans(x, forbidden)
  end, seps)

  -- Append edge separators. This allows single argument and ensures at least 2 elements.
  table.insert(res, 1, { 1, 1 })
  table.insert(res, { s:len(), s:len() })
  return res
end

local argument = function(opts)
  opts = vim.tbl_deep_extend('force', {
    brackets = { '%b()', '%b[]', '%b{}' },
    separators = { ',' },
    exclude_regions = { '%b""', "%b''", '%b()', '%b[]', '%b{}' },
  }, opts or {})
  local brackets, separators, exclude_regions = opts.brackets, opts.separators, opts.exclude_regions

  if type(opts.brackets) == 'string' then
    opts.brackets = { opts.brackets }
  end
  local separators_esc = vim.tbl_map(vim.pesc, separators)
  local sep_str = table.concat(separators_esc, '')
  local sep_pattern = '[' .. sep_str .. ']'

  local res = {}
  -- Match brackets
  res[1] = brackets

  -- Remove brackets and padding
  res[2] = function(s, init)
    if init > 1 then
      return nil
    end
    local result = { 1, s:len() }
    s:gsub('^.%s*().-()%s*.$', function(l, r)
      result = { l, r - 1 }
    end)
    return result[1], result[2]
  end

  -- Match argument with separators
  res[3] = function(s, init)
    -- Cache string separators per spec as they are used multiple times.
    -- Storing per spec allows coexistence of several argument specifications.
    cache.argument_seps = cache.argument_seps or {}
    cache.argument_seps[res] = cache.argument_seps[res] or {}
    local seps = cache.argument_seps[res][s] or arg_get_separators(s, sep_pattern, exclude_regions)
    cache.argument_seps[res][s] = seps

    -- Return span fully on right of `init`, `nil` otherwise
    -- For first argument returns left bracket; for last - right one.
    for i = 1, #seps - 1 do
      if init <= seps[i][1] then
        return seps[i][1], seps[i + 1][2]
      end
    end

    return nil
  end

  res[4] = {
    '^%s*' .. sep_pattern .. '()%s*().-()' .. sep_pattern .. '()%s*$',
    '^%s*' .. sep_pattern .. '?%s*().-()' .. sep_pattern .. '?%s*$',
  }

  return res
end
```

in

```lua
require('mini.ai').setup({
  n_lines = 500,
  custom_textobjects = {
    a = argument(),
  },
})
```

So this solution always keeps the brackets padding, but captures whitespaces in the argument list.
One downside is when being on a whitespace there are 2 possible arguments which can cover the cursor and I cannot specify the right one (or "best"). But otherwise it feels natural to me.

**Comment by echasnovski** [comment]
> FYI: I am now using the following custom solution:
> ...

Woah, this is **the dedication** right here! Very nice, if it is working for you!
I am somewhat relieved that this code can be processed by someone other than myself :)

> One downside is when being on a whitespace there are 2 possible arguments which can cover the cursor and I cannot specify the right one (or "best"). But otherwise it feels natural to me.

Yeah, I don't think that making it default is good. Maybe in an option somehow?
If you'll have more free time, could you, please, make it in a patch against current 'lua/mini/ai.lua'? I started trying to align them, but there seems to be quite a few minor differences that makes it difficult without knowing which parts actually changed.

**Comment by tobiwild** [comment]
Sure, here are the changes: https://github.com/echasnovski/mini.nvim/pull/187
