### ISSUE TITLE
[mini.files] Case insensitive file name detection

### ISSUE THREAD

**Issue by 0x7a7a** [echasnovski/mini.nvim#1091]
When I create a file, I found that the file with the same name can't be created if the case is different, I briefly tested the `vim.loop.fs_stat` function, and it doesn't seem to recognize the case accurately.

https://github.com/echasnovski/mini.nvim/blob/e24ec1fcf885990fec1a993fe8304a033fd1806d/lua/mini/files.lua#L2356

I'm not sure. Can you check for me?

**Comment by 0x7a7a** [comment]
Sorry, I think I know why, because Mac systems are case-insensitive

**Comment by echasnovski** [comment]
Yep. My first question was going to be about OS. If it is MacOS or Windows, then it is an expected behavior because they ignore case in file system paths.

**Comment by 0x7a7a** [comment]
I'm sorry to bother you with my lowly mistake. Thank you for your reply and your work.

**Comment by echasnovski** [comment]
> I'm sorry to bother you with my lowly mistake. Thank you for your reply and your work.

Ow, no worries whatsoever :)
