### ISSUE TITLE
Mini.Ai: add more options for movement mappings

### ISSUE THREAD

**Issue by heygent** [echasnovski/mini.nvim#1093]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

I'd like to have different mappings to go to the previous or next textobject. For now, mini.Ai only exposes the `goto_left` and `goto_right` options for movement. It would be nice to either have more options, for example relative to search methods:

```lua
goto = {
  next_or_cover = {
    left = 'g[',
    right = 'g]',
  },
  prev_or_cover = {
    left = 'g(',
    right = 'g)'
  }
}
```

The way I'd probably use it would be to map `next_or_cover.left` to `g]` and `prev_or_cover.right` to `g[`, given that I rarely think about which side of the textobject I'm in.

An alternative could be exposing directly the `expr_mapping` function, and allow users to make their own mappings while keeping the base options simpler.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think having these as options is too much. 'mini.ai' already has enough default mappings.

> An alternative could be exposing directly the `expr_mapping` function, and allow users to make their own mappings while keeping the base options simpler.

Its main functionality is exported via [`MiniAi.move_cursor()`](https://github.com/echasnovski/mini.nvim/blob/59ecf78491f29a9ec31f4124f3da77091f37e4d9/doc/mini-ai.txt#L582). It can be used almost as is with help of `vim.fn.getcharstr()` to get textobject identifier from the user. However, covering more quality-of-life features also doesn't look extremely complex to have in one's config:

```lua
local make_ai_move_rhs = function(side, search_method)
  return function()
    local ok, tobj_id = pcall(vim.fn.getcharstr)
    if not ok or tobj_id == '\27' then return end
    local tobj_esc = vim.fn.escape(tobj_id, "'\\")
    local opts = string.format('{ n_times = %d, search_method = "%s" }', vim.v.count1, search_method)
    local cmd = string.format('MiniAi.move_cursor("%s", "a", "%s", %s)', side, tobj_esc, opts)
    return '<Cmd>lua ' .. cmd .. '<CR>'
  end
end

local map_ai_move = function(lhs, side, search_method)
  vim.keymap.set({ 'n', 'x', 'o' }, lhs, make_ai_move_rhs(side, search_method), { expr = true })
end

map_ai_move('g(', 'left', 'cover_or_prev')
map_ai_move('g)', 'right', 'cover_or_prev')
```

Closing as not planned.
