### ISSUE TITLE
When using mini.base16 colorscheme and mini.deps the foreground text is not visible while installing

### ISSUE THREAD

**Issue by nshern** [echasnovski/mini.nvim#1097]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.base16, mini.deps

### Description

When using mini.base16 colorscheme and mini.deps the foreground text is not visible while installing

### Neovim version

NVIM v0.10.1

### Steps to reproduce

1. Use a mini.base16 colorscheme e.g. minicyan
2. Install a new plugin with mini.deps
3. See that the installation text is not visible

### Expected behavior

that the installation text is visible

### Actual behavior

installation text is not visible
<img width="644" alt="Screenshot 2024-07-30 at 22 22 14" src="https://github.com/user-attachments/assets/7debd8be-78f4-4733-9d08-72c8b3e81ed1">

**Comment by echasnovski** [comment]
Thanks for the issue!

The only way I could reproduce this is if there is a `MiniDeps.add()` call executed during startup which leads to installing a plugin. And it doesn't depend on color scheme but on the implementation of `vim.notify` (which is universally used in 'mini.deps' to show these messages). Everything works as expected in case of an interactive `:DepsAdd`.

 My suggestion would be to use a more robust implementation of `vim.notify`. Like, for example, is suggested in ['mini.deps' example 'init.lua'](https://github.com/echasnovski/mini.nvim/blob/691c5f38f575b572d0c857bd22c35be9a1512925/scripts/init-deps-example.lua#L24-L27).

Closing as not an issue (either of 'mini.base16' or 'mini.deps').
