### ISSUE TITLE
[mini.tests] conditional `quit_on_finish` option or API to determine if tests failed?

### ISSUE THREAD

**Issue by mrcjkb** [echasnovski/mini.nvim#1098]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.test

### Description

Hey 👋 

I've been experimenting with combining mini.test with busted. The idea is to use the busted CLI to run tests and invoke mini.tests from a `mini_tests_spec` file.
This allows

- To use both test frameworks (e.g. busted for unit tests and mini.test for integration tests).
- To use mini.test with our [nvim-busted-action](https://github.com/nvim-neorocks/nvim-busted-action).

It works, but I had to [hack into the reporter](https://github.com/nvim-neorocks/busted-interop-examples/blob/d7daad8a564da7eea444dfd6a640db6508d18e5b/mini.test/spec/mini_tests_spec.lua#L8) to make sure I get a non-zero exit code if either of the test suites fail.
Otherwise, a successful mini.test run prevents a failed busted run from exiting with a non-zero code.

It would be nice if there were either

- an API to determine if tests failed 
- a possibility to pass in the `quit_on_finish` option as a function that takes the success or failure as an argument (I can see how this might be unergonomic),
  allowing to only quit on failure. 
- Or, an option to make `quit_on_finish` a union of `boolean` and `"on_failure"`.

What do you think? 
I'd be happy to open a PR if you're open to this 😄

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't really understand the problem. Here are some statements which might clarify things:
- Writing own reporter *is* the suggested way to customize how test execution information is displayed to the user.
- The `gen.reporter.stdout()` reporter does quit on finish. Supplying `quit_on_finish = false` will indeed make it not quit on finish assuming the caller wants to do something else.
- [Examining the state of `cases`](https://github.com/nvim-neorocks/busted-interop-examples/blob/d7daad8a564da7eea444dfd6a640db6508d18e5b/mini.test/spec/mini_tests_spec.lua#L15-L1) *is* the suggested way to extract any information about how tests were executed. This allows for much more flexibility than providing a separate API or a boolean value to, for example, `reporter.finish()`. Couple of things I'd change in the code itself:
    - There is seemingly no need to track `has_fails` in `update()`. The same can be done in `finish()`.
    - I'd save `cases` inside `reporter.start()`. Same way as is [done in `gen_reporter.stdout()`](https://github.com/echasnovski/mini.nvim/blob/691c5f38f575b572d0c857bd22c35be9a1512925/lua/mini/test.lua#L987).

Does this clarify the situation?

**Comment by mrcjkb** [comment]
Thanks for the response.

> [Examining the state of cases](https://github.com/nvim-neorocks/busted-interop-examples/blob/d7daad8a564da7eea444dfd6a640db6508d18e5b/mini.test/spec/mini_tests_spec.lua#L15-L1) is the suggested way to extract any information about how tests were executed.

This is what I had tried, initially, but I was trying to use `MiniTest.current.all_cases`, which didn't seem to work.
Thanks for the recommendation. That works too.

> Does this clarify the situation?

Yes. Closing :smile:
