### ISSUE TITLE
return keyword in mini.base16

### ISSUE THREAD

**Issue by sohamshanbhag** [echasnovski/mini.nvim#1102]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.base16

### Description

The `return` keyword in mini.base16 is assigned to `base08`, shouldn't keywords be assigned to `base0E` according to https://github.com/chriskempson/base16/blob/main/styling.md? I have red mapped to `base08`, since `base08` is used for lsp errors. Should errors and the return keyword have the same color?

### Neovim version

0.10.1

### Steps to reproduce

NA

### Expected behavior

`return` should be mapped to `base08`

### Actual behavior

`return` is mapped to `base0E`.

**Comment by echasnovski** [comment]
This is deliberate to make `return` keyword stand out. All other keywords use `base0E`.
