### ISSUE TITLE
[mini.jump2d] Lua mappings for start_jumping_forwards and start_jumping_backwards

### ISSUE THREAD

**Issue by KohlJary** [echasnovski/mini.nvim#1104]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump2d

### Description

I would like to be able to map separate bindings for jumping forwards and backwards within the lua setup function (I.E. s for jump forwards, S for jump backwards). I was able to accomplish this via vimscript, but it would be nice to be able to have all of my mini mappings contained within my mini.nvim setup file.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The design of 'mini.jump2d' and `require('mini.jump2d').setup()` will remain the same: single mapping defined in `setup()` with the suggestion to create separate mappings if users want them.

Closing as not planned.
