### ISSUE TITLE
Italic options for mini.hues

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#1106]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.hues

### Description

It might be nice idea, to add a configuration option to enable some italic highltight groups in mini.hues. Probably not as a default, but having some things like Comments or such in optional italic fonts can look nice. I'm currently doing this manually with overwriting highlight groups, but it think this could be a popular option.
![image](https://github.com/user-attachments/assets/a78c7831-aa31-478d-ae7b-74aac9c53600)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I personally don't really like italic font variants, so it won't be part of config, sorry. Manually making target highlight groups (which users want) to be italic is the suggested approach here. This can be achieved by `vim.cmd.highlight('Comment gui=italic')`, for example. Or with the approach shown in screenshot, which is more versatile indeed.

Closing as not planned.
