### ISSUE TITLE
mini.files to work better without acd

### ISSUE THREAD

**Issue by mjrogozinski** [echasnovski/mini.nvim#1108]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

When acd it turned off (`:set noacd`), the explorer (`:lua MiniFiles.open()`) is open in cwd (`:lua print(vim.fn.getcwd())`).
It would be nice to have an option to navigate to the folder of the last buffer.

Scenario:
1. `:set noacd`
2. navigate to a file in a different folder
3. `:lua MiniFiles.open()`
4. press backspace to reset, the explorer will point at the original cwd
5. press q to close the explorer
6. `:lua MiniFiles.open()`
7. the explorer will open in the original cwd, not in the folder of the current buffer

The desired behaviour is:
7. the explorer opens in the folder of current buffer
or
7. press some key, similarly to `<BS>` to navigate to the folder of the current buffer

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is already possible through the [`path`](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/doc/mini-files.txt#L655) argument of `open()`. In particular, [supplying path to current buffer](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/doc/mini-files.txt#L644-L645) will open directory of current file focused on the file. This can be made more streamlined with a custom mapping.

Closing as already possible.
