### ISSUE TITLE
Mini-jump configuration

### ISSUE THREAD

**Issue by justEstif** [echasnovski/mini.nvim#111]
Hello, 

I have found your mini.jump to be a great alternative to other plugins of its type. 

In the doc, there are two functions: `MiniJump.on_cursormoved()` and `MiniJump.stop_jumping()` that I want to apply together. 
Basically, I want mini-jump to prompt for a new search on cursor moved, are there any working example for this functionality? I tried, but there was very little code in the doc to start with. 

In addition, is there any way to implement a prev-search `prev_jump = ','`?

Thank you again for the great plugin.

**Comment by echasnovski** [comment]
Hi!

'mini.jump' implements five different mappings for initiating and performing jumps: `f`, `t`, `F`, `T`, and `;`. The idea is to start jumping with one of those (for example, `f`), type character to which user wants to jump (for example, `e`), and then keep jumping with one of those five keys. So like `feffFF` will initiate forward inclusive jumping to character `e`, repeat two those jumps, the perform two backward jumps.

To answer your questions:
- I am not sure that you *really* want prompt for a new search on cursor moved. It will basically disable any other operation in Normal mode. `MiniJump.on_cursormoved()` is exported only to be used inside module's autocommand to reset jumping state. It shouldn't be used directly.
- No, no reverse jump. The idea is for users to reverse jumping direction by typing same letter in another case: if jumping with `f`, then type `F` and keep jumping with `F`.

**Comment by justEstif** [comment]
Thank you for replying so quickly,

I didn't realize you could use 'f' to jump the next match. That was great to learn. I think I will be able to think of another keybinding to use instead of ';'. 

I will mark this as closed, as that is a solution to the problem I had.
