### ISSUE TITLE
Add git log --graph functionality like rbong/vim-flog

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1112]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.git

### Description

Hi! Is it possible to integrate a feature like a pretty git log graph in the same way as rbong/vim-flog does it. I feel like this would be a killer feature to mini.git.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is out of scope for 'mini.git'. The best solution I can suggest is `:Git --oneline --graph` with possibly hand-crafted pretty formatting.

Closing as not planned.
