### ISSUE TITLE
Strange `gs` mapping with `Sleep` comment

### ISSUE THREAD

**Issue by dzirtusss** [echasnovski/mini.nvim#1113]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

There is a strange `gs` mapping described as `Sleep` in `mini.clue` source code. But there is no such mapping in any "standard nvim" or even "mini" setups. Most probably some copy-pasting form local. However, this makes me wonder are there any similar bugs? I mean similar misleading mappings that don't exist.

### Neovim version

0.10

### Steps to reproduce

https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/clue.lua#L748 or search "Sleep" in `mini.clue` code.

### Actual behavior

There should be no `gs` mapping. Maybe other mappings need a quick sanity look as well.

**Comment by rafikdraoui** [comment]
This is a built-in mapping in Neovim. See [`:help gs`](https://neovim.io/doc/user/various.html#gs).

I believe most people remap it to something else, since it's hard to come up with a reason why anyone would want to use the default sleep behaviour in normal mode :slightly_smiling_face:

**Comment by dzirtusss** [comment]
Oops, sorry. Please close

**Comment by echasnovski** [comment]
> But there is no such mapping in any "standard nvim" or even "mini" setups. Most probably some copy-pasting form local. However, this makes me wonder are there any similar bugs? I mean similar misleading mappings that don't exist.

Please, verify such claims before opening an issue.
