### ISSUE TITLE
Invalid `cwd` passed to `H.git_cli_output` in `MiniGit.show_at_cursor` temporarily hangs Neovim

### ISSUE THREAD

**Issue by rafikdraoui** [echasnovski/mini.nvim#1114]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.git

### Description

When `MiniGit.show_at_cursor` is called inside a `minigit://*` buffer and makes it to the "show range history" section of the code, the `cwd` argument to `H.git_cli_output` in [the definition of `is_in_git`](https://github.com/echasnovski/mini.nvim/blob/42a58673bc86359b006f83fecd971ecb95ee8bf8/lua/mini/git.lua#L333-L335) is `"minigit://n"` (where `n` is a number).

This ends up making the git command hang until `config.job.timeout` milliseconds have elapsed, when an error is raised (by default, this is 30 seconds).

### Neovim version

0.10.1

### Steps to reproduce

1. `:lua require("mini.git").setup()`
1. `:Git show`
1. `:lua MiniGit.show_at_cursor()`

### Expected behavior

1. The UI doesn't block
1. A message saying "Nothing Git-related to show at cursor" (or similar) is displayed

### Actual behavior

The UI blocks for 30 seconds. It can be recovered with `ctrl-c`, but then 30 seconds later an error message will still be displayed.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce. It should now be resolved on latest `main`.
