### ISSUE TITLE
(misc): `setup_termbg_sync` breaks firenvim

### ISSUE THREAD

**Issue by TheLeoP** [echasnovski/mini.nvim#1115]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.misc

### Description

Using `setup_termbg_sync` alongside firenvim breaks the latter because how it's designed to communicate with the browser.

My feature request is to add a FAQ or mention of taking this into account for end users of mini.misc.

Said FAQ could mentoin that to solve this issue a user simply has to conditionally enable `setup_termgb_sync` only if the current Neovim session hasn't been started by firenvim:

```lua
    if not vim.g.started_by_firenvim then require("mini.misc").setup_termbg_sync() end
```

Or do you think this should be mentioned on the firenvim side?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The general idea of the note about when it should be used sounds reasonable. I thought that having the mention of "terminal emulator" would be enough, but it might not be. There is now a [dedicated note](https://github.com/echasnovski/mini.nvim/blob/af673d8523c5c2c5ff0a53b1e42a296ca358dcc7/doc/mini-misc.txt#L187) on latest `main`.

Mentioning any specific cases of when *not* to call it (like when Firenvim is used, etc.) seems to be too much.

**Comment by echasnovski** [comment]
@TheLeoP, while reading some unrelated parts of Neovim help, I noticed that there seems to be an automated way to make `setup_termbg_sync()` do nothing if Neovim is started not in compatible way. So I think guarding behind `vim.g.started_by_firenvim` should not be necessary anymore (at least it is not needed for Neovide and VS Code Neovim extension).

**Comment by TheLeoP** [comment]
Thanks for the heads up :D. Could you link/mention the tag of the relevant part of the Neovim help?
