### ISSUE TITLE
Follow global system-wide dark mode preference 

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1116]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

misc

### Description

**Hello o/**

Starting with https://github.com/echasnovski/mini.nvim/commit/d1d950c00eb247cdedf6e03f7c58e305b8fc7b72, mini.nvim now introduce synchronization between neovim background and the terminal. I propose that we follow through by introducing synchronization for system-wide dark mode preferences:

https://github.com/user-attachments/assets/5ea633be-e732-4a23-a323-12e6f9d15c4b

# 

In general, each system offers a way to query its dark mode preference:

**Linux:**
- Using `org.freedesktop.appearance.color-scheme`, which is managed by [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/blob/main/data/org.freedesktop.impl.portal.Settings.xml#L34).

**Windows:**
- Using `reg.exe` to query `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize`

**MacOS:**
- Using `defaults read -g AppleInterfaceStyle`

### Example:

> [!IMPORTANT]  
> For the sake of this example, we are continuously polling org.freedesktop.appearance; implementations should consider using interrupts instead.

```lua
local timer = vim.fn.timer_start(
  2000,
  function()
    vim.fn.jobstart(
      table.concat(
        {
          "dbus-send --session --print-reply=literal --reply-timeout=1000",
          "--dest=org.freedesktop.portal.Desktop",
          "/org/freedesktop/portal/desktop",
          "org.freedesktop.portal.Settings.Read",
          "string:'org.freedesktop.appearance'",
          "string:'color-scheme'",
        },
        " "
      ),
      {
        stdout_buffered = true,
        on_stdout = function(_, res)
          local color_scheme = string.match(res[1], "uint32 1") ~= nil and "dark" or "light"
          if vim.o.background ~= color_scheme then
            vim.o.background = color_scheme
          end
        end,
      }
    )
  end,
  { ["repeat"] = -1 }
)
```
### Bonus (randomhue)

https://github.com/user-attachments/assets/4c6b1627-d88e-4d83-8f89-355cfae8c25e

**Comment by echasnovski** [comment]
Thanks for the suggestion!

At the moment I don't really the idea for at least these reasons:
- It depends on OS dependent tools, which 'mini.nvim' tries to avoid. Not only because "dependency is bad", but also due to implementation and maintenance complications.
- Implementation indeed seems to be either constant rate polling or something more complex. Both options are not good.

I'll give it some thought, but at the moment it doesn't look like a good fit for 'mini.nvim'.

**Comment by echasnovski** [comment]
I am afraid I am more inclined to close this for the same reasons described in previous comment. Thanks for the suggestions, though!

**Comment by echasnovski** [comment]
I am afraid, this is not something that I think would justify all the code/doc/test/maintenance complexity.
