### ISSUE TITLE
mini.splitjoin - Golang requires an additional `,` on the last argument

### ISSUE THREAD

**Issue by svartkanin** [echasnovski/mini.nvim#1117]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.splitjoin

### Description

In Golang when a split of arguments is donw it will correctly put each argument on a new line, e.g. 
```
func test(
	a int,
	b int,
	c int
) {

```
But Golang requires the last argument to be suffixed with a `,` to compile, so the correct split should result in 
```
func test(
	a int,
	b int,
	c int,
) {
```

### Neovim version

NVIM v0.10.0

### Steps to reproduce

1. `mkdir test && cd test && go mod init test.com`
2. `touch main.go`
3. 
```
package main

func test(a int, b int, c int) {
	println("test")
}

func main() {
	test(1, 2, 3)
}
```

4. Put cursor inside `test(...)` params and execute the mini.splitjoin 

### Expected behavior

Formatting should be 
```
func test(
	a int,
	b int,
	c int,
) {
```

`c int,` needs the trailing `,` at the end for it to compile

### Actual behavior

```
func test(
	a int,
	b int,
	c int
) {
```

**Comment by echasnovski** [comment]
This (not adding trailing comma) is the default behavior. Customizing it for specific languages is left to users. The dedicated customization approach is via [hooks](https://github.com/echasnovski/mini.nvim/blob/af673d8523c5c2c5ff0a53b1e42a296ca358dcc7/doc/mini-splitjoin.txt#L214) with [built-in `gen_hooks` table](https://github.com/echasnovski/mini.nvim/blob/af673d8523c5c2c5ff0a53b1e42a296ca358dcc7/doc/mini-splitjoin.txt#L357) containing several most common cases. Handling of trailing comma included.

This is use case can be resolved by creating '~/.config/nvim/after/ftplugin/go.lua' with the following content:

```lua
if _G.MiniSplitjoin ~= nil then
  local gen_hook = MiniSplitjoin.gen_hook
  local parens = { brackets = { '%b()' } }

  -- Add trailing comma when splitting inside parenthesis
  local add_comma_parens = gen_hook.add_trailing_separator(parens)

  -- Delete trailing comma when joining inside parenthesis
  local del_comma_parens = gen_hook.del_trailing_separator(parens)

  vim.b.minisplitjoin_config = {
    split = { hooks_post = { add_comma_parens } },
    join = { hooks_post = { del_comma_parens } },
  }
end
```

**Comment by svartkanin** [comment]
Aahh perfect thanks for the quick reply
