### ISSUE TITLE
cursorword: Error with binary data in file

### ISSUE THREAD

**Issue by tbsmark86** [echasnovski/mini.nvim#112]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.cursorword

### Description

I get an error when moving the cursor over binary data especially null bytes (`^@`)

I've tryed this:
``` 
 local status, res = pcall(vim.fn.match(curchar, '[[:keyword:]]'))  
  if status then  
    return res >= 0  
  end  
  return false  
```
but the the error is still there?

### Neovim version

0.7.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. require('mini.cursorword').setup({})
3. create zip with uncompressed text data
4. remove .zip extension
5. open
6. move around

### Expected behavior

error free

### Actual behavior

```
E5108: Error executing lua Vim:E976: using Blob as a String  
stack traceback:  
        [C]: in function 'match'  
        ...nvim/pack/packer/start/mini.nvim/lua/mini/cursorword.lua:280: in function 'is_cursor_on_keyword'  
        ...nvim/pack/packer/start/mini.nvim/lua/mini/cursorword.lua:138: in function 'auto_highlight'  
        [string ":lua"]:1: in main chunk  
```

**Comment by echasnovski** [comment]
You have just won "The most unusual issue yet" award! :joy:
The problem seems to be that cursor is positioned on multibyte character which is not fetched correctly. I'll think about a proper way to deal with this.

Meanwhile, you can use a slightly modified version of your code (which threw error because call is executed *before* going into `pcall`):
```lua
  local ok, res = pcall(vim.fn.match, curchar, '[[:keyword:]]')
  return ok and res >= 0
```

**Comment by echasnovski** [comment]
Should be fixed on latest `main`. Thanks for the issue!

**Comment by tbsmark86** [comment]
Works, thanks.
