### ISSUE TITLE
mini.clue default bindings support

### ISSUE THREAD

**Issue by doomgutt** [echasnovski/mini.nvim#1121]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Is there or will there be support for default keybindings (e.g. `d` or `y`) and something like a `g?` for exploring all Normal mode keybindings? It might be an issue with my setup but I couldn't find any information on this in the docs or anywhere online.

Thanks.

**Comment by echasnovski** [comment]
The design of 'mini.clue' is pretty much established. It implements a custom key query process that narrows down mappings and/or user clues for the same mode. Here is [a help entry](https://github.com/echasnovski/mini.nvim/blob/d8faae693d266ee4f3a2bf1fb7ca4bc81314c3e9/doc/mini-clue.txt#L169-L171).

Setup of 'mini.clue' is intentionally opt-in, i.e. users need to explicitly set up which clues they want to show. Here is [an example if you don't know where to start](https://github.com/echasnovski/mini.nvim/blob/d8faae693d266ee4f3a2bf1fb7ca4bc81314c3e9/doc/mini-clue.txt#L241-L284). For example, it defines `g` as trigger and after pressing `g` shows all built-in mappings that start with it (including `g?`; you may need to scroll the clue window with default `<C-d>`).

The `d` and `y` are operators which change mode from Normal to Operator-pending and wait for keys in *that* mode. Showing clue window right after Neovim starts waiting for a textobject/motion was considered, but did not really fit the 'mini.clue' implementation. See #1008.

**Comment by doomgutt** [comment]
Thanks for the detailed answer and pardon the clumsy post - still a bit new to GitHub.
