### ISSUE TITLE
mini.statusline: disable statusline per buffer

### ISSUE THREAD

**Issue by aarnphm** [echasnovski/mini.nvim#1125]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

I'm thinking `mini.statusline` can support similar feature from `lualine` `disabled_filetype` and `disabled_buftype` for setting statusline.

This might be a bit hard since lualine manage buffers and render statusline by themselves, whereas afaik mini.statusline uses `vim.o.statusline` (Please do correct me if I'm wrong).

**Comment by echasnovski** [comment]
All 'mini.nvim' modules can be disabled per buffer my setting `vim.b.minixxx_disable` buffer-local variable to `true` (that is, if disabling module per buffer even makes sense). This is [documented](https://github.com/echasnovski/mini.nvim/blob/d8faae693d266ee4f3a2bf1fb7ca4bc81314c3e9/doc/mini-statusline.txt#L70-L76). For automated disabling, see [recipes](https://github.com/echasnovski/mini.nvim/blob/d8faae693d266ee4f3a2bf1fb7ca4bc81314c3e9/doc/mini.txt#L335).

This approach was chosen **specifically** to not have to implement all kinds of `disable_*` config entries.
