### ISSUE TITLE
mini.git: when visiting the diff file of HEAD, `show_at_cursor()` opens the current file instead of a snapshot

### ISSUE THREAD

**Issue by milanglacier** [echasnovski/mini.nvim#1126]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.git

### Description

Currently `mini.git` opens a snapshot of the related file when visiting a `diff` buffer.

I am wondering if when the diff is from the `HEAD`, e.g. `git diff`, or `git diff --HEAD`, then we can directly open the file so that we can review the diff and make the edit directly. This is a very convenient feature.

Thanks for your  awesome plugin, and consideration for this feature request.

Best!

**Comment by echasnovski** [comment]
If I understand correctly, this is currently (kind of?) possible. If you execute `:Git diff` or `:Git diff HEAD`, then `show_at_cursor()` **will** show the file at the proper state. This was possible since [almost the very release of 'mini.git'](https://github.com/echasnovski/mini.nvim/commit/7b0e9733b99c1aeab19bcc2721ce48e89c5e3228).

**Comment by milanglacier** [comment]
Hi, I think this is not exactly the same:

<img width="464" alt="Screenshot 2024-08-08 at 03 20 01" src="https://github.com/user-attachments/assets/ebc074ed-2a9c-4083-89bd-8348977dd4ec">

This is the snapshot of the HEAD of file, not the buffer associating with the file itself, so you cannot directly edit that buffer to change the file.

**Comment by echasnovski** [comment]
> This is the snapshot of the HEAD of file, not the buffer associating with the file itself, so you cannot directly edit that buffer to change the file.

This is not a snapshot from the HEAD, but from the actual worktree (same *content* as you get from `:edit lua/minuet/config.lua`).

But I get what you mean, you can not use it to directly edit the file on the disk. This is rather deliberate because if it *is* editable, then the diff might get outdated and this is slightly confusing.

To actually edit the file, you can navigate to the closest from top file name (like a line '+++ b/lua/minuet/config.lua') and execute `gf` on the file part. I think even a custom function in this case can be rather concise.

**Comment by milanglacier** [comment]
Thanks, I completely understand your choice of designing the API and want to make behaviors consistent. And I also agree that I can create a customize function to do the things easily.

There’s one thing I would like to request so that I do not need to copy paste a lot of the code to do the things:

I just read the source code and find that `H.diff_pos_to_source` is the key function to get the file name when you are navigating a diff entry. Could you consider make it a public API so that I can get the buffer file name when the cursor is on a diff line so I can make my custom function open that file directly?

**Comment by echasnovski** [comment]
> There’s one thing I would like to request so that I do not need to copy paste a lot of the code to do the things:
> 
> I just read the source code and find that `H.diff_pos_to_source` is the key function to get the file name when you are navigating a diff entry. Could you consider make it a public API so that I can get the buffer file name when the cursor is on a diff line so I can make my custom function open that file directly?

Sorry, I don't exporting it is a good idea.

Here is I'd do it without that function:

```lua
local compute_diff_path = function()
  local pattern = '^%+%+%+ b/(.*)$'
  for i = vim.fn.line('.'), 1, -1 do
    local path = vim.fn.getline(i):match(pattern)
    if path ~= nil then return path end
  end
end

local compute_diff_lnum = function()
  local i, offsets = vim.fn.line('.'), { [' '] = 0, ['-'] = 0, ['+'] = 0 }
  while i > 0 do
    local prefix = vim.fn.getline(i):sub(1, 1)
    if not (prefix == ' ' or prefix == '-' or prefix == '+') then break end
    offsets[prefix] = offsets[prefix] + 1
    i = i - 1
  end

  local hunk_start_after = string.match(vim.fn.getline(i), '^@@ %-%d+,?%d* %+(%d+),?%d* @@')
  if hunk_start_after == nil then return end
  return math.max(1, tonumber(hunk_start_after) + offsets[' '] + offsets['+'] - 1)
end

local edit_path_at_cursor = function()
  local path, lnum = compute_diff_path(), compute_diff_lnum()
  if not (path and lnum) then return vim.notify('Could not find both path and line', vim.log.levels.WARN) end
  vim.cmd('vertical split ' .. vim.fn.fnameescape(path))
  vim.api.nvim_win_set_cursor(0, { lnum, 0 })
end

vim.keymap.set('n', '<Leader>gS', edit_path_at_cursor)
```

**Comment by milanglacier** [comment]
Thank you! This solution works perfectly for me. Your productivity is impressive!
