### ISSUE TITLE
mini.starter fuzzy find

### ISSUE THREAD

**Issue by 22ispencer** [echasnovski/mini.nvim#1127]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter, mini.fuzzy?

### Description

Currently, the mini.starter query only matches if you type verbatim the start of the link you want to select. I think that it's a decent idea to enable fuzzy finding for these entries (especially since the mini.fuzzy module exists).

Ex:
- Help.md
- **Hello_World.md** <-

(mini.starter) Query: hewo

**Comment by echasnovski** [comment]
Thanks for the suggestion!

[It is intentionally not supported](https://github.com/echasnovski/mini.nvim/blob/d8faae693d266ee4f3a2bf1fb7ca4bc81314c3e9/doc/mini-starter.txt#L39) to reduce complexity.

Closing as not planned.
