### ISSUE TITLE
Cannot select or filter LSP document/workspace symbols

### ISSUE THREAD

**Issue by linhns** [echasnovski/mini.nvim#1129]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.extra, mini.pick

### Description

Inconsistent behavior for different scopes of `MiniExtra.pickers.lsp`.  While `refrences` works as expected, `workspace_symbol` and `document_symbol` cannot be matched/selected.

### Neovim version

0.10.1

### Steps to reproduce

1. Set up `mini.pick` and `mini.extra` as standalone plugins with [lazy.nvim](https://github.com/folke/lazy.nvim) as in the [document](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-extra.md#installation).
2. Configure any LSP server using [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)
3. Try to pick LSP symbols and references, then try to move up/down or enter some characters.

### Expected behavior

`workspace_symbol` and `document_symbol` scopes can be fuzzy-matched/selected similar to `references`.

### Actual behavior

Pressing any key close the floating window.

https://github.com/user-attachments/assets/0254fdc8-77cc-428e-bdeb-f2c90464a42f

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce while being pretty sure that this is not a 'mini.nvim' issue, but rather a conflict with some other plugin. If there are a reproduction steps with only 'mini.nvim' modules installed (and, say, 'nvim-lspconfig' with LuaLS configured as a language server), I'll take a closer look

**Comment by echasnovski** [comment]
I've just noticed from video replay that you seem to have 'mini.icons' installed (with probably executed `MiniIcons.tweak_lsp_kind()`), but there is no highlighting. I do get conflicting default icon and highlighting in this case (as entries with tweaked `vim.lsp.protocol.CompletionItemKind` are not recognized in `MiniIcons.get()`), which I'll try to fix that soon-ish. Still, no such behavior as on video.

**Comment by echasnovski** [comment]
> I do get conflicting default icon and highlighting in this case (as entries with tweaked `vim.lsp.protocol.SymbolKind` are not recognized in `MiniIcons.get()`), which I'll try to fix that soon-ish.

This should now be resolved on latest `main`. `pickers.lsp` with 'document_symbol' and 'workspace_symbol' scopes now properly work after `MiniIcons.tweak_lsp_kind()` (no extra icon yet proper highlighting). Maybe this will also fix the issue in the original comment.

**Comment by linhns** [comment]
Thanks for fixing, however I completely overhaul my Neovim config to use `MiniDeps` as the main plugin manager (I like the vim-plug declaration style). The problem does not appear anymore so I suspect a possible loading order issue with `lazy`, which is too complex under the hood to understand. 

Btw, thank you for the work on `mini.nvim`, the modules are just brilliant and hands down the best I have ever used.
