### ISSUE TITLE
New mini.cmdline module to show UI like folke/noice.nvim

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1132]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cmdline

### Description

Hi echasnovski! Is it possible to include a UI for commandline like noice.nvim does. It would be really cool if that is added to mini.nvim.
Also a ui for vim.input would be cool as well.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> Is it possible to include a UI for commandline like noice.nvim does. It would be really cool if that is added to mini.nvim.

I would like to have this implemented but the current state of Neovim API is that doing so robustly requires **a lot** of hacks.

There are vague plans to update Neovim itself to make this type of task easier, but I am not sure what is the progress there. So much so, that I am fairly confident to close this issue as "There is no good support for this in Neovim itself". If/when there is a development in that area, I'll revisit this.
