### ISSUE TITLE
mini.files doesn't follow symlinks

### ISSUE THREAD

**Issue by flexagoon** [echasnovski/mini.nvim#1139]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When a file is a symlink, mini.files doesn't open it

### Neovim version

Nightly v0.11.0-dev+599-g8df6736ca

### Steps to reproduce

1. Create a symlink
2. Try to open it with mini.files

### Expected behavior

The target file of the symlink opens

### Actual behavior

Nothing happens

**Comment by echasnovski** [comment]
Thanks for the issue!

Wow, indeed I can reproduce. It is rather strange because it works with symlinked directories (which I mostly have to deal with). I'll take a look.

**Comment by echasnovski** [comment]
On a second note, I'd like to ask for some clarifications.

I did indeed manage to reproduce it with the following setup (on Linux in zsh):
- `echo "File original" > file-orig`
- `mkdir dir`
- `ln -s file-orig dir/file-linked`

Then after navigating to 'dir' directory, there is both no preview of 'file-linked' (although it is present) and it is not opened. The reason for that is that the file path is resolved as '/dir/file-orig', which is indeed not present on file system. You can verify it with `:=vim.fn.resolve('dir/file-linked')` (should print 'dir/file-orig') and `:=vim.uv.fs_stat('dir/file-linked')` (which should print `nil` and an error that file does not exist).

On the other hand, if symbolic link is created to the full path, everything works as expected. That is, after `ln -s $(pwd)'/file-orig' dir/file-linked2`, everything works as expected for 'dir/file-linked2' file.

So I'd like to ask how exactly did you create symlinks? If via linking *to* relative path, then it seems to be not a good way. Another confirmation of this is that Neovim's built-in `:edit` doesn't recognize 'dir/file-linked' but recognized 'dir/file-linked2'.

**Comment by flexagoon** [comment]
@echasnovski Yes, I created the symlinks using a relative file path. Could that perhaps be an upstream bug if the `:edit` command doesn't work with it either?

Also, in case it matters, I got this issue while managing files on a mounted ssh server (I guess it uses sshfs but I'm not sure how Gnome does stuff). Though I don't think this is relevant to the issue since you're able to reproduce in on a local filesystem.

**Comment by echasnovski** [comment]
> Could that perhaps be an upstream bug if the `:edit` command doesn't work with it either?

It is certainly possible, however it is not only `:edit` that behaves this way but also `vim.uv.fs_stat()` doesn't recognize these "relative symlinks" as paths that actually exist on disk. As both of these come from different parts of software with long history of widespread use and tests, I'd say this is intentional.

On latest `main` this case at least results into a notification which shows information about *why* there is nothing happening. I think this is the best 'mini.files' can do here.
