### ISSUE TITLE
mini.pick: Cursor disappears when switching files using picker

### ISSUE THREAD

**Issue by abeldekat** [echasnovski/mini.nvim#1149]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Since [this](https://github.com/echasnovski/mini.nvim/commit/0c5f49e349539aebba7384a2ede7b22ecffbaa7e) commit, the cursor disappears when switching from file a to file b using mini.pick.

I tested with an [older](https://github.com/echasnovski/mini.nvim/commit/49e2699dc0d585b445eda24ed4bb45952ac20508) commit, and the cursor does not disappear.

### Neovim version

0.10.1

### Steps to reproduce

Open neovim and open a file. Cursor is visible.
Now, use pick.files to open another file. Cursor disappears.

### Expected behavior

Cursor does not disappear...;)

### Actual behavior

Cursor disappears

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce (because I of course tested this prior). I'd need to ask for more details of the setup and actual steps (is just `:Pick files` and `<CR>`?). For instance:
- What is the value of `guicursor` option before and after?
- What OS, terminal emulator?

**Comment by abeldekat** [comment]
Os: Arch linux
Terminal: Alacritty and tmux

The guicursor: 

```lua
vim.opt.guicursor = ""
```

**Comment by echasnovski** [comment]
> The guicursor:
> 
> ```lua
> vim.opt.guicursor = ""
> ```

This is the problem, as it should probably not be that way (it more or less means "disable cursor"). Is there a reason you use it this way (I presume from `vim.cmd('set guicursor=')`?

**Comment by echasnovski** [comment]
I'll look more closely on the weekend. In the meantime, having `vim.o.guicursor = 'a:block'` seems to give the same cursor styling effect but without disappearing cursor.

**Comment by abeldekat** [comment]
If I remember correctly:

1. I use zsh vim mode extensively. Somehow, terminal outside vim behaved differently than terminal inside vim. 
2. I vaguely remember a Neovim issue where the terminal cursor was changed when closing Neovim.
3. I saw that ThePrimeagen uses this setting. It took some time getting used to the cursor always having the same shape. Now I like the consistency.

**Comment by abeldekat** [comment]
> I'll look more closely on the weekend. In the meantime, having vim.o.guicursor = 'a:block' seems to give the same cursor styling effect but without disappearing cursor.

Thanks!

**Comment by abeldekat** [comment]
Regarding the Neovim issue: I think it was [this](https://github.com/neovim/neovim/issues/21480#issuecomment-1360746259) one.

**Comment by echasnovski** [comment]
> Regarding the Neovim issue: I think it was [this](https://github.com/neovim/neovim/issues/21480#issuecomment-1360746259) one.

I *think* this was a suggestion to use `set guicursor=` inside autocommand for `VimLeave`. The cursor links to a [FAQ entry](https://neovim.io/doc/user/faq.html#faq-general) which in fact suggests `au VimLeave,VimSuspend * set guicursor=a:block-blinkon0`.

**Comment by echasnovski** [comment]
With some dirty hack taken [from 'folke/noice.nvim'](https://github.com/folke/noice.nvim/blob/448bb9c524a7601035449210838e374a30153172/lua/noice/util/hacks.lua#L176-L178), this should now be resolved on latest `main`. But to reiterate, I don't think using `vim.o.guicursor = ''` as the main option value is a good idea to begin with.

**Comment by abeldekat** [comment]
Thanks!

As per your suggestion, I now use `vim.o.guicursor = 'a:block'`. I don't see any difference, and vim mode inside terminal is still working as before, so I will keep that setting.
