### ISSUE TITLE
mini.git: add `--stat --patch` to `show_at_cursor()`

### ISSUE THREAD

**Issue by milanglacier** [echasnovski/mini.nvim#1150]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

git

### Description

When reviewing the commit details by `show_at_cursor()`, it would be better we can also include `--stat` option (and consequently `--patch` is also need to included) so that when reviewing the commit, we can have a summary stat to know what files are changed and how many lines are changed.

This is my proposed change. But I am not sure if there are any other places which are also need to updated so I created an issue rather than submitting a PR directly.

```diff
 lua/mini/git.lua | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lua/mini/git.lua b/lua/mini/git.lua
index 40a6f78..754213c 100644
--- a/lua/mini/git.lua
+++ b/lua/mini/git.lua
@@ -317,7 +317,7 @@ MiniGit.show_at_cursor = function(opts)
   local is_commit = string.find(cword, '^%x%x%x%x%x%x%x+$') ~= nil and string.lower(cword) == cword
   if is_commit then
     local split = H.normalize_split_opt((opts or {}).split or 'auto', 'opts.split')
-    local args = { 'show', cword }
+    local args = { 'show', '--stat', '--patch', cword }
     local lines = H.git_cli_output(args, cwd)
     if #lines == 0 then return H.notify('Can not show commit ' .. cword, 'WARN') end
     H.show_in_split(split, lines, 'show', table.concat(args, ' '))

```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I personally don't think `--stat` is that much useful to be included by default. I'll take some time to probably reconsider, though.

In the meantime I can suggest using custom mapping with `<Cmd>Git show --stat --patch <cword><CR>` as right hand side to achieve this.

**Comment by echasnovski** [comment]
After thinking about it a bit more and trying to observe how I look at commit information in LazyGit, the commit statistics indeed seems to be useful. Pity that it does not get highlighted inside "git" filetype, but it still is useful for an overview for commit impact.

This should be resolved on latest `main`. Thanks again for the suggestion!
