### ISSUE TITLE
mini.diff reset hunk when invoked does not track cursor position.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1154]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.diff

### Description

Hi echasnovski! So I have this issue where if I reset a line hunk using gHH, it resets but puts the cursor at another line instead of the line where the hunk was reset. Is it possible to save the hunk line location and put the cursor back in the same line in any way.

### Neovim version

NVIM v0.11.0-dev-632+g33464189b

### Steps to reproduce

1. In a git tracked directory, if you reset hunk with gHH, the hunk resets but the cursor is put in a different line than the line where the hunk is located.

### Expected behavior

The cursor should be put in the same line after the hunk is reset.

### Actual behavior

The cursor is put in a random line after the hunk is reset.

**Comment by echasnovski** [comment]
`gHH` in fact consists from two parts: `gH` operator and `H` motion (see `:h H`). So it resets lines from current and up until the first visible ("top") line. As executing operator places cursor at the start of its target, cursor is moved to the top line.

If you want to resent current hunk, use `gHgh` (`gH` operator + `gh` textobject). If you want to reset current line, use `gH_` (`gH` operator + `_` textobject).
