### ISSUE TITLE
mini.undotree

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1155]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.undotree

### Description

Hi again. I just wanted to conform if something like [mbbill/undotree](https://github.com/mbbill/undotree) can be considered part of neovim. Also I apologize for raising too many issues 🙏🙏🙏.

**Comment by echasnovski** [comment]
No worries about the amount of issues :) Not duplicating module suggestions, feature requests, or bug reports are completely fine.

I've thought about that while briefly using it. For me the actual tree visualization is rarely useful (if at all).

Most of the time I wanted to have a more "linear" undo history: traverse through the states as they appeared chronologically (i.e. in order they actually appeared). Here is how the idea for the [undo target of 'mini.bracketed'](https://github.com/echasnovski/mini.nvim/blob/d6e6a6fb010cc452b491704aa9ecc96a8aa2cde1/doc/mini-bracketed.txt#L446) was born. With this already in place I don't think 'mini.undotree' is on the horizon.

Closing as not planned.
