### ISSUE TITLE
mini.regex, mini.startuptime, mini.indentlines, mini.rainbow

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1157]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

Hi! So I am on my way to create a new config entirely with mini.nvim. I wanted to know if few of these plugins and features can be added if you think they are a good fit.

[folke/ts-comments.nvim](https://github.com/folke/ts-comments.nvim)
Can configuration to add new comments for filetypes which do not have comment strings defined be supported by mini.comment.

https://github.com/dstein64/vim-startuptime
Can something which can show and analzye startup time be added to mini.nvim suite and if possible be show as part of mini.starter dashboard. Also can it be extended to show load times of every plugin via mini.deps.

https://github.com/nvimdev/indentmini.nvim
This is something similar to https://github.com/lukas-reineke/indent-blankline.nvim altough this plugin adds the extmarks for indentlines in just around 100 to 130 lines of code. Can this be done in mini.nvim in any way possible.

https://gitlab.com/HiPhish/rainbow-delimiters.nvim
Most colorschemes dont highlight parenthesis, curly brackets, square brackets by default separately. Can these be highlighted via mini.hipatterns in any way or if not can this be supported as a additional plugin.

https://github.com/bennypowers/nvim-regexplainer
Can something like this be added as part of mini.nvim. It would be really helpful if we could get the explanation of what a regex does like this plugin functionality shows.

**Comment by echasnovski** [comment]
Thanks for the suggestions!

> [folke/ts-comments.nvim](https://github.com/folke/ts-comments.nvim) Can configuration to add new comments for filetypes which do not have comment strings defined be supported by mini.comment.

If some filetypes don't have proper 'commentstring' set, it can be done so by the user inside autocommand for `FileType` event. Alternatively, there is `config.hooks.pre` inside which ['commentstring' can be set](https://github.com/echasnovski/mini.nvim/blob/d6e6a6fb010cc452b491704aa9ecc96a8aa2cde1/doc/mini-comment.txt#L152).

> https://github.com/dstein64/vim-startuptime Can something which can show and analzye startup time be added to mini.nvim suite and if possible be show as part of mini.starter dashboard. Also can it be extended to show load times of every plugin via mini.deps.

I think once in a while running `nvim --startuptime ~/nvim.log` and then inspecting '~/nvim.log' file is good enough.

> https://github.com/nvimdev/indentmini.nvim This is something similar to https://github.com/lukas-reineke/indent-blankline.nvim altough this plugin adds the extmarks for indentlines in just around 100 to 130 lines of code. Can this be done in mini.nvim in any way possible.

There is [mini.indentscope](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-indentscope.txt) for that. Showing all indent guides looks too noisy for my taste.

> https://gitlab.com/HiPhish/rainbow-delimiters.nvim Most colorschemes dont highlight parenthesis, curly brackets, square brackets by default separately. Can these be highlighted via mini.hipatterns in any way or if not can this be supported as a additional plugin.

I generally don't really like the idea of rainbow-ing repetitive objects (brackets, delimiters, indent guides, etc.). So I don't think this will be supported as a separate module.

Off the top of my head, I also don't think this can be done with 'mini.hipatterns'.

> https://github.com/bennypowers/nvim-regexplainer Can something like this be added as part of mini.nvim. It would be really helpful if we could get the explanation of what a regex does like this plugin functionality shows.

This seems to be too niche, complex, and not really enhancing editing experience.

------

As a side note, not everything should/will be implemented as 'mini.nvim' module. At the moment, [this is a list of planned modules](https://github.com/echasnovski/mini.nvim?tab=readme-ov-file#planned-modules) plus maybe a couple more that I didn't add there (because they are a "maybe").

------

Closing as not planned.

**Comment by 231tr0n** [comment]
> n

One small doubt, like is just highlighting parenthesis, square and curly braces with only a single color possible using mini.hipatterns.

**Comment by 231tr0n** [comment]
> Thanks for the suggestions!
> 
> > [folke/ts-comments.nvim](https://github.com/folke/ts-comments.nvim) Can configuration to add new comments for filetypes which do not have comment strings defined be supported by mini.comment.
> 
> If some filetypes don't have proper 'commentstring' set, it can be done so by the user inside autocommand for `FileType` event. Alternatively, there is `config.hooks.pre` inside which ['commentstring' can be set](https://github.com/echasnovski/mini.nvim/blob/d6e6a6fb010cc452b491704aa9ecc96a8aa2cde1/doc/mini-comment.txt#L152).
> 
> > https://github.com/dstein64/vim-startuptime Can something which can show and analzye startup time be added to mini.nvim suite and if possible be show as part of mini.starter dashboard. Also can it be extended to show load times of every plugin via mini.deps.
> 
> I think once in a while running `nvim --startuptime ~/nvim.log` and then inspecting '~/nvim.log' file is good enough.
> 
> > https://github.com/nvimdev/indentmini.nvim This is something similar to https://github.com/lukas-reineke/indent-blankline.nvim altough this plugin adds the extmarks for indentlines in just around 100 to 130 lines of code. Can this be done in mini.nvim in any way possible.
> 
> There is [mini.indentscope](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-indentscope.txt) for that. Showing all indent guides looks too noisy for my taste.
> 
> > https://gitlab.com/HiPhish/rainbow-delimiters.nvim Most colorschemes dont highlight parenthesis, curly brackets, square brackets by default separately. Can these be highlighted via mini.hipatterns in any way or if not can this be supported as a additional plugin.
> 
> I generally don't really like the idea of rainbow-ing repetitive objects (brackets, delimiters, indent guides, etc.). So I don't think this will be supported as a separate module.
> 
> Off the top of my head, I also don't think this can be done with 'mini.hipatterns'.
> 
> > https://github.com/bennypowers/nvim-regexplainer Can something like this be added as part of mini.nvim. It would be really helpful if we could get the explanation of what a regex does like this plugin functionality shows.
> 
> This seems to be too niche, complex, and not really enhancing editing experience.
> 
> As a side note, not everything should/will be implemented as 'mini.nvim' module. At the moment, [this is a list of planned modules](https://github.com/echasnovski/mini.nvim?tab=readme-ov-file#planned-modules) plus maybe a couple more that I didn't add there (because they are a "maybe").
> 
> Closing as not planned.

@echasnovski, One small doubt, like is just highlighting parenthesis, square and curly braces with only a single color possible using mini.hipatterns.

**Comment by echasnovski** [comment]
> @echasnovski, One small doubt, like is just highlighting parenthesis, square and curly braces with only a single color possible using mini.hipatterns.

Depending on what exactly you want, it might be possible, but I don't think 'mini.hipatterns' is a good tool for this. I'd adjust `Deliimiter` highlight group or only `@punctuation.bracket` for tree-sitter powered highlighting (see `:h treesitter-highlight-groups` for full list).

**Comment by 231tr0n** [comment]
> > @echasnovski, One small doubt, like is just highlighting parenthesis, square and curly braces with only a single color possible using mini.hipatterns.
> 
> Depending on what exactly you want, it might be possible, but I don't think 'mini.hipatterns' is a good tool for this. I'd adjust `Deliimiter` highlight group or only `@punctuation.bracket` for tree-sitter powered highlighting (see `:h treesitter-highlight-groups` for full list).

Yup thank you soo much!!!

**Comment by ronisbr** [comment]
Just for the record, the startup time can be "more or less" obtained by the following method:

1. Add this to the very first line of your `init.lua`:

```lua
_G.__nvim_start_time = (_G.__nvim_start_time or vim.uv.hrtime())
```

2. On your mini.starter configuration, add the following function to generate the footer:

```lua
    local function mini_starter_footer()
      local tbl_footer = {}

      -- Startup Time ----------------------------------------------------------------------

      if not _G.__nvim_startup_time then
        local started = _G.__nvim_start_time
        if not started then return "" end
        local dt_ns = vim.uv.hrtime() - started
        local ms = math.floor(dt_ns / 1e6 + 0.5)
        _G.__nvim_startup_time = ms
      end

      table.insert(tbl_footer, string.format("Startup : %d ms", _G.__nvim_startup_time))

      -- Footer ----------------------------------------------------------------------------

      return "\n" .. table.concat(tbl_footer, "\n")
    end
```

3. Finally, create a command to refresh mini.starter when the event `UIEnter` triggers:

```lua
    vim.api.nvim_create_autocmd(
      "UIEnter",
      {
        once     = true,
        callback = function() MiniStarter.refresh() end,
      }
    )
```

In this case, you will have something like this:

<img width="1173" height="1115" alt="Image" src="https://github.com/user-attachments/assets/ac7b9b13-a76f-4763-90c5-8d2fd5638c05" />
