### ISSUE TITLE
ASCII glyphs for 'init.lua' and 'README.md' are not displayed correctly in mini.files

### ISSUE THREAD

**Issue by bluerev** [echasnovski/mini.nvim#1161]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files mini.icons

### Description

Specifically, files titled 'README.md' and 'init.lua', instead being preceded by a corresponding glyph, are preceded by a '/' (e.g. instead of 'I init.lua' it displays '/init.lua', which in turn makes mini.files behave problematically, as after editing or creating a file in the same folder, it treats '/init.lua' as a directory.

I was able to mitigate this by explicitly defining glyphs in mini.icons' configuration:

```lua
opts = {
    style = "ascii",
    file = {
        README = { glyph = "R" },
        ["README.md"] = { glyph = "R" },
        ["README.txt"] = { glyph = "R" },
        ["init.lua"] = { glyph = "I" },
    },
},
```

What makes me think that this is an odd interaction specifically between mini.files and mini.icons is the fact that all glyphs show correctly within other plugins (e.g. fzf-lua).

### Neovim version

0.10.1

### Steps to reproduce

1. Create a file with mini.files in a folder that contains an 'init.lua' and/or 'README.md'
2. Synchronize changes

### Expected behavior

1. File is created
2. Other files and folders remain intact

### Actual behavior

1. File is created
2. Other files preceded by / get moved to a new folder with empty title (e.g. /init.lua gets moved to '  '/init.lua)

**Comment by echasnovski** [comment]
Oh, wow, I indeed can reproduce this. Thanks for the issue! I'll take a look.

**Comment by echasnovski** [comment]
This now should be fixed on latest `main`. Thanks again for noticing!

**Comment by bluerev** [comment]
Works great, thank you!
