### ISSUE TITLE
`mini.operators` replace until end of line

### ISSUE THREAD

**Issue by Susensio** [echasnovski/mini.nvim#1165]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.operators

### Description

I'm trying to keymap `S` to _replace until end of line_ just like `Y` does for _yanking_, but I cannot get it to work

### Neovim version

v0.10.1

### Steps to reproduce

```lua
vim.keymap.set("n", "S", require("mini.operators").replace().."$", { expr = true, replace_keycodes = false })
```

### Expected behavior

Given
https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/lua/mini/operators.lua#L460-L468
and
https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/lua/mini/operators.lua#L548
I should be able to make an expression mapping for _replace until eol_  with the above code

### Actual behavior

`E15: Invalid expression: "<80><fd>hechon ""^Mg@$"`

**Comment by echasnovski** [comment]
I'd suggest using keymap with `remap = true`: `vim.keymap.set('n', 'S', 'gr$', { remap = true })`
