### ISSUE TITLE
Add border options for mini.completion

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1168]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

I had another feature request about mini.completion. 
Is it possible to set border configuration for the wildmenu used by mini.completion?
If not can it be integrated into mini.completion in any way? 
If that is not possible, can you suggest some hacky way in which I can get borders around it.
Also does mini.completion wildmenu color not change according to mini.hues and mini.base16?

**Comment by echasnovski** [comment]
If by "wildmenu" you mean popup with all completion candidates, then I am afraid adding border to it it is not possible. It uses built-in completion menu which doesn't have this property. See #741.

> Also does mini.completion wildmenu color not change according to mini.hues and mini.base16?

Its colors are defined by a set of `PMenu*` highlight groups which [are defined](https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/lua/mini/hues.lua#L480-L487).

------

Closing as not (currently) possible and duplicate.
