### ISSUE TITLE
[mini.extra] Picker for LSP code actions

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#1169]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick, mini.extra

### Description

A picker for `vim.lsp.buf.code_action` would be very useful. Was it not included for a specific reason?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yeah, I can see how this can be useful. And yes, it indeed was not included because `vimi.lsp.buf.code_action()` doesn't support `on_list` option which allows customizing behavior of how returned items are processed. All other scopes [rely on that](https://github.com/echasnovski/mini.nvim/blob/71b5694a2df4f7e3661855eb8e2814980d2e0ac9/doc/mini-extra.txt#L599-L601) and including one more with different implementation feels a bit too much.

Closing as not planned.

**Comment by ndavd** [comment]
Thanks for the reply! So it's not straightforward at all if I wanted to implement it for myself, right?

**Comment by echasnovski** [comment]
I don't really use it, so can't give a reasonable estimate.

After looking at it for a bit, it seems that calling `vim.lsp.buf.code_action()` already should work as it uses `vim.ui.select()` function. However, it seems to work with default `vim.ui.select()` but not with `vim.ui.select = MiniPick.ui_select`. I'll take a look.

**Comment by ndavd** [comment]
Thanks a lot! You're great

**Comment by echasnovski** [comment]
I am not sure what was that earlier, but calling `vim.lsp.buf.code_action()` should work out of the box with 'mini.pick' if you have `vim.ui.select = MiniPick.ui_select` override. Here is the demo:

https://github.com/user-attachments/assets/3a0469da-a941-43f7-ae29-c2d517c28edd

Preview won't really be useful, but I think that should be fine/expected.

**Comment by ndavd** [comment]
How would that work if I want to have it set to a custom mapping?

Example:
```lua
    pick.registry.lsp_references = function()
      extra.pickers.lsp({ scope = 'references' })
    end
    vim.keymap.set('n', ',r', pick.registry.lsp_references)
```

**Comment by ndavd** [comment]
Ah sorry, I misread. That's actually even better, I didn't know mini.pick had that. Then I can even probably just keep the mappings on the LSP side, nice!

**Comment by echasnovski** [comment]
> How would that work if I want to have it set to a custom mapping?
> 
> Example:
> 
> ```lua
>     pick.registry.lsp_references = function()
>       extra.pickers.lsp({ scope = 'references' })
>     end
>     vim.keymap.set('n', ',r', pick.registry.lsp_references)
> ```

There is no need to create a custom registry entry specifically for that mapping. It is enough to do something like this:

```lua
vim.keymap.set('n', ',r', '<Cmd>Pick lsp scope="references"<CR>')
```

That's what [I use](https://github.com/echasnovski/nvim/blob/0a8c9664f0c3d42f0ac912d530d9dd46ee6ae95e/src/mappings-leader.lua#L72).
