### ISSUE TITLE
Write module: buffer manager

### ISSUE THREAD

**Issue by Betelgeuse1** [echasnovski/mini.nvim#117]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

telescope

### Description

First, congrats on mini, really **really** impressive project !

I'm not a fan of having a tabline. So when using lunarvim, I disabled bufferline and went with <S-{h,l}> for buffer control + telescope for accessing already opened buffers and non-open files.
I first thought I should make my own, less "_bloated_", configuration + custom plugins for statusline and buffer management. 
As I started my project, I ran into yours. Mini.nvim directly spoke to me with its lightweight, handmade aspect and philosophy. 

I would love to contribute by writing this plugin, with following functionalities:
- floating menu to select buffers:
    - Either by using j,k,<Enter>
    - Or with hop like access where each buffer is assigned a custom letter
        > a |  first_file.lua
        > d |  second_file.lua
- floating menu with unopened file in current directory (same selection method as previous menu)
    - possibility to set a depth in configuration
    - possibility to blacklist certain files/directories
- remapping for buffer navigation (imo leader based is better)
    |keymap | leader based keymap | command                                          |
    |-----------|-------------------------------|-------------------------------------------------|
    | \<S-l\>  |  \<leader\>bh              |  :bn                                                    |
    | \<S-h\> |  \<leader\>bl               |  :bp                                                    |
    | \<C-b\> |  \<leader\>bb              | :MiniBuffers.open_select_buffer()     |
    | \<C-f\>  |  \<leader\>bf               | :MiniBuffers.open_new_buffer()        |

**Comment by echasnovski** [comment]
Thanks for kind words! And for opening an issue to discuss before actually making a PR. And for contribution suggestion.

I am really not sure about this at the moment. Here are my thoughts:
- The best way of buffer switching to me is indeed with `:Telescope buffers`.
- The best way of buffer switching without dependencies is `:nnoremap <F5> :buffers<CR>:buffer<Space>` (taken from [here](https://vim.fandom.com/wiki/Easier_buffer_switching)). It will show all non-hidden buffers and prompt for buffer number input. It is very simple but really powerful. Not quite a selection with letters, but a very good simplicity/outcome trade-off.
- I plan the 'mini.filetree' which will show file tree with possibility to open buffers. Not in the near future, but definitely is planned.
- I also plan a module which will make some kind of opinionated settings and mappings. It will probably have mappings for `:bn` and `:bp`.

So all in all, every suggested functionality is either a very simple to add to personal config or planned in other modules. Lets leave this open for some time, I'll think more about it.

**Comment by Betelgeuse1** [comment]
Yeah, definitely understand your point, will see in the future. Thanks for reading and considering it anyway (and for `:nnoremap <F5> :buffers<CR>:buffer<Space>`)

**Comment by matu3ba** [comment]
I think to estimate better the use cases, it would help to provide guidelines or a plugin how to create and read scratch buffers (not backed by file or stored in /tmp) for users and convert them to notes (backed by file).
And to have a simple way to attach unique names (per cwd) to buffers + look them up.

The code is not particular complex, but having not return value from the uri functions is annoying, because it requires to store duplicates of all paths and loop through the current one:
```lua
M.makeScratch = function(scratchpath)
  local uri = vim.uri_from_fname(scratchpath)
  local bufnr = vim.uri_to_bufnr(uri)
  vim.bo[bufnr].bufhidden = ""
  vim.bo[bufnr].buflisted = true
  vim.bo[bufnr].buftype = "nofile"
  vim.bo[bufnr].readonly = false
  vim.bo[bufnr].swapfile = false
end

-- :ls! to list all bufs
-- TODO: store and load scratch/notes files
-- scratch -> notes (persistent)
-- make neovim instance
M.makeFileScratch = function(filepath)
--M.makeNamedScratch = function(filepath, scratchname)
  -- local bufs = vim.api.nvim_list_bufs()
  --for i, v in ipairs(bufs) do
  --  if(vim.api.nvim_buf_get_name(v) == "abspath_tocompare") then
  --    print("matching comparison")
  --  end
  --  print(k, ", ", v)
  --end
  local uri = vim.uri_from_fname(filepath)
  local bufnr = vim.uri_to_bufnr(uri)
  vim.bo[bufnr].bufhidden = ""
  vim.bo[bufnr].buflisted = true
  vim.bo[bufnr].buftype = ""
  vim.bo[bufnr].readonly = false
  vim.bo[bufnr].swapfile = false
  return true
end
```

harpoon is basically this + storing and reloading as/from json with the absolute path taken, a bunch of wrappers to send things to those buffers and doing this based on the numbering in 2 scratch buffers (files and terminals) [+ storing into backed file].

I dont think json is necessary and sending stuff does not sound complicated either.

**Comment by echasnovski** [comment]
> I think to estimate better the use cases, it would help to provide guidelines or a plugin how to create and read scratch buffers (not backed by file or stored in /tmp) for users and convert them to notes (backed by file).
> And to have a simple way to attach unique names (per cwd) to buffers + look them up.

I am not sure I follow.

Here is the way to create new scratch buffer:
```lua
local new_scratch_buffer = function()
  local buf = vim.api.nvim_create_buf(true, true)
  vim.api.nvim_win_set_buf(0, buf)
end
```

The idea is to quickly save scratch buffer to a file system? Like 'scratch_1' or 'scratch_2' in the current directory? After they are saved, I don't think they should be treated as scratch buffers.

**Comment by matu3ba** [comment]
Agreed, they look much simpler.

> The idea is to quickly save scratch buffer to a file system?

The idea is to have a lib to manage a buffer, lets call it "master buffer", which controls all buffers and has `bufnr user_alias absolute_path/uri/scratch` as internal state preferring the most explicit representation, if possible.
As of now, there is no way to annotate a scratch buffer with additional info for convenient search and user-defined strategy to cleanup buffers (by grouping them).

**Comment by echasnovski** [comment]
> The idea is to have a lib to manage a buffer, lets call it "master buffer", which controls all buffers and has bufnr user_alias absolute_path/uri/scratch as internal state preferring the most explicit representation, if possible.
As of now, there is no way to annotate a scratch buffer with additional info for convenient search and user-defined strategy to cleanup buffers (by grouping them).

Oh, I see. So, something like [elihunter173/dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim), but for listed buffers. Interesting. I'll have this in mind.

**Comment by echasnovski** [comment]
I think I'll close this for reasons explained in [my initial answer](https://github.com/echasnovski/mini.nvim/issues/117#issuecomment-1224040356).
