### ISSUE TITLE
Add options to toggle default plugins of vim like gzip, compiler in mini.basics

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1171]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.basics

### Description

Hi echasnovski! Is it possible to add options to disable default plugins loaded in vim like and more if any of them are missing in the list.
```
                "2html_plugin",
                "tohtml",
                "getscript",
                "getscriptPlugin",
                "gzip",
                "logipat",
                "netrw",
                "netrwPlugin",
                "netrwSettings",
                "netrwFileHandlers",
                "matchit",
                "tar",
                "tarPlugin",
                "rrhelper",
                "spellfile_plugin",
                "vimball",
                "vimballPlugin",
                "zip",
                "zipPlugin",
                "tutor",
                "rplugin",
                "syntax",
                "synmenu",
                "optwin",
                "compiler",
                "bugreport",
```
Also it would be really helpful if the default plugins which are not used much like tutor, zip, etc which are not used much be disabled by default.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Some of them might be useful to people: like 'tutor' for newcomers (as 'mini.basics' is more or less targeted for them) and 'matchit'. So the interface will be mostly the same as if disabling them manually, which I don't think is a good design.

Closing as not planned.
