### ISSUE TITLE
mini.hues: Strikethrough does not work in Markdown files using Treesitter

### ISSUE THREAD

**Issue by oskarkook** [echasnovski/mini.nvim#1174]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.hues

### Description

To have strikethrough work using Treesitter in Markdown files, I have to do:

```lua
vim.api.nvim_set_hl(0, '@markup.strikethrough', { link='@text.strike' })
```

### Neovim version

0.10.1

### Steps to reproduce

- Install nvim-treesitter
- `require('mini.hues').setup()`
- Open a Markdown file
- Insert: `~~test~~`

### Expected behavior

The line will have strikethrough applied on it.

### Actual behavior

No strikethrough.

**Comment by oskarkook** [comment]
This line is the issue: https://github.com/echasnovski/mini.hues/blob/0e46bdc04d3df4185097ecff08ad208868572b98/lua/mini/hues.lua#L810

**Comment by echasnovski** [comment]
Thanks the issue and finding the cause!

This should be resolved on latest `main`.
