### ISSUE TITLE
:DepsListPlugins to list all installed plugins.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1176]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.deps

### Description

Hi echasnovski! I wanted to know if there is anyway with which I can list all the installed plugins with mini.deps. Is something like that possible in any way or if not, can it be supported.

**Comment by echasnovski** [comment]
Yes, it is possible with [`get_session()`](https://github.com/echasnovski/mini.nvim/blob/2c55015a518e11ea9d49bb96078f5ede51f5d2af/doc/mini-deps.txt#L534). If you want *any* possibly loadable plugin, inspect runtime paths for native packages.

**Comment by 231tr0n** [comment]
@echasnovski is it possible to add some command like ``:DepsListPlugins`` to mini.deps if possible for showing all plugins in a neat manner like when we use ``:DepsUpdate``.

**Comment by echasnovski** [comment]
Sure, it is possible, but I don't much point in it. `:DepsUpdate` already has such view. In case of no internet, there is [`:DepsUpdateOffline`](https://github.com/echasnovski/mini.nvim/blob/2c55015a518e11ea9d49bb96078f5ede51f5d2af/doc/mini-deps.txt#L317). To not apply updates, close the window without writing the buffer.
