### ISSUE TITLE
Issue with insert mode in mini.files when configuring height of window

### ISSUE THREAD

**Issue by adriankarlen** [echasnovski/mini.nvim#1179]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When using `MiniFilesWindowUpdate`-event to update window height via config, the cursor placement hops back when inserting first letter if the window height is configured to be larger than the file list. I've recorded the issue.

https://github.com/user-attachments/assets/e137829f-60a6-4f6a-9b9c-fde6232e5662

The issue does not appear when the filelist is larger than the configured height.

I've tested it with only this event in my config.

### Neovim version

0.10.1

### Steps to reproduce

1. add the following event:
```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "MiniFilesWindowUpdate",
  callback = function(args)
    local config = vim.api.nvim_win_get_config(args.data.win_id)
    config.height = 15
    vim.api.nvim_win_set_config(args.data.win_id, config)
  end,
})
```
2. Open mini.files, and navigate to an directory with fewer than 15 entries.
3. Create a new file.

### Expected behavior

If I type `hello.lua`, it should become the file name.

### Actual behavior

The file name becomes `ello.luah`

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce. Will look into it.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.
