### ISSUE TITLE
Add pickers for LSP Incoming and Outgoing Calls

### ISSUE THREAD

**Issue by linhns** [echasnovski/mini.nvim#1180]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.extra, mini.pick

### Description

Hi @echasnovski, I've been using the LSP picker of **mini.extra** and are really happy about it. Since incoming and outgoing calls have Neovim API support, would it be possible to add support for these 2 features for the LSP picker?

After browsing the code for this picker and the Neovim docs, it seems to me that the reason these are not implemented is due to `vim.lsp.buf.incoming_calls()` not allowing to pass an `opts` table like that of `vim.lsp.buf.references()`, and `opts.on_list` is used to start the picker. Similarly for `vim.lsp.buf.outgoing_calls()`. In this case, would it be possible to adopt some part of [Trouble](https://github.com/folke/trouble.nvim/blob/6efc446226679fda0547c0fd6a7892fd5f5b15d8/lua/trouble/sources/lsp.lua#L229)'s implementation?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> After browsing the code for this picker and the Neovim docs, it seems to me that the reason these are not implemented is due to `vim.lsp.buf.incoming_calls()` not allowing to pass an `opts` table like that of `vim.lsp.buf.references()`, and `opts.on_list` is used to start the picker. Similarly for `vim.lsp.buf.outgoing_calls()`. In this case, would it be possible to adopt some part of [Trouble](https://github.com/folke/trouble.nvim/blob/6efc446226679fda0547c0fd6a7892fd5f5b15d8/lua/trouble/sources/lsp.lua#L229)'s implementation?

Yes, indeed, `MiniExtra.pickers.lsp()` only supports scopes which have the same "hook" interface (`opts.on_list`) in built-in `vim.lsp.buf.xxx()` function. I am afraid this won't change as it would require adding more code to already crowded 'mini.extra'.

Closing as not planned.

**Comment by linhns** [comment]
@echasnovski Since you are a major contributor to the official Neovim project as well, do you think adding hook support to Neovim API is a good idea? This will allow all these calls to have a coherent interface. For me, I don't see why not.

**Comment by echasnovski** [comment]
> @echasnovski Since you are a major contributor to the official Neovim project as well, do you think adding hook support to Neovim API is a good idea? This will allow all these calls to have a coherent interface. For me, I don't see why not.

Maybe it is a good idea, but I'd imagine if it is reasonable there would be a support already. Not sure.

Also, I try to stay away from LSP and tree-sitter if possible (as they tend to be complicated and tiresome to deal with). So probably won't help you here, sorry.
