### ISSUE TITLE
Open file explorer via cmdline

### ISSUE THREAD

**Issue by Edgar200021** [echasnovski/mini.nvim#1182]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

How can I open file explorer with cmdline ? I need it for another plugin (alpha.nvim).

**Comment by echasnovski** [comment]
There is [`MiniFiles.open()`](https://github.com/echasnovski/mini.nvim/blob/b5ee41d2b8ab54f8b6b383b488e822c5cc431871/doc/mini-files.txt#L660) Lua function. So something like `lua MiniFiles.open()`.

**Comment by Edgar200021** [comment]
> There is [`MiniFiles.open()`](https://github.com/echasnovski/mini.nvim/blob/b5ee41d2b8ab54f8b6b383b488e822c5cc431871/doc/mini-files.txt#L660) Lua function. So something like `lua MiniFiles.open()`.

does not work through cmdline

**Comment by echasnovski** [comment]
> > There is [`MiniFiles.open()`](https://github.com/echasnovski/mini.nvim/blob/b5ee41d2b8ab54f8b6b383b488e822c5cc431871/doc/mini-files.txt#L660) Lua function. So something like `lua MiniFiles.open()`.
> 
> does not work through cmdline

It does:

https://github.com/user-attachments/assets/9a78f6a0-8b30-49a6-b909-3cd50577ba99

If not, maybe there needs to be special handling in 'alpha.nvim'. Or maybe 'mini.files' is lazy loaded and there is no `MiniFiles` at the point of execution. Hard to tell without more info.

**Comment by Edgar200021** [comment]
> > > There is [`MiniFiles.open()`](https://github.com/echasnovski/mini.nvim/blob/b5ee41d2b8ab54f8b6b383b488e822c5cc431871/doc/mini-files.txt#L660) Lua function. So something like `lua MiniFiles.open()`.
> > 
> > 
> > does not work through cmdline
> 
> It does:
> minifiles-cmdline.mp4
> 
> If not, maybe there needs to be special handling in 'alpha.nvim'. Or maybe 'mini.files' is lazy loaded and there is no `MiniFiles` at the point of execution. Hard to tell without more info.

I forgot to write the lua in the beginning, it works now, thank you
