### ISSUE TITLE
Option to rename :Git command to something else like :MiniGit so that vim-fugitive which also uses :Git can be used

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1187]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-git

### Description

Hi echasnovski! Is it possible to rename :Git command to something like :MiniGit so that vim-fugitive can be used along with mini-git. I want mini-git show_at_cursor to work as it is while wanting the vim-fugitive's capabilities if possible. Can this be done in any way.

**Comment by echasnovski** [comment]
Sorry, no, it will stay the same.

You can still use `MiniGit.show_at_cursor()` (or probably even `require('mini.git').show_at_cursor()` without prior `require('mini.git').setup()`) even though `:Git` from 'mini.git' is not used. Besides, 'vim-fugitive' provides `:G` command which is [the same as its `:Git`](https://github.com/tpope/vim-fugitive/blob/0444df68cd1cdabc7453d6bd84099458327e5513/plugin/fugitive.vim#L547-L550).

Closing as not planned.

**Comment by echaya** [comment]
I came across a similar problem recently when trying to migrate to use more vim-fugitive and keep using mini.git's `minigit_summary_string`.  Depending on the loading sequence, the `Git` command registered from mini.git could interact with vim-fugitive command / interface from time to time.

One solution I found was to delete "Git" command right after mini.git setup call.

```
require("mini.git").setup()
pcall(vim.api.nvim_del_user_command, "Git")
```

**Comment by dannydulai** [comment]
@echasnovski, would you accept a pull request, or do you have an idealogical issue with the request?

**Comment by krovuxdev** [comment]
@dannydulai  pull requests are (**edit** from echasnovski: usually, but not in this case) welcome, but in my humble opinion I’d prefer not to change it. If you personally want a different command, you can use `:help nvim_del_user_command` and `:help nvim_create_user_command`.

**Comment by echasnovski** [comment]
> [@echasnovski](https://github.com/echasnovski), would you accept a pull request, or do you have an idealogical issue with the request?

I am not sure what you mean by "ideological", but this was closed as not planned for a reason, as adding this functionality is not planned (i.e. out of scope). There are several workarounds for this, depending on the culprit of why this is important: call use `:G` command from 'vim-fugitive', `require('mini.git').setup()` before 'vim-fugitive' creates its own command, not call `setup()`, etc.

**Comment by dannydulai** [comment]
I want this, it's a tiny change, so I've forked and done it for me.

I believe I've done it completely and within the style of the codebase so I'm sending you a pull request. I can only ask you to look. Feel free to do it as you want.

https://github.com/nvim-mini/mini.nvim/pull/2356
