### ISSUE TITLE
mini.animate throws error when setup in the following way.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1189]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

When i setup mini.animate in the following way, it throws an error.

### Neovim version

nightly

### Steps to reproduce

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
        spec = {
                "echasnovski/mini.animate",
        },
})

require("mini.animate").setup({
        scroll = {
                enable = false,
        },
        cursor = {
                enable = true,
                    timing = function(_, n) return 250 / n end,
                    path = MiniAnimate.gen_path.line({
			predicate = function()
				return true
			end,
	         }),
        resize = {
                enable = false,
        },
        open = {
                enable = false,
        },
        close = {
                enable = false,
        },
})
```

### Expected behavior

Not throw an error

### Actual behavior

Throws an error

**Comment by 231tr0n** [comment]
NVM my bad this is a false positive. I called MiniAnimate in mini.animate setup and before the setup is called it is not exported. Sorry for raising this defect. Closing it.

**Comment by echasnovski** [comment]
Please, make sure that this is *specifically* a 'mini.nvim' issue. At least by trying to reproduce this in a separate config and examining the error message first.
