### ISSUE TITLE
Write mini.resize

### ISSUE THREAD

**Issue by Weissle** [echasnovski/mini.nvim#119]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.resize

### Description

A sub-plugin like [smart-splits.nvim](https://github.com/mrjones2014/smart-splits.nvim) helps people easily resize their windows.
Neovim isn't a gui software thus resizing the windows is troublesome. This feature is simple but useful.

Expected behaviors (like smart-splits.nvim):
1. Normally it doesn't map any key to resize since people generally don't need to resize the windows. 
3. It creates the resize-mode which allows us to resize the windows by h/j/k/l.

I can help you implement this sub-plugin if you want it in mini.nvim. Of course, it is totally ok if you want to implement it by yourself.

**Comment by echasnovski** [comment]
Interestingly enough, it was already suggested in #12. Using `Alt + hjkl` is in somewhat of a "mode" in itself as `Alt` can be pressed. And creating splits seems not that inconvenient with built-in `<C-w> + sv`.

What exactly do you feel is troublesome in Neovim with resizing windows?

**Comment by Weissle** [comment]
Well, it does like a duplicated issue. Thanks for your reply.
