### ISSUE TITLE
mini.pairs - smarter handling pairs next to words

### ISSUE THREAD

**Issue by Drachenfels** [echasnovski/mini.nvim#1194]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

This plugin works like a charm but has one feature that is missing (and one that overlaps with mini.surround).

Let's imagine this Python code:
```py
print(hello_world)
```

If I position my cursor between `(` and `h` and then add a quote mark or parenthesis, we will get this:

```py
print(''hello_world)
```
or
```py
print(()hello_world)
```

It would be great if there was a way to configure the plugin so that it wraps words that start with alphanumerics instead of adding pairs.

So in same scenario:

> If I position my cursor between `(` and `h` and then add a quote mark or parenthesis, we will get this:

Outcome will be:
```py
print('hello_world')
```
or
```py
print((hello_world))
```

Note1: Perhaps such configuration in the current plugin version is achievable already?
Note2: I know I can achieve the same with mini.surround.
Note3: Also I am aware there is this ticket -> https://github.com/echasnovski/mini.nvim/issues/835

In my opinion, this use case is a bit different than what 835 wants to achieve.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> Note1: Perhaps such configuration in the current plugin version is achievable already?

I am afraid there is none and never will be. This is because 'mini.pairs' intentionally works **only** with inside a two character neighborhood (one to the left and one to the right) and **only** with a two character pair (one open and one close).

> Note2: I know I can achieve the same with mini.surround.

Indeed, and my suggestion is to use 'mini.surround' for that.

------

Closing as not planned.
