### ISSUE TITLE
Add a mini.starter MiniStarterEchoHeader highlight group

### ISSUE THREAD

**Issue by slugbyte** [echasnovski/mini.nvim#1196]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter 

### Description

The mini.starter `echo()` function hard codes the `WarningMsg` hl group for the `'(mini.starter)'` text that appears before echo's log messages [link to source](https://github.com/echasnovski/mini.nvim/blob/eb0f557a5797cfe9c720ed84a71582c22bccb4f8/lua/mini/starter.lua#L1490) . I propose that a new highlight group is created (potentially called `MiniStarterEchoHeader`) that links to `WarningMsg` allowing color schemes to customize the color of this log message header. 

I think this should be considered because currently colorscheme maintainers cannot customize this prompt without effecting all warning messages for all plugins, and the mini.starter echos are not always actually warnings so it would be nice if they did not have to use warning colors. 

I would be  interested in helping implement this feature if this feature request is approved, and help is wanted :)

> The orange text in the bottom left is what I would like to customize with my colorscheme [lackluster.nvim](https://github.com/slugbyte/lackluster.nvim)

![image](https://github.com/user-attachments/assets/baa70942-dc87-4f1f-ac19-f585c75a0abb)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The major problem in having this done is that the same approach is used in 10 modules in total. All of them have `(mini.xxx)` prefix whenever the text is `echo`ed and highlighted as a `WarningMsg`.

Case can be made that 'mini.starter' (and probably 'mini.align') use them not for one time messages but for user interaction. I am not yet sure how strong of a case that this. Currently preserving all modules to behave in the same way feels like a stronger argument, but I'll think about it.

**Comment by slugbyte** [comment]
@echasnovski Thanks for responding so quickly :)

Your hesitation makes a lot of sense.  I think preserving consistency is always a good idea. Plus this isn't really a critical feature request, and it seems like it could be quite a bit of effort to implement and maintain across all the mini modules. I'll mark this issue as closed for now.

If you ever change your mind and want to re-open this issue, I'd be happy to help you experiment to find a solution that could fit all 10 modules. Perhaps with something like `MiniLogHeader` linking to `WarningMsg`, or whatever you think works best.

Anyways thanks for all your great work on this project! I think mini.nvim is a really inspiring project!
