### ISSUE TITLE
disable title in mini.clue

### ISSUE THREAD

**Issue by MahanRahmati** [echasnovski/mini.nvim#1198]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Hi. 
Thank you for hard work. 
Is there any way to disable the title in mini.clue?

**Comment by echasnovski** [comment]
Yes, there is a [`config.window.config`](https://github.com/echasnovski/mini.nvim/blob/eb0f557a5797cfe9c720ed84a71582c22bccb4f8/doc/mini-clue.txt#L557) for that. Setting it to `{ title = { { '', 'MiniClueBorder' } } }` removes the title.

But I'd like to mention that title shows useful information about the currently typed keys and there is no (and won't be) any testing that title can be disabled. So the above solution might stop working at any time.
