### ISSUE TITLE
Add a window resize easy

### ISSUE THREAD

**Issue by axpira** [echasnovski/mini.nvim#12]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

winresize

### Description

Please,

Create a module like this https://github.com/roxma/vim-window-resize-easy
With this will be easier to resize windows

**Comment by echasnovski** [comment]
Well, seems not that hard. I'll think about it.
I personally use `<M-hjkl>` in Normal mode for resizing, so it is not a big problem for me.

**Comment by axpira** [comment]
So It's a good idea too.
I'll use this <M-hjkl> too, thanks

**Comment by axpira** [comment]
I've created this shortcut and It's good enough
