### ISSUE TITLE
New plugin to highlight active window

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1203]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.colorfulwinseperator

### Description

Hi echasnovski! Can something like [colorful-winsep](https://github.com/nvim-zh/colorful-winsep.nvim) be included as part of mini.nvim suite. I just wanted to know your opinion on this.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I've thought about doing that, but it seems that utilizing the `NormalNC` highlight group is not only more straightforward but also has better usability in my opinion. So although the colorful separators look great, I don't think they worth extra complexity.

Closing as not planned.

**Comment by 231tr0n** [comment]
> Thanks for the suggestion!
> 
> I've thought about doing that, but it seems that utilizing the `NormalNC` highlight group is not only more straightforward but also has better usability in my opinion. So although the colorful separators look great, I don't think they worth extra complexity.
> 
> Closing as not planned.

Is there a way to do it without the plugin is it. Can you give me some insight on how to do it if you dont mind?

**Comment by echasnovski** [comment]
> There a way to do it without the plugin is it. Can you give me some insight on how to do it if you dont mind?

I meant adding something like `vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#000000' })` after initializing color scheme.
