### ISSUE TITLE
icons  get_icons function only return a small set of icons

### ISSUE THREAD

**Issue by linsui** [echasnovski/mini.nvim#1207]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

icons

### Description

https://github.com/echasnovski/mini.nvim/blob/8413efde2546be4dec9ea424bc6af346a14dffbe/lua/mini/icons.lua#L595 only returns a small set of icons (148). Can you also add the filetype category so that it will return a larger set of icons (1050)?

### Neovim version

0.10.0

### Steps to reproduce

```lua
devicons_ok, devicons = pcall(require, "nvim-web-devicons")
icon = devicons.get_icons()["lua"]
```

This doesn't work because lua icon is not in the set.

### Actual behavior

https://github.com/utilyre/barbecue.nvim/blob/main/lua/barbecue/theme.lua#L159 barbecue.nvim can't get the icons.

**Comment by echasnovski** [comment]
This is mocking [how 'nvim-tree/nvim-web-devicons' does this](https://github.com/nvim-tree/nvim-web-devicons/blob/9793801f974bba70e4ac5d7eae6c4f5659993d8e/lua/nvim-web-devicons.lua#L15) (i.e. it [does not include filetypes](https://github.com/nvim-tree/nvim-web-devicons/blob/9793801f974bba70e4ac5d7eae6c4f5659993d8e/lua/nvim-web-devicons.lua#L62-L66)).

If anything, 'utilyre/barbecue.nvim' needs to use `get_icon` here, which is the intended use in this kind of situations. It was changed [here](https://github.com/utilyre/barbecue.nvim/commit/4c43a3cf31ac10c564f5df30385f57e9c81c0465), yet I am still not sure why. Or add direct support for 'mini.icons'.

Closing as working as expected.
