### ISSUE TITLE
Highlight trailspace in Insert mode (only when cursor is not at the end of spaces)

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1208]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.trailspace

### Description

Consider this set of commands:

```
highlight ExtraWhitespace ctermbg=red guibg=red
au BufEnter * match ExtraWhitespace /\s\+$/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/
```

They will highlight trailspace
1. normal mode
2. insert mode, when cursor is not at the end of trailspace

I like this behavior and hope you can consider modifying the behavior of mini.trailspace

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I am afraid this is [out of scope for 'mini.trailspace'](https://github.com/echasnovski/mini.nvim/blob/8413efde2546be4dec9ea424bc6af346a14dffbe/doc/mini-trailspace.txt#L9-L10).

Closing as not planned.
