### ISSUE TITLE
Add support for mini highlight groups to Neovim default colorscheme

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1211]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

All

### Description

Starting with https://github.com/neovim/neovim/pull/26334, Neovim has a new default color scheme. It'd be great to have some kind of bridge to apply mini highlight groups to it; Currently there's a few issues (not exclusive):

![image](https://github.com/user-attachments/assets/296b21b1-1f86-4496-9145-3df59a78050a)
![image](https://github.com/user-attachments/assets/011131c7-b92d-4f5e-b74b-39856af57085)
![image](https://github.com/user-attachments/assets/c03f1797-54a0-4137-8cff-f0d0e32d74b5)
![image](https://github.com/user-attachments/assets/8a2ad2dd-4549-4447-bd86-4849989c78f1)

**Comment by echasnovski** [comment]
I am not sure what exactly you'd expect here. Could you clarify, please?

This is all the result of default linking of 'mini.nvim' highlight groups (like in 'mini.files' the border is [linked to `DiagnosticFloatingWarn`](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/lua/mini/files.lua#L1339), hence the yellow color and not grey).

It is color scheme that should add support for plugin highlight groups, not the other way around.

**Comment by wroyca** [comment]
> I am not sure what exactly you'd expect here. Could you clarify, please?
> 
> This is all the result of default linking of 'mini.nvim' highlight groups (like in 'mini.files' the border is [linked to `DiagnosticFloatingWarn`](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/lua/mini/files.lua#L1339), hence the yellow color and not grey).
> 
> It is color scheme that should add support for plugin highlight groups, not the other way around.

The yellow is correct here, but border background should match float background, and float title should be consistent as well:

![image](https://github.com/user-attachments/assets/4cd919b3-c5a7-4aec-9522-39c05221bc82)
![image](https://github.com/user-attachments/assets/28dd73ec-4fdd-4b01-8511-3b981169aaa2)

Notice how the current border background is the same as Normal background.

Compare with randomhue:

![image](https://github.com/user-attachments/assets/afdaffb4-1972-470c-a3bf-0e11176bdffe)

**Comment by echasnovski** [comment]
> The yellow is correct here, but border background should match float background, and float title should be consistent as well:

That's the result of how default color scheme defines `DiagnosticFloatingWarn`: it [links to `DiagnosticWarn`](https://github.com/neovim/neovim/blob/4c5bce9cb417cf1c6a93cdd5ca6d3d52d2bf95d6/src/nvim/highlight_group.c#L223) which only defines foreground. I initially suggested that all `DiagnosticFloatingXxx` groups define background from `NormalFloat`, but it comes at a cost that all other color schemes would have to redefine `DiagnosticFloatingXxx` to match *their* background color of floating window.

It can be argued that this particular case (default highlighting of `MiniFilesBorderModified`) have hybrid definition of "foreground from `DiagnosticWarn`, background from `NormalFloat`", but that is *exactly* what `DiagnosticFloatingWarn` is supposed to represent.

------

Same thing with `MiniClueTitle`. It by default links to `FloatTitle` which in default highlight group links to `Title`. Motivation for this decision is the same: if it had defined background color, color schemes would need to override `FloatTitle` (even if they are fine with it linking to `Title`).

------

All in all, I think the suggestion/question is not really doable, because all modules in 'mini.nvim' already do as much as they can: define default highlights to (in most cases) link to the semantically closest built-in highlight group. In the end it is the color scheme's job to add support for a particular plugin. As much as I'd love to have default color scheme define all 'mini.nvim' highlight groups, I think chances for this are... somewhat slim.

Closing as "already does what is possible".

**Comment by wroyca** [comment]
The highlight mismatch has been mentioned a few times, but discussion never quite converged on a remedy. The result is a slightly awkward default experience: several mini.* components assume a coherent floating-window palette, while the built-in default colorscheme leaves a number of DiagnosticFloating* and FloatTitle groups with inconsistent backgrounds. Most colorschemes override these groups explicitly; default doesn't, so mini.nvim ends up drawing against a mixture of Normal and NormalFloat backgrounds.

For those hoping to solve that, here's a snippet to realign the affected groups with NormalFloat. It only applies when the active scheme is literally "default" and does not interfere with colorschemes that provide their own highlight definitions. Nothing fancy, just enough glue to make the built-in theme behave like a coherent base layer for mini.nvim's floating UI:

```lua
local function mini_highlights ()
  if vim.g.colors_name ~= "default" then return end

  local h = vim.fn.hlID
  local t = vim.fn.synIDtrans
  local a = vim.fn.synIDattr

  local float_bg = a (t (h ("NormalFloat")), "bg")
  local title_fg = a (t (h ("Title")), "fg")

  for _, sev in ipairs ({ "Error", "Warn", "Info", "Hint", "Ok" }) do
    local b = "Diagnostic" .. sev
    local f = a (t (h (b)), "fg")
    local s = f

    vim.api.nvim_set_hl (0, "DiagnosticFloating" .. sev, { fg = f, bg = float_bg })
  end

  vim.api.nvim_set_hl (0, "FloatTitle", { fg = title_fg, bg = float_bg, bold = true })
end
vim.api.nvim_create_autocmd( "ColorScheme", { callback = mini_highlights })
mini_highlights ()
```

Note that vim.g.colors_name is not populated on startup when using the built-in default colorscheme. Neovim sets this variable for all named schemes, but leaves it unset for default unless :colorscheme default is invoked explicitly:

```lua
-- Neovim populates `g.colors_name` with the active colorscheme name.
-- The default scheme is an exception: on initial startup Neovim leaves
-- this variable unset unless `:colorscheme default` is applied
-- explicitly.
--
-- Several utilities assume that `g.colors_name` always describes the 
-- current scheme. The unset case therefore leads to incorrect 
-- initialization on a first launch.
--
-- We normalize the state by assigning "default" when the variable is
-- still nil.
vim.g.colors_name = vim.g.colors_name or "default"
```

Stepping back, it would still be helpful to see some form of this logic surface in mini.misc (or a similar compatibility layer) if the stance around highlight defaults evolves in the future. The current position, that modules already link to the closest built-in groups and that the remaining responsibility lies with colorschemes, is understandable. At the same time, the built-in default theme occupies a special corner case: it exposes enough missing groups to degrade the experience, yet remains the fallback environment many users encounter first. If the perspective on these guardrails ever changes, a small amount of normalization inside mini.misc could go a long way. :)

**Comment by echasnovski** [comment]
> The highlight mismatch has been mentioned a few times, but discussion never quite converged on a remedy.

It did: 

> All in all, I think the suggestion/question is not really doable, because all modules in 'mini.nvim' already do as much as they can: define default highlights to (in most cases) link to the semantically closest built-in highlight group. In the end it is the color scheme's job to add support for a particular plugin. As much as I'd love to have default color scheme define all 'mini.nvim' highlight groups, I think chances for this are... somewhat slim.

---

> Stepping back, it would still be helpful to see some form of this logic surface in mini.misc (or a similar compatibility layer) if the stance around highlight defaults evolves in the future. The current position, that modules already link to the closest built-in groups and that the remaining responsibility lies with colorschemes, is understandable. At the same time, the built-in default theme occupies a special corner case: it exposes enough missing groups to degrade the experience, yet remains the fallback environment many users encounter first. If the perspective on these guardrails ever changes, a small amount of normalization inside mini.misc could go a long way. :)

I am afraid, it most certainly will not. 'mini.nvim' highlight groups already do as much as they reasonably can to fit in any color scheme. And default color scheme here is a part of that set.

If anything, this fits better in 'mini.colors', but I find it too opinionated to be added there (and anywhere else besides custom color schemes, really).

> Nothing fancy, just enough glue to make the built-in theme behave like a coherent base layer for mini.nvim's floating UI:

One user's "coherent" is another user's "chaotic and opinionated". The 'mini.nvim' already has opinionated ways of setting highlight groups: 'mini.hues' and bundled colorshemes (like `miniwinter`).
Some users might prefer title being different background (I was one of them until several months before 'mini.hues').

I'd also highly recommend to not use Vimscripts' `hlID()` in favor of a single `local hl_groups = vim.api.nvim_get_hl(0)`.

**Comment by wroyca** [comment]
> > The highlight mismatch has been mentioned a few times, but discussion never quite converged on a remedy.
> 
> It did:
> 
> > All in all, I think the suggestion/question is not really doable, because all modules in 'mini.nvim' already do as much as they can: define default highlights to (in most cases) link to the semantically closest built-in highlight group. In the end it is the color scheme's job to add support for a particular plugin. As much as I'd love to have default color scheme define all 'mini.nvim' highlight groups, I think chances for this are... somewhat slim.

I understand that you don't want mini.nvim itself to take on this responsibility, but that's exactly why I didn't consider the earlier discussion "settled." The conclusion at the time defined a boundary ("modules link to semantically closest built-ins; everything else belongs to the colorscheme"), but it didn't actually answer the narrower question that prompted this thread:

*If a module relies on highlight groups that the default theme does not define, where should that mismatch be handled, if anywhere?*

Your current reply makes the stance explicit: it should not be handled in mini.nvim, even for the default theme. That's a clear position, and I can work with that. My only point is that this clarity didn't exist in the earlier discussion; the distinction between "third-party themes" and the "default Neovim baseline" was never addressed directly.

> I am afraid, it most certainly will not. 'mini.nvim' highlight groups already do as much as they reasonably can to fit in any color scheme. And default color scheme here is a part of that set.
>
> One user's "coherent" is another user's "chaotic and opinionated". The 'mini.nvim' already has opinionated ways of setting highlight groups: 'mini.hues' and bundled colorshemes (like `miniwinter`). Some users might prefer title being different background (I was one of them until several months before 'mini.hues').

That's interesting, and I think this is where our perspectives diverge.

You're viewing the default colorscheme as simply another entry in the broader set of themes, and from that standpoint it makes sense to say that mini.nvim already does everything it reasonably should, and anything beyond that belongs squarely in the colorscheme layer.

My angle is a bit different. That is, the default theme isn't just "one more theme," it's the environment Neovim presents when the user hasn't expressed any preference at all. When highlight groups required for mini.nvim's floating UI aren't present there, the impact is something the user didn't opt into.

That's why I keep coming back to this distinction. For third-party themes, missing groups are a design choice; for the default theme, they're more of a structural gap. The concern isn't about being opinionated, but about whether the stock configuration provides the minimum surface needed for mini.nvim modules to look coherent.

If the project's stance is that this still falls outside mini.nvim's remit, even for the default theme, then that's a consistent boundary. I just wanted to highlight why some users (myself included) treat the default theme as a different category altogether.

Either way, thanks for taking the time to discuss it, the conversation is always welcome!

**Comment by echasnovski** [comment]
> If a module relies on highlight groups that the default theme does not define, where should that mismatch be handled, if anywhere?
> ...
> When highlight groups required for mini.nvim's floating UI aren't present there, the impact is something the user didn't opt into.

This is fundamentally not the correct angle to look at this. If there is a link to a highlight group in 'mini.nvim' module, it is *always* defined and present (with an exception on Neovim<0.10 for `diff*` groups). It might link to a highlight group which you don't like the look of in some situations, but that is a possibility of any color scheme.

This is verifiable by `:hi FloatTitle` which shows `... links to Title`. If it were not defined, it would have been either a `Highlight group not found` error or a `cleared` description.

> The concern isn't about being opinionated, but about whether the stock configuration provides the minimum surface needed for mini.nvim modules to look coherent.

I'd say it does, yes. And in the examples from this issue it *definitely* does. Every default link uses semantically proper highlight group:
- `FloatTitle` for titles in module's floating windows.
- `DiagnosticFloatingXxx` for colored foreground intended to be used inside floating windows.
