### ISSUE TITLE
FR: Harpoon like file navigation plugin

### ISSUE THREAD

**Issue by gh-liu** [echasnovski/mini.nvim#1212]

**Comment by echasnovski** [comment]
There is a ['mini.visits'](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/doc/mini-visits.txt) for that. Here is the [comparison with 'ThePrimeagen/harpoon'](https://github.com/echasnovski/mini.nvim/blob/f0d6e89515c6b055c20d257da717bd30211532f1/doc/mini-visits.txt#L81-L94).
