### ISSUE TITLE
vim.treesitter.get_parser will return nil instead of raising an error in Neovim 0.12

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#1218]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

When I open a picker I get the warning:
```
WARNING: vim.treesitter.get_parser will return nil instead of raising an error in Neovim 0.12
```

### Neovim version

NVIM v0.11.0-dev-774+g3b54adc6c

**Comment by echasnovski** [comment]
Thanks for the issue!

The warning is a Neovim Nightly effect of neovim/neovim#30313 and currently can not be removed. It should be reworked soon, after which I'll apply appropriate changes to all modules which use `vim.treesitter.get_parser()`.

**Comment by ndavd** [comment]
Nice, thank you! Indeed mini was not the only plugin where I noticed this warning so I suspected it was something from Neovim itself.

**Comment by echasnovski** [comment]
Thanks to Nightly updates and adjustments in 'mini.nvim', this issue now should be resolved on latest `main`.
