### ISSUE TITLE
`mini.notify` - Allow window border options

### ISSUE THREAD

**Issue by yavorski** [echasnovski/mini.nvim#1219]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.notify

### Description

Hi, It would be nice if you allow the users to pass the border they want for `nvim.notify` window - e.g. one of default ones like 
`none`, `single`, `double`, `rounded`, `solid`, `shadow`. Right now `single` is hardcocded. I noticed `none` works too, but `solid` is not working - which my personal preference.
Thanks for your time and consideration.

**Comment by echasnovski** [comment]
This is already possible via [`config.window.config`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-notify.txt#L123). The `"solid"` border can be achieved with this set up:

```lua
require('mini.notify').setup({ window = { config = { border = 'solid' } } })
```

**Comment by yavorski** [comment]
Sorry, I was using only `window.border` and not `window.config.border`. Thanks.
