### ISSUE TITLE
`@class.outer` treesitter query does not work with `mini.ai`

### ISSUE THREAD

**Issue by shashanktomar** [echasnovski/mini.nvim#122]
### Contributing guidelines

- [ ] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [ ] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Here is my mini.ai config

```lua
local ok, mini_ai = pcall(require, 'mini.ai')
if not ok then return end

local spec_treesitter = mini_ai.gen_spec.treesitter
mini_ai.setup({
  custom_textobjects = {
    -- a = mapped to args by mini.ai
    f = spec_treesitter({
      a = '@function.outer',
      i = '@function.inner',
    }),
    u = spec_treesitter({
       a = '@class.outer',
       i = '@class.outer', -- only outer is available
    }),
    j = spec_treesitter({
      a = '@loop.outer',
      i = '@loop.inner',
    }),
    o = spec_treesitter({
      a = '@block.outer',
      i = '@block.inner',
    }),
    r = spec_treesitter({
      a = '@parameter.outer',
      i = '@parameter.inner',
    }),
    i = spec_treesitter({
      a = '@conditional.outer',
      i = '@conditional.inner',
    }),
    m = spec_treesitter({
      a = '@comment.outer',
      i = '@comment.outer', -- only outer is available
    }),
    c = spec_treesitter({
      a = '@call.outer',
      i = '@call.inner',
    }),
    d = spec_treesitter({
      a = '@statement.outer',
      i = '@statement.inner',
    }),
    -- scopename
    -- frame
    -- attribute
  },
})

```

Everything else other than `@class` mapping works. I have tested this with typescript project which has a `@class` support. To verify that it is not a `nvim-treesitter-textobjects` plugin bug, if I add this to treesitter config, it seems to work fine:

```lua

-- treesitter textobjects setup
  select = {
    enable = true,
    keymaps = {
      ['iu'] = '@class.outer', -- for some reason this does not seem to work with mini.ai
      ['au'] = '@class.outer', -- for some reason this does not seem to work with mini.ai
    },
  },
-- ... more config
```

### Neovim version

v0.8.0

### Steps to reproduce

1. setup `mini.ai` with `nvim-treesitter-textobjects` plugin
2. create a `custom_textobjects` mapping for `@class`
3. test with a language which support `@class` query, like typescript

### Expected behavior

The text object should work and select `a` class.

### Actual behavior

The class selection does not work

**Comment by echasnovski** [comment]
I've tested this setup with Python and it works for me:

```lua
  require('mini.ai').setup({
    custom_textobjects = {
      u = require('mini.ai').gen_spec.treesitter({ a = '@class.outer', i = '@class.outer' }),
    },
  })
```

My guess is that this is a result of conflicting mapping(s) for `au`/`iu` which gets triggered instead of `a` and `i` defined by 'mini.ai'. Could you execute `:xmap a`, `:xmap i`, `:omap a`, `:omap i` and see if there are `au`/`iu` mappings that don't come from 'mini.ai'? If yes, then you have two options:
- Delete them.
- Type `a`/`i` and wait at least `timeoutlen` milliseconds and only then type `u`.

**Comment by shashanktomar** [comment]
Thanks for a quick response @echasnovski. I checked my `:xmap` and `omap` mappings and `u` is not mapped to anything. Here is my `omap` output. `xmap` looks very similar:
```
   <Space>     * <Cmd>lua require("packer.load")({'which-key.nvim'}, { keys = "<leader>", prefix = "" }, _G.packer_plugins)<CR>
o  al            v:lua.MiniAi.expr_textobject('o', 'a', {'search_method': 'prev'})
                 Around last textobject
o  an            v:lua.MiniAi.expr_textobject('o', 'a', {'search_method': 'next'})
                 Around next textobject
o  a             v:lua.MiniAi.expr_textobject('o', 'a')
                 Around textobject
   gc          * <Cmd>lua require("packer.load")({'Comment.nvim'}, { keys = "gc", prefix = "" }, _G.packer_plugins)<CR>
   gb          * <Cmd>lua require("packer.load")({'Comment.nvim'}, { keys = "gb", prefix = "" }, _G.packer_plugins)<CR>
o  g]            v:lua.MiniAi.expr_motion('right')
                 Move to right "around"
o  g[            v:lua.MiniAi.expr_motion('left')
                 Move to left "around"
o  il            v:lua.MiniAi.expr_textobject('o', 'i', {'search_method': 'prev'})
                 Inside last textobject
o  in            v:lua.MiniAi.expr_textobject('o', 'i', {'search_method': 'next'})
                 Inside next textobject
o  i             v:lua.MiniAi.expr_textobject('o', 'i')
                 Inside textobject
   <Plug>luasnip-expand-repeat * <Cmd>lua require'luasnip'.expand_repeat()<CR>
   <Plug>luasnip-delete-check * <Cmd>lua require'luasnip'.unlink_current_if_deleted()<CR>
```

I can test with a python project and let you know

**Comment by shashanktomar** [comment]
I tested it with python and it is working. This is very strange 🤯. Here is the current behavior with my setup:

- setup `@class.outer` with `custom_textobjects` in `mini.ai`
  - it works in python but not in typescript
- set it up with `nvim-treesitter-textobjects`, it works for both

Can you clone [this](https://github.com/shashanktomar/ts-cdk-monorepo) small `typescript` project. Go to `sqs-sourced-function.ts` and try it inside the class block?

**Comment by echasnovski** [comment]
Oh, it does work for me. With one little change (and in some cases without it).

By any chance, does it give a following message in the command line: `` No textobject "au" found covering region within 50 lines and `search_method = 'cover_or_next'`. ``? Basically, it means what it says: it couldn't find textobject with those parameters listed. It is meant as indication that at least *one* of those should be changed.

In your case, it is a `50 lines` part. Both 'mini.ai' and 'mini.surround' work by fetching some neighborhood of initial (reference) region and performing search within those. For speed and certain usability reasons, 'mini.ai' uses 50 lines before start and after end of reference region. In case of your example, target class region spans 84 lines, so if you put your cursor near its edges it can't find it. But if you place cursor on line 75 and it should select that region.

If you don't want this behavior, set `config.n_lines` to some very high value (like 10000). It will come at a cost of somewhat increased execution time. Still should be unnoticeable and very quick though.

**Comment by shashanktomar** [comment]
That was precisely the issue. Thanks
