### ISSUE TITLE
Does mini-indentscope have analog of IndentWiseBlockScopeBoundaryBegin and IndentWiseBlockScopeBoundaryEnd?

### ISSUE THREAD

**Issue by srghma** [echasnovski/mini.nvim#1221]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

 mini-indentscope

### Description

suppose I have 

n  [bi         * <Cmd>lua MiniBracketed.indent('backward')<CR>
                 Indent backward
n  [i          * <Cmd>lua MiniIndentscope.operator('top', true)<CR>
                 Go to indent scope top

and file

```
return {
  "echasnovski/mini.bracketed",
  opts = {
    buffer     = { suffix = 'bb', options = {} },
    comment    = { suffix = 'bc', options = {} },
    indent     = { suffix = 'bi', options = {} },
  },
}
```

using these keys I cannot reach `[b]uffer` if I am on `[i]ndent`, only `[o]pts` and `[r]eturn`

but with 

```
lvim.keys.normal_mode["K"] = "<Plug>(IndentWiseBlockScopeBoundaryBegin)"; lvim.keys.visual_mode["K"] = lvim.keys.normal_mode["K"]

-- Mapping J to navigate to the end of the block scope boundary
lvim.keys.normal_mode["J"] = "<Plug>(IndentWiseBlockScopeBoundaryEnd)"; lvim.keys.visual_mode["J"] = lvim.keys.normal_mode["J"]
```

**Comment by echasnovski** [comment]
There is [`move_cursor()`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-indentscope.txt#L429) function which can move to top or bottom part of the body when `use_border` is `false`. Here is a way to replicate mappings for `J` and `K` (although I don't recommend using them, as both have quite useful built-in functionality):

```lua
vim.keymap.set({ 'n', 'x', 'o' }, 'J', '<Cmd>lua MiniIndentscope.move_cursor("bottom", false)<CR>')
vim.keymap.set({ 'n', 'x', 'o' }, 'K', '<Cmd>lua MiniIndentscope.move_cursor("top", false)<CR>')
```

**Comment by echasnovski** [comment]
This does not happen with default config. Most probably, you have set [`try_as_border`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-indentscope.txt#L161-L164) option to `true`. This results in line `opts = {` being first treated as a border of its scope and moving cursor to the bottom of scopes body (which is `indent   ` line.

Here are possible solutions:
- Do not set `try_as_border = true` globally.
- Set `try_as_border = false` temporarily locally inside a callable used in mappings.
- Similar to previous approach, but utilize another documented feature: [third argument `scope`](https://github.com/echasnovski/mini.nvim/blob/e50cf9de614500a20e47cfc50e30a100042f91c3/doc/mini-indentscope.txt#L439). With something like this:

    ```lua
    local make_goto_inner = function(side)
      return function()
        local scope = MiniIndentscope.get_scope(nil, nil, { try_as_border = false })
        MiniIndentscope.move_cursor(side, false, scope)
      end
    end
    vim.keymap.set({ 'n', 'x', 'o' }, 'J', make_goto_inner('bottom'))
    vim.keymap.set({ 'n', 'x', 'o' }, 'K', make_goto_inner('top'))
    ```
