### ISSUE TITLE
[mini.files] move/copy multiple files (non-adjacent)

### ISSUE THREAD

**Issue by lost22git** [echasnovski/mini.nvim#1226]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

we select/mark them and move/copy them

**Comment by pkazmier** [comment]
See this Reddit [comment](https://www.reddit.com/r/neovim/comments/1f7zrjt/comment/llcrhxe/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) for some suggestions.

**Comment by lost22git** [comment]
> See this Reddit [comment](https://www.reddit.com/r/neovim/comments/1f7zrjt/comment/llcrhxe/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) for some suggestions.

Thanks, it is very helpful.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The approach of appending to a register (as @pkazmier describes in his Reddit comment) is indeed one approach to do that. Another approach is to utilize bookmarks for a quicker back and forth navigation.

As the separate "select and cut non consecutive lines" is out of scope, closing this as not planned.
