### ISSUE TITLE
Fast way switch picks

### ISSUE THREAD

**Issue by fishioon** [echasnovski/mini.nvim#1231]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Open buffers pick and input fuzzy text, but not found my want result.
I need exit buffers pick and open files pick, and re input fuzzy text.
Any way shortcut or actions for switch between picks?

**Comment by echasnovski** [comment]
That's a very nice suggestion! Thank you!

I don't think having this built-in is undoubtedly a good thing (built-in mappings is already quite crowded). But it can be implemented via custom action. For example, something like this:

```lua
local switch_picker = function()
  local ok, picker_name = pcall(vim.fn.input, 'Picker name: ')
  if not ok or MiniPick.registry[picker_name] == nil then return end

  local query = MiniPick.get_picker_query()
  MiniPick.stop()

  vim.cmd('Pick ' .. picker_name)
  local transfer_query = function() MiniPick.set_picker_query(query) end
  vim.api.nvim_create_autocmd('User', { pattern = 'MiniPickStart', once = true, callback = transfer_query })
end

require('mini.pick').setup({
  mappings = {
    switch = { char = '<C-z>', func = switch_picker },
  },
})
```

With this you can press `<C-z>`, type a picker name you want to switch to (should be present in registry, i.e. executable via `:Pick` command), press `<CR>`, and it should switch picker while transferring the current query.

------

Closing as "doable but seems to be too much to be built-in". Although it is a very good candidate for a possible future wiki entry.

**Comment by fishioon** [comment]
Input picker name is slow. It would be better to open a picker for selecting from registry and retain the previous query.

**Comment by echasnovski** [comment]
> Input picker name is slow. It would be better to open a picker for selecting from registry and retain the previous query.

This can also be achieved because registry is available to the user. I'd suggest either using `MiniPick.ui_select()` to get the registry entry name or supply `completion` to ` vim.fn.input()`.

**Comment by fishioon** [comment]
> > Input picker name is slow. It would be better to open a picker for selecting from registry and retain the previous query.
> 
> This can also be achieved because registry is available to the user. I'd suggest either using `MiniPick.ui_select()` to get the registry entry name or supply `completion` to ` vim.fn.input()`.

Thanks for the suggestion. 
```lua
  local switch_picker = function()
    local query = MiniPick.get_picker_query() or {}
    MiniPick.stop()
    MiniPick.ui_select(vim.tbl_keys(MiniPick.registry), {
      prompt = 'Switch picker with query: ' .. table.concat(query, ''),
    }, function(picker)
      vim.cmd('Pick ' .. picker)
      local transfer_query = function() MiniPick.set_picker_query(query) end
      vim.api.nvim_create_autocmd('User', { pattern = 'MiniPickStart', once = true, callback = transfer_query })
    end)
  end
  require('mini.pick').setup({
    mappings = {
      switch = { char = '<C-k>', func = switch_picker },
    },
  })

```
