### ISSUE TITLE
Textobject for mini.indentscope which does not include blank lines

### ISSUE THREAD

**Issue by srghma** [echasnovski/mini.nvim#1233]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

I lack `ii` from https://github.com/kana/vim-textobj-indent

(N.B.  `ia` from https://github.com/kana/vim-textobj-indent is `ai` from `mini.indentscope`)
------------

in

```py
def foo:
  bar
  bar
end
```

cursor on `bar` should select 

```py
  bar
  bar
```
------------
in

```py
def foo:
  bar
  bar
        end
```

cursor on `bar` should select 

```py
  bar
  bar
        end
```

too

------------
in

```py
def foo:
  bar
  bar

  foo
  foo
        end
```

cursor on `bar` should select 

```py
  bar
  bar
```

too

------------

having

```lua
:lua print(vim.inspect(MiniIndentscope.config))
{
  draw = {
    animation = <function 1>,
    delay = 100,
    priority = 2
  },
  mappings = {
    goto_bottom = ",J",
    goto_top = ",K",
    object_scope = "ii",
    object_scope_with_border = "ai"
  },
  options = {
    border = "both",
    indent_at_cursor = true,
    try_as_border = false
  },
  symbol = "▏"
}
```

cursor on `[g]oto_top`

```lua
      mappings = {



        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

        -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',
      },
```

if I `vii`

currently - selects

```lua
      mappings = {
[


        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

        -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',]
      },
```

the `vii` from https://github.com/kana/vim-textobj-indent would select only

```lua
      mappings = {



        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

[       -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',]
      },
```

**Comment by AhmadMahmoodRana** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by srghma** [comment]
bot, virus spammer

**Comment by srghma** [comment]
having

```lua
:lua print(vim.inspect(MiniIndentscope.config))
{
  draw = {
    animation = <function 1>,
    delay = 100,
    priority = 2
  },
  mappings = {
    goto_bottom = "<C-j>",
    goto_top = "<C-k>",
    object_scope = "ii",
    object_scope_with_border = "ai"
  },
  options = {
    border = "none",
    indent_at_cursor = true,
    try_as_border = false
  },
  symbol = "▏"
}
```

cursor on `[g]oto_top`

```lua
      mappings = {



        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

        -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',
      },
```

if I `vii` or `vai`

currently - selects

```lua
      mappings = {



[        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

        -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',]
      },
```

thus, there is no way to accomplish `vii` from https://github.com/kana/vim-textobj-indent IIUC

---------


# About `ip`

 it will select

```lua
      mappings = {



        -- Textobjects
        object_scope = 'ii',
        object_scope_with_border = 'ai',

[       -- Motions (jump to respective border line; if not present - body line)
        goto_top = ',K',
        goto_bottom = ',J',
      },]
```

not the same (just as kevintraver wrote here https://github.com/kiyoon/treesitter-indent-object.nvim/issues/1#issuecomment-1692816987)

**Comment by echasnovski** [comment]
> thus, there is no way to accomplish `vii` from https://github.com/kana/vim-textobj-indent IIUC

Yes, this is what was meant by "out of scope for 'mini.indentscope". I don't think this particular textobject is useful enough to be worth adding extra complexity to 'mini.indentscope' module.

> not the same (just as kevintraver wrote here

Yes, that's why it was "in *most cases* it is *similar* to `ip`".

**Comment by srghma** [comment]
> is useful enough

:( at least two people search for it

I used often :(
