### ISSUE TITLE
FEATURE REQUEST: Mini.ai: move to next/move to last

### ISSUE THREAD

**Issue by takiadev** [echasnovski/mini.nvim#1236]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

## What?

Hello, it would be extremely convenient to expose these features in `mini.ai`:

- go to start of next object around
- go to start of next object inside
- go to end of next object around
- go to end of next object inside
- go to start of previous object around
- go to start of previous object inside
- go to end of previous object around
- go to end of previous object inside

My understanding is that the feature is already implemented in the code, but currently not easily configurable.

## Why?

- Natively, vim textobjects (like `w` word) are associated with a motion (`w` goto next word) so it would mimic this builtin way of thinking
- Just like the "select around next" feature proved extremely useful, being able to "move inside next" make editing code easier:
    > Add code in the if statement? `go to inside next if + o`
    > Add code before the if statement? `go to around next if + O`
    > What an overview of the file? Just iterate `go to next function`
- Also, it is useful to be able to free some keys on the keyboard. The builtin motions `w`, `e` and `b` all correspond to the `word` textobject and can be replaced with these new plugin motions. This would free up some space on the keyboard for something else for those interested in doing so.

## Why in mini.ai?

Similar features have been implemented but *in an incomplete manner* in other plugins, such as treesitter-textobjects or other motion plugins. The problem with these other plugins is that they will define the motions for some objects (like a treesitter node, for instance) but the motions won't work with other mini.ai objects. Which makes for a very inconsistent experience.

It would be a lot more powerful and cleaner to make these motions work with every mini.ai objects, which would remove the need for these plugins and make motions consistent across the board.

## Example mappings

This section shows how I personally would map these motions but it's not intended to suggest default mappings. I'm hoping to add a bit more context around this feature by providing examples.

```
go_next_start_around = 'n',
go_next_start_inside = 'ni',
go_next_end_around = 'ne',
go_next_end_inside = 'nei',
go_prev_start_around = 'N',
go_prev_start_inside = 'Ni',
go_prev_end_around = 'Ne',
go_prev_end_inside = 'Nei',
```

With these mappings:

- go to next word: `nw` (`w` is now free for something else)
- go to prev word: `Nw` (`b` is now free for something else)
- go to next function: `nf`
- edit inside function `nif i`
- Let's say you are currently writing code inside an `if` block. You realize that you need a new variable whose scope is not limited to the `if`. Assume `c` is the textobject for conditionals. Use `Nc` to jump to the start of the if block then `O` to open line before and add your variable.
- We can keep to original next-match (`n`) and prev-match (`N`) behavior by mapping them to `nm` and `Nm` for instance, or `n/` and `N/`

## Workaround implementation

Currently I have defined this mapping manually but it's not as good as if they were inside the library because (1) typing the shortcut too slow breaks, while the library can wait longer to get the textobject char after typing the prefix, (2) it will break in case of api change and (3) it would be better to shar the feature with others too

Note the careful selection of `search_method` based on left/right and next/prev directions.

```lua
-- used for operators (select/delete/yank/etc.)
around_next = 'an',
around_prev = 'aN',
inside_next = 'in',
inside_prev = 'iN',

-- new motions
go_next_start_around = 'n',
go_next_start_inside = 'ni',
go_next_end_around = 'ne',
go_next_end_inside = 'nei',
go_prev_start_around = 'N',
go_prev_start_inside = 'Ni',
go_prev_end_around = 'Ne',
go_prev_end_inside = 'Nei',


-- next match (search)
vim.keymap.set({'n', 'x', 'o'}, "n/", "n", {noremap=true})

-- prev match (search)
vim.keymap.set({'n', 'x', 'o'}, "N/", "N", {noremap=true})

for k, _ in pairs(ai_objects) do
-- k is the letter of the object (for instance f for function)

    -- nf: next function
    vim.keymap.set({"n", "x", "o"}, go_next_start_around .. k, function() 
        return MiniAi.move_cursor("left", "a", k, {search_method="next"})
    end, {silent=true})

    -- nef: next end of function (or: Nf)
    vim.keymap.set({"n", "x", "o"}, go_next_end_around .. k, function() 
        return MiniAi.move_cursor("right", "a", k, {search_method="cover_or_next"})
    end, {silent=true})

    -- nif: next inside function
    vim.keymap.set({"n", "x", "o"}, go_next_start_inside .. k, function() 
        return MiniAi.move_cursor("left", "i", k, {search_method="next"})
    end, {silent=true})

    -- neif: next end inside function (or: Nif)
    vim.keymap.set({"n", "x", "o"}, go_next_end_inside .. k, function() 
        return MiniAi.move_cursor("right", "i", k, {search_method="cover_or_next"})
    end, {silent=true})

    -- Nf: prev start of function
    vim.keymap.set({"n", "x", "o"}, go_prev_start_around .. k, function() 
        return MiniAi.move_cursor("left", "a", k, {search_method="cover_or_prev"})
    end, {silent=true})

    -- Nef: prev end of function (or: Pf)
    vim.keymap.set({"n", "x", "o"}, go_prev_end_around .. k, function() 
        return MiniAi.move_cursor("right", "a", k, {search_method="prev"})
    end, {silent=true})

    -- Nif: prev start inside function
    vim.keymap.set({"n", "x", "o"}, go_prev_start_inside  .. k, function() 
        return MiniAi.move_cursor("left", "i", k, {search_method="cover_or_prev"})
    end, {silent=true})

    -- Neif: prev end inside function (or: Pif)
    vim.keymap.set({"n", "x", "o"}, go_prev_end_inside .. k, function() 
        return MiniAi.move_cursor("right", "i", k, {search_method="prev"})
    end, {silent=true})
end
```

**Comment by echasnovski** [comment]
Thanks for the detailed suggestion!

I thought about it several times and always the conclusion was that having this built-in under some default mappings is a bit confusing. The current `g[` / `g]` is the extent to which I think the "go to" feature is reasonable to have built-in.

The "Workaround implementation" is not *that* workaround but more in the spirit of how it is suggested to resolve this kind of request. You can look for a similar yet slightly different approach [here](https://github.com/echasnovski/mini.nvim/discussions/33#discussioncomment-10692806).

Closing as not planned.

**Comment by llakala** [comment]
@takiadev This seems like a really great proposal. Since echasnovski doesn't want it in default mappings, I'd be interested in maintaining a patch on top of `mini.ai` to support this. If you'd like to work on this together, I made an issue for it at https://github.com/llakala/mini.ai/issues/1!
