### ISSUE TITLE
[Question] How to do file type specific comment

### ISSUE THREAD

**Issue by vihu** [echasnovski/mini.nvim#124]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

I was setting up `mini.comment` and noticed that I can't seem to figure out how to do something like this:

```lua
local ft = require("Comment.ft")
ft.set("erlang", "%% %s")
```

It effectively says that every time I try to comment anything in a `.erl` file use `%%` instead of `%`. I am currently using [comment](https://github.com/numToStr/Comment.nvim) plugin to do so.

**Comment by echasnovski** [comment]
The 'mini.comment' [uses 'commentstring' option](https://github.com/echasnovski/mini.nvim/blob/085baefa6aca44526be621b15e7b688f996c2daf/doc/mini.txt#L1382-L1385) to infer what to use for commenting. Your case can be solved by setting this option locally to buffer of "erlang" filetype. There are two roads:

- Create file 'after/ftplugin/erlang.lua' inside your Neovim config and put this line there: `vim.opt_local.commentstring = '%% %s'` (or if there is no support of `opt_local` in your Neovim version, use `vim.cmd([[setlocal commentstring=%%\ %s]])`). I prefer this one.
- Create an autocommand for `FileType` event: `vim.cmd([[au FileType erlang lua vim.opt_local.commentstring = '%% %s']])` (or use `vim.api.nvim_create_autocmd()`).
