### ISSUE TITLE
mini.clue top level trigger

### ISSUE THREAD

**Issue by ibrokemypie** [echasnovski/mini.nvim#1243]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

I've had a look and haven't found a way to cause mini.clue to show clues for the top level binds, i.e. before hitting any key. 
When using which-key, I had a bind of `<leader><leader>` mapped to `<cmd>WhichKey<cr>` which achieved this result, so my request is just to have something similar, either a command or a lua method to bring up a list of any clues for top level binds, as well as all defined mini.clue triggers.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

You can see all the triggers by inspecting `MiniClue.config.triggers` and `vim.b.miniclue_config` (if present). There is also a more dynamic way to inspect the output of `vim.api.nvim_buf_get_keymap(0, 'n')`.

I don't really see a big advantage of having a separate method to show all triggers interactively in a clue window.

There also was an attempt to create a function that starts a query without triggers: #442. It was met with a lot of tricky issues and was deemed not worth the time and effort.

Closing as not planned.
