### ISSUE TITLE
More granular control in mini.diff

### ISSUE THREAD

**Issue by S1M0N38** [echasnovski/mini.nvim#1245]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.diff

### Description

I really appreciate the versatility of `mini.diff` in computing diffs between arbitrary sources. To further enhance its strength, I propose adding more granular control over the diffs and sources.

#### 1. Improved Word Diff
In the overlay visualization, word diffs are computed and shown, but there's no way to:

* Move between individual word diffs within the same hunk/lines
* Accept/reject word diffs individually

Inspired by [rickhowe/diffchar.vim](https://github.com/rickhowe/diffchar.vim), this feature would enhance user interaction with the diff output.

#### 2. Line Range Diff Computation
Currently, `MiniDiff.set_ref_text` computes the diff between the whole buffer and the given text. I propose adding an option to restrict the diff computation to a specific line range.

Similar to [rickhowe/spotdiff.vim](https://github.com/rickhowe/spotdiff.vim), this feature would provide more fine-grained control over the diff process.

### Rationale
Although plugins like `diffchar.vim` and `spotdiff.vim` offer similar functionalities using Neovim's built-in diff tool, integrating them into another plugin is not straightforward. These plugins expose user commands but lack a comprehensive API. By incorporating these features into `mini.diff`, we can provide a more seamless experience for plugin authors.

*Are these proposals aligned with the `mini.diff` spirit?*

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> 1. Improved Word Diff

This look a bit too much. Both because it implies extra actions/mappings and a separate `apply_word_hunk` method for the source (which is not trivial because most VCS work on per line basis).

> 2. Line Range Diff Computation

This might be doable in a concise manner, but not sure about when/how to make it usable. I'll think about that. If you can provide a more complete example of how you envision to work with "partial `set_ref_text()`", it'll greatly help.

**Comment by S1M0N38** [comment]
Here is a use case for "partial `set_ref_text`":

Suppose I'm using an AI plugin like `codecompanion` or `avante` to leverage LLM code generation capabilities. I select a function with a visual selection (e.g., to add documentation to that function) and ask the LLM to generate improvements. The response is saved in a new buffer.

Now I have:
- The **position** of the original function in the original buffer (e.g., a range of lines).
- A new buffer containing **only** the improved version of the function.

I want to use mini.diff to compare the differences between the old function and the improved version, but limit the comparison to **only** the lines where the old function is defined, and the text of the new function. Currently, as I understand, mini.diff can only compare the **entire** buffer where the old function resides, rather than restricting it to the relevant lines.

**Comment by echasnovski** [comment]
> I want to use mini.diff to compare the differences between the old function and the improved version, but limit the comparison to **only** the lines where the old function is defined, and the text of the new function. Currently, as I understand, mini.diff can only compare the **entire** buffer where the old function resides, rather than restricting it to the relevant lines.

I would expect here that `set_ref_text()` is called inside a new buffer (which contains **only** the improved version of the function). And reference text is the original content of a function, i.e. lines extracted from the available range of lines in the original buffer. Does this make sense?

**Comment by S1M0N38** [comment]
Yeah, it makes perfect sense! Thanks :)
