### ISSUE TITLE
Contributing a reference implementation to mini.terminals

### ISSUE THREAD

**Issue by Charl-AI** [echasnovski/mini.nvim#1249]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.terminals

### Description

Hi @echasnovski!

Thanks a lot for mini.nvim, I love the project and use it extensively myself.

Just raising this issue because I saw that mini.terminals is a planned module. I recently implemented a similar concept for my own personal use, and I would be happy to contribute my implementation as a starting point for the mini.terminals one. You can find it at:

https://github.com/Charl-AI/dotfiles/blob/main/.config/nvim/lua/repl.lua

It is ~150 lines long and is probably the simplest repl/terminals module possible, which I thought would fit in with the ethos of mini.nvim. It supports toggling the inbuilt terminal whilst maintaining its current state, as well as sending visual selections to the terminal.

I know you like to do things in your own style, so feel free to ignore the suggested implementation or change it however you see fit. Also, if there is anything I can do to help contribute to this module, please let me know how I can help. I just thought it would be a nice opportunity to give back to a project from which I have benefitted.

:)

**Comment by echasnovski** [comment]
I am *extremely* grateful for the suggestion!

And yes, this particular module is somewhat important to me to the point that I'd like to implement it myself. Also, the part of the plan is for it to have some "standardized" interface of creating a window (either float or split) which can be reused for similar task in other modules. This requires review of where it is already done (to maybe adjust if the design is not good enough) or can be done in the future.

Using your linked implementation as a reference will save me considerable amount of time in the future. It contains the "send to REPL" implementation part which I didn't have time to fully wrap my head around. So this is already in itself a great contribution on your part :) Thank you very much!

I'll close this now but will definitely get back to it later.
