### ISSUE TITLE
Mini.notify documentation concerning setting window at the bottom of the screen

### ISSUE THREAD

**Issue by marcinmdev** [echasnovski/mini.nvim#1262]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.notify

### Description

I think putting snippet pasted below in the help file could improve the experience of new users. Especially because it is not a matter of setting one variable in config, but a more involved process.

Lifted straight from https://old.reddit.com/r/neovim/comments/18ye17d/mininotify_show_notifications_a_vimnotify_maker/kgeqnvn/
```lua
local win_config = function()
  local has_statusline = vim.o.laststatus > 0
  local bottom_space = vim.o.cmdheight + (has_statusline and 1 or 0)
  return { anchor = "SE", col = vim.o.columns, row = vim.o.lines - bottom_space }
end
require("mini.notify").setup({ window = { config = win_config } })
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I'll take a look if there is a better way to provide some useful examples.

**Comment by echasnovski** [comment]
It now [part of the help file](https://github.com/echasnovski/mini.nvim/blob/a535342b6105a684f16114f598d44318e6a1d20f/doc/mini-notify.txt#L213-L218). Thanks again for the suggestion!
