### ISSUE TITLE
Show mini.files instead of netrw when launching nvim into a directory and `use_as_default_explorer` is enabled

### ISSUE THREAD

**Issue by emonadeo** [echasnovski/mini.nvim#1264]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Currently, when opening a directory with neovim (e.g. `nvim ~/.config/nvim`) it'll throw you into netrw.

Instead I suggest a behavior similar to [`stevearc/oil.nvim`](https://github.com/stevearc/oil.nvim), where it opens its file explorer instead when `use_as_default_explorer` is enabled.

To me, this would seem a lot more ergonomic.

**Comment by emonadeo** [comment]
Oh, thanks for the heads up. Works like a charm! I do feel silly for not figuring that out myself, especially because I even had `event = { "VimEnter" }` set for 'oil.nvim' but removed it for some reason when switching to 'mini.files'.

Still, I think it might be worth mentioning this in the README, unless I missed it.

**Comment by echasnovski** [comment]
> Still, I think it might be worth mentioning this in the README, unless I missed it.

Thanks for the suggestion! The note about not lazy loading for this use case is now [part of the help file](https://github.com/echasnovski/mini.nvim/blob/a535342b6105a684f16114f598d44318e6a1d20f/doc/mini-files.txt#L665).
