### ISSUE TITLE
Add option for stop highlight in visual mode

### ISSUE THREAD

**Issue by fnix2** [echasnovski/mini.nvim#127]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

cursorword

### Description

Would be nice to have an option to stop highlighting word in visual mode.

**Comment by echasnovski** [comment]
Disabling/enabling of module core functionalities are expected to be done by user through `vim.b.mini*_disable` variables. [Here](https://github.com/echasnovski/mini.nvim/blob/02e22656f1b78aa9f9a678e0ff31b62bbaf0dee6/doc/mini.txt#L164) is documentation about it. And your case is covered with [this](https://github.com/echasnovski/mini.nvim/blob/02e22656f1b78aa9f9a678e0ff31b62bbaf0dee6/doc/mini.txt#L199-L202).

If you have Neovim>=0.7, try adding this to your config **before** call to `require('mini.cursorword').setup()`:

```lua
vim.cmd([[
  augroup MyMini
    autocmd!
    au ModeChanged *:[vV\x16]* let b:minicursorword_disable=v:true
    au ModeChanged [vV\x16]*:* let b:minicursorword_disable=v:false
  augroup END
]])
```

Does this solve your problem?

**Comment by fnix2** [comment]
Yes, that's exactly what i need, thanks
