### ISSUE TITLE
mini.files : Issue with filepath containing parentheses on MS Windows

### ISSUE THREAD

**Issue by harg** [echasnovski/mini.nvim#1270]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

mini.files is unable to open a file whose path contains parentheses

### Neovim version

0.10.2

### Steps to reproduce

OS: Windows 10
Install latest nvim & mini.files
Navigate the filesystem and open a folder with parenthesis in its name
Open a file

### Expected behavior

The selected file is opened

### Actual behavior

mini.files opens an empty buffer, the filepath is incorrect, missing a backslash in the filepath

![image](https://github.com/user-attachments/assets/3b4a91c0-a329-4ab8-a7a9-df82790bfcf0)

**Comment by echasnovski** [comment]
Thanks for the issue!

This was already discussed #1237 with explanation of solution in [this comment](https://github.com/echasnovski/mini.nvim/issues/1237#issuecomment-2366878051).

Closing as duplicate and working as expected.

**Comment by harg** [comment]
Oops , sorry for that! Thank you very much for your support.
