### ISSUE TITLE
mini.pairs: Unexpected behaviour when pressing <CR> in InsertMode

### ISSUE THREAD

**Issue by primeapple** [echasnovski/mini.nvim#1273]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pairs

### Description

So I co-maintain a plugin for autosaving (see https://github.com/okuuva/auto-save.nvim). One functionality we offer is to provide a `defer_save` and a `cancel_deferred_save` action. Each of these gets a list of events. When one of these events trigger the action is triggered.
As you might guess, `defer_save` defers a save to be run in the future, where as `cancel_deferred_save` cancels a pending save. By default the events are:
```lua
    defer_save = { "InsertLeave", "TextChanged" },
    cancel_deferred_save = { "InsertEnter" },
```

Now we had users report a weird thing. When pressing `<CR>` betwen e.g. `{}` in insert mode, a save would be deferred. We realized it is because of this plugin, since it remaps `<CR>` in these situations. I'm not sure what happens but it looks it triggers `"InsertLeave"` but won't trigger `"InsertEnter"`, because of this code: https://github.com/echasnovski/mini.pairs/blob/694d9beb488ff1afaf3d1977b067e53c827d9af5/lua/mini/pairs.lua#L398
In the end it leads to an unexpected save confuses the user.

How could we go on with this? User @akikanellis showed some solutions here: https://github.com/okuuva/auto-save.nvim/issues/57#issuecomment-2322882389 . Maybe you could give some feedback.

### Neovim version

0.10.2

### Steps to reproduce

 
I will provide one if needed, but I think it's more of a technical problem.

### Actual behavior

?

**Comment by echasnovski** [comment]
Thanks for the issue!

> I'm not sure what happens but it looks it triggers `"InsertLeave"` but won't trigger `"InsertEnter"`, because of this code: https://github.com/echasnovski/mini.pairs/blob/694d9beb488ff1afaf3d1977b067e53c827d9af5/lua/mini/pairs.lua#L398

This code prevents listed events from being triggered during execution of `<C-o>` which accompanies `<CR>` . See 2049bca9c51214ef61a9c29e05cc7ef82556840b for more details.

Both in tests and right interactively I can not reproduce the "... it triggers `"InsertLeave"` but won't trigger `"InsertEnter"` ..." part. Typing in Insert mode `<CR>` with cursor inside `{}` and 'mini.pairs' set up *does not* trigger any of the listed there events. Entering and exiting Insert mode with a regular `i` and `<Esc>` still work as expected. So I would need a reproduction example here, please (with latest `main` branch, of course).

**Comment by echasnovski** [comment]
What 'mini.pairs' *does* do, though, is triggering `TextChanged` event in `<CR>` (which you outline [here](https://github.com/okuuva/auto-save.nvim/issues/57#issuecomment-2303797088)). And this indeed seems like an issue.

Would you mind checking if applying the following patch to 'mini.pairs' solves the issue on your end?

```diff
diff --git a/lua/mini/pairs.lua b/lua/mini/pairs.lua
index c32efb3..4e2b20f 100644
--- a/lua/mini/pairs.lua
+++ b/lua/mini/pairs.lua
@@ -395,7 +395,7 @@ MiniPairs.cr = function(key)
     -- Temporarily ignore mode change to not trigger some common expensive
     -- autocommands (like diagnostic check, etc.)
     local cache_eventignore = vim.o.eventignore
-    vim.o.eventignore = 'InsertLeave,InsertLeavePre,InsertEnter,ModeChanged'
+    vim.o.eventignore = 'InsertLeave,InsertLeavePre,InsertEnter,TextChanged,ModeChanged'
     H.restore_eventignore(cache_eventignore)
 
     -- Temporarily redraw lazily for no cursor flicker due to `<C-o>O`.
```

**Comment by echasnovski** [comment]
I am pretty sure that triggered `TextChanged` was the culprit here and it now should be fixed on latest `main`.

It would be still useful to see a possible confirmation that 'okuuva/auto-save.nvim' now works with 'mini.pairs'.

**Comment by akikanellis** [comment]
@echasnovski I tested this out with latest `mini.pairs` and `auto-save.nvim` and it is working as expected, making the `vim.api.nvim_get_mode()["mode"] ~= "niI"` fix from [my comment](https://github.com/okuuva/auto-save.nvim/issues/57#issuecomment-2322882389) redundant. Thank you for the fix!

**Comment by primeapple** [comment]
I also tested it and everything works now. Thanks a lot @echasnovski , there is a reason I switched most of my plugins to their mini equivalent :)
