### ISSUE TITLE
Please make mini.clue autostart\always-showing without needing a trigger key like in nano.

### ISSUE THREAD

**Issue by aliresool621** [echasnovski/mini.nvim#1274]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

https://www.reddit.com/r/neovim/s/MQqQEI9ecz i asked on reddit and got no answer 

It will definitely help a noob(and others) like me use neovim, or just people who like this type of feature

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think this is a good design idea. The main use case for 'mini.clue' is to show clues for sets of "nested" mappings, primarily starting with `<Leader>`.

Closing as not planned.
