### ISSUE TITLE
[mini.completion] extra garbage in completed function

### ISSUE THREAD

**Issue by ngortheone** [echasnovski/mini.nvim#1277]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

Hi @echasnovski !

I recently switched from `hrsh7th/nvim-cmp` to `mini.completion`. Everything seems to work great out of the box except for one thing. When completing functions with LSP (I use golang, but I think it is true for all LSPs) the completed function appears with some garbage where parameters should be.

Example: I complete `Logger.Info` function which takes some parameters. 
The completed line looks like this
```go
Logger.Info(${1:})
```

This `${1:}` is the garbage. I didn't find a way to disable it. Please help.

### Neovim version

v0.11.0-dev-957+g0e42c81c7f 

### Steps to reproduce

1. Setup any LSP (gopls in my case)
2. Open any codebase
3. Start typing a funcion name, complete a function name.
4. Observe garbage where function parameters should be!

### Expected behavior

Function's parameter list should be empty

### Actual behavior

Garbage `${1:}` appears

**Comment by GitMurf** [comment]
@ngortheone these are for snippet placeholders from the lsp which mini.completion does not support yet.

See here for same issue on TypeScript and Lua and how to fixed it (assume similar setting for Go LSP but I have no Go experience): 

- https://github.com/echasnovski/mini.nvim/issues/193#issuecomment-2017435585
- https://github.com/echasnovski/mini.nvim/issues/193#issuecomment-2028049110

See here for conversation on future mini.snippets being a module (WIP but nothing available yet): https://github.com/echasnovski/mini.nvim/issues/886#issuecomment-2390989574

**Comment by echasnovski** [comment]
Thanks for the issue!

Indeed, as @GitMurf said, this comes from LSP server advertising completion item as not 'Snippet' kind but instead completing as if it was a snippet.

I was also told somewhere (can not find this, unfortunately), that this can be controlled via [`textDocument.completion.completionItem.snippetSupport`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#completionClientCapabilities) server capability. I.e. setting this to `false` in your LSP setup (at least until there is snippet support in 'mini.completion') should fix the issue.

**Comment by gonzaloserrano** [comment]
@echasnovski execute my limited knowledge, but do you have an example on how to disable `snippetSupport` within a basic nvim config? I've run into the same "garbage" issue.

**Comment by echasnovski** [comment]
Judging by your dotfiles, you use 'nvim-lspconfig'. In that case I'd suggest passing it directly to the `require('lspconfig').gopls.setup()` with something like this:

```lua
require('lspconfig').gopls.setup({
  capabilities = {
    textDocument = {
      completion = {
        completionItem = {
          snippetSupport = false,
        },
      },
    },
  },
})
```

Although in your case you seem to use 'ray-x/go.nvim', in which case there is [a separate way to configure LSP server](https://github.com/ray-x/go.nvim?tab=readme-ov-file#lsp). So I'd say it would be something like this:

```lua
require('go').setup({
  lsp_cfg = {
    capabilities = {
      textDocument = {
        completion = {
          completionItem = {
            snippetSupport = false,
          },
        },
      },
    },
  },
})
```

**Comment by gonzaloserrano** [comment]
Indeed! It was very kind of you to take the time to check out my dotfiles and gather the exact answer I needed for a go.nivm setup. Thanks! ❤️

**Comment by jakubsmolaga** [comment]
I don't know if this will be useful to anyone else but I had a similar issue and ended up writing a little hack that just always tries to expand the inserted text (which just does nothing if the text does not include any snippet placeholders). I'm using `vim.snippet.expand` which requires neovim 0.11, but you can replace it with any other engine for expanding the snippets.
```lua
-- autoexpand.lua

local clear_text = function (r1, c1, r2, c2)
	vim.api.nvim_buf_set_text(0, r1, c1, r2, c2, {})
end

local get_line = function (row)
	return vim.api.nvim_buf_get_lines(0, row, row + 1, false)[1]
end

local remove_inserted_text = function (txt)
	local cursor = vim.api.nvim_win_get_cursor(0)
	local row, col = cursor[1] - 1, cursor[2]
	local _, num_extra_lines = txt:gsub("\n", "\n")
	if num_extra_lines == 0 then
		clear_text(row, col - txt:len(), row, col)
		return
	end
	local start_row = row - num_extra_lines
	local buf_line1 = get_line(start_row)
	local txt_line1 = txt:match("^[^\n]*")
	local start_col = buf_line1:len() - txt_line1:len()
	clear_text(start_row, start_col, row, col)
end

local expand_lsp_snippet = function()
	local path = { "user_data", "nvim", "lsp", "completion_item" }
	local item = vim.tbl_get(vim.v.completed_item, unpack(path))
	local txt = vim.tbl_get(item or {}, "insertText")
	local fmt = vim.tbl_get(item or {}, "insertTextFormat")
	if fmt ~= 2 or txt == 0 then return end
	remove_inserted_text(txt)
	vim.snippet.expand(txt)
end

local setup = function ()
	vim.api.nvim_create_autocmd("CompleteDone", {
		callback = expand_lsp_snippet,
	})
end

return { setup = setup }
```
I never wrote any lua before this so I'm sure this code is awful and has lots of bugs, but so far it's been working great for me so maybe someone will find it useful :smile:

**Comment by GitMurf** [comment]
> I'm not sure how to do this without modifying the plugin code because I can't just copy it into the config since it uses H which is not exported.

You need to either fork and make the change to your fork and use that instead of mini repo (but then you have to monitor and rebase whenever changes occur upstream). 

Or you can manually go edit the line in your neovim data folder where all your plugins are actually installed to and can just manually edit the code directly.

**Comment by echasnovski** [comment]
> I'm not sure how to do this without modifying the plugin code because I can't just copy it into the config since it uses `H` which is not exported.

You can write and set your own [`config.lsp_completion.process_lsp_items`](https://github.com/echasnovski/mini.nvim/blob/1bd64e3ce49964cdfa9ee0e84c56f42d53b89052/doc/mini-completion.txt#L218). If you need highlighting of item kind (which is what `H.make_add_kind_hlgroup()` is for), then you can copy [its definition](https://github.com/echasnovski/mini.nvim/blob/1bd64e3ce49964cdfa9ee0e84c56f42d53b89052/lua/mini/completion.lua#L887-L904) (change usage of `H.kind_map` for custom `local kind_map` prior) into your config. Without comments it is fairly concise.
