### ISSUE TITLE
mini.tabline: colored icons

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#1279]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

tabline

### Description

The `mini.icons` module allows icons to be colored using `MiniIcons*` highlight groups. However, `mini.tabline` does not actually use these highlights. It would be nice if there was an option for that.

Note that since the tabline often uses a different background color, it may be impossible to make the icons look right with the default highlight groups. This could be solved by having separate highlights for each combination of tabline and icon highlight group: `MiniTablineCurrentIconRed`, etc.

## Attempted workaround

I tried to implement this myself by using a custom `MiniTabline.config.format` function which adds highlight specifiers. However, it turns out that `mini.tabline` escapes percent signs, which makes it impossible to use any tabline formatting in the result. So another option, which could also have other use-cases, would be to allow not escaping the string returned by `MiniIcons.config.format`.

**Comment by echasnovski** [comment]
Thanks for the suggestion, Adam! Glad you still use 'mini.nvim' :)

Similar suggestion was discussed in #153. Those are indeed slightly different cases: 'nvim-web-devicons' has separate highlight group for each icon while 'mini.icons' intentionally uses fixed set of highlight groups. So indeed defining own set of highlight groups is possible here.

Having it be possible to achieve with `config.format` is indeed a good approach. So forced `%` escaping I'd say even a bug and should be done inside `default_format()` (not after `format`).

There is still an issue, though: highlighting in tabline/statusline/winbar can only be done as a "switch" (i.e. "highlight all characters to the right with *this* highlight group). As tabs in tabline can change colors interactively, adding colors to icons needs to also "reset" added color to the highlight group of the tab, which is not passed to `format` currently. But I think the use case with 'mini.icons' is reasonable enough for this to be added.

I'll take a look.

**Comment by echasnovski** [comment]
I thought I have resolved this, but I didn't take into account that tab width is computed based on the `config.format` output. If it contains any special constructs (like `%#HLname#`, for example), it interferes with computing which tabs should be shown.

This needs more time and effort, I am afraid.

**Comment by echasnovski** [comment]
I am afraid I have to close with resolution "'mini.tabline' can have only predefined set of full tab colors". Another way to put it is "an output of `config.format` will be treated strictly as text".

The full explanation is in 70862cc80182dfb6ff6f0e869c439011e4e874b8 commit message. TL;DR:
- Allowing colored icons requires respecting special 'statusline' like constructs in output of `config.format`.
- It conflicts with the requirement of being able to partially show a tab.
- Together with other complexity issues I think it is reasonable to document this as a known limitation.

**Comment by echasnovski** [comment]
> I guess I’ll have to configure my tabline manually now. :P

It's a bit more tedious than statusline specifically for the reason mentioned here: the content can not fit in the available width and there needs to be *some* truncating going on. So beware.

**Comment by edte** [comment]
hello, Is this issue solved?

**Comment by echasnovski** [comment]
> hello, Is this issue solved?

Hi! It is *re*solved with "sorry, it brings more troubles than usefulness". See [this comment](https://github.com/echasnovski/mini.nvim/issues/1279#issuecomment-2419762549) for more details.
