### ISSUE TITLE
Surround without adding spaces

### ISSUE THREAD

**Issue by CleoMenezesJr** [echasnovski/mini.nvim#128]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

An option would be cool to turn off this behavior. Particularly whenever I use the mini.surround, I have to be manually removing the spaces.
`[ "something" ]` -> `["something"]`
`( "something" )` -> `("something")`
`{ "something" }` -> `{"something"}`

**Comment by echasnovski** [comment]
This is the behavior of open brackets (`(`, `[`, `{`, `<`). [Here](https://github.com/echasnovski/mini.nvim/blob/02e22656f1b78aa9f9a678e0ff31b62bbaf0dee6/doc/mini-surround.txt#L158-L169) are examples and [here](https://github.com/echasnovski/mini.nvim/blob/02e22656f1b78aa9f9a678e0ff31b62bbaf0dee6/doc/mini-surround.txt#L189-L190) is this in documentation.

You have two options:
- Use corresponding close bracket (`)`, `]`, `}`, `>`) to add brackets without spaces. This is preferred solution.
- Make custom surroundings:
```lua
require('mini.surround').setup({
  custom_surroundings = {
    ['('] = { input = { '%b()', '^.().*().$' }, output = { left = '(', right = ')' } },
    ['['] = { input = { '%b[]', '^.().*().$' }, output = { left = '[', right = ']' } },
    ['{'] = { input = { '%b{}', '^.().*().$' }, output = { left = '{', right = '}' } },
    ['<'] = { input = { '%b<>', '^.().*().$' }, output = { left = '<', right = '>' } },
  },
})
```
