### ISSUE TITLE
mini.tabline: diagnostics and diff indicators

### ISSUE THREAD

**Issue by 0xJWLabs** [echasnovski/mini.nvim#1280]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

It would be incredibly useful if `mini.tabline` could display diagnostics and git diff indicators directly on each tab. This enhancement would help users quickly identify which tabs have errors, warnings, or modified content, without switching back and forth between buffers.

## Proposed Features

	1.	Diagnostics Indicator: Display error, warning, and hint counts (or icons) on each tab that correspond to the current diagnostics in the buffer.
	2.	Diff Indicator: Show git status (modified, added, deleted) as part of the tab label.

## Use Cases

	•	Easily identify which buffers need attention (e.g., those containing errors or warnings) while navigating between multiple buffers/tabs.
	•	Quickly spot modified files in a git repository, helping with version control workflows.

## Possible Configurations

	•	Allow users to configure which indicators to show (e.g., only errors, or all diagnostics).
	•	Customize the symbols/icons used for diagnostics and git diff.
	•	Option to toggle the feature on/off via settings.

## Benefits

	•	Streamlines development workflows by providing immediate feedback on file statuses.
	•	Helps users manage multiple buffers more efficiently by showing essential information at a glance.

## References

	•	Other plugins like `bufferline.nvim` have similar functionality, which could serve as inspiration for implementing this in `mini.tabline`.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I am afraid all of this is out of scope for being built-in into 'mini.tabline' as too complex (and in my opinion not really suitable for being part of tabline). In theory all of this is possible via `config.format` (as it takes buffer identifier as an argument) and that will be it.

Closing as not planned.

**Comment by 0xJWLabs** [comment]
Okay since it’s not planned but you understand neovim more, can you give me snippets of how to do it? Thanks! @echasnovski

**Comment by echasnovski** [comment]
You can take a look at how 'mini.statusline' does this: [`section_diff()`](https://github.com/echasnovski/mini.nvim/blob/df1559e2ed7ece458e0a97a8bb9556d465d1c775/lua/mini/statusline.lua#L301) for diff data and [`section_diagnostics()`](https://github.com/echasnovski/mini.nvim/blob/df1559e2ed7ece458e0a97a8bb9556d465d1c775/lua/mini/statusline.lua#L326) for diagnostics.

**Comment by 0xJWLabs** [comment]
To make tabline is similar to make statusline? @echasnovski

**Comment by echasnovski** [comment]
`config.format` in 'mini.tabline' should return a string used as a tab label. Both linked sections from 'mini.statusline' also return strings. Those can be used to construct your own `MiniTabline.config.format`. I will not be posting the full working code for showing diff and/or diagnostics in 'mini.tabline' tabs because I think this is a bad practice to do so.
