### ISSUE TITLE
mini.ai add another object matching rule?

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1281]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

given the text:

```
"aaa"bbb"ccc"
```

when the cursor is on the middle `b`, i want to use `di"` to delete the three `b` characters
mini.ai delete three `c` characters instead

i know that mini.ai groups the first and second quotation marks as one pair, and the third and fourth quotation marks as another pair

but i prefer the original, slightly dumber behavior, as it's more intuitive

it is also more user-friendly for cases like `case "$(printf "%s" "$arg")" in...`

users can still delete the three `c` characters via next/last prefix

**Comment by echasnovski** [comment]
This is already possible with [`custom_textobjects`](https://github.com/echasnovski/mini.nvim/blob/df1559e2ed7ece458e0a97a8bb9556d465d1c775/doc/mini-ai.txt#L464). To change textobject with id `"` to use regular 'from " to "' matching without balancing, use the following:

```lua
require('mini.ai').setup({
  custom_textobjects = {
    -- Match without balancing
    ['"'] = { '"().-()"' },
  },
})
```
