### ISSUE TITLE
mini.icons(`c`): current icon is confusing

### ISSUE THREAD

**Issue by Zeioth** [echasnovski/mini.nvim#1286]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.icons

### Description

See on the bottom left of the screen

---

**Current icon**
![screenshot_2024-10-17_20-57-47_600999717](https://github.com/user-attachments/assets/8b211e90-78f0-45fa-a288-a59a2394b2b1)

**Proposed icon**
![screenshot_2024-10-17_20-57-14_873788753](https://github.com/user-attachments/assets/db96d1e3-0007-40b8-a594-3f1595042aae)

You can find the commit here: https://github.com/echasnovski/mini.icons/compare/main...Zeioth:mini.icons:main
(The repo have no permission to send PRs)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The current icon is `nf-md-language_c` from Nerd Fonts. The `nf-md-language` is preferred over other alternatives for consistency. You can override this icon in `config.filetype` with `c = { glyph = '' }` entry.

Closing as not planned.

**Comment by Zeioth** [comment]
@echasnovski the proposed icon is part in nerd fons:
![screenshot_2024-10-17_21-11-56_728860197](https://github.com/user-attachments/assets/a830b12d-40df-4f0e-bf86-94ba3e5ac06b)

If you refer to the notation `nf-md-` that's ok, your choice ^_^

**Comment by echasnovski** [comment]
> If you refer to the notation `nf-md-` that's ok, your choice ^_^

Yes, [it is documented](https://github.com/echasnovski/mini.nvim/blob/e5273e8a01597e9b71c015abb2b1f4278892e12a/doc/mini-icons.txt#L305-L306).
