### ISSUE TITLE
docs: use video format supported by Firefox for screencasts

### ISSUE THREAD

**Issue by przepompownia** [echasnovski/mini.nvim#1287]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.notify for example

### Description

![image](https://github.com/user-attachments/assets/14fa445f-f503-4d66-b4f9-e82f25eaff9c)

No problem with manually downloading such demos and using mpv or other player but it would be nice to play such demos in Firefox. To convert screencasts from gnome-shell I use ffmpeg wrapped by bash function:

```bash
screencast_to_yuv_420p ()
{
    declare in out helpMessage;
    helpMessage='screencast_to_yuv_420p in out';
    in="${1?${helpMessage}}";
    out="${2?${helpMessage}}";
    ffmpeg -i "${in}" -vf 'pad=ceil(iw/2)*2:ceil(ih/2)*2' -pix_fmt yuv420p "${out}"
}
```

**Comment by WizOfOz-1** [comment]
+1

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I too use Firefox and everything works fine. There are *very rare* instances of the same issue, but refreshing the page loads the video fine.

What operating system and Firefox version do you use? Also, did you try going through [list of steps suggested by Firefox](https://support.mozilla.org/en-US/kb/fix-common-audio-and-video-issues)?

------

All demo videos are recorded as mp4 video files with H.264 codec. This codec is [recommended by GitHub itself](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files).

**Comment by przepompownia** [comment]
Hm, after refreshing the video became available, but not sure how often it works. At the moment I then cannot see the error reported in console. In the past Firefox complained about unsupported pixel format (yuv444). 

On the other side, after manually download https://github.com/echasnovski/mini.nvim/assets/24854248/81014300-3380-4b8c-9ab5-ba09345032d7 I see (by `ffprobe`) `yuv420p` format, the same as suggested by me above. I then have no idea what happened. 

More: I converted this video to pixel format `yuv444p` and FF can play it for me. 

Currently I use FF 132.0b5 (Developer Edition) on Debian Sid. 

Finally, it seems that this issue can be closed in this form, especially that both pixel formats are supported.

**Comment by przepompownia** [comment]
In other words it would probably be better to open a separate issue containing any related error displayed in the console.
