### ISSUE TITLE
[mini.indentscope] Allow to specify multiple indent colors

### ISSUE THREAD

**Issue by dgmora** [echasnovski/mini.nvim#1294]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

It would be useful to have different (or "rainbow") colors for different indentation levels. Is this something you would consider implementing?

Thanks!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The current highlighting ([regular and when indent is "off"](https://github.com/echasnovski/mini.nvim/blob/9618cf56e76cc0caab54ad60116a8d72f99d7b3b/doc/mini-indentscope.txt#L58-L62)) provides enough information to be useful. On the other hand, rainbow indent levels are mostly useful if there can be several of them shown, while 'mini.indentscope' has (and will have) only one shown at a time.

Closing as not planned.

**Comment by dgmora** [comment]
My bad, I was mixing what mini.indentscope does with what indent-blankline does!
