### ISSUE TITLE
mini.rainbow

### ISSUE THREAD

**Issue by Song-Tianxiang** [echasnovski/mini.nvim#1297]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.nvim

### Description

Can we have a new module [mini.rainbow]. 
> highlights delimiters such as parentheses, brackets or braces according to their depth

like:
- [neovim rainbow](https://github.com/HiPhish/rainbow-delimiters.nvim)
- [emacs rainbow](https://github.com/Fanael/rainbow-delimiters)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already suggested in #1157 with the following resolution:

> I generally don't really like the idea of rainbow-ing repetitive objects (brackets, delimiters, indent guides, etc.). So I don't think this will be supported as a separate module.

Closing as not planned.
