### ISSUE TITLE
A function to automatically detect indent style of file, tabs or 2,4,6,8 spaces etc.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1298]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.misc

### Description

Hi echasnovski! Do you think it a good feature to add a function to mini.misc which can detect the indentation type of the file and change shiftwidth, expandtab, softtabstop and tabstop values accordingly?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think that this type of functionality is better reserved for filetype plugins (together with proper filetype detection and probably per-project '.editorconfig').

Closing as not planned.
