### ISSUE TITLE
[mini.test] Ability to change screenshot directory

### ISSUE THREAD

**Issue by stasjok** [echasnovski/mini.nvim#1299]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.test

### Description

Currently `expect.reference_screenshot` places all screenshots in `tests/screenshots/` directory. Also it accepts a complete path to the screenshot. I think it can be useful to define the default directory to store screenshots. And allow to override it per `expect.reference_screenshot`. Why? Because the logic to generate the unique filenames is still useful, but I would like to store screenshots closer to the actual tests, not in a big pile in one directory. Potentially the option can also be a function that returns a screenshot directory for the current test file.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think this use case makes sense and code change is fairly minimal. I'll look into it.

**Comment by echasnovski** [comment]
This now should be possible on latest `main` with [`opts.directory` option](https://github.com/echasnovski/mini.nvim/blob/92ff9f0a1291a1bddc8e5a8535dc02930d4d7203/doc/mini-test.txt#L586-L587). Thanks again for the idea!
