### ISSUE TITLE
Beta-testing 'mini.sessions'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#13]
Please leave your feedback about new 'mini.sessions' module here. Feel free to either add new comment or positively upvote existing one.

Some things that I am interested to find out (besides seemingly omnipresent bugs):

- Are configuration and function names intuitive enough? In particular, names `read` and `write` for managing session files. I understand that they are *different* from `load` and `save` in 'vim-startify', but are they intuitive enough for you?
- Are default values of settings convenient for you?
- Is documentation clear enough?

**Comment by xigoi** [comment]
I would appreciate if it was possible to create project-local sessions. Or alternatively, automatically make the outer terminal `cd` to the correct directory when opening a session (is that even possible?) Sorry if this is already a thing, I haven't played around that much with sessions.

**Comment by echasnovski** [comment]
Thanks for for feedback!

Well, session is just a file which should be sourced. There is a possibility to create project-local sessions: look for certainly named file (`Session.vim` by default) inside current working directory. I thought about it but decided to stick to what 'vim-startify' seemed to be doing.

I wasn't sure how to align this possibility with quite clean idea of "all session files are stored in this configured directory". Maybe something like `MiniSessions.config.use_local`? If `nil`, don't search in current working directory, if string - search for that file inside current working directory and display it first?

**Comment by echasnovski** [comment]
Adam, thank you once again for constructive feedback. I never use local sessions because i use start screen to choose a session, so I just forgot to implement this.

Now 'mini.sessions' can handle global and local sessions. It is primarily designed for two workflows:
- Use global sessions (files stored in configured directory) together with 'mini.starter' to choose them upon opening.
- Use local sessions (configured file that is stored inside current working directory) which will be automatically sourced if `config.autoread` is `true` and global sessions are disabled.
