### ISSUE TITLE
Don't highlight `@lsp.mod.defaultLibrary`

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#1301]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

base16, hues

### Description

`@lsp.mod.defaultLibrary` is very aggressive, and the logic behind what it considers to be from defaultLibrary seems almost arbitrary. In [neovim/neovim#27929](https://github.com/neovim/neovim/pull/27929), it was agreed not to highlight it. Perhaps we should follow suit for both modules with mini?

![image](https://github.com/user-attachments/assets/abd71465-1b3e-4626-bbf3-d57b4fa6a7d5)

vs

![image](https://github.com/user-attachments/assets/779e91fe-7549-4121-b36a-1a4ad34ce66b)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> In https://github.com/neovim/neovim/pull/27929, it was agreed not to highlight it.

The main point was that it was too aggressive for default color scheme. I still think that having `Special` color be used for anything "default" is a good idea *in theory*. If some LSP overuses it, it's bad. I'll take a further look beyond only C++.

**Comment by echasnovski** [comment]
After looking at the result in several LSP servers, they all indeed seem to go too far with adding the `defaultLibrary` modifier. On latest `main` it now should be not highlighted. Thanks again for the suggestion!
