### ISSUE TITLE
[mini.diff] Add option to use both 'sign' and 'number' visualization style

### ISSUE THREAD

**Issue by dafta** [echasnovski/mini.nvim#1302]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.diff

### Description

Currently, users have the choice to use either the 'sign' or the 'number' visualization for hunks in `view.style`. It would be great to add an option to have both on at the same time.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think this is a bit too much and will introduce redundancy without much benefit.

Closing as not planned.
