### ISSUE TITLE
Improvents in colorfulness in mini.base16

### ISSUE THREAD

**Issue by wizardlink** [echasnovski/mini.nvim#1303]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.base16

### Description

Howdy! Hope this issue finds you in good health.

I'm submitting this issue in regards to the lack of colorfulness in a few languages when generating a color scheme using `mini.base16`; I've found [catppuccin](https://github.com/catppuccin/base16/)'s base16 colors strenuous to read with. I'll highlight today two instances where this occurs.

## C
![image](https://github.com/user-attachments/assets/5f47b1f9-fc3f-4038-b136-45067fcdfd29)

As seen in this case, constants, variables and operators are all the same color, it isn't unreadable but makes recognizing who is who, harder in my opinion. According to the base16 styling guidelines, variables should be the color `08` and not the current `05`.

I've attempted to fix this in [wizardlink/mini.base16](https://github.com/wizardlink/mini.base16) but found the unfortunate side effect that constants have the same color as variables, not too familiar with highlight groups, so probably that's why it did not work as expected.

## HTML

![image](https://github.com/user-attachments/assets/b0b1cacf-def5-466b-8bbe-7e52ad3d058e)

I think this is an easy one to see why it is a problem... I have a hard time reading this when it comes to larger code, styling guidelines here also says that tags should be `08` instead of `0A`, while the delimiter being `05`, which I think improves the problem.

This is what I ended up with by trying to follow the guideline:
![image](https://github.com/user-attachments/assets/18a07643-2987-411e-bb89-d1f5e22b3b55)

Not quite sure why the text became white, but my biggest concern were the tags, which to me are more readable, albeit,  not by a large margin with this color scheme.

## Closing thoughts

Your plugins have saved me time and time again, thank you! These changes don't need to be made, but I would love to see the plugin flourish into a more colorful one.

**Comment by echasnovski** [comment]
Thanks for the suggestion and kind words!

I believe both instances showcase the effect of tree-sitter highlighting. For example, if you execute `:Inspect` with cursor on the cell which highlighting you want to know, it will show a `Treesitter` section with highlight groups like `@variable.c`, `@constant.c`,`@tag.html`, and `@tag.delimiter.html`.

This can also be the effect of LSP semantic tokens. In this case you'll see a `Semantic Tokens` section with groups like `@lsp.type.macro.c`, etc.

Language-specific precise tree-sitter and semantic token highlighting is (mostly) out of scope of 'mini.base16' (and 'mini.hues', for that matter). They are suggested to be tweaked by the user:
- Execute `:Inspect` on the part you wish to customize.
- See which tree-sitter/LSP highlight group is responsible for this. It should have a language suffix at the end.
- Customize it as a regular highlight group. For example, with something like `vim.api.nvim_set_hl(0, '@variable.c', { link = 'Identifier' })` (i.e. link to some built-in basic highlight group) or directly define the foreground color (as palette is known to the user).

Hope this helps.

------

Closing as not planned.
