### ISSUE TITLE
mini.surround still depends on timeoutlen

### ISSUE THREAD

**Issue by mjrogozinski** [echasnovski/mini.nvim#1305]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

With default mappings, even if |s| is diabled with 
```vim.keymap.set({ 'n', 'x' }, 's', '<Nop>')``` 
as [described in the documentation](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-surround.txt#L573C3-L573C45) , the combination "sa" needs to be pressed within timeoutlen.

However, for example combination "dd" does not. 

### Neovim version

v0.10.1

### Steps to reproduce

In a text file containing text, press s. 
Wait longer than timeoutlen.
Press a.

### Expected behavior

after pressing iw) the word under cursor will be surrounded by ()

### Actual behavior

iw) are inserted inside of the word. Because "a" acted like a normal nvim command.

**Comment by echasnovski** [comment]
This is how mappings work in Neovim: if mapping contains more than one key press, each of them should be pressed no longer than 'timeoutlen' milliseconds after the previous. The documentation says that it will prevent occasional usage of built-in `s` action (which will delete character under cursor and start Insert mode) and it does exactly that.

> However, for example combination "dd" does not.

`dd` is not a mapping created by user but keys for built-in action, which can behave differently.
