### ISSUE TITLE
mini.notify: Option to ignore certain notifications

### ISSUE THREAD

**Issue by marcelarie** [echasnovski/mini.nvim#1306]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.notify

### Description

Hi, I would like a way of ignoring certain messages for specific LSP progress. 

For example, `rust-analyzer` seems to be really loud about each event, and I would like to know only when it is ready:
![2024-10-24-141757_hyprshot](https://github.com/user-attachments/assets/614ba633-e955-4ce7-ba02-01ab091e6a81)

Is there any way of doing this? Thanks!

**Comment by echasnovski** [comment]
The [`content.sort` can be used to define order and/or filter items](https://github.com/echasnovski/mini.nvim/blob/77533e69cc4fadb7f4c25f23255ae0890a058818/doc/mini-notify.txt#L142-L147). For example, [I use it for similar purpose for LuaLS](https://github.com/echasnovski/nvim/blob/f30b003cb2f30b928a03a095af849fd49c2c95e9/init.lua#L68-L76).

**Comment by marcelarie** [comment]
Thanks!

**Comment by marcelarie** [comment]
I left my config with the implementation that I did in case someone sees it useful:

```lua
return {
	"echasnovski/mini.notify",
	version = "*",
	config = function()
		local notify_filter = function(notif_arr)
			local filter = function(notif)
				if vim.startswith(notif.msg, "rust_analyzer: ") then
					return notif.msg:match "Indexing "
				end
				-- Keep others
				return true
			end
			notif_arr = vim.tbl_filter(filter, notif_arr)
			---@diagnostic disable-next-line: undefined-global
			return MiniNotify.default_sort(notif_arr)
		end

		local opts = {
			-- Content management
			content = {
				-- Function which formats the notification message
				-- By default prepends message with notification time
				format = nil,

				-- Function which orders notification array from most to least important
				-- By default orders first by level and then by update timestamp
				sort = notify_filter,
			},

			-- Notifications about LSP progress
			lsp_progress = {
				-- Whether to enable showing
				enable = true,

				-- Duration (in ms) of how long last message should be shown
				duration_last = 1000,
			},

			-- Window options
			window = {
				-- Floating window config
				config = {
					border = "none",
				},

				-- Maximum window width as share (between 0 and 1) of available columns
				max_width_share = 0.582,

				-- Value of 'winblend' option
				winblend = 25,
			},
		}

		require("mini.notify").setup(opts)
	end,
}
```
