### ISSUE TITLE
support for `Three read-only registers ":, "., "%` of `gr` operator

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1307]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.operators

### Description

can't use `"%` `".` `":` registers with `gr` operator

### Neovim version

v0.10.2

### Steps to reproduce

press `"%grr` and an error occurs:

```
E5108: Error executing lua Vim:E354: Invalid register name: '%'
stack traceback:
        [C]: in function 'setreg'
        .../.local/share/nvim/lazy/mini.nvim/lua/mini/operators.lua:1033: in function 'replace_do'
        .../.local/share/nvim/lazy/mini.nvim/lua/mini/operators.lua:483: in function <.../.local/share/nvim/lazy/mini.nvim/lua/mini/operators.lua:460>
```

### Expected behavior

replace current line with file name

### Actual behavior

error

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce. This indeed seems to be related to the fact that those registers are read-only. I'll take a look.

**Comment by echasnovski** [comment]
This (and a more general "support all special registers" functionality) should now be fixed on latest `main`.

It also revealed small issues 'mini.clue', so double thanks for this issue :)

**Comment by aidancz** [comment]
Hi echasnovski

After pressing `"%grr`, the current line and the newline character were replaced, but the newline character should be preserved. Could you please take a look at this?

**Comment by echasnovski** [comment]
> After pressing `"%grr`, the current line and the newline character were replaced, but the newline character should be preserved. Could you please take a look at this?

Yeah, this is because all those readonly registers are treated as charwise by `getreginfo()`. I'll take a look.

**Comment by echasnovski** [comment]
The read-only registers should now also respect the mode on latest `main`. Thanks for finding this!
