### ISSUE TITLE
[mini.pairs] Smarter way to handle <BS>?

### ISSUE THREAD

**Issue by stevalkr** [echasnovski/mini.nvim#1308]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

My expected behavior is:

`((|))`: Pressing `<BS>` twice will delete all parentheses.
`(()|)`: Pressing `<BS>` twice will only remove the inner parentheses.

The current behavior is:

`(()|)`: Pressing `<BS>` twice results in `(`

Is it possible to achieve this behavior? Alternatively, I would like to delete the closing parenthesis `(|)` only when it is auto-paired *just now*, rather than whenever there are matching parentheses around the cursor. But I don't know how to do that.

Thank you!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The first one requires figuring out whether parenthesis are balanced or not. This is out of scope of 'mini.pairs' as it deliberately works [only based on character to the left and character to the right](https://github.com/echasnovski/mini.nvim/blob/77533e69cc4fadb7f4c25f23255ae0890a058818/doc/mini-pairs.txt#L9-L10) (for performance reasons).

The second one is quite tricky to implement as it requires tracking being started *every time* a pair is inserted, which is out of scope (again for performance).

Closing as not planned.
