### ISSUE TITLE
[mini.files] Multiple key mapping for each action | Override default go_in behavior

### ISSUE THREAD

**Issue by MinhTran0911** [echasnovski/mini.nvim#1309]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Recently migrating from nvim-tree to mini.files (and eventually the mini.nvim lib), I was surprised how good and lightweight it is. So thank you for this amazing library.

For mini.files, I saw some features that I felt missing compared to nvim-tree and I hope these would be considered:
1. I would like to have the ability to map multiple keys for as single action like go in or go out. I usually map <CR> and <2-LeftMouse> to open directories or files.
2. Is it possible to override the default behavior of MiniFiles.go_in() (opening the file in a new buffer)? In nvim-tree I was able to setup so that when opening a file it opens in a new tab (or if the file is already opened in a tab then it jumps to that tab (tab drop)).

**Comment by echasnovski** [comment]
Thanks for the suggestion!

1. This is already possible via creating buffer-local mappings in dedicated event, as described in #/879, #534, and #409. The solution is similar in spirit as the [one described in examples](https://github.com/echasnovski/mini.nvim/blob/919b953f044d97a2243cc2d1f0b316a199434127/doc/mini-files.txt#L445) for a different purpose.
2. Yes, it is possible by creating buffer-local mappings together with "disabling" creating a default mapping via `config.mappings.go_in = ''`. The tabpage part of the question is possible via changing the target window (i.e. the window inside which the buffer for the file will be shown). See [this example](https://github.com/echasnovski/mini.nvim/blob/919b953f044d97a2243cc2d1f0b316a199434127/doc/mini-files.txt#L473). You can change the logic of target window change to your liking. Also, couple of clarifications here:
    - The default behavior of `go_in()` in case a file is already opened in *some* buffer is to show that *same* buffer in the target window. Not "open file in a new buffer".
    - My suggestion would be to override the `go_in_plus` behavior leaving `go_in` untouched for common usage (but that is a matter of taste).

Closing as both duplicate and already possible.
