### ISSUE TITLE
[mini.diff] Last empty line is always shown as Changed

### ISSUE THREAD

**Issue by MinhTran0911** [echasnovski/mini.nvim#1310]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.diff

### Description

I setup mini.diff with latest save source, and if I have an empty line at the end of any of my files, then that line would be shown as Changed even though I don't make any modifications to the file. If I have multiple empty lines at the end then only the very last line has this issue.

### Neovim version

0.10.0

### Steps to reproduce

1. In init.lua:
```
local MiniDiff = require('mini.diff')
MiniDiff.setup({
  view = {
    style = 'sign'
  },
  source = MiniDiff.gen_source.save()
})
```
2. Open any file with some text, go to the end of file, add 1 or a few empty lines, then save (:w).
3. Should see the very last line shown as Changed

### Expected behavior

The last empty line should not be marked as changed if it was not added since last saved.

### Actual behavior

![image](https://github.com/user-attachments/assets/c726dd00-ac05-48a3-8643-6f09271019ee)

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce. Would you mind sharing several details?
1. What OS are you using?
2. What is the output of `:=vim.inspect(MiniDiff.get_buf_data(0).ref_text)` in the buffer where you see this behavior? In particular the end of the string (at least several lines in between line endings).
3. What is the output of `:=vim.o.fileformat, vim.o.endofline, vim.o.endoffile, vim.o.fixendofline`?

**Comment by MinhTran0911** [comment]
Hi,
1. Linux (RHEL7.9)
2. At the end of the string it is all "\n" for each empty line
3a. :=vim.o.fileformat --> unix
3b. :=vim.o.endofline --> true
3c. :=vim.o.endoffile --> false
3d. :=vim.o.fixendofline --> true

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.
