### ISSUE TITLE
[mini.deps] Separate the MiniDeps.add command for downloading plugins and adding them to the rtp

### ISSUE THREAD

**Issue by xulongwu4** [echasnovski/mini.nvim#1311]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.deps

### Description

Currently the `MiniDeps.add` function will download the plugin if it is not present on the disk, and add the plugin to the runtime path. There is no separate commands to download plugins based on its source information regardless of whether or not this plugin should be loaded.

I would like to add an command for downloading plugins. This is useful why I lazy load plugins based on, for example, filetypes. Currently, if I add a filetype autocmd to lazy load a plugin, this plugin will be downloaded first, and then added to rtp. This could be a bit cumbersome if I would like the plugin to be loaded instantly so that I can start working on my file immediately.

If we have a command for downloading plugins based on their source info, I can first download all plugins, and then when they need to be loaded, they will be loaded instantly without users realizing that it is being downloaded/loaded.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> If we have a command for downloading plugins based on their source info, I can first download all plugins, and then when they need to be loaded, they will be loaded instantly without users realizing that it is being downloaded/loaded.

I don't think I fully understand the use case you describe. Using the current `add()` will download plugin only one time (per machine configuration) and will add it to runtimepath without downloading afterwards. Do you say that you'd like to have a functionality to even avoid it downloading the first time in exchange of downloading it once during some initial config setup?

**Comment by xulongwu4** [comment]
> Thanks for the suggestion!
> 
> > If we have a command for downloading plugins based on their source info, I can first download all plugins, and then when they need to be loaded, they will be loaded instantly without users realizing that it is being downloaded/loaded.
> 
> I don't think I fully understand the use case you describe. Using the current `add()` will download plugin only one time (per machine configuration) and will add it to runtimepath without downloading afterwards. Do you say that you'd like to have a functionality to even avoid it downloading the first time in exchange of downloading it once during some initial config setup?

Yes that would be what I am looking for. The use case is that, we could set up some plugins to be lazy loaded on filetypes, keystrokes, or user commands. In such cases, if we only have the `add()` API for adding plugins to the rtp, that would mean that these plugins won't be downloaded until they are loaded the very first time. Because these are lazy-loaded plugins, users will not notice that these plugins are not installed until they try to load it through, say, some key bindings. When they type these key bindings, they usually expect it to work immediately. However, we have to bear the initial plugin downloading time. Even worse, sometimes this delay could result in some mysterious nvim error messages.

**Comment by echasnovski** [comment]
Thanks for the follow up!

I think I am going to close this in favor of suggesting to use `add()` in the same way as you'd expect to use its "only download" part. Here is some reasoning:
- Downloading happens only once and I don't think this is a huge inconvenience for users. Moreover, I'd say that the current behavior is beneficial in a sense that the plugin *fully* lazy loaded: it is not even downloaded if it is not used.
- Implementing "download all at once but load only on filetype/keystroke/etc." needs either a separate custom run with downloading all plugins (in which case using `:DepsAdd` should be enough, with possible Neovim restart afterwards) or duplicated separate code lines for downloading and adding (which I'd personally not encourage).

Closing as not planned.
