### ISSUE TITLE
notification history: allow using formatter other than `content.format`

### ISSUE THREAD

**Issue by przepompownia** [echasnovski/mini.nvim#1312]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.notify

### Description

I have custom notification formatter that returns only message but would like to still use the default formatter to display notification history.

If necessary I can prepare PR.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think having `config.content.format` being universally applied to all instances of showing notifications (whether in floating window or in `show_history()`) is a more straightforward design.

There are already several approaches to customize this behavior:
- Write custom wrapper that temporarily sets `config.content.format` to what you'd like to see being used when showing history. Here is an example of showing raw message:
    ```lua
    _G.my_show_notifications = function()
      local cur_format = MiniNotify.config.content.format
      MiniNotify.config.content.format = function(notif) return notif.msg end
      MiniNotify.show_history()
      MiniNotify.config.content.format = cur_format
    end
    ```
- Use [`get_all()`](https://github.com/echasnovski/mini.nvim/blob/919b953f044d97a2243cc2d1f0b316a199434127/doc/mini-notify.txt#L342) to get all notifications and process them as you'd like (would require creating/showing a special buffer).

Closing as not planned.

**Comment by przepompownia** [comment]
Thank you! Switching formatters perfectly does what I want.
