### ISSUE TITLE
[mini.files] Preview on selected file extension only

### ISSUE THREAD

**Issue by MinhTran0911** [echasnovski/mini.nvim#1314]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I would like to have the ability to select a couple of file extensions to show preview (files with text only). Sometimes I move over some large binary or object files and that cause Neovim to lag or freeze. Is there a way to do this?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I can not reproduce any visible lag (for example, with 4.5Gb zip files or 1.5Gb mkv files).

Working with non-text files is already [fairly optimized](https://github.com/echasnovski/mini.nvim/blob/919b953f044d97a2243cc2d1f0b316a199434127/lua/mini/files.lua#L2288-L2294) and large size should not be a factor here. Providing ability to filter which files are previewed should be not necessary (ideally).

I am inclined to close this, but first would you mind answering couple of questions?
- Can you describe files with which you experience delay?
- Does preview show 'Non-text-file-------' string or some random characters?

**Comment by MinhTran0911** [comment]
Hi, it seems that I can't consistently reproduce the problem, so I think I will close this issue for now.
