### ISSUE TITLE
mini.deps full url default name can be better

### ISSUE THREAD

**Issue by Song-Tianxiang** [echasnovski/mini.nvim#1316]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.deps

### Description

current if I set:
```lua
MiniDeps.add {
  source = 'https://github.com/neovim/nvim-lspconfig.git'
}
```
The default `name` would be `nvim-lspconfig.git`
Can we make it better as `nvim-lspconfig`?

### Neovim version

nightly

### Steps to reproduce

```lua
MiniDeps.add {
  source = 'https://github.com/neovim/nvim-lspconfig.git'
}
```

### Expected behavior

default plugin name and disk directory is `nvim-lspconfig` instead of `nvim-lspconfig.git`

### Actual behavior

default name is `nvim-lspconfig.git`

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think having any name manipulation by default is a good idea as it increases unnecessary user surprise and documentation (although removing potential '.git' suffix is more or less reasonable). Besides:
- Having '.git' suffix in `source` is redundant.
- Users can set eventual [plugin name](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-deps.txt#L261-L264).

Closing as not planned.
