### ISSUE TITLE
Deleting first argument using the argument text object in mini.ai leaves an extra space

### ISSUE THREAD

**Issue by tskj** [echasnovski/mini.nvim#1317]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Probably best illustrated with an example. If I select the last argument or an argument in the middle of the list using `vaa` it gives me this as expected:
![bilde](https://github.com/user-attachments/assets/ef28eb95-da2b-4ba4-847c-4b7c22034442)
![bilde](https://github.com/user-attachments/assets/3aa26ab6-5d69-45b8-b47b-ee61c64ec5ce)

However when selecting the first argument:
![bilde](https://github.com/user-attachments/assets/c737ac7d-9ebe-4da4-babc-7cc009bdaaf4)

I understand that the selection has to grab the comma in the other direction in this case for it to work, but the problem is that if you use `daa` to delete an argument it, then it works fine in all cases except for the first argument:
![bilde](https://github.com/user-attachments/assets/fb124cfa-07f0-43d9-9095-9133559f227b)

As you can see on the last line, when deleting the first argument it leaves the space that was to the right of the comma.

As a fix I sugggest maybe just expanding the text object to include the space as well in this corner case? Kind of like this:
![bilde](https://github.com/user-attachments/assets/c4b37ee7-36ad-4fa3-9a53-24f0e22ee8de)

Hope that makes sense!

### Neovim version

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. navigate to the first argument of a list
3. type daa to delete the argument
4. observe the extra space

### Expected behavior

I want to be able to delete any argument of an argument list with the quick and simple `daa` without having to fix spacing afterwards.

### Actual behavior

I have to fix spacing after deleting the first argument of a list.

**Comment by echasnovski** [comment]
Thanks for the issue!

I am afraid this is a known limitation of argument textobject which comes from how 'mini.ai' searches for the best target textobject. There are more details in #187 and 551a8726ab382cb02b1e925512162da478ff3811 commit in particular.

This can be adjusted via configuring `a` textobject with [`separator` option of `gen_spec.argument()`](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-ai.txt#L641-L649). So the following setup fixes this particular issue (but with caveats described in the `gen_spec.argument` help):

```lua
local ai = require('mini.ai')
ai.setup({
  custom_textobjects = {
    a = ai.gen_spec.argument({ separator = '%s*,%s*' }),
  },
})
```

**Comment by tskj** [comment]
Ah thanks for pointing me to all that information! I tried the pattern `',%s*'`, as I don't expect there to be a lot of spaces before the comma in any situation I can think of.

I can see what you mean by the ambiguity, in my case putting the cursor on the comma or the space after the comma deletes the argument to the right, except in the case of the first argument, where it deletes to the left (the first argument). I much prefer that behavior to having to fix the whitespace manually though! I will get used to not placing the cursor on the comma or whitespace I imagine.

Again thank you!

**Comment by echasnovski** [comment]
> I can see what you mean by the ambiguity, in my case putting the cursor on the comma or the space after the comma deletes the argument to the right, except in the case of the first argument, where it deletes to the left (the first argument). I much prefer that behavior to having to fix the whitespace manually though! I will get used to not placing the cursor on the comma or whitespace I imagine.

It is not *quite* like that, as it should pick the left or right textobject with the smallest width.

**Comment by tskj** [comment]
Oh it does, that's craaazy.

Having thought about this some more, I think the behavior I would expect (only thinking about my usecase with argument lists, I'm sure there are others this wouldn't make senes for) is something like this:

 - putting the cursor on the comma would always select the argument to the left, the comma itself, and whitespace to the right of the comma (if there is whitespace)
 - putting the cursor on the whitespace would select the argument to the right of it, the comma following that argument, and the space following that comma (so not the whitespace where the cursor is initially)
 - special case: if we're on the last argument in the argument list, we select backwards to include previous space

That's maybe a bit weird because in the case of putting the cursor on the whitespace it would select a text object that the cursor is not really on, but I think this matches the behavior people expect, and I think this would both delete the "correct" argument in all cases as well maintaining the correct spacing, both for normal cases like I showed `(foo, bar, qux)` and more padded ones like `( foo, bar, qux )` and also handle trailing spaces in both cases `(foo, bar, qux,)` and `( foo, bar, qux, )`. 

The special case I think is unavoidable because argument lists don't usually have trailing commas, and I think maybe special casing on the last argument gives the behavior you would most expect?

**Comment by echasnovski** [comment]
> * putting the cursor on the whitespace would select the argument to the right of it, the comma following that argument, and the space following that comma (so not the whitespace where the cursor is initially)

I am afraid this breaks on something like `(aaa  ,  bbb  ,  ccc)`. Although rare in real life, it still needs to be accounted for.
The current behavior seems to be the best compromise between what is reasonable to expect, various edge cases, and how 'mini.ai' itself works to search for the best textobject region in the current text.

**Comment by tskj** [comment]
I don't necessarily see why that wouldn't work. I have constructed some examples below to illustrate the different cases. Star `*` means cursor position, underscores `_` are used to mark selection/deletion.

```
(aaa, bbb, ccc)
(aaa* bbb, ccc) -> (_____bbb, ccc)
(aaa,*bbb, ccc) -> (aaa, _____ccc)
(aaa, bbb* ccc) -> (aaa, _____ccc)
(aaa, bbb,*ccc) -> (aaa, bbb_____)

( aaa, bbb, ccc )
( aaa* bbb, ccc ) -> ( _____bbb, ccc )
( aaa,*bbb, ccc ) -> ( aaa, _____ccc )
( aaa, bbb* ccc ) -> ( aaa, _____ccc )
( aaa, bbb,*ccc ) -> ( aaa, bbb_____ )

(aaa, bbb, ccc,)
(aaa* bbb, ccc,) -> (_____bbb, ccc,)
(aaa,*bbb, ccc,) -> (aaa, _____ccc,)
(aaa, bbb* ccc,) -> (aaa, _____ccc,)
(aaa, bbb,*ccc,) -> (aaa, bbb,_____) // no trailing space, therefore we expand back

( aaa, bbb, ccc, )
( aaa* bbb, ccc, ) -> ( _____bbb, ccc, )
( aaa,*bbb, ccc, ) -> ( aaa, _____ccc, )
( aaa, bbb* ccc, ) -> ( aaa, _____ccc, )
( aaa, bbb,*ccc, ) -> ( aaa, bbb, _____)

(aaa , bbb , ccc ,)
(aaa*, bbb , ccc ,) -> (______bbb , ccc ,)
(aaa ,*bbb , ccc ,) -> (aaa , ______ccc ,)
(aaa , bbb*, ccc ,) -> (aaa , ______ccc ,)
(aaa , bbb ,*ccc ,) -> (aaa , bbb ,______) // no trailing space, same rule as above

( aaa , bbb , ccc , )
( aaa*, bbb , ccc , ) -> ( ______bbb , ccc , )
( aaa ,*bbb , ccc , ) -> ( aaa , ______ccc , )
( aaa , bbb*, ccc , ) -> ( aaa , ______ccc , )
( aaa , bbb ,*ccc , ) -> ( aaa , bbb , ______)
( aaa , bbb , ccc ,*) -> ( aaa , bbb , ccc ,?) // I don't know what this would mean, no-op?
```

With this additional rule about potentially grabbing whitespace backwards if there aren't any trailing spaces, I think it will behave as expected in every usecase.

However, of course, how it's implemented and the constraints of the existing solution I have no idea, just a suggestion for a better user experience!

**Comment by echasnovski** [comment]
> I don't necessarily see why that wouldn't work.

With the rule "putting the cursor on the whitespace would select the argument to the right of it, the comma following that argument, and the space following that comma (so not the whitespace where the cursor is initially)" the following cases will behave not as you described: `(aaa*, bbb , ccc ,)` and `( aaa , bbb*, ccc , )`.

But yes, it is not quite as simple as deciding what to do based on the cursor. It is more about the overall rule that should detect *any* argument after which built-in algorithm chooses the "best" one (taking into account search method, etc.). I am fairly certain that the current behavior of argument textobject won't change (especially considering that there is some customization options in `gen_spec.argument()`).

**Comment by tskj** [comment]
> the following cases will behave not as you described: 

Fair enough, my rule should have been more precise. I was thinking of the space following a comma, so really it should have been:
"putting the cursor on whitespace following a comma would select the argument to the right of it, the comma following that argument, and any space following that comma".

Do you not think this rule would give the correct result in all cases? If you look at my examples I think it does.

I understand that you don't really want to change it, but the way it currently behaves it's honestly kind of broken. I understand that you also want to consider all edge cases, but as it stands it messes up the formatting for completely standard lists like `(aaa, bbb, ccc)`. Isn't that worse than potentially having weird behavior for weirdly formatted lists? It doesn't get any more run-of-the-mill, regular argument list than that. And with the customization you suggested (or my variant) it deletes the wrong arguments if you happen to put the cursor on a comma or whitespace (in some but not all cases, making it even worse!). 

Wouldn't it be better if it selected the correct arguments even if you have your cursor on a comma, _and_ didn't mess up the formatting, both in regular cases and in edge cases?

**Comment by echasnovski** [comment]
> I understand that you don't really want to change it, but the way it currently behaves it's honestly kind of broken.
> ...
> Wouldn't it be better if it selected the correct arguments even if you have your cursor on a comma, and didn't mess up the formatting, both in regular cases and in edge cases?

Chasing 110% worth of features at the expense of adding more complexity to the code is against overall design of 'mini.nvim'. The current solution has its downsides, but they are the result of a careful compromise.

Adding an extra `diw` to delete whitespace after an occasional `daa` on the first argument is considered a worthwhile tradeoff here.
