### ISSUE TITLE
Beta-testing 'mini.align'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#132]
Please leave your feedback about new 'mini.align' module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by andrewferrier** [comment]
Minor bug: visually select some lines, hit the key you've defined for `start_with_preview`, hit `<Esc>`. The visual selection is cleared but the "helper prompt" in the command line is not.

**Comment by andrewferrier** [comment]
On your questions: yes it's all very intuitive so far (although my alignment needs are generally fairly basic). Defaults are good for `vim-easy-align` user.

**Comment by echasnovski** [comment]
> Minor bug: visually select some lines, hit the key you've defined for `start_with_preview`, hit `<Esc>`. The visual selection is cleared but the "helper prompt" in the command line is not.

It is not really a bug, as it is meant that way (at least at the moment). What I usually observe with most well-known plugins, is that they don't "clean up" command line after they `echo`ed something. 'vim-easy-align' have this behavior also. I think it has to do something with messing up the screen redraw, but not sure. So decided to have it like this right now.

> On your questions: yes it's all very intuitive so far (although my alignment needs are generally fairly basic). Defaults are good for vim-easy-align user.

Thanks, that's helpful!

How do you feel about `j` modifier (which changes alignment side)? I opted to always need 2 key presses to change it instead of just looping over all possibilities. By the way, the latter is also possible with [this custom config](https://github.com/echasnovski/mini.nvim/blob/821ebe136ea45603c25c2c64bdba54ebd10d9420/doc/mini-align.txt#L498-L507).

**Comment by andrewferrier** [comment]
> What I usually observe with most well-known plugins, is that they don't "clean up" command line after they echoed something

I mean, yeah, maybe, but personally I think that's one of those conventions that does need to die :) It makes some sense if you view the command-line as a scrolling terminal, but here you aren't using it as such, but instead as an 'assistant' window. I don't feel super-strongly about it, but I do think the current behaviour is maybe a bit confusing.

**Comment by andrewferrier** [comment]
> How do you feel about `j` modifier (which changes alignment side)? I opted to always need 2 key presses to change it instead of just looping over all possibilities. By the way, the latter is also possible with [this custom config](https://github.com/echasnovski/mini.nvim/blob/821ebe136ea45603c25c2c64bdba54ebd10d9420/doc/mini-align.txt#L498-L507).

Totally fine. Personally I very rarely use anything other than left-indent anyway.

**Comment by echasnovski** [comment]
> I mean, yeah, maybe, but personally I think that's one of those conventions that does need to die :) It makes some sense if you view the command-line as a scrolling terminal, but here you aren't using it as such, but instead as an 'assistant' window. I don't feel super-strongly about it, but I do think the current behaviour is maybe a bit confusing.

I vaguely remember tackling it for a bit, but I think I ended up with some redrawing issues. I'll keep this in mind during future update of printing logic in all modules.

**Comment by echasnovski** [comment]
> Minor bug: visually select some lines, hit the key you've defined for `start_with_preview`, hit `<Esc>`. The visual selection is cleared but the "helper prompt" in the command line is not.

@andrewferrier, I reconsidered this. All messages shown from 'mini.align' should now be cleared after alignment is done.

**Comment by oncomouse** [comment]
I'm enjoying `mini.align` so far, but I've hit on something frustrating that I think might be addressed in the API.

I use Tabular for aligning tables in Markdown (and for nothing else), so I'd like to replace `:Tabular` with a wrapper for that specific use-case. In doing so, I'm finding it hard to interact with `mini.align` in a programmatic way. It would be easier if there were a  function---say `MiniAlign.align_region()`--- [that does the work of these three lines in `H.process_region()`](https://github.com/echasnovski/mini.nvim/blob/49f970355e7b0dc5407057eb39b778d20209b7aa/lua/mini/align.lua#L1658-L1660). It's a little weird to have to pass a region and the contents of a region to `MiniAlign.align_strings()`, especially when the helper functions to get and set a region aren't exposed by the module.

I might be missing something obvious, but I think the ability to directly align a region from a command or another function would be helpful.

**Comment by echasnovski** [comment]
`MiniAlign.align_region()` was initially planned to be exported, but there were at least couple of things I didn't like about doing it. I don't quite remember all of them, but the bigger picture was that it didn't quite align (haha :) ) with other exported functionality. Like what region should be used as default, etc.

Let's say, there will be a `MiniAlign.align_region(region, mode, opts)` function. What do you expect to be able to do with it? It can't really be a drop-in replacement for `:Tabular`, because it is not a user command (like it can't be called with a range, for example).

The easiest way to make this exported function is to make passing `region` and `mode` obligatory and not support any kind of dot-repeat, etc. But I think it won't be *that* useful, so finding an optimal compromise is a way to go here. At the time of writing this module, that compromise was "don't export it, see if it can be useful for other people", but I am open to adding it.

**Comment by Doltonius** [comment]
Is there a way to trim whitespace by default?

**Comment by echasnovski** [comment]
> Is there a way to trim whitespace after split by default?

Sure. Add `trim` step to default `pre_justify` steps. Like this:

```lua
local align = require('mini.align')
align.setup({ steps = { pre_justify = { align.gen_step.trim() } } })
```

**Comment by echasnovski** [comment]
> Which is incorrect. The first line should have a space removed between let(:a) and { 1 } to align with the other two, instead a space is added to the other lines.

It is correct, because first column after split looks have strings with different widths. They are made same width by padding from whitespace from right. The reason `gaip=` works is because `=` has [pre-defined modifier](https://github.com/echasnovski/mini.nvim/blob/49f970355e7b0dc5407057eb39b778d20209b7aa/doc/mini-align.txt#L310-L325).

If you want to trim whitespace for this case, you have at least three options:
- Press `t` modifier (so like `gaipt{`).
- Make custom modifier `{` which will work similarly to `=`. Something like this:
```lua
local align = require('mini.align')
align.setup({
  modifiers = {
    ['{'] = function(steps, opts)
      opts.split_pattern = '{'
      table.insert(steps.pre_justify, align.gen_step.trim())
      opts.merge_delimiter = ' '
    end
  }
})
```
- Always trim whitespace and merge with ` ` by adding `trim` pre-justify step and setting `merge_delimiter` option. Like this:
```lua
local align = require('mini.align')
align.setup({
  options = { merge_delimiter = ' ' },
  steps = { pre_justify = { align.gen_step.trim() } },
})
```

**Comment by CKolkey** [comment]
Gotcha, the custom modifier seems to be just right - thanks for the quick feedback :)

**Comment by oncomouse** [comment]
@echasnovski That makes a lot of sense. I was able to do what I wanted with the existing API: https://github.com/oncomouse/dotfiles/blob/master/conf/vim/plugin/tabular.lua

It seems like there's no reason for an `align_region` function after all.

**Comment by echasnovski** [comment]
> @echasnovski That makes a lot of sense. I was able to do what I wanted with the existing API: https://github.com/oncomouse/dotfiles/blob/master/conf/vim/plugin/tabular.lua
> 
> It seems like there's no reason for an `align_region` function after all.

That is some elaborate code you've got there. And it does the job. Nice!

Couple of observations:
- It is usually very cheap to do `local lines = vim.api.nvim_buf_get_lines(0, 0, -1, true)` to get all lines and work with them (instead of taking one at a time).
- This seems to only work in linewise mode. Granted, it usually is an overwhelming majority of cases, but you should be aware of that.

**Comment by echasnovski** [comment]
The 'mini.align' is now out of beta-testing after the release of version 0.6.0. Thank you all for your input!
