### ISSUE TITLE
Is it possible to make it open mini.files as a buffer instead of a floating.

### ISSUE THREAD

**Issue by medwatt** [echasnovski/mini.nvim#1322]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

[mini.files]

### Description

I find having columns that constantly change in size distracting. I have modified it in the config to show only 1 column. I would like mini.files to open as a buffer instead of a floating window so that when I have several splits, mini.files opens in the split where the command is invoked. Can this be done?

**Comment by echasnovski** [comment]
I am afraid, no: 'mini.files' explorer will always be possible to open *only* as temporary floating windows.

If changing widths is the main problem here, then it can be adjusted by setting the same [`config.windows.width_*`](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-files.txt#L602-L607) values. This will make all windows have same width while still allowing to show the current branch via Miller columns. The currently focused window can then by identified via title which will be highlighted with [`MiniFilesTitleFocused`](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-files.txt#L97) highlight group.

**Comment by medwatt** [comment]
It is both width and height. At the moment, it completely covers over lualine, which doesn't look nice.

```
local default_height = vim.api.nvim_win_get_height(0)

vim.api.nvim_create_autocmd('User', {
    pattern = 'MiniFilesWindowUpdate',
    callback = function(args)
        local config = vim.api.nvim_win_get_config(args.data.win_id)

        -- Ensure fixed height
        config.height = default_height

        -- Ensure title padding
        if config.title[#config.title][1] ~= ' ' then
            table.insert(config.title, { ' ', 'NormalFloat' })
        end
        if config.title[1][1] ~= ' ' then
            table.insert(config.title, 1, { ' ', 'NormalFloat' })
        end

        vim.api.nvim_win_set_config(args.data.win_id, config)
    end,
})
```

**Comment by echasnovski** [comment]
> It is both width and height. At the moment, it completely covers over lualine, which doesn't look nice.

Then you can adjust it with `config.height = vim.api.nvim_win_get_height(0) - 1`. Note that it will limit height to the height of current window which might be smaller if there are vertically stacked splits. You can use `config.height = vim.o.lines - vim.o.cmdheight - 1` to make it span whole instance height.

Also note that `-- Ensure title padding` paragraph is not needed for adjusting height.

**Comment by medwatt** [comment]
Thanks for the replies. These are not proper solutions. I had tried something like that but it looks bad when size of neovim window changes. Also, the way you have things setup at the moment does not allow the width to be changed dynamically. So, it almost impossible to have it look nice. I have tried `oil`. While it works as I would like it to work, it has a weird flickering when I go up a directory. Looks like I have to go back to using `nnn`.

**Comment by echasnovski** [comment]
> I had tried something like that but it looks bad when size of neovim window changes.

There is a `VimResized` event to adjust for that:
- Have `local default_height = vim.o.lines - vim.o.cmdheight - 1`
- Recompute it inside `VimResized` event.

**Comment by medwatt** [comment]
What about the width when there are multiple splits?

**Comment by echasnovski** [comment]
> What about the width when there are multiple splits?

Similar to `vim.o.lines`, there is `vim.o.columns`.

**Comment by medwatt** [comment]
Yes, but how to make it change dynamically when the config option expects a number, not a function.

**Comment by medwatt** [comment]
I think I now understand that you meant that I can change the width inside the same event as the height.

**Comment by pernambucano** [comment]
> I am afraid, no: 'mini.files' explorer will always be possible to open _only_ as temporary floating windows.
> 
> If changing widths is the main problem here, then it can be adjusted by setting the same [`config.windows.width_*`](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-files.txt#L602-L607) values. This will make all windows have same width while still allowing to show the current branch via Miller columns. The currently focused window can then by identified via title which will be highlighted with [`MiniFilesTitleFocused`](https://github.com/echasnovski/mini.nvim/blob/0a8a1072137d916406507c941698a4bfa9dbbe7a/doc/mini-files.txt#L97) highlight group.

Thank you SO MUCH! This is what I've looking for a long time (without knowing they were called "MIller Columns" xD). I believe there are many other plugins that try to do this, without knowing this is already possible here. Might I suggest to put this in a more visible place, maybe a wiki?

**Comment by echasnovski** [comment]
> Thank you SO MUCH! This is what I've looking for a long time (without knowing they were called "MIller Columns" xD). I believe there are many other plugins that try to do this, without knowing this is already possible here. Might I suggest to put this in a more visible place, maybe a wiki?

I mean... Config structure is documented both in [help file](https://github.com/echasnovski/mini.nvim/blob/c8bc67a35e627908da644c5f8cd26b3f987f2627/doc/mini-files.txt#L596-L608) and [module's README](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-files.md#default-config). If the goal is to have windows have same width, then looking for something that configures windows seems like a common sense.

One thing that might be worth adding to the (planned in some type of future) wiki is the code snippet for a "static" layout which respects Neovim instance window resize. Same as described in this issue, with `VimResized` callback, etc.
