### ISSUE TITLE
[mini.files] Set preview width specifically for files

### ISSUE THREAD

**Issue by nickvonkaenel** [echasnovski/mini.nvim#1324]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I have my setting for width_preview set to a size that is comfortable for viewing a file, but it is much larger than needed for a directory. I would appreciate a width setting that is specifically for viewing files since it is hard to pick a size that works well for both of them.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Although an actual implementation is probably quite concise, I don't think having different preview widths for directory and files is a good idea for the following reasons:
- It increases (already quite large) config size.
- It introduces visual flicker when navigating down with `j`. Not sure how inconvenient this might be, but I don't think I like it in general.

The main idea for previewing file is mostly to have a general idea if the file is the one user expects it to be, not seeing all the details of the file in question. So (in my opinion) having a wide preview is not really a good idea, which can be seen in the default value of `config.windows.window_preview`.

Closing as not planned.

**Comment by nickvonkaenel** [comment]
That's understandable, thanks for the quick response!
