### ISSUE TITLE
Getting E5107 while doing yi'

### ISSUE THREAD

**Issue by stormherz** [echasnovski/mini.nvim#1329]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Hey, first things first, thanks for a great plugin!

I'm having a strange issue with `yi'` operation while `mini.ai` is enabled.

The following error is reported:
```
07:13:40 msg_show.lua_error E5107: Error loading lua [string ":lua"]:1: ')' expected near '', { search_method = ''
07:13:40 msg_show cannot set clipboard contents
07:13:40 msg_show stack traceback:
07:13:40 msg_show ^I[C]: in function 'rpcrequest'
07:13:40 msg_show ^I[string "<nvim>"]:31: in function <[string "<nvim>"]:30>
```

I've looked through `mini.ai` code and it seems it's being produced here:
```lua
  return '<Cmd>lua '
    .. string.format(
      [[MiniAi.select_textobject('%s', '%s', { search_method = '%s', n_times = %d, reference_region = %s, operator_pending = %s, vis_mode = %s })]],
      ai_type,
      vim.fn.escape(tobj_id, "'\\"),
      opts.search_method,
      vim.v.count1,
      reference_region_field,
      operator_pending_field,
      vis_mode_field
    )
    .. '<CR>'
```

Though I'm not sure what to think of it. This particular part of `mini.ai` hasn't changed for a while and I've been having this issue with `yi'` only for a week or so. I'm not that well versed in Lua, so I'm not really sure what to think of it, apart from the hunch it's something about `'` being unescaped somewhere or my nvim setup playing tricks on me.

Can you help me out with some tips what might be wrong on my end?

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu any_file_with_single_quotes`
2. move cursor within any text, surrounded by `''`
3. press `yi'`

### Expected behavior

Text within `''` would be yanked

### Actual behavior

An error happened instead

**Comment by stormherz** [comment]
I've tried some debug printing with `expr_textobject`, it does produce valid call:
```
<Cmd>lua MiniAi.select_textobject('i', '\'', { search_method = 'cover_or_next', n_times = 1, reference_region = nil, operator_pending = true, vis_mode = "v" })<CR>
```

The strangest thing is - when I try to run this code manually - it actually works as expected, selecting what's needed, but performing seemingly the same with `yi'` results in error. I'm almost 100% sure it's not the issue with `mini.ai`, but I'm lost on where to look next

**Comment by echasnovski** [comment]
I am also clueless as to why this can happen. Judging by the nature of the error, it seems to happen only with `'` textobject (and possible `\`), right?

One thing I can suggest is, could you please try replacing `vim.fn.escape(tobj_id, "'\\")` argument (i.e. [this one](https://github.com/echasnovski/mini.nvim/blob/c8bc67a35e627908da644c5f8cd26b3f987f2627/lua/mini/ai.lua#L1258)) with `vim.inspect(tobj_id)`? And see if you can reproduce the issue. The latter is a better solution in this type of situation, so replacing it should be a good idea anyway.

Also, judging by the log messages, I'd assume you run Neovim not directly from terminal emulator (more like Neovide or VS Code emulation). Is it correct?

**Comment by stormherz** [comment]
@echasnovski hey, thanks for checking it out! it actually does solve it, replacing `escape` with `vim.inspect` and replacing placeholder for tobj `'%s'` with just `%s`

it now looks like this:

```lua
  return '<Cmd>lua '
    .. string.format(
      [[MiniAi.select_textobject('%s', %s, { search_method = '%s', n_times = %d, reference_region = %s, operator_pending = %s, vis_mode = %s })]],
      ai_type,
      vim.inspect(tobj_id),
      opts.search_method,
      vim.v.count1,
      reference_region_field,
      operator_pending_field,
      vis_mode_field
    )
    .. '<CR>'

```

yep, I'm running with Neovide and lazyvim, though tried directly in the terminal, was getting the same error, but not yet tried on a bare nvim with `mini.ai` only.

I'm sure it has nothing to do with `mini.ai`, judging from the error itself - it would be somewhat related to neovim or lua handling/adapter, but that sounds a bit stupid, since I haven't updated it in a while and a bug of that magnitude will be all over the place by now, in every bugtracker, and I've looked somewhat thoroughly before posting here.

If you're interested in trying to figure it out - I can always debug on my side, since it's reproducing here, but I'm not sure if you'd want to spend time on that, since there's no reports of this. I can make pull request out of this, but, again, I'm not sure if it's relevant or you want that, considering it's only me having an issue

**Comment by echasnovski** [comment]
The `vim.inspect()` usage instead of `vim.fn.escape()` should now be part of `main` branch and (hopefully) fixing the issue.

> If you're interested in trying to figure it out - I can always debug on my side, since it's reproducing here, but I'm not sure if you'd want to spend time on that, since there's no reports of this. I can make pull request out of this, but, again, I'm not sure if it's relevant or you want that, considering it's only me having an issue

Using the `vim.inspect()` is the better approach here, so probably not worth going fully down the rabbit hole here.

One thing I am curious though, what OS are you using? Is it Windows, by any chance?

**Comment by stormherz** [comment]
@echasnovski oh wow, thanks a lot for resolving it right on the spot, works like a charm now!

> Using the vim.inspect() is the better approach here, so probably not worth going fully down the rabbit hole here.

yeah, probably would be a waste of time in the end

> One thing I am curious though, what OS are you using? Is it Windows, by any chance?

and an answer to that is, probably, why it would be a huge waste of time =) speaking about rabbit holes - it's mandatory for me to use windows for one of the projects I'm working on, so my current setup for neovim is:

- for neovim in windows - neovide as the frontend, neovim installed as a windows binary
- for neovim in wsl - neovide as the frontend, connecting to neovim, which is running in WSL. sooo, yeah, probably somewhere down the pipeline it breaks in unexpected places =)

**Comment by stormherz** [comment]
@echasnovski I'll definitely fiddle with it a bit more, if there's a chance of helping out open source community - I'll take it. my next step would probably be hooking up into neovide to see what's going on under the hood at this point. I'll let you know if anything comes up, at least just to satisfy the feeling of unveiling the mystery =)

**Comment by echasnovski** [comment]
> my next step would probably be hooking up into neovide to see what's going on under the hood at this point. I'll let you know if anything comes up, at least just to satisfy the feeling of unveiling the mystery =)

I'd say that coming up with a minimal and stable reproduction example would already be very helpful. Without any extra plugins and only using built-in functions. If it errors on Neovim and not in terminal raw Neovim, then open issue in Neovide. Otherwise - in Neovim itself. Probably there is no need to look into internals before that.

**Comment by stormherz** [comment]
@echasnovski well, yeah, I've figured it out

letting you know just for the giggles, an old at the world itself story of "stupidity strikes back". I've messed up my `cpoptions` somewhere around last week. to the point that it landed to have `n` flag only (and the default is `aABceFs_`)

sooo, probably it's missing `B` flag that messed things up for me beyond repair, which prevents `\` to be treated as `Ctrl-V` in mappings, commands, abbreviations

spent half a day and only found out during a full directory diff of two nvim configs (nice job, man, nice jooob)

sorry for spending your time on this, big thanks for looking into it and making a fix =)

**Comment by echasnovski** [comment]
Absolutely no worries! Thanks for the follow up and an interesting use case! And inadvertently prompting to do the `vim.inspect()` change, because I it *is* a better approach in on itself.

All this is an insane learning experience, which at least will make you not forget about 'B' flag in 'cpoptions' :)
