### ISSUE TITLE
Remove use of glyphs in neovim

### ISSUE THREAD

**Issue by nshern** [echasnovski/mini.nvim#1332]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When I open mini.files I get the following "no glyph" icon for each item in the menu 

![Screenshot 2024-11-10 at 11 38 39](https://github.com/user-attachments/assets/f522867d-584b-4ffd-b015-fbe26d24a455)

**is it possible to disable this?**

### Neovim version

NVIM v0.10.2

### Steps to reproduce

1. use [berkeley mono typeface](https://berkeleygraphics.com/typefaces/berkeley-mono/)
2. open mini.files
3. see issue

### Expected behavior

No glyphs shown, similar to oil.nvim

### Actual behavior

No glyph icon shown

**Comment by echasnovski** [comment]
For future reference, making 'mini.files' to not show icons can be done by [supplying custom `config.content.prefix` function](https://github.com/echasnovski/mini.nvim/blob/998cfcf1fdd0a6830d0fc35f1c054a6f55de1e7f/doc/mini-files.txt#L443).

At the same time, judging by the screenshot, icons are provided by 'mini.icons'. In this case the better approach might be to use ['ascii' style when setting up 'mini.icons'](https://github.com/echasnovski/mini.nvim/blob/998cfcf1fdd0a6830d0fc35f1c054a6f55de1e7f/doc/mini-icons.txt#L190). But the best approach is to set up terminal emulator to have a "fallback" font just for this types of glyphs (for example, [`NerdFontsSymbolsOnly`](https://github.com/echasnovski/mini.nvim/blob/998cfcf1fdd0a6830d0fc35f1c054a6f55de1e7f/doc/mini-icons.txt#L61-L63)).
