### ISSUE TITLE
Mark and go to next position

### ISSUE THREAD

**Issue by phrmendes** [echasnovski/mini.nvim#1339]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Is there a way to use the `telescope.nvim` or `fzf` behavior so that when you select an entry, the selection goes to the next item below?

**Comment by echasnovski** [comment]
Yes, there is, albeit not very convenient one. It requires making a custom mapping which emulates pressing "mark" + "go down" keys (thus should be mapped to some other key and not override default 'mark' keys, `<C-x>`). See [this comment](https://github.com/echasnovski/mini.nvim/issues/513#issuecomment-1764784504).

**Comment by phrmendes** [comment]
Thanks!
