### ISSUE TITLE
mini.sessions cannot create a default sessions directory under windows

### ISSUE THREAD

**Issue by B4mbus** [echasnovski/mini.nvim#134]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

The default `mini.sessions`' path is incorrect in a way that at startup `mini.sessions` keeps erroring
```
(mini.sessions) "C:\\\\Users\\\\B4mbus\\\\AppData\\\\Local\\\\nvim-data\\\\session" is not a directory path
```
Changing it manually to `vim.fn.stdpath('data') .. '\\sessions\\` works and it doesn't display that error anymore.

My understanding is that on windows to create the directory one must append `\\` at the end. I'm willing to look into that, just creating that issue for organization purposes.

(related to #133, but I'm splitting that issue into two)

### Neovim version

0.8.0-dev-922-g42e9fe7d9

### Steps to reproduce

1. `nvim -nu minimal.lua`
Contents of minimal.lua:
```lua
require('mini.sessions').setup({})
```

### Expected behavior

`mini.session` properly creating, recognizing and using the default directory.

### Actual behavior

![image](https://user-images.githubusercontent.com/75364377/192996379-6c6b5fe3-b6e5-49d1-a991-7bffcfc19127.png)

**Comment by echasnovski** [comment]
The 'mini.sessions' now automatically creates directory if it is not present.

Could you, please, update and see if the issue still persists?

**Comment by echasnovski** [comment]
I was just able to verify on Windows machine that 'mini.sessions' works as expected after initial set up. Itcreated global default directory and was able to write/read/delete a session there.

So closing this now.If you still experience this, feel free to reopen.
