### ISSUE TITLE
[Feature] support buffer-local keymaps in mini.clue?

### ISSUE THREAD

**Issue by Bekaboo** [echasnovski/mini.nvim#1340]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

First of all thanks for making mini.nvim! It is an awesome collection of lightweight but functional modules.

I am currently considering adding mini.clue to my workflow to help me remember some less-used keymaps, mainly debug keymaps and buffer-local keymaps defined by plugins. However, mini.nvim does not show buffer-local keymaps for me.

For example, oil.nvim defines some buffer-local keymaps for opening files using external program, reorder files, toggle preview, etc with `g` as prefix. When I press `g` in a oil buffer, mini.clue does not show up. I've also tried which-key.nvim and it works as expected in this case.

Oil.nvim's buffer-local keymaps:

![image](https://github.com/user-attachments/assets/cf116638-cf18-4664-892f-4ad171591683)

With mini.clue:

![image](https://github.com/user-attachments/assets/f08c8dea-a0e1-4c85-a9a4-24e544f7f3aa)

With which-key.nvim:

![image](https://github.com/user-attachments/assets/e678c89d-4811-47ef-a70c-cd454ab36044)

**Comment by echasnovski** [comment]
Thanks for the kind words!

I can not reproduce the behavior with plain `require('oil').setup()` and [full starter setup of 'mini.clue'](https://github.com/echasnovski/mini.nvim/blob/c520765241541e0c7d4bc6fd4a716f706b0d5de7/doc/mini-clue.txt#L236) . It works as expected: pressing `g` shows *all* available mappings (both global and buffer-local from 'oil.nvim') plus possibly additional clues (as a result of [`gen_clues.g()`](https://github.com/echasnovski/mini.nvim/blob/c520765241541e0c7d4bc6fd4a716f706b0d5de7/doc/mini-clue.txt#L278)). 'mini.clue' already supports buffer-local mappings, so this shouldn't be the culprit of the issue.

Does `g` trigger work in regular buffers (pressing `g` and waiting 1 second should show available Normal mode mappings that start with `g`)? With 'oil.nvim' buffer being current, does `:nmap g` show an entry from 'mini.clue' with description "Query keys after "g""?

**Comment by Bekaboo** [comment]
Thanks for your quick reply! I will try to find a minimal repro in the following days.

**Comment by Bekaboo** [comment]
Sorry I cannot reproduce this anymore. Mini.clue works out of the box for buffer-local keymaps now. Thanks for all you work for mini.nvim!
