### ISSUE TITLE
notify: assign timer to message

### ISSUE THREAD

**Issue by przepompownia** [echasnovski/mini.nvim#1345]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

notify

### Description

https://github.com/przepompownia/mini-ui-messages-example in the current form shows (normal `n` and `search_count` messages) that updating existing message it does not delay the moment of its disappearance. 

The example still uses the callback returned by `make_notify()` - I modified it like in #1341 but it still uses `vim.defer_fn()` to remove the message. The timer returned is not assigned anywhere so we lose control over the extension of the life of such message. 

Probably we need to 
- create `msg.rm_timer` with remove callback to the message,
- on update call `msg.rm_timer:again()`,
- `msg.rm_timer:stop(); msg.rm_timer = nil` on `remove()`.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think it is necessary to make notification API more complicated in this case. There are two notification "layers" at play here:
- Notifications produced by the output of `make_notify()` are essentially [added and then deleted after configurable delay](https://github.com/echasnovski/mini.nvim/blob/b07157c51e52a1b004ec7959f9618e9bc24686d3/lua/mini/notify.lua#L310-L311). They are not meant to be updated: show immediately and hide after later. It should be not be more complicated (unless documented `vim.notify` interface changes).
- Notifications managed by lower level [`add()`](https://github.com/echasnovski/mini.nvim/blob/b07157c51e52a1b004ec7959f9618e9bc24686d3/lua/mini/notify.lua#L310-L311), [`update()`](https://github.com/echasnovski/mini.nvim/blob/b07157c51e52a1b004ec7959f9618e9bc24686d3/doc/mini-notify.txt#L286), [`remove()`](https://github.com/echasnovski/mini.nvim/blob/b07157c51e52a1b004ec7959f9618e9bc24686d3/doc/mini-notify.txt#L299). Those are specifically designed to be a public interface for users to micromanage notifications without the need to deal with how they are displayed.

I believe going the second route is what should be preferable here. I.e. manually add, update, and remove notifications based on custom logic (including prolonging time until removal if update was made).

Closing as not planned.
