### ISSUE TITLE
[mini.files] show line numbers

### ISSUE THREAD

**Issue by onexbash** [echasnovski/mini.nvim#1347]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Hi together, 
If it's possible already, I'd love to hear, but the request is basically to have the option to enable relative line numbers in the filetree. I navigate a lot with motions like 5j , so it's crucial to have those.

**Comment by echasnovski** [comment]
Yes, it is possible through custom autocommand. See [this comment](https://github.com/echasnovski/mini.nvim/issues/747#issuecomment-1995360187).

**Comment by onexbash** [comment]
> Yes, it is possible through custom autocommand. See [this comment](https://github.com/echasnovski/mini.nvim/issues/747#issuecomment-1995360187).

oh wow, the day will come when i can easily think of those custom autocmds on my own :D 
Thanks a lot.
