### ISSUE TITLE
[mini.files] center filetree windows

### ISSUE THREAD

**Issue by onexbash** [echasnovski/mini.nvim#1349]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I have my mini.files config with 2 filetree windows of the same width displayed permanently. 
Now I search for a possibility to center these as it would look much better.
![CleanShot 2024-11-19 at 20 57 19](https://github.com/user-attachments/assets/7d72e017-d2fe-4663-aa9a-c17563606f0d)

**Comment by echasnovski** [comment]
This not planned, see #382.

------

Please, take some time searching prior issues before creating new one(s).
