### ISSUE TITLE
Delete/replace operations have different behavior for eating whitespace depending on surrounding

### ISSUE THREAD

**Issue by thisisrandy** [echasnovski/mini.nvim#1350]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

When deleting or replacing bracket-like surroundings in multiline sections, whitespace, in particular new lines, are removed in an undesirable way that, depending on the language, may make the resulting code ungrammatical. However, tags are not similarly affected.

### Neovim version

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Steps to reproduce

If the following is `repro.lua`

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{ "echasnovski/mini.surround", version = false, opts = {} },
	},
})
```

and this is `example`

```
if (condition) { 
	let stuff = ( // comment
		foo,
		bar,
	);
}

<t1>
	<t2><t2/>
</t1>
```

1. Go to line 2, `sd{`. The relevant part of `example` becomes:
```
if (condition) let stuff = ( // comment
		foo,
		bar,
	);
```
2. Undo, then go to line 3, `sd(`. `example` becomes
```
	let stuff = // comment
		foo,
		bar,;
```
3. Notice how the trailing comment kept the upper new line from being removed.
4. Undo and then try `sr({` on line 3:
```
	let stuff = { // comment
		foo,
		bar, };
```
5. Finally, go to line 9, `sdt`
```

	<t2><t2/>

```
6. Notice how the surrounding tags are simply removed without affecting any other formatting.

### Expected behavior

The behavior should be consistent across different surroundings. In particular, it should look most like the tag behavior, i.e. the situation where formatting is minimally affected. It should not be sucking up newlines.

### Actual behavior

See Steps to reproduce.

**Comment by thisisrandy** [comment]
I'm digging in a little and seeing right away code from [this line](https://github.com/echasnovski/mini.surround/blob/48a9795c9d352c771e1ab5dedab6063c0a2df037/lua/mini/surround.lua#L815) onward that looks like it's supposed to delete blank lines and dedent the surrounded ones, which definitely *isn't* what I observed with tags, so possibly another issue there...

**Comment by thisisrandy** [comment]
Most of what I reported is intended behavior, as it turns out. I hadn't realized that in/out brackets behave differently as *input* these modes (I'm pretty sure that only mattered for *output* in `vim-surround`, which is my reference point).

It's still unclear to me if there's a way to get tag deletion to clear empty lines. That seems almost always desirable, so I may submit a PR later on.

**Comment by echasnovski** [comment]
Yes, this is indeed the case of [difference between opening and closing parenthesis/brackets](https://en.wikipedia.org/wiki/Clapperboard). And as newline character is whitespace, it is also included in the `{` / `[` / `(` surroundings. Tip for future: you can (temporarily) highlight the (found with `sd`, `sr`, `sf`, `sF`) surrounding with `sh`. For example, `sh{` or `sh(`.

> Most of what I reported is intended behavior, as it turns out. I hadn't realized that in/out brackets behave differently as _input_ these modes (I'm pretty sure that only mattered for _output_ in `vim-surround`, which is my reference point).

You can address this at least these approaches:
- Use closing character instead of opening: `sd)`, `sd}`.
- Modify input part of relevant surroundings to include only single character on left and right. With something like this:
    ```lua
    require('mini.surround').setup({
      custom_surroundings = {
        ['('] = { input = { '%b()', '^.().*().$' } },
        ['['] = { input = { '%b[]', '^.().*().$' } },
        ['{'] = { input = { '%b{}', '^.().*().$' } },
      },
    })
    ```

**Comment by thisisrandy** [comment]
Highlighting is actually a great tip for understanding what's about to be changed. I'll admit I was failing to see its utility before you pointed that out. Thanks for your help.
