### ISSUE TITLE
Add mini.pick pickers to mini.extra for listing and toggling breakpoints, scopes and frames of nvim-dap.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1351]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick, mini.extra

### Description

Hi echasnovski! Is it in scope to add pickers to leverage nvim-dap functionality to toggle breakpoints, scopes and frames to mini.extra just like how fzf-lua does with commands like `dap_breakpoints`, `dap_variables` and `dap_frames`. And if you are ok with including these in mini.extra and are ok with me contributing, I can probably try raising a PR for these pickers if can get them to work to mini.extra.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think including anything debug/breakpoint/DAP related to 'mini.nvim' makes sense before there is a relatively straightforward, organized, and documented way to deal with them. Either as 'mini.nvim' module or Neovim's built-in functionality (like with `vim.lsp`, for example). At the moment, I don't think any of these will happen, I am afraid.

Closing as not planned. But if you end up implementing any of them, would you mind making it somewhere public and linking it here? Maybe they will be useful for others.

**Comment by 231tr0n** [comment]
> Thanks for the suggestion!
> 
> I don't think including anything debug/breakpoint/DAP related to 'mini.nvim' makes sense before there is a relatively straightforward, organized, and documented way to deal with them. Either as 'mini.nvim' module or Neovim's built-in functionality (like with `vim.lsp`, for example). At the moment, I don't think any of these will happen, I am afraid.
> 
> Closing as not planned. But if you end up implementing any of them, would you mind making it somewhere public and linking it here? Maybe they will be useful for others.

Sure, I will make sure to post it in discussions.

**Comment by 231tr0n** [comment]
Ok I just did some research on this and based on this comment from nvim-dap author itself https://github.com/mfussenegger/nvim-dap/discussions/810#discussioncomment-4623606, there is currently an internal api like ``require('dap.breakpoints').get()`` but the cavecat is that it is internal and not meant for external use and its arguments can change anytime without notice since it is internal. Also about scopes and frames there is already dap.ui.widgets for that and they can be used to show both scopes and frames using the following remaps.
``lua	
Nmap("<leader>ds", ":lua require('dap.ui.widgets').centered_float(require('dap.ui.widgets'.scopes)<CR>", "Scopes")
Nmap("<leader>df", ":lua require('dap.ui.widgets').centered_float(require('dap.ui.widgets').frames)<CR>", "Frames")
``
The first one is for scopes and the second one is for frames.
As per breakpoints we have ``require("dap").list_breakpoints()`` which will populate quickfix list with all the breakpoint lines.
We also have ``require("dap").clear_breakpoints()`` to clear all breakpoints. 

So the clever way to deal with specific bulk breakpoint toggling is probably to delete unecessary items in the quickfix list and just use some command like `cdo` and call the toggle_breakpoint function on that line is probably the way to go.
Since the quickfix list is populated when we call list_breakpoints() method, we can probably view it using mini.pick using something like MiniExtra.pickers.list({scope = "quickfix"}).

**Comment by echasnovski** [comment]
Yeah, this looks similar to [what is done in 'ibhagwan/fzf-lua'](https://github.com/ibhagwan/fzf-lua/blob/9427dc65afaa7972fb20fc52280cd1449f691928/lua/fzf-lua/providers/dap.lua#L79).

**Comment by 231tr0n** [comment]
> Yeah, this looks similar to [what is done in 'ibhagwan/fzf-lua'](https://github.com/ibhagwan/fzf-lua/blob/9427dc65afaa7972fb20fc52280cd1449f691928/lua/fzf-lua/providers/dap.lua#L79).

Yeah either way, what you told initially stands right since dap.breakpoints module is not a complete one yet since the author wanted to add support for something called data breakpoints and will then probably work on providing a widget for toggling breakpoints. So since the api is not stable, there is probably no point in writing a picker as of now for it.
