### ISSUE TITLE
Mini.Deps: add more helper functions for lazy loading

### ISSUE THREAD

**Issue by leath-dub** [echasnovski/mini.nvim#1353]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.deps

### Description

First off, thank you ! Your plugin is busybox on crack for neovim !

I have started using `mini.deps` after managing plugins with git submodules before. I have a few helper functions that I wrote for lazy loading and was wondering if you think they would fit in `mini.deps`.

Here are the functions:

```lua
function stub.keymap(mode, lhs, callback, opts)
  vim.keymap.set(mode, lhs, function()
    vim.keymap.del(mode, lhs)
    callback()
    vim.api.nvim_input(lhs) -- replay keybind
  end, opts)
end

function stub.command(c, callback)
  vim.api.nvim_create_user_command(c, function(cr)
    local args = not vim.tbl_isempty(cr.fargs) and table.concat(cr.fargs, " ") or nil
    vim.api.nvim_del_user_command(c) -- remove stub command
    callback()
    vim.cmd(c .. (args and (" " .. args) or ""))
  end, { nargs = "*" })
end

function stup.require(mod, callback)
  package.preload[mod] = function()
    package.loaded[mod] = nil
    package.preload[mod] = nil
    return callback()
  end
end
```

`stub.keymap` just lets you only load on a keymap that is triggered, `stub.command` only loads when a command is run and `stub.require` will only load if the specified module has being tried to "require".

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The 'mini.deps' module [only supports two stage loading](https://github.com/echasnovski/mini.nvim/blob/6714e738555b1cfbef646a23af29aa113f91f4fe/doc/mini-deps.txt#L154) and I'd like it to be that way. Mostly because of simplicity: both on plugin side and user side. I personally think that these types of complex lazy loading are rarely needed in practice and usually is a major source of user confusion.

However, those snippets look fairly compact and non-trivial, so maybe will be added to the wiki in the future, if you don't mind.

Closing as not planned.

**Comment by leath-dub** [comment]
> Thanks for the suggestion!
> 
> The 'mini.deps' module [only supports two stage loading](https://github.com/echasnovski/mini.nvim/blob/6714e738555b1cfbef646a23af29aa113f91f4fe/doc/mini-deps.txt#L154) and I'd like it to be that way. Mostly because of simplicity: both on plugin side and user side. I personally think that these types of complex lazy loading are rarely needed in practice and usually is a major source of user confusion.
> 
> However, those snippets look fairly compact and non-trivial, so maybe will be added to the wiki in the future, if you don't mind.
> 
> Closing as not planned.

that makes sense, do what you wish with the snippets.

**Comment by shuber2** [comment]
I have made a package out of this code, see [oneshotstubs.vim](https://github.com/shuber2/oneshotstubs.nvim).
