### ISSUE TITLE
Add option to toggle at global level instead of local

### ISSUE THREAD

**Issue by gabeklavans** [echasnovski/mini.nvim#1355]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.basics

### Description

I’d personally prefer the toggles occur at the global level (`set` instead of `setlocal`). An option to determine which level is used for all toggles would be great. Even better if this could be configured per-toggle but I think that might not be worth the effort.

**Comment by gabeklavans** [comment]
Shoot messed up the module name on submission

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Indeed, 'mini.basics' has overall design of being as much "plug and play" as possible. Yet I don't think having this kind of configurability in this case is worth it.

Moreover, I'd like to encourage users to move away from parts of 'mini.basics' that they want to precisely customize (it is [more or less mentioned in help](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-basics.txt#L32-L35)). So my suggestion would be to creating your own mappings that use `:set` following [this part of source code](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/lua/mini/basics.lua#L613-L638). If you want only part of mappings to use `:set` you can create them after `require('mini.basics').setup()` to override only part of them.

Closing as not planned.

**Comment by gabeklavans** [comment]
Fair enough! Thanks for all your work
