### ISSUE TITLE
Add support for using grep and find command of gnu utils to mini.pick.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1356]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Hi echasnovski! Is it possible to add support for using grep and find commands of gnu utils as tools for mini.pick's grep and files builtins as fallbacks before git. This is for the case when there is no fd or rg installed.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't those will be added as built-in tools in 'mini.pick'. Mostly for these reasons:
- I strongly suggest users to install `rg` to use in all `files`/`grep`/`grep_live` built-in pickers.
- Both `find` and `grep` don't seem to be as cross platform as already present tools.
- There is a 'fallback' tool which should work without needing to install any third party software. Yes, it is relatively slow, but should be enough as a fallback.

Closing as not planned.
