### ISSUE TITLE
`virtualedit=all` and mini.ai yank

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1359]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

with `virtualedit=all`
`mini.ai` yank newline as space

### Neovim version

v0.10.2

### Steps to reproduce

1. with these lines:

```
'
okay
'
```

2. move cursor to letter `o`

3. press `yi'`

### Expected behavior

register text:
`^Jokay^J`

### Actual behavior

register text:
`^Jokay `

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce. I wouldn't call the exact behavior itself a bug, but the fact that it is inconsistent with any other 'virtualedit' value might indeed be. I'll take look.

**Comment by echasnovski** [comment]
After 812917c this now should work for 'selection=exclusive'. For combination of 'virtualedit=all' and 'selection=inclusive' collapsing multline regions doesn't work for technical reasons ([read here more](https://github.com/echasnovski/mini.nvim/blob/2435d0de00174a45d6b352fefeaa6008ebe9f23b/lua/mini/ai.lua#L1037-L1041)). There *is*a solution, but it is a bit clumsy and potentially expensive/breaking, so I don't think worth it in this particular case.
