### ISSUE TITLE
mini.git cannot run `Git commit -m "a string with spaces"`

### ISSUE THREAD

**Issue by brianhuster** [echasnovski/mini.nvim#1360]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.git

### Description

Sometimes I just want to write a short message, I will use `Git commit -m "some messages"`. But mini.git cannot run that, and throw error `(mini.git) pathspec did not match any files known to git`

### Neovim version

NVIM v0.11.0-dev-1210+g3597633075

### Steps to reproduce

1. `nvim -c "lua require('mini.git').setup()"`
2. Go to a Git repository that has been modified
3. Run `:Git commit -m "my messages"`
4. It will throw an error

### Expected behavior

I want it to behave like vim-fugitive, it just run the command and returns the same output as I run `git commit -m "my messages"` in terminal

### Actual behavior

`(mini.git) pathspec 'messages"' did not match any files known to git`

**Comment by echasnovski** [comment]
Thanks for the issue!

This is an [intended behavior](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-git.txt#L184-L186), which I think is the better approach as it aligns with how built-in commands work.
