### ISSUE TITLE
fit oil.nvim’s ssh file system function

### ISSUE THREAD

**Issue by Parsifa1** [echasnovski/mini.nvim#1361]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I would like to ask if you are willing to adapt mini.files to fit this https://github.com/stevearc/oil.nvim#ssh. If not, please ignore this issue.

**Comment by echasnovski** [comment]
[Only local file system](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-files.txt#L30) is planned to be supported. I am not *actually* opposed to to having 'mini.files' work over SSH, but only if the cost is relatively low (in terms of code complexity and size). For example, if there will be such functions in Neovim core (maybe support through `vim.fs`), I'd adapt 'mini.files' accordingly.
