### ISSUE TITLE
[mini.icons] Can't get the icons to be displayed properly on Kitty terminal

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#1362]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.icons

### Description

I'm using Kitty terminal and have a nerd font `ttf-jetbrains-mono-nerd 3.3.0-1`, I can't get the icon to be displayed in the overflow view...

### Neovim version

0.11.0-dev-1226+gaf112e605d

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:=MiniIcons.get('file','file.lua')`

### Actual behavior

Should display the icon with the overflow view.

**Comment by echasnovski** [comment]
This doesn't look like an issue with 'mini.icons' per se.

Here are the steps that might help here:
- Install different font or [use suggested fallback](https://github.com/echasnovski/mini.nvim/blob/ccfc6300a5c17387f2899f979ecc04f942bee2a0/doc/mini-icons.txt#L61-L63). Probably try the pakcage without 'mono' in the title as some fonts might have that to indicate that *all* its glyphs should be rendered in a single cell.
- Try following [this recommendation](https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font) and adjust [`symbol_map`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.symbol_map).
- Check that [`narrow_symbols`](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.narrow_symbols) option does not override default "overflow" logic.
