### ISSUE TITLE
[mini.pick] picker not closing after an error caused when opening the file

### ISSUE THREAD

**Issue by padulkemid** [echasnovski/mini.nvim#1363]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

I was testing events called in form of `VeryLazy` or such thing that made `mason` won't load when I open a file that contains extension to be fowarded into the linter daemon (in this case `eslint_d` was installed with `mason`, but `nvim-lint` can't open the binary because `mason` registry path wasn't loaded yet because the plugin wasn't loaded yet) so I accidentally opened `mini.pick` and the error happens.

after dismissing the error (by pressing `ENTER`) the picker won't close or be dismissed, although we can spawn another picker and do such things without any bugs, its just the last picker won't close.

but we can close it by closing the buffer and it won't happen again.

some pics:
![Screenshot 2024-11-25 at 04 07 17](https://github.com/user-attachments/assets/018eafe6-7ce8-4476-89cd-770aaabe9272)
in this case, `mini.pick` overlays the error message causing the error unreadable (but the window focus will be directed to the error window) so that when you press `ENTER` it will go into the error window instead of `mini.pick`.

![Screenshot 2024-11-25 at 04 07 29](https://github.com/user-attachments/assets/e1dca396-fb5c-4380-a645-643f2ec681ae)
after the error above, the picker still exist and won't close until you close the buffer.

![Screenshot 2024-11-25 at 04 07 54](https://github.com/user-attachments/assets/d4798f08-385e-46f1-934d-c8dcf0b5c531)
you can still spawn `mini.pick` but it will overlap the last picker (normal usage, there are no bugs) 

idk this might be a very edge case or so, just pointing out, I really want to take a look in the code but haven't yet figured it out (I'm new to mini environments but already moved several of my plugins to mini (like 7 plugins) so it won't grow a hefty size in my memory I can just use mini if its already available here.

env:
- macos sonoma
- alacritty + tmux

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. put mason in lazy load state (while an lsp or linter is already installed)
3. open mini.pick
4. open file that relates the linter with (e.g: ts files with `eslint_d`)

### Expected behavior

if there are errors we could just destroy the picker, i think...

### Actual behavior

defined above in the description (with images).

here are the video observation:

https://github.com/user-attachments/assets/2578a502-cd1e-4d70-b8cb-a87df3229aea

**Comment by padulkemid** [comment]
> Thanks for the issue!
> 
> I can partially reproduce this with `MiniPick.ui_select({'1'}, {}, function() error("Ooops!") end)`: picker window is indeed overlaying the error message but it goes away after pressing `<CR>`. So this is more about how picker react to the error when executing function from the mapping. I'll take a look.

hi thanks for replying, is there something I can help to fix this? (maybe I'll try to read some of the stuff in `mini.pick` repo first)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think I already have it fixed. Would you mind installing 'mini.nvim' from [`backlog` branch](https://github.com/echasnovski/mini.nvim/tree/backlog) and see if it fixes your particular case?

**Comment by padulkemid** [comment]
yes its working! thank you very much @echasnovski (although this is a very edge cases, you still respond T__T)

**Comment by echasnovski** [comment]
> yes its working! thank you very much @echasnovski (although this is a very edge cases, you still respond T__T)

Great! And it is not *that* edge case as proper error handling is a good idea anyways (and I kind of surprised 'mini.pick' didn't handle it earlier).

I can't merge the fix today, so hopefully tomorrow.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main`. Thanks for the early feedback!
