### ISSUE TITLE
mini.align: add default modifier for pipe (|)

### ISSUE THREAD

**Issue by aktau** [echasnovski/mini.nvim#1368]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.align

### Description

There's already some pre-existing modifiers for common splits, like `=`. For example:

https://github.com/echasnovski/mini.nvim/blob/c8922aef8207137e66c80acdb9523668599ba62a/lua/mini/align.lua#L595-L601

I think the pipe is another common one. I use it a lot for markdown-like tables (also in plain text). I've got the following:

```lua
      -- Add special modifier for pipes, often used for (markdown) tables.
      -- mini.align already has builtins for ["="], [","] and [" "].
      modifiers = {
        ["|"] = function(steps, opts)
          opts.split_pattern = "|"
          table.insert(steps.pre_justify, mini.align.gen_step.trim("both", "keep"))
          opts.merge_delimiter = ' '
        end,
      },
```

One could consider adding it to the default set.

**Comment by echasnovski** [comment]
The "|" character now should have its built-in modifier as suggested here. Thanks again for the suggestion!
