### ISSUE TITLE
mini.jump shortcuts doesn't work when used with ':norm' to delete a character with 'x'

### ISSUE THREAD

**Issue by AliGaygisiz** [echasnovski/mini.nvim#137]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.jump

### Description

When mini.jump shortcuts used with `:norm` to delete a character with `x`, it only deletes the first character it found in selected text.

### Neovim version

0.7.2

### Steps to reproduce

1. Open a file that has more than one line, choose a character that included on those lines ('a' will be used for example).
2. Select those lines with visual mode.
3. Try to run `:norm fax`

### Expected behavior

Selected character should be deleted from all selected lines.

### Actual behavior

Only the character in the first line that includes selected character gets deleted.

![output](https://user-images.githubusercontent.com/30773603/193450449-32aabb60-9bbb-46d4-ac44-ba73f508f290.gif)
![output2](https://user-images.githubusercontent.com/30773603/193450455-cec03432-6683-421f-95be-d19ab79fbfdd.gif)

**Comment by echasnovski** [comment]
Thanks for the issue!

I'll look into it, but shouldn't this be equivalent to `:'<,'>norm! f,x` (with `!`)?

**Comment by AliGaygisiz** [comment]
Yes `:norm!` works, thanks for the tip.

**Comment by AliGaygisiz** [comment]
Accidentally closed it, sorry😅

**Comment by echasnovski** [comment]
This should be fixed on latest `main` branch.

The reason was that `:normal-range` doesn't issue `CursorMoved` when it moves cursor on start of every line. As this event is used to stop smart jumping (when you press `ftFT` to repeat jump with same target), this lead to some complications.
