### ISSUE TITLE
mini.indentscope will not show indent if there are blank lines in between

### ISSUE THREAD

**Issue by xzbdmw** [echasnovski/mini.nvim#1371]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

https://github.com/user-attachments/assets/73119af1-6c95-4023-81ac-b3c8dcc4a4a2

### Neovim version

0.10

### Steps to reproduce

same as video.

### Expected behavior

the innder "if" node is expected to be identified.

### Actual behavior

If node is ignored if there is a blank line in between

**Comment by echasnovski** [comment]
Thanks for the issue!

Behavior in video is as expected. When `z` characters are removed, the line becomes blank. In this case its indent is computed [based on previous and next non-blank lines](https://github.com/echasnovski/mini.nvim/blob/c8922aef8207137e66c80acdb9523668599ba62a/doc/mini-indentscope.txt#L258-L262). In this case (assuming default `config.options.border` being `'both'`) it will be the same as both `if ...` and `}` lines. So it shows a scope of lines which have at least this indent ([as per definition](https://github.com/echasnovski/mini.nvim/blob/c8922aef8207137e66c80acdb9523668599ba62a/doc/mini-indentscope.txt#L8-L11)) and it happens to be the parent `for` scope.

Closing as working as expected.

**Comment by xzbdmw** [comment]
Thanks, sorry I did not read the documentation carefully. May I suggest that distinguish between zero length lines and lines containing only blank characters and tabs, because the former if what we really want to ignore but the latter makes sense taking into account like the video.

**Comment by echasnovski** [comment]
> May I suggest that distinguish between zero length lines and lines containing only blank characters and tabs, because the former is what we really want to ignore but the latter makes sense taking into account like the video ( sometimes I want to `dai` on the not yet completed if).

I don't think that is a good idea. Mostly because of the nature of the indent itself: it is a whitespace before the "main part" of the line. With blank lines any separation might result in indent and main part.

Plus, blank lines are not ignored: their indent is computed based on the surroundings.

So although I can understand the issue of not being able to `dai` in this case, I don't this this is going to change.

**Comment by xzbdmw** [comment]
> With blank lines any separation might result in indent and main part.
I don't understand that, could you give me an example?

**Comment by echasnovski** [comment]
> > With blank lines any separation might result in indent and main part.
> 
> I don't understand that, could you give me an example?

The line `\t\t` can (in theory) be considered as
- `''` indent and `'\t\t'` main part.
- `'\t'` indent and `'\t'` main part.
- `'\t\t'` indent and `''` main part.

If define "main part" as "any non-whitespace charater", then there is none in blank lines. So fall back to neighbor lines.

**Comment by xzbdmw** [comment]
I think this problem can be delegated to `vim.fn.indent` though, where it will report the whole `\t\t` as indented.
