### ISSUE TITLE
How to close nvim-tree before save session?

### ISSUE THREAD

**Issue by maosocial** [echasnovski/mini.nvim#1376]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

sessions

### Description

I tried this:
```lua
hooks = {
    pre = { read = nil, write = (require("nvim-tree.api").close()) , delete = nil },
},

```
but get error:
```module 'nvim-tree.api' not found:```

**Comment by echasnovski** [comment]
For future reference: at least one issue here was that `(require("nvim-tree.api").close())` is executed immediately, i.e. during `require('mini.sessions').setup()` call, when it should be wrapped in `function() ... end` to be a function hook that gets executed when it is needed.
