### ISSUE TITLE
V-Line & V-Block don't appear until a motion is made

### ISSUE THREAD

**Issue by downhiller** [echasnovski/mini.nvim#1377]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

I actually don't know that this is a bug.  Maybe it's a feature.  If so can someone explain why this is desirable, as a relative newbie it's not clear to me.

When I enter normal/insert/visual mode, the statusline notifies me of this immediately.  But if I enter visual-line or visual-block, the statusline stays on "Normal" until I key a movement, and then and only then does the mode on the statusline change to whichever of the two modes I selected.

If I start `nvim --clean`, `visual-line` and `visual-block` show immediately upon keying `<S-v>` & `<C-v>`, so this is a side-effect of this plugin, rather than something NeoVim does as standard.

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. <C-v>

### Expected behavior

Expect status-line to show "visual-block"

### Actual behavior

Status-line shows "normal"

**Comment by downhiller** [comment]
My apologies, this appears to be an issue with folke/which-key.nvim, not mini.nvim.

**Comment by echasnovski** [comment]
Glad you sorted that out!

My first instinct would be to check if there are any mapping that start with `V` or `<C-v>`. In that case Neovim would wait for 'timeoutlen' milliseconds (1000 by default) for user to type another key to make sure that it doesn't have to execute the mapping.
