### ISSUE TITLE
Autocomplete doesn't give options

### ISSUE THREAD

**Issue by AutoAFK** [echasnovski/mini.nvim#138]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completeion

### Description

I have mini.completetion setup with mason-lsp.
For some reason I don't get any suggetsions of completion in my go file unless its something
that has been written in any of the open buffers.

### Neovim version

0.7.0

### Steps to reproduce

1. setup mini.completetion
2. setup mason (lsp installer) from [this](https://github.com/williamboman/mason-lspconfig.nvim)
3. downloaded the server (gopls)

### Expected behavior

An autocompletetion in my go file 
For example: If i write S i would like it to suggest Struct
or if I type fmt. It should suggest functions from the fmt library

### Actual behavior

it doesn't suggest anything.

![image](https://user-images.githubusercontent.com/91673569/193645747-3cc4e20b-d35f-411d-8b79-2d9d7567bfff.png)

**Comment by echasnovski** [comment]
It doesn't look right now as a 'mini.completion' issue. Do you have other LSP servers set up? If yes, do they work (provide completion results from language server)?

It can be a misconfigured language server. One sure way to find out is this:
- Add these lines somewhere inside your config:
```lua
_G.lsp_results = false
_G.track_lsp = function()
  _G.lsp_results = {}
  vim.lsp.buf_request_all(
    vim.api.nvim_get_current_buf(),
    'textDocument/completion',
    vim.lsp.util.make_position_params(),
    function(result) table.insert(_G.lsp_results, result) end
  )
end

-- Change `<M-m>` keybinding to your liking
vim.keymap.set('i', '<M-m>', '<Cmd>lua _G.track_lsp()<CR>', {})
```
- When you expect to see an LSP completion result in Insert mode, type `<M-m>` (or other mapping, if you changed it).
- Type `:lua print(vim.inspect(_G.lsp_results))` and look at output. It should contain a table with everything retrievable from LSP servers under that conditions. If it is empty, 'mini.completion' can do nothing. Look at how to configure LSP server.

Another thing might be a misconfigured 'mini.completion'. For example, what is the output of the following code: `:lua print(vim.inspect(vim.o[MiniCompletion.config.lsp_completion.source_func]))` ?

**Comment by echasnovski** [comment]
After looking at your config, I think this is a LSP misconfiguration issue.

You seem to have installed Go language server ([via 'williamboman/mason-lspconfig.nvim'](https://github.com/AutoAFK/VimConfig/blob/c6c356063244188a395ca4260c6c9c3478408613/init.lua#L37-L40), but you didn't tell Neovim to automatically use it (attach) in Go files. You still need ['neovim/nvim-lspconfig'](https://github.com/neovim/nvim-lspconfig) for that (as it says in 'mason-lspconfig' docs).

**Comment by AutoAFK** [comment]
> After looking at your config, I think this is a LSP misconfiguration issue.
> 
> You seem to have installed Go language server ([via 'williamboman/mason-lspconfig.nvim'](https://github.com/AutoAFK/VimConfig/blob/c6c356063244188a395ca4260c6c9c3478408613/init.lua#L37-L40)), but you didn't tell Neovim to automatically use it (attach) in Go files. You still need ['neovim/nvim-lspconfig'](https://github.com/neovim/nvim-lspconfig) for that (as it says in 'mason-lspconfig' docs).

Yeah that fixed everything for me :) 
My bad though, didn't see this section.
