### ISSUE TITLE
make `help message delay` configurable

### ISSUE THREAD

**Issue by aidancz** [echasnovski/mini.nvim#1381]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround mini.align etc

### Description

I notice that many mini modules hard code the `help message delay` to 1 second:

for example:

- **mini.surround**:

https://github.com/echasnovski/mini.nvim/blob/690a3b4c78c4956f7ecf770124b522d32084b872/lua/mini/surround.lua#L1948

- **mini.align**:

https://github.com/echasnovski/mini.nvim/blob/690a3b4c78c4956f7ecf770124b522d32084b872/lua/mini/align.lua#L1794

---

I am aware that many modules can be configured with `silent = true`, this is equivalent to setting `delay = ∞`

users have to choose `delay = 1000` or `delay = ∞`, but they might prefer other values

would you be willing to add an option to allow the delay to be configurable?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I am hesitant about adding an extra configuration in general, yet alone the one that can already be partially configured in a way that I see matters.

Would you mind elaborating a bit about why do you think this is needed? Is it a personal preference and you want to make delay longer/shorter or is there some technical reason (it conflicts with something, etc.)?

**Comment by aidancz** [comment]
This is my personal preference.  

I like instant feedback (`delay=0`) or no feedback at all (`delay=∞`).  

I feel anxious in the following two situations:  

1. When I haven't pressed any key, but information appears on the screen.  
2. If I happen to finish pressing a key slightly over one second, the feedback message will flash briefly, causing the screen to flicker.  

With a delay of one second, these two situations occur quite frequently...  

Moreover, when I first started using mini, I mistakenly thought mini was so slow that I needed to wait one second for feedback (I didn’t read the help file carefully).  

For these reasons, I believe adding a `delay` option is necessary—at least allowing the choice of `delay=0`.

**Comment by echasnovski** [comment]
Thanks for clarification!

I am strongly against instant feedback. Mostly because it gets annoying pretty quickly at the rate 'mini.ai' and 'mini.surround' keys are expected to be used.

> 2\. If I happen to finish pressing a key slightly over one second, the feedback message will flash briefly, causing the screen to flicker.

Unfortunately, this will be the case for any manually set finite delay. Yes, users can tweak it to adjust to their typing speed, yet my instinct is that 1 second delay should cover majority frequently used textobjects/surroundings. Mostly because they are expected to be typed quicker as muscle memory settles in.

> Moreover, when I first started using mini, I mistakenly thought mini was so slow that I needed to wait one second for feedback (I didn’t read the help file carefully).

*This* is a real concern. I remember seeing couple of such feedbacks. The main point of these helper messages were exactly for the beginners who are not yet comfortable with using textobjects and surroundings to remind them what should be done after pressing `a`, `i`, `sd`, `sr`, etc. Probably making it documented more prominently is a good idea. I'll take a look.

**Comment by echasnovski** [comment]
`main` branch now has mentions that those helper messages are purely informational. It is right next to `silent = false` in default config which is present in both module's help and README. Hope this will clarify that there is no need of waiting for the message to press the key.

------

I think I am going to close this for reasons from previous comments.

**Comment by aidancz** [comment]
> I am strongly against instant feedback. Mostly because it gets annoying pretty quickly at the rate 'mini.ai' and 'mini.surround' keys are expected to be used.

Yes, I agree with this. I have set `silent = true` for these two modules.  

As for `mini.align`, I find the help information to be very useful.

It would be better if `ga` had quick feedback like `gA`, I think.

**Comment by echasnovski** [comment]
> It would be better if `ga` had quick feedback like `gA`, I think.

`ga` is intended for a quick `gaip=` / `gaip<Space>`, so showing the message immediately also feels distracting. For a more complex aligning I suggest using `gA` which is intended to be more interactive.
