### ISSUE TITLE
Use a real buffer for mini.pick prompt

### ISSUE THREAD

**Issue by Lattay** [echasnovski/mini.nvim#1383]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Using a normal scratch buffer as the prompt of mini.pick would improve user experience by automatically providing the normal nvim experience while simplifying the logic at the same time, as lots of key handling would be delegated to nvim. For example it would automatically get Home key or '<c-o>0' working, and let one remove all the code related to "special keys".

Would you be interested in merging a PR that replace the prompt of mini.pick with a real buffer?

I haven't looked at the prompt implementation much yet, but it seems like it could be a pretty big refactor, so I would understand if this is out of scope.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is certainly out of scope. It is both against [main goal of having single window design](https://github.com/echasnovski/mini.nvim/blob/73bbcbfa7839c4b00a64965fb504f87461abefbd/doc/mini-pick.txt#L10) and will disrupt [one of the advantages of 'mini.pick'](https://github.com/echasnovski/mini.nvim/blob/73bbcbfa7839c4b00a64965fb504f87461abefbd/doc/mini-pick.txt#L208-L210).

Closing as not planned.
