### ISSUE TITLE
mini.surround doesn't seem to work in macros?

### ISSUE THREAD

**Issue by RUGMJ** [echasnovski/mini.nvim#1385]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

When recording a macro mini.surround doesnt seem to function

### Neovim version

0.10.2

### Steps to reproduce

1. Begin recording a macro `qq`
2. Attempt to use mini.surround `sr[(`
3. See broken output

### Actual behavior

When recording a macro running `sr[(` will replace the character under the cursor with `(` instead of replacing the surrounding brackets with parentheses.

**Comment by RUGMJ** [comment]
Okay, i'm going crazy. Just tried it again and for some reason it's working fine. Sorry for the mess

**Comment by echasnovski** [comment]
Yes, I also have no clue why this didn't work. 'mini.surround' should be fine to use in macros.

**Comment by danielfleischer** [comment]
The trick here is to go quick, e.g. press `gsr` or `gsa` quick to get it to work, there is some delay that is missing, maybe because which-key is disabled in macros, it means we need to go quick with the combination.

**Comment by RUGMJ** [comment]
that'd make sense, i was still trying to get used to the binds at that point.
