### ISSUE TITLE
mini.align: accept optional line count prefix

### ISSUE THREAD

**Issue by c4rlo** [echasnovski/mini.nvim#1388]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.align

### Description

It would be nice if `mini.align`'s `ga` and `gA` maps accepted an optional count that was interpreted as the number of lines to operate on.

For example, in order to `=`-align the 5 lines counting from the current one, currently this is done via `ga4j=`. I am proposing to also allow `5ga=`. Note this saves a keystroke.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This indeed sounds interesting. Yet I don't think it is enough to justify added complexity (both in code and mental). Right now `ga` and `gA` are regular operators (same as built-in `d`, `c`, etc.) and always expect textobject/motion after it. Having a different fixed linewise behavior for when `v:count` is supplied seems to be going against all established operators logic.

Closing as not planned.
