### ISSUE TITLE
[mini.files] `cursorline` is visible in file preview

### ISSUE THREAD

**Issue by tvsfx** [echasnovski/mini.nvim#1391]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When setting 
```lua
vim.opt.cursorline = true
vim.opt.cursorlineopt = "line" -- Or "both"
require("mini.files").setup({ windows = { preview = true } })
```
The file preview will have the cursorline set.
I would turn the `cursorline` off myself in the `MiniFilesWindowOpen` handler, but there seems to be no way currently to differentiate between a preview of a file vs. a (preview of a ) directory in `mini.files` (bar requesting more state from `mini.files` and/or traversing the filesystem ourselves)

### Neovim version

v0.10.2

### Steps to reproduce

1. Use config options above
2. Open `mini.files` and navigate to any file so that the preview is shown
3. The preview will have its cursorline set

### Expected behavior

Files do not have the cursorline set, since there is no way to edit them. For buffer previews this is different, since the line is where our cursor will land. 

### Actual behavior

Cursor line is set.

**Comment by echasnovski** [comment]
Thanks for the issue!

Haven't really noticed this myself, but I guess it indeed makes sense to not show cursorline in file previews. I'll take a look.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main` branch. Thanks again for noticing this!

**Comment by echasnovski** [comment]
Yeah, my bad, didn't interactively test when file is immediately previewed after opening explorer. Should be fixed now.

> I think the following code might be the issue:

Only partially, but yes: 'cursorline' was set initially, but did not get unset later due to a big `if` statement (which should have been a more direct `vim.wo[win_id].cursorline = <boolean: path is for directory>`.

**Comment by tvsfx** [comment]
Now it works like a charm, thanks :)
