### ISSUE TITLE
[mini.icons] Set `vim.g.nvim_web_devicons = 1` with `mock_nvim_web_devicons()`?

### ISSUE THREAD

**Issue by leaysgur** [echasnovski/mini.nvim#1393]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.icons

### Description

Hi~ 👋🏻 

I've just found some plugins (for my case, `nvim-linefly`) seem to use `vim.g.nvim_web_devicons` to detect the use of icons.

https://github.com/bluz71/nvim-linefly/blob/20102924d734a8f3ca760575b2b9a544efcf8dd3/lua/linefly/file.lua#L12

Does it make sense to set `vim.g.nvim_web_devicons = 1` in `mock_nvim_web_devicons()`?

https://github.com/nvim-tree/nvim-web-devicons/blob/e73d2774d12d0ecf9e05578d692ba1ea50508cf2/plugin/nvim-web-devicons.vim#L7

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, I think it probably does. Although it is probably not a huge deal for users to add that after a call to `MiniIcons.mock_nvim_web_devicons()`.

I'll hope to add this tomorrow.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main` branch.

**Comment by leaysgur** [comment]
Confirmed. 🤩 Thank you very much~!
