### ISSUE TITLE
MiniMisc.zoom() when setup with mini.animate causes a bug where command line renders in between buffer.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1396]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.misc, mini.animate

### Description

Basically, during scrolling animation in ``:lua MiniMisc.zoom()`` mode, the commandline renders at the center of the screen till the scroll animation is done.

### Neovim version

NVIM v0.11.0-dev-1341+g5eda7aafe9

### Steps to reproduce

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		"echasnovski/mini.animate",
		"echasnovski/mini.misc",
	},
})

vim.o.number = true

require("mini.animate").setup()
require("mini.misc").setup()
```
1. Open a file which is big enough to be scrollable for atleast 2 seconds with the following command ``nvim -u repro.lua bigfile.lua``.
2. Run the command ``:lua MiniMisc.zoom()``.
3. type ``ggG`` in normal mode to scroll from top of the file to bottom of the file. You can see that command line is rendered at the center of the screen during scrolling.

### Expected behavior

Commandline should not be rendered at the center of the screen during scrolling animation.

### Actual behavior

Commandline is rendered at the center of the screen during scrolling animation.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce. In particular, because "Open a file which is big enough to be scrollable for atleast 2 seconds ..." is not really possible with the provided 'init.lua' as it defines 250 milliseconds total scroll time.

Even with 'mini.animate' configured to have scroll of 2000 milliseconds, it is still not reproducible.

What makes you think that this is command line is rendered on top? Could you make a screencast, please?

**Comment by 231tr0n** [comment]
> Thanks for the issue!
> 
> I can not reproduce. In particular, because "Open a file which is big enough to be scrollable for atleast 2 seconds ..." is not really possible with the provided 'init.lua' as it defines 250 milliseconds total scroll time.
> 
> Even with 'mini.animate' configured to have scroll of 2000 milliseconds, it is still not reproducible.
> 
> What makes you think that this is command line that is rendered on top? Could you make a screencast, please?

I apologize for not actually uploading a screencast earlier since without it this bug wouldn't make sense and is ridiculous.
https://drive.google.com/file/d/1ljBqCHl2V3PJ1Z_TujeXWgurYYMCew4r/view?usp=sharing
I am posting the google drive link since the video is over 10mb and github is not allowing me to upload.

But in this video you can see that ``:lua MiniMisc.zoom()`` appears in the middle of the screen while scrolling. By cmdline appearing in middle, that is what I meant.

As for the file used in scrolling
https://github.com/231tr0n/config/blob/main/nvim/init.lua
repro.lua is the same as above. With this setup I am able to reproduce it.

**Comment by 231tr0n** [comment]
> Thanks for the issue!
> 
> I can not reproduce. In particular, because "Open a file which is big enough to be scrollable for atleast 2 seconds ..." is not really possible with the provided 'init.lua' as it defines 250 milliseconds total scroll time.
> 
> Even with 'mini.animate' configured to have scroll of 2000 milliseconds, it is still not reproducible.
> 
> What makes you think that this is command line that is rendered on top? Could you make a screencast, please?

Also about the scrolling, yeah my bad I meant file enough to cause a scrolling effect. I termed it wrongly i guess.

**Comment by echasnovski** [comment]
Yes, I was able to reproduce. It appeared as a 'mini.misc' issue: `zoom()` window was opened with very big dimensions to not have to compute them. Big height in particular lead to this issue of redrawing command line, presumably because window was drawn beneath it. Properly computing and updating dimensions seems to fix this on latest `main`.

Thanks again for finding this!

**Comment by 231tr0n** [comment]
> Yes, I was able to reproduce. It appeared as a 'mini.misc' issue: `zoom()` window was opened with very big dimensions to not have to compute them. Big height in particular lead to this issue of redrawing command line, presumably because window was drawn beneath it. Properly computing and updating dimensions seems to fix this on latest `main`.
> 
> Thanks again for finding this!

As always, awesome work and fastest fixes. You are a beast @echasnovski! Hope I become a software engineer like you one day!!
