### ISSUE TITLE
Beta-testing 'mini.map'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#140]
Please leave your feedback about new 'mini.map' module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by Arkoprabho** [comment]
First time around here. In case I miss some conventions or am following an anti-pattern, please do call it out.

1. Rendering issue
2. Behaviour with file explorer open on the right side (NvimTree)

![Screenshot 2022-10-11 at 11 07 20 PM](https://user-images.githubusercontent.com/16442535/195161277-46f6796a-a4b8-4d2f-ae75-2d3db481bb9f.png)

Terminal: iTerm2
Terminal Font: FiraCodeNerdFontComplete-Retina 15
OS: macOS 12.6
Neovim version:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```
Plugin Version: Latest as of commit: 1e0a7aa0d62867974ae93a73fdd39e62d8d5b7af

**Comment by Arkoprabho** [comment]
Ah, so the first set of characters are all confused boxes (apart from 2 characters),
The 2nd set though seems to render fine.

![Screenshot 2022-10-12 at 10 27 43 AM](https://user-images.githubusercontent.com/16442535/195253770-9fe852cf-47f3-4527-8f55-87a9d0cde4bb.png)

**Comment by echasnovski** [comment]
> Ah, so the first set of characters are all confused boxes (apart from 2 characters), The 2nd set though seems to render fine.
> 
> ![Screenshot 2022-10-12 at 10 27 43 AM](https://user-images.githubusercontent.com/16442535/195253770-9fe852cf-47f3-4527-8f55-87a9d0cde4bb.png)

Yeah, not much I can do here. You have at least these options:
- Use dots as encode symbols. So the setup should look something like this:
```lua
local map = require('mini.map')
map.setup({
  symbols = { encode = map.gen_encode_symbols.dot('4x2') }
})
```
- Try other terminal emulator and/or font. And/or OS :) 


(One of the reasons I chose these block elements as default, apart from a subjective better look, is that I thought they should be wider supported. Oh, well :( )

**Comment by Arkoprabho** [comment]
Dots work much better for me. Thanks.

What are your thoughts on the interaction with the explorer tree?

**Comment by echasnovski** [comment]
> Seems to work fine with Kitty, though the interaction with NvimTree still seems a bit wonky ![Screenshot 2022-10-12 at 10 34 24 AM](https://user-images.githubusercontent.com/16442535/195254603-f636cbf8-794e-471c-85ce-36a050e07996.png)
> 
> I think ideally the map should offset the tree or get offsetted by it instead of getting overlapped

Unfortunately, that is by design. It uses floating window instead of a regular one. It means it is independent of what is displayed underneath it. You can set 'winblend' option in setup to 100, but it will only help in empty areas of map window.

Having it automatically offset based on what is underneath is problematic, because there is no definitive way of setting this up in a way that will recognize all "important" underneath buffers.

There is an approach of creating new `side_offset` option, but this is not very sustainable, as it won't update on window updates.

What I would suggest as a solution here, is to create/modify mappings for opening 'nvim-tree': opening should open tree and close map, closing - close tree and open map. Instead of open/close map it can be refreshing with setting proper side.

**Comment by echasnovski** [comment]
> Is there a way to enable some color syntax based highlighting? If not, is there a plan to add it?

If you mean colorize map lines based on character colors in source buffer, then yes, I would really love to implement this. However, there is no way of doing this reliably in current version of Neovim (if ever). Once it is implemented (and I have a vague desire to dive into this some day), I'll add it to 'mini.map'.

**Comment by Arkoprabho** [comment]
Cheers!
Thanks for the input. I'll keep using the map, works fine for me with the nuances at the moment.

**Comment by assistcontrol** [comment]
There is an unfortunate cursor position issue. When cycling windows (`C-w C-w`), focus jumps to the map window, and the cursor position is always at the top, which then changes cursor position in the original window to the top. So, when cycling windows, the buffer always gets scrolled to the top.

Perhaps `CursorMoved, CursorMovedI` could change position in the map window too?

**Comment by CleoMenezesJr** [comment]
For me, the experience has been great. I just miss having the option to start the mini-map with Neovim. I don't find it interesting to have to be opening and closing it, since in the end it is a quick access map.
![image](https://user-images.githubusercontent.com/54215258/195450181-6e299f02-ebbf-4139-8259-b32632c4aefc.png)

**Comment by kovasap** [comment]
Two things I noticed:

1. Is there a way to prevent `wincmd` window switching to switch into the tree window?  I find myself switching between code windows and unintentionally ending up in the minimap window, which I don't want.
2. Is there a way to change the highlight group of the background and text in the mini map WITHOUT changing the background/text in all other floating windows?

Loving this plugin so far besides these little nits!

**Comment by assistcontrol** [comment]
>     1. Is there a way to prevent `wincmd` window switching from switch into the tree window?  I find myself switching between code windows and unintentionally ending up in the minimap window, which I don't want.

I did this in https://github.com/assistcontrol/vim/blob/main/lua/aw/functions.lua#L57. It jumps windows with a configurable skip list.

**Comment by echasnovski** [comment]
> There is an unfortunate cursor position issue. When cycling windows (C-w C-w), focus jumps to the map window, and the cursor position is always at the top, which then changes cursor position in the original window to the top. So, when cycling windows, the buffer always gets scrolled to the top.

@assistcontrol, this should be fixed on latest `main`. Now cursor is set on window local `BufEnter`. Also solution to your request enabled other small quality of usage improvement: no cursor in source window doesn't change if just focused on map window. So thanks twice for suggestion!

**Comment by echasnovski** [comment]
>     1. Is there a way to prevent `wincmd` window switching from switch into the tree window?  I find myself switching between code windows and unintentionally ending up in the minimap window, which I don't want.

@kovasap, there is a way to make floating window(s) not focusable. Unfortunately, this will also made them unfocusable for mouse clicks, which is not good. I am contemplating adding another `config.window.focusable` option for users to decide what they want. Not a fan of many options, but this might be worthwhile. Need to think a bit about it. 
 
>     2. Is there a way to change the highlight group of the background and text in the mini map WITHOUT changing the background/text in all other floating windows?

There is a way for me to implement it in latest Neovim 0.8 (via `nvim_win_set_hl_ns()`), but this plugin needs to be compatible with Neovim>=0.6. There is a `winhighlight` window-local option which should do the trick, but quick experiments didn't work out. I'll investigate it further. I see this as a new highlight group `MiniMapNormal`, which you will be able to redefine like any other highlight groups.

**Comment by echasnovski** [comment]
> For me, the experience has been great. I just miss having the option to start the mini-map with Neovim. I don't find it interesting to have to be opening and closing it, since in the end it is a quick access map.

Yeah, of course, it is reasonable to want it to autoopen. The reason why it is not done inside module is [described in documentation](https://github.com/echasnovski/mini.nvim/blob/89c77d220f546782f1da12fe451c6a56c479ffd4/doc/mini-map.txt#L59-L70). Basically the same reasoning as to why I don't want to add `filetype_disable` to configs: too many user scenarios to cover.

For example, I use 'mini.starter' and don't want map window to appear in Starter buffer, but rather after it. So I remapped `<CR>` in the buffer.

**However**, I assumed adding `MiniMap.open()` call on `VimEnter` event should work. But I can't make it happen... Need to investigate further to make a more reliable advice on how to autoopen. Any input is welcome here.

**Comment by echasnovski** [comment]
> Is there a way to prevent wincmd window switching from switch into the tree window? I find myself switching between code windows and unintentionally ending up in the minimap window, which I don't want.

@kovasap, on latest `main` by default map window is now not focusable with normal methods (`wincmd`, `<C-w>`, or mouse).

If someone wants focusability with mouse (but also with `wincmd` and `<C-w>`, as Neovim window setting can only toggle them together), set `config.window.focusable` to `true`.

**Comment by zeitchef** [comment]
Something I've just noticed is that when setting `show_integration_count = false` the padding is collapsed because that column disappears. Would be great if that remained consistent, I think.

<img width="149" alt="Screen Shot 2022-10-14 at 11 23 01" src="https://user-images.githubusercontent.com/6670659/195812486-16d390bc-8ea3-4d16-ac6b-38cf5bb05205.png">

**Comment by echasnovski** [comment]
> Something I've just noticed is that when setting show_integration_count = false the padding is collapsed because that column disappears. Would be great if that remained consistent, I think.

No, that is intentional to allow users to save space or increase width of actual map content. If you want padding, add them to scrollbar symbols. In your case it seems to be something like this:
```lua
...
symbols = { scroll_line = '▶ ', scroll_view = '┃ ' },
window = { show_integration_count = false },
...
```

**Comment by zeitchef** [comment]
@echasnovski Cool. It was enough for me to add `symbols = { scroll_line = '▶ ' }` - everything shifted back over. Thanks!
