### ISSUE TITLE
mini.map to support `marks`

### ISSUE THREAD

**Issue by echaya** [echasnovski/mini.nvim#1400]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.map

### Description

Can we consider supporting `marks` in map. This is the only missing / useful feature that prevent me from switching from `satellite.nvim` . I use it when trying to edit text between 2 marks. Thanks!

**Comment by echasnovski** [comment]
Thanks foe the suggestion!

'mini.map' allows creating [custom integrations](https://github.com/echasnovski/mini.nvim/blob/7ebfab26d77a4b9b05aaae565907e7fa4b2ee154/doc/mini-map.txt#L285). I don't think integration for marks will be built-in.

Closing as not planned.

------

I'd encourage you to try and create integration that suits you best here. If you don't have time/enthusiasm to do it yourself, I can help with at least some challenging aspects here if you describe what you want 'mini.map' to display and how.

**Comment by echaya** [comment]
Thanks much for the offer! I guess what I'm missing is some example code to show how custom integration looks / works. Some sample code to start with could be super helpful. Ultimately, I'd like to display the `mark` within the map at its approximate location. Below is a combination of `satellite` and `MiniMap`

![image](https://github.com/user-attachments/assets/6172bd16-5aac-4795-8f30-3cd1806f3688)
