### ISSUE TITLE
mini.clue interferes with z<CR>

### ISSUE THREAD

**Issue by rothskeller** [echasnovski/mini.nvim#1405]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

nvim has a default binding for z<CR>, which moves the current line to the top of the screen.  When mini.clue is in use, it eats the <CR>, and one has to type z<CR><CR> to get the desired behavior.  I'm not sure if there are any other bindings that include a <CR>, but if so, they would presumably have the same issue.

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. install mini.clue with suggested config that has trigger for 'z'
3. type z<CR>

### Expected behavior

Should move current line to top of screen.

### Actual behavior

Enters the 'z' prefix without the typed <CR>

**Comment by echasnovski** [comment]
Thanks for the issue!

I am afraid there is no clear solution to this:
- 'mini.clue' *needs* some key to execute the currently typed keys because there can be a mapping for it. I would not recommend having this kind of setup (like have both `<Leader>s` and `<Leader>st` mappings, for example), but some cases it might be justified. And not being able to execute some mappings is worth than having an inconvenience during some other mappings (which I'd argue are not common).
- To be perfectly honest, I was surprised to learn about `z<CR>` because I always use `zt` for that. It has better mnemonic (`z` - "top"), is easier to type, and I'd argue more ergonomic (preserves cursor column instead of moving to the first non-blank character). If you want to preserve `z<CR>` behavior, I'd recommend remapping `zt` with something like `nnoremap zt zt^`.

Closing as not planned.

**Comment by koljakube** [comment]
Sorry to revive this, but I'm having the same issue (using neovim-orgmode, where `<Leader><CR>` maps to a context-aware "continue in the next line with the current type of paragraph" type of action (`org-meta-cr`).

As far as I can tell (and according to mini-clue), that is the only mapping involving CR, and the behavior is the same as @rothskeller described. What exactly does mini-clue need here? All other mappings work find without doubling any input (and I really need clue to get the hang of all those mappings, so: thank you!). If there is some internal mapping-to-a-dummy-key going on, why not use something not found on most keyboards, like F24?

**Comment by echasnovski** [comment]
> What exactly does mini-clue need here? All other mappings work find without doubling any input (and I really need clue to get the hang of all those mappings, so: thank you!). If there is some internal mapping-to-a-dummy-key going on, why not use something not found on most keyboards, like F24?

The `<CR>` is a part of ['mini.clue' lifecycle](https://nvim-mini.org/mini.nvim/doc/mini-clue.html#miniclue-key-query-process-lifecycle), same as other special keys: `<Esc>`, `<C-c>`, `<BS>`, `<C-u>`, `<C-d>`. They have special meaning when advancing the key query process that 'mini.clue' provides and nothing to do with "mapping-to-a-dummy-key".

So I am afraid the suggestion here is to either not use triggers that result into mapping with these special keys or prefer other keys. Whichever keys are chosen for these special actions, there will always be a possibility of this sort of collisions. The current choice makes the most sense in what keys are intended to do.

**Comment by koljakube** [comment]
Wow, that was quick! Thank you, and sorry for not looking at the docs first. That section explains everything really well! The examples given starting with `g` also explain why that behavior can't be easily deactivated even though all my _personal_ mappings only distinct sequences.

What I can gather from [what I think is the corresponding source location](https://github.com/nvim-mini/mini.clue/blob/d846600d4664dc793aa29859ad135b1fd25d648b/lua/mini/clue.lua#L1396), this behavior is hardcoded. I guess I need to get creative, hitting three keys just for a smarter linebreak is a bit much.

**Comment by echasnovski** [comment]
> What I can gather from [what I think is the corresponding source location](https://github.com/nvim-mini/mini.clue/blob/d846600d4664dc793aa29859ad135b1fd25d648b/lua/mini/clue.lua#L1396), this behavior is hardcoded. I guess I need to get creative, hitting three keys just for a smarter linebreak is a bit much.

Yes, all non-scroll special keys are hardcoded because they both are the first choices for their respective functionalities and making them configurable won't solve the problem of needing such keys per se.
