### ISSUE TITLE
Ident.nvim - Overshadows and hides text in some peculiar cases

### ISSUE THREAD

**Issue by sultanahamer** [echasnovski/mini.nvim#141]
I have recently moved to neovim 8.0 and was testing if all plugins are working. I wasn't testing ident.nvim particularly but this peculiar case appeared.

I have seen this as of now with only help text in neovim
May be something to do with source text not following proper indentation.

Its happening both on stable and default branch

https://user-images.githubusercontent.com/11389059/195303131-d32467da-8cff-4729-8534-f52cd7e1ccec.mov

**Comment by echasnovski** [comment]
Thanks for the issue!
It is a combination of #125 and neovim/tree-sitter-vimdoc#23. It doesn't cover any *real* underlying text (execute `:set filetype=text` to see it).

This is a temporary problem with tree-sitter help highlighting which default in 0.8.

**Comment by sultanahamer** [comment]
Thanks for the very quick response. Setting file type to text worked.

**Comment by echasnovski** [comment]
> Thanks for the very quick response. Setting file type to text worked.

That Neovim/tree-sitter issue is marked as resolved, so this should be unnecessary soon (if not already).

**Comment by sultanahamer** [comment]
if this is specific treesitter issue then running TSUpdate should fix it?

**Comment by echasnovski** [comment]
> if this is specific treesitter issue then running TSUpdate should fix it?

I am not sure yet. That particular issue seemed to depend on at least 'nvim-treesitter'.
I'll get back to you if/when I am able to fix this on my setup.

**Comment by sultanahamer** [comment]
Thanks. Have a good day

**Comment by echasnovski** [comment]
> if this is specific treesitter issue then running TSUpdate should fix it?

So updating 'nvim-treesitter' plugin and then running `:TSUpdate` did improve whitespace situation, but not completely. For now, I personally will disable tree-sitter highlighting in 'help' files via using `highlight = { enable = true, disable = { 'help' } }` in `require('nvim-treesitter.configs').setup()` call.
