### ISSUE TITLE
Add some API to get the output of any command in mini.git

### ISSUE THREAD

**Issue by fpohtmeh** [echasnovski/mini.nvim#1410]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.git

### Description

As a user, I would like to be able to process the output of any command. Currently, some commands are displayed in the split (MiniGitCommandSplit), while others are displayed as notifications.

**My use case**
- I would like to display the list of branches in the buffer
- Having this, I can set some nice mappings for this buffer to perform different operations with the branches (log, delete, etc.)
Notification is useless for me in this context.

Please add some API to set callbacks for any command.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> * I would like to display the list of branches in the buffer
> 
> * Having this, I can set some nice mappings for this buffer to perform different operations with the branches (log, delete, etc.)
>   Notification is useless for me in this context.

Forcing output appear in a split can be done [by explicitly using dedicated command modifiers](https://github.com/echasnovski/mini.nvim/blob/7ebfab26d77a4b9b05aaae565907e7fa4b2ee154/doc/mini-git.txt#L151-L153). For example: `:horizontal Git branch -a` or `:vertical Git branch -a`.

Which command is shown with `vim.notify()` and which in a split is [decided automatically based on information `git` itself provides](https://github.com/echasnovski/mini.nvim/blob/7ebfab26d77a4b9b05aaae565907e7fa4b2ee154/doc/mini-git.txt#L144-L149).

------

As per the title ("Add some API to get the output of any command in mini.git"). The main point of 'mini.git' `:Git` command is for interactive usage. For any scripting/automation I'd recommend using Git CLI directly (with something like `vim.system`).

Closing as not planned.
