### ISSUE TITLE
mini.clue: Add clues for built-in diff operations

### ISSUE THREAD

**Issue by star-szr** [echasnovski/mini.nvim#1411]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Hello!

I always forget the keys for diff operations, specifically <kbd>do</kbd> and <kbd>dp</kbd>.

Would you consider adding these to mini.clue as `MiniClue.gen_clues.diff()` or similar? I can work on a PR if that's helpful. If it doesn't make sense to include, all good, I can just include in my personal config.

Thanks for your time.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think it makes more sense to leave it to the users to define these clues. The main reason for this is that they need `d` trigger enabled, but it would conflict with `d` operator.

On first glance (if my memory serves me right) this might be even impossible to properly set up with 'mini.clue'. If you manage to make it work, please leave a comment with you setup.

Closing as not planned.
