### ISSUE TITLE
Mini.pick preview not working properly when quickfix list is populated with MiniDiff.export

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1416]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick, mini.diff

### Description

Hi echasnovski! I just found out this exported function which populates quickfix list with diff patch entries for easy navigation. So, when using this, for better preview, I use mini.pick to navigate through quickfix entries with preview enabled. But the issue is that the preview does not get updated when the quickfix list is populated using `vim.fn.setqflist(MiniDiff.export('qf'))` and stays on the same file.

### Neovim version

NVIM v0.11.0-dev-1388+g39781be14b

### Steps to reproduce

1. Have mini.pick and mini.diff setup in your configuration.
2. Go to a git repo with lot of file changes which are in unstaged mode so that there are many files present in quickfix list.
3. Open quickfix list entries with mini.pick quickfix picker go to preview and traverse through different entries. You can see that preview does not work properly and is not updated according to the line.

### Expected behavior

It should update according to line.

### Actual behavior

It is not updating according to line.

**Comment by echasnovski** [comment]
Thanks for the issue!

I indeed can reproduce. No obvious reason from quick glance, I'll take a look later.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`. Together with added text ("Add", "Change", "Delete") set for quickfix entries for 'mini.diff' hunks.

The issue proved to be that `MiniDiff.export()` did not set `col` and `end_col` for entries which propagated into `col=0` and `end_col=nil` for 'mini.pick' items. Having `col=0` refused to update preview (this issue), while `end_col=nil` didn't show range highlighting. Both of them should now be present resulting in `:Pick list scope='quickfix'` preview working better.
