### ISSUE TITLE
Add highlight for visualized text

### ISSUE THREAD

**Issue by zeitchef** [echasnovski/mini.nvim#142]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.map

### Description

Currently, it seems there are only three highlights available: `MiniMapSymbolLine`, `MiniMapSymbolView` and `MiniMapSymbolCount` - none of which adjust the highlight of the visualized text in the map. Could we get a way to adjust this?

**Comment by echasnovski** [comment]
> ... none of which adjust the highlight of the visualized text in the map ...

Could you, please, elaborate on this? Do you mean customize how builtin search, diagnostic, and git is highlighted? Or how whole encoded lines are highlighted?

**Comment by zeitchef** [comment]
I assume I mean how the lines are highlighted - though I'm not extremely familiar with your implementation. Basically, I want to adjust the highlight for the light gray boxes (see image) representing the text in the file. Hope that makes sense :)

<img width="119" alt="Screen Shot 2022-10-13 at 14 26 40" src="https://user-images.githubusercontent.com/6670659/195596167-5929522f-f15c-498d-b305-68cd53f18ca3.png">

**Comment by echasnovski** [comment]
Should be possible with `MiniMapNormal` highlight group on latest `main`.

Just curious, what changes do you plan to make to basic highlighting?

**Comment by zeitchef** [comment]
Hey, thanks so much - works great! I just wanted something with less contrast:

<img width="1705" alt="Screen Shot 2022-10-13 at 17 09 57" src="https://user-images.githubusercontent.com/6670659/195635766-0f8588ea-7b4c-42a6-92f3-d4aa8f9dc9b7.png">

**Comment by echasnovski** [comment]
> with less contrast:

Thought so. I also wanted that for defaults, but couldn't find anything more appropriate in builtin groups. Thanks!
