### ISSUE TITLE
differentiating builtin aliases through custom surroundings

### ISSUE THREAD

**Issue by nurira** [echasnovski/mini.nvim#1420]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Hi,

Is there a way to override the builtin aliases for inputs like this?
`srbB` => replace nearest `()` with `{}` ?

Thank you!

**Comment by echasnovski** [comment]
Or course:

```lua
require('mini.surround').setup({
  custom_surroundings = {
    b = { input = { '%b()', '^.().*().$' }, output = { left = '(', right = ')' } },
    B = { input = { '%b{}', '^.().*().$' }, output = { left = '{', right = '}' } },
  },
})
```

However, this is also possible with `sr)}` which is pretty similar from ergonomic point of view. The [built-in `b` surrounding](https://github.com/echasnovski/mini.nvim/blob/4228f166ee9db3e910eea1915e2d3683028add47/doc/mini-surround.txt#L175-L176) is pretty useful by itself.
