### ISSUE TITLE
A better alternative to matchit.vim plugin.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#1425]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.matchit

### Description

Hi echasnovski! Is it worth adding something like [matchit](https://github.com/chrisbra/matchit) to mini.nvim suite.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

'matchit' itself is already part of Neovim, so it is not an "urgent" task. Also, I've heard talks about some day replacing it in Neovim itself with Lua alternative (that probably will respect or completely depend on tree-sitter).

So I think it is safe to close this, as I hope this will be part of core before the whole new modules queue runs out of ideas.

**Comment by 231tr0n** [comment]
> Thanks for the suggestion!
> 
> 'matchit' itself is already part of Neovim, so it is not an "urgent" task. Also, I've heard talks about some day replacing it in Neovim itself with Lua alternative (that probably will respect or completely depend on tree-sitter).
> 
> So I think it is safe to close this, as I hope this will be part of core before the whole new modules queue runs out of ideas.

I apologize for raising this issue. I did not know there were plans to rewrite match paren in lua. That was my main intention behind raising this issue since i taught this could be a good addition to mini.nvim.

**Comment by echasnovski** [comment]
No worries. I don't remember seeing something public about this. It is more like "strong aspirations", but without some traction yet. Maybe it will go the 'mini.comment' route (create in 'mini.nvim' and then port smaller version to core), but there are no immediate and not-so-immediate plans about creating it.
