### ISSUE TITLE
Add support to open a file in vertical/horizontal split in mini.files

### ISSUE THREAD

**Issue by mozbz** [echasnovski/mini.nvim#1432]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-files

### Description

The go_in function in mini.files replaces the buffer in the most recent window now. Can an option to open the file in horizontal/vertical split of the most recent window also be added? The key-bindings 'S' and 'V' can be set by default for this. This will simplify opening files side by side.
Also this can be done by a custom config using existing apis, but I think it would be good to have this builtin by default.

**Comment by echasnovski** [comment]
This was already suggested in #943, #760, and #646. Following [example for making a mapping that creates a split](https://github.com/echasnovski/mini.nvim/blob/c78332b4c71ad3c2a09efe6acd0a51283627258f/doc/mini-files.txt#L473-L503) is the suggest approach here. Note, that examples only create a split and changes target window to be that split. Follow with actually opening a file the usual way (`l` or `L` by default).
