### ISSUE TITLE
[mini.diff] signs misaligned

### ISSUE THREAD

**Issue by epheien** [echasnovski/mini.nvim#1433]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.diff

### Description

Signs misaligned with this config
```lua
require('mini.diff').setup({
  view = {
    style = 'sign',
    signs = { add = '┃', change = '┃', delete = '_' },
  },
```

### Neovim version

0.10.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `nvim {somefile}` in a git repo
3. `ggO<CR>`

### Expected behavior

signs aligned

### Actual behavior

signs misaligned

<img width="530" alt="Xnip2024-12-27_12-01-22" src="https://github.com/user-attachments/assets/ea10f634-e5ef-46ec-97a4-9980b04106d5" />

**Comment by epheien** [comment]
Temporary workaround:
```lua
H.set_extmark = function(buffer, ns_id, line, col, opts)
  if line == 0 then
    local li = vim.api.nvim_buf_get_extmarks(buffer, ns_id, { line, col }, { line, col }, {})
    if #li > 0 then
      vim.api.nvim_buf_del_extmark(buffer, ns_id, li[1][1])
    end
  end
  pcall(vim.api.nvim_buf_set_extmark, buffer, ns_id, line, col, opts)
end
```

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce. First, the reproduction steps most certainly need some custom value of 'signcolumn'. For example, `vim.o.signcolumn = 'yes:2'`. But even with that I can not reproduce.

Would you mind narrowing down reproduction steps to minimal setup. Ideally, if it uses only 'mini.diff' as a source of signs and only necessary options set. For example, [with these lines as starting point](https://github.com/echasnovski/mini.nvim/blob/c78332b4c71ad3c2a09efe6acd0a51283627258f/scripts/init-deps-example.lua#L1-L17)?

If this happens only on the first line, I have an idea of why this happens, but I can not reliably fix it without reproducing it and writing test for it.

**Comment by epheien** [comment]
> Thanks for the issue!
> 
> Unfortunately, I can not reproduce. First, the reproduction steps most certainly need some custom value of 'signcolumn'. For example, `vim.o.signcolumn = 'yes:2'`. But even with that I can not reproduce.
> 
> Would you mind narrowing down reproduction steps to minimal setup. Ideally, if it uses only 'mini.diff' as a source of signs and only necessary options set. For example, [with these lines as starting point](https://github.com/echasnovski/mini.nvim/blob/c78332b4c71ad3c2a09efe6acd0a51283627258f/scripts/init-deps-example.lua#L1-L17)?
> 
> If this happens only on the first line, I have an idea of why this happens, but I can not reliably fix it without reproducing it and writing test for it.

Sorry, after testing, `vim.o.signcolumn = 'auto:9'` is the key.

This is my minimal setup.
```lua
vim.o.signcolumn = 'auto:2'
vim.opt.runtimepath:append{'/Users/eph/.config/nvim/pckr/opt/mini.diff'}
require('mini.diff').setup({
  view = {
    style = 'sign',
    signs = { add = '┃', change = '┃', delete = '_' },
  },
})
```

**Comment by echasnovski** [comment]
> Sorry, after my testing, `vim.o.signcolumn = 'auto:9'` is the key.
> 
> This is my minimal setup.

Thanks for the follow up! I can reproduce this interactively, but not in test. The issue is indeed what I thought it is (basically, 690a3b4c78c4956f7ecf770124b522d32084b872). Will take a look.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.

The reason I was not able to reproduce it earlier is because I tested on Nightly (0.11) with `signcolumn=yes:2` which has order correct and correctly shows space for 2 signs (i.e. 4 cells). Testing with 0.10.3 indeed showed different order, while testing with `signcolumn=auto:2` showed the real issue of wider sign column than it should be.
