### ISSUE TITLE
Add configuration to exclude filetypes

### ISSUE THREAD

**Issue by zeitchef** [echasnovski/mini.nvim#144]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

`indent-blankline` lets me set a `filetype_exclude` list which is super handy, as I prefer not to have indentation markers in `neo-tree`, for example. Thanks for your consideration!

**Comment by echasnovski** [comment]
Disabling *all* modules is done in a similar fashion: set corresponding global or local variable `mini***_disable` to `true` ([here](https://github.com/echasnovski/mini.nvim/blob/89c77d220f546782f1da12fe451c6a56c479ffd4/doc/mini-indentscope.txt#L58-L64) is documentation for 'mini.indentscope'). To do this automatically, create autocommand that suits your need. [Here](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini.txt#L174) are approaches for some common tasks.

So in your case, adding something like this (or similar Lua API alternative) in your Neovim config should do the trick:
```lua
vim.cmd('au FileType neo-tree lua vim.b.miniindentscope_disable = true')
```

**Comment by FrancescoLuzzi** [comment]
If someone wants a different approach (maybe more modular):
```lua
    local disabled_filetypes = { 'NvimTree', 'alpha', 'help' }
    vim.api.nvim_create_autocmd('FileType', {
      group = vim.api.nvim_create_augroup('MiniIndentScopeDisable', { clear = true }),
      callback = function(opts)
        local ftype = vim.bo[opts.buf].filetype
        if vim.tbl_contains(disabled_filetypes, ftype) then
          vim.b.miniindentscope_disable = true
        end
      end,
    })
```

**Comment by echasnovski** [comment]
> If someone wants a different approach (maybe more modular):

Yeah, something like that is the suggested approach indeed. I'd slightly refactor it:

```lua
local disabled_filetypes = { NvimTree = true, alpha = true, help = true }
local disable_in_ft = function(opts)
  local ft = vim.bo[opts.buf].filetype
  if disabled_filetypes[ft] then vim.b[opts.buf].miniindentscope_disable = true end
end
local augroup = vim.api.nvim_create_augroup('MiniIndentScopeDisable', { clear = true })
vim.api.nvim_create_autocmd('FileType', { group = augroup, callback = disable_in_ft })
```
