### ISSUE TITLE
mini.cursorword conflicts with highlight on yank

### ISSUE THREAD

**Issue by eldar** [echasnovski/mini.nvim#1440]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.cursorword

### Description

Hi! This one is an edge case I suppose. I use mini.cursorword to highlight current word under cursor, and recently I enabled highlight on yank. It seems that after yank both highlight mechanisms act on the word under cursor, which is most often yanked. This is not ideal and creates confusion.

### Neovim version

0.10.2

### Steps to reproduce

I enable highlight on yank like so:
```lua
vim.api.nvim_create_autocmd('TextYankPost', {
  callback = function()
    vim.highlight.on_yank({
      -- on_visual = false,
      timeout = 750,
    })
  end,
  group = vim.api.nvim_create_augroup('YankHighlight', { clear = true }),
  pattern = '*',
})
```

I load mini.cursorword with Lazy plugin manager like so:
```lazy
  {
    'echasnovski/mini.cursorword',
    enabled = true,
    version = '*',
    opts = {
      -- Delay (in ms) between when cursor moved and when highlighting appeared
      delay = 250, -- same as updatetime
    }
  },
```

### Expected behavior

The entire yanked text should be highlighted uniformly until the timeout, without mini.cursorword interfering. Afterwards, the highlight of the word under cursor can be restored.

### Actual behavior

As you can see on the attached screencast, when yanking an entire line, the word under cursor is highlighted differently.
[highlight_on_yank.webm](https://github.com/user-attachments/assets/de796cab-61df-499b-b6b1-d642021ca045)

**Comment by echasnovski** [comment]
Thanks for the issue!

> The entire yanked text should be highlighted uniformly until the timeout, without mini.cursorword interfering. Afterwards, the highlight of the word under cursor can be restored.

I don't this is a reasonable expectation for 'mini.cursorword' to have out of the box. There is really no good way of doing that for any scenario like this. You have several options:
- Use different highlighting by adjusting [module's highlight groups](https://github.com/echasnovski/mini.nvim/blob/733afb94ed88d32b839a644dc137604691e46032/doc/mini-cursorword.txt#L35-L45). They are underline by default which works better with this use case. 'sainnhe/everforest' redefines it to use background, so you'd have to adjust highlight groups *after* sourcing it.
- Manually temporarily disable 'mini.cursorword' and then re-enable it later. With something like this inside autocommand callback:
    ```lua
    vim.b.minicursorword_disable = true
    vim.highlight.on_yank({ timeout = 750 })
    vim.defer_fn(function()
      vim.b.minicursorword_disable = nil
      -- Trigger 'mini.cursorword' re-render after yank highlight is hidden
      vim.cmd('doautocmd CursorMoved')
    end, 760)
    ```

Closing as working as expected.
