### ISSUE TITLE
Mini.Files - Is doc example for buffer splits incorrect?

### ISSUE THREAD

**Issue by Or1g3n** [echasnovski/mini.nvim#1441]
# Issue
I may be mis-interpreting what this example function is supposed to do. I thought this was supposed to open the selected file from the explorer buffer as a split (vert of horizontal). However, in practice all this appears to do is duplicate the existing active buffer.

I have modified the code as such to get the intended result of opening the selected file as a split:
```lua
	-- Open buffers in split
	local map_split = function(buf_id, lhs, direction)
	    local rhs = function()
		-- Make new window and set it as target
		local cur_target = MiniFiles.get_explorer_state().target_window
		local new_target = vim.api.nvim_win_call(cur_target, function()
		    vim.cmd(direction .. ' split')
		    return vim.api.nvim_get_current_win()
		end)

		MiniFiles.set_target_window(new_target)
-----------MY ADDITION START
		-- Get the file path of the selected item
		local file_path = MiniFiles.get_fs_entry().path

		-- Open the file in the new split if a file is selected
		if file_path then
		    vim.api.nvim_win_set_buf(new_target, vim.fn.bufadd(file_path))
		else
		    vim.notify("No file selected", vim.log.levels.WARN)
		end
----------MY ADDITION END
	    end

	    -- Adding `desc` will result into `show_help` entries
	    local desc = 'Split ' .. direction
	    vim.keymap.set('n', lhs, rhs, { buffer = buf_id, desc = desc })
	end

	vim.api.nvim_create_autocmd('User', {
	    pattern = 'MiniFilesBufferCreate',
	    callback = function(args)
		local buf_id = args.data.buf_id
		-- Tweak keys to your liking
		map_split(buf_id, '<C-s>', 'belowright horizontal')
		map_split(buf_id, '<C-v>', 'belowright vertical')
	    end,
	})
```

# Doc Reference
https://github.com/echasnovski/mini.nvim/blob/733afb94ed88d32b839a644dc137604691e46032/lua/mini/files.lua#L468C1-L497C9

**Comment by echasnovski** [comment]
It works *exactly* as the title says: ["Create mappings to **modify target window via split**"](https://github.com/echasnovski/mini.nvim/blob/733afb94ed88d32b839a644dc137604691e46032/lua/mini/files.lua#L468). This means that it creates the split expecting user to follow up with either `l` ("go in") or `L` ("go in and close the explorer").

If you want to automatically go in, replace all the custom code with appropriate usage of [`go_in()`](https://github.com/echasnovski/mini.nvim/blob/733afb94ed88d32b839a644dc137604691e46032/doc/mini-files.txt#L770).

**Comment by Or1g3n** [comment]
Thanks,  that makes good sense now! Using the go_in() function was much simpler.

**Comment by echasnovski** [comment]
I hope [this should be clearer now](https://github.com/echasnovski/mini.nvim/blob/9df78f3cdf9bdcc5aaf93cc51412a69a384041b2/doc/mini-files.txt#L488-L490).

**Comment by Or1g3n** [comment]
Thank @echasnovski, yes, I believe this comment would have mitigated my initial confusion. I am coming from opening splits via nvim-tree and telescope which opens the split and sets the buffer automatically which is why I assumed this functionality in mini.files. It makes sense why you would not do this by default given mini.files go_in_plus action. Appreciate your time.
