### ISSUE TITLE
Use jump spot's first character as hint

### ISSUE THREAD

**Issue by pengux** [echasnovski/mini.nvim#145]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

jump2d

### Description

Similar to hop's `hint_char1` function, let the user type in the first character of the spot that the user wants to jump to. This usually decrease the number of keystrokes required for the jump and allow the user to jump to any position in the buffer as long as he/she can type the character at that position.

![image](https://user-images.githubusercontent.com/2286687/196723115-adfb9bfc-56bc-4742-bf5d-5537941250af.png)

**Comment by echasnovski** [comment]
Did you try `MiniJump2d.builtin_opts.single_character`? Like this:
`:lua MiniJump2d.start(MiniJump2d.builtin_opts.single_character)`.

Is it what you describe here?

**Comment by pengux** [comment]
Yes, thank you! That is what I was looking for. For anybody looking for the same thing:

```
local mini_jump2d = require('mini.jump2d')
mini_jump2d.setup({
  mappings = {
    start_jumping = '',
  },
})
vim.keymap.set({ "n", "v" }, "<cr>",
  function() return mini_jump2d.start(mini_jump2d.builtin_opts.single_character) end, keymap_opts)
```

**Comment by echasnovski** [comment]
Yep, it is intended to be used this way.
