### ISSUE TITLE
Question: Backtick support with mini-pairs

### ISSUE THREAD

**Issue by vihu** [echasnovski/mini.nvim#148]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-pairs

### Description

Hi, firstly thank you for your excellent plugin suite!

I was wondering how to configure the following two scenarios with mini-pairs:

1. Single backtick should place the cursor in the middle and close with a single pairing backtick. (Example: writing a single line code block in markdown)
2. Triple backticks should place the cursor after the third backtick and close with triple pairing backticks (Example:  writing multi-line code blocks in a markdown file).

Any suggestions?

**Comment by echasnovski** [comment]
>     1. Single backtick should place the cursor in the middle and close with a single pairing backtick. (Example: writing a single line code block in markdown)

If I understand you correctly, it is already a default behavior: typing `` ` `` in empty line will lead to `` `|` `` (`|` meaning cursor).

>     2. Triple backticks should place the cursor after the third backtick and close with triple pairing backticks (Example:  writing multi-line code blocks in a markdown file).

`mini.pairs` is designed to work only with single previous and single next characters. This was done to make functionality as fast as possible. Working with a greater number of previous/next symbols should be done with snippets, in my opinion.

Does it answer you question?

**Comment by vihu** [comment]
Yup, that answers it. Thanks @echasnovski
