### ISSUE TITLE
]f ]F [f [F with mini.ai?

### ISSUE THREAD

**Issue by folke** [echasnovski/mini.nvim#149]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

Hi!

Firts of all, I love what you're doing with mini.

I'm just starting to convert my `nvim-treesitter-textobjects` config to use `mini.ai`.

The `custom_textobjects` work great, but I'm a bit stuck on implementing the `move` comands.

Secifically, the ones below:

```lua
      move = {
        enable = false,
        set_jumps = true, -- whether to set jumps in the jumplist
        goto_next_start = { ["]f"] = "@function.outer", ["]c"] = "@class.outer" },
        goto_next_end = { ["]F"] = "@function.outer", ["]C"] = "@class.outer" },
        goto_previous_start = { ["[f"] = "@function.outer", ["[c"] = "@class.outer" },
        goto_previous_end = { ["[F"] = "@function.outer", ["[C"] = "@class.outer" },
      },
```

- `g[f` moves to the next function end, but how do I change it to go to the next function start instead?

I'm probably missing something obvious here :)

**Comment by echasnovski** [comment]
Thanks, Folke! That's a high praise coming from you :)

To be honest, moving cursor was mostly a tangential extra feature that required a relatively small addition to a codebase. So it is far from perfect and can't be a full replacement of 'nvim-treesitter-textobjects'.

The way default `g[`/`g]` work is essentially this: find corresponding whole `a` textobject using search direction from config and then move to its left/right edge. There is a slight difference when cursor is already on the edge of correct textobject: then it will find next one (with `count` bigger by one).

So `g[f` should find `af` textobject and move to its left edge. I am not sure why it is moving to function end instead. If it is indeed the case, I would be curious to see the config and text.

**Comment by folke** [comment]
Sorry, I meant `g]f` instead.

I'll stick for that functionality to treesitter objects for now :)

Thanks!

**Comment by echasnovski** [comment]
Although, if you don't mind some custom mapping code and lack of dot-repeat support in Operator-pending mode, you can make custom mappings with `MiniAi.move_cursor()`. Like this:

```lua
local mini_ai = require('mini.ai')
mini_ai.setup({
  custom_textobjects = {
    F = mini_ai.gen_spec.treesitter({ a = '@function.outer', i = '@function.inner' }),
  },
})

local map_previous = function(lhs, side, textobj_id)
  for _, mode in ipairs({ 'n', 'x', 'o' }) do
    vim.keymap.set(mode, lhs, function() MiniAi.move_cursor(side, 'a', textobj_id, { search_method = 'prev' }) end)
  end
end

local map_next = function(lhs, side, textobj_id)
  for _, mode in ipairs({ 'n', 'x', 'o' }) do
    vim.keymap.set(mode, lhs, function() MiniAi.move_cursor(side, 'a', textobj_id, { search_method = 'next' }) end)
  end
end

map_previous('[f', 'left', 'F')
map_previous('[F', 'right', 'F')
map_next(']f', 'left', 'F')
map_next(']F', 'right', 'F')
```

**Comment by folke** [comment]
That's exactly what I was looking for. Great!!
