### ISSUE TITLE
Beta-testing 'mini.jump'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#15]
Please leave your feedback about new 'mini.jump' module here. Feel free to either add new comment or positively upvote existing one.

Some things that I am interested to find out (besides seemingly omnipresent bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation clear enough?

**Comment by drowning-cat** [comment]
1. There is no keymap for the comma: `repeat_jump_back = ','` (discussed in [PR#1077](https://github.com/nvim-mini/mini.nvim/issues/1077)).
2. It doesn't support forced linewise mode: `dVf(`.
3. And a few tips to share:

    3.1. Simple `;` and `,`:

    ```lua
    MiniJump.setup({
      mappings = {
        repeat_jump = "",
      },
    })

   local jump_direction = false
    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniJumpStart",
      group = vim.api.nvim_create_augroup("minijump_save_dir", { clear = true }),
      callback = function()
        jump_direction = MiniJump.state.backward
      end,
    })
    vim.keymap.set({ "n", "x", "o" }, ";", function()
      MiniJump.jump(nil, jump_direction, nil, vim.v.count1)
    end)
    vim.keymap.set({ "n", "x", "o" }, ",", function()
      MiniJump.jump(nil, not jump_direction, nil, vim.v.count1)
    end)
    ```

    3.2. Keep `<Esc>` key unbound so other plugins can handle it:
    
    ```lua
    local esc_key = vim.keycode("<Esc>")
    vim.on_key(function(_, key)
      if MiniJump.state.jumping and key == esc_key then
        MiniJump.stop_jumping()
      end
    end, vim.api.nvim_create_namespace("mini_jump_esc"))
    ```
  
    3.3. Stop `MiniJump` mode after motion operator mode keymaps like `dt`, `df`, etc.
  
    ```lua
    vim.api.nvim_create_autocmd("ModeChanged", {
      pattern = "no*:*",
      desc = "Stop `MiniJump` mode after operator-pending mode keymaps",
      callback = function()
        if MiniJump.state.jumping then
          MiniJump.stop_jumping()
        end
      end,
    })
    ```

P.S. It was so lonely here that I decided to share something in this discussion.

**Comment by echasnovski** [comment]
> 1. There is no keymap for the comma: `repeat_jump_back = ','` (discussed in [PR#1077](https://github.com/nvim-mini/mini.nvim/issues/1077)).

A more relevant discussion is #282.

> 2\. It doesn't support forced linewise mode: `dVf(`.

That was not on the radar when the module was created. Should be pretty straightforward to add, I think.

---

Also, please, don't revive 4.5 year old issue for this. A more proper place would be a new discussion in 'Discussions'.
