### ISSUE TITLE
Support `nvim-web-devicons` colors

### ISSUE THREAD

**Issue by bangedorrunt** [echasnovski/mini.nvim#153]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

Following #152,

At the moment, `mini.tabline` doesn't support colored icons. It's good to have an option for that, such as `{colored_devicons = true}` by default. 

Since it's only for customization, not really important, so please consider this feature when you got free time. 

Many thanks!

**Comment by echasnovski** [comment]
Thanks for creating an issue!

I think this should be simultaneously implemented in both 'mini.tabline' and 'mini.statusline'.

I'll see when I get to it.

**Comment by echasnovski** [comment]
So I finally got to trying to implement this. After experimenting a bit, there seems to be these quite large obstacles:

- In 'mini.statusline' highlighting and section text is strictly separated. Highlighting is a property of a group (see [`iniStatusline.combine_groups()`](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-statusline.txt#L157)), not a section. So implementation of colored file icons would mean to either extract them into separate groups or update `combine_groups()` behavior. Either one is a severe breaking change, which is not good.

- In 'mini.tabline' things are even more sad. General idea behind how tabline and statusline (and statuscolumn in Neovim nightly) work is by constructing a special string which gets interpreted by special rules (see `:h statusline`). Under those rules highlighting of text is treated similarly to how it is done in terminal: any `%#xxx#` string "activates" `xxx` highlight group for any text to the right. This means that directly trying to apply highlight groups from 'nvim-web-devicons' will lead to them not having correct background, as they only define foreground.

    The seemingly only way to overcome this is involves black magic of patching icons highlight groups like [bufferline.nvim](https://github.com/akinsho/bufferline.nvim/blob/cbb798dd2db7841550cd2c6c6dde12dfda055928/lua/bufferline/highlights.lua#L148-L195) does. This is certainly too complicated to be in 'mini.tabline'.

    By the way, this issue also concerns 'mini.statusline' as well.

So overall, I am afraid I have to decline this feature. I genuinely is open to adding this to 'mini.tabline' only if there is a way to make icons respect background without too much of a hassle.

Thanks again for suggestion!

**Comment by Iron-E** [comment]
Apologies for the necro; I saw in Neovim 0.12, there was a pertinent addition:

> $ - Same as #, except the `%$HLname$` group will inherit from preceding highlight attributes.

Would that make this more feasible to implement? 

(There could still be edge cases where a user has set a background for one of these icons explicitly, though I'm not sure how likely that is.)

**Comment by echasnovski** [comment]
> > $ - Same as #, except the `%$HLname$` group will inherit from preceding highlight attributes.
> 
> Would that make this more feasible to implement?

Yeah, I've seen this and have a todo item to make a deeper dive into this. However:
- There were still issues beyond that in 'mini.tabline'.
- At this point I think it is more of a stylistic "minimalism" choice for 'mini.statusline' and 'mini.tabline' to not show colored icons.

So no promises beyond "I'll take one more look".
