### ISSUE TITLE
miniai - improper tag selection

### ISSUE THREAD

**Issue by jemag** [echasnovski/mini.nvim#156]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Mini.ai seems to improperly select tags in nested situations

### Neovim version

NVIM v0.9.0-dev-220+g234b8c5f3

### Steps to reproduce

minimal_init.lua:
```lua
local on_windows = vim.loop.os_uname().version:match("Windows")
-- vim.api.nvim_command("!rm -rf /tmp/nvim")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  vim.cmd([[ syntax off]])
  vim.g.ts_highlight_lua = true
  require("packer").init({
    package_root = package_root,
    compile_path = compile_path,
  })
  require("packer").startup({
    function(use)
      use({ "wbthomason/packer.nvim" })
      use({ "nvim-treesitter/nvim-treesitter" })
      use({
        "echasnovski/mini.ai",
      })
    end,
  })
end

_G.load_config = function()
  require("mini.ai").setup({
    -- Table with textobject id as fields, textobject specification as values.
    -- Also use this to disable builtin textobjects. See |MiniAi.config|.
    custom_textobjects = {
      f = false,
      b = false,
    },

    -- Module mappings. Use `''` (empty string) to disable one.
    mappings = {
      -- Main textobject prefixes
      around = "a",
      inside = "i",

      -- Next/last variants
      around_next = "an",
      inside_next = "in",
      around_last = "al",
      inside_last = "il",

      -- Move cursor to corresponding edge of `a` textobject
      goto_left = "g[",
      goto_right = "g]",
    },

    -- Number of lines within which textobject is searched
    n_lines = 50,

    -- How to search for object (first inside current line, then inside
    -- neighborhood). One of 'cover', 'cover_or_next', 'cover_or_prev',
    -- 'cover_or_nearest', 'next', 'previous', 'nearest'.
    search_method = "cover_or_next",
  })
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
else
  load_plugins()
  require("packer").sync()
  _G.load_config()
end
```
test.html:
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Neptune</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favneptune.png">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&amp;display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet">
  <link rel="manifest" href="manifest.webmanifest">
  <meta name="theme-color" content="#1976d2">
</head>
<body>
  <app-root>
    <div style="background: #1b2b40; width: 100%; height: 100%"  >
      <div style="background: black; opacity: 1; color: white; position: absolute; top: 30%; left: 40%; padding: 20px" >
        <div style="font-size: 64px;" >Neptune</div>
        <br>
        <div>Loading... | Chargement...</div>
      </div>
    </div>
  </app-root>
  <app-redirect></app-redirect>
  <noscript>Please enable JavaScript to continue using this application.</noscript>
</body>
</html>
```
1. Open html file using: `nvim -u minimal_init.lua test.html`
2. Place your cursor on the `<br>` like so:
![image](https://user-images.githubusercontent.com/7985687/200668213-592ee8f3-1319-4200-9a51-78b0e048bfae.png)
3. Press `vit`
4. Notice how it selects the improper tag

### Expected behavior

Selects
![image](https://user-images.githubusercontent.com/7985687/200668908-9c32829c-19bd-49f5-b8b5-a361eb3ce9de.png)
 
(This works out of the box in neovim with nvim --clean)

### Actual behavior

Selects
![image](https://user-images.githubusercontent.com/7985687/200668433-f292189d-955e-4fac-ab4a-96d526d7c8bf.png)

**Comment by echasnovski** [comment]
Thanks for the issue!

All builtin textobject search is done with Lua patterns and certain false positives are to be expected (as [stated in docs](https://github.com/echasnovski/mini.nvim/blob/07ad48937204446ba350837a3413a5d19de22c36/doc/mini-ai.txt#L37-L38)).

Tags suffer the most from this. And nested tags is the most visible example. I couldn't find a reasonably not complicated approach to update [current Lua patterns](https://github.com/echasnovski/mini.nvim/blob/07ad48937204446ba350837a3413a5d19de22c36/lua/mini/ai.lua#L1094) to work in nested tags situation.

The main reason for the lack of trying to solve this is that I believe using some tree-sitter base approach is more appropriate here. The `tag` builtin was mostly added for completeness (with builtin textobject, 'targets.vim', and 'mini.surround') and expected to work in most basic situations.

#110 is relevant here.
