### ISSUE TITLE
Mini.completion as more of a tab complete

### ISSUE THREAD

**Issue by GNOMES** [echasnovski/mini.nvim#157]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

completion

### Description

I have been really enjoying using mini.completion, and have enjoyed that it is only sourcing suggestions from text previously written.

Apologies if this is already possible with the config. 

A nice improvement would be to auto use the first suggestion after pressing tab.

**Comment by echasnovski** [comment]
I am not entirely sure what you mean here.

There are [suggested mappings for `<Tab>` and `<S-Tab>` in help file](https://github.com/echasnovski/mini.nvim/blob/07ad48937204446ba350837a3413a5d19de22c36/doc/mini-completion.txt#L96-L97). With them and default `config.set_vim_settings` (which sets `completeopt` option), you can press `<Tab>` while popup suggestions are visible which will lead to first suggestion placed in text. After that, you can continue typing text as usual. This is how I use it.

If you also want for dismiss popup after `<Tab>`, try this mapping (adds `<C-y>` in case of visible popup):
```lua
vim.api.nvim_set_keymap('i', '<Tab>', [[pumvisible() ? "\<C-n>\<C-y>" : "\<Tab>"]], { noremap = true, expr = true })
```

... or a more modern approach:
```lua
vim.keymap.set('i', '<Tab>', [[pumvisible() ? "\<C-n>\<C-y>" : "\<Tab>"]], { expr = true })
```

Does this solve your issue?
