### ISSUE TITLE
Spacing around parentheses/brackets

### ISSUE THREAD

**Issue by majjoha** [echasnovski/mini.nvim#16]
Thank you for a great plugin! I am amazed by how you have managed to cover so much functionality while still making it feel lightweight.

In surround.vim, if I have the cursor on the word "hello", and I hit `ysiw)`, then it becomes "(hello)". If I had used `ysiw(`, then it would have been "( hello )" instead. The plugin uses the same pattern for other types of brackets too.
However, in mini.surround, it does not seem to make a difference whether I use `saiw(` or `saiw)`, so I am wondering if I am missing anything, or if this is not supported?

**Comment by echasnovski** [comment]
Thank you for your kind words!

It is not supported at the moment, but I plan in foreseeable future to allow custom definition of single character surroundings. So users can map themselves what is inserted and/or searched when they type `(` or `)`. This should cover your case and some others, like LaTeX operators and so on. Need to finish some other things, settle on the API and implement.

**Comment by majjoha** [comment]
Sounds great. Thank you!

**Comment by echasnovski** [comment]
@majjoha, I understand that this was a very long delay and it might be irrelevant, but this is now possible with [config.custom_surroundings](https://github.com/echasnovski/mini.nvim/blob/297993c40e93bd155d72424e3a1abeefb3be344e/doc/mini.txt#L3784) option. Your use case is (almost fully) possible with the following setup:
```lua
require('mini.surround').setup({
  custom_surroundings = {
    ['('] = { output = { left = '( ', right = ' )' } },
    ['['] = { output = { left = '[ ', right = ' ]' } },
    ['{'] = { output = { left = '{ ', right = ' }' } },
    ['<'] = { output = { left = '< ', right = ' >' } },
  },
})
```

This will add (like in `saiw(` or `sr"(`) parentheses/brackets with spaces but will find and delete (like in `sd(`) without spaces. The latter is, unfortunately, not possible under current design and, probably, won't be.

**Comment by majjoha** [comment]
I just quickly tested it, and it seems to work perfectly for my use case. Thank you for taking the time to implement it. Great job!
