### ISSUE TITLE
mini.pairs: Don't add closing pair if cursor is in front of closing character

### ISSUE THREAD

**Issue by jmbaur** [echasnovski/mini.nvim#164]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

Similar to https://github.com/windwp/nvim-autopairs#dont-add-pairs-if-it-already-has-a-close-pair-in-the-same-line. If the cursor is in front of an already existing closing character, this plugin could decide to not add the closing pair.

**Comment by echasnovski** [comment]
This is already possible to the extent which this module is designed. It intentionally can operate only based on cursor neighborhood (two characters to its left and right). It is not (and won't be) able to condition action based on anything else.

Here is the config which will insert only `(` \ `[` \ `{` if the next character is `)` \ `]` \ `}`:
```lua
require('mini.pairs').setup({
  mappings = {
    ['('] = { action = 'open', pair = '()', neigh_pattern = '[^\\][^%)]' },
    ['['] = { action = 'open', pair = '[]', neigh_pattern = '[^\\][^%]]' },
    ['{'] = { action = 'open', pair = '{}', neigh_pattern = '[^\\][^%}]' },
  }
})
```
