### ISSUE TITLE
mini.sessions: Automatically create sessions folder if it's not present.

### ISSUE THREAD

**Issue by mokafolio** [echasnovski/mini.nvim#166]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions

### Description

`mini.sessions` does not appear to automatically create the default `sessions` folder if it's not present. This will be a cool addition to automate for fresh installs as it reduces one manual step. Thanks for all your super clean plugins!

**Comment by echasnovski** [comment]
Thanks for suggestion!

This is actually a good idea. Not sure why I didn't do this in the first place. I hope to implement it in the near future.

**Comment by Ciel-MC** [comment]
Also, perhaps it can do better than instantly crash (I couldn't even see the error message) if the folder wasn't present. :sob: I had to record my screen and play it back to figure out why there's just a random error when I launch

**Comment by echasnovski** [comment]
> Also, perhaps it can do better than instantly crash (I couldn't even see the error message) if the folder wasn't present. sob I had to record my screen and play it back to figure out why there's just a random error when I launch

What do you mean by "instantly crash"? Just tried it and Neovim works just fine. If you want to look at previous messages, execute `:messages`: it will clearly state the error.

**Comment by Ciel-MC** [comment]
> > Also, perhaps it can do better than instantly crash (I couldn't even see the error message) if the folder wasn't present. sob I had to record my screen and play it back to figure out why there's just a random error when I launch
> 
> What do you mean by "instantly crash"? Just tried it and Neovim works just fine. If you want to look at previous messages, execute `:messages`: it will clearly state the error.

Huh, when the error triggered, it instantly closed neovim, as in back to the terminal, I had no chance to see the message

**Comment by echasnovski** [comment]
> Huh, when the error triggered(launched without ~/.local/share/nvim/session), it instantly closed neovim, as in back to the terminal, I had no chance to see the message

Tried it on both Neovim 0.8.3 and latest nightly release. Still no such crash. Might be an issue with how you install and load plugins. I have a feeling that you are using 'folke/lazy.nvim'.

**Comment by Ciel-MC** [comment]
> > Huh, when the error triggered(launched without ~/.local/share/nvim/session), it instantly closed neovim, as in back to the terminal, I had no chance to see the message
> 
> Tried it on both Neovim 0.8.3 and latest nightly release. Still no such crash. Might be an issue with how you install and load plugins. I have a feeling that you are using 'folke/lazy.nvim'.

Oh, lazy does that? It's weird since other errors don't tend to crash neovim entirely.

**Comment by echasnovski** [comment]
> Oh, lazy does that? It's weird since other errors don't tend to crash neovim entirely.

Might be some combination of how 'mini.sessions' throw errors and how 'lazy.nvim' handles that. Plus maybe a Neovim version.

**Comment by Ciel-MC** [comment]
> > Oh, lazy does that? It's weird since other errors don't tend to crash neovim entirely.
> 
> Might be some combination of how 'mini.sessions' throw errors and how 'lazy.nvim' handles that. Plus maybe a Neovim version.

I'm building from latest git (neovim-git AUR), if that helps

**Comment by echasnovski** [comment]
Should be implemented now in `main` branch. Thanks for the idea!

**Comment by Ciel-MC** [comment]
On the topic of the session folder, is there no quick command to save a session to the global directory? :mksession seems to drop it in the local one, are we supposed to just specify the dir ourselves? It would be helpful to at least have an API for getting the directory path.

**Comment by echasnovski** [comment]
> On the topic of the session folder, is there no quick command to save a session to the global directory? :mksession seems to drop it in the local one, are we supposed to just specify the dir ourselves? It would be helpful to at least have an API for getting the directory path.

[Here](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-sessions.txt#L135) is the documentation of `MiniSessions.write()`. It has all the information about where session is saved.
