### ISSUE TITLE
mini.starter: Only highlight first character of prefix

### ISSUE THREAD

**Issue by p00f** [echasnovski/mini.nvim#170]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

![image](https://user-images.githubusercontent.com/36493671/205380714-950737de-4673-4d1d-a616-17eff222a4f5.png)

When the same file is in the two categories, the prefix highlighting on the whole filename looks bad. Can only the first character of the prefix be highlighted since that is what needs to be typed immediately?

(This isn't so bad when I can link `MiniStarterItemPrefix` to `Normal`)

**Comment by echasnovski** [comment]
> When the same file is in the two categories, the prefix highlighting on the whole filename looks bad. Can only the first character of the prefix be highlighted since that is what needs to be typed immediately?
> 
> (This isn't so bad when I can link `MiniStarterItemPrefix` to `Normal`)

The whole idea behind prefix highlighting is to show which characters should be typed to uniquely identify item. In your case there are four pairs of items with same name leading them to be highlighted as a whole.

Having only the next character highlighted seems too superficial and adding not much value, as next character to be typed will be visible as the one to the right of highlighted query.

If you want to disable highlighting of prefix, it is better to link to `MiniStarterItem` (like `hi! link MiniStarterItemPrefix MiniStarterItem`).
