### ISSUE TITLE
mini.base16: variables (possibly) link to the wrong highlight group

### ISSUE THREAD

**Issue by raddari** [echasnovski/mini.nvim#171]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

base16

### Description

I realised whilst writing that this is more so an issue with treesitter linking the `@variable` capture to `Identifier` rather than an issue with this plugin itself, but I'd like to post it anyway so you're aware :)

The pictures and videos from module demos (for example, [`mini.doc`](/echasnovski/mini.nvim/blob/6402c79d73c07ad19374dc7b4f9d4bdfc2f57f42/readmes/mini-doc.md#demo)) indicate that variables should be linked to a yellow highlight group (such as `Normal`), but instead are linked to `Identifier` (an orange colour).

However, reading the documentation for [`mini.base16`](/echasnovski/mini.nvim/blob/6402c79d73c07ad19374dc7b4f9d4bdfc2f57f42/lua/mini/base16.lua#L235) seems to indicate that, for variables, the orange colour (`base08`) is correct.

I believe the former should be the case (see actual vs expected behaviour below), but maybe I'm wrong on this.

### Neovim version

0.8.2

### Steps to reproduce

1. Copy the following code block into `test.lua` (from the `mini.doc` demo):
```lua
local MiniDoc = {}

MiniDoc.config = {
  annotation_extractor = function(l)
    return string.find(l, '^%-%-%-(%S*) ?')
  end,
}
```
2. Look at the highlight group of the variables `string` and `l` inside of the local function body, along with `MiniDoc`.

### Expected behavior

The highlight group of `string` and `l` inside the local function body, along with `MiniDoc` are linked to a yellow highlight group (such as `Normal`). The fields `config`, `annotation_extractor`, along with the parameter `l` inside the local function declaration are linked to `Identifier` (an orange colour).

This can be achieved with the command `hi! link @variable Normal`:

![image](https://user-images.githubusercontent.com/25364469/206426246-d4832cfc-7e05-4128-afd9-bf8cbe3f3103.png)

### Actual behavior

The highlight group of `string` and `l` inside the local function body, along with `MiniDoc` are (incorrectly?) linked to `Identifier` (an orange colour). The fields `config`, `annotation_extractor`, along with the parameter `l` inside the local function declaration are correctly linked to `Identifier`:

![image](https://user-images.githubusercontent.com/25364469/206425651-ce9414fe-92d5-4671-9089-c7d00fd660dc.png)

**Comment by raddari** [comment]
> Although doable, `hi! link @variable Normal` won't work universally, unfortunately, because it will also add the `guibg` color which will override other background color (like from cursor line).

Ahhhh, I didn't notice that until you mentioned it! Yeah, looks like the hl link isn't a proper fix. Fine tuning the highlight groups sounds like a neat feature, I'm interested to see what you end up doing!

I understand why you would want to keep complexity down and preserve backwards compatibility, so I am perfectly happy to stick with my workaround. I like the added contrast of yellow variables before the treesitter update changed them to orange :) 

I appreciate the work you've put into these modules and your fast responses to issues!

**Comment by echasnovski** [comment]
Yes, this behavior is indeed due to changed default link of variables in 'nvim-treesitter' and Neovim itself.

I think I'll leave default links for tree-sitter highlight groups in favor of allowing users to choose highlighting they want (and modify it with `highlight` or `highlight link` commands.

Thanks for noticing and bringing attention to this!

**Comment by echasnovski** [comment]
@raddari, while developing my own color scheme generator I indeed found having variables with default foreground color easier on the eyes. So decided to follow your suggestion in 'mini.base16' too. Thanks for suggestion!
