### ISSUE TITLE
mini.base16: allow users to fine-tune treesitter highlight groups

### ISSUE THREAD

**Issue by raddari** [echasnovski/mini.nvim#172]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

base16

### Description

In my previous issue (#171), @echasnovski suggested:
> At the moment, I am inclined to let the user fine-tune tree-sitter highlight groups by manually defining them. But I'll think about this more.

This issue is a continuation of that discussion, as I have noticed another unexpected change in the colorscheme and wanted to formalise your suggestion as a feature request :)

A [recent treesitter update](https://github.com/nvim-treesitter/nvim-treesitter/commit/7ce62670b2e0946e3f586f3f07a584f642b02b9b?diff=split) moved the keywords related to storage class into the `@storageclass` and `@type.qualifier` highlight groups (linked to the builtin `StorageClass` and `Type` groups respectively). This change has the unfortunate effect of making C code look quite green:

![image](https://user-images.githubusercontent.com/25364469/206439563-ed27008d-763e-49c3-b719-09d3cac83b60.png)

For a slightly less contrived example, function return types are a bit more difficult to see at a glance:

![image](https://user-images.githubusercontent.com/25364469/206442358-2b4d1fa1-b095-4728-b996-4cad069e7a10.png)

Since treesitter is quite unstable, and changes such as this are common and difficult to track, the implementation of this feature would allow users to change the colours back to how they were without the plugin requiring an update every time a group is changed.

For example, using `hi! link @storageclass Keyword` and `hi! link @type.qualifier Keyword` to simulate overriding these groups would allow users to revert the change themselves:

![image](https://user-images.githubusercontent.com/25364469/206443482-68bbf57b-7e66-4356-a5f6-d35440c70e89.png)

Since these changes are likely to continue until treesitter stabilises, this feature is an interim solution.

**Comment by echasnovski** [comment]
Well, what I really wanted to say is that fine-tuning of highlight groups (in particular, tree-sitter related once) is most likely will be left to user. I don't a better API, than using Neovim's builtin capabilities of `:highlight` and `:highlight link`. Those are both not verbose and flexible enough.

I''ll spend a day or two pondering over this, though.

**Comment by echasnovski** [comment]
I've thought this through and I still think that the best way of personalizing highlight groups is with Neovim's built-in tools.

Thanks for the issue, though, and for proactively using 'mini.nvim'.

**Comment by raddari** [comment]
Forgot to reply to this earlier, sorry!
I realised yesterday that what I was asking for can be achieved through the inbuilt highlighting. I didn't have much experience using highlights until I looked into #171, so thank you and your plugin for helping me learn 😄
