### ISSUE TITLE
mini.menu

### ISSUE THREAD

**Issue by dpretet** [echasnovski/mini.nvim#178]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

None

### Description

Hello,

I developed some times ago a [simple plugin](https://github.com/dpretet/vim-leader-mapper) to create a menu for leader key mapping, like present in Spacemacs. I tried Spacemacs and I found their menu is awesome. 

I just ported my Neovim setup to use a Lua-based init file and I'm considering porting my plugin in Lua. Would you be interested to add it in your mini collection? My plugin is easy to configure from [a vim script or Lua dictionary](https://github.com/dpretet/dotfiles/blob/master/nvim/init.lua#L264) and bind any regular command or function call. The plugin doesn't have code dependency.

BTW, thanks for your work, I love your plugins :)

Damien

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2131563/209434204-a4a11c0d-5899-480e-ad56-b50434864edb.png">

**Comment by echasnovski** [comment]
Thanks for suggestion! I've looked at your plugin: it is quite nice and simple. And the fact that it is older than any of 'mini.nvim' modules says a lot about its quality!

I [have similar module in mind](https://github.com/echasnovski/mini.nvim#planned-modules), named 'mini.clue' (but I quite like the 'mini.menu' name, although it is even more ambiguous than 'mini.clue'). It has some specific goals and approaches in mind. There is some discussion about it in #118.

So I am afraid I am going to say no to this, sorry. Hope you'll still like and use 'mini.nvim' after that :)
