### ISSUE TITLE
Cant get any commands

### ISSUE THREAD

**Issue by shubham-cpp** [echasnovski/mini.nvim#18]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

All modules 

### Description

Cant seem to get any command from any module even after requiring the module.
Eg:  I have this in my `init.lua`
```lua
--- init.lua
require("mini.surround").setup{}
require("mini.tabline").setup{}
require("mini.starter").setup{}
require("mini.starter").open()
```
Upon startup of neovim tabline is visible and so do starter screen, but I can get any commands like 
- MiniStarter.refresh
- MiniStarter.open
- MiniSurround
You get the point

Also I want to mention there's a spelling mistake in `doc/mini.txt` on line 27
expected: `require('mini.surround')`
actual : `require('mini.suround')`

### Neovim version

NVIM v0.6.0-dev+604-g725cbe7d4 Build type: Release

### Steps to reproduce

1. Setup
```lua
-- init.lua
require("packer").startup(function()
use 'echasnovski/mini.nvim'
end
require("mini.surround").setup{}
```
2. Start nvim
```bash
nvim .
```

### Expected behavior

Command `MiniSurround` to work

### Actual behavior

Error: MiniSurround command no found

**Comment by echasnovski** [comment]
Thank for the typo tip.
Just to be sure: how did you call `MiniSurround`, etc? Those are not Neovim commands, those are global Lua objects (tables to be precise). So it is not `:MiniStarter.open`, it is `lua MiniStarter.open()`.

**Comment by echasnovski** [comment]
And also there is no need to call `require("mini.starter").open()` after `require("mini.starter").setup{}`. It will open on VimEnter by default.

**Comment by shubham-cpp** [comment]
Sorry my bad. I thought those were global vim commands. Will close this issue. I have another issue regarding tabline I'll open that later

**Comment by echasnovski** [comment]
No worries. I think I might need to clarify it more clearly in documentation, as those do indeed look like vim commands.
