### ISSUE TITLE
event documentation for mini.starter

### ISSUE THREAD

**Issue by assistcontrol** [echasnovski/mini.nvim#185]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

A while back, in the late 1930's if memory serves me correct, I filed a bug report about not wanting `mini.trailspace` to activate in `mini.starter`, which you resolved.

Similarly, I'd like `MiniMisc.find_root()` to run on `mini.starter` buffers (99% of the time I pick the starter entry that spawns a Telescope file browser for `$PWD`, so I'd like pwd to be set right away).

The issue is that I don't see anything in `mini-starter.txt` that shows for dummies like me what `mini.starter`'s events are. Could you maybe clarify what event I'm looking for for creating an autocommand that runs when `mini.starter` opens a buffer?

Hooking into starter's behaviour opens up some fun possibilities, so perhaps this is an opportunity for highlighting the documentation of starter's event hooks?

**Comment by echasnovski** [comment]
> A while back, in the late 1930's if memory serves me correct, I filed a bug report about not wanting `mini.trailspace` to activate in `mini.starter`, which you resolved.

That's some quality memory 😂👍

> Similarly, I'd like `MiniMisc.find_root()` to run on `mini.starter` buffers (99% of the time I pick the starter entry that spawns a Telescope file browser for `$PWD`, so I'd like pwd to be set right away).

I am not sure what you mean here. The `MiniMisc.find_root()` usually makes sense only for buffers which are associated with actual file on your disk (which buffer from 'mini.starter' is not). The Starter buffer will inherit current directory at place: if opened during startup - current directory of where you called `nvim`; if later - acting current directory at the moment of calling `MiniStarter.open()`. Could you, please, elaborate here? 
 
> The issue is that I don't see anything in `mini-starter.txt` that shows for dummies like me what `mini.starter`'s events are. Could you maybe clarify what event I'm looking for for creating an autocommand that runs when `mini.starter` opens a buffer?
>
> Hooking into starter's behaviour opens up some fun possibilities, so perhaps this is an opportunity for highlighting the documentation of starter's event hooks?

If you mean en event after Starter buffer is opened, then it is a `MiniStarterOpened` event of `User` type. I documented it in [`MiniStarter.open()`](https://github.com/echasnovski/mini.nvim/blob/06eddfd8d6341e6c4f53ec9ae109a376a566329d/doc/mini-starter.txt#L255-L257) and for good measure also in [general lifecycle description](https://github.com/echasnovski/mini.nvim/blob/06eddfd8d6341e6c4f53ec9ae109a376a566329d/doc/mini-starter.txt#L168-L170). What do you think is a better place for this kind of information?

**Comment by echasnovski** [comment]
@assistcontrol, does this answer your questions?

**Comment by assistcontrol** [comment]
It definitely does. I have no idea why I had such a difficult time finding it, as searching for "event" brings you right to it.
