### ISSUE TITLE
mini.starter normal mode forcing is executing whatever is mapped to `<C-\>`

### ISSUE THREAD

**Issue by RaafatTurki** [echasnovski/mini.nvim#189]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

I have toggleterm bound to `[[<C-\>]]` and it's always popping up along with mini.starter.
I've looked more into it and [this line](https://github.com/echasnovski/mini.nvim/blob/06eddfd8d6341e6c4f53ec9ae109a376a566329d/lua/mini/starter.lua#L1284) seems to be the issue.

I think a check for the current mode ought to fix this.

### Neovim version

0.8.2

### Steps to reproduce

use mini.starter with something bound to `<C-\>`

### Expected behavior

`<C-\>` not executing

### Actual behavior

`<C-\>` executing

**Comment by echasnovski** [comment]
I forgot that this could happen... Thanks for noticing!

I'll find a workaround.

**Comment by echasnovski** [comment]
@RaafatTurki, could you try [`tmp`](https://github.com/echasnovski/mini.nvim/tree/tmp) branch, please? It passes tests, but just to be sure that it is also works on your side.

**Comment by RaafatTurki** [comment]
that branch fixes the issue nicely

**Comment by echasnovski** [comment]
> that branch fixes the issue nicely

Thanks. Should be in `main` now... hopefully not breaking anything else.
