### ISSUE TITLE
interactive saiw issue

### ISSUE THREAD

**Issue by hunleyd** [echasnovski/mini.nvim#190]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

surround

### Description

The docs online say:
```
- `saiwi[[<CR>]]<CR>` - add (`sa`) for inner word (`iw`) interactive
  surrounding (`i`): `[[` for left and `]]` for right.
```
and indeed, it worked this way in the past. However, it appear that the default is now:
```
- `saiw?[[<CR>]]<CR>` - add (`sa`) for inner word (`iw`) interactive
  surrounding (`?`): `[[` for left and `]]` for right.
```
Which of these are intended?

### Neovim version

0.8.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. enter `saiwi` and see it surround the word with `i` and not go into interactive mode

### Expected behavior

1. `nvim -nu minimal.lua`
2. enter `saiwi` and see it go into interactive mode

### Actual behavior

1. `nvim -nu minimal.lua`
2. enter `saiwi` and see it surround the word with `i` and not go into interactive mode

**Comment by echasnovski** [comment]
Oh, thanks! I missed to update it after implementing #103. I'll fix this tomorrow.

**Comment by hunleyd** [comment]
oh, ok. gotta forget and relearn the muscle memory now, lol

thanks *a ton* for your work on mini.nvim. i <3 this plugin!

**Comment by echasnovski** [comment]
Should be fixed now. Thanks again!

> thanks a ton for your work on mini.nvim. i <3 this plugin!

Coming from a 10+ years GitHub user with (so far) a single star to 'mini.nvim' means a lot! 🙏
