### ISSUE TITLE
Add description field for mini.ai custom_textobjects

### ISSUE THREAD

**Issue by nat-418** [echasnovski/mini.nvim#192]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

Given a configuration like:

```lua
local tsSpec = require('mini.ai').gen_spec.treesitter
require('mini.ai').setup({
  custom_textobjects = {
    c = tsSpec({
      a = '@class.outer',
      i = '@class.inner',
    }, {})
  }
})
```

It would be nice to be able to put something like `desc` to use in conjunction with which-key or legendary or whatever to describe the keymap.

**Comment by echasnovski** [comment]
This is an interesting idea. It has at least one, but pretty significant obstacle: 'mini.ai' only defines `a` and `i` mappings along with their `next`/`last` variants. They implement their custom waiting for character input, which allows users to take their time when deciding what to press. This is a part of 'which-key' type of functionality.

I *think* it should be possible to add custom description to already existing mappings inside 'folke/which-key.nvim'.

**Comment by nat-418** [comment]
Thanks for following up. I'm a bit unclear on where the use-case for mini.ai ends and treesitter-textobjects begins. Would be nice to find a solution that "just works".
