### ISSUE TITLE
`require('mini.indentscope').gen_animation.none()` throws an error

### ISSUE THREAD

**Issue by charlyalizadeh** [echasnovski/mini.nvim#194]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

When I try to assign `animation = require('mini.indentscope').gen_animation.none()` I get the following error:
```
attempt to index field 'gen_animation' (a function value)
```
I fixed this issue by using `require('mini.indentscope').gen_animation('none')` but the documentation specifies to use `require('mini.indentscope').gen_animation.none()` for no animation.

### Neovim version

0.8.2

### Steps to reproduce

```lua
--- minimal.lua
local indentscope = require('mini.indentscope')
indentscope.setup({
    draw = {
        animation = indentscope.gen_animation.none()
    }
})
```
1. `nvim -nu minimal.lua`

### Expected behavior

`require('mini.indentscope').gen_animation.none()` should not throw an error and return a function that always return 0.

### Actual behavior

`require('mini.indentscope').gen_animation.none()` throws the following error:
```
attempt to index field 'gen_animation' (a function value)
```

**Comment by echasnovski** [comment]
Do you have the latest 'mini.nvim'/'mini.indentscope' version? When you look into 'lua/mini/indentscope.lua' file inside 'mini.nvim' plugin directory (somewhere where your plugin manager put it), does it have [this line](https://github.com/echasnovski/mini.nvim/blob/e33b9a7d7214b5c743b79082b6b89dca78620030/lua/mini/indentscope.lua#L431)?

**Comment by charlyalizadeh** [comment]
I had the "stable" version 'mini.nvim'/'mini.indentscope' so I understand now the origin of the bug (my fault, I thought "stable" was considered the latest version). Thank you for your fast reaction!

**Comment by echasnovski** [comment]
Glad it worked out!

**Comment by ragu-manjegowda** [comment]
@echasnovski 

I bumped into this just now. May be it is worth mentioning in the doc about missing feature in stable version.

**Comment by echasnovski** [comment]
> @echasnovski
> 
> I bumped into this just now. May be it is worth mentioning in the doc about missing feature in stable version.

It is not a missing, but a breaking feature, which is [mentioned in CHANGELOG](https://github.com/echasnovski/mini.nvim/blob/main/CHANGELOG.md#mini.indentscope). By default on GithlHub you see README for `main` branch describing its features. Switch to `stable` branch which [has an appropriate description](https://github.com/echasnovski/mini.nvim/blob/stable/readmes/mini-indentscope.md#default-config).

If you are on a `stable` branch, I would suggest favoring reading documentation locally from your installed version.
