### ISSUE TITLE
I replace 'i' with 'k', but using mini.ai, set inside = 'k', will overwrite my own key maps

### ISSUE THREAD

**Issue by huwqchn** [echasnovski/mini.nvim#195]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.ai

### Description

I use Colemak keyboard layout, so I always map k to i when I use neovim/vim,
using k for insert and inside operator prepend.

### Neovim version

0.82

### Steps to reproduce

1. my keymaps
```lua
vim.keymap.set("", "k", "i")
```
2. set inside = "k" when I setup mini.ai
```lua
require("mini.ai").setup({
  mappings = {
    -- Main textobject prefixes
    around = 'a',
    inside = 'k',

    -- Next/last variants
    around_next = 'ae',
    inside_next = 'ke',
    around_last = 'au',
    inside_last = 'ku',
 }
})
```

### Expected behavior

Works both mini.ai keymaps and my own keymaps

### Actual behavior

It works when I type `ckf`, but not works when I type `ckw`.
I read Mini.ai source code, I think, mini.ai overwrote my mapping for 'k'.

**Comment by echasnovski** [comment]
Thanks for the issue! Never really looked into different keyboard layouts, so didn't think about this use case.

> I read Mini.ai source code, I think, mini.ai overwrote my mapping for 'k'.

Overriding mappings for `a` and `i` is the whole point of this plugin. The issue here is that `iw` is not a 'mini.ai'-defined textobject, so it falls back to being equivalent to typing `iw`, which is not correct in your user case.

I'll see what I can do here.

**Comment by echasnovski** [comment]
Have you tried using 'langmap' instead of key mapping? It seems like a more appropriate solution for your use case.

So instead `vim.keymap.set("", "k", "i")` try `vim.o.langmap = 'k;i,i;k'`.

**Comment by huwqchn** [comment]
wow, Thanks so much, I dont even know about langmap, It's amazinig, I learned a lot

**Comment by echasnovski** [comment]
I've just added tests for this use case. Having `set langmap=ki,ik` seems to solve this use case with default 'mini.ai' config.

Thanks for the issue!

**Comment by b1nhack** [comment]
I tried this solution.
1. I mapped "i" to "l", because I need to use "i" to move the cursor to the right.
2. I use `vim.o.langmap = 'k;i,i;k'`
"i" will move the cursor up

3. Modify langmap to `vim.o.langmap = 'k;i'`
"i" moves the cursor to the right, but "k" doesn't go into insert mode, "k" also moves the cursor to the right

add keymap: `vim.keymap.set({ "n", "x", "o" }, "k", "i")`
"k" still can't get into insert mode

**Comment by echasnovski** [comment]
> I tried this solution.
> ...
>     2. I use `vim.o.langmap = 'k;i,i;k'`
>        "i" will move the cursor up

Sorry, I do not understand the problem here. With `vim.o.langmap = 'ki,ik'` keys "i" and "k" are essentially swapped: use "i" to go up and "k" for all "regular" "inside" textobjects (like `vk)`, `dkw`, etc.). This works and does not need any more additional mappings.

**Comment by b1nhack** [comment]
The problem is that colemak's i is qwerty's l, and I need to keep the neovim convention, so I need to map i to l.
At the same time, I needed a key instead of i, for entering insert mode and text objects, and I chose the k key.
The current mapping situation is as follows:
```
vim.keymap.set({ "n", "x" }, "i", "l")
vim.keymap.set({ "n", "x", "o" }, "k", "i")
```
So my scenario involves three keys, i, l, k, and I cannot simply swap k and i.
The implementation principle of mini.ai is to remap inside, which will theoretically conflict with my keys.
Maybe only compatible from within.

**Comment by echasnovski** [comment]
> The problem is that colemak's i is qwerty's l, and I need to keep the neovim convention, so I need to map i to l.
> At the same time, I needed a key instead of i, for entering insert mode and text objects, and I chose the k key.

I am not sure that manually choosing what keys to remap is a good idea here. I would assume that the better approach is to remap the whole keyboard layout altogether. For example, judging by [Wikipedia article](https://en.wikipedia.org/wiki/Colemak), a "key instead if i" is "u".

Here is an [article with 'langmap'](https://www.xudongz.com/blog/2017/vim-colemak/) example. With those remappings, pressing "u" on Colemak will have the same effect as "i" in QWERTY. So, for example, to delete inside word ("diw" in QWERTY) press "suw".

This is the only way 'mini.ai' will support different keyboard layouts (outside of already exported `config.mappings`).

**Comment by huwqchn** [comment]
> The problem is that colemak's i is qwerty's l, and I need to keep the neovim convention, so I need to map i to l. At the same time, I needed a key instead of i, for entering insert mode and text objects, and I chose the k key. The current mapping situation is as follows:
> 
> ```
> vim.keymap.set({ "n", "x" }, "i", "l")
> vim.keymap.set({ "n", "x", "o" }, "k", "i")
> ```
> 
> So my scenario involves three keys, i, l, k, and I cannot simply swap k and i. The implementation principle of mini.ai is to remap inside, which will theoretically conflict with my keys. Maybe only compatible from within.

```
custom_textobjects = {
    w = { "()()%f[%w]%w+()[ \t]*()" },
},
``` 
this might help, only `kw` overwrite keymap

**Comment by huwqchn** [comment]
If it is a custom textobjects, there will not be fall back to builtin `a`/`i` textobjects

**Comment by b1nhack** [comment]
> > The problem is that colemak's i is qwerty's l, and I need to keep the neovim convention, so I need to map i to l. At the same time, I needed a key instead of i, for entering insert mode and text objects, and I chose the k key. The current mapping situation is as follows:
> > ```
> > vim.keymap.set({ "n", "x" }, "i", "l")
> > vim.keymap.set({ "n", "x", "o" }, "k", "i")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So my scenario involves three keys, i, l, k, and I cannot simply swap k and i. The implementation principle of mini.ai is to remap inside, which will theoretically conflict with my keys. Maybe only compatible from within.
> 
> ```
> custom_textobjects = {
>     w = { "()()%f[%w]%w+()[ \t]*()" },
> },
> ```
> 
> this might help, only `kw` overwrite keymap

Yes, it works
