### ISSUE TITLE
Add functionality to change buffer position in tabline

### ISSUE THREAD

**Issue by thomas-ah** [echasnovski/mini.nvim#197]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

First off: I love the `mini` plugin library. It has replaced lots of other separate plugins for me and made Neovim loads and loads faster. Thank you for all your hard work!

In the tabline Documentation, under the Features section, I noticed you wrote:
```
--- What it doesn't do:
--- - Custom buffer order is not supported.
```

Does this mean you are not planning to ever implement it? Or can you still be persuaded to do so? :) I can very much appreciate the minimalist approach for `mini.tabline`. The only functionality I currently miss is exactly the one above: custom positioning/ordering for buffers in the tabline.

It's a functionality I used extremely much when I still used `BarBar`, as it allows a user to visually pair tabs together that are related in any form or manner. For example, one of my use cases was to pair the tab of an open implementation file together with its test file. This allowed for fast and easy buffer switching.

I searched through the closed issues for the tabline module and did not come across this request before, hence my asking regardless of your comment in the documentation. Apologies if this request is unwanted.

**Comment by echasnovski** [comment]
> First off: I love the `mini` plugin library. It has replaced lots of other separate plugins for me and made Neovim loads and loads faster. Thank you for all your hard work!

:heart:


> Does this mean you are not planning to ever implement it? Or can you still be persuaded to do so? :) I can very much appreciate the minimalist approach for `mini.tabline`. The only functionality I currently miss is exactly the one above: custom positioning/ordering for buffers in the tabline.
> 
> It's a functionality I used extremely much when I still used `BarBar`, as it allows a user to visually pair tabs together that are related in any form or manner. For example, one of my use cases was to pair the tab of an open implementation file together with its test file. This allowed for fast and easy buffer switching.
> 
> I searched through the closed issues for the tabline module and did not come across this request before, hence my asking regardless of your comment in the documentation. Apologies if this request is unwanted.

Custom order was indeed not even planned to be supported. Mostly because it was not easy to implement for me at the time, but also because it would mean extra functions (like `next_tab()`/`prev_tab()`) instead of already present `:bnext`/`:bprev`.

That said I do also wish for custom order possibility for the exact reason you described. It is far from urgent, though, as there is `:b#` command which takes you to alternate file (the buffer you previously visited) which can be mapped to a more easier mapping (I use `<Leader>ba`; some like `<BS>`).

I'll think about it, but at the moment it is definitely not the top priority.

**Comment by thomas-ah** [comment]
Thanks for your fast response! Yes, I can imagine it's much more work. You would have to to keep track of the buffer positions by yourself instead of relying on neovim's numbering/indexing.

> [...] but also because it would mean extra functions (like next_tab()/prev_tab()) instead of already present :bnext/:bprev.

I suppose the new functions would become something like `move_buf_prev()` and `move_buf_next()`, and `:bprev/:bnext` would just keep on existing and functioning like they do :)

> It is far from urgent, though, as there is :b# command which takes you to alternate file (the buffer you previously visited) which can be mapped to a more easier mapping (I use <Leader>ba; some like <BS>).

Yeah, although that is more of an alternative to navigating the buffers though. It's not an alternative to moving the buffer tabs to a different location on the tabline, unfortunately.

> I'll think about it, but at the moment it is definitely not the top priority.

I completely understand it's not high on the list :) Thanks a lot for taking it into consideration at all!

**Comment by echasnovski** [comment]
> I suppose the new functions would become something like `move_buf_prev()` and `move_buf_next()`, and `:bprev/:bnext` would just keep on existing and functioning like they do :)

Yes, something like `move_left()`/`move_right()`. But on top of that, there should be functionality to switch focus on next/previous buffer in current tab order: `next_tab()`/`prev_tab()` (or `goto_left()`/`goto_right()`).

**Comment by echasnovski** [comment]
I think this won't be a part of 'mini.tabline'. Mostly for two reasons:
- It will indeed lead to almost complete refactor of existing code plus adding new one (with documentation close to the size of existing one). Not a huge deal considering current size, but still.
- I kind of like that it is intended to work with `:bnext`/`:bprev`. Once the door of custom order is opened, it would lead to other complications. Like the new 'mini.bracketed' has `[b` and `]b` for navigating through buffers which uses natural buffer order right now. If this feature is implemented, those would need to account for it.

That said, I'd like to recommend looking at new ['mini.bracketed'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-bracketed.md). Besides `[b`/`]b` for buffers, it also has `[o`/`]o` for recently used files. I noticed that it completely removed my need for visually pairing related buffers for easier switching between 2 and more buffers.

All in all, unfortunately I'll close this. Thanks for suggestion, though!
