### ISSUE TITLE
Beta-testing 'mini.move'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#199]
Please leave your feedback about new 'mini.move' module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by ggandor** [comment]
`<alt-h/j/k/l>` are still being overtaken with the following setup:
```
require('mini.move').setup {
    -- Move current line in Normal mode
    line_left = '',
    line_right = '',
    line_down = '',
    line_up = '',
}
```

**Comment by echasnovski** [comment]
> `<alt-h/j/k/l>` are still being overtaken in Normal mode with the following setup:
> 
> ```
> require('mini.move').setup {
>     -- Move current line in Normal mode
>     line_left = '',
>     line_right = '',
>     line_down = '',
>     line_up = '',
> }
> ```

It should be done inside `config.mappings`:

```
require('mini.move').setup({
  mappings = {
    -- Move current line in Normal mode
    line_left = '',
    line_right = '',
    line_down = '',
    line_up = '',
  },
})
```

**Comment by ggandor** [comment]
Silly me. Feel free to delete these comments to reduce noise.

**Comment by RaafatTurki** [comment]
Hello Evgeni!
Awesome work as usual!
Function names and documentation were pretty clear for me.

**Some issues:**
1. Sometimes when I'm moveing lines vertically lines "jumble" or shake a bit (tried recording it with asciinema and into a gif but it's too fast for them, lmk if you need a showcase and ill see what I can do).
My guess would be that I'm seeing the split second between the 'cut' and 'paste' actions, maybe swapping lines with `nvim_buf_set_lines()` fixes it.

1. The same "jumbling" happens when holding down the keys (activating keyboard auto repeat) trying to move one or more lines into the buffers top or bottom edges, I suspect this is the same as `#1` but I'll list it just to be sure.

**A Request:**
1. Moving lines over folds is handled nicely, however moving folds themselves happens only ones and they get opened, I've always wanted to see this feature but I haven't seen any moving plugin that does it.

**Comment by echasnovski** [comment]
> **Some issues:**
> 
>     1. Sometimes when I'm moveing lines vertically lines "jumble" or shake a bit (tried recording it with asciinema and into a gif but it's too fast for them, lmk if you need a showcase and ill see what I can do).
>        My guess would be that I'm seeing the split second between the 'cut' and 'paste' actions, maybe swapping lines with `nvim_buf_set_lines()` fixes it.
> 
>     2. The same "jumbling" happens when holding down the keys (activating keyboard auto repeat) trying to move one or more lines into the buffers top or bottom edges, I suspect this is the same as `#1` but I'll list it just to be sure.

Unfortunately, I can't replicate any of these two. For me it is as smooth as moving cursor. I don't think redraw should happen between "cut" and "paste" (not 100% sure, though). 

One thing I noticed when trying to replicate the second point is that lines were reformatted and automatically collapsed into a fold (I have `foldmethod=indent`), but on the next step it again was reformatted outside of fold. The fold creation lead to line collapsing which indeed look like a glitch of some sort.

Another possible source of the issue might be tree-sitter highlighting and diagnostic. Could you try this in regular buffer without highlight and diagnostic, and see if it still there?

> **A Request:**
> 
>     1. Moving lines over folds is handled nicely, however moving folds themselves happens only ones and they get opened, I've always wanted to see this feature but I haven't seen any moving plugin that does it.

That is a **great** suggestion. My first instinct is that there is no such functionality for a reason: folds are usually created automatically by method from `:h 'foldmethod'`. They seem to be managed "from outside" only in case of `foldmethod=manual`, which is not ideal.

So this is a "I would love to do this, but I don't know how and if it is even possible" case.

**Comment by RaafatTurki** [comment]
> Another possible source of the issue ...

I've disabled treesitter entirely and it's still jittering, I've [captured](https://user-images.githubusercontent.com/16624558/212563701-7cad100d-d309-416c-b35e-1416a9a18b92.mp4) it with obs

I might try the buffer line swap `nvim_buf_set_lines()` implementation on my end and report back.

> My first instinct is that there is no such functionality for a reason ...

Plugin authors in general steer away from fold manipulation because nvim doesn't provide an API for querying them [yet](https://github.com/neovim/neovim/issues/19226).

**Comment by lodisy** [comment]
Hello,

I just installed the plugin, but there was an issue in the V/v mode.

I double checked the key mappings with `verbose vmap <M-j>`, there were no other overrides.

```
n  <M-j>       * <Cmd>lua MiniMove.move_line('down')<CR>
                 Move line down
        Last set from Lua
x  <M-j>       * <Cmd>lua MiniMove.move_selection('down')<CR>
                 Move down
        Last set from Lua
```

The issue was: after selecting more than 2 lines of code in visual mode, the first move by pressing <M-j> (or other directions, or with count) was working as expected, it moved lines of code. After the first move, mode was changed automatically back to NORMAL, if keep pressing <M-j>, it would only move the first line of the selected code block. I thinks it's not an expected behavior after checking the demo video.

**Comment by davidsierradz** [comment]
Could be interesting if there was an option to maintain the cursor position when doing the movements, my use-case would be replacing [gbprod/stay-in-place.nvim](https://github.com/gbprod/stay-in-place.nvim).

**Comment by zeitchef** [comment]
I'm wondering if a single config option to just change the modifier key would make sense? `vim-move` provided this and reduced by config to just a single line.

**Comment by echasnovski** [comment]
> Could be interesting if there was an option to maintain the cursor position when doing the movements, my use-case would be replacing [gbprod/stay-in-place.nvim](https://github.com/gbprod/stay-in-place.nvim).

This is only reasonable for horizontal linewise movement, though. The proper way of doing it (using extmark, I think) will add some amount of complexity to it. I'll look into it, but I am not sure it will be added, though.

**Comment by echasnovski** [comment]
> The issue was: after selecting more than 2 lines of code in visual mode, the first move by pressing `<M-j>` (or other directions, or with count) was working as expected, it moved lines of code. After the first move, mode was changed automatically back to NORMAL, if keep pressing `<M-j>`, it would only move the first line of the selected code block (same as the normal mode keymap). I am not sure why it changed the mode automatically, I also tried disabling all other active plugins via Lazy.nvim with `enabled = false`, still have this problem.

Hi, @lodisy! I am honestly not sure where to even start with this. I can not reproduce it.

Let's go step by step (assuming mappings are indeed correct):
- Does it indeed happen **only** if selection is strictly more than 2 lines?
- It doesn't show any errors or messages after visual selection is gone?
- Do you have close folds around where you move lines?
- Maybe you still have some plugin active when trying `enabled = false` in 'lazy.nvim'? Like the ones left from when you used 'packer.nvim' or other plugin manager.

**Comment by RaafatTurki** [comment]
> Does it happen in plain text files, without any highlighting and LSP servers running

Turning off LSP and TS in the c file still jittered, however it doesn't jitter in text files (same c file content)

I've implemented a very crude `nvim_buf_set_lines()` solution (linewise and vertical only) I was talking about earlier.
It lacks many of the niceties currently present but the jittering is gone. lmk what you think.

```lua
MiniMove.move_line = function(direction)
  if H.is_disabled() then return end

  local is_moving = vim.deep_equal(H.state, H.get_move_state())
  local normal_command = (is_moving and 'undojoin |' or '') .. ' keepjumps normal! '
  local cmd = function(x) vim.cmd(normal_command .. x) end

  local lnr = vim.api.nvim_win_get_cursor(0)[1]

  if direction == 'up' then
    local lines = vim.api.nvim_buf_get_lines(0, lnr-2, lnr, true)
    vim.api.nvim_buf_set_lines(0, lnr-2, lnr, true, {lines[2], lines[1]})
    cmd 'k'
  elseif direction == 'down' then
    local lines = vim.api.nvim_buf_get_lines(0, lnr-1, lnr+1, true)
    vim.api.nvim_buf_set_lines(0, lnr-1, lnr+1, true, {lines[2], lines[1]})
    cmd 'j'
  end
  
  if vim.o.equalprg == '' then cmd('==^') end
end
```

**Comment by echasnovski** [comment]
> I've implemented a very crude `nvim_buf_set_lines()` solution (linewise and vertical only) I was talking about earlier.
> It lacks many of the niceties currently present but the jittering is gone. lmk what you think.

Yes, it does seem like working, but it won't transform nicely when trying to account useful small things: `v:count`, undo blocks, folds (should compute which lines to swap taking into account all possible folds between current and target swapping lines), removing marks (`nvim_buf_set_lines()` removes all marks inside their input range).

I think the `move_line()` might be simplified to use `move_selection()` (select line, move, unselect, restore visual marks). I tried it for a brief moment, but not sure why I discarded it.

Presence of jittering is not good, I agree. Could you try setting `lazyredraw=true` and try reproduce jittering again? If it work out, the solution might be to set it temporarily inside moving functions. (Note: if you use 'folke/noice.nvim', you might need to disable it for the time of experiment).

**Comment by RaafatTurki** [comment]
> nvim_buf_set_lines() removes all marks inside their input range

I see

> I think the `move_line()` might be simplified to use `move_selection()` ...

I should make it clear that `move_selection()` jitters as well, and all jittering happens on vertical movement only.

> Could you try setting `lazyredraw=true`
> if you use 'folke/noice.nvim', you might need to disable it

I've tried it with `lazyredraw`, no LSP, no TS, no Noice .. same issues

I'll debug this further and come back with something solid/minimal repro

**Comment by lodisy** [comment]
> > The issue was: after selecting more than 2 lines of code in visual mode, the first move by pressing `<M-j>` (or other directions, or with count) was working as expected, it moved lines of code. After the first move, mode was changed automatically back to NORMAL, if keep pressing `<M-j>`, it would only move the first line of the selected code block (same as the normal mode keymap). I am not sure why it changed the mode automatically, I also tried disabling all other active plugins via Lazy.nvim with `enabled = false`, still have this problem.
> 
> Hi, @lodisy! I am honestly not sure where to even start with this. I can not reproduce it.
> 
> Let's go step by step (assuming mappings are indeed correct):
> 
>     * Does it indeed happen **only** if selection is strictly more than 2 lines?
> 
>     * It doesn't show any errors or messages after visual selection is gone?
> 
>     * Do you have close folds around where you move lines?
> 
>     * Maybe you still have some plugin active when trying `enabled = false` in 'lazy.nvim'? Like the ones left from when you used 'packer.nvim' or other plugin manager.

Hi, thanks for your reply..

>     * Does it indeed happen **only** if selection is strictly more than 2 lines?

I was meant to say more than 1 line, i.e a block of code, in visual mode, plugin works fine in normal mode movement with one line of code.


>     * It doesn't show any errors or messages after visual selection is gone?

There was no message or error.

>     * Do you have close folds around where you move lines?

No, I didn't have any folds in the test code.

>     * Maybe you still have some plugin active when trying `enabled = false` in 'lazy.nvim'? Like the ones left from when you used 'packer.nvim' or other plugin manager.

I am not using any plugin manager other than lazy.nvim. I disabled all other active plugins except the colorscheme and also minimove, see the screenshot below...

![2023-01-17_11-39](https://user-images.githubusercontent.com/8101584/212805010-7c147710-f972-4c35-aaa0-54f621c386db.png)

I would append a video record later if necessary.

**Comment by echasnovski** [comment]
> I am not using any plugin manager other than lazy.nvim. I disabled all other active plugins except the colorscheme and also minimove, see the screenshot below...

Good thing you have you dorfiles public...
After bisecting your 'lua/configs/settings.lua', [this line](https://github.com/lodisy/dotfiles/blob/35769b8e2961e9814b4cda0696c066503dcdcbf6/nvim/lua/configs/settings.lua#L60) seems to be the root cause of this. This redefines `` ` `` without keymapping, thus making virtually impossible to use its original meaning. This is not a good idea, as it breaks the [`]`(https://neovim.io/doc/user/motion.html#%60) meaning for marks. It is used in 'mini.move' to reselect Visual selection.

I'd suggest you remove this settings as ['paste' seems to be obsolete](https://neovim.io/doc/user/options.html#'paste').

**Comment by echasnovski** [comment]
> I've tried it with lazyredraw, no LSP, no TS, no Noice .. same issues

Some other things to try that come to mind:
- Try both `:TSBufDisable highlight` and `:syntax off`. The built-in syntax might also be the cause here.
- Maybe some other plugin does something computationally intensive on `CursorMoved`? Is there anything like that if execute `:au CursorMoved`?

**Comment by echasnovski** [comment]
I have just pushed some updates. Among fixes, there are two relatively small, but significant features:
- Cursor now moves along the linewise selection. This is indeed more intuitive. Thanks @davidsierradz!
- There is now a `config.options` field controlling movement. It now has the `reindent_linewise` option, which can be used to disable automatic reindent when moving linewise. I didn't want to make it an option, as there seemed to be no issues with it, but it doesn't always play nicely with folds (especially with `foldmethod=indent`).
    Interestingly, with `MiniMove.config.options.reindent_linewise = false` it is now possible to move folds themselves (again, at least with `foldmethod=indent`). It is not something I'd like to guarantee as feature, but a nice little bonus for now. @RaafatTurki, maybe it will also work for you?

**Comment by JJGO** [comment]
I've been testing the plugin and I'd like to use HJKL in both normal and visual mode. Following the help page I specified the following config 

```lua
require("mini.move").setup({
  mappings = {
    left = "H",
    right = "L",
    down = "J",
    up = "K",
    line_left = "H",
    line_right = "L",
    line_down = "J",
    line_up = "K",
  },
})
```

All bindings work in visual mode but `K` does not work in normal mode.

**Comment by echasnovski** [comment]
> I've been testing the plugin and I'd like to use HJKL in both normal and visual mode. Following the help page I specified the following config
> 
> ```lua
> require("mini.move").setup({
>   mappings = {
>     left = "H",
>     right = "L",
>     down = "J",
>     up = "K",
>     line_left = "H",
>     line_right = "L",
>     line_down = "J",
>     line_up = "K",
>   },
> })
> ```
> 
> All bindings work in visual mode but `K` does not work in normal mode.

What does `nmap K` says? It should be something having `MiniMove` in it.

It is usually used as a common mapping for `vim.lsp.buf.hover`, so maybe that is it.

**Comment by JJGO** [comment]
Good call, I assumed that since it was last in the config it'd take precedence, but apparently not, most likely due to the on_attach event.

```
:nmap K
n  K           *@<Lua 807: /usr/local/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/buf.lua:41>
                 Hover
n  K           * <Cmd>lua MiniMove.move_line('up')<CR>
                 Move line up
```

And sure enough, commenting out the following from the lspconfig on_attach function from the [docs](https://github.com/neovim/nvim-lspconfig) makes the `K` mapping work. 

```lua
vim.keymap.set("n", "K", vim.lsp.buf.hover, bufopts)
```

Maybe it is worth putting in the help page as the lspconfig is a quite popular package.

**Comment by matu3ba** [comment]
I would prefer to not being forced to waste precious keybindings with hydra.nvim.
However, afaiu there seems to be no setup option to not set any keybindings and directly use the functions for moving.
Would that be possible to arrange?

What I basically want is a hydra with venn-like behavior, but for moving:
```lua
local venn_hint = [[
 Arrow^^^^^^   Select region with <C-v>
 ^ ^ _K_ ^ ^   _f_: surround it with box
 _H_ ^ ^ _L_
 ^ ^ _J_ ^ ^                      _<C-c>_
]]

M.venn_hydra = Hydra({
   name = 'Draw Diagram',
   hint = venn_hint,
   config = {
      color = 'pink',
      invoke_on_body = true,
      hint = {
         border = 'rounded'
      },
      on_enter = function()
         vim.o.virtualedit = 'all'
      end,
   },
   mode = 'n',
   body = '<leader>v',
   heads = {
      { 'H', '<C-v>h:VBox<CR>' },
      { 'J', '<C-v>j:VBox<CR>' },
      { 'K', '<C-v>k:VBox<CR>' },
      { 'L', '<C-v>l:VBox<CR>' },
      { 'f', ':VBox<CR>', { mode = 'v' }},
      { '<C-c>', nil, { exit = true } },
   }
})
```
as shown here: https://github.com/anuvyklack/hydra.nvim/wiki/Draw-diagrams

**Comment by echasnovski** [comment]
> I would prefer to not being forced to waste precious keybindings with hydra.nvim. However, afaiu there seems to be no setup option to not set any keybindings and directly use the functions for moving. Would that be possible to arrange?

You can set no keybindings by providing empty string for all `mappings` fields. Like so:

```lua
require('mini.move').setup({
  mappings = {
    left  = '',
    right = '',
    down  = '',
    up    = '',

    line_left  = '',
    line_right = '',
    line_down  = '',
    line_up    = '',
  },
})
```

**Comment by matu3ba** [comment]
@echasnovski Thanks alot. 

Block selection appears to work flawlessly, which enables the nice use case of moving venn diagrams.

However, line selection moves break very fast (for example selection with V from line start and j or k(up/down) moves the lines 1 row up or down, but the hydra bricks (selection gone and hydra not closable with C-c).

Not sure, if this is a bug due to hydra. Afaiu, the mode `v` for line selection should be still correct.

This is my config (feel free to steal):
```lua
local selmove_hint = [[
 Arrow^^^^^^
 ^ ^ _k_ ^ ^
 _h_ ^ ^ _l_
 ^ ^ _j_ ^ ^                      _<C-c>_
]]

local ok_minimove, minimove = pcall(require, "mini.move")
assert(ok_minimove)
if ok_minimove == true then
  local opts = {
    mappings = {
      left  = '', right = '', down  = '', up    = '',
      line_left  = '', line_right = '', line_down  = '', line_up    = '',
    },
  }
  minimove.setup(opts)
  -- setup here prevents needless global vars for opts required by `move_selection()/moveline()`
  M.minimove_box_hydra = Hydra({
     name = 'Move Box Selection',
     hint = selmove_hint,
     config = {
        color = 'pink',
        invoke_on_body = true,
        hint = {
           border = 'rounded'
        },
        on_enter = function()
           vim.o.virtualedit = 'all'
        end,
     },
     mode = 'v',
     body = '<leader>vb',
     heads = {
        { 'h', function() minimove.move_selection("left", opts) end },
        { 'j', function() minimove.move_selection("down", opts) end },
        { 'k', function() minimove.move_selection("up", opts) end },
        { 'l', function() minimove.move_selection("right", opts) end },
        { '<C-c>', nil, { exit = true } },
     }
  })
  M.minimove_line_hydra = Hydra({
     name = 'Move Line Selection',
     hint = selmove_hint,
     config = {
        color = 'pink',
        invoke_on_body = true,
        hint = {
           border = 'rounded'
        },
        on_enter = function()
           vim.o.virtualedit = 'all'
        end,
     },
     mode = 'v',
     body = '<leader>vl',
     heads = {
        { 'h', function() minimove.move_line("left", opts) end },
        { 'j', function() minimove.move_line("down", opts) end },
        { 'k', function() minimove.move_line("up", opts) end },
        { 'l', function() minimove.move_line("right", opts) end },
        { '<C-c>', nil, { exit = true } },
     }
  })
end
```

**Comment by echasnovski** [comment]
> However, line selection moves break very fast (for example selection with V from line start and j or k(up/down) moves the lines 1 row up or down, but the hydra bricks (selection gone and hydra not closable with C-c).

After spending around half an hour trying to set this up, I finally understand the issue.

`MiniMove.move_line()` is designed to be used in Normal mode. Replace `mode = 'v'` with `mode = 'n'` and it should work.

**Comment by matu3ba** [comment]
Consider my configuration, which enables virtualedit=all for the local window
```
| Done   | Name          | a         | b    | Out  | Comment                        |
| ------ | ------------- | --------- | ---- | ---- | ------------------------------ |
|   |                    |           |      |      | **Decimal Float Conversion**   |
| ✗ | __dpd_extendsddd2  |      dec32| ∅  |dec64      |                        |
| ✗ | __bid_extendsddd2  |      dec32| ∅  |dec64      |                        |
```
Selecting
```
|dec64      |                        |
|dec64      |                        |
```
to move them rightwards does not work, because right movement stops at EOL and it gets weirder (to be continued).

**Comment by matu3ba** [comment]
Now without setting ve=all (I think ve=none is the default).

1. Another thing: Block movements outside the draw area of neovim moves things weirdly.
2. Moving rightwards and upwards loses focus on the whole block for some reason and the selection with cursor glitches leftwards.

**Comment by matu3ba** [comment]
> After spending around half an hour trying to set this up, I finally understand the issue.
Sorry for the long time. I'll try to make up with some testing.

**Comment by matu3ba** [comment]
Apparently this bug depends on the context somehow, so here a video (without set ve=all which seems to make no different in block selection mode):
https://asciinema.org/a/k3knrtBpQIXPnzX14CWZu1Ic8

**Comment by echasnovski** [comment]
> Sorry for the long time. I'll try to make up with some testing.

No worries, it was me who should have looked at code more carefully. It took that long because I couldn't understand why there were no `<Leader>vl` keymapping in Normal mode (as I expected).

-------

I've reproduced this. It has nothing to do with Hydra, but with multibyte characters in your strings.

Here is a shorter example:
```
aaaaaaaaa
✗ bbbbbbb
✗ bbbbbbb
```
Steps:
- Select all `b` in blockwise Visual selection.
- Move up. It moves all selection by reselects 2 less horizontally. Happens only if selection spans at least two lines.

I'll see what I can do, but I fear it might need a Vim patch...

**Comment by echasnovski** [comment]
> I'll see what I can do, but I fear it might need a Vim patch...

Yes, it indeed does seem to be an issue with Vim itself. See vim/vim#11925.

**Comment by echasnovski** [comment]
@matu3ba, it should be fixed in latest Nightly (NVIM v0.9.0-dev-857+g2c5906b55). Could you, please, try it?

**Comment by matu3ba** [comment]
@echasnovski Thanks alot!

One nitpick, which could also go into documentation as it creates some complexity to handle interval logic: using `:set ve=all` creates empty lines which are not truncated.

I did also find, that spaces <-> tabs conversion might lead to surprising behavior on line movement:
https://asciinema.org/a/vU5F0KlQMcDDwIGQF1VKImX3Q

Both things could/should be probably documented in a FAQ.

**Comment by echasnovski** [comment]
> One nitpick, which could also go into documentation as it creates some complexity to handle interval logic: using :set ve=all creates empty lines which are not truncated.

It is not because of `virtualedit=all` but because moving selection *only moves selection* and does nothing more. If you make a selection at the end of line with only whitespace to the left, it will move that selection leaving trailing whitespace untouched. In your case of `ve=all` you probably make intermediate moves creating this type of lines, which when moved further recreate this situation. Usage of `[count]` might prevent that.

Here is a demo (lines 3 and 4 are empty):

https://user-images.githubusercontent.com/24854248/216561917-bc357571-46f1-4091-b86b-b57d814b6096.mp4

This is a natural consequence of moving selection which just happens to be prepended by whitespace instead of other characters, so not sure if it deserves separate mention in help file.

> I did also find, that spaces <-> tabs conversion might lead to surprising behavior on line movement:

I am not sure what you think is surprising here. By default, [vertical linewise movement is reindented with `=`](https://github.com/echasnovski/mini.nvim/blob/8e007cf3ae8db59bd926a9fbaf7f0d25a7fe67ca/doc/mini-move.txt#L15). This is the effect I see here. As it doesn't always play nice with what user wants, there is an [option to disable it](https://github.com/echasnovski/mini.nvim/blob/8e007cf3ae8db59bd926a9fbaf7f0d25a7fe67ca/doc/mini-move.txt#L103-L104). Use it like this:

```lua
require('mini.move').setup({ options = { reindent_linewise = false } })
```

**Comment by echasnovski** [comment]
The 'mini.move' is now out of beta-testing after the release of version 0.7.0. Thank you all for your input!
