### ISSUE TITLE
Cannot find color scheme 'base16-custom'

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#2]
If I create a colorscheme using `mini.base16`, the plugin sets highlights and changes `g:colors_name`, but it doesn't actually register a colorscheme (selectable in `:colorscheme`). This causes Neovim's syntax loader to freak out:

```
Error detected while processing /usr/share/nvim/runtime/syntax/synload.vim:
line   19:
E185: Cannot find color scheme 'base16-custom'
```

In `base16.lua` on line 352, if I change `vim.g.colors_name = name or 'base16-custom'` to `vim.g.colors_name = nil`, this error goes away and nothing seems to break. However, there is probably a better way to do this.

**Comment by echasnovski** [comment]
Yeah, and it shouldn't show. The prerequisite is that for something to appear in `:colorscheme` is to have certain file inside any 'colors' folder in `runtimepath`. I've just learned that from `:h colorscheme` :)
So `name` field in `config` is actually useless. And your `vim.g.colors_name = nil` seems to be a reasonable solution. Thank you for this :)
Should be fixed now. Could you try it out?
