### ISSUE TITLE
mini.comment disrespects indentation with tabs

### ISSUE THREAD

**Issue by kmarius** [echasnovski/mini.nvim#20]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

Currently, `mini.comment` replaces indentation by tabs with the same number of spaces.

### Neovim version

0.6

### Steps to reproduce

1. `:set noexpandtab ts=4 sw=4 sts=0 nosmarttab`
2. In any buffer, type `<tab><tab>asdf`
3. Toggle comment twice.

### Expected behavior

The line `\t\tasdf`

### Actual behavior

The line `__asdf` where `_` is a space.

**Comment by echasnovski** [comment]
Thanks, reproduced in both Neovim 0.6.0 and 0.5.1. I'll look into this.

**Comment by echasnovski** [comment]
Should be fixed now.
