### ISSUE TITLE
Add 'folke/lazy.nvim' installation instructions

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#200]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

all

### Description

Add installation instructions for [folke/lazy.nvim](https://github.com/folke/lazy.nvim). Don't forget to add trailing comma for convenience and use `version = false` for `main` branch.

**Comment by ramgp** [comment]
Is there anything pending, from what I could see this is already addressed by [this commit](https://github.com/echasnovski/mini.nvim/commit/1c11d5fdb71c1d766545e42b0dd99eda50f1e349)?

**Comment by echasnovski** [comment]
Ah, yes. Forgot to close. Thanks!
