### ISSUE TITLE
mini.move separate repo does not have stable branch as readme says

### ISSUE THREAD

**Issue by NullVoxPopuli** [echasnovski/mini.nvim#201]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have updated 'mini.nvim' to latest version (irrelevant, I think? -- not using mini.nvim)

### Module(s)

echasnovski/mini.move

### Description

The separate git repo does not have a `stable` branch.

I can install from the default branch just fine, but the README says I stable branch should exist?

### Neovim version

NVIM v0.9.0-dev-629+gd89290b45

### Steps to reproduce

1. check github branches on repo: https://github.com/echasnovski/mini.move

### Expected behavior

stable branch exists

### Actual behavior

stable branch does not exist

**Comment by echasnovski** [comment]
Oh... thanks for the catch! Forgot about that.

Will fix it in the morning. It should still be considered in public beta-testing until new release of 'mini.nvim'.

**Comment by Isrothy** [comment]
mini.animate doesn't have a stable branch neither.
