### ISSUE TITLE
List of detected sessions can get stale when using multiple nvim instances

### ISSUE THREAD

**Issue by abdullatif-k** [echasnovski/mini.nvim#202]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini-session

### Description

Hello, 

So this is a pretty straightforward problem. When `mini-sessions` starts it takes a snapshot of the sessions directory in the setup. If afterwards you start another neovim instance, delete a session, then go back to the original instance you'll still see the deleted session show up with `require("mini.sessions").select()`. Or if you add a session, it won't be visible in the other instance. A simple solution would be to have the detected sessions refreshed before every operation. 

### Neovim version

NVIM v0.9.0-dev-678+g922075530

### Steps to reproduce

Open 2 Neovim instances, delete a session in one and use `require("mini.sessions").select()` in the other.

### Actual behavior

List of sessions not synchronized across instances.

**Comment by echasnovski** [comment]
> When `mini-sessions` starts it takes a snapshot of the sessions directory in the setup.

Yes, this is a design decision to simplify code. I think it might be added, but I am not sure if this is a huge problem. Do you feel this use case affects you frequently?

**Comment by abdullatif-k** [comment]
Admittedly it doesn't have a significant effect on usability, but I've caught myself several times opening sessions I've deleted. It's a marginal improvement, but I think it would take a marginal change to the code, wouldn't it? We'd run `detect_sessions` at the beginning of `write`,`delete`, and `select`.

But again, I like mini because of it's simplicity if you think it's giving up too much for too little that's fair.

**Comment by echasnovski** [comment]
> It's a marginal improvement, but I think it would take a marginal change to the code, wouldn't it? We'd run `detect_sessions` at the beginning of `write`,`delete`, and `select`.

Probably, yes. Plus tests for each one. I'll think about it.

**Comment by abdullatif-k** [comment]
If you decide to include it let me know, you don't have to do it yourself. I could open up a PR with the changes and the tests.

**Comment by echasnovski** [comment]
This should be now implemented in `main` branch.
