### ISSUE TITLE
mini.trailspace: trim empty lines at the beginning of a file

### ISSUE THREAD

**Issue by alex35mil** [echasnovski/mini.nvim#203]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.trailspace

### Description

Add a function or option to trim empty lines at the beginning of a file:

```
1 |
2 |
3 | foo
4 | bar
```

Lines 1 and 2 should be deleted.

**Comment by echasnovski** [comment]
Thanks for suggestion!

Probably not, as it is not aligned with 'mini.trailspace' and is essentially a single command:
```
vim.api.nvim_buf_set_lines(0, 0, vim.fn.nextnonblank(1) - 1, true, {})
```
