### ISSUE TITLE
Keep cursor fixed while commenting lines

### ISSUE THREAD

**Issue by UtkarshVerma** [echasnovski/mini.nvim#204]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

Currently, the cursor is moved to the beginning of the line while toggling the comment. Would it be possible to make the cursor stick to the character below it before commenting?

https://user-images.githubusercontent.com/31820255/212968048-c5aa31cd-b4a8-403a-82a8-3532c4320d95.mp4

**Comment by echasnovski** [comment]
Probably, not. The reasoning is essentially the same as in #191. I'll think about it, but I doubt it will happen.

**Comment by echasnovski** [comment]
I think I am going to close this because the current behavior is more in line with Neovim's behavior for operators. And it is a good thing.

Thanks for suggestion!
