### ISSUE TITLE
Beta-testing 'mini.basics'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#209]
Please leave your feedback about new [mini.basics](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-basics.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by oncomouse** [comment]
Just an FYI, [the mapping of `<C-W>` in terminal mode](https://github.com/echasnovski/mini.nvim/blob/d613f3be2bb215e62317e711ddc7196c969acf9e/lua/mini/basics.lua#L597) breaks the shortcut for delete word in TUI apps that use readline. I'm finding it pretty frustrating and wish there was a way to turn off that mapping.

**Comment by echasnovski** [comment]
> Just an FYI, [the mapping of `<C-W>` in terminal mode](https://github.com/echasnovski/mini.nvim/blob/d613f3be2bb215e62317e711ddc7196c969acf9e/lua/mini/basics.lua#L597) breaks the shortcut for delete word in TUI apps that use readline. I'm finding it pretty frustrating and wish there was a way to turn off that mapping.

Thanks for noticing. I've never really got to incorporate those into my workflow.

You can add `vim.keymap.del('t', '<C-w>')` **after** `require('mini.basics').setup()` call.

**Comment by echasnovski** [comment]
As I can see it being a common usage, I've [added this to help](https://github.com/echasnovski/mini.nvim/blob/4ae99890ebb8013c2d5c2526f768c3b685d276b3/doc/mini-basics.txt#L203-L208).

**Comment by echasnovski** [comment]
The 'mini.basics' is now out of beta-testing after the release of version 0.7.0. Thank you all for your input!
