### ISSUE TITLE
Add filetype option in each module's configuration

### ISSUE THREAD

**Issue by bart-jaskulski** [echasnovski/mini.nvim#21]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

All modules would be affected

### Description

It would be nice to enable only specific filetypes when using specified module. I think of something like packer.nvim does, when you can load plugin only for associated filetypes.

In my case, it occurs that I want to use `cursorword` for code files, not especially for markdown files.

Such config as below could be a possible outcome of feature implementation.

```lua
use {
  "echasnovski/mini.nvim",
  config = function()
    require'mini.cursorword'.setup({
      -- Launch this module only when filetype match
      ft = { 'js', 'php', 'py' }
    })
  end
}
```

I am aware this can be done by hitting module's enable/disable toggle, e.g. in `autocmd` but that solution would be cleaner in configuration in my opinion.

**Comment by echasnovski** [comment]
Thanks for your feedback!

I considered this early on, but decided to stick with current mechanism using global and buffer "disabling" variables. It enables quite flexible behavior while being very fast. Having settings specifically for filetypes will be either a duplication (which doesn't quite align with plugin idea of balancing between features and support) or separate mechanism which might slow things down (which is crucial for something that is executed on every CursorMoved). This also might be a precedent to include another conditions in `setup()`, which I don't really want. Currently I have strong opinion about this subject, but for the time being I'll keep this open as a reminder to try and reconsider.

What might be a more appropriate thing to do is to provide in help more explicit code snippets for most common scenarios. I just tried really quickly to implement your case (I admit, should be a quite common one) with `autocmd` and it is not trivial. This plugin is designed more towards "disable this module under these handful of conditions" and not "enable ... conditions", which might be a problem for not experienced users. I'll think about it.

**Comment by bart-jaskulski** [comment]
I see, in such case it may be more reasonable to rely on disabling for selected filetypes. Actually, the outcome is similar to desired.

```lua
  vim.cmd [[ autocmd BufReadPost *.md let b:minicursorword_disable=v:true ]]
```

I've been thinking for a moment on the setup for possible snippet and indeed this is more complex. The best, low effort idea I've came up with would be toggling global state of module, what itself just seems odd.

```lua
use {
  'echasnovski/mini.nvim',
  config = function()
    vim.g.minicursorword_disable = true
    require'mini.cursorword'.setup()
  end
}

  vim.cmd [[ autocmd BufReadPost *.md let g:minicursorword_disable=v:true ]]
  vim.cmd [[ autocmd BufReadPost *.php,*.js,*.html,*.css let g:minicursorword_disable=v:false ]]
```

**Comment by echasnovski** [comment]
In the end, I decided to leave writing these rules to user. There are examples for common situations in `mini.nvim-disabling-recipes` help tag.
Thanks for suggestion nevertheless!
