### ISSUE TITLE
Ctrl+u / Ctrl+d not working

### ISSUE THREAD

**Issue by MaximilianLloyd** [echasnovski/mini.nvim#212]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

When trying to use ctrl+d or ctrl+u to scroll half of the page, it scrolls to the current position.

### Neovim version

NVIM v0.9.0-dev-845+gfacbb11e0

### Steps to reproduce

1. `nvim .`
2. Try to use CTRL+d og CTRL+u

### Expected behavior

To scroll half of the page up / down.

### Actual behavior

It jumps up, then scrolls to the initial postition of your cursor.

Here is my configuration.

```lua
			-- don't use animate when scrolling with the mouse
			local mouse_scrolled = false
			for _, scroll in ipairs({ "Up", "Down" }) do
				local key = "<ScrollWheel" .. scroll .. ">"
				vim.keymap.set({ "", "i" }, key, function()
					mouse_scrolled = true
					return key
				end, { expr = true })
			end

			local animate = require("mini.animate")
			return {
				resize = {
					timing = animate.gen_timing.linear({ duration = 100, unit = "total" }),
				},
				scroll = {
					timing = animate.gen_timing.linear({ duration = 150, unit = "total" }),
					subscroll = animate.gen_subscroll.equal({
						predicate = function(total_scroll)
							if mouse_scrolled then
								mouse_scrolled = false
								return false
							end
							return total_scroll > 1
						end,
					}),
				},
				open = {
					enable = false
				},

				close = {
					enable = false
				}
			}
		end,
		config = function(_, opts)
			require("mini.animate").setup(opts)
		end,
```

**Comment by echasnovski** [comment]
What does `:nmap <C-u>` and `:nmap <C-d>` show? Judging by behavior it is something like `<C-u>zvzz`.

Unfortunately, limited centering after movement command is one of a downsides of asynchronous animation. With that keybinding it will tell Neovim to start animate scroll but then immediately tell to forget previous animation and start animating `zvzz`.

One possible way to overcome this is to use [`MiniAnimate.execute_after()`](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-animate.txt#L443) as shown in example. For `<C-u>`/`<C-d>` it would be something like this:

```lua
  vim.keymap.set(
    'n',
    '<C-d>',
    [[<Cmd>lua vim.cmd('normal! <C-d>'); MiniAnimate.execute_after('scroll', 'normal! zvzz')<CR>]]
  )
  vim.keymap.set(
    'n',
    '<C-u>',
    [[<Cmd>lua vim.cmd('normal! <C-u>'); MiniAnimate.execute_after('scroll', 'normal! zvzz')<CR>]]
  )
```

**But** it would often lead to jittering animations.

**Comment by MaximilianLloyd** [comment]
That was the issue for me as well! Closing now.

**Comment by MaximilianLloyd** [comment]
> > I got similar issue.
> 
> What does `:nmap <C-u>` and `:nmap <C-d>` show for you?

https://github.com/echasnovski/mini.nvim/pull/214 I created a pull request that adds a note for this issue, hope it is helpfull :)
