### ISSUE TITLE
[mini.align] Pattern "--" cannot advance search

### ISSUE THREAD

**Issue by farzadmf** [echasnovski/mini.nvim#216]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.align

### Description

I'm trying to align inline comments in a few Lua lines; something like this:
```lua
one = 'one' -- one
two = 'two-2' -- two
three = '3' -- three
```

### Neovim version

0.8.3

### Steps to reproduce

1. Select the 3 lines in visual mode
2. Go to interactive align mode
3. Type `s` to enter "split"
4. Type `--` and press `enter`
5. I get the error

### Expected behavior

I expect `--` to be treated as any other expression

### Actual behavior

I get the following error:

```
E5108: Error executing lua (mini.align) Pattern "--" can not advance search.
stack traceback:
        [C]: in function 'error'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:1940: in function 'error'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:1497: in function <...vim/my_lazy/data/n
vim/lazy/mini.align/lua/mini/align.lua:1466>
        vim/shared.lua: in function 'tbl_map'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:1459: in function 'action'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:1413: in function 'apply_step'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:672: in function 'align_strings'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:1657: in function 'process_current_regio
n'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:775: in function 'align_user'
        ...vim/my_lazy/data/nvim/lazy/mini.align/lua/mini/align.lua:813: in function 'action_visual'
```

**Comment by echasnovski** [comment]
To use "as is", you need to escape it. So type `%-%-`.

After typing `s`, it [expects Lua pattern](https://github.com/echasnovski/mini.nvim/blob/8e007cf3ae8db59bd926a9fbaf7f0d25a7fe67ca/doc/mini-align.txt#L21). The `-` character has a [special meaning](https://www.lua.org/manual/5.1/manual.html#5.4.1) - it is a non-greedy version of `*` quantifier (like `a-`will match 0 or more shortest possible matches).

**Comment by farzadmf** [comment]
Thank you @echasnovski for the SUPER fast response!

**Comment by farzadmf** [comment]
I did have another question @echasnovski if possible: I'm using [noice](https://github.com/folke/noice.nvim/), and the `mini.align` prompt appears as a notification on top, but when I press `s` and enter characters, they don't appear in the dialog box displayed by noice (when I press enter, they do appear in `mini.align` interactive prompt, so they _were_ picked up)

There are other plugins asking for input that cause `noice` to display that input dialog box, but what I type into them is reflected.

I was wondering if you could help me with that issue, and whether it's a noice issue or `mini.align`

**Comment by echasnovski** [comment]
> I did have another question @echasnovski if possible: I'm using [noice](https://github.com/folke/noice.nvim/), and the `mini.align` prompt appears as a notification on top, but when I press `s` and enter characters, they don't appear in the dialog box displayed by noice (when I press enter, they do appear in `mini.align` interactive prompt, so they _were_ picked up)
> 
> There are other plugins asking for input that cause `noice` to display that input dialog box, but what I type into them is reflected.
> 
> I was wondering if you could help me with that issue, and whether it's a noice issue or `mini.align`

It does seem to be a 'noice.nvim' issue. I created folke/noice.nvim#347 with minimal reproducible steps.

Just yo be sure: you experience this only when aligning is invoked in Visual mode? Like if you place cursor on some text, type `gAip` (align interactively inner paragraph), and then press `s`, you can see keys pressed?

**Comment by farzadmf** [comment]
Thank you so much @echasnovski for creating that issue; sorry, I maybe should have created a separate issue for that in here (usually whenever these things happen, it's something I messed up so I'm always like "for sure it's my fault" 🙂)

But yeah, you're correct, it does happen when selecting visually

And, another weird thing that I've seen is that sometimes the mini.align prompt (the "split: ...  | justify: ..." message) doesn't even appear at all (but things work if I press keys), but that may be another story 🤔

**Comment by echasnovski** [comment]
> And, another weird thing that I've seen is that sometimes the mini.align prompt (the "split: ... | justify: ..." message) doesn't even appear at all (but things work if I press keys), but that may be another story thinking

With "mini" display in 'noice.nvim' they always appeared in right bottom side of screen. Even if they don't, that is most probably coming from 'noice.nvim'.

**Comment by farzadmf** [comment]
> With "mini" display in 'noice.nvim' they always appeared in right bottom side of screen

Oh wait, what do you mean by this? Is there an additional setting that I missed? Because for me, they appear in the top right (similar to other "notifications" but they're just "sticky" and stay there)

**Comment by echasnovski** [comment]
> > With "mini" display in 'noice.nvim' they always appeared in right bottom side of screen
> 
> Oh wait, what do you mean by this? Is there an additional setting that I missed? Because for me, they appear in the top right (similar to other "notifications" but they're just "sticky" and stay there)

In your case they come from [rcarriga/nvim-notify](https://github.com/rcarriga/nvim-notify). I tested with minimal dependencies without it, in which case [`mini` view](https://github.com/folke/noice.nvim#-views) is used (as per [documentation](https://github.com/folke/noice.nvim#-installation)). To force it for a particular part of config, I think you should use `view = 'mini'` inside its configuration table. Something like this, maybe:

```lua
require('noice').setup({
  messages = { view = 'mini' },
})
```

**Comment by farzadmf** [comment]
Nice, thank you very much @echasnovski , that looks much better! Hopefully there'll be an update for the issue in noice 🤞
