### ISSUE TITLE
mini.pairs: Temporarily cancel / disable auto pairing

### ISSUE THREAD

**Issue by cassava** [echasnovski/mini.nvim#217]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

I couldn't find an issue or discussion for this. How do you approach situations where you don't want auto pairing to get in the way, just temporarily? I feel like I'm missing something.

**Use Case 1:**
Lets say I have a block of Lua code I want to comment out and I want to do it by hand.
When using `mini.pairs`, it's kinda frustrating to type `--[==[` on a line because I get `--[==[]]`.

**Use Case 2:**
I realize I'm missing a quote on a word and just want to insert a single quote at the beginning/end.
But each time, the second quote is inserted, and removed when I backspace.

**Available Solutions:**
1. Use `<C-V>` before typing each character
2. Use DEL key after typing each character
3. Exit insert mode, and delete extra characters

**Suggestion:**
Would it make sense to provide a binding that for example disables autopair until leaving insert mode?

**Comment by cassava** [comment]
If you feel this is outside the scope of `mini.pairs`, then that's fine; I thought it would be useful to have the topic documented somewhere at least.

**Comment by echasnovski** [comment]
> 1. Use `<C-V>` before typing each character

Why is this not an appropriate solution? This is the one I use, as this happens not that often.

Of course, there is also a common way of disabling all 'mini.nvim' modules: [via `vim.g.minixxx_disable` and `vim.b.minixxx_disable`](https://github.com/echasnovski/mini.nvim/blob/33e76b0c22465de03906ebd00c01b64a04e495b3/doc/mini-pairs.txt#L69) variables.

You can, for example, make this mapping to toggle autopairing:

```lua
vim.keymap.set('i', '<M-m>', '<Cmd>lua vim.g.minipairs_disable = not vim.g.minipairs_disable<CR>')
```

Choose mode, key, and global/buffer-local variable for you liking.

Does this solve your issue?

**Comment by cassava** [comment]
I guess part of me was wondering how others deal with this situation. Thanks for your input! This does work, and it should also be pretty trivial to create an autocommand via keymap that then deletes itself.

**Comment by cassava** [comment]
This is the (`lazy.nvim`) configuration I'm using now:

```lua
  {
    "echasnovski/mini.pairs",
    event = "VeryLazy",
    config = function(_, opts)
      require("mini.pairs").setup(opts)

      vim.api.nvim_set_keymap("i", "<c-v>", "<c-v>", {
        silent = true,
        noremap = true,
        desc = "Temporarily disable auto-pairing",
        callback = function()
          vim.g.minipairs_disable = true
          vim.api.nvim_create_autocmd("InsertLeave", {
            callback = function()
              vim.g.minipairs_disable = false
              return true
            end
          })
        end
      })
    end,
  }
```

**Comment by echasnovski** [comment]
> Edit: that is, I'd like to use `<c-v>`, but I'm not sure how to not mask the original `<c-v>` whilst doing so.

This is an almost perfect example of expression mappings. Those are first execute right hand side expression which should return an eventually needed value of right hand side. You can use it to first execute some of your code and then return `<C-v>`. Like this:

```lua
vim.keymap.set('i', '<C-v>', function()
  vim.g.minipairs_disable = true
  vim.cmd('au InsertLeave * ++once let g:minipairs_disable = v:false')
  return '<C-v>'
end, { silent = true, expr = true })
```

Yes, this code does have some Vimscript, but it has less nesting, so is better to me :)
