### ISSUE TITLE
is_truncated should respect laststatus config

### ISSUE THREAD

**Issue by leaxoy** [echasnovski/mini.nvim#218]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

When set laststatus to 3, the statusline is global, not per window, so whether truncate should respect this config, when set to 3, prefer use vim.opt.columns than winwidth.

**Comment by echasnovski** [comment]
Yes, you're right. I'll look into the most efficient way of doing this.

**Comment by echasnovski** [comment]
> I rewrite it in my local machine as belows:
> 
> ```lua
> local origin = MiniStatusline.is_truncated
> ---@diagnostic disable-next-line: duplicate-set-field
> function MiniStatusline.is_truncated(trunc_width)
>   if vim.o.laststatus == 3 then return vim.o.columns < (trunc_width or -1) end
>   return origin(trunc_width)
> end
> ```

Of course, updating `is_truncated()` is a most straightforward solution. But it implies that checking for `laststatus = 3` is done for every section which is suboptimal. Not sure if squeezing this optimization would be worth it, but I'll look into it.

This is a more streamlined version:
```lua
MiniStatusline.is_truncated = function(trunc_width)
  -- Use -1 to default to 'not truncated'
  local cur_width = vim.o.laststatus == 3 and vim.o.columns or vim.api.nvim_win_get_width(0)
  return cur_width < (trunc_width or -1)
end
```

I'll look into it soon.

**Comment by echasnovski** [comment]
Should be fixed now in `main`.

In the end, it didn't seem worth the complications, so I used the one from previous comment.
