### ISSUE TITLE
mini.identscope animation not shown after 1st install

### ISSUE THREAD

**Issue by Shinzu** [echasnovski/mini.nvim#220]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

indentscope

### Description

hello,

after installing indentscope (with lazy) together with indent-blackline the animation for the indent is only shown once on the first restart, after i quit and start nvim again i see the indent from indent-blankline but not the animation from indentscope.

relevant part of lazy config:
```
  {
    "lukas-reineke/indent-blankline.nvim",
    event = "BufReadPost",
    opts = {
      char = '┊',
      filetype_exclude = { "help", "alpha", "dashboard", "neo-tree", "Trouble", "lazy" },
      show_trailing_blankline_indent = false,
      -- space_char_blankline = " ",
      show_current_context = false,
      -- show_current_context_start = true,
    }
  },
  {
    "echasnovski/mini.indentscope",
    event = "BufReadPre",
    opts = {
      -- symbol = "▏",
      symbol = "┊",
      options = { try_as_border = true },
    },
    config = function(_, opts)
      vim.api.nvim_create_autocmd("FileType", {
        pattern = { "help", "alpha", "dashboard", "neo-tree", "Trouble", "lazy", "mason" },
        callback = function()
          vim.b.miniindentscope_disable = true
        end,
      })
      require("mini.indentscope").setup(opts)
    end,
  },
```

When i deinstall indent-blankline and install it again (with restart in between) on the first start with both enabled i see the animation , but after a restart it is "broken" again.

### Neovim version

NVIM v0.9.0-dev

### Steps to reproduce

1. install indentscope together with indent-blankline 
2. restart nvim
3. animation is shown
4. restart nvim
5. animation is not shown

### Expected behavior

animation is shown 

### Actual behavior

animation is not shown on second start with both indentscope and indent-blankline enabled

first start after install

![image](https://user-images.githubusercontent.com/1894476/217049796-867646df-ad0d-4c53-b310-7fb8864abee8.png)

second start

![image](https://user-images.githubusercontent.com/1894476/217049876-e345014c-344f-479d-9bbc-eafedbcda5b5.png)

**Comment by echasnovski** [comment]
Hi!

Hmmm... I am not sure what to tell you here, as it doesn't look like 'mini.indentscope' issue, but rather how you install it. I can not reproduce this if installed using built-in packages (manually clone into some `pack/*/opt` and execute `:packadd`).

Here are first steps i'd take to debug this:
- What does executing `:lua print(MiniIndentscope)` show? It should show something like `table: 0x...`. If not (like `nil`), probably `setup()` function is somehow not called.
- What does executing `:au MiniIndentscope` show? It should show several autocommands calling `MiniIndentscope.auto_draw()`. If not, again `setup()` was not called properly or autocommands got deleted.

**Comment by Shinzu** [comment]
Will have a look later, thanks for the suggestions

**Comment by Shinzu** [comment]
i got a table back with the 1st command

i get also au back

![image](https://user-images.githubusercontent.com/1894476/217092852-f2a51a88-20ab-4113-a1d3-6a754816cadc.png)

are there any missing?

**Comment by echasnovski** [comment]
> are there any missing?

Nope, all seems good.

------

Here are other possible causes:
1) What does `:lua print(vim.g.miniindentscope_disable)` and `:lua print(vim.b.miniindentscope_disable)` show? They should be either `nil` or `false`. If `true`, it means it is disabled somewhere.
2) What does `:hi MiniIndentscopeSymbol show? It should not be cleared.

**Comment by Shinzu** [comment]
found the error in my config

it is based on [LazyVim](https://github.com/LazyVim/LazyVim) and in https://github.com/LazyVim/LazyVim/blob/edd0fbb6a10f1a6fbcf12de92c20f430ea1bbc89/lua/lazyvim/plugins/ui.lua#L248 it seems to be disable miniindentscope.

thank you for you help.

**Comment by echasnovski** [comment]
Great it is solved.

That source line, though, should only disable 'mini.indentscope' in current buffer. It should have worked in other buffers.

**Comment by Shinzu** [comment]
yes, seems like while opening a file directly via `nvim <filename>` it gets disabled, when opening a file over alpha it works as indented.
