### ISSUE TITLE
mini.ai - using textobject auto closes cmdline window

### ISSUE THREAD

**Issue by skippi** [echasnovski/mini.nvim#223]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Using either the `i` or `a` textobjects in the cmdline window (`q:`, `q/`, `q?`) will abruptly close said window. I believe the cause is in [this function](https://github.com/echasnovski/mini.nvim/blob/0e82cef370ffd355815a5159307c7b74382ff657/lua/mini/ai.lua#L1908), in particular the `<C-\><C-n>` sequence. Perhaps `<Esc>` or `<C-c>` would suffice?

### Neovim version

v0.9.0-dev-883+g1391385ba

### Steps to reproduce

1. Open the command line window via `q:`.
2. Insert `(hello)` into an open line.
3. Position cursor inside the parenthesis. Use `vi(` in normal mode.

Note that this can be reproduced with any built in textobject. If performing a change (EG: `ci(`), nvim will enter insert mode, but will exit the cmdline window as soon as the user returns to normal mode.

### Expected behavior

The cmdline window shouldn't close after using `mini.ai` textobject.

### Actual behavior

The cmdline window abruptly closes.

**Comment by echasnovski** [comment]
Yes, you are right. Rarely use command-line window myself, so didn't notice this earlier.

I'll fix this soon (probably tomorrow).

**Comment by echasnovski** [comment]
Should be fixed now in `main`.

Thanks again for noticing!
