### ISSUE TITLE
Optional indexing from zero

### ISSUE THREAD

**Issue by haoming-li-ling** [echasnovski/mini.nvim#225]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Starter

### Description

At present, the 1-based indexing means that one needs two keystrokes to access the first file in the recent file list if there are more than 10 files listed, since multiple files will start with 1 in the index. If 0-based indexing is available, one can access the first file in the list with just one keystroke since only that file starts with 0 in the index, which is going to be more convenient.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Do you feel like using 9 files instead of 10 would be enough for you?

It certainly is doable, but at the moment I am not sure if it will be much better than having 9 files instead of 10.

**Comment by adrian5** [comment]
In my own alpha.nvim config I use 1 through 9, I think that's a sensible tradeoff.

**Comment by echasnovski** [comment]
Yes, I think using 9 files instead of 10 to always have single key navigation is a reasonable compromise here.

Thanks for suggestion!
