### ISSUE TITLE
Different color for indent guide not matching tab width

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#226]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

Make scope's vertical line to be different (attention-seeking) color when current scopes indent doesn't align with tab width.

This is a compromise to #65 and #99.

**Comment by ABlueDruid** [comment]
How do I apply it? I can't make it work.

**Comment by echasnovski** [comment]
Here is [the name of the highlight group](https://github.com/echasnovski/mini.nvim/blob/c404fc5717866ff738aadeeb1f54ab8ed270ae1e/doc/mini-indentscope.txt#L60-L62).

Add something like this to the config: `vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbolOff', { link = 'DiagnosticWarn' })`. Choose highlight group attributes or linked built-in highlight group to your liking.
