### ISSUE TITLE
mini.animate prevents <C-D>zz from centering when at top/end of file

### ISSUE THREAD

**Issue by zolrath** [echasnovski/mini.nvim#228]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

With <C-d> and <C-u> rebound to <C-d>zz and <C-u>zz scrolling does not function properly.

Depending on the version of neovim this problem has two variants:

## 0.8.3
When I press <C-d> in the center of a file, everything works great. But if you are at the very top/bottom of a file the first `<C-d>` will not center the screen. The next press will attempt to scroll, fail, jump back to the current position, but this time with the screen centered. Continuing down will now succeed for the rest of the file.

## 0.9.0
`<C-d>` and `<C-u>` fail, always returning to the original cursor position.

### Neovim version

0.8.3 and nightly 0.9.0-dev-857+g2c5906b55

### Steps to reproduce

1. Rebind <C-d> and <C-u> to center the buffer with zz
````
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
````
2. Hit C-d at the top of a long file.
3. Hit C-u at the bottom of a long file.

### Expected behavior

The buffer should scroll down and center the screen when <C-d> is pressed from the top of a file.
Alternatively, it should scroll up and center the screen when <C-u> is pressed from the bottom of a file.

## 0.8.3
The buffer scrolls down but does not center the screen. The next time <C-d> is pressed the screen starts to scroll down, then jerks back up and ends up with the cursor back at the same location, but the buffer is now centered. After this point, scrolls succeed as normal.

https://user-images.githubusercontent.com/454563/218840867-888d99e6-e8c8-40dc-99d5-2b01a297eb18.mp4

## 0.9.0
The screen scrolls but snaps back and the cursor returns to the original position. If you rapidly press <C-d> and get the command in before the buffer scrolls down to 1, you successfully scroll *a bit*.

https://user-images.githubusercontent.com/454563/218840823-580471b1-e448-4a7c-85a0-b1c8b1b179b4.mp4

**Comment by echasnovski** [comment]
Thanks for a detailed issue!

It seems like symptoms of asynchronous nature of scroll. When you execute `<C-d>zz` mapping, what happens is Neovim registers `<C-d>` and 'mini.animate' starts scroll animation (which also progressively changes cursor position for a smoother effect). **But** right after it start animating, there is a `zz` command which is registered as another scroll event which takes precedence (thus trying to center the screen).

Unfortunately, having multiple scrolling commands in a mapping is not really supported. The best way to overcome this right now is by following [this advice](https://github.com/echasnovski/mini.nvim/issues/212#issuecomment-1411674528). Could you try remapping it as written there and tell if this makes things better?

**Comment by zolrath** [comment]
Ah, not sure how I missed that issue, thanks!

Adding the execute_after version did solve my problem.

```lua
  vim.keymap.set(
    'n',
    '<C-d>',
    [[<Cmd>lua vim.cmd('normal! <C-d>'); MiniAnimate.execute_after('scroll', 'normal! zvzz')<CR>]]
  )
  vim.keymap.set(
    'n',
    '<C-u>',
    [[<Cmd>lua vim.cmd('normal! <C-u>'); MiniAnimate.execute_after('scroll', 'normal! zvzz')<CR>]]
  )
  ```

Given how common the `<C-d>zz` rebind is maybe explicitly using this remap as an example in a section after **Installation** in the readme for **Remapping animated commands** or something of that nature would help future users.

Thanks again!

**Comment by echasnovski** [comment]
> Adding the execute_after version did solve my problem.

Great!

> Given how common the `<C-d>zz` rebind is maybe explicitly using this remap as an example in a section after **Installation** in the readme for **Remapping animated commands** or something of that nature would help future users.

This is already in the help file. But as you are not the first one with this kind of problem (and solution, even), this might be a good idea.

Closing then.
