### ISSUE TITLE
mini.surround when using config from help file

### ISSUE THREAD

**Issue by LandonSchropp** [echasnovski/mini.nvim#231]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

The vim-surround config from the mini.surround help file produces an error for me.

### Neovim version

0.8.3

### Steps to reproduce

I'm using Lazy.nvim, and here's my mini.surround config, pulled from the mini.surround [help file](https://github.com/echasnovski/mini.surround/blob/main/doc/mini-surround.txt):

```
return {
  "echasnovski/mini.surround",
  opts = {
    mappings = {
      add = "ys",
      delete = "ds",
      find = "yf",
      find_left = "yF",
      highlight = "vs",
      replace = "cs",
      update_n_lines = "",
    },
    search_method = "cover_or_next",
  },
  config = function(_, opts)
    require("mini.surround").setup(opts)
  end,
}
```

### Expected behavior

The editor should start without an error.

### Actual behavior

When I start Neovim, I get the following error:

```
Failed to setup handlers for mini.surround

vim/keymap.lua:0: Invalid (empty) LHS

# stacktrace:
  - vim/keymap.lua:0 _in_ **set**
```

If I comment out the `update_n_lines = "",`, it works fine.

**Comment by echasnovski** [comment]
I can not reproduce this without LazyVim. It seems to be the way it either lazy loads it or sets up 'which-key.nvim'. Created a LazyVim/LazyVim#296 for this.
