### ISSUE TITLE
mini.surround  automatically select the current cursor character

### ISSUE THREAD

**Issue by xuliefeng** [echasnovski/mini.nvim#232]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

hi,Hello. Hello, is it possible to automatically obtain the current cursor character during operation? For example, sr'" No need to manually input ', directly input the character to be replaced

**Comment by echasnovski** [comment]
Hello, hi!

Do you mean like in case of `"('hello world')"` and cursor on first `'` you would like to `type sr"` in order to immediately get `"("hello world")"`?

If yes, what is your expectation to when user wants in this exact initial situation replace the outer `"` with `]`?

**Comment by xuliefeng** [comment]
Hmm, I see what you mean. This is different from everyone's habits. Personally, I like to find the character that needs to be replaced first, and then operate on that place. So I hope to provide a configuration to automatically select whether to automatically operate the character under the current cursor

**Comment by echasnovski** [comment]
> Well, I understand what you mean. It's different with everyone's habits. I personally like to find the character that needs to be replaced first and replace it there. So I expect you to consider whether to provide a configuration to automatically select whether to automatically manipulate the character under the current cursor

With current approach there is no need to manually find which surrounding will be replaced. It is taken care of by appropriate searching of surrounding user wants to replace.

The approach of automatically inferring surrounding id with character under cursor leads to plenty of problems down the road. Besides mentioned use case earlier, it disables possibility to replace surrounding with more than a single character parts (like function call, tag, etc.).

So no, unfortunately, I don't see this as a part of 'mini.surround'.

**Comment by xuliefeng** [comment]
Ok, thanks for your reply. Thanks again for such a great plugin, cheers

**Comment by szechp** [comment]
you could try https://github.com/machakann/vim-sandwich, which does that automatically. its vor vim, but it works in neovim too

**Comment by echasnovski** [comment]
> you could try https://github.com/machakann/vim-sandwich, which does that automatically. its vor vim, but it works in neovim too

Well, not exactly. It seems to have a special `srb` mapping for that which finds the closest surrounding.
