### ISSUE TITLE
mini.cursorword - highlight group is cleared after `hi clear`

### ISSUE THREAD

**Issue by jemag** [echasnovski/mini.nvim#239]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cursorword

### Description

Currently mini.cursorword seems to define its highlighting in the setup function: https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/cursorword.lua#L123-L127

This means that the highlighting will be cleared if a colorscheme is loaded afterwards:
![image](https://user-images.githubusercontent.com/7985687/221374082-fe2a0454-1d68-4afa-8f30-609184b0bc04.png)

My suggestion would be to go with the common plugin pattern of setting those highlight in a `ColorScheme` autocmd to prevent this problem.

**Comment by echasnovski** [comment]
Thank you for the issue!

Hmm... This seems to affect all highlight groups which are defined with `hi default ...` and not `hi default link`.

However, using only `ColorScheme` event seems to be not enough: what if color scheme without `MiniCursorword` highlight group definition is loaded *before* 'mini.cursorword'? Then no 'MiniCursorword' highlight group will be created at all.

I'll think about the best solution.

In the meantime, please consider using one of these approaches:
- Load color scheme first. It seems like a good idea anyway: load color scheme before everything else.
- Define manually `MiniCursorword` highlight group in `ColorScheme` event.
- Add 'mini.nvim' integration in the color scheme you are using. The best option, if you'd ask me :)

**Comment by jemag** [comment]
Sorry I should have been clearer, I believe usually the pattern is to define your highlight in a function that you can call initially as usual. However, in addition to that, you have the `ColorScheme` autocmd that ensure that they do not get cleared. 

At least that seems to be the way that I have seen it done in most popular plugins.
Don't have time to look at a lot of examples, but of the top of my head:
https://github.com/folke/noice.nvim/blob/d8a1f3056ad713b5d471048f8d029264828e22c0/lua/noice/config/init.lua#L253-L258
https://github.com/lewis6991/gitsigns.nvim/blob/f388995990aba04cfdc7c3ab870c33e280601109/lua/gitsigns.lua#L462

**Comment by echasnovski** [comment]
> Sorry I should have been clearer, I believe usually the pattern is to define your highlight in a function that you can call initially as usual. However, in addition to that, you have the `ColorScheme` autocmd that ensure that they do not get cleared.
> 
> At least that seems to be the way that I have seen it done in most popular plugins. Don't have time to look at a lot of examples, but of the top of my head: https://github.com/folke/noice.nvim/blob/d8a1f3056ad713b5d471048f8d029264828e22c0/lua/noice/config/init.lua#L253-L258 https://github.com/lewis6991/gitsigns.nvim/blob/f388995990aba04cfdc7c3ab870c33e280601109/lua/gitsigns.lua#L462

Sure, sure. It is just not that big of an issue with most modules, because highlight groups are usually defined with `hi default link` which doesn't get cleared. I've just missed the ones which are defined explicitly without linking.

**Comment by echasnovski** [comment]
This should be fixed now on `main` branch for all modules.

Thanks again for the great catch!
