### ISSUE TITLE
(mini.sessions) Telescope extension

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#24]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions

### Description

Consider implementing Telescope extension which allows to list and read session files.

**Comment by JoseConseco** [comment]
Hi I made nvim session picker that works with mini.sessions  (it works with all nvim session made with mksession).
 Link: https://github.com/JoseConseco/telescope_sessions_picker.nvim

Its very basic - only allows to open session file ( `:so  session_path'). Should work with most  session managers.

**Comment by echasnovski** [comment]
Thanks for the pointer! I'll look at it, when solving #24.

**Comment by echasnovski** [comment]
I opted into creating `MiniSessions.select()` which utilizes `vim.ui.select()` (initially designed to be overridable). To use Telescope for picking sessions, consider [stevearc/dressing.nvim](https://github.com/stevearc/dressing.nvim) plugin.
