### ISSUE TITLE
mini.base16: Syntax highlighting in diffs

### ISSUE THREAD

**Issue by David-Kunz** [echasnovski/mini.nvim#240]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.base16

### Description

Hi 👋 ,

Thank you for these great plugins!

Once thing I miss in [mini.base16]([mini.base16](https://github.com/echasnovski/mini.base16)) is **syntax highlighting** in diffs.

Consider this example in [tokyonight](https://github.com/folke/tokyonight.nvim):
![Screenshot 2023-02-26 at 11 54 02](https://user-images.githubusercontent.com/1009936/221406124-81674716-8255-4507-9a86-a8a91b3c45a7.png)

Now the same in [mini.base16](https://github.com/echasnovski/mini.base16):
![Screenshot 2023-02-26 at 11 54 53](https://user-images.githubusercontent.com/1009936/221406181-f5bda154-968c-4fe4-9146-4e5f80171673.png)

In [tokyonight](https://github.com/folke/tokyonight.nvim), syntax highlighting is still active, e.g. for additions. In [mini.base16](https://github.com/echasnovski/mini.base16), it's just green text.

Would it be possible to keep syntax highlighting in diffs and only change the background of additions/substractions/changes?

Thanks again and best regards,
David

**Comment by echasnovski** [comment]
Thanks for the issue!

Hmm... I'll take a look, but at first sight I somewhat like the current behavior, makes it more visible. Another thing to consider is that 'mini.base16' is intended to be as much a reimplementation of original, Vim's base16, so they might conflict.

**Comment by David-Kunz** [comment]
Thanks for looking into it, @echasnovski! Having syntax highlighting helps me to better read the difference, especially for larger code blocks, it's not as intrusive as painting everything in a green color and is closer to the original code.

**Comment by echasnovski** [comment]
Yeah, this is indeed a severe limitation of 'base16'. All "colorful colors" are intended to be used as foreground. For background there are simply 4 shades available. There is simply not enough colors to both preserve original syntax highlighting and and make background green/red/purple, as this might lead to same colors for text and background.

Lack of shades in colors (both accent ones and darker shades of background) is the main reason why I plan to make 'mini.base3' (name can vary) - my own color scheme generator where I can make any shades I want.

The only solution to this is to switch background to be colorful instead. This will not preserve highlighting, unfortunately. Here is how it will look:

![screenshot_2023-02-26_13:48:55](https://user-images.githubusercontent.com/24854248/221409019-6fdbfef6-fa17-42a5-92ce-1e1a5879efa2.png)

What do you think about this?

**Comment by David-Kunz** [comment]
> Lack of shades in colors (both accent ones and darker shades of background) is the main reason why I plan to make 'mini.base3' (name can vary)

This is great, can't wait for this!

> The only solution to this is to switch background to be colorful instead. 

I think depending on the color scheme, it might be too bright/intrusive.

My initial thought was to take the given background color of mini.base16 (`base00`) and slightly modify it to make it more red/green/yellow. But I'm not sure if that would work.

**Comment by echasnovski** [comment]
> I think depending on the color scheme, it might be too bright/intrusive.

Agree.

> My initial thought was to take the given background color of mini.base16 (`base00`) and slightly modify it to make it more red/green/yellow. But I'm not sure if that would work.

Yes, it would be great and this is what I plan to do in my own color scheme generator. But this can't be part of 'mini.base16', unfortunately, because it would mean creation of a color outside of supplied palette.

So I think I'll close it with a promise to use your suggestion in an upcoming original color scheme generator in some near-ish future.

Thanks for your interest and promotion of 'mini.nvim'.

**Comment by David-Kunz** [comment]
Awesome, thank you! ❤️

**Comment by echasnovski** [comment]
By the way, @David-Kunz, I forgot to write here after I released new color scheme: [mini.hues](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-hues.md). Making sure that diffs highlight only background was one of the first things I did when started tweaking highlight groups :)

Here are some examples of diffs using 'randomhue' color scheme:

![demo_mini-hues_diff_1](https://github.com/echasnovski/mini.nvim/assets/24854248/532779cc-18cc-4fbb-84fe-14e6886d5e27)
![demo_mini-hues_diff_2](https://github.com/echasnovski/mini.nvim/assets/24854248/7966e346-68f4-4105-b75f-be77858b09b3)
![demo_mini-hues_diff_3](https://github.com/echasnovski/mini.nvim/assets/24854248/5e9dbd69-ff26-4ded-b8c1-295436e2fdb5)

Granted, background is not always clearly differentiable, but it is not always easy to procedurally generate very different background color. Like `DiffAdd` will have green background which can't be *very* different from already green `Normal` background (but it is as different as it reasonably can be).

**Comment by David-Kunz** [comment]
Hi @echasnovski ,

That's awesome, thanks for the pointer, I will definitely check it out! 👍 

Btw:
Thanks to your `base16` plugin, I could style my Neovim to match the SAP colors, here an excerpt from the SAP Sapphire Keynote: https://youtu.be/YwXWoa1srkk?t=836
