### ISSUE TITLE
[Question] mini.completion, insert variables?

### ISSUE THREAD

**Issue by vihu** [echasnovski/mini.nvim#241]
I had been using nvim-cmp for a while and thought to give mini.completion a go for simplicity sake. Here's my configuration (using lazy.nvim):

```lua
return {
    "echasnovski/mini.completion",
    config = function()
        require('mini.completion').setup()

        Imap('<Tab>', [[pumvisible() ? "\<C-n>" : "\<Tab>"]], { noremap = true, expr = true })
        Imap('<S-Tab>', [[pumvisible() ? "\<C-p>" : "\<S-Tab>"]], { noremap = true, expr = true })
        local keys = {
            ['cr']        = vim.api.nvim_replace_termcodes('<CR>', true, true, true),
            ['ctrl-y']    = vim.api.nvim_replace_termcodes('<C-y>', true, true, true),
            ['ctrl-y_cr'] = vim.api.nvim_replace_termcodes('<C-y><CR>', true, true, true),
        }
        _G.cr_action = function()
            if vim.fn.pumvisible() ~= 0 then
                -- If popup is visible, confirm selected item or add new line otherwise
                local item_selected = vim.fn.complete_info()['selected'] ~= -1
                return item_selected and keys['ctrl-y'] or keys['ctrl-y_cr']
            else
                -- If popup is not visible, use plain `<CR>`. You might want to customize
                -- according to other plugins. For example, to use 'mini.pairs', replace
                -- next line with `return require('mini.pairs').cr()`
                return keys['cr']
            end
        end
        Imap('<CR>', 'v:lua._G.cr_action()', { noremap = true, expr = true })
    end
}
```

I am not exactly sure why (and it could be something silly on my part) but whenever I do tab completion, I get $0, $1 etc (which I don't really need). For example:

![mini-completion-issue](https://user-images.githubusercontent.com/3199183/221432249-d7f6931c-887b-43b4-a3fc-0edf06a2e801.gif)

I'd really appreciate if you could point me in the right direction to not have the $* show up in completion. Thanks!

**Comment by echasnovski** [comment]
These are the artifacts describing snippets. It seems that LSP server provides that entry described as "Function fr...", but it should be described as "Snippet" (or I have an outdated knowledge of LSP specification). This seems similar to #193.

One downside of 'mini.completion' is that it (maybe yet) doesn't support expanding LSP snippets. And it probably never will. I think that most people are using only a handful of snippets which are better off with setting up manually.  #180 has some good advice on this.

I'll close it as similar to #193.

Thanks for trying out 'mini.completion'. Hope you'll stay for it or other modules :)
