### ISSUE TITLE
Remap adding surrounding to Visual mode selection fails

### ISSUE THREAD

**Issue by thepenguinthatwants** [echasnovski/mini.nvim#245]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

I get this error when I try the mapping  mentioned in
https://github.com/echasnovski/mini.nvim/blob/ee7c02297cf95cba07f8bf8da3ecf99337a1c15e/doc/mini.txt#L4252

`  vim.api.nvim_set_keymap('x', 'S', [[:<C-u>lua MiniSurround.add('visual')<CR>]], { noremap = true })`
The error is

E5108: Error executing lua [string ":lua"]:1: attempt to index global 'MiniSurround' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

### Neovim version

NVIM v0.8.3

### Steps to reproduce

When I remove all other plugins and only having mini plugins. I still get this behaviour when using lazy to install this.

```
return {
  "echasnovski/mini.surround",
  keys = function(_, keys)
    -- Populate the keys based on the user's options
    local plugin = require("lazy.core.config").spec.plugins["mini.surround"]
    local opts = require("lazy.core.plugin").values(plugin, "opts", false)
    local mappings = {
      { opts.mappings.add, desc = "Add surrounding", mode = { "n", "v" } },
      { opts.mappings.delete, desc = "Delete surrounding" },
      { opts.mappings.find, desc = "Find right surrounding" },
      { opts.mappings.find_left, desc = "Find left surrounding" },
      { opts.mappings.highlight, desc = "Highlight surrounding" },
      { opts.mappings.replace, desc = "Replace surrounding" },
      { opts.mappings.update_n_lines, desc = "Update `MiniSurround.config.n_lines`" },
    }
    mappings = vim.tbl_filter(function(m)
      return m[1] and #m[1] > 0
    end, mappings)
    return vim.list_extend(mappings, keys)
  end,
  opts = {
    mappings = {
      add = "gza", -- Add surrounding in Normal and Visual modes
      delete = "gzd", -- Delete surrounding
      find = "gzf", -- Find surrounding (to the right)
      find_left = "gzF", -- Find surrounding (to the left)
      highlight = "gzh", -- Highlight surrounding
      replace = "gzr", -- Replace surrounding
      update_n_lines = "gzn", -- Update `n_lines`
    },
  },
  config = function(_, opts)
    -- use gz mappings instead of s to prevent conflict with leap
    require("mini.surround").setup(opts)
  end,
}
```

### Expected behavior

It should work just like surround.vim plugin and let me add surrounds after visually selecting text.

### Actual behavior

E5108: Error executing lua [string ":lua"]:1: attempt to index global 'MiniSurround' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

**Comment by echasnovski** [comment]
It looks like you try to use `S` mapping here before `require('mini.surround').setup()` is called. The `MiniSurround` is a table in global namespace equivalent to `require('mini.surround')` and it created for easier mappings.

I recommend making sure that your `S` mapping is not used before setting up 'mini.surround'. Also using `[[:<C-u>lua require('mini.surround').add('visual')<CR>]]` *should* work, but it is not guaranteed.

Notes:
- It is better now to use `vim.keymap.set()`. Like this:
    ```lua
    vim.keymap.del('x', 'ys')
    vim.keymap.set('x', 'S', [[:<C-u>lua MiniSurround.add('visual')<CR>]], { silent = true })
    vim.keymap.set('n', 'yss', 'ys_', { remap = true })
    ```
    I'll update the help.
- You are referencing **very** old commit, much has changed since then.

Closing, as it does work and seems to be configuration order issue.
