### ISSUE TITLE
Handle neighborhood with `closeopen` action

### ISSUE THREAD

**Issue by jakubkaczor** [echasnovski/mini.nvim#247]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

pairs

### Description

# The Problem
In the documentation, it is stated that `neigh_pattern` is for action. With `closeopen` I expect it to work with closing and opening, but it only works with the latter. With symmetrical „brackets”, it is not possible to register them twice, as the second would overwrite the first.

# The Context
I would like to register `$` for LaTeX/Markdown, and also be able to pair it twice in the row for exposed math (`$$ math $$`). Therefore, I need to prevent inserting the closing pair, when the character before the cursor is `$`, but the pattern `[^$].` is respected only while opening the first bracket. Having `$|$` where `|` is the cursor and pressing `$` results in `$$|` instead of `$$|$$`.

**Comment by echasnovski** [comment]
What I tend to suggest for this kind of scenarios is that it is more suitable for snippet engine: type `$`, then type `$` again leading to `$$` and this should be a prefix for snippet.

I don't think that behavior of `neigh_pattern` in `closeopen()` will change. I vaguely remember that the reasoning behind this design was that it can be used either for the whole `closeopen()` (your suggestion) or only for possible `open()` (current behavior). The second one proved to be more useful after a bit of testing.

I'll revisit it and see if something can be done here.

**Comment by jakubkaczor** [comment]
I agree that with regard to checking `neigh_pattern`, the current behavior may be more useful, than checking with both opening, and closing. I described expected behavior after reading the documentation, but what I would actually expect is to be able to specify different patterns for different actions, whether the brackets are symmetric or not. That is, be able to specify open action and close action separately for symmetric brackets, as it is currently possible for asymmetric ones.

When it comes to whether this is a task for paring plugin or a snippet engine, at first I thought that the difference is more subtle. Expressions as `\(`, `\)` and `\{`, `\}` in LaTeX really feel like brackets, and that is actually their purpose. On the other hand, it seems as a bracket should be just one symbol, not words or even worse, sentences. But this is the peculiarity of brackets in programming languages, perhaps because we use the fixed set of symbols.

I used to think, for a brief moment, that a snippet engine could replace pairing plugin entirely, but the functionality of just moving the cursor after typing the closing bracket proved indispensable. I believe that the difference in case for each of the technologies is whether moving the cursor after typing the closing bracket is better, i.e. more natural or faster, than jumping after it using normal mode or some special key map. In the case of `(` or `"` it really is. Typing `$$` seemed quite this way also, but perhaps you're right and this is a stretch.

Anyway, the solution as you described it would work, but the problem is with the triggering of a snippet. When the cursor is moved after typing the closing bracket, i.e. we are in the state `$$|`, at least my current snippet engine (LuaSnip) can't trigger the snipped. I believe it may listen for some event with regard to buffer change, but with a simple move right, nothing actually changes. Listening for events with regard to cursor moves would be expensive.

So assuming that this is a task for a snippet engine, the problem comes down to making it possible for a snippet engine to trigger a snippet after the cursor move.

**Comment by echasnovski** [comment]
> ... but the functionality of just moving the cursor after typing the closing bracket proved indispensable. I believe that the difference in case for each of the technologies is whether moving the cursor after typing the closing bracket is better, i.e. more natural or faster, than jumping after it using normal mode or some special key map.

I mapped `<M-hjkl>` in Insert mode to be identical to arrow keys and it proved really useful to get out of the auto-paired brackets. Mostly because I don't have to think which key I have to type to get out of it.

> Anyway, the solution as you described it would work, but the problem is with the triggering of a snippet. When the cursor is moved after typing the closing bracket, i.e. we are in the state `$$|`, at least my current snippet engine (LuaSnip) can't trigger the snipped. I believe it may listen for some event with regard to buffer change, but with a simple move right, nothing actually changes. Listening for events with regard to cursor moves would be expensive.

> So assuming that this is a task for a snippet engine, the problem comes down to making it possible for a snippet engine to trigger a snippet after the cursor move.

There are two things needed to make it work:
- A snippet for `$$` should be defined. With Lua snippets, it is defined in VSCode-like json format. Here is an entry which adds it:
    ```
    "math": {
      "prefix": "$$",
      "body": "$$ $0 $$",
      "description": "Insert math"
    }
    ```
    This should be put in some '.json' file and read by 'LuaSnip'. You can check out how I do it: there is [separate directory](https://github.com/echasnovski/nvim/tree/master/misc/snippets) with filetype-specific snippets which then should be loaded by 'LuaSnip' (something [like this](https://github.com/echasnovski/nvim/blob/master/lua/ec/configs/luasnip.lua#L5)).
- When you type prefix of a snippet (`$$` in this case), you need to tell LuaSnip to expand it. Make a mapping for that (I use [`<C-l>` for a slightly more complex behavior](https://github.com/echasnovski/nvim/blob/master/lua/ec/configs/luasnip.lua#L16)).

I've just recreated these steps and got working `$$|` expansion into `$$ | $$`.

**Comment by jakubkaczor** [comment]
> I mapped `<M-hjkl>` in Insert mode to be identical to arrow keys and it proved really useful to get out of the auto-paired brackets. Mostly because I don't have to think which key I have to type to get out of it.

Thanks for the suggestion. For now, I use `<C-n>` for next stop in snippets and next item in auto-completion.

> There are two things needed to make it work:
> 
>     * A snippet for `$$` should be defined. With Lua snippets, it is defined in VSCode-like json format. Here is an entry which adds it:
>       ```
>       "math": {
>         "prefix": "$$",
>         "body": "$$ $0 $$",
>         "description": "Insert math"
>       }
>       ```
>
>       This should be put in some '.json' file and read by 'LuaSnip'. You can check out how I do it: there is [separate directory](https://github.com/echasnovski/nvim/tree/master/misc/snippets) with filetype-specific snippets which then should be loaded by 'LuaSnip' (something [like this](https://github.com/echasnovski/nvim/blob/master/lua/ec/configs/luasnip.lua#L5)).
> 
>     * When you type prefix of a snippet (`$$` in this case), you need to tell LuaSnip to expand it. Make a mapping for that (I use [`<C-l>` for a slightly more complex behavior](https://github.com/echasnovski/nvim/blob/master/lua/ec/configs/luasnip.lua#L16)).
> 
> 
> I've just recreated these steps and got working `$$|` expansion into `$$ | $$`.

Oh, I thought you meant auto-trigger as it would provide similar feel to pairing, almost equivalent, therefore it is kind of solution. Manual expansion loses it. Automatic expansion is much faster and comfortable. I have the following snippet, but it can't trigger automatically after move, as mentioned.
```lua
    s(
        "$$",
        fmta(
            [[
            $$
                <>
            $$
            <>
            ]],
            {
                i(1),
                i(0),
            }
        )
    ),
```
The first argument to `s` is a trigger string.

As you can see the snippet solution also lack easy choice between inline `$$|$$` and block-like
```tex
$$
  |
$$
```
with `<CR>`, but that's on the side note.

**Comment by echasnovski** [comment]
Well, I still think that managing anything beyond two characters is outside of scope for 'mini.pairs'.

I'll ponder a bit about `closeopen()` and `neigh_pattern` and get back to you.

**Comment by echasnovski** [comment]
Yeah, I remembered now the reasoning behind the design of how `neigh_pattern` is used in `closeopen()`. If it is used to decided whether to do "closeopen" action at all, it will not work for situations like `\|"`: now it moves cursor after `"` but if `neigh_pattern` is used for whole action, it will result into `\"|"`.

Making it work with both close and open will not solve your initial problem of `$|$` -> `$$|$$` because `closeopen()` still needs some logic to decide if it should apply `close` or `open`, which will always result in jumping over `$` at this open.

So I don't think the behavior of `closeopen()` will change. For your particular use case, manually expanded snippets seems the best choice here.

**Comment by jakubkaczor** [comment]
I don't think I understand the example in the first paragraph. When it comes to the second, right, that would need an additional method of deciding whether to apply opening or closing action that I didn't consider. I thought in terms of patterns behaving like exclusive disjunction, but not every pattern pair has to be this way, so it would need to be handled. Perhaps it would be as simple as defining the closing action as simply having a higher precedence, so it would somehow be backward compatible, as it appears this is the current behavior. Then I think it would solve the problem, having `[^$.]` for closing pattern. It wouldn't trigger in the state `$|$`, so the opening action would trigger, if its pattern was `..`.

I understand that perhaps the plugin is created under the assumption that a bracket is one character and in my opinion it is a valid assumption, but I also think that handling opening and closing characters for symmetric brackets falls in the scope. Let us assume that opening `$` and closing `$` is a symmetric pair in some language. The one could want to write `$$This$ is an example.$|`. That would start with `$$|$$`, went through `$$This|$$` and this `$$This$|$`. I don't know use such a language, therefore not handling this case, justifying by assumption that a bracket is a single character, convinces me.

Either way, thank you for discussion. It was nice to consider whether the bracket should be one or more characters. 😉 But perhaps you have an idea, how I could automatically hint the snippet engine to check for a pattern after the closing move, as stated before? Listening for events related to cursor move would be expensive. I'm not sure if it is possible without modifying the plugin.

**Comment by echasnovski** [comment]
> But perhaps you have an idea, how I could automatically hint the snippet engine to check for a pattern after the closing move, as stated before? Listening for events related to cursor move would be expensive. I'm not sure if it is possible without modifying the plugin.

I use [this custom code](https://github.com/echasnovski/nvim/blob/0678ebd59dcd94c67f5b332316fff2b8c6adde23/lua/ec/configs/luasnip.lua#L22-L41) to show `!` as notification that I can expand some snippet. Yes, it does get called on events tracking cursor or text state, but it should be done either way if you want it to be up to date. It seems similar in spirit to what you want to do, but instead of notification you want conditional expansion.

I guess besides `require('luasnip').expandable()` there should be some other exported function that tells you which snippet can now be expanded. You can check if it is the one you want expanded automatically and expand.

**Comment by jakubkaczor** [comment]
Thanks! It directed my thoughts to the solution I think I will be happy with. 😉
