### ISSUE TITLE
Add events to mini.bufremove

### ISSUE THREAD

**Issue by LandonSchropp** [echasnovski/mini.nvim#249]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bufremove

### Description

The bufdelete.nvim package adds two handy events:

* `BDeletePre`
* `BDeletePost`

I'd like to add an autocommand that allows me to open Alpha.nvim when all of the buffers close. With bufdelete.nvim, this can be accomplished like this:

``` lua
vim.api.nvim_create_autocmd("User", {
  pattern = "BDeletePost*",
  group = "alpha_on_empty",
  callback = function(event)
    local buffer_name = vim.api.nvim_buf_get_name(event.buf)
    local buffer_filetype = vim.api.nvim_buf_get_option(event.buf, "filetype")
    local is_empty = buffer_name == "" and buffer_filetype == ""

    if is_empty then
      vim.cmd("Alpha")
    end
  end,
})
```

It would be awesome if mini.bufremove could also add two events, such as `MiniBufremovePre` and `MiniBufremovePost` to enable this.

Thank you for the great plugins!

**Comment by echasnovski** [comment]
Thanks for suggestion!

It is a completely valid request, but I'd go a slightly different route. What about creating own commands for buffer delete and wipeout? Something like this (with a more on brand start screen):

```lua
local open_starter_if_empty_buffer = function()
  local buf_id = vim.api.nvim_get_current_buf()
  local is_empty = vim.api.nvim_buf_get_name(buf_id) == "" and vim.bo[buf_id].filetype == ''
  if not is_empty then return end

  require('mini.starter').open()
end

_G.my_bufdelete = function(...)
  require('mini.bufremove').delete(...)
  open_starter_if_empty_buffer()
end

_G.my_bufwipeout = function(...)
  require('mini.bufremove').wipeout(...)
  open_starter_if_empty_buffer()
end
```

It is a comparable amount of code with a more freedom for user customization.

**Comment by LandonSchropp** [comment]
Thanks for the reply @echasnovski!

This is a great suggestion! I'm using LazyVim, and as far as I can tell MiniBufremove is only used once, so it's not a big deal to remap it.

Would you like to leave this issue opened as a planned feature or close it? I'm happy either way.

Thanks again!

**Comment by LandonSchropp** [comment]
(Also, I like the nod to mini.starter in there. 😉)

**Comment by echasnovski** [comment]
Great it works for you.

I think I'll close this, as it is a fairly good alternative for this use case.

If anyone encounters another use case for `Pre` and `Post` events which can not be done with built-in events, feel free comment here.
