### ISSUE TITLE
Latex comment string is not escaped properly

### ISSUE THREAD

**Issue by piotr-machura** [echasnovski/mini.nvim#25]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

When commenting things using `gcc` (and others) in latex, an "invalid option %% to format" error is  encountered and nothing gets commented. I believe it has to do with the fact that the latex `commentstring` is `%` (`%%s` to be precise), which is also used in formatting and not escaped properly.

### Neovim version

0.6.0

### Steps to reproduce

mini.lua:
```lua
require'packer'.startup {
  function()
  use {
    'echasnovski/mini.nvim',
    branch = 'stable',
    config = function()
      require'mini.comment'.setup()
    end
  }
  end
}
```
1. Open any latex file: `nvim -u mini.lua file.tex`
2. Try to comment something using `gcc`.

### Expected behavior

The error does not occur and commenting works as with other `commentstring`s.

### Actual behavior

Full error message:
```
E5108: Error executing lua ...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:130: Vim(lua):E5108: Error executing lua ...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:164: invalid option '%%' to 'format'
stack traceback:
	[C]: in function 'f'
	...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:164: in function 'toggle_lines'
	[string ":lua"]:1: in main chunk
	[C]: in function 'cmd'
	...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:130: in function <...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:97>
stack traceback:
	[C]: in function 'cmd'
	...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:130: in function <...im/site/pack/packer/start/mini.nvim/lua/mini/comment.lua:97>
```

**Comment by echasnovski** [comment]
Thanks!

Should be fixed now.
