### ISSUE TITLE
mini.indentscope: Make indent line priority configurable

### ISSUE THREAD

**Issue by lkhphuc** [echasnovski/mini.nvim#251]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

I would like to configure the priority with indentscope to make it work with plugin nvim-ufo, i.e still display in folded line.
![Screenshot 2023-03-03 at 16 23 48](https://user-images.githubusercontent.com/12573521/222775452-d18c9fd1-bc27-4841-8fac-636f7fe1e363.png)

Something similar to indent-blankline.nvim `vim.g.indent_blankline_char_priority = 10`?

**Comment by echasnovski** [comment]
Thanks for issue!

Yes, this is reasonable. I remember considering doing this during initial implementation, but didn't see a use case. Not sure, though, why 'nvim-ufo' overriding here...

**Comment by echasnovski** [comment]
Thanks again for suggestion!

This should now be in `main` branch under `config.draw.priority`.

**Comment by lkhphuc** [comment]
Awesome. THanks for the quick update.
