### ISSUE TITLE
mini.pairs support for nvim-cmp method/function autocomplete

### ISSUE THREAD

**Issue by briandipalma** [echasnovski/mini.nvim#252]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

I don't have a lot of hope for this but would it be possible to add support for method/function call bracket autocompete triggered by `nvim-cmp`? In essence what this function https://github.com/windwp/nvim-autopairs/blob/master/lua/nvim-autopairs/completion/cmp.lua#L51 does. Look at the LSP kind and if it's a function/method add brackets?

It could be a generic piece of code that mini.completion could use to achieve the same effect if the `confirm_done` equivalent callback in mini.completion provided the same data?

**Comment by echasnovski** [comment]
Thanks for suggestion!

I remember thinking about implementing it in 'mini.completion' for some time, but something stopped me. Might be either my decision that it doesn't have necessary cost/benefit ratio (hitting single `(` after function completion doesn't seem *that* hard), some implementation difficulty, or something else. I am more inclined to think that it the the first one, but I'll take another look.

**Comment by briandipalma** [comment]
Thanks! All `mini.completion` needs to do is emit the event with the LSP data. I imagine there's more work in the `mini.pairs` end of the task?

**Comment by echasnovski** [comment]
> Thanks! All `mini.completion` needs to do is emit the event with the LSP data. I imagine there's more work in the `mini.pairs` end of the task?

On the contrary. What I was thinking about is that 'mini.completion' will result into adding `()` if entry has type "Function" or "Method".

The 'mini.pairs' module is almost certainly stays as is.

**Comment by echasnovski** [comment]
After thinking about it again, I don't think having automatically placed `()` after accepting completion entry for function has good usefullness/complexity ratio. That is, with 'mini.pairs' it doesn't seem to be much trouble to insert `()` after completion. Besides, not all languages use `()` after function name in calls.

And 'mini.pairs' also doesn't seem to be a good place for that.

Thanks for suggestion nevertheless!
