### ISSUE TITLE
Consider improving terminal mode in basics module 

### ISSUE THREAD

**Issue by Diablo-D3** [echasnovski/mini.nvim#257]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

basics

### Description

I currently use the following in my config:
```vim
augroup term
    au TermOpen * setlocal listchars= nonumber norelativenumber
    au TermOpen * startinsert
    au BufEnter,BufWinEnter,WinEnter term://* startinsert
    au BufLeave term://* stopinsert
augroup END
```

Basics can already do startinsert, but doesn't seem to do it as extensively as this. The rest, it doesn't. I think this approximates what most nvim users do with their terminal, as the defaults (ie, do nothing special) are too rough around the edges.

**Comment by echasnovski** [comment]
Thanks for suggestion!

I tried initially to start Insert mode on every buffer enter, but it had several issues:
- Some plugins open and close terminal inside their functionality, which lead to entering Insert mode in current non-terminal buffer. Don't quite remember which ones did this, but still.
- I think it somewhat contradicts the overall Neovim workflow: after buffer switch I expect to always end up in Normal mode. It is different if I deliberately want to end up in terminal buffer, which `TermOpen` does. Besides, adding this will cause problems for traversing buffers when there are open terminal buffers.

I'll think about local options, though. It does seem useful and universal enough.
