### ISSUE TITLE
gen_path.angle does not handle tab characters correctly

### ISSUE THREAD

**Issue by debugloop** [echasnovski/mini.nvim#258]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

As tab characters take up more than one visible column on the screen, the handling of gen_path.angle should multiply tab characters by their width in visible columns.

### Neovim version

0.8.3

### Steps to reproduce

Open a file that uses tabs, e.g. Go code. Scroll to a position that is indented using as many tabs as possible (for greater effect), observe where the line animation goes.

### Actual behavior

The line animation ends at the column that the character count at the target position implies, not at the visible target position taking into account visible tab width.

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I can reproduce this for default path too. This one might be hard to account for, as internally `\t` is treated as single character while visually represented differently.

I'll look into it.

**Comment by echasnovski** [comment]
Thank you for the push to finally fix some issues which I have been noticing earlier. They didn't bother me too much, so didn't look into them more.

Both `cursor` and `scroll` animations didn't really work with tabs because they used byte-based columns instead of virtual columns. Both of them should now be fixed in `main` branch.

**Comment by debugloop** [comment]
Works perfectly, thanks a lot! 🥳
