### ISSUE TITLE
Repeat jumps in either direction with f / f

### ISSUE THREAD

**Issue by rogersai** [echasnovski/mini.nvim#26]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump

### Description

In clever-f.vim, there is an option that after doing a backwards jump with 'F', you can repeat the jump (still moving backwards) with 'f'. In other words, when you are in the middle of a chain of jumps, 'f' means to keep going in the same direction as the initial jump of the chain, and 'F' means to go in the opposite direction. Similar logic applies to 't' and 'T'.

Not having to go back to holding the shift key after the initial backward jump is more ergonomic, and makes repeated jumps quicker and easier. It would be nice to see this functionality in mini.jump.

**Comment by echasnovski** [comment]
Thanks for the suggestion! There is a `repeat_jump` mapping, which is by default `;`. So you can, for example, type `Fx` to search backwards for `x` and then repeat backward jump with `;`. Then possibly jump forward with `f` and repeat forward jump again with `;`. The same goes with `t` and `T`. Is this good enough for you?

At the moment I like current design better for its simplicity: `f` and `t` always jump forward, `F` and `T` always jump backward, `;` always repeats previous jump.

**Comment by rogersai** [comment]
The repeat map will work well enough, perhaps remapped to another key for my preferences. I do appreciate the logic of keeping the directions absolute.

By chance is there any status variable set by the plugin, where a user could detect if there is a jump chain in progress, and remap 'f' during a chain if desired? I tried to have a look at the code but I'm pretty new at Lua.

BTW, so far I'm  loving mini.nvim, and have replaced several standby plugins with your modules. You've covered most of my "essentials" with nice minimal versions. Big thumbs up, and I'm looking forward to mini-vim-lion.

**Comment by echasnovski** [comment]
Thank you for your kind words!

At the moment there is some stored helper information about the process (if "inside jumping", if "backward", etc.), but it is not exported to the user. I'll think about exporting it, as it does seem like there is an interesting use case.

**Comment by echasnovski** [comment]
I think I'll close this in favor of a newly created one.

**Comment by echasnovski** [comment]
@rogersai, I've created an exported `MiniJump.state` table which should have enough information for the custom remap you were looking for. Sorry for this much delay, wanted to cover module with tests before making any changes. Hope it helps.
