### ISSUE TITLE
Beta-testing 'mini.splitjoin'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#260]
Please leave your feedback about new [mini.splitjoin](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-splitjoin.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by assistcontrol** [comment]
I suspect this is actually the module working as intended, and it just requires a second `toggle()`, but:

```lua
f = {
    1, 2, 3, 4
}

-- Mini.Splitjoin.toggle()

f = {1, 2, 3, 4}
```

My brain was expecting:
```lua
f = {
    1,
    2,
    3,
    4,
}
```

**Comment by echasnovski** [comment]
Yes: toggle is "split if on single line, join otherwise". Doing `toggle` twice [is documented](https://github.com/echasnovski/mini.nvim/blob/46774982c5b74ca056e640aa92689f26f9c62139/doc/mini-splitjoin.txt#L40-L41).

Using `split` explicitly won't actually work here at the moment (and I doubt it will), as I have hard time finding a universal rule on when and how to split when arguments are not on the same line.

**Comment by 13k** [comment]
any plans to integrate with `nvim-treesitter-textobjects` (or even maybe leverage `mini.ai`?) or it's outside the scope of the project?

**Comment by echasnovski** [comment]
> any plans to integrate with `nvim-treesitter-textobjects` (or even maybe leverage `mini.ai`?) or it's outside the scope of the project?

Like for determining what is an "argument"? No, not really. I considered alternative approaches, but the argument definition is consistent with 'mini.ai' which I think is a good approach to use.

**Comment by echasnovski** [comment]
With the release of 0.8.0, 'mini.splitjoin' is now out of beta-tesing.
