### ISSUE TITLE
Add option to choose whether to use padding before/after comment delimiters

### ISSUE THREAD

**Issue by atchim** [echasnovski/mini.nvim#263]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

Some users (me included) like to distinguish between explanatory/documenting comments, and actual code that was commented to avoid it being compiled/interpreted. Usually we use the padding before (and after if needed) the delimiter(s) to differ between those kinds of comments. In my case I use comments without padding to comments for inactivating code, and I use comments with padding to comments with explanatory nature.

```lua
--function commented_function() end
-- This is a comment with explanatory nature.
```

```markdown
<!--# Commented Heading-->
<!-- This is a comment with explanatory nature. -->
```

Usually users only toggle code or comments with actual code instead of explanatory/documenting code, since uncommenting explanatory comments is very likely to cause errors to the compiler/interpreter.

With that in mind, I think that would be very valuable to have an option to choose whether to use padding when commenting, uncommenting or toggling comments.

**Comment by echasnovski** [comment]
Thank for suggestion!

I have hard time picturing a whole workflow here. If there were distinction between "code comments" and "documenting comments" how would you expect to use them? If there is an option to pad or not to pad, it will be applied to any comment toggle. So you would be able to uncomment both code and document commented lines, but create comment only for one type ("code comment" if there is no padding; "doc comment" otherwise). Do you expect to be two mappings for two types of comments or do I misunderstand something here?

**Comment by atchim** [comment]
@echasnovski, sorry for not being clear in my explanation; I really struggle to express my ideas (writing and speaking).

The feature I am asking for is to have an option to control whether commenting/uncommenting should apply a space (padding) after (and before in some cases) the comment delimiter(s).

The explanation about the types of comments was intended to kinda justify this feature request: if the user wants to comment code in a way that differs from how they write doc comments, they are able to do so.

Worth mentioning that maybe the user would like to control both left and right padding, so I thought something like this:

```lua
require'mini.comment'.setup{
  padding = {
    left = false, -- No space after start delimiter.
    right = true, -- With space before end delimiter.
  },
}
```

I hope that I was clear this time. Thanks for the attention!

**Comment by echasnovski** [comment]
I understand this better now, thanks.

> The explanation about the types of comments was intended to kinda justify this feature request: if the user wants to comment code in a way that differs from how they write doc comments, they are able to do so.

But not really this part. How are they able to do so? If by manually adding/removing padding, then how it is different from the current situation?

However, I think adding a boolean option to not trim whitespace from comment parts (as is done now) is reasonable, though. Your case can then be supported by setting appropriate 'commentstring' (like `--%s` or `<!--%s-->`).

**Comment by atchim** [comment]
In the case of the user, they would be able to differentiate by writing doc comments in a way that differs from the options established by `'commentstring'` in conjunction with the proposed options for `mini.comment`.

For instance, if a user write doc comments with padding, they would be able to set a proper `'commentstring'` that does not make use of padding and also configure `mini.comment` to do not add padding when dealing with comments.

I'm having some trouble to change `'commentstring'`. Using `:verbose setl comentstring?` it shows that `'commentstring'` is last set from Lua. Seems that it gets automatically reset after I changing it. Due to that, I cannot properly test the behavior of `mini.comment`.

I will figure out what is happening before trying to check if currently `mini.comment` works as expected with a proper `'commentstring'`.

**Comment by echasnovski** [comment]
Thanks again for suggestion! I wanted to make this behavior behind an option, but it never had enough priority to me.

This should in `main` branch now under `config.options.pad_comment_leaders`. Your use case can be achieved with `require('mini.comment').setup({ options = { pad_comment_leaders = false } })` and setting proper 'commentstring' option per file type. It can be used with `FileType` autocommand like this:

```lua
vim.api.nvim_create_autocmd(
  'FileType',
  {
    pattern = 'lua',
    callback = function() vim.bo.commentstring = '--%s' end,
  }
)
```

I'd suggest using 'after/ftplugin' for this: create 'lua.lua' file in '.config/nvim/after/ftplugin' directory (possibly create it too) with content `vim.bo.commentstring = '--%s'`.

**Comment by atchim** [comment]
The `'cms'` being reset was due to a hook calling [`nvim-ts-context-commentstring`](https://github.com/JoosepAlviste/nvim-ts-context-commentstring). That plugin uses `'cms'` with paddings.

Thank you so much @echasnovski  for working on this! I really appreciate your efforts!

**Comment by echasnovski** [comment]
I've realized **just after** pushing that `pad_comment_parts` is a better name for this, as it seems weird to name right part "leader". So pushed a rename just now. Let's hope it is a last change for it :)
