### ISSUE TITLE
Getting error "bad argument #2 to 'next_span' (number expected, got string)" when using mini.ai text objects

### ISSUE THREAD

**Issue by comfortablynick** [echasnovski/mini.nvim#267]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

I am getting this error when trying to use the text objects. I cannot reproduce with minimal config, so something must be conflicting with the plugin. I previously used targets.vim and I am hoping to replace with mini.ai.

I understand it may not technically be a bug, I'm just hoping someone can point me in the right direction to figure out what might be causing this error:

```
E5108: Error executing lua /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1584: bad argument #2 to 'next_span' (number expected, got string)
stack traceback:
        [C]: in function 'next_span'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1584: in function 'process'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1607: in function 'iterate_matched_spans'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1560: in function 'find_best_match'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1374: in function 'find_next'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:1396: in function 'find_textobject_region'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:560: in function 'find_textobject'
        /home/nick/.local/share/nvim/lazy/mini.ai/lua/mini/ai.lua:983: in function 'select_textobject'
        [string ":lua"]:1: in main chunk
```

### Neovim version

NVIM v0.9.0-dev-1170+gb9f19d3e2

### Steps to reproduce

1. Type `vaf`

### Expected behavior

Expect it to select the next function as it does with minimal config

### Actual behavior

Immediately get error message above

**Comment by echasnovski** [comment]
Two questions:
- What is your 'mini.ai' config? Like how do you call `require('mini.ai').setup()`?
- What does executing `:xmap af` show?

**Comment by echasnovski** [comment]
Hmmm... I can not reproduce.
Does this happen for any text? If not, could you find a minimal example of the text where this happens?

**Comment by comfortablynick** [comment]
It happens for any text in any file type that I've tried so far.

I even tried disabling all of my other plugins and it still happens.

**Comment by echasnovski** [comment]
I can not reproduce this *at all*.

Does it happen on Neovim 0.8.3?
And in general, how did you obtain your Neovim executable? If you built it from source, maybe try [release appimage](https://github.com/neovim/neovim/releases)?

**Comment by comfortablynick** [comment]
I downloaded Neovim 0.8.3 release using pacman and it still happened using that executable. I normally build from master.

I was hoping you might at least have some notion of what might cause it. I've ruled out all of my plugins so it must be something in my config somewhere.

**Comment by echasnovski** [comment]
Let's first get on the same setup and rule out Neovim build itself.

Could you, please:
- Go to [Neovim's 0.8.3 GitHub release](https://github.com/neovim/neovim/releases/tag/v0.8.3) and download `nvim.appimage`.
- Make this downloaded image executable by executing `chmod u+x <path-to-downloaded-nvim.appimage`.
- Run it try from command line with your normal config and try to reproduce the error.

**Comment by comfortablynick** [comment]
Yes, I still get the error using the appimage.

**Comment by echasnovski** [comment]
Great!

Let's now try to be on the same page regarding plugin install:
- Execute `mkdir -p ~/.config/nvim/pack/plugins/opt` . This will create directory where we will install 'mini.ai'.
- Clone 'mini.ai' into that directory with this command:
```bash
git clone --depth 1 https://github.com/echasnovski/mini.ai.git ~/.config/nvim/pack/plugins/opt/mini.ai
```
- Create an init file (lets say at location '~/init-ai.lua') with the following content:
```lua
vim.cmd('set packpath+=~/.config/nvim')
vim.cmd('packadd mini.ai')

require('mini.ai').setup()
```
- Run Neovim 0.8.3 from appimage you downloaded earlier using the following command (assuming you used '~/init-ai.lua' as file path from previous step):
```bash
<path-to-nvim.appimage> --clean -u ~/init-ai.lua -- ~/init-ai.lua
```
    This should open Neovim with already loaded 'mini.ai' and display initialization file used.
- Try pressing `vaf`. It should select whole first line without errors.

**Comment by echasnovski** [comment]
Oh, and by the way: does only `vaf` cause error? Like does all `vif`, `va)` and `va'` lead to this error?

**Comment by comfortablynick** [comment]
> Great!
> 
> Let's now try to be on the same page regarding plugin install:

Sorry if I wasn't clear. I've already tested with minimal config and was **not** able to reproduce the error. It worked exactly as you suggest. I just can't figure out what could possibly be in my config that could interfere with it. I performed your test just to double-check and it highlighted the first line with no errors.

> Oh, and by the way: does only `vaf` cause error? Like do all `daf`, `vif`, `va)` and `va'` lead to this error?

All of them lead to this error.

**Comment by echasnovski** [comment]
> Sorry if I wasn't clear. I've already tested with minimal config and was **not** able to reproduce the error. It worked exactly as you suggest. I just can't figure out what could possibly be in my config that could interfere with it. I performed your test just to double-check and it highlighted the first line with no errors.

I am extremely puzzled by this. If 'mini.ai' works on its own, but not inside your configuration (even when it is the only plugin enabled), then it might be some option which does this. After re-reading 'mini.ai' relevant parts of source code several times I can't see how any option can result into an error.

I'd suggest then going the good old "bisect by comment out parts of you config". Like comment all config except 'mini.ai' (which *should* work); uncomment half of your non-plugin config and see if error appears; etc.

Is [this 'nvim' directory](https://github.com/comfortablynick/dotfiles/tree/main/.config/nvim) in your dotfiles up to date? And do you use regular 'init.lua' and not the 'minit.{lua,vim}' files?

**Comment by echasnovski** [comment]
The reason you have this error is because [you redefine `__call` for string objects](https://github.com/comfortablynick/dotfiles/blob/6e9c5dd4cdab57eec46f9a9b8fbdb747f08764f5/.config/nvim/lua/globals.lua#L100-L110).

This conflicts with 'mini.ai' finding logic because [it allows both string patterns and callables](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-ai.txt#L287) to be part of its specification.

My only suggestion here would be to not modify built-in Lua tables and use separate helper functions.
