### ISSUE TITLE
Quickfix statusline not setting

### ISSUE THREAD

**Issue by oncomouse** [echasnovski/mini.nvim#268]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

Using mini.statusline, the statusline for quickfix and loclist windows are not set immediately on opening, but instead only set on changing window focus (first on leaving quickfix or loclist for another window).

### Neovim version

0.9.0-dev-1210+g172227a44

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Run `:copen`
3. Quickfix statusline is the Neovim default (`%t%{exists('w:quickfix_title')? ' '.w:quickfix_title : ''} %=%-15(%l,%c%V%) %P`)
4. Type `<C-W><C-W>` to return to previous window. Then `<C-W><C-W>` to go back to the quickfix list.
5. Quickfix statusline is now set by mini.statusline (`%!v:lua.MiniStatusline.active()`)

### Expected behavior

In other statusline plugins I've used, the statuslines for quickfix and location list windows are set immediately after opening by the plugin. Ideally, mini.statusline should do the same.

### Actual behavior

Quickfix and loclist statuslines are not set immediately on running `:copen` and `:lopen`, but only when the window focus changes.

**Comment by echasnovski** [comment]
Thank you for the issue!

I can reproduce it. Don't know why I didn't see it sooner. Will look into it.

**Comment by echasnovski** [comment]
So the reason was that built-in quickfix filetype [is setting its own 'statusline' value](https://github.com/neovim/neovim/blob/f01f18cdf4ffc3ce035db5fde2f45493eebb7fd9/runtime/ftplugin/qf.vim#L13-L18) *after* 'mini.statusline' sets its own. This should be fixed in latest ` main`.

**Comment by oncomouse** [comment]
It works, thank you!
