### ISSUE TITLE
[mini.animate] Cursor position outside buffer

### ISSUE THREAD

**Issue by nikolasetiawan** [echasnovski/mini.nvim#273]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

getting similar errors to:
- https://github.com/echasnovski/mini.nvim/issues/177#issuecomment-1363753439
and
- https://github.com/echasnovski/mini.nvim/issues/177#issuecomment-1363753439

For me it happens when [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim) and [Aerial](https://github.com/stevearc/aerial.nvim) window are opened and a new file is opened from neo-tree where it result in the Aerial window changing size.

Here is the full err message
```
Error detected while processing WinScrolled Autocommands for "*":

E5108: Error executing lua ....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1688: Error executing lua: ....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1701: Cursor position outside buffer
stack traceback:
	[C]: in function 'nvim_win_set_cursor'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1701: in function <....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1688>
	[C]: in function 'nvim_win_call'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1688: in function 'apply_resize_state'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1632: in function 'start_resize'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1288: in function 'auto_resize'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_win_call'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1688: in function 'apply_resize_state'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1632: in function 'start_resize'
	....local/share/nvim/lazy/mini.animate/lua/mini/animate.lua:1288: in function 'auto_resize'
	[string ":lua"]:1: in main chunk
```

This happens intermittently though (around 30% at a time), still cannot find a definite situation where it can be reproduced.

If not possible to fix, is there any way to ignore the error message instead? Not having animation once in a while is better than having a big chunk of error pushed out.

### Neovim version

0.8.3

### Steps to reproduce

1. Open file
2. Open neo-tree window
3. Open Aerial window
4. Open a different file from neo-tree which has different Aerial window size
5. try several times until the error pops up

### Expected behavior

no error

### Actual behavior

error pops out

**Comment by nikolasetiawan** [comment]
and here is the mini.animate config I use: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/scrolling/mini-animate/mini-animate.lua

**Comment by echasnovski** [comment]
Finally I can reproduce this! Thank you!

I'll take a look. Probably, tomorrow.

**Comment by echasnovski** [comment]
I still couldn't reliably reproduce this. But as you are far from being a first person to report this, I decided to implement to best possible fix in this situation (suppress errors from setting cursor).

If you still experience this **after** the update, feel free to comment here.

(Yeah, it took slightly more than a day :( ).
