### ISSUE TITLE
mini.jump similar to hop.nvim

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#28]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump

### Description

hop.nvim is faster for jumps. Can we have mini.jump exactly similar to hop.nvim?

**Comment by echasnovski** [comment]
I might consider extending behavior of 'mini.jump', but this will have a low priority, unfortunately. It was initially designed based on 'clever-f' and has many functionality tailored to it, so I expect this will need quite a big rewrite (preserving reverse compatibility, of course).

**Comment by echasnovski** [comment]
I didn't intend to write this functionality in quite some time, but I've got *ideas*. They don't quite align with 'mini.jump', so I ended up creating 'mini.jump2d'. Check it out. And thanks for suggestion!
