### ISSUE TITLE
Repeat jumps backwards with `,`

### ISSUE THREAD

**Issue by e-thn** [echasnovski/mini.nvim#282]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump

### Description

Vanilla vim uses `,` to repeat the last search, but backwards. This functionality hasn't been replicated in this module.

I've tried workarounds like:
```lua
vim.keymap.set('n', ',', function() MiniJump.jump(nil, false, nil, vim.v.count1) end, { desc = 'Repeat jump (backwards)' })
```

But this causes issues because it changes the cached direction of the 'jump chain'.

**Comment by echasnovski** [comment]
Yes, having `,` repeat in previous direction doesn't really suit 'mini.jump' exactly for the reason you described - it changes cached direction. The idea is for users to reverse jumping direction by typing same letter in another case: if jumping with `f`, then type `F` and keep jumping with `F`.

**Comment by echasnovski** [comment]
> I wish to use `mini.jump` only for the multiline `f`, `F`, `t`, `T` behavior (`opts.delay.idle_stop = 0`) and thus need `,`.
> Would it be possible for the closing of this issue, and thus the exclusion of this feature, to be reconsidered?

'mini.jump' is still usable for multi-line `f`/`F`/`t`/`T` with only `;` present (which is somewhat redundant). Current design of jumping in absolute direction with those four keys instead of relative direction with only `;` and `,` will stay.
