### ISSUE TITLE
base06 only used once in base16.lua

### ISSUE THREAD

**Issue by altermo** [echasnovski/mini.nvim#284]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

base16.lua

### Description

The `base06` color is only used once in `base16.lua`. This feels like a waste. 
I recommend the feature of using `base06` more than once in `base16.lua`.

**Comment by echasnovski** [comment]
Thanks for suggestion!

'mini.base16' tries to follow [chriskempson/base16-vim](https://github.com/chriskempson/base16-vim/blob/master/templates/default.mustache) as much as possible. As it doesn't use `base06` at all, so is 'mini.base16'.
