### ISSUE TITLE
Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim(bprevious):E85: There is no listed buffer

### ISSUE THREAD

**Issue by cbochs** [echasnovski/mini.nvim#286]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.bufremove

### Description

When removing the _last_ buffer in a window and that buffer is a _help_ file, the following error occurs:

```
   Error  21:25:39 msg_show.emsg E5108: Error executing lua: ...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152: Error executing lua: vim/_editor.lua:0: nvim_exec2(): Vim(bprevious):E85: There is no listed buffer
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:166: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152>
	[C]: in function 'nvim_win_call'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:142>
	vim/shared.lua: in function 'tbl_map'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:128: in function 'unshow'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:238: in function 'delete'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:323: in function <...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:323>
stack traceback:
	[C]: in function 'nvim_win_call'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:152: in function <...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:142>
	vim/shared.lua: in function 'tbl_map'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:128: in function 'unshow'
	...al/share/nvim/lazy/mini.bufremove/lua/mini/bufremove.lua:238: in function 'delete'
	...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:323: in function <...l/share/nvim/lazy/LazyVim/lua/lazyvim/plugins/editor.lua:323>

```

### Neovim version

NVIM v0.9.0-dev-1292+geac75a971

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:h only` (or any unlisted buffer)
3. `:only`
4. `:lua require("mini.bufremove").delete(0, false)`

### Expected behavior

The unlisted buffer should be deleted.

### Actual behavior

An error is thrown (as shown above).

**Comment by echasnovski** [comment]
I can not reproduce it on neither Neovim 0.8.3 nor on `NVIM v0.9.0-dev-1296+g8b7fb668e` (latest available Nightly release). Also can not reproduce neither with minimal setup (only 'mini.nvim' added to `packpath`) nor with my day-to-day setup (all my used plugins are enabled).

Here is a demo of Nightly with minimal setup:

https://user-images.githubusercontent.com/24854248/228762587-61cb72a2-4c7c-47d7-baba-b038ef15e206.mp4

---------------

What kind of setup you actually used in `nvim -nu minimal.lua` step? It seems like there is some other plugin interfering with buffer list.

**Comment by cbochs** [comment]
Apologies here. The error appeared fairly unambiguous when it was happening the other day. I was able to reproduce, but I hadn't considered other plugins interfering. I can't seem to reproduce anymore, so will close for now. Thanks for taking a look 👍

**Comment by aldanor** [comment]
In other words, you can come up with cases where [this line](https://github.com/echasnovski/mini.bufremove/blob/14805473144fffbd019d07e51bed2d176e065ee9/lua/mini/bufremove.lua#LL156C7-L156C7) will simply fail:

```lua
    -- Try using previous buffer
    vim.cmd('bprevious') -- <------------- this line can (and will) crash sometimes
    if cur_buf ~= vim.api.nvim_win_get_buf(win_id) then return end
```

**Comment by echasnovski** [comment]
Thanks for the detailed analysis!

I have nothing against updating code of 'mini.bufremove', but it needs to be based on concrete reproducible example. This will both help decide which fix is better and serve as test.

Without it, I am hesitant touching (otherwise working) code.

**Comment by aldanor** [comment]
@echasnovski Thanks for the prompt reply. Tbh I have no prior experience in creating reproducible examples in nvim, any tips on how to try to isolate it? (i.e. creating a working minimal environment with bufremove and perhaps a few other plugins that may interfere?)

**Comment by echasnovski** [comment]
> @echasnovski Thanks for the prompt reply. Tbh I have no prior experience in creating reproducible examples in nvim, any tips on how to try to isolate it? (i.e. creating a working minimal environment with bufremove and perhaps a few other plugins that may interfere?)

Sure.
- Put (via `git clone`, for example) necessary  plugins somewhere where you can load them. I suggest 'pack/plugins/opt/' directory inside your config ('\~/.config/nvim' in Unix). For example, you should have '~/.config/nvim/pack/plugins/opt/mini.nvim' with latest code changes (or 'mini.bufremove' if you want to clone standalone repository).
- Create 'repro-init.lua' file (or any other name). It should load and initialize plugins. Following previous step, it should contain at least something like this:
```lua
-- Make Neovim aware about 'mini.nvim' source code
vim.cmd('packadd mini.nvim')

-- Initialize 'mini.bufremove'
require('mini.bufremove').setup()
```
    It can also contain some other initialization you wish to do on startup.
- Start neovim with `nvim --noplugin -u repro-init.lua`.
- Perform actions which lead to the error. Make sure that they consistently lead to the same error.
- Put your 'repro-init.lua' file and steps: either here or in a new issue.

Note, that if error can be reproduced only with another plugin, then it also might be the reason of the error.
