### ISSUE TITLE
How to surround entire sentence?

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#29]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

In vim-surround plugin I could do `yss(` to surround the entire sentence with
`()` but that functionality didn't seem to be working with vim-sandwich. I have
changed the bindings to be similar to vim-surround's but I'm unable to do `yss`.

I can do `Vys(` but it'd be rather convenient to have `yss`.

### Neovim version

0.6.1

### Steps to reproduce

```lua
require("mini.surround").setup({
      -- Number of lines within which surrounding is searched
      n_lines = 20,

      -- Duration (in ms) of highlight when calling `MiniSurround.highlight()`
      highlight_duration = 500,

      -- Pattern to match function name in 'function call' surrounding
      -- By default it is a string of letters, '_' or '.'
      funname_pattern = "[%w_%.]+",

      -- Mappings. Use `''` (empty string) to disable one.
      mappings = {
      add = "ys", -- Add surrounding
      delete = "ds", -- Delete surrounding
      -- find = "sf", -- Find surrounding (to the right)
      -- find_left = "sF", -- Find surrounding (to the left)
      -- highlight = "sh", -- Highlight surrounding
      replace = "cs", -- Replace surrounding
      -- update_n_lines = "sn", -- Update `n_lines`
      },
})
```

### Expected behavior

`yss(` surrounds the entire sentence with `(` or respective object.

### Actual behavior

-

**Comment by echasnovski** [comment]
Judging by the text of this issue, what you actually want is to surround the entire *line* and not sentence.
Vim (and Neovim, of course) has a motion for lines which is coded with [`_`](https://vimhelp.org/motion.txt.html#_) (underscore). So to surround the entire line with parenthesis, type `sa_)` (`ys_)` in your setup). You can make your own keymap for `yss` to mimic `ys_`.

By the way, Vim also has a text object for a [`sentence`](https://vimhelp.org/motion.txt.html#as).

**Comment by gerazov** [comment]
How can I setup a linewise surround to `yss`. I tried but it didn't work:
```vim
  config = function()
    require 'mini.surround'.setup()
    vim.api.nvim_set_keymap('n', 'yss', 'ys_', {noremap = false, silent = true})
  end,

```

**Comment by echasnovski** [comment]
> How can I setup a linewise surround to `yss`. I tried but it didn't work:
> 
> ```viml
>   config = function()
>     require 'mini.surround'.setup()
>     vim.api.nvim_set_keymap('n', 'yss', 'ys_', {noremap = false, silent = true})
>   end,
> ```

By default 'mini.surround' has different from 'tpope/vim-surround' mappings. See [this part of the help](https://github.com/echasnovski/mini.nvim/blob/d8bab386fe69c02129857957e148c7178bf94ae9/doc/mini-surround.txt#L500-L522).

If, by any chance, you still want to have `yss` to surround the line while having default mappings, use `sa_` as the right hand side in your example instead of `ys_`.

**Comment by gerazov** [comment]
Wow this is awesome :love_you_gesture: - and I ploughed through the help before writing here and still didn't see it :sweat_smile: Consider adding this part to the README, I guess many people coming from `vim-surround` will find it useful.

**Comment by echasnovski** [comment]
> Wow this is awesome 🤟 - and I ploughed through the help before writing here and still didn't see it 😅 Consider adding this part to the README, I guess many people coming from `vim-surround` will find it useful.

Thanks!

The existence of the config is already mentioned at the top of the README with indication that there is more data in help file. And indication of where to look for the config is [the second sentence in the config](https://github.com/echasnovski/mini.nvim/blob/c87d3b73d763d4222cdef19323e6a2c4bee33013/doc/mini-surround.txt#L8-L9). I hoped this would be enough.

**Comment by gerazov** [comment]
Ahah :sweat_smile: true true ...
