### ISSUE TITLE
indentscope wrongly marks non bracketed indents

### ISSUE THREAD

**Issue by UtkarshVerma** [echasnovski/mini.nvim#290]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

I'm having issues with indentscope in C indents where curly braces are not there. Here's a video:

https://user-images.githubusercontent.com/31820255/229249581-79cc0914-0f6c-42a8-9e8e-cd12ab2ea283.mp4

Here's the snippet, just in case:

```c
int smbios_add_string(u8 *start, const char *str)
{
	int i = 1;
	char *p = (char *)start;

	/*
	 * Return 0 as required for empty strings.
	 * See Section 6.1.3 "Text Strings" of the SMBIOS specification.
	 */
	if (*str == '\0')
		return 0;

	while (*p) {
		if (!strcmp(p, str))
			return i;

		p += strlen(p) + 1;
		i++;
	}

	strcpy(p, str);
	p += strlen(str);
	*(p + 1) = '\0'; // Indicate the end of set with an additional null byte
	return i;
}
```

### Neovim version

0.8.3

### Steps to reproduce

This is the default behaviour.

### Expected behavior

Indent guides should not be shown on empty lines, for non-bracketed blocks in C.

### Actual behavior

Indent guides are also shown for empty lines, even if the block is not bracketed.

**Comment by echasnovski** [comment]
It works as expected. 'mini.indentscope' takes into account only text indent. In your example you seem to use `options.try_as_border = true` which leads to showing indent scope of a construct's "inner body" instead of outer one. Presence or absence of brackets has nothing to do with.

**Comment by UtkarshVerma** [comment]
I do understand that, but is it expected behaviour for it to show indent on empty lines? Here is what it looks like, with  `try_as_border = false`.

https://user-images.githubusercontent.com/31820255/229270847-d55b5ba4-ee3b-47d9-b5cc-3c7ac0b2ec2e.mp4

The video shows that the if block ends on line 157, but the indent guides are still shown for it on line 158. It feels a bit off while using it.

Here is my `lazy.nvim` config:
```lua
  {
    "echasnovski/mini.indentscope",
    opts = function(_, opts)
      return vim.tbl_deep_extend("force", opts, {
        draw = {
          animation = require("mini.indentscope").gen_animation.none(),
        },
        options = {
          try_as_border = false,
        },
        symbol = "a",
      })
    end,
  },
```

**Comment by echasnovski** [comment]
> I do understand that, but is it expected behaviour for it to show indent on empty lines?

By default, yes. Behavior of empty lines near the edge is controlled by `options.border`. To not recognize bottom blank lines try `options = { border = 'top' }`.

**Comment by UtkarshVerma** [comment]
Thanks, now it behaves as expected.
