### ISSUE TITLE
Ability to define linewise textobjects

### ISSUE THREAD

**Issue by oncomouse** [echasnovski/mini.nvim#291]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

I've been using the following textobject with mini.ai to select the whole buffer:

```lua
e = function() -- Whole buffer
	local from = { line = 1, col = 1 }
	local last_line_length = #vim.fn.getline("$")
	local to = {
		line = vim.fn.line("$"),
		col = last_line_length == 0 and 1 or last_line_length,
	}
	return {
		from = from,
		to = to,
	}
end,
```

Additionally, I use [vim-sort-motion](https://github.com/christoomey/vim-sort-motion) to map `gs` to sort. vim-sort-motion uses `:sort` to sort a textobject when it is linewise (when `line` is passed to the operatorfunc) but tries to split the region by a delimiter and sort using `sort()` when the region is charwise (so, it could sort `5,2,1` into `1,2,5`).

I get an error when I run `gsae` to sort buffer contents because, as far as I can tell, textobjects defined by mini.ai are always defined as charwise regions.

In [vim-textobj-user](https://github.com/kana/vim-textobj-user), you could define the visual command when creating a region (passing `V` to define a linewise region or `v` to define a charwise region). I know I can pass `vis_mode` to `MiniAi.select_textobject()`, but is there (or could there be) a way to define the preferred `vis_mode` for a textobject, so that some could always be linewise?

**Comment by echasnovski** [comment]
@oncomouse, this is now possible with the `vis_mode` field in returned region table. The following `custom_textobjects` specification should work now as you'd expect (tested with [vim-sort-motion](https://github.com/christoomey/vim-sort-motion)):
```lua
e = function() -- Whole buffer
  local from = { line = 1, col = 1 }
  local last_line_length = #vim.fn.getline('$')
  local to = {
    line = vim.fn.line('$'),
    col = last_line_length == 0 and 1 or last_line_length,
  }
  return { from = from, to = to, vis_mode = 'V' }
end,
```

(Side note: I almost closed this without adding new feature because forcing selection mode still works. So with your original textobject specification, doing `gsVae` worked. See `:h forced-motion`)

**Comment by haoming-li-ling** [comment]
Can you make it so that simple pattern-string-defined textobjects can also take the linewise option?

**Comment by echasnovski** [comment]
> Can you make it so that simple pattern-string-defined textobjects can also take the linewise option?

Most certainly won't happen. It is possible to make them linewise by using `V` for visual selection and `V` after common operators (like `dV`, `yV`, etc.).
