### ISSUE TITLE
feat(ai): move_cursor more flexible

### ISSUE THREAD

**Issue by IndianBoy42** [echasnovski/mini.nvim#293]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

Right now the api is a bit inflexible in a few ways
- left, right are mutually exclusive
- outer and inner are mutually exclusive (can be fixed by defining the textobject spec with both inner and outer together, which brings me to the next problem:)
- it can only use predefined specs, even though the specs I might want for movement may be different from the ones I want for selection

I've been trying to tweak my jump mappings in a way that I find convenient and intuitive (not so much thinking about do I want to get to the end, or the beginning, including the current object or not, etc). And I think something like `]f` moving between both the outer beginning, inner beginning, inner end, outer end of functions, along with easy repeatability (hydra.nvim <3), seems ideal, would have to try but mini.ai doesn't support it for now.

**Comment by echasnovski** [comment]
Thanks for suggestion!

I am not really sure what you want to achieve, to be honest. Maybe you could an example: text with cursor position and how pressing certain keys will work?

My best guess right now is that you want something like `]f` to cycle through four positions: right `i`, right `a`, left `a`, left `i`. If that is the case, this functionality is supported in 'mini.surround' with `sf` and `sF`. And both of them are dot-repeatable.

**Comment by IndianBoy42** [comment]
Surrounds find does cycle through those positions but it doesn't move to the next object after that (i'd have to use sfn, sfl, sFn, sFl which returns me to the problem of having too many different keybindings) so it doesn't exactly fit my needs, which is more about navigating across the whole codebase somewhat semantically. It should move between `{right, left} x {i, a} x {all instances of that text object}`, surround misses the last part of that product, ai misses the first two

It also has the problem of not being invokable from custom mappings, ie I don't know what i'd put as the rhs inside a hydra.nvim head to invoke find next with a specific textobject/surround, since i'd rather use that than . for repeating

**Comment by IndianBoy42** [comment]
I'll use parenthese for the example for brevity but imagine these are functions/block/loops/etc 
```
( text ) ( other text )
   ^
   ]b
( text ) ( other text )
     ^
   ]b
( text ) ( other text )
       ^
   ]b
( text ) ( other text )
         ^
   ]b
( text ) ( other text )
           ^
   [b
( text ) ( other text )
         ^
   [b
( text ) ( other text )
       ^
   ]b
( text ) ( other text )
         ^
   ]b
( text ) ( other text )
           ^
   ]b
( text ) ( other text )
                    ^
   b
( text ) ( other text )
                 ^  
   [b
( text ) ( other text )
           ^  
```

**Comment by IndianBoy42** [comment]
```
( text ) ( other ( text ) )
^ ^  ^ ^ ^ ^     ^ ^  ^ ^ ^
```
You could imagine finding the 4 keypoints (al, il, ir, ar) of all textobjects in the buffer, deduplicating, and then `][` keys would go to the closest next or previous keypoint

**Comment by echasnovski** [comment]
> ```
> ( text ) ( other ( text ) )
> ^ ^  ^ ^ ^ ^     ^ ^  ^ ^ ^
> ```
> 
> You could imagine finding the 4 keypoints (al, il, ir, ar) of all textobjects in the buffer, deduplicating, and then `][` keys would go to the closest next or previous keypoint

I see know, thanks!

Well, if you want to primarily use `][`, then it is the job for 'mini.bracketed'. It does have a [`MiniBracketed.advance()` helper](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-bracketed.txt#L596) which can help here. You'd need to write your own iterator, possibly with help of 'mini.ai'.

I'll think about it, but at the moment I don't see a good way of adding this type of functionality in any of 'mini.nvim' modules.

**Comment by IndianBoy42** [comment]
i'll look into mini.bracketed, nvim-treesitter has some useful methods to make iterators so that shouldn't be the problem, even without mini.ai. is it possible to disable dot-repeat for it? (and surround too), I'll be setting up my own system for repeating jumps. I'll probably also disable all the mappings and try to set the mappings through hydra.nvim myself

**Comment by echasnovski** [comment]
> is it possible to disable dot-repeat for it? (and surround too)

There is no dot-repeat in 'mini.bracketed' and movement in 'mini.ai'. There is dot-repeat for any 'mini.surround' actions which can not be disabled.

**Comment by IndianBoy42** [comment]
Oh yeah, sorry I misunderstood the meaning of: https://github.com/echasnovski/mini.nvim/blob/a7c375312edba618d7abc7c6129c53c512cca9d7/doc/mini-bracketed.txt#L22
