### ISSUE TITLE
[mini.animate] Unable to scroll properly when `scrolloff` is set

### ISSUE THREAD

**Issue by cdevoogd** [echasnovski/mini.nvim#294]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

animate

### Description

I am currently running neovim 0.9.0 and `mini.nvim` at commit `a7c3753`. When I enable the `animate` module with `scrolloff` enabled (mine is set to 8) I experience really erratic animations and the cursor seems to frequently jump upwards when trying to scroll down.

Here is the minimal config I created to reproduce this issue:
```lua
-- Minimal config based on the example in folke/noice.nvim to prevent it from using existing lazy plugins
-- https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue
local root = vim.fn.fnamemodify("./nvim-repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
   vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
   vim.fn.system({
      "git",
      "clone",
      "--filter=blob:none",
      "--single-branch",
      "https://github.com/folke/lazy.nvim.git",
      lazypath,
   })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
   "echasnovski/mini.nvim",
   -- pinning the commit to the one where I experienced the issue
   commit = "a7c3753",
   config = function()
      require("mini.animate").setup({})
   end,
}
require("lazy").setup(plugins, {
   root = root .. "/plugins",
})

vim.opt.scrolloff = 8

```

### Neovim version

0.9.0

### Steps to reproduce

1. Run neovim with the minimal config provided above: `nvim -nu minimal.lua`
2. Open a file with enough lines that you can scroll
3. Attempt to scroll up and down in the file

### Expected behavior

Scrolling should move up and down normally without stuttering or moving in the wrong direction

### Actual behavior

With no mini plugin and `scrolloff` set, this is what it looks like

```lua
vim.opt.scrolloff = 8
```

https://user-images.githubusercontent.com/15240739/230755465-3ea9b2a1-c3ba-4601-a0ca-b63e4464ef40.mp4

With these configs, this is what it looks like when I try to scroll down.

```lua
require("mini.animate").setup({})
vim.opt.scrolloff = 8
```

https://user-images.githubusercontent.com/15240739/230755161-405c41b9-7f7c-470d-bee5-0abffab36c14.mp4

And this is what it looks like when I try to scroll up

https://user-images.githubusercontent.com/15240739/230755172-4e9557ec-0432-452d-8432-43fb5376f01f.mp4

When I get rid of `scrolloff` it does let me scroll without jumping around (albeit really slowly but maybe I can change that with configuration?).

```lua
require("mini.animate").setup({})
```

https://user-images.githubusercontent.com/15240739/230755238-d374f081-2d4c-4f7d-a2d3-48f95d6a6d18.mp4

If I disable `scroll` in the animate module then the scrolling goes back to normal and looks like the first video

```lua
require("mini.animate").setup({
   scroll = { enable = false },
})
vim.opt.scrolloff = 8
```

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce with my current config.

> With no mini plugin and scrolloff set, this is what it looks like

You still have scroll animation here. Where does it come from? As this is not a default behavior. Maybe there is some other scroll animation plugin that you didn't disable?

**Comment by cdevoogd** [comment]
I don't seem to see any scroll animation in that video, maybe you are mistaking where I am resetting my finger on the mouse's scroll wheel? 

All of those videos were made using that minimal config, and that video had just `scrolloff` set and mini disabled in `lazy.nvim`, so the only plugin that would have been loaded was lazy. I also just went ahead and reproduced the issue with that minimal config on my macbook and iterm2, so I don't believe this is a terminal-specific issue either (the initial report is on windows terminal and wsl2 ubuntu).

**Comment by echasnovski** [comment]
> I don't seem to see any scroll animation in that video, maybe you are mistaking where I am resetting my finger on the mouse's scroll wheel?
> 
> All of those videos were made using that minimal config, and that video had just `scrolloff` set and mini disabled in `lazy.nvim`, so the only plugin that would have been loaded was lazy. I also just went ahead and reproduced the issue with that minimal config on my macbook and iterm2, so I don't believe this is a terminal-specific issue either (the initial report is on windows terminal and wsl2 ubuntu).

How do you scroll? I assumed you used something like `<C-d>` or `<C-f>`. Do you have this issue when you use mouse wheel to scroll? If yes, then this a limitation of async nature of this scroll (see [here in help](https://github.com/echasnovski/mini.nvim/blob/a7c375312edba618d7abc7c6129c53c512cca9d7/doc/mini-animate.txt#L277-L282)). Also try `set mousescroll=1` and scroll aggressively (many wheel turns per second) or `set mousescroll=30` and move wheel once.

**Comment by cdevoogd** [comment]
Ah I see. I do typically use those keymaps but these clips are from me using the mouse wheel. I will still rarely use the mouse and noticed it when I first tried after installing the plugin. If it's already a documented issue then that should be fine. Because the README had notes about scrolling (like using neovim 0.9.0) I was expecting that kind of note to be included in there as well, my apologies I should have probably dug into the help doc a little more. I was hoping to find a way to make the animations work for the keymaps but disable them for the mouse but it seems like that wouldn't be possible or make much sense from a logic point of view since both are scrolling, so maybe I'll just try to avoid the mouse for now.

**Comment by echasnovski** [comment]
> Ah I see. I do typically use those keymaps but these clips are from me using the mouse wheel. I will still rarely use the mouse and noticed it when I first tried after installing the plugin. If it's already a documented issue then that should be fine. Because the README had notes about scrolling (like using neovim 0.9.0) I was expecting that kind of note to be included in there as well, my apologies I should have probably dug into the help doc a little more. I was hoping to find a way to make the animations work for the keymaps but disable them for the mouse but it seems like that wouldn't be possible or make much sense from a logic point of view since both are scrolling, so maybe I'll just try to avoid the mouse for now.

Well, staying away from mouse as much as possible **is** a good solution in my book :)

However, [here](https://github.com/echasnovski/mini.nvim/issues/177#issuecomment-1363816701) is some other in-depth insights. And [here](https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/ui/mini-animate.lua#L6) is how Folke solves this.

Do I understand correctly that there is no issue of scrolling not with mouse?

**Comment by cdevoogd** [comment]
> Do I understand correctly that there is no issue of scrolling not with mouse?

Yeah, scrolling without the mouse seems to act as expected.

**Comment by echasnovski** [comment]
> > Do I understand correctly that there is no issue of scrolling not with mouse?
> 
> Yeah, scrolling without the mouse seems to act as expected.

Great. Closing then.
I'll think about adding this to the README, though. As it is indeed a somewhat crucial detail.

**Comment by echasnovski** [comment]
I've added information to README about why scroll animation and mouse wheel scroll need updates to work together. Thanks again for (inadvertently) raising this issue!
