### ISSUE TITLE
Indent scope provider for fold method

### ISSUE THREAD

**Issue by top4ek** [echasnovski/mini.nvim#296]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

identscope

### Description

Ability to fold code based on scope highlight.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Not *exactly* the same, but using `set foldmethod=indent` is close enough. So I don't it will be implemented in 'mini.indentscope'.

**Comment by top4ek** [comment]
Yep, i'm using it right now and can't get accustomed to what I see and what I get :)

**Comment by saygo-png** [comment]
>using set foldmethod=indent is close enough

I really don't think it is. For me what indentscope shows vs what `indent` folds is vastly different. `indent` also has very strange behavior on comments.

These are my settings, you can play around with it yourself and see the large disconnect. This is very jarring when editing...

```lua
            require("mini.indentscope").setup({
                draw = { delay = 0, priority = 2 },
                options = { border = "top", indent_at_cursor = true, try_as_border = true },
                symbol = "│",
            })
```
