### ISSUE TITLE
Support dot-repeat for `MiniMove.move_line()`

### ISSUE THREAD

**Issue by sassanh** [echasnovski/mini.nvim#299]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.move

### Description

Thanks for this helpful plugin!

I noticed when I activate `line_left`/`line_right`, repeat is possible by pressing `.`, but it doesn't work for `line_up` and `line_down`. It would be nice if it worked for these actions as well.

### Neovim version

0.9.0

### Steps to reproduce

1. `nvim -nu minimal.lua minimal.lua`
2. Press `<a-j>`
3. Press `.`

minimal.lua:
```lua
local lazypath = '/tmp/minimal-mini.lua-bug-report/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require 'lazy'.setup {
  {
    'echasnovski/mini.move',
    config = function() require 'mini.move'.setup() end,
  }
}
```

### Expected behavior

First 3 lines to become:
```lua
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
          local lazypath = '/tmp/minimal-mini.lua-bug-report/lazy/lazy.nvim'
```

### Actual behavior

First 3 lines is:
```lua
if not vim.loop.fs_stat(lazypath) then
        local lazypath = '/tmp/minimal-mini.lua-bug-report/lazy/lazy.nvim'
  vim.fn.system({
 ```

**Comment by echasnovski** [comment]
Thanks for the issue!

Dot-repeat with horizontal movement is mostly a coincidence as it uses `<` and `>` which are dot-repeatable. I didn't consider making single line movement dot-repeatable as it ergonomically is virtually similar as pressing default mappings while holding `Alt`/`Meta`.

I'll look into it.

**Comment by sassanh** [comment]
Yeah, I used `[e` and  `]e` too. Personally I think key combination is for emac, we use vim to have key sequences and avoid hurting pinkie. Also alt/meta are not easily available on all terminal emulator. I have them on macOS (left alt is alt, right alt is for diacritics) but I know it is tricky in some terminal emulators. Btw, not a deal breaker, everybody can change the default mappings as they wish and enjoy mini.nvim, we just need repeat to work.

I also have `[r` and `]r` for moving characters left and right, it would be nice if `mini.nvim` supports these too, maybe I should create another issue or maybe even a PR if it is a feature with a single user :-)

**Comment by echasnovski** [comment]
> I also have `[r` and `]r` for moving characters left and right, it would be nice if `mini.nvim` supports these too, maybe I should create another issue or maybe even a PR if it is a feature with a single user :-)

Probably, not the best fit in 'mini.move', as there is `move_selection()`. I'd suggest making custom keymappings:

```
nmap [r v<M-h>v
nmap ]r v<M-l>v
```

Notes:
- Replace `<M-h>` and `<M-l>` with your mappings for horizontal movement of visual selection.
- This is not ideal as it overrides previous visual selection (`gv` will reselect moved single character). But at the moment I feel this is worthwhile trade-off.

**Comment by echasnovski** [comment]
So I've looked into adding dot-repeat to mappings for moving current line and it is not that simple. Usual approach of setting `'operatorfunc'` and using expression mapping doesn't work right away here. The main reason seems to be that `move_line()` itself uses some dot-repeatable actions which override the main one.

I'll give it another go, but my hopes are not high at the moment.

**Comment by sassanh** [comment]
I had these:

```Lua
vim.keymap.set(
  'n',
  ']r',
  function()
    vim.fn['repeat#set']("]r", vim.v.count)
    return '@=len([execute("let b:_tmp=@a"),execute(\'normal! "aylx"ap\')' ..
        ',execute("let @a=b:_tmp"),execute("unlet b:_tmp")]) ? "hl" : "" <cr>'
  end,
  { expr = true, silent = true }
)
vim.keymap.set(
  'n',
  '[r',
  function()
    vim.fn['repeat#set']("[r", vim.v.count)
    return '@=len([execute("let b:_tmp=@a"),execute(\'normal! "ayhx"ap\')' ..
        ',execute("let @a=b:_tmp"),execute("unlet b:_tmp")]) ? "h" : "" <cr>'
  end,
  { expr = true, silent = true }
)
```

I don't understand what exactly I achieved in these cryptic vim script snippets, it is written years ago, but it was doing the job.

Yesterday I changed them to these:
```lua
vim.keymap.set(
  'n',
  '[r',
  function()
    vim.fn['repeat#set']("[r", vim.v.count)
    local pos = vim.api.nvim_win_get_cursor(0)
    local col = pos[2]
    if col <= 0 then return end
    local line = vim.api.nvim_get_current_line()
    vim.api.nvim_set_current_line(
      line:sub(1, col - 1) .. line:sub(col + 1, col + 1) .. line:sub(col, col) .. line:sub(col + 2)
    )
    vim.api.nvim_win_set_cursor(0, { pos[1], pos[2] - 1 })
  end,
  {}
)
vim.keymap.set(
  'n',
  ']r',
  function()
    vim.fn['repeat#set']("]r", vim.v.count)
    local pos = vim.api.nvim_win_get_cursor(0)
    local col = pos[2]
    local line = vim.api.nvim_get_current_line()
    vim.api.nvim_set_current_line(
      line:sub(1, col) .. line:sub(col + 2, col + 2) .. line:sub(col + 1, col + 1) .. line:sub(col + 3)
    )
    vim.api.nvim_win_set_cursor(0, { pos[1], pos[2] + 1 })
  end,
  {}
)
```

**Comment by echasnovski** [comment]
> I had these:
> 
> ...
>
> I don't understand what exactly I achieved in these cryptic vim script snippets, it is written years ago, but it was doing the job.
> 
> Yesterday I changed them to these:
> ...

Good thing this works for you!

Two observations here:
- Crucial part here is a call to `vim.fn['repeat#set']` which utilizes 'tpope/vim-repeat' - the core reason for dot-repeat. On that note, `[e` and `]e` in 'vim-unimpaired' are also not dot-repeatable out of the box, only when using 'tpope/vim-repeat'.
- I'd simplify a bit (or rather would have taken different route with) Lua code by using `vim.cmd('normal! xp')` and `vim.cmd('normal! Xph')` (along with caching register and going around some edge cases). It will also work on multi-byte characters where current solutions don't.

**Comment by sassanh** [comment]
You are right, both of them work with vim-repeat, but I have a vague impression that the old vim-script version, which is using an `<expr>` mapping used to work in vim-script, before I move it to Lua files and define it using vim.keymap. Or maybe I'm mistaken, maybe I try hard to achieve it with `<expr>` but failed and just kept it as is.

`xp` and `Xph` are the way most people go, it just ruins the registers as you mentioned, and other than that they don't seem to be repeatable, I tried this:
```Lua
vim.keymap.set(
  'n',
  ']r',
  function()
    vim.cmd([[
    normal! xp
    ]])
  end,
  {}
)
```

Btw, the trend these days is to have mini.everything ;) Maybe we can have a mini.repeat. [It is one of the smallest and yet popular vim plugins](https://github.com/tpope/vim-repeat/blob/master/autoload/repeat.vim). I couldn't believe my search for "repeat.nvim" or "nvim-repeat" in Google returned no result.

**Comment by echasnovski** [comment]
> `xp` and `Xph` are the way most people go, it just ruins the registers as you mentioned,

Yes, this is why I said that it needs to cache register content (and later restore). This is what id one in 'mini.move' anyway.

> Btw, the trend these days is to have mini.everything ;) Maybe we can have a mini.repeat. [It is one of the smallest and yet popular vim plugins](https://github.com/tpope/vim-repeat/blob/master/autoload/repeat.vim). I couldn't believe my search for "repeat.nvim" or "nvim-repeat" in Google returned no result.

Yeah, I've seen those. The thing is that there is no additional benefit to just rewriting it Lua.

But you've moved me towards an idea of 'mini.keymap' which can contain something like `MiniKeymap.with_dotrepeat()` and `MiniKeymap.with_timer()` (resolving #86 which I am thinking about sometimes) for different kinds of mappings. I'll definitely think about it.

**Comment by sassanh** [comment]
> Yeah, I've seen those. The thing is that there is no additional benefit to just rewriting it Lua.

Well, it can be beyond rewriting, we can add features or improve usage. One thing that bothers me in vim-repeat is that you need to write you lhs twice (once in keymap definition, and then in repeat call), then whenever you change the keymap you should be careful not to forget updating repeat call. So I have a helper function `rkeymap` which calls vim.keymap, with a wrapped version of the callback sent to it to automatically call repeat.

**Comment by echasnovski** [comment]
> So I've looked into adding dot-repeat to mappings for moving current line and it is not that simple. Usual approach of setting `'operatorfunc'` and using expression mapping doesn't work right away here. The main reason seems to be that `move_line()` itself uses some dot-repeatable actions which override the main one.
> 
> I'll give it another go, but my hopes are not high at the moment.

As much as I would like to support this, I don't see a reasonable way to introduce dot-repeat while preserving all current functionality in edge-cases. The thing is, that latter is done by essentially `"zdd` - `<Up>/<Down>` - `"zP` (or `"zp`). First and last steps are themselves dot-repeatable which breaks any my attempt to make whole function dot-repeatable.

Closing as "would love to support but don't think it is reasonably possible".
