### ISSUE TITLE
The WRAP functionality of the status line is annoying for those who have 'wrap' on all the time

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#3]
The default status line has a functionality for showing `WRAP` next to the mode name when `'wrap'` is on. I figure that this is intended to be helpful when you often switch the setting, but I don't think most Neovim users do that. I personally always have `'wrap'` on and the indicator is completely redundant. I understand that I could just copy the default config and remove the line, but I'm questioning if it should be included in the default in the first place. I don't think it's generally useful, since you can usually easily tell if `'wrap'` is on by looking at the screen. The same applies to SPELL for people who use it.

**Comment by echasnovski** [comment]
Hmmm. That seems like a valid point. I'll sleep on it and return to it tomorrow. Thanks.

**Comment by xigoi** [comment]
Great. Thinking about it, what if there was a way to modify the default config without having to copy the whole thing into your code? Would that be needlessly complex?
