### ISSUE TITLE
Add discussions tab

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#30]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

none

### Description

Use github's discussion tabs for casual questions.

**Comment by echasnovski** [comment]
Thanks for suggestion! Done.
