### ISSUE TITLE
Beta-testing 'mini.colors'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#301]
Please leave your feedback about new [mini.colors](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-colors.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by Iron-E** [comment]
As I said on Reddit, this module is fantastic. The _only_ thing I think could be improved is, when calling `:write`, test for the `background` value to preserve the original colorscheme file's light/dark variants.

(Just wanted to put it here, since a forum isn't the best place to track those things)

**Comment by echasnovski** [comment]
> As I said on Reddit, this module is fantastic. The _only_ thing I think could be improved is, when calling `:write`, test for the `background` value to preserve the original colorscheme file's light/dark variants.
> 
> (Just wanted to put it here, since a forum isn't the best place to track those things)

Thanks for the feedback!

Not exactly sure what you mean here. If you mean creating a file which checks for `'background'` and sources either one of the color schemes, then no it doesn't do that. And I don't think this is reasonable in the scope of this module.

General idea is that color scheme is basically a set of name, highlight group definitions, and terminal colors. Imagine like a snapshot: nothing conditional, only preserve the state.

If you want to make a color scheme with different highlights depending on the value of 'background' (which is totally reasonable), I'd suggest creating three variants of color scheme: `scheme_dark`, `scheme_light`, and `scheme` which conditionally sources either one depending on 'background'

I'll keep this "conditional on `'background'`" in mind. Maybe I'll find a reasonable way to add this.

**Comment by Iron-E** [comment]
Thanks for the workaround, I'll use that for now :)
