### ISSUE TITLE
[mini.completion] tries to trigger completion even when not available

### ISSUE THREAD

**Issue by fedemp** [echasnovski/mini.nvim#302]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

`mini.completion` is trying to trigger the completion even on buffers where it's not available.

![image](https://user-images.githubusercontent.com/735314/232502633-87a5b029-9024-49b1-80b0-1595d8bf6b45.png)

### Neovim version

0.9.0

### Steps to reproduce

1. Have `mini.completion` enabled.
2. In my case, I tried editing a `yaml` file even then I don't have any related server installed.

There are the registered lsp servers.

![image](https://user-images.githubusercontent.com/735314/232504656-af5b2753-19b2-49df-8c8a-0c7bc336e95d.png)

And this is my current `init.lua`

https://github.com/fedemp/dotfiles/blob/5cd40a99ec51eb4450dc6efe36f441d73f72a97e/home/.config/nvim/init.lua

### Expected behavior

`mini.completion` should not try to trigger onmicompletion.

### Actual behavior

![image](https://user-images.githubusercontent.com/735314/232502633-87a5b029-9024-49b1-80b0-1595d8bf6b45.png)

An error is shown every time I enter `insert` mode.

**Comment by echasnovski** [comment]
I still can not reproduce this. If you'll have a small and reliable way to reproduce this, please, add it here.
