### ISSUE TITLE
[mini.basics] Dot-repeat for go and gO

### ISSUE THREAD

**Issue by kiryph** [echasnovski/mini.nvim#303]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

basics

### Description

In vim-unimpaired, you can insert blank lines above and below with `[<space>` and `]<space` similar to `go` and `gO` from mini.basics. However, in vim-unimpaired you can press dot to insert more and more lines after the first `[/]<space>`.

I would like to have the same behaviour in mini.nvim. In particular for `gO` where you have to reach for the shift key dot-repeat is much more ergonomic.

**Comment by echasnovski** [comment]
Both `go` and `gO` now should support dot-repeat out of the box.
