### ISSUE TITLE
[mini.indentscope] request: ignore first indent

### ISSUE THREAD

**Issue by NickyTope** [echasnovski/mini.nvim#305]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

### Description

I love the animation and look of mini.indentscope but one thing that really stops me fully switch from indent-blankline is the ability to ignore the first indent `show_first_level_indent = false`.

I work in sometimes large typescript react files where most of the files is indented one level which makes the animation take too long (I have it sped up for this case) and doesn't provide useful information!

Is it possible to add an option to ignore this here?

**Comment by echasnovski** [comment]
Thanks for suggestion!

At the moment I don't think adding this meets the "features-maintenance" trade-off. I agree that speeding up animation in case of a large number of lines is probably the best thing to do. If you don't mind, could you share how you tweak animation to fit your taste?

I'll think about it.

Some semi-random thoughts:
- If anything, the option should be something like `minimal_indent` with minimal indent to draw (default to 0).
- The only concern here might be performance, but I don't think it will matter here *that* much.

**Comment by NickyTope** [comment]
My config is very simple for speeding these up, with just hard stops based on my usage:
```      require("mini.indentscope").setup({
        draw = {
          delay = 500,
          animation = function(_n, total)
            if total > 40 then
              return 0
            elseif total > 30 then
              return 2
            elseif total > 20 then
              return 5
            end
            return 15
          end,
        },
      })
```
This just speeds up the line rendering but I would still really like to have no line at all for the first level.. 

my own random thought: perhaps the animation function could receive the indent level as well and be able to return a table, something like `{wait: 10, symbol: ""}` then you could have different symbols at each level including blank (or nil?)

**Comment by echasnovski** [comment]
Sorry, I don't think this fits well in 'mini.indentscope'. This feels like either a very special case or a creeping possibility of too much configuration. If the main concern is a long animation, then customizing delay based on the number of lines in scope is the suggested solution here.
