### ISSUE TITLE
temporarily deactivate mini.animate since it breaks some macros

### ISSUE THREAD

**Issue by bergtholdt** [echasnovski/mini.nvim#307]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

When mini.animate is active, some macros may break if they use the cursor as context. I found this to happen especially if I use search in a macro with "/".

This might be difficult to fix, however it would be nicht to just temporarily deactivate animation while running a macro. It would be ok to do that manually, but I did not find a command for this.

### Neovim version

0.9

### Steps to reproduce

Example using sonme python file (with multiple function definitions "def my_func...()"

- Start a macro, e.g. with qq
- use "/def " to search for "def "
- esc to normal mode
- w to go to start of function name
- i to go into insert mode, insert some new prefix to be used for all functions
- esc to normal mode
- j to move down
- q to end macro

Now rerun the macro with @q and @@, instead of inserting at each occurrence the text get's inserted at arbitrary locations since the animation actually seems to emulated key strokes.
 
Of course this is a contrived example and could be replaced by `:%s /def /def prefix/g` or similar.

### Expected behavior

text gets inserted at every function definition

### Actual behavior

text get's inserted at arbitrary locations since the animation actually seems to emulated key strokes

**Comment by echasnovski** [comment]
> This might be difficult to fix, however it would be nicht to just temporarily deactivate animation while running a macro. It would be ok to do that manually, but I did not find a command for this.

In would indeed be not quite easy to do automatically when running macro as there seems to be no event triggering to hook into.

Did you try `:lua MiniAnimate.config.scroll.enable = false`? And then later `:lua MiniAnimate.config.scroll.enable = true`.

You can also create a mapping to toggle that with `'<Cmd>lua MiniAnimate.config.scroll.enable = not MiniAnimate.config.scroll.enable<CR>'` as right hand side.

**Comment by echasnovski** [comment]
I am relatively certain that the suggested approach should work here. If not, please, add more information here.
