### ISSUE TITLE
Autopairs for triple backticks

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#31]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

Single back tick(\`) outputs double backtick (\`\`) but adding another
backtick(third) should output 3 more backticks for codeblocks.

`code line`

```
code
block
```

**Comment by echasnovski** [comment]
Thanks for suggestion, but no, this won't get implemented. `mini.pairs` is intended to work only for single "open" and "close" characters. I feel that snippets are better for this kind of task.

**Comment by zim0369** [comment]
> Thanks for suggestion, but no, this won't get implemented. `mini.pairs` is intended to work only for single "open" and "close" characters. I feel that snippets are better for this kind of task.

What snippets?

Is there an alternative to triple backticks?

**Comment by echasnovski** [comment]
I meant that functionality of "Type something which expands to `` ``` ``` `` or similar" is more suited for snippets (predefined and configurable set of expandable text). More info:
- https://github.com/L3MON4D3/LuaSnip
- https://github.com/rafamadriz/friendly-snippets (in particular [this snippet](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/markdown.json#L77-L81), which you can modify to your taste)

**Comment by zim0369** [comment]
> I meant that functionality of "Type something which expands to `` ``` ``` `` or similar" is more suited for snippets (predefined and configurable set of expandable text). More info:
> 
> * https://github.com/L3MON4D3/LuaSnip
> * https://github.com/rafamadriz/friendly-snippets (in particular [this snippet](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/markdown.json#L77-L81), which you can modify to your taste)

Using snippets feels like an overkill. I will stick to nvim-autopairs for now
but I'd love to see this functionality getting implemented in mini.pairs.

**Comment by georgeguimaraes** [comment]
Hi, in the case for triple backticks, if I input the third backtick, can mini.pairs ignore it and not insert the fourth backtick?

**Comment by echasnovski** [comment]
> Hi, in the case for triple backticks, if I input the third backtick, can mini.pairs ignore it and not insert the fourth backtick?

Unfortunately no. See [this comment](https://github.com/echasnovski/mini.nvim/issues/31#issuecomment-1003724924).

**Comment by georgeguimaraes** [comment]
hmm I got it that we can't work with pairs of triple backticks. But can we ignore the second pair of single backticks? Like mini.pairs already ignore ' after a letter. 

Right now, after ``, if I hit ` again, I get 4 backticks and my cursor is between the third and fourth backtick.

**Comment by echasnovski** [comment]
> hmm I got it that we can't work with pairs of triple backticks. But can we ignore the second pair of single backticks? Like mini.pairs already ignore ' after a letter.
> 
> Right now, after ``, if I hit ` again, I get 4 backticks and my cursor is between the third and fourth backtick.

Ah, sorry, I misread my own comment.

But the answer is still a no, because 'mini.pairs' "knows" only about single character to its left and single character to its right when making a decision whether to insert a pair or not. So having a logic "if there are two backticks to the left then insert single backtick" is not designed to be done in 'mini.pairs'.

**Comment by georgeguimaraes** [comment]
got it! tks for the reply and for all the plugins

**Comment by Susensio** [comment]
Hey @georgeguimaraes , maybe this solution makes your life a little easier
https://github.com/echasnovski/mini.nvim/discussions/255

```
        ['`'] = { action = 'closeopen', pair = '``', neigh_pattern = '[^\\`].', register = { cr = false } },
```

This would avoid the _fourth_ backtick

**Comment by jesseleite** [comment]
@Susensio Love that solution, allows for pair, but not 4th backtick when doing triples. Thanks for sharing! I think this could be useful in default config to. What you think @echasnovski? 🙏

**Comment by echasnovski** [comment]
> @Susensio Love that solution, allows for pair, but not 4th backtick when doing triples. Thanks for sharing! I think this could be useful in default config to. What you think @echasnovski? 🙏

I don't think it is that useful as default, as it makes typing **6** backticks (which are needed to designate a codeblock) less comfortable. The fact that it can be configured that way should be enough.

**Comment by jesseleite** [comment]
Hey thanks for the reply @echasnovski! That's fair!

The thing I'm finding is that without that config, it doesn't complete the final three ticks, it only complete one fourth tick, if that makes sense. This is with standard markdown treesitter parser that ships with the official nvim-treesitter repo. Is this how it behaves for you?

![CleanShot 2024-10-08 at 00 16 49](https://github.com/user-attachments/assets/1d0027b2-2a93-4908-8625-81dae2ddbd40)

**Comment by echasnovski** [comment]
> Hey thanks for the reply @echasnovski! That's fair!
> 
> The thing I'm finding is that without that config, it doesn't complete the final three ticks, it only complete one fourth tick, if that makes sense. This is with standard markdown treesitter parser that ships with the official nvim-treesitter repo. Is this how it behaves for you?

Yes, it does. The reason is that 'mini.pairs' "knows" only about cursor's single character neighborhood (by design for easier code/logic and better performance) *and* it can insert only two-character pair (left and right). So it can not (and will not) work with triple backticks.

Here is the use case which I meant in "... it makes typing 6 backticks ... less comfortable":

https://github.com/user-attachments/assets/39063a24-c58b-4f05-8cae-eeb5dd46db86

But a long standing suggestion is to [use snippets](https://github.com/echasnovski/mini.nvim/issues/31#issuecomment-1003724924) for this type of functionality. With builtin `vim.snippet` it can be achieved with `vim.snippet.expand('```\n$0\n```')`.
