### ISSUE TITLE
Errors when jumping to only one possible target

### ISSUE THREAD

**Issue by nat-418** [echasnovski/mini.nvim#310]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.jump2d

### Description

When jumping to a unique target, I get the following error message: 
```
E5108: Error executing lua: ...Packages/start/echasnovski-mini.nvim/lua/mini/jump2d.lua:846: table index is nil
stack traceback:
        ...Packages/start/echasnovski-mini.nvim/lua/mini/jump2d.lua:846: in function 'spots_to_extmarks'
        ...Packages/start/echasnovski-mini.nvim/lua/mini/jump2d.lua:783: in function 'spots_show'
        ...Packages/start/echasnovski-mini.nvim/lua/mini/jump2d.lua:402: in function 'start'
```

### Neovim version

0.9.0

### Steps to reproduce

1. Write a file with contents like: 

```
a b c d
e f g h
i j k l
m n o p
```

2. Attempt to jump to the letter `g`.

### Expected behavior

If there is only one possible target, the jump should go directly there.

### Actual behavior

Throws the aformentioned error message.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce this: neither with minimal config nor in my usual setup with other plugins active. What is your 'mini.jump2d' setup?

**Comment by nat-418** [comment]
```lua
require('mini.jump2d').setup({
  view = {
    dim = true,
    n_steps_ahead = 2,
  },
  mappings = {
    start_jumping = ''
  }
})
```

seems to be a problematic interaction with `MiniJump2d.start(MiniJump2d.builtin_opts.single_character)`

**Comment by echasnovski** [comment]
Thanks again! It should be fixed on latest `main`.

It was possible to reproduce with default spotter with just single non-whitespace character showing. Indeed has more impact on `single_character` spotter.

**Comment by nat-418** [comment]
thanks for all the great plugins
