### ISSUE TITLE
mini.animate scrolls too much when exiting the terminal mode

### ISSUE THREAD

**Issue by qwertzui11** [echasnovski/mini.nvim#312]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

First of all: Thanks a lot for your work and time! :heart_eyes: 

When I use the `:terminal`, and output a lot lines, (eg when I build stuff) the `mini.animate` module introduces a very odd scroll behavior

### Neovim version

0.9.0

### Steps to reproduce

1. Create the file `minimal.lua` with the content

```lua
-- Minimal config based on the example in folke/noice.nvim to prevent it from using existing lazy plugins
-- https://github.com/folke/noice.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue
local root = vim.fn.fnamemodify("./nvim-repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	"echasnovski/mini.nvim",
	-- pinning the commit to the one where I experienced the issue
	commit = "9f1f555",
	config = function()
		require("mini.animate").setup({})
	end,
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
```

2. run `nvim -nu minimal.lua`
3. wait for the plugin installed
4. restart `nvim`
5. open a terminal with `:terminal`
6. get into terminal mode using `i`
7. emit some output eg using `cat`
8. exit the terminal mode using `C-<Leader>C-n`

### Expected behavior

It should just exit the terminal mode and NOT scroll at all.

### Actual behavior

Instead it jumps to, where the command started, and then scrolls (animation) back down

Video:

https://user-images.githubusercontent.com/220049/235211031-0540ce8f-b3bd-494c-ad0d-e9b6c730e816.mp4

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I experienced this myself. But not that frequently and without an obvious quick fix.

This seems to happen because scroll state is not up to date in this case. I'll look into it.

**Comment by echasnovski** [comment]
The fix was easier than I feared. Should be now fixed in `main` branch.

**Comment by qwertzui11** [comment]
Tested and verified! Thx for your time and great work! :heart_eyes:
