### ISSUE TITLE
Wrong `at` and `it` for html tag with "-"

### ISSUE THREAD

**Issue by jqhr** [echasnovski/mini.nvim#314]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

ai, surround

### Description

For vue, svelte or other template language, textobj "at" or "it"  only work for common tag without "-". For example div
![图片](https://user-images.githubusercontent.com/23305067/235364482-16fe5b0b-b853-414a-9848-30f482c11a8f.png)
But for "el-dropdown-menu", it dones select  tag "el-dropdown-menu", but select the outer tag "template", because "template" has no "-"
![图片](https://user-images.githubusercontent.com/23305067/235364668-236d51eb-b372-4f65-ae8d-0b36779e58d2.png)

### Neovim version

0.9.0

### Steps to reproduce

use "vat" or "vit" on html tag with "-"

### Expected behavior

![图片](https://user-images.githubusercontent.com/23305067/235364744-f106bd88-45e1-49c6-9f58-40dcef14e326.png)

### Actual behavior

![图片](https://user-images.githubusercontent.com/23305067/235364755-1a6add9f-f2cb-4a82-aadb-0dc7a69486ec.png)

**Comment by jqhr** [comment]
I have not install `nvim-treesitter`.
The nvim default textobj "at" or "it"  was correct. but "mini.ai" or "mini.surrount" was wrong

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, tag implementation in 'mini.ai' relies on an appropriate Lua patterns to match a tag region. I would strongly suggest using tree-sitter to get more proper information about tag structure. Something like how it this mentioned in [this comment](https://github.com/echasnovski/mini.nvim/issues/110#issuecomment-1212277863).

However, you can still customize tag textobject to include punctuation in tag name by slightly modifying built-in one like this:

```lua
require('mini.ai').setup({
  custom_textobjects = {
    t = { '<([%p%w]-)%f[^<%w][^<>]->.-</%1>', '^<.->().*()</[^/]->$' }
  }
})
```

**Comment by jqhr** [comment]
Thanks.
The treesitter has so many bugs for template language filetypes. so I cannot use it.
For  custom_textobject of example, it was incorrrect.
For example 
![图片](https://user-images.githubusercontent.com/23305067/235592442-dd9e4a4d-5b51-4b06-883b-03550f1503ce.png)
I want to select `vat` for template.
The correct is
![图片](https://user-images.githubusercontent.com/23305067/235592611-7b14700b-284d-4a00-84a1-6e45821d6f32.png)

**Comment by echasnovski** [comment]
Those two options (using tree-sitter and customizing built-in pattern) are the only ones available right now, sorry.
