### ISSUE TITLE
add explicit `@symbol` highlight group

### ISSUE THREAD

**Issue by CosmicToast** [echasnovski/mini.nvim#317]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

base16

### Description

While nvim-treesitter does export a lot of capture groups as built-in neovim groups, some are unaffected.
A particularly relevant one is the `@symbol` capture group, which refers to atoms (the most common term).
Atoms are essentially immutable strings with different comparison semantics, used in several languages such as Elixir, many lisps, and others.
They're very commonly used, and need to be differentiable from variables, but by default the highlight groups end up the same under Mini16.
I've achieved this in my theme temporarily using `vim.api.nvim_set_hl(0, '@symbol', { fg = palette.base0E })`, which roughly matches what non-compliant (since `@symbol` is the correct capture to use) grammars use.
The equivalent in `base16.lua` would be `hi('@symbol', { fg=p.base0E, bg=nil, attr=nil, sp=nil})`, which I would submit if I was sure that this is the desirable outcome.
While `@symbol` is the specific one of note for me today, it may be interesting to set up highlight groups for all the treesitter groups (though it is also out of scope for today).

**Comment by echasnovski** [comment]
Thanks for constructive suggestion! (And special thanks for opening an issue first and not PR straight away)

Around couple of weeks ago I'd reject right away, but since then I decided to add **selective** tree-sitter support. I'll take a look at what base color might suit best (`base0C` looks like a good option as it is used for `Special` which is described as "any special symbol") and update it myself.

**Comment by echasnovski** [comment]
Thanks again for suggestion! I decided to go with "same as `Keyword`" (the one you suggested), as it indeed seems to be the most appropriate choice here.
