### ISSUE TITLE
Modify "HJKL" in mini.basics similar to mini.move

### ISSUE THREAD

**Issue by joshsurber** [echasnovski/mini.nvim#320]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.basicr

### Description

HJKL navigation is used in a couple of spots in basics, as well as in move. However, in move, they can be customized but can't in basics. This would be a very nice feature to have for people who use other keys to move (alternate layout users, for example).

**Comment by echasnovski** [comment]
Could you, please, clarify what you mean? Do you want 'mini.basics' contain configurable keys where now `hjkl` is used? Like in `mappings.window` instead of `<C-hjkl>` it could create something different?

**Comment by joshsurber** [comment]
Yes, very sorry, I'm requesting the window navigation and insert mode cursor movements be configurable like the line and selection movement is. For my use case I'd like HNEI to match the colemak layout, but I'm sure others would have other use cases.
