### ISSUE TITLE
mini.splitjoin with hanging indent

### ISSUE THREAD

**Issue by gerazov** [echasnovski/mini.nvim#324]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.splitjoin

### Description

It would be nice to be able to turn on hanging indents on split join in Python, i.e.:
```python
i = [1, 2, 3]

# mini.splitjoin

i = [
    1,
    2,
    3,
    ]
```

There was a setting for this in https://github.com/AndrewRadev/splitjoin.vim :

```vim
vim.g.splitjoin_python_brackets_on_separate_lines = 1
```

**Comment by echasnovski** [comment]
Thanks for suggestion!

'mini.splitjoin' can be customized with hooks. Something [like this](https://github.com/echasnovski/mini.nvim/blob/50ade2218c2ad32b1c6421ea500adaad01fa476f/doc/mini-splitjoin.txt#L365-L381). Here is a [starting point](https://github.com/echasnovski/mini.nvim/blob/50ade2218c2ad32b1c6421ea500adaad01fa476f/doc/mini-splitjoin.txt#L211) to read about them. It is not planned to have such specific options as you mentioned, unfortunately.

Would you mind clarifying what exactly you mean here? I might be able to help you set this up. Preferably with example of "before" and "after".

**Comment by echasnovski** [comment]
So if I understand correctly, you want to also increase indent of last line (along with other inner ones). Here is the post split hook for that:

```lua
local hang_indent = function(split_positions)
  -- Increase indent of the last split
  local last_split = split_positions[#split_positions]
  local line, col = last_split.line - 1, last_split.col - 1
  local pad = vim.bo.expandtab and string.rep(' ', vim.fn.shiftwidth()) or '\t'
  vim.api.nvim_buf_set_text(0, line, col, line, col, { pad })
end
```

If you want this only for square brackets, here is possible solution:

```lua
local hang_indent = function(split_positions)
  -- Increase indent of the last split only inside square brackets 
  local last_split = split_positions[#split_positions]
  local line, col = last_split.line - 1, last_split.col - 1

  local is_square = vim.fn.getline(line + 1):sub(col + 1, col + 1) == ']'
  if not is_square then return end

  local pad = vim.bo.expandtab and string.rep(' ', vim.fn.shiftwidth()) or '\t'
  vim.api.nvim_buf_set_text(0, line, col, line, col, { pad })
end
```

If you want to use this only for Python, I'd recommend creating 'after/ftplugin/python.lua' file with the following code:

```lua
if _G.MiniSplitjoin ~= nil then
  local hang_indent = function(split_positions)
    -- Enter code which you prefer
  end

  vim.b.minisplitjoin_config = { split = { hooks_post = { hang_indent } } }
end
```

If you want this globally, set this config inside `require('mini.splitjion').setup()`.

Does this solve your problem?

**Comment by gerazov** [comment]
Awesome! It would've taken me a long time to do this myself :sweat_smile: 

Maybe this can be added in the docs?

**Comment by echasnovski** [comment]
> Maybe this can be added in the docs?

Having it in this issue seems to be fine for now.
