### ISSUE TITLE
Uncommenting comments with the comment treesitter parser installed

### ISSUE THREAD

**Issue by oncomouse** [echasnovski/mini.nvim#325]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

I'm having an issue with mini.comment, trying to uncomment lines that are commented out. If I'm in lua file with comments, such as this one:

```lua
local f  = function(a, b, c)
  -- return a + b + c
end
```

And try to uncomment the commented line, I get:

```lua
local f  = function(a, b, c)
  # -- return a + b + c
end
```

I have the [comment](https://github.com/stsewd/tree-sitter-comment) treesitter parser installed. If I run `lua vim.print(vim.filetype.get_option("comment", 'commentstring'))` in Neovim, "# %s" is returned.

I suspect the [`H.get_commentstring`](https://github.com/echasnovski/mini.nvim/blob/50ade2218c2ad32b1c6421ea500adaad01fa476f/lua/mini/comment.lua#L358-L440) is getting to this filetype option and the error I'm seeing is the result.

I didn't have this problem with [nvim-ts-context-commentstring](https://github.com/JoosepAlviste/nvim-ts-context-commentstring).

Running `TSUninstall comment` and reopening the file fixes this issue.

### Neovim version

v0.10.0-dev-323+g6a273af10

### Steps to reproduce

1. `:TSInstall comment`
2. Open lua file with commented content
3. Try to uncomment line

### Actual behavior

The commented line has `# ` appended.

**Comment by clason** [comment]
Please provide a full, minimal, reproducing example. This works fine for me.

**Comment by echasnovski** [comment]
Thanks for the issue. I can not reproduce (even with 'comment' , as 'comment' filetype doesn't have 'commentstring' option set by default.

It seems like something in your config sets it. It might set at least through following mechanisms:
- Autocommands. What is the output of `:au FileType comment`?
- Filetype plugins. What is the output of `:=vim.api.nvim_get_runtime_file('ftplugin/comment*', true)`?

**Comment by clason** [comment]
Here's your issue: https://github.com/oncomouse/dotfiles/blob/72c545d59ea4097584158e6a6e0bbed07a6cbc6f/conf/vim/init.lua#L59

comment.nvim requires an empty default commentstring to know when to look for containing tree-sitter regions. (This is how Neovim behaves by default, and you should not change it.)

**Comment by echasnovski** [comment]
It seems that you [set default 'commentstring'](https://github.com/oncomouse/dotfiles/blob/master/conf/vim/init.lua) in your config.

**Comment by oncomouse** [comment]
Got it. Commenting out the line where I set commentstring fixes the problem.

**Comment by echasnovski** [comment]
I've added note about this to both README and help page. Thanks for suggestion!
