### ISSUE TITLE
feature-request, mini.pairs support select mode

### ISSUE THREAD

**Issue by 2nthony** [echasnovski/mini.nvim#327]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

using luasnip

<img width="625" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/19513289/47a5ae5d-a105-450e-b9fb-d83d6ad700a1">

input the `{`

<img width="625" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/19513289/f213a2c9-fe15-42c7-b8a8-903fad5469be">

i am expect the result is

```lua
vim.api.nvim_create_autocmd('FileType', {|}) -- | is the input cursor
```

PS: my neovim setup is from [LazyVim](https://github.com/LazyVim/LazyVim)

**Comment by echasnovski** [comment]
Thanks for suggestion!

I can not reproduce this: with LuaSnip and snippets I have this working as you expect. In particular, I use plain `require('mini.pairs').setup()` and this snippet:
```json
  "fori": {
    "prefix": "fori",
    "body": "for ${1:idx},${2:val} in ipairs(${3:table_name}) do\n\t$4\nend$0",
    "description": "for .. ipairs()"
  },
```

Right after expanding it (with LuaSnip's own `expand_or_jump()` function) I have `idx` selected in Select mode. Pressing single `(` leads to inserting `()` and cursor ending up in between them.

Couple of questions:
- Do you have pairs set up in Insert mode? What does `imap {` say?
- What does `smap {` and `vmap {` say? Maybe they are somehow remapped in Select mode.
- How do you expand snippet? With plain `LuaSnip` or with 'nvim-cmp'? Does it work if expanded with another method from these two?

**Comment by 2nthony** [comment]
Thanks to remind me `smap {`😅, now I figure it out the reason is I have https://github.com/gbprod/cutlass.nvim plugin.
