### ISSUE TITLE
mini.align question

### ISSUE THREAD

**Issue by albertfgu** [echasnovski/mini.nvim#328]
I recently migrated from vim-easy-align to mini.align; thanks for the amazing plugins! It's working out of the box for my use case, except for one minor detail that's confusing me. When I align a table on `&`, all the columns are shrunk to the smallest possible width, except the first column is much larger than expected. See screenshot:

![image](https://github.com/echasnovski/mini.nvim/assets/8164679/5b57e82b-1032-4d99-aeea-abf095d5775d)

I apologize if this question has been answered in other documentation

**Comment by echasnovski** [comment]
Columns are not shrunk, but the opposite - they are padded (from left and/or right). Try using `trim` step with custom merge character. 

That is:
- Visually select region to be aligned.
- Press `gA` to initiate interactive align.
- Press `&` to align by it.
- Press `t` to trim whitespace.
- Press `m` followed by `<Space>` and `<CR>` (Enter).
