### ISSUE TITLE
BUG: inside next brace (inB) selects surrounding braces

### ISSUE THREAD

**Issue by ten3roberts** [echasnovski/mini.nvim#330]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

ai

### Description

Using *inside next Brace"*(`inB`) textobject, the surrounding braces will be selected instead rather than the *next* nested braces.

`this is an example {}` will be selected rather than `` (inside `{}`)

omap says that this is caused by mini, but it may also be a fallback to a builtin textobject

```
:omap inB

o  in            <Lua 1089: ~/.local/share/nvim/lazy/mini.nvim/lua/mini/ai.lua:1120>
                 Inside next textobject
o  i             <Lua 1082: ~/.local/share/nvim/lazy/mini.nvim/lua/mini/ai.lua:1120>
                 Inside textobject

```

### Neovim version

NVIM v0.10.0-dev-1696+g189e21ae5-Homebrew

### Steps to reproduce

```
{ this| is an example {} }
```

`|` being the cursor

`vinB`

### Expected behavior

Inside of `{}` is selected

### Actual behavior

Inside of `{ this is an example {} }` is selected

**Comment by echasnovski** [comment]
Yes, this is a fallback to Neovim's built-in textobject, as there is no `B` textobject in 'mini.ai'. Try `vinb` instead.

**Comment by ten3roberts** [comment]
Thanks for the quick response.

Maybe `B` should be aliased to brace like in neovim.

using `vinb` will select parenthesis as well.

My main use case for the motion is going inside the function body in rust while on the signature.

**Comment by echasnovski** [comment]
> Maybe `B` should be aliased to brace like in neovim.

I'd rather reserve this for users to decide, as having duplicating functionality doesn't seem like a good design.
