### ISSUE TITLE
mini.backeted: automatically enables treesitter, even if not wanted / no config option to disable

### ISSUE THREAD

**Issue by matu3ba** [echasnovski/mini.nvim#331]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.backeted

### Description

Relevant treesitter config:
```lua
require('nvim-treesitter.configs').setup {
  -- ensure_installed = 'maintained',
  ensure_installed = { 'bash', 'c', 'cpp', 'julia', 'lua', 'python', 'rust', 'typescript', 'vim', 'vimdoc', 'zig' },
  auto_install = true,

  highlight = {
    enable = false,
    additional_vim_regex_highlighting = false,
    -- nvim gcc/c-family/c-common.cc from git://gcc.gnu.org/git/gcc.git
    -- freezes editor and configured clangd provides us with highlighting
    -- zig does not need treesitter for highlighting (zls also provides info)
    disable = { 'c', 'cpp', 'zig' },
  },
  -- Note, that vib also works for blocks (symbols might be desirable)
  incremental_selection = {
    enable = false,
    keymaps = {
      init_selection = '<leader>vs',
      node_decremental = 'gsN',
      node_incremental = 'gsn',
      scope_incremental = 'gss',
    },
    disable = { 'c', 'cpp', 'zig' }, -- slow, so opt-in
  },
  indent = {
    enable = false,
    disable = { 'c', 'cpp', 'python', 'zig' }, -- broken
  },
}
```

### Neovim version

HEAD master

### Steps to reproduce

1. `nvim -nu minimal1.lua some.cpp` (without mini.bracketed) [T and ]T have no effect. Also only installing mini.bracketed has no effect as the config is not run:
```lua
  {
    'echasnovski/mini.bracketed',
    version = false,
    config = function() require('mini.bracketed').setup {} end,
  },
```
2. `nvim -nu minimal2.lua some.cpp` (with mini.bracketed installed) [T and ]T jump to treesitter objects, even though I dont want to use treesitter.

### Expected behavior

No active treesitter. Upstream should provide a sane way to decide, if treesitter is active or not and/or at least a convention how plugins should provide an interface instead of only offering it per plugin https://neovim.discourse.group/t/check-if-treesitter-is-enabled-in-the-current-buffer/902 and guessing if the config has been run or changed with `:TSConfigInfo`.

Treesitter should be configurable as opt-in due to problematic behavior ie 
`nvim gcc/c-family/c-common.cc` from git://gcc.gnu.org/git/gcc.git freezes editor and configured clangd provides  highlighting. (runs out of memory, but thats another story)

Upcoming changes https://github.com/nvim-treesitter/nvim-treesitter/issues/4767 might provide this.

### Actual behavior

Active treesitter.

**Comment by echasnovski** [comment]
Thanks for the issue!

I am not sure I follow you here.

Here is what I see:
- You have tree-sitter for 'cpp' installed (it is listed in `ensure_installed`), which means that is is automatically attached to a buffer with `cpp` filetype. You can verify this by running `:InspectTree` in `cpp` buffer without 'mini.bracketed' installed: it should show parsed tree structure (although you disabled all its built-in capabilities).
- Yes, mappings `[T` and `]T` don't work without 'mini.bracketed' and do work with 'mini.bracketed' (as they are defined in it).

If you don't want tree-sitter for `c` and `cpp`, is there something preventing you from *not installing* specific parsers?

**Comment by matu3ba** [comment]
> (it is listed in ensure_installed), which means that is is automatically attached

Thanks for the kind words and quick clarification.

Ugh. I really dont like the behavior of `installed == loading`.
Feel free to close then or leave it open to nudge upstream into fixing this.
