### ISSUE TITLE
mini.map: integration highlights not working.

### ISSUE THREAD

**Issue by mrshmllow** [echasnovski/mini.nvim#333]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

map

### Description

mini.map integration highlights do not work. added lines are expected to be green in the map.

![image](https://github.com/echasnovski/mini.nvim/assets/40532058/be30d917-b9f6-43a6-9cd8-87b14dee77f4)

### Neovim version

NVIM v0.10.0-dev-354+g24b60b0f7 (24b60b0f71e0ffbd09c827230ecb5a37e833cade)

### Steps to reproduce

1. Use this minimal config

```lua
...

require("lazy").setup({
	{
		"catppuccin/nvim",
		name = "catppuccin",
		priority = 1000,
		opts = {
			intergration = {
				mini = true,
			},
			custom_highlights = function(colors)
				return {
					MiniMapNormal = { fg = colors.surface0 },
					MiniMapSymbolCount = { fg = colors.mauve },
					MiniMapSymbolLine = { fg = colors.surface1 },
					MiniMapSymbolView = { fg = colors.surface0 },
				}
			end,
		},
		config = function(_, opts)
			require("catppuccin").setup(opts)

			vim.cmd.colorscheme("catppuccin")
		end,
	},
	{
		"lewis6991/gitsigns.nvim",
		opts = true,
	},
	{
		"echasnovski/mini.map",
		version = false,
		dependencies = "lewis6991/gitsigns.nvim",
		lazy = false,
		keys = { ... },
		config = function()
			local map = require("mini.map")
			map.setup({
				integrations = {
					map.gen_integration.gitsigns({
						add = "GitSignsAdd",
						change = "GitSignsChange",
						delete = "GitSignsDelete",
					}),
				},
				symbols = {
					encode = map.gen_encode_symbols.block("3x2"),
				},
				window = {
					show_integration_count = true,
				},
			})
		end,
	},
}, {
	change_detection = {
		notify = false,
	},
})
```

2. Open a tracked file and modify some lines. The highlights are simply not shown. We can doubly check that the integrations do actually exist by running `:= MiniMap.gen_integration.gitsigns()()`, and the highlights are somehow the issue.

Am i missing something?

### Expected behavior

Highlights are applied to affected minimap lines.

### Actual behavior

Lines remain on their default highlighting

**Comment by echasnovski** [comment]
Thanks for detailed issue!

Today I had to use Neovim nightly and just noticed this myself. Spent several hours finding the culprit which ended up being my own recklessness. Pushed the fix several minutes ago.

Could you try the latest `main`?
