### ISSUE TITLE
N and P not usual in mini.starter

### ISSUE THREAD

**Issue by icyrainz** [echasnovski/mini.nvim#335]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

For the mini.starter, it seems like the N and P items shortcut key to go to the item starting with that character does not work.
It seems to interpret it as literal N and P key that tries to search the next item as well as pasting from register. Other characters work for me.

My current config:
```
starter.setup({
			content_hooks = {
				starter.gen_hook.adding_bullet(""),
				starter.gen_hook.aligning("center", "center"),
				starter.gen_hook.indexing("all", {
					"Git",
					"Telescope",
					"Plugins",
					"Builtin actions",
				}),
			},
			evaluate_single = true,
			footer = os.date(),

			header = table.concat({
				[[  /\ \▔\___  ___/\   /(●)_ __ ___  ]],
				[[ /  \/ / _ \/ _ \ \ / / | '_ ` _ \ ]],
				[[/ /\  /  __/ (_) \ V /| | | | | | |]],
				[[\_\ \/ \___|\___/ \_/ |_|_| |_| |_|]],
				[[───────────────────────────────────]],
			}, "\n"),
			query_updaters = [[abcdefghilmoqrstuvwxyz0123456789_-,.ABCDEFGHIJKLMOQRSTUVWXYZ]],
			items = {
				starter.sections.recent_files(9, true, false),
				{ action = "Telescope find_files", name = "F: Find Files", section = "Telescope" },
				{ action = "Telescope projects", name = "P: Projects", section = "Telescope" },
				{ action = "tab G", name = "G: Fugitive", section = "Git" },
				{ action = "Lazy", name = "M: Package Manager", section = "Plugins" },
				-- { action = "enew", name = "N: New Buffer", section = "Builtin actions" },
				{ action = "qall!", name = "Q: Quit Neovim", section = "Builtin actions" },
			},
		})

		vim.cmd([[
  augroup MiniStarterJK
    au!
    au User MiniStarterOpened nmap <buffer> j <Cmd>lua MiniStarter.update_current_item('next')<CR>
    au User MiniStarterOpened nmap <buffer> k <Cmd>lua MiniStarter.update_current_item('prev')<CR>
    au User MiniStarterOpened nmap <buffer> <C-n> <Cmd>lua MiniStarter.update_current_item('next')<CR>
    au User MiniStarterOpened nmap <buffer> <C-p> <Cmd>lua MiniStarter.update_current_item('prev')<CR>
  augroup END
]])
```

More of my dotfiles is here: https://github.com/icyrainz/.dotfiles/tree/master/nvim

### Neovim version

0.9.0

### Steps to reproduce

1. Install nvim.starter
2. Add items starting with N or P
3. Try pressing N or P

### Expected behavior

The item starting with N or P should be selected

### Actual behavior

It tries to perform literal action of N or P key

**Comment by echasnovski** [comment]
In your setup keys 'N' and 'P' are missing in `query_updaters`. That is why they don't act like query updaters.

Also 'j', 'k', 'n', 'p' are missing.

Add them and it should work.

**Comment by icyrainz** [comment]
Thanks for checking. I was copying this query_updater config from some other place without knowing that it's missing a few characters in it.
