### ISSUE TITLE
[mini.comment] Error when commenting lines via gcc and similar commands

### ISSUE THREAD

**Issue by redxtech** [echasnovski/mini.nvim#336]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

I am not able to use `gcc` to comment out a line or a block of text anymore.

Whenever I try, this I will get the following error:

```
E5108: Error executing lua ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:160: nvim_exec(): Vim(lua):E5108: Error executing lua ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:392: attempt to call field 'get_filetypes' (a nil value) stack traceback: ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:392: in function 'traverse' ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:403: in function 'get_commentstring' ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:345: in function 'make_comment_parts' ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:215: in function 'toggle_lines' [string ":lua"]:1: in main chunk [C]: in function 'cmd' ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:160: in function 'operator' [string ":lua"]:1: in main chunk stack traceback: [C]: in function 'cmd' ....local/share/nvim/lazy/mini.comment/lua/mini/comment.lua:160: in function 'operator' [string ":lua"]:1: in main chunk
```

### Neovim version

NVIM v0.9.0-dev-1184+g0ecb4d725

### Steps to reproduce

Using `lazyvim`:

`nvim <file>`

`gcc` a line, or `gc` a visual selection.

### Expected behavior

The line/selection should get commented.

### Actual behavior

Nothing happens except the error described above.

**Comment by redxtech** [comment]
I'm not alone with this issue, it's also here:
https://github.com/LazyVim/LazyVim/discussions/777

**Comment by echasnovski** [comment]
Thanks for the issue!

Is there a reason you still use development version of Neovim 0.9 even though there was already an official release? The error is there because 'mini.comment' uses some functionality from Neovim 0.9 **if** it can detect that version. In your case it detects it, but due to not being the released one it doesn't have a necessary functionality.

I recommend either updating Neovim to current stable release 0.9 or downgrading to 0.8. Development versions of previous release are not supported.

**Comment by redxtech** [comment]
Aha, thanks!

I hadn't updated it in a while, that certainly fixed it right up!

Thanks!
