### ISSUE TITLE
custom icons for different diagnostics severity and  maybe separate hl for it

### ISSUE THREAD

**Issue by hornyjailfish** [echasnovski/mini.nvim#337]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statuline

### Description

way to change `diagnostic_level.sign`
with additional option to `section_diagnostics(args)` like this
```lua
MiniStatusline.section_diagnostics({
  sign ={
     error = "",
     warn = "",
     ...
  },
  hl = {
    error = "",
    ...
  },
})
```
right now i "must" use lsp-status plugin because i dont want completely rewrite lsp section myself to be colorfull and using icons

**Comment by echasnovski** [comment]
Thanks for suggestion!

'mini.statusline' is designed to be minimal and rely on *user-written* customization via writing own functions. So I don't think supporting this much customization is aligned with the module's design.

For what it is worth, you don't **have to** use another plugin:
- To get the number of diagnostic entries with specific severity. Use `#vim.diagnostic.get(0, { severity = vim.diagnostic.severity.ERROR })` for errors and so on.
- To add highlighting, either use `MiniStatusline.combine_groups` with entry for each diagnostic level or add them manually (see `:h statusline`).
