### ISSUE TITLE
[mini.completion] Make signature help to not overlap lines

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#338]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

In a scenario where function arguments are wrapped on their respective lines to comply with wrap limits, placing the cursor after one of the parameter commas results in an unintended "overlaps" of the preceding line by the signature helper.

### Neovim version

v0.9.0

### Steps to reproduce

1. Write a function that triggers signature helper.
2. Wrap arguments onto their individual lines.
3. Place the cursor following a comma in one of the arguments.

### Expected behavior

It is expected that the signature helper consistently appears above the function line, regardless of cursor position and/or parameter wrapping.

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/7c9e3403-aac0-4d4b-bbd7-42f095a71f88)

[Screencast from 2023-05-24 14-09-55.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/3da3a667-ea1e-40bf-b2cb-4f06123dfb17)

**Comment by echasnovski** [comment]
Thanks for suggestion!

Do I understand you correctly: in you video example you always expect signature window to be located above the first visible line (`auto d ...` one)?

The main reasons for the current behavior (open above cursor line) are:
- It seems more ergonomic to see this information right where you are typing as you are already looking at that area.
- It is relatively easy to implement.

**Comment by echasnovski** [comment]
Hmmm... Thanks for the feedback! Never cover the text does sound interesting.

I'll think about it, but I don't have high hopes right now that it will be implemented.

**Comment by wroyca** [comment]
> Hmmm... Thanks for the feedback! Never cover the text does sound interesting.
> 
> I'll think about it, but I don't have high hopes right now that it will be implemented.

Thank! Ping me if you do in the end.




> Hmmm... Thanks for the feedback! Never cover the text does sound interesting.
> 
> I'll think about it, but I don't have high hopes right now that it will be implemented.

Thank! I appreciate the consideration - ping me if you decide to go through with it.

**Comment by echasnovski** [comment]
I've thought about implementing this and I think it is not that trivial to make it have good usability. Main reason is that lines can be long enough to make "show signature to not hide text" rule somewhat annoying.

Thanks for suggestion, though!

Closing this as not planned.

**Comment by echasnovski** [comment]
> @echasnovski Thank for looking into it regardless! - If you don't mind, can you elaborate a little more should I wish to look into it on my own?

Sure. For reference, here is the [code which computes config of signature help floating window](https://github.com/echasnovski/mini.nvim/blob/a2bafb341894044e887e209fc013bf955371f9ae/lua/mini/completion.lua#L1195-L1232). It basically opens exactly to the right of cursor either at line above (most of the time) or below (if not enough space above).

The only way I considered altering this to not cover text is to possibly shift the window to right until it is not over any character. This is both:
- Difficult to do in general case because window can have multiple lines.
- Not universal enough because even in successful case it might end up too much to the right that it becomes unusable.
