### ISSUE TITLE
Beta-testing 'mini.hipatterns'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#339]
Please leave your feedback about new [mini.hipatterns](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-hipatterns.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by assistcontrol** [comment]
Regarding the doc discussion about mini.completion flickering, where it says to ensure that delay.completion is less than delay.text_changed it might be worth adding, “(which it is by default)”. And maybe clarify that the flickering issue can occur “if the completion and/or hipatterns delays are modified from their defaults.”

As it reads now it looks like the two modules shouldn’t be used together.

**Comment by echasnovski** [comment]
> Regarding the doc discussion about mini.completion flickering, where it says to ensure that delay.completion is less than delay.text_changed it might be worth adding, “(which it is by default)”. And maybe clarify that the flickering issue can occur “if the completion and/or hipatterns delays are modified from their defaults.”
> 
> As it reads now it looks like the two modules shouldn’t be used together.

Thanks for this observation (and actually reading help pages :) ). To me it didn't sound like, but I updated it with more careful wording.

**Comment by jamapag** [comment]
@echasnovski, do you plan to add short hex color support `#rgb`?

**Comment by echasnovski** [comment]
> @echasnovski, do you plan to add short hex color support `#rgb`?

Not really, at the moment, no. I feel that it shouldn't be that much code to add custom highlighters:
- Pattern is essentially `'#%x%x%x%f[%X]'`.
- Group computation and computation should also be relatively straightforward. The only big problem here is to compute the proper foreground color (black or white) based on lightness of the color. 'mini.hipatterns' does a [somewhat fancy Oklab approach](https://github.com/echasnovski/mini.nvim/blob/a508fc9c737045c5d8d194dcb6e9556c44309bb9/lua/mini/hipatterns.lua#L784-L812), but there are simpler formulas than that.

It might end up as a recipe of some sort somewhere.

**Comment by echasnovski** [comment]
> I'd like to do a highlighter like this:
> 
> ```lua
> todo = {
> 	pattern = '%f[%w]()(FIXME|HACK|NOTE|TODO|WIP|XXX)()%f[%W]',
> 	group = 'Todo',
> },
> ```
> 
> but lua doesn't have non-capturing groups AFAIK, so I can't do it withou the `()` end position capture breaking. Just doing multiple highlighters to work around it is okay though.

Well, yes, Lua doesn't allow this approach. That is why [documented common use cases](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-hipatterns.txt#L196) has them separately.

**Comment by beardedsakimonkey** [comment]
In case anyone finds it helpful, here's a highlighter for vim's builtin named colors (found in $VIMRUNTIME/rgb.txt):
```lua
local hipatterns = require'mini.hipatterns'
local color_map = vim.api.nvim_get_color_map()
hipatterns.setup({
    highlighters = {
        named_color = {
            pattern = '%w+',
            group = function(_, match)
                local color = color_map[match]
                if color == nil then return nil end
                local hex = require'bit'.tohex(color, 6)
                return hipatterns.compute_hex_color_group('#' .. hex, 'bg')
            end
        },
    },
})
```

**Comment by echasnovski** [comment]
> In case anyone finds it helpful, here's a highlighter for vim's builtin named colors (found in $VIMRUNTIME/rgb.txt):

Nice one!

I have a suggestion for a slight performance improvement. You can fully pre-compute hex colors in color map like this:
```lua
color_map = vim.tbl_map(
  function(dec) return string.format('#%06x', dec) end,
  vim.api.nvim_get_color_map()
)
```

**Comment by calops** [comment]
It seems the plugin tries to be smart when using the color groups specified for any highlight. Is there any reason to disable that and just have it use the groups raw? For example, I don't think there is a way currently to affect the foreground color of the highlight, is there?

**Comment by echasnovski** [comment]
> It seems the plugin tries to be smart when using the color groups specified for any highlight. Is there any reason to disable that and just have it use the groups raw? For example, I don't think there is a way currently to define the foreground color of the highlight, is there?

I am not sure what you mean by "use the groups raw". It uses highlight group specified in `group` field of highlighter.

Do you mean highlight groups for hex colors? Yes, it does try to be smart with foreground colors in order to have the most readable text possible. It uses either black or white depending on color's (background's) lightness.

Currently there is no way of customizing this through function argument. If you don't like the approach, it is possible to write own callable `group` which will compute and possibly define custom highlight groups.

Other than that, you can customize colors by defining and using your own highlight groups.

**Comment by calops** [comment]
Alright, my bad then. It seems I did something wrong somewhere because the foreground color of my groups doesn't get applied.

**Comment by echasnovski** [comment]
> Alright, my bad then. It seems I did something wrong somewhere because the foreground color of my groups doesn't get applied.

If you are on Neovim>=0.9 try executing `:Inspect` when cursor is on suspicious highlighting. It will show what currently affects highlighting. Maybe foreground gets overridden by something else? I vaguely remember having something similar with tree-sitter, or semantic tokens, or diagnostics. It was the result of having default `priority` not high enough to override what was also placed there.

**Comment by calops** [comment]
Indeed, I had some shenanigans going on, thanks!

Looking good so far:
![image](https://github.com/echasnovski/mini.nvim/assets/4097716/a367f11c-d087-4aa1-8213-8eaf5aecd8de)

Next challenge is being able to color every group exactly as described within the `{}`. I feel like I'm going to need to do a lot of parsing by hand to achieve this, and obviously it will only work for one-liners, but I guess that's good enough.

**Comment by echasnovski** [comment]
> Looking good so far:

Can confirm, looks really interesting.

> Next challenge is being able to color every group exactly as described within the `{}`. I feel like I'm going to need to do a lot of parsing by hand to achieve this, and obviously it will only work for one-liners, but I guess that's good enough.

May I ask what is you end goal here? Can't quite figure it out.

Side note: if you want a more automated highlight group creation, take a look into refactoring single `style` field into boolean fields for each "substyle". Just as a valid value of `nvim_set_hl()`.

**Comment by calops** [comment]
> May I ask what is you end goal here? Can't quite figure it out.

What you're seeing in the screenshot is where I define all of my custom highlights in my almost-handmade theme (it's based on catppuccin's engine). What I would like would be for the name of each group here to be highlighted just as it's describe in its definition. It would make tweaking and adding more highlights much easier since I'd be able to see the result in real time. It's already a huge boon to be able to see the result of `brighten` and `darken` without needing to reload my whole config.

I definitely think it's possible to do an okay job with this module right now, but if I really want something robust I'm going to need to use treesitter queries eventually (mostly because these definitions could in theory span multiple lines), and pretty much redo this whole mini module but with treesitter instead of regex. I'm willing but don't have time for this yet.

> Side note: if you want a more automated highlight group creation, take a look into refactoring single style field into boolean fields for each "substyle". Just as a valid value of nvim_set_hl().

As I said I'm just using catppuccin's engine here, and they do it this way, which I don't dislike.

**Comment by calops** [comment]
There we go:
![image](https://github.com/echasnovski/mini.nvim/assets/4097716/77baa034-b9aa-442f-a05b-c04054318573)

These are all updated in real time depending on what's between the outermost brackets.

**Comment by echasnovski** [comment]
This is incredible! If/when you'll make this public, I'll certainly would like to look it.

> I definitely think it's possible to do an okay job with this module right now, but if I really want something robust I'm going to need to use treesitter queries eventually (mostly because these definitions could in theory span multiple lines), and pretty much redo this whole mini module but with treesitter instead of regex. I'm willing but don't have time for this yet.

Just to be clear: I don't think rewriting 'mini.hipatterns' to use anything other than Lua patterns will be a good idea to merge into 'mini.nvim'. If you want your own functionality like that, then sure, go for it (if you want and have time).

**Comment by calops** [comment]
Oh I wasn't suggesting to merge such a thing into your module, it's definitely out of scope. I'm just saying that right now, what I've showed works only loosely. Something robust would require treesitter, but I don't think I have any actual need for it.

Unless there's a way to match patterns over multiple lines? That would solve it, and probably wouldn't be out of scope here.

**Comment by calops** [comment]
Good call for the `require`s, thanks.

As for the pattern, I'm not seeing a case where it would make sense for me to have nested `{}`. But doesn't it work anyway? Are the patterns not greedy in lua?

**Comment by echasnovski** [comment]
> As for the pattern, I'm not seeing a case where it would make sense for me to have nested `{}`. But doesn't it work anyway? Are the patterns not greedy in lua?

You have nested `{}` in your screenshots: `CustomTablineNumber = { style = { "bold" } },`. Using `%b{}` ensures that it matches balanced `{` and `}` pair.

But yeah, I suppose relying on its greediness also works.

**Comment by calops** [comment]
Oh right, yeah I do have this. But it does work, actually (thanks to the greediness). The issue for this particular example is that there's no `palette` mentioned anywhere, which was my very rough estimation about what a highlight looks like. I don't want to remove this requirement as it would mess up the rest of my file.

If lua had non-capturing groups I could instead match something like `(fg|bg|style)` or something but alas, I see no solution with things as they are now. However, if `hipatterns` supported a *list* of patterns instead of just the one, it would cover this use-case.

**Comment by echasnovski** [comment]
> Oh right, yeah I do have this. But it does work, actually (thanks to the greediness). The issue for this particular example is that there's no `palette` mentioned anywhere, which was my very rough estimation about what a highlight looks like. I don't want to remove this requirement as it would mess up the rest of my file.

Sure, sounds reasonable. If it works, then it is good.
 
> If lua had non-capturing groups I could instead match something like `(fg|bg|style)` or something but alas, I see no solution with things as they are now. However, if `hipatterns` supported a _list_ of patterns instead of just the one, it would cover this use-case.

Instead it supports many highlighters. You can create three ones for specific pattern rules and with the same `group`.

**Comment by calops** [comment]
> Instead it supports many highlighters. You can create three ones for specific pattern rules and with the same group.

It does the job, but in this case it's possible that the pattern is applied multiple times, meaning the group is evaluated several times instead of just once, which is a bit of a waste.

**Comment by echasnovski** [comment]
The 'mini.hipatterns' is now out of beta-testing after the release of version 0.9.0. Thank you all for the input!
