### ISSUE TITLE
mini.cursorword features from vim-illuminate

### ISSUE THREAD

**Issue by zeitchef** [echasnovski/mini.nvim#34]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cursorword

### Description

I currently use `vim-illuminate` for this functionality and would love to use `mini.cursorword` but there are two features that are keeping me from making the switch:

1. **Don't mark/underline the word directly under the cursor.** This is not a deal-breaker, but I find it a lot more intuitive, as I theoretically should already know where my cursor is, and I just want to see all other instances of that word in the current viewable area of the buffer.

![Screen Shot 2022-01-03 at 08 52 57](https://user-images.githubusercontent.com/6670659/147909125-c76a44bd-1493-4f32-ab82-9ff1dd9b87fd.jpg)

2. **Change highlighting styles.** I may have overlooked if this was a possibility, but I prefer highlighting with `Visual` rather than underline matches.

Thanks for this awesome collection of utilities!

**Comment by echasnovski** [comment]
Thanks for your kind words!

As for the features:
1. My initial reaction was "Not really possible with current design". But after some digging, I think I found a reasonable implementation for this. I'll try and update in a couple of days.
2. Every custom highlighting in this package is done with corresponding highlight group. All highlighted groups defined within module are listed in its "# Highlight groups" section of help file. A dedicated mechanism to change highlighting to your liking is update the highlight group with [`highlight`](https://vimhelp.org/syntax.txt.html#%3Ahighlight) command. In your case it will be `hi! link MiniCursorword Visual`. Put this in your init file after loading colorscheme and this module.

**Comment by zeitchef** [comment]
@echasnovski Thanks for the consideration and info!

**Comment by zeitchef** [comment]
@echasnovski Glad it proved to be so interesting for you! I'm unfortunately still having a problem, in that `MiniCursorwordCurrent` is still being highlighted. Here's what it look like for me:

<img width="579" alt="Screen Shot 2022-01-05 at 12 42 27" src="https://user-images.githubusercontent.com/6670659/148212454-01efdbd6-db0c-4a43-aff0-bd342e2e96a6.png">

Note: `cmd` is a local map for `vim.cmd`.

**Comment by echasnovski** [comment]
Hmmm, it works for me with these exact commands.
Could you look at what actually `MiniCursorwordCurrent` is set to (with `:verbose hi MiniCursorwordCurrent`)? It should be something like `MiniCursorwordCurrent xxx gui=nocombine`. It might be that your colorscheme or something else is overwriting this value.

**Comment by zeitchef** [comment]
What `:verbose hi MiniCursorwordCurrent` reports looks good, but for whatever reason the highlighting is still the same for me:

![Screen Shot 2022-01-05 at 20 42 28](https://user-images.githubusercontent.com/6670659/148279621-c749aeb2-3297-47e7-9fac-361033a0836d.jpg)

**Comment by hunleyd** [comment]
fwiw, i saw the same thing @zeitchef is seeing when i tried this yesterday.

**Comment by echasnovski** [comment]
This is very strange. I tried it with both very minimal setup (only `mini.nvim` plugin and `mini.cursorword` with highlight groups) and my main one. Both times it works as expected. If I could look at your setup, it would be easier, but they don't seem to be public.

Let's be methodical here. Are you sure that you are using the latest version of `mini.nvim`? For example, have you run `PackerSync` if you use `packer.nvim`? To be 100% sure, could you please find where you installed `mini.nvim` (it should be present as entry in `:echo &runtimepath`) and look if [this line](https://github.com/echasnovski/mini.nvim/blob/main/lua/mini/cursorword.lua#L80) is present.

**Comment by hunleyd** [comment]
just did a PaqSync and said line is _not_ present. did you commit it to 'stable' or another branch?

**Comment by echasnovski** [comment]
> just did a PaqSync and said line is _not_ present. did you commit it to 'stable' or another branch?

Oh, there it is (at least for you). No, `stable` branch is for stable changes :) I.e. ones which are tested for some time. This change is in `main` branch.

**Comment by zeitchef** [comment]
@echasnovski That was it! I was also on the `stable` branch - moved over the the development branch and everything works as expected. Sorry for the confusion, and thanks again for your awesome work on this!

**Comment by echasnovski** [comment]
Glad it worked out!

**Comment by hunleyd** [comment]
just curious, how does one know when  feature moves to stable. 'watch' the releases?

**Comment by echasnovski** [comment]
At the moment I tend to work without strict rules and backlog but something like this:
- Main work branch is `main`. All new features and bug fixes will go there after my initial alpha-testing.
- After there are "enough" of changes, I'll make new release and update `stable` branch. You'll see that something moved to `stable` by many new commits merged to it.

This is somewhat similar to the situation with Neovim nightly and new Neovim release.
