### ISSUE TITLE
nvim-ts-context-commentstring doesn't work with newer versions of mini.comment

### ISSUE THREAD

**Issue by victornswd** [echasnovski/mini.nvim#342]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

Hey! 
Starting with commit  50ade2218c2ad32b1c6421ea500adaad01fa476f the plugin https://github.com/JoosepAlviste/nvim-ts-context-commentstring stopped working, at least with JSX & TSX. It's when `mini.comment` started to use tree-sitter comment string. Not sure if this is an issue for `mini.comment` or https://github.com/JoosepAlviste/nvim-ts-context-commentstring though

### Neovim version

0.10.0-dev-4423+gb46f61ac0-Homebrew

### Steps to reproduce

``` lua
-- init.lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
	"folke/tokyonight.nvim",
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"tsx",
					"typescript",
				},
				highlight = {
					enable = true,
				},
				context_commentstring = {
					enable = true,
					enable_autocmd = false,
				},
			})
		end,
		dependencies = {
			"JoosepAlviste/nvim-ts-context-commentstring",
		},
	},
	{
		"echasnovski/mini.nvim",
		-- commit = "50ade2218c2ad32b1c6421ea500adaad01fa476f",
		commit = "7a2b975c1fee1814268ed57d640dfba3ac88f302",
		dependencies = {
			"nvim-treesitter/nvim-treesitter",
		},
		config = function()
			require("mini.comment").setup({
				hooks = {
					pre = function()
						print("Successfully calling pre hook function...")
						require("ts_context_commentstring.internal").update_commentstring()
					end,
				},
			})
		end,
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.opt.termguicolors = true
vim.opt.updatetime = 100
vim.cmd([[colorscheme tokyonight]])
```
``` jsx
// example.jsx
export default function Profile() {
  const altText = "Katherine Johnson";
  return (
   <>
    <p>Some text</p>
    <img
      src="https://i.imgur.com/MK3eW3Am.jpg"
      alt= {altText}
    />
  </>
  )
}
```

1. `nvim -nu <above lua file>` 
2. open the `.tsx` or `.jsx` file and comment the before the returned element and inside of it
3. if you toggle the commented commits in the lua config you see the difference in the comments

### Actual behavior

With the newer versions of `mini.comment` JSX Elements get commented with `//` instead of `{/**/}`

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, it was a breaking change in 'mini.comment' due to a somewhat rushed introduction builtin tree-sitter based 'commentstring'. I thought it will solve all issues and 'nvim-ts-context-commentstring' wouldn't be needed. But it still is for TSX and JSX. But I didn't realize it up until very recently.

That was the reason for [introducing `options.custom_commentstring`](b464a490a363145505cee319a68d28711c34c2ff) several days ago. The following setup should work (tested with your .tsx example):

```lua
require('mini.comment').setup({
  options = {
    custom_commentstring = function()
      return require('ts_context_commentstring.internal').calculate_commentstring() or vim.bo.commentstring
    end,
  },
})
```
