### ISSUE TITLE
mini.statusline to ignore some buftypes (like neotree) and custom hook to different sections

### ISSUE THREAD

**Issue by icyrainz** [echasnovski/mini.nvim#344]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

I'm trying to customize the status bar to add the git blame with this. It would be great if we can inject only the customized part and leave everything else as is instead of repeating like my code below.

Also I would like ignore some buftypes like 'neo-tree' since it's very small and not cleaned to have the full status bar.

```
require("mini.statusline").setup({
	content = {
		active = function()
			local mode, mode_hl = MiniStatusline.section_mode({ trunc_width = 120 })
			local git = MiniStatusline.section_git({ trunc_width = 75 })
			local diagnostics = MiniStatusline.section_diagnostics({ trunc_width = 75 })
			local filename = MiniStatusline.section_filename({ trunc_width = 140 })
			local fileinfo = MiniStatusline.section_fileinfo({ trunc_width = 120 })
			local location = MiniStatusline.section_location({ trunc_width = 75 })

			local git_blame = require("gitblame").get_current_blame_text()

			return MiniStatusline.combine_groups({
				{ hl = mode_hl, strings = { mode } },
				{ hl = "MiniStatuslineDevinfo", strings = { git, diagnostics } },
				"%<", -- Mark general truncate point
				-- { hl = "MiniStatuslineFilename", strings = { filename } },
				{ hl = "MiniStatuslineFilename", strings = { git_blame } },
				"%=", -- End left alignment
				{ hl = "MiniStatuslineFileinfo", strings = { fileinfo } },
				{ hl = mode_hl, strings = { location } },
			})
		end,
	},
})
```

Ideally to avoid repeating code, I would just do something like this:
```
require("mini.statusline").setup({
	content = {
		replace = {
			filename = equire("gitblame").get_current_blame_text()
		}
	}
})

**Comment by echasnovski** [comment]
Thanks for suggestion!

Not having a customizable config in fixed table structure is intentional. Mostly because it would need to have complicated rules in order to achieve the flexibility of a current single function approach.

Your question about how to customize per filetype confirms this argument. I would suggest doing something like this:

```lua
local blocked_filetypes = { ['neo-tree'] = true }

require("mini.statusline").setup({
	content = {
		active = function()
			-- Customize statusline content for blocked filetypes to your liking
			if blocked_filetypes[vim.bo.filetype] then return '' end
			-- Continue the function
```

The way you add git blame section seems good to me (as long as `git_blame` is always a string).

Closing as the function approach probably won't change.
