### ISSUE TITLE
mini.surround dot-repeat is not working

### ISSUE THREAD

**Issue by cgjosephlee** [echasnovski/mini.nvim#345]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

Dot-repeat is not working.

### Neovim version

0.9.0

### Steps to reproduce

I tried following config in docker alpine image.

```lua
-- init.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
    { "echasnovski/mini.surround", version = false },
})

require('mini.surround').setup()
```

1. insert `apple`
2. `viw`
3. `sa"` (work)
1. `.` `.` (not work)

### Expected behavior

`"""apple"""`

### Actual behavior

`"applappleeapple"`
Seems typing `apple` is repeated.

**Comment by echasnovski** [comment]
Adding surroundings in dot-repeat doesn't work in Visual mode because it doesn't have full information about selection. This is similar to built-in behavior of dot-repeat: type `viw` followed by `d`. If you then press `.`, it won't delete current `iw` textobject (as one might expect), but instead will delete the same number of characters (which one might not expect).

Instead of adding to visual selection, use adding to textobject: `sa`, `iw`, `"`. Then pressing `.` will repeat adding `"` to inner word.

**Comment by cgjosephlee** [comment]
Thanks for explaining this. My common workflow is to triple-quote a string:
```python
q = select a from b
# to
q = """select a from b"""
```
or sometimes more complicated
```python
abc
# to
["abc"]
```
In viscode and sublime, it would be a simple selection and type. Can you please provide some suggestions on this kind of scenario?

**Comment by echasnovski** [comment]
> In viscode and sublime, it would be a simple selection and type. Can you please provide some suggestions on this kind of scenario?

I have two:
- Get comfortable using textobjects (like `aw`, `ip`, etc.) and motions (like `f`, `t`, `$`, etc.). This is one of the most powerful Vim ideas. You can read more about them in `:h text-objects` and `:h motion.txt`.
This is the recommended approach. Here are some examples for your cases:
    - `q = select a from b`: place cursor on `s` and type `sa$"` followed by two `.`.
    - `'''abc'''`: type `sr'"` followed by two `.`.
    - `abc`: type `saiw"` (add `"` surrounding to **i**nside **w**ord) and `sai"]` (add `]` surrounding to **i**nside `"`).

- If triple quotes this very common, you can create custom surrounding like this:
    ```lua
    require('mini.surround').setup({
      custom_surroundings = {
        q = {
          input = { '"""().-()"""' },
          output = { left = '"""', right = '"""' },
        },
      },
    })
    ``` 
    Now the first `q = select a from b` example can be done with `sa$q`.

**Comment by cgjosephlee** [comment]
Thanks a lot! I will try to build up my muscle memory!
