### ISSUE TITLE
mini.surround: Surrounds added in weird places in line-wise visual mode when line is indented

### ISSUE THREAD

**Issue by filipekiss** [echasnovski/mini.nvim#346]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

First of all, thank you so much for these plugins. They are great and straight to the point :)

I was using mini.surround and trying to add `{}` around some lines using line-wise visual mode (<kbd>Shift+V</kbd>) but got unexpected results.

### Neovim version

0.9.0 (homebrew bottle)

### Steps to reproduce

```lua
-- minimal.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

require("lazy").setup({
	"https://github.com/echasnovski/mini.surround",
	config = true,
})
```

In any file, visually select a couple of lines that have indentation (<kbd>Shift+V</kbd>) and try to add some surroundings like `sa{`. The text below is enough to see the issue

```
this is a
paragraph with
no indentation


	this is
	a paragraph
	with indentation

```

### Expected behavior

I would expect the surrounding pairs to be added to either before and after the lines or at the beggining of the first line and end of the last one:

```
{
 this is a
paragraph with
no indentation 
}

{ 	
	this is
	a paragraph
	with indentation 
}

```

### Actual behavior

The first one, with no indentation, works fine:

```
{ this is a
paragraph with
no indentation }
```

The second one is where we have some trouble:

```
	t{ his is
	a paragraph
	with indentation }
```

If I use visual selection (<kbd>v</kbd>) instead of line-wise selection (<kbd>Shift+V</kbd>), it kinda works, but the surroundings do not respect the line indents:

```
{	this is
	a paragraph
	with indentation}
```

**Comment by echasnovski** [comment]
Thanks for reporting this!

Indeed, I can reproduce this but only with tabs indents. I'll investigate it.

**Comment by echasnovski** [comment]
This should now be fixed on `main` branch. The correct behavior with default `setup()` is for first line to start with `{ this ...`.
