### ISSUE TITLE
mini-starter: Add "hotkeys" options

### ISSUE THREAD

**Issue by filipekiss** [echasnovski/mini.nvim#347]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

I am replacing [alpha](https://github.com/goolord/alpha-nvim) with mini.starter and, so far, I really like the results.

One thing that got me a little confused at the start was the whole 'querying' for the items. I understand now how it works, but I don't think that's the optimal approach for a start screen (in my case, at least). 

For the sake of this example, let's say I have the following items on my start screen:

```
- [N]ew File
- [Gi]t status
- [F]ind File
- [Gr]ep Text
- [Q]uit
```

The characters enclosed in `[]` are the characters highlighted by `mini.starter` that will trigger that command. As you can see, Git and Grep both require two keystrokes instead of one, as they share the first letter.

I would like to have an option to set each item 'hotkey' and pressing that hotkey would trigger the item, for example:

```
 - [N]ew file
 - [G]it status
 - [F]ind file
 - G[r]ep Text
 - [Q]uit
```

This would make <kbd>g</kbd> trigger the `Git` item and <kbd>r</kbd> trigger the `Grep Text` item.

Since the items in the dashboard aren't changing all that much (pretty much never), querying for an item becomes a bit cumbersome, as if I had the option to set the shortcut for that item directly would be much more efficient.

I understand that this might affect the querying system as it might cause conflicting maps, but for my personal case, I don't mind losing query capabilities in favor of this, so an opt-in configuration would be fine.

**Comment by echasnovski** [comment]
Thanks for suggestion!

> Since the items in the dashboard aren't changing all that much (pretty much never), querying for an item becomes a bit cumbersome, as if I had the option to set the shortcut for that item directly would be much more efficient.

Items can change in start screen, like in default "Sessions" and "Recent files" sections. If user wants some static item names, the current suggestion is to manually design item names to have unique prefix. 

I would suggest modifying item names by manually prepending them with the hotkey you'd like. Something like this:

```
- N New File
- G Git status
- F Find File
- R Grep Text
- Q Quit
```

Or choose entirely different description for problematic entries. I opted for `Live grep` in [`telescope` built-in section](https://github.com/echasnovski/mini.nvim/blob/09476036cbaa7676172f7dd37a26a51a92388aab/lua/mini/starter.lua#L545).

Sorry, but current approach with querying will be the only possibility in the foreseeable future.

**Comment by filipekiss** [comment]
Actually, the names with the labels at the beginning are more than enough! Thanks for the suggestion!
