### ISSUE TITLE
Mini.starter leaves an empty hidden buffer after selecting a file

### ISSUE THREAD

**Issue by Penaz91** [echasnovski/mini.nvim#35]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

Greetings,
Thanks for making this collection of modules!

There is a small problem regarding the "mini.starter" module: when I select a file from the "ministarter.sections.recent_files" a hidden buffer with no name is left, while the selected file is opened on another buffer.

If anything is unclear, feel free to ask any question.

Thank you in Advance!

### Neovim version

0.6.1

### Steps to reproduce

1. Start nvim with mini installed (I used packer, removing all other plugins and leaving only mini.nvim, stable branch)
2. Configure nvim to start mini.starter with the default configuration
3. Open a recent file from the menu
4. Use the ":ls" command to list open buffers

### Expected behavior

I expect that the file I selected is opened in the current buffer

### Actual behavior

According to ":ls" there is an empty "hidden" buffer, followed by another buffer containing the file I just opened.

**Comment by echasnovski** [comment]
Yeah, I've seen this behavior too. I couldn't find quick solution and it didn't bother me too much, so it is still there :) Thanks for reporting it, I'll try to come with some solution for this.

**Comment by Penaz91** [comment]
I had a similar problem with my first plugin, what I did was the following (in VimScript)
```
....
let empty_buffer_nr = bufnr("%")
execute ":e " . a:item
execute ":silent bd " . empty_buffer_nr
....
```
In the first line I memorize the buffer number I'm "using" as a menu, open my file in edit mode and then silently do a buffer delete on the "used buffer"

**Comment by echasnovski** [comment]
This should be fixed now.

Issue was not exactly like you pointed (starter buffer not closing), but similar: it was a buffer created by Neovim on startup. As 'mini.starter' always created new buffer, that previous one was left untouched. I settled on allowing to open Starter in specified buffer and used this on startup to occupy initial empty buffer.

**Comment by Penaz91** [comment]
I can confirm that the fix works as expected, thank you very much!
