### ISSUE TITLE
Specifying multiple patterns for a custom textobject in mini.ai

### ISSUE THREAD

**Issue by frnsys** [echasnovski/mini.nvim#350]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Thanks for these plugins. I'm trying to set up a custom textobject for `mini.ai`. The idea is to match segments of camel case and pascal case words.

I have two patterns that work:

```
[%s%p]()%u?[%l%d]+()
%l()%u+[%l%d]+()
```

I tried specifying a composed pattern like so:

```
      {
        '[%s%p]()%u?',
        '%l()%u+',
      },
      '[%l%d]+()',
```

but this doesn't work because the last pattern doesn't have two captures in it:

```
Could not extract proper positions (two or four empty captures) from string 'o' with extraction pattern '[%l%d]+()'.
```

I would have thought that due to how composed patterns work (creating the cartesian product of its components) then the final patterns would have two captures?

### Neovim version

0.9.0

### Steps to reproduce

Configure the following:

```
require('mini.ai').setup({
    S = {
      {
        '[%s%p]()%u?',
        '%l()%u+',
      },
      '[%l%d]+()',
    },
  },
})
```

### Expected behavior

Composed pattern would generate valid textobject patterns

### Actual behavior

Composed pattern is rejected due to not having enough captures:

```
Could not extract proper positions (two or four empty captures) from string 'o' with extraction pattern '[%l%d]+()'.
```

**Comment by frnsys** [comment]
Thanks for your fast response! Unfortunately it doesn't work. But the patterns work individually for my target cases:

where `[...]` indicates what is selected:

```
[%s%p]()%u?[%l%d]+()

[foo]Bar
[Foo]Bar
    [Foo]Bar
baz.[foo]Bar
baz.[Foo]Bar
```

```
%l()%u+[%l%d]+()

foo[Bar]
    Foo[Bar]
baz.foo[Bar]
baz.Foo[Bar]
```

When I combine them like you suggested, the matches of the second part (the `Bar`s) still works, but the matches of the first part become inconsistent.

These cases still work:

```
    [Foo]Bar
baz.[foo]Bar
baz.[Foo]Bar
```

but not these ones:

```
[foo]Bar
[Foo]Bar
```

so perhaps it's related to these being at the start of the line?

Indeed, if I explicitly add a pattern to match newline it works as expected:

```
    S = { {
      '^()%u?[%l%d]+()',
      '[%s%p]()%u?[%l%d]+()',
      '[%l%u]()%u+[%l%d]+()'
    } },
```

**Comment by echasnovski** [comment]
> After playing around with it some more, I'm satisfied with this, so feel free to close this issue--though not sure if that newline inconsistency is to be expected or not. In any case, thanks again for an amazing set of plugins!

Both pattern explicitly say that there should be *something* before the match start (`[%s%p]` or `[%l%u]`), so match at start of line is not possible.

Glad it worked out!
