### ISSUE TITLE
Comment support for Blueprint markup language (.blp)

### ISSUE THREAD

**Issue by CleoMenezesJr** [echasnovski/mini.nvim#351]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

> Blueprint uses C-style line comments (// comment for the rest of the line) and block comments (/* multiline comment... */).

https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/reference/index.html

**Comment by echasnovski** [comment]
Yes, the suggested way of defining custom comment structure is by defining custom commentstring per buffer or [`options.custom_commentstring`](https://github.com/echasnovski/mini.nvim/blob/afa6f0a3dc27b910501651f5fc26ef3b551fd99b/doc/mini-comment.txt#L111) for complex cases.

Create a file 'after/ftplugin/blueprint.lua' (or whichever 'filetype' is actually set in your case) and add line `vim.bo.commentstring = '// %s'` to it.

**Comment by CleoMenezesJr** [comment]
@clason @echasnovski Thank you!!
