### ISSUE TITLE
[mini.base16] - Introduce a feature to remove background highlights

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#352]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

base16

### Description

mini.base16 offers default background highlights for numerous highlight groups, but this may not always complement every available colorscheme. It would be great to have a options that allows users to disable these background highlights:

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/fa8d01a9-9ea0-4bbb-9728-38ae388126ff)

Currently, I personally employ an autocmd to clear them whenever a colorscheme event occurs, but this additional clutter could be more effectively managed internally.

```lua
vim.api.nvim_create_autocmd({ "colorscheme" }, { 
  pattern = "*",
  callback = function()
    vim.schedule(function()
      vim.cmd[[
        highlight clear LineNr
        highlight clear LineNrAbove
        highlight clear LineNrBelow
        highlight clear SignColumn
        highlight clear DiagnosticSignError
        highlight clear DiagnosticSignWarn
        highlight clear DiagnosticSignInfo
        highlight clear DiagnosticSignHint
        
        -- dim line numbers.
        highlight! link LineNrAbove Comment
        highlight! link LineNrBelow Comment
      ]]
    end) 
  end
})
```

https://github.com/wroyca/dotfiles/tree/main/home/dot_config/nvim/colors

**Comment by echasnovski** [comment]
Thanks for suggestion!

I think using autocommand on `ColorScheme` event is the best way for this kind of tweaking. Alternatively, if user wants to tweak only one particular color scheme, then those commands can be done only after corresponding `:colorscheme` command.

This decision is mostly based on the fact, that there are many possible ways which users might want to tweak color scheme. It would not benefit overall maintainability and loading speed of color scheme.

Sorry, but I don't see this as part of 'mini.base16' (or 'mini.hues' for that matter).

**Comment by wroyca** [comment]
> Thanks for suggestion!
> 
> I think using autocommand on `ColorScheme` event is the best way for this kind of tweaking. Alternatively, if user wants to tweak only one particular color scheme, then those commands can be done only after corresponding `:colorscheme` command.
> 
> This decision is mostly based on the fact, that there are many possible ways which users might want to tweak color scheme. It would not benefit overall maintainability and loading speed of color scheme.
> 
> Sorry, but I don't see this as part of 'mini.base16' (or 'mini.hues' for that matter).

Fair enough - My perspective was that enabling or disabling backgrounds provides a different level of flexibility compared to, for instance, directly changing the background color to a specific shade - in short, it doesn't require granular adjustments to individual color values
