### ISSUE TITLE
mini.animate issue with split window background color

### ISSUE THREAD

**Issue by ls-devs** [echasnovski/mini.nvim#357]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

Hi,
Just installed mini.animate today and really apreciate it.
But I have an issue where when I open a split window, the window do not respect transparency. Background become black for 1s and then get back to transparent.

Please see : 

https://github.com/echasnovski/mini.nvim/assets/58638832/6a75a78d-afdd-4f5a-b285-cfe1cfc691c7

### Neovim version

NVIM v0.10.0-dev-463+g780ab11b9

### Steps to reproduce

Tbh, I don't really know how to reproduce this issue.
I've tested without all of my plugins and it still remains the same.

### Expected behavior

Open split window with transparent background

### Actual behavior

Open split window and get black background during 1s.

**Comment by echasnovski** [comment]
Thanks for the issue!

This is a result of `open` animation which shows which window was just opened. By default it does so by covering whole window with floating window which changes its 'winblend' option from being slightly opaque to completely transparent.

As your `NormalFloat` highlight group seems to already be "transparent" (i.e. no actual color as resolved background), Neovim seems to resort to black background.

In your case of transparent floating windows having `open` and `close` animations is kind of unusable at the moment, so disabling them should fix this:

```lua
require('mini.animate').setup({
  open = { enable = false },
  close = { enable = false },
})
```

**Comment by echasnovski** [comment]
It might be a good idea to add some kind of dedicate highlight group for users with transparent background to use. I'll think about it.

**Comment by ls-devs** [comment]
Thanks for your quick reply!
I understand, i'll stick with this fix for the moment, and hope those animations will be available later.

**Comment by echasnovski** [comment]
There is now `MiniAnimateNormalFloat` highlight group to customize how floating windows in `open` and `close` animations look.

But... It doesn't seem to help with transparent backgrounds. This seems to be a Neovim issue: neovim/neovim#18576.
