### ISSUE TITLE
mini.animate: Avoid vertical scroll animation from scrolloff

### ISSUE THREAD

**Issue by TJ-Adams** [echasnovski/mini.nvim#364]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

I do not know if this is possible, but I have turned off cursor animations because I noticed it slowed down my movement when using [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim). I'd have to wait for the animation to finish before I could do actions at the desired cursor location.

However I also have scrolloff turned on and if I move the cursor to somewhere near the bottom or top of my screen I have to wait again for the animation to finish before my cursor is in the proper spot because it triggers a vertical scroll event where I want animations turned on. So basically I'm wondering if it's possible to add something to turn off vertical animations _only_ caused by scrolloff (probably a stretch).

Alternatively, if there was support for turning off certain animations runtime vs config time, I could change my configs so that way everytime I trigger lightspeed I turn off all mini.animate animations and then turn them back on afterwards.

Thank you!

**Comment by echasnovski** [comment]
I am not sure we are on the same page here.

Cursor animation, as in [`cursor` field of config](https://github.com/echasnovski/mini.nvim/blob/56509def588044fd5dcd1efe74197f1f4fe8953a/doc/mini-animate.txt#L123), does not affect cursor position in any way. It only adds visualization of its path.

Scroll animation, as in [`scroll` field of config](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-animate.txt#L135), does affect cursor position.

> So basically I'm wondering if it's possible to add something to turn off vertical animations only caused by scrolloff (probably a stretch).

No, it is not possible to do that by using only 'mini.animate' functionality. And I am not sure how to detect only animations which the result of `scrolloff`.

> Alternatively, if there was support for turning off certain animations runtime vs config time, I could change my configs so that way everytime I trigger lightspeed I turn off all mini.animate animations and then turn them back on afterwards.

Yes, this is possible. Here is an example of custom wrapper to trigger jump of 'mini.jump2d' with disabled scroll animation:
```lua
_G.jump = function()
  MiniAnimate.config.scroll.enable = false
  MiniJump2d.start()
  -- Need `vim.schedule()` here to still have it disabled at animation's start
  vim.schedule(function() MiniAnimate.config.scroll.enable = true end)
end
```

Does this solve your problem?

**Comment by TJ-Adams** [comment]
Hey @echasnovski,

I think because I saw the cursor being animated I thought it had to finish before I could type but like you said that's not the case. I can start typing because the cursor position is actually in the correct place even if the animation isn't finished.

And yes I think I can take that and apply it for my use case. Thanks for taking the time out to answer my question and provide the example! I'll close this issue now.
