### ISSUE TITLE
Allow several patterns in `MiniJump2d.gen_pattern_spotter()`

### ISSUE THREAD

**Issue by fgombault** [echasnovski/mini.nvim#365]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump2d

### Description

mini.jump2d can be setup() with a custom spotter function, that's awesome.

AFAIK due to the limitations of lua pattern matching, the default spotter function in jump2d.lua has to compose a merge of unique jump targets from half a dozen simple regexes.

The feature request is that the H module of jump2d.lua also be exported, so that users can also take advantage of it and use the merge_unique() helper function to implement their custom spotter function.

Or, alternatively  → if the "spotter" option handling can be enhanced to accept an array of lua patterns, this could also meet 90% of custom spotter use cases (possibly being more user-friendly as well).

**Comment by echasnovski** [comment]
Thanks for the suggestion! This is a really interesting one.

I think the best approach to solve this pain point is to allow several patterns in `gen_pattern_spotter()`. It should result into union of all spots.

I'll think about it.

**Comment by echasnovski** [comment]
I've just pushed an update of 'mini.jump2d' which contains `gen_union_spotter()`. I think this is a better and more versatile approach to the problem of combining results of several spotters. Here is [its documentation with usage examples](https://github.com/echasnovski/mini.nvim/blob/4fd0f9c72fb54696442c81a64c71514c95239148/doc/mini-jump2d.txt#L367).
