### ISSUE TITLE
mini.ai: handle escaped quotes better

### ISSUE THREAD

**Issue by milanglacier** [echasnovski/mini.nvim#366]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Suppose we have the following strings:

```
"hello \"world\""
```

putting cursor inside this string and let's see the behavior of `mini.ai`

### Neovim version

0.9

### Steps to reproduce

minimal config:

```lua
require('mini.ai').setup {search_method = "cover"}
vim.highlight.on_yank { higroup = 'IncSearch', timeout = 400 }
-- we use `cover` method to understand what's under the hood mini.ai is doing under current context
```

### Expected behavior

If `mini.ai` is not installed, this is the default behavior in vim:

No matter where the cursor position is in, as long as cursor is inside `hello \"world\"`, then `ya"` will select `"hello \"world\""`,

and `yi"` will select `hello \"world\"`

This option is more acceptable than current `mini.ai`'s implementation.

A more ideal way would be:

when cursor is at `hel|lo`, where `|` is the cursor position, typing `yaq or ya"` should select `"hello \"world\""`, and when cursor is at `wor|ld`, `yaq or ya"` should select `"world"` or `\"world\"` (I think either two cases are resonable).

### Actual behavior

However, in `mini.ai`, this is the behavior:

cursor position 1:

```
"he|llo \"world\""
```

press `yi"` select `hello \`,

cursor position 2:

```
"hello \"wo|rld\""
```

press `yi"` will yield an error: `No textobject "ia" found covering region within 100 lines and `search_method = 'cover'`.`

**Comment by echasnovski** [comment]
Thanks for suggestion!

The behavior you describe does sound nicer than current verbatim quote treatment of quotes. But I doubt there is a concise yet effective way to account for it under current Lua pattern based matching. It certainly is possible, but might require callable textobject specification, which is not ideal.

I'll think about it, but I don't have high hopes about this being implemented.

Side note: same remark goes for `'` and possibly for `` ` ``; maybe even for all kinds of parenthesis.

**Comment by milanglacier** [comment]
Besides,
When putting at cursor position2 (inside the escaped quote), `a"` and `i"` in mini don’t select anything but yield an error. May I consider this as a bug?

**Comment by echasnovski** [comment]
> I understand. Lua pattern match is less powerful than regex.
> 
> Can we have a blacklist (fallback) config option? That is, if I specified `"` as part of this config, then when I press `a"` or `i'` then it will use the default vim way rather than using mini?

It is already possible by [setting `custom_textobject` entry to `false`](https://github.com/echasnovski/mini.nvim/blob/56509def588044fd5dcd1efe74197f1f4fe8953a/doc/mini-ai.txt#L441-L442).



> Besides, When putting at cursor position2 (inside the escaped quote), `a"` and `i"` in mini don’t select anything but yield an error. May I consider this as a bug?

I can not reproduce any error.

If you have `No textobject "ia" found ...`, as in original post, then you typed `ia` instead of `i"`.

If you execute `yi"`, it shows message `Textobject region is empty. Nothing is done.`. This is because when cursor is on `world`, it tries to copy **inside** the following `""` (which is the the next match here, as quotes are balanced). This is expected.

**Comment by milanglacier** [comment]
Thanks for reminding  me to set custom_text object to false to configure the blacklist!

> If you execute `yi"`, it shows message `Textobject region is empty. Nothing is done.`. This is because when cursor is on `world`, it tries to copy **inside** the following `""` (which is the the next match here, as quotes are balanced). This is expected.

I got your point, thanks for mentioning that.

**Comment by echasnovski** [comment]
After pondering over it for a while, I think the current behavior is here to stay. Handling escaped symbols is too complicated here.
