### ISSUE TITLE
I would like to reindent vertical movement using LSP format instead of `=`

### ISSUE THREAD

**Issue by homerosbart2** [echasnovski/mini.nvim#367]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.move

### Description

Using LSP to format the line is better than `=` because it takes into account everything to indent the line (code, Prettier, ESLint, etc..). Probably the performance of doing this is worst, but the dev experience will be better.

It would be nice if it is an optional configuration.

https://github.com/echasnovski/mini.nvim/assets/25249581/e3fdf8d0-4e56-4d23-a9bf-4e5a9d2a266f

**Comment by echasnovski** [comment]
Sorry, but no, this is out of scope.

I would suggest to disable formatting by setting [`options.reindent_linewise`](https://github.com/echasnovski/mini.nvim/blob/807b32ed36a6668558c7c1b800ccc23fe273613c/doc/mini-move.txt#L109) to `false` and then manually format after movement.
