### ISSUE TITLE
Incorrect highlight with `folke/trouble.nvim`

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#368]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

base16

### Description

Incorrect highlight with `folke/trouble.nvim` and `mini.base16`

### Neovim version

0.9.1

### Steps to reproduce

1. `colorscheme minicyan`
1. `TroubleToggle`

### Expected behavior

The designated highlights group should possess a transparent background -

Starting point: 

* TroubleFoldIcon 
* TroubleIndent
* TroubleLocation
* ... ? 

Reference:

![shot](https://github.com/echasnovski/mini.nvim/assets/91024200/b966ac50-c601-4297-bee5-8d3efb69ccf9)

### Actual behavior

Using minicyan:

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/37129be4-6b46-4f96-a8e9-79d9a6bc0799)

**Comment by echasnovski** [comment]
This should be now resolved on latest `main`.
