### ISSUE TITLE
Add terms to blocklist for mini.cursorword

### ISSUE THREAD

**Issue by zeitchef** [echasnovski/mini.nvim#37]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cursorword

### Description

I've completely switched to using `mini.cursorword` from `vim-illuminate` and I'm absolutely thrilled with it. Thanks!

One thing that I would like to see is a configuration option to add a list of words that should **not** be highlighted. For example, when working with a large JavaScript codebase, the `import` statements are often grouped together - thus not really necessary to highlight, as they are so easy to find:

<img width="253" alt="Screen Shot 2022-01-12 at 14 54 44" src="https://user-images.githubusercontent.com/6670659/149153472-2fa19eca-5bcf-408d-a639-59bae8aee4cc.png">

So I'd like to be able to do something like:

``` 
config = {
  disable_highlighting = { 'import' }
}
``` 

Again, thanks for your consideration!

**Comment by echasnovski** [comment]
Thanks for suggestion!

Well, it is interesting and in theory not that hard to implement. I am more worried about inherited complexity that might come with it. It seems to be more useful for these lists to have both "local" and "global" nature. That means a need for a check on every cursor movement, which is not a great news for execution speed.

I'll think about it, but at the moment my expectation is not that high.

**Comment by echasnovski** [comment]
At the moment I would really like to try and not introduce any conditional disabling in config. I believe that `vim.g.mini***_disable` and `vim.b.mini***_disable` are flexible enough for people to use them to achieve behavior they like. Granted, it requires certain Lua (or even Vimscript) knowledge, but that is what I currently believe is best for this plugin. I intend to help with issues of this kind and collect code snippets in one place somewhere.

Your case can be solved by adding something like this to tour init file:
```lua
_G.cursorword_blocklist = function()
  local curword = vim.fn.expand('<cword>')
  local filetype = vim.api.nvim_buf_get_option(0, 'filetype')
  local blocklist = {}
  -- Add any disabling global or filetype-specific logic here
  if filetype == 'lua' then
    blocklist = {'local'}
  elseif filetype == 'javascript' then
    blocklist = {'import'}
  end

  vim.b.minicursorword_disable = vim.tbl_contains(blocklist, curword)
end

-- Make sure to add this autocommand *before* calling module's `setup()`.
vim.cmd([[au CursorMoved * lua _G.cursorword_blocklist()]])

require('mini.cursorword').setup()
```

Does this solve your problem?

**Comment by zeitchef** [comment]
Hi, sorry for my late response. This solves my problem nicely. Thanks again!
