### ISSUE TITLE
How'd you not lazy load mini.colors with other plugins?

### ISSUE THREAD

**Issue by pwnwriter** [echasnovski/mini.nvim#371]
I've the following conf to use mini.nvim
```lua
local spec = {
  "echasnovski/mini.nvim",
  name = "mini",
  version = '*',
  event = { "InsertEnter" },
}

function spec:config()
  local pairs = require("mini.pairs")

  pairs.setup({
    modes = { insert = true, command = false, terminal = false },

    mappings = {
      ['('] = { action = 'open', pair = '()', neigh_pattern = '[^\\].' },
      ['['] = { action = 'open', pair = '[]', neigh_pattern = '[^\\].' },
      ['{'] = { action = 'open', pair = '{}', neigh_pattern = '[^\\].' },

      [')'] = { action = 'close', pair = '()', neigh_pattern = '[^\\].' },
      [']'] = { action = 'close', pair = '[]', neigh_pattern = '[^\\].' },
      ['}'] = { action = 'close', pair = '{}', neigh_pattern = '[^\\].' },

      ['"'] = { action = 'closeopen', pair = '""', neigh_pattern = '[^\\].', register = { cr = false } },
      ["'"] = { action = 'closeopen', pair = "''", neigh_pattern = '[^%a\\].', register = { cr = false } },
      ['`'] = { action = 'closeopen', pair = '``', neigh_pattern = '[^\\].', register = { cr = false } },
    },
  })

end


return spec


```

I want to use mini.colors, can we pass the configuration for mini.colors in the same file and lazy load only other components/plugins from mini.nvim but not colors?

**Comment by echasnovski** [comment]
It doesn't look like default Neovim?

Do you use specific distribution? Or just 'folke/lazy.nvim' as plugin manager? Or something else?

**Comment by pwnwriter** [comment]
Yes, it's [folke/lazy.nvim](https://github.com/folke/lazy.nvim)

**Comment by echasnovski** [comment]
I don't this is reasonably possible with your code right now.

I would suggest investigating at least these options:
- Load whole 'mini.nvim' without lazy loading. This will have hardly any impact on startup speed. Inside its config you can set up 'mini.colors' right away and manually lazy load others with autocommands. Something like `vim.api.nvim_create_autocmd('InsertEnter', { once = true, callback = function() <your code goes here> end })`.
- Use standalone modules for more granular setup.
