### ISSUE TITLE
Smart cursor and backspace handling

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#373]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

# Feature request

Nvim lacks consistent indentation preservation, resulting in indentation loss depending on the cursor's context. I have been working on a concept to address this issue thank to [AnonymousBoch](https://www.reddit.com/r/neovim/comments/146gya4/comment/jnrl8lu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) for introducing the initial backspace concept.

My proposed approach aims to handle expressions more effectively by maintaining proper indentation, and handling backspacing with proper context awareness. In short, nvim will dynamically adjust and align indentation in a "smart" way, allowing users to focus more on writing code and less on manual formatting adjustments:

[Screencast_from_2023-06-15_13-15-47.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/b382771d-cb6f-43a3-90fc-6c9d492d6856)

Here's a short overview:

- Cursor
  - Improve and optimize cursor handling to guarantee precise and consistent movement throughout the editing process.
  - Resolve any potential issues that may arise, such as indentation partial loss or inaccurate cursor positioning.
  - Handle boundary, including scenarios where the cursor reaches the buffer either the first or last line to prevent any unexpected behavior.

- Backspace
  - Mechanism to accurately adjust the cursor position following the execution of a backspace operation, thereby maintaining a seamless and uninterrupted editing workflow.
  - Address any associated challenges or edge cases that may arise when backspacing, such as maintaining correct cursor alignment in relation to the edited line and preserving the content of adjacent lines.

## Concept

> **Note**
> Code is primarily experimental in nature and is intended to serve as a demonstration. That said, it has undergone rigorous testing through dogfooding and operates without any known issues

```lua
-- https://www.reddit.com/r/neovim/comments/146gya4/comment/jnrl8lu/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

local function smart_backspace()
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  local char = vim.api.nvim_get_current_line():sub(col, col)
  local previous_line = vim.api.nvim_buf_get_lines(0, line-2, line-1, false)[1]
  if char == " " and previous_line:match("^%s*$") then
    vim.cmd([[
      let g:exprvalue =
          \ (&indentexpr isnot '' ? &indentkeys : &cinkeys) =~? '!\^F' &&
          \ &backspace =~? '.*eol\&.*start\&.*indent\&' &&
          \ !search('\S','nbW',line('.')) ?
          \   (col('.') != 1 ? "\<C-U>" : "") .
          \   "\<bs>" . (getline(line('.')-1) =~ '\S' ? "" : "\<C-F>") :
          \ "\<bs>"
    ]])
    return vim.g.exprvalue
  else
    return vim.api.nvim_replace_termcodes("<bs>", true, false, true)
  end
end

-- Retrieves the expression value based on the specified direction.
-- @param direction (string): Direction to search for the expression value. Can be "up" or "down".
-- @return (string): The expression value.
--
function getExprValue(direction)
  local line, col = unpack(vim.api.nvim_win_get_cursor(0))
  local char = vim.api.nvim_get_current_line():sub(col, col)
  local nextLine
  if direction == "up" then
    nextLine = vim.api.nvim_buf_get_lines(0, line-2, line-1, false)[1]
  else
    nextLine = vim.api.nvim_buf_get_lines(0, line, line + 1, false)[1]
  end

  if char == " " and nextLine:match("^%s*$") then
    -- Exprvalue:
    --
    -- Condition 1: (&indentexpr isnot '' ? &indentkeys : &cinkeys) =~? '!\^F'
    --   - If the 'indentexpr' option is not empty, use the 'indentkeys' value.
    --   - Otherwise, use the 'cinkeys' value.
    --   - The expression matches '!^F' to enable indenting when no 'foldexpr' is defined.
    --
    -- Condition 2: &backspace =~? '.*eol\&.*start\&.*indent\&'
    --   - The 'backspace' option is checked to have specific values to handle backspacing behavior.
    --     - expr matches any string that contains 'eol', 'start', and 'indent'.
    --
    -- Condition 3: !search('\S','nbW',line('.'))
    --   - The '\S' pattern matches any non-whitespace character.
    --   - The 'nbW' flags limit the search to the current buffer and disable wrapping.
    --   - The search is performed starting from the current line.
    --
    -- Result Construction:
    --   - (col('.') != 1 && getline('.') !~ '^\s*$' ? "" : "\<C-U>")
    --     - If the current column is not 1 and the current line is not entirely whitespace, prepend "\<C-U>" to clear the line.
    --     - Otherwise, an empty string is used.
    --   - "\<]] .. direction .. [[>"
    --     - Append the movement key (either "\<Up>" or "\<Down>") to the expression value.
    --   - (getline(line('.')+(]] .. (direction == "up" and "-1" or "+1") .. [[)) =~ '\S' ? "" : "\<C-F>")
    --     - If the line at the relative position (previous line for "up" or next line for "down") contains a non-whitespace character, append an empty string.
    --     - Otherwise, append "\<C-F>" to move to the previous or next screen.
    --
    vim.cmd([[
      let g:exprvalue =
          \ (&indentexpr isnot '' ? &indentkeys : &cinkeys) =~? '!\^F' &&
          \ &backspace =~? '.*eol\&.*start\&.*indent\&' &&
          \ !search('\S','nbW',line('.')) ?
          \   (col('.') != 1 && getline('.') !~ '^\s*$' ? "" : "\<C-U>") .
          \   "\<]] .. direction .. [[>" . (getline(line('.')+(]] .. (direction == "up" and "-1" or "+1") .. [[)) =~ '\S' ? "" : "\<C-F>") :
          \ "\<]] .. direction .. [[>"
    ]])
    return vim.g.exprvalue
  else
    -- If the current character is not a space or the next line is not empty:
    -- Return the termcodes representing the movement in the specified direction.
    return vim.api.nvim_replace_termcodes("<" .. direction .. ">", true, false, true)
  end
end

vim.keymap.set('i', '<BS>', smart_backspace(), { expr = true, noremap = true, replace_keycodes = false })
vim.keymap.set('i', '<Up>', 'v:lua.getExprValue("up")', { expr = true, noremap = true, replace_keycodes = false })
vim.keymap.set('i', '<Down>', 'v:lua.getExprValue("down")', { expr = true, noremap = true, replace_keycodes = false })
```

**Comment by echasnovski** [comment]
Thanks for suggestion and the code snippet.

I don't think this behavior is consistent with what I would expect of coherent editing experience. Inserting indentation is pretty good with built-in Neovim's features (like 'autoindent', 'copyindent', 'smartindent', 'preserveindent'). Making `<BS>` delete whole previous indent and go to previous lines seems a bit too much. Besides, there is already mapping for `<BS>` in 'mini.pairs' which would introduce conflicts.

I don't think this will be a part of 'mini.nvim'. Nevertheless, thanks for taking your time to write this!
