### ISSUE TITLE
`[<space>` / `]<space>` to add blank lines

### ISSUE THREAD

**Issue by mcchrish** [echasnovski/mini.nvim#375]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

bracketed

### Description

Similar feature to https://github.com/tpope/vim-unimpaired

**Comment by echasnovski** [comment]
This is a part of ['mini.basics'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-basics.md) under [`go` and `gO`](https://github.com/echasnovski/mini.nvim/blob/3a11a130bac227462dd226669d260c4bbe33fb5b/doc/mini-basics.txt#L234-L235). Also, unlike 'vim-unimpaired', it is dot-repeatable out of the box.
