### ISSUE TITLE
(mini.surround) Cannot surround with f or F motions

### ISSUE THREAD

**Issue by rosshadden** [echasnovski/mini.nvim#38]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

With the following config:

```lua
require("mini.surround").setup {
	mappings = {
		add = "s",
		delete = "ds",
		replace = "cs",
	}
}
```

I am able to use most motions, including `t` and `T`, but cannot surround with vim's vanilla `f` or `F` motions.

### Neovim version

NVIM v0.7.0-dev+848-gb4fbb9dcf

### Steps to reproduce

1. Verify that `<surround.add>t<char>` and `<surround.add>T<char>` work
2. Attempt to use `<surround.add>f<char>` and `<surround.add>F<char>`

### Actual behavior

Pressing `f` or `F` in surround's operator pending mode seems to just exit the mode and carry out the normal `f`/`F` motion (finding a character).

**Comment by echasnovski** [comment]
Considering that `tT` work but `fF` don't and that you mapped plain `s` to `surround.add`, I would guess that you type `sf` and `sF` somewhat fast. These leads to activating `find` and `find_left` default mappings, which find surrounding character (not really a default `f/F` motions). To verify that, first type `s`, then wait some time (at least `timeoutlen` milliseconds) and only then try `f/F`.

There are several solutions for your:
- Don't create other default 'mini.surround' maps. You can supply `''` to disable them.
- By aware that you need to wait after `s` before applying `f`/`F`/`h`/`n` in operator pending mode.
- Decrease `timeoutlen` (seems a bit drastic, but an option nevertheless).

**Comment by rosshadden** [comment]
Oh yeah, you're totally right. I didn't even realize `sf` was a thing.
Thanks!
