### ISSUE TITLE
Allows center alignment for Mini.Files

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#382]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Mini.Files

### Description

In Zen mode, it would be beneficial to have center alignment layout for Mini.Files - and, similarly, it would also be useful when the terminal width is smaller, such as GNOME Terminal default 80x24:

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/ee18f716-550c-474c-a689-32e7d714eaba)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/fa2ecb62-b21b-4d1d-9689-f8ad843c62a1)

**Comment by echasnovski** [comment]
Thanks for suggestion!

Unfortunately, this will result into a lot of extra code, which is not good.

Also having it always in top-left ensures maximum space to show both directory contents and branch depth.

Closing as not planned.

**Comment by echasnovski** [comment]
> @echasnovski Just a thought, achieving the same result is feasible by setting `windows.max_number` to 1 and making minor tweaks to row and column. For individuals who are not concerned about depth, could there be a possibility of offering it as a configurable option when `max_number = 1` ?

I am highly against it now, but will be keeping this in mind.

**Comment by idelice** [comment]
+1

@echasnovski  you have "kept this in mind" for 10~ months now. 

Any plan on adding this feature that enables consumers to modify the position?

**Comment by wroyca** [comment]
> FYI, what "will be keeping this in mind" referred to was allowing config tweaks for the single window.
> 
> No, I am still against it for the reasons stated in [this comment](https://github.com/echasnovski/mini.nvim/issues/382#issuecomment-1604737337).

Are you still against it for the single window? I find myself running a tiny fork locally to adjuste the position a little ( adding just slightly more padding/margin in the top left for example ) :)
