### ISSUE TITLE
mini.misc: `setup_restore_cursor()` doesn't unfold folds

### ISSUE THREAD

**Issue by AlexKurisu** [echasnovski/mini.nvim#383]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.misc

### Description

`setup_restore_cursor()` neither unfolds folds nor centers screen on line after opening the file with folds

`minimal.lua`:
```
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "echasnovski/mini.nvim",
        version = false,
        config = function()
            require("mini.misc").setup()
            MiniMisc.setup_restore_cursor()
        end,
    },
})
```

</details>

### Neovim version

0.10.0-dev-565+g3688735c2b

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Open any file with latest position being inside folds

### Actual behavior

Folds don't get unfolded, window is not centered at last line

**Comment by echasnovski** [comment]
I can not reproduce this neither on Neovim 0.9.1 nor on the latest Nightly (`NVIM v0.10.0-dev-569+gfa0a25dcb`). It also passes designated tests for unfolding and centering both locally and on GitHub actions. It also works for me both with my normal configuration and with your example (with added `vim.o.foldmethod = 'indent'` line).

Couple of questions:
- Just to be safe, did you actually test this with the config you provided?
- Are you sure, that `MiniMisc.setup_restore_cursor()` is actually executed prior you opening the file? It might happen if there is some lazy loading involved.
- Are you sure, that folds are closed prior to opening file?

**Comment by AlexKurisu** [comment]
>did you actually test this with the config you provided
Yes, and that works for me
>MiniMisc.setup_restore_cursor() is actually executed prior you opening the file
Yep, i have lazy-loading disabled everywhere
>folds are closed prior to opening file
Yes

**Comment by AlexKurisu** [comment]
Cannot reproduce the bug anymore too. Weird…
