### ISSUE TITLE
mini.ai bugs in the help file examples

### ISSUE THREAD

**Issue by yodigi7** [echasnovski/mini.nvim#384]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

I have LazyVim installed which is using mini.ai module. When going to the mini.ai help file to learn and test the module it is not selecting the expected objects.

On line 159 of the help file. When I hover the cursor over the `*` and type `vit` it is expected to select the `*` character at position 4 as expected however it instead jumps to select the `b` character at position 12.

For context:
```
|---|---------------|-1234567890123456-|--------|--------|--------|--------|
| t |      Tag      | <x>*</x><y>b</y> | [1;8]  | [4;4]  | [9;16] |[12;12] |
```

I noticed that the highlighting of the tags is very weird where just hovering over the `b` character it naturally hint highlights from position 5 to 16. I assume this is from something like treesitter which may not be correctly parsing out the tags.

### Neovim version

0.9.1

### Steps to reproduce

Currently using LazyVim but can try to put together a minimal config if not reproducable. Would be nice if you could supply me with a minimal lua config as I was having an issue getting mini.ai working with that as the only plugin for lazy.vim

### Expected behavior

Select the text as described int he help file.

### Actual behavior

Highlighting a different part of the text.

**Comment by echasnovski** [comment]
Thanks for noticing this (and actually reading help page, for that matter :) ).

It was not an issue with module, but with example. The reason it selected inside next tag is because after initiating Visual mode with `v` the whole inner tag was already selected, so 'mini.ai' tried to search for another (using default "cover_or_next" search method).

I've updated example so that it could showcase `tag` textobject.
