### ISSUE TITLE
Option to open mini.files at the bottom of the window instead of at the top

### ISSUE THREAD

**Issue by heygarrett** [echasnovski/mini.nvim#385]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Currently, mini.files opens at the top. But when opening small files most of the content is obscured until mini.files is closed. It's also far from the command line at the bottom of the window, where I use a user command to open mini.files.

I'd love an option to open mini.files at the bottom of the window.  
- It wouldn't obscure small files opened with mini.files  
- I wouldn't need to move my eyes very far at all after typing my user command to open mini.files

**Comment by echasnovski** [comment]
Thanks for suggestion!

No, this is not planned. For at least these reasons:
- It will introduce too much new code to deal with not fixed opening position.
- Having it at the bottom means that top part of the windows will either be not aligned or have different row relative to editor. Which is not good.

Closing as not planned.
