### ISSUE TITLE
Consider implementing Sideways.vim

### ISSUE THREAD

**Issue by jdsutherland** [echasnovski/mini.nvim#387]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

ai

### Description

It'd be nice to have a lua version of https://github.com/AndrewRadev/sideways.vim and it seems like it may fit well with mini.nvim. I haven't looked deeply, but it seems like TS would allow for a cleaner implementation, though I suspect TS won't cover everything. I particularly find the 'Adding items' feature useful for frontend development, where it's common to append properties as the last argument using the dot operator.

I'm not sure if you'd consider the `ai` module to be a good fit but there is some overlap since Sideways.vim also features text objects.

**Comment by IndianBoy42** [comment]
iswap.nvim has ISwapLeft and ISwapRight commands (and much more)

**Comment by echasnovski** [comment]
Thanks for suggestion!

I've used 'sideways.vim' myself up until 'mini.ai' with its argument textobject. I mostly used it for swapping arguments and replaced it with custom mapping using [tommcdo/vim-exchange](https://github.com/tommcdo/vim-exchange):
- `<Cmd>normal cxiacxila<CR>` to move argument to the left.
- `<Cmd>normal cxiacxina<CR>` to move argument to the right.

These are not ideal, but do the job.

So instead I am planning to implement 'mini.swap' (or 'mini.exchange') which will allow exchanging to text regions.

**Comment by adrianstaniec** [comment]
Evgeni put this solution in [MiniMax](https://github.com/nvim-mini/MiniMax/blob/main/configs/nvim-0.11/plugin/30_mini.lua)
```lua
  require('mini.operators').setup()
  -- Create mappings for swapping adjacent arguments. Notes:
  -- - Relies on `a` argument textobject from 'mini.ai'.
  -- - It is not 100% reliable, but mostly works.
  -- - It overrides `:h (` and `:h )`.
  -- Explanation: `gx`-`ia`-`gx`-`ila` <=> exchange current and last argument
  -- Usage: when on `a` in `(aa, bb)` press `)` followed by `(`.
  vim.keymap.set('n', '(', 'gxiagxila', { remap = true, desc = 'Swap arg left' })
  vim.keymap.set('n', ')', 'gxiagxina', { remap = true, desc = 'Swap arg right' })
```
