### ISSUE TITLE
Starter is shown when creating a new file

### ISSUE THREAD

**Issue by Penaz91** [echasnovski/mini.nvim#39]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

Greetings.

When I try to create a new file using `nvim <filename>`, instead of showing an empty file, ready to write in, the starter is shown, forcing me to use the "edit new buffer" option.

Thank you in advance.

### Neovim version

0.6.1

### Steps to reproduce

1. `nvim <filename>` where "<filename>" is the name of a file that doesn't exist yet

### Expected behavior

Nvim starts on an empty buffer, since a filename is present.

### Actual behavior

Mini.starter is shown, like when I start nvim without any file name.

**Comment by echasnovski** [comment]
Thanks! Should be fixed in `main` branch.

It was me very excited that couple of days ago that condition for showing Starter buffer can be "greatly simplified". It turns out not to be the case :)
