### ISSUE TITLE
mini.files: use `:w` to save filesystem changes

### ISSUE THREAD

**Issue by mrjones2014** [echasnovski/mini.nvim#391]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

If you set the buftype to `acwrite` it makes it so that read/write events are handled by autocmds. Then, you can use `BufWriteCmd` and `BufReadCmd` to handle simulated read/write events.

This way, you could have `:w` from the `mini.files` buffer do the same thing as pressing `=` from the same buffer.

**Comment by mrjones2014** [comment]
For what it's worth, I've got it working in my own config like so:

```lua
vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesBufferCreate',
  callback = function()
    vim.schedule(function()
      vim.api.nvim_buf_set_option(0, 'buftype', 'acwrite')
      vim.api.nvim_buf_set_name(0, require('mini.files').get_fs_entry(0, 1).path)
      vim.api.nvim_create_autocmd('BufWriteCmd', {
        buffer = 0,
        callback = function()
          require('mini.files').synchronize()
        end,
      })
    end)
  end,
})
```

**Comment by mrjones2014** [comment]
>Technical details. Saving buffer means using certain approach at adding name to buffer which I don't think I'd like to add, as it increases complexity for not much benefit (together with previous points).

With `buftype=acwrite` it doesn't matter at all what the buffer name is as long as it isn't blank. It just has to have any name, and then your `BufWriteCmd` autocmd handles "writing" the buffer, which in this case isn't a file so you don't actually need the buffer name.

**Comment by echasnovski** [comment]
> For what it's worth, I've got it working in my own config like so:
> 
> ```lua
> vim.api.nvim_create_autocmd('User', {
>   pattern = 'MiniFilesBufferCreate',
>   callback = function()
>     vim.schedule(function()
>       vim.api.nvim_buf_set_option(0, 'buftype', 'acwrite')
>       vim.api.nvim_buf_set_name(0, require('mini.files').get_fs_entry(0, 1).path)
>       vim.api.nvim_create_autocmd('BufWriteCmd', {
>         buffer = 0,
>         callback = function()
>           require('mini.files').synchronize()
>         end,
>       })
>     end)
>   end,
> })
> ```

Yeah, but a more logical way of introducing working `:w` instead of duplicating `=` is to synchronize only buffer's changes. Which doesn't cover all use cases properly and means more code.

**Comment by echasnovski** [comment]
I don't think having this functionality (synchronization only of current buffer after `:w` or on `BufWritePost` event) meets reasonable threshold for "features/complexity" trade-off.

Together with mentioned earlier points, I think I'll close this as not planned.

**Comment by Susensio** [comment]
> For what it's worth, I've got it working in my own config like so:
> 
> ```lua
> vim.api.nvim_create_autocmd('User', {
>   pattern = 'MiniFilesBufferCreate',
>   callback = function()
>     vim.schedule(function()
>       vim.api.nvim_buf_set_option(0, 'buftype', 'acwrite')
>       vim.api.nvim_buf_set_name(0, require('mini.files').get_fs_entry(0, 1).path)
>       vim.api.nvim_create_autocmd('BufWriteCmd', {
>         buffer = 0,
>         callback = function()
>           require('mini.files').synchronize()
>         end,
>       })
>     end)
>   end,
> })
> ```

I had to tweak it because it failed on opening an empty directory. Instead of using the current cursor entry to name the buffer, i use the buffer number.

This is the result
```lua
vim.api.nvim_create_autocmd('User', {
        pattern = 'MiniFilesBufferCreate',
        callback = function(ev)
          print('MiniFilesBufferCreate')
          vim.schedule(function()
            print("scheduled")
            vim.api.nvim_buf_set_option(0, 'buftype', 'acwrite')
            vim.api.nvim_buf_set_name(0, tostring(vim.api.nvim_get_current_win()))
            vim.api.nvim_create_autocmd('BufWriteCmd', {
              buffer = 0,
              callback = MiniFiles.synchronize,
            })

            -- close with <esc>
            vim.keymap.set("n", "<Esc>", MiniFiles.close, { buffer = ev.buf })
          end)
        end,
      })
```
