### ISSUE TITLE
(mini.surround) Preserve attributes when replacing tag

### ISSUE THREAD

**Issue by thenbe** [echasnovski/mini.nvim#397]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Example:

> Starting position

```html
<p class="foo">Lo*rem ipsum</p>
```

1. Cursor represented by asterisk
2. Press `csttspan<CR>`

> Current result:

```html
<span>Lorem ipsum</span>
```

> Desired result:

```html
<span class="foo">Lorem ipsum</span>
```

## Prior art

- vim-surround [keeps](https://github.com/tpope/vim-surround/blob/3d188ed2113431cf8dac77be61b842acb64433d9/doc/surround.txt#L132-L136) keeps the attributes. However if you end your pattern with `>` (e.g. `srttspan><CR>`), it omits them.

**Comment by echasnovski** [comment]
Thanks for suggestion!

Unfortunately this is out of scope for 'mini.surround' as it doesn't really fit its design. Replacing is done uniformly for all surroundings:
- First find left and right parts for input surrounding. In your case it is `<p class="foo">` and `</p>`.
- Replace found left and right parts with left and right parts of output surrounding correspondingly. As after `tspan<CR>` left and right parts are `<span>` and `</span>`, the result is what you are seeing.

The best suggestion I can make within 'mini.surround' functionality is to manually supply attributes for output surrounding. So type `srt` followed by `t`, `span class="foo"`, and `<CR>`.
