### ISSUE TITLE
Add module targets.vim

### ISSUE THREAD

**Issue by CRAG666** [echasnovski/mini.nvim#4]
add module similar to https://github.com/wellle/targets.vim

**Comment by echasnovski** [comment]
Yeah, It seems a little bit complex, but I'll think about it.
What might help me make a decision:
- More people having this request (please upvote first comment with emoji).
- More people share what their crucial functionality is. Like:
    - Do you use all of 'aiAI` or just `ai`?
    - Do you use any of `inb` etc. (like `d2inb` "will skip one next pair (any kind) and delete in the one after (any kind)")?
    - Do you have anything "must have" in this type of plugin?

**Comment by CRAG666** [comment]
I have another question but I don't want to open a new issue, how can I substitute ' for " if I'm at the beginning of the line? Example: helloworld(' some word '), I still haven't been able to do it, which with vim-surround was just cs'"

**Comment by echasnovski** [comment]
After about 9 months I finally felt confident enough to make it useful and the way I want to. 'mini.nvim' now has [mini.ai](https://github.com/echasnovski/mini.nvim#miniai).

Thanks for the issue!
