### ISSUE TITLE
[mini.completion] "invalid window id" error

### ISSUE THREAD

**Issue by justinmk** [echasnovski/mini.nvim#401]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

Sometimes in LSP-enabled buffers I see a `Invalid window id` error:

### Neovim version

NVIM v0.10.0-dev-613+gdb590e96d593

### Steps to reproduce

I don't have a root cause, but mini.completion could avoid the error by checking if a window id is valid.

### Expected behavior

No error.

### Actual behavior

```
Error executing vim.schedule lua callback: .../pack/paqs/start/mini.completion/lua/mini/completion.lua:1282: Invalid window id: 1304
stack traceback:
        [C]: in function 'nvim_win_close'
        .../pack/paqs/start/mini.completion/lua/mini/completion.lua:1282: in function 'close_action_window'
        .../pack/paqs/start/mini.completion/lua/mini/completion.lua:1078: in function 'show_signature_window'
        .../pack/paqs/start/mini.completion/lua/mini/completion.lua:1063: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:2171: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1499: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by echasnovski** [comment]
Thanks for the issue!

Interesting. I did also have couple of errors recently (on Neovim 0.9.1), but that seemed to be the result of loading session without restarting Neovim.

I'll look into it.
