### ISSUE TITLE
[mini.files] preview window is not closed

### ISSUE THREAD

**Issue by lost22git** [echasnovski/mini.nvim#402]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

preview window is not closed

### Neovim version

0.9.1

### Steps to reproduce

![1](https://github.com/echasnovski/mini.nvim/assets/65008815/b6021bb3-8d81-4b4c-a979-9e03f381ddd4)

### Actual behavior

preview window is not closed

**Comment by echasnovski** [comment]
What do you press to achieve this? If you use in any form a regular `:quit`, then this is expected, as it is designed to close only current window. To close explorer, press `q` or execute `:lua require('mini.files').close()`.

**Comment by lost22git** [comment]
my fault, it works as expected when press `q`, thanks a lot ; )
