### ISSUE TITLE
[mini.files] Open mini.files in current file directory with current file selected.  Expanded by cwd

### ISSUE THREAD

**Issue by otavioschwanck** [echasnovski/mini.nvim#406]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Open mini.files in current file directory with current file selected.  Expanded by cwd

Today, i have to do it:
```lua
MiniFiles.open(vim.fn.expand("%:p:h"))
```

But this have two problems:

1 - If i run again on same file, it will go to last place it was
2 - i can see the previous folders.

The ideal is to open like that:

(I am on mini.lua buffer and call the command)
![image](https://github.com/echasnovski/mini.nvim/assets/9551316/dd48af59-8df2-4234-94b1-1cc4b687a0c0)

Suggestion:

MiniFiles.open_in_file(filename)

or

MiniFiles.open_in_current_file()

**Comment by echasnovski** [comment]
Thanks for the suggestion!

You can supply file path directly to `MiniFiles.open()` in which case [it will try to focus on that file](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L628-L629). You can use path of current buffer [like this](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L616) or [like this](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L619).

Expanding until current working directory was requested more than once, so I'll think about it. But there isn't high hope for it to be implemented, as it both is somewhat visible in window title full path and can be reached manually by going out. Meanwhile, there is [this custom solution](https://github.com/echasnovski/mini.nvim/discussions/395#discussioncomment-6305006).

**Comment by otavioschwanck** [comment]
> Thanks for the suggestion!
> 
> You can supply file path directly to `MiniFiles.open()` in which case [it will try to focus on that file](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L628-L629). You can use path of current buffer [like this](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L616) or [like this](https://github.com/echasnovski/mini.nvim/blob/760c1f3619418f769526884a3de47f0b76245887/doc/mini-files.txt#L619).
> 
> Expanding until current working directory was requested more than once, so I'll think about it. But there isn't high hope for it to be implemented, as it both is somewhat visible in window title full path and can be reached manually by going out. Meanwhile, there is [this custom solution](https://github.com/echasnovski/mini.nvim/discussions/395#discussioncomment-6305006).

@echasnovski 

Thanks for the custom solution!  But there is a problem with it.  After a while, it starts throwing error:

```
Error executing vim.schedule lua callback: (mini.files) `line` should be a valid line number in buffer 19.
stack traceback:
	[C]: in function 'error'
	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2428: in function 'error'
	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2422: in function 'validate_line'
	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:878: in function 'get_fs_entry'
	/Users/otavio/.config/nvim/lua/core/mappings.lua:92: in function </Users/otavio/.config/nvim/lua/core/mappings.lua:64>
```

**Comment by echasnovski** [comment]
> @echasnovski
> 
> Thanks for the custom solution! But there is a problem with it. After a while, it starts throwing error:
> 
> ```
> Error executing vim.schedule lua callback: (mini.files) `line` should be a valid line number in buffer 19.
> stack traceback:
> 	[C]: in function 'error'
> 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2428: in function 'error'
> 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2422: in function 'validate_line'
> 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:878: in function 'get_fs_entry'
> 	/Users/otavio/.config/nvim/lua/core/mappings.lua:92: in function </Users/otavio/.config/nvim/lua/core/mappings.lua:64>
> ```

This should be addressed in that discussion.

Meanwhile, I **think** I'll add separate `reveal_cwd()` function. It than could be used both as a separate buffer mapping (created inside `MiniFilesBufferCreate`) or inside user mapping used to open explorer.

**Comment by otavioschwanck** [comment]
> > @echasnovski
> > Thanks for the custom solution! But there is a problem with it. After a while, it starts throwing error:
> > ```
> > Error executing vim.schedule lua callback: (mini.files) `line` should be a valid line number in buffer 19.
> > stack traceback:
> > 	[C]: in function 'error'
> > 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2428: in function 'error'
> > 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:2422: in function 'validate_line'
> > 	...vio/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:878: in function 'get_fs_entry'
> > 	/Users/otavio/.config/nvim/lua/core/mappings.lua:92: in function </Users/otavio/.config/nvim/lua/core/mappings.lua:64>
> > ```
> 
> This should be addressed in that discussion.
> 
> Meanwhile, I **think** I'll add separate `reveal_cwd()` function. It than could be used both as a separate buffer mapping (created inside `MiniFilesBufferCreate`) or inside user mapping used to open explorer.

i think is a good idea

**Comment by silicakes** [comment]
Wonderful idea!
Are there any updates on this?
