### ISSUE TITLE
[mini.files] Folder picker

### ISSUE THREAD

**Issue by otavioschwanck** [echasnovski/mini.nvim#407]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Would be awesome to have an folder picker with fuzzy to open mini.files direct in this folder.

The ideal is to open this folder expanded by cwd (or have an option to do that)

**Comment by echasnovski** [comment]
Thanks for suggestion!

This is out of scope for 'mini.files'. It provides `open()` function which can be used inside any picker of your choice.

Closing as not planned.

**Comment by towry** [comment]
You can use telescope-file-browser and make it's default action to open mini.files.
