### ISSUE TITLE
[bug] Failed to run `config` for mini.basics

### ISSUE THREAD

**Issue by sarvex** [echasnovski/mini.nvim#408]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.basicss

### Description

```lua
H.is_default_keymap = function(mode, lhs, map_info)
  if map_info == nil then return true end

  -- Some mappings are set by default in Neovim
  if mode == 'n' and lhs == '<C-L>' then return map_info.rhs:find('nohl') ~= nil end
  if mode == 'x' and lhs == '*' then return map_info.rhs == [[y/\V<C-R>"<CR>]] end
  if mode == 'x' and lhs == '#' then return map_info.rhs == [[y?\V<C-R>"<CR>]] end
end
``` 
The case where :find fails is not handled 

```powershell
2023-07-10T16:23:00 lazy.nvim  ERROR Failed to run `config` for mini.basics

...ata/Local/nvim-data/lazy/mini.basics/lua/mini/basics.lua:701: attempt to index field 'rhs' (a nil value)

# stacktrace:
  - mini.basics\lua\mini\basics.lua:701 _in_ **is_default_keymap**
  - mini.basics\lua\mini\basics.lua:690 _in_ **map**
  - mini.basics\lua\mini\basics.lua:650 _in_ **apply_mappings**
  - mini.basics\lua\mini\basics.lua:428 _in_ **apply_config**
  - mini.basics\lua\mini\basics.lua:82 _in_ **setup**
  - AppData/Local/nvim/lua/astronvim/utils/init.lua:144
````

### Neovim version

Nightly

### Steps to reproduce

Windows 11
Windows Terminal
Neovim Nightly

### Expected behavior

No Error

### Actual behavior

Error

**Comment by echasnovski** [comment]
Thanks for the issue!

I guess, `<C-l>` is mapped with Lua callback in your case?

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.
