### ISSUE TITLE
[mini.files] Swap alert causes error while go_in

### ISSUE THREAD

**Issue by sunho** [echasnovski/mini.nvim#410]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

First, thanks for amazing plugin. I've been enjoying this plugin so much! The issue is:

When I go in to the file inside mini.files and there's a swap alert, after I respond to swap alert I'm seeing this error:

<img width="1387" alt="Screenshot 2023-07-10 at 5 43 03 AM" src="https://github.com/echasnovski/mini.nvim/assets/12246126/c2db7abb-15aa-4bb1-a420-4d6a50be3307">

This is not that annoying for regular go in. But for go_in_plus (key L) which closes the mini.files window when I go inside the file, this error actually prevent the closing of the mini.files window.

### Neovim version

760c1f3619418f769526884a3de47f0b76245887 (top of tree)

### Steps to reproduce

1. Setup mini.files with default setting
2. Go in plus to file with swap using key 'L'
3. Error shows up and the mini.files window does not close

### Expected behavior

No error and mini.files window closes

### Actual behavior

Error shows up and mini.files window does not close

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`. Although I couldn't create a reproducible test, 'mini.files' error should not show up while regular swap file notification should still be there.

**Comment by sunho** [comment]
I just tried it now and it's indeed fixed!
