### ISSUE TITLE
Support inlay virtual text option for mini.hipatterns

### ISSUE THREAD

**Issue by calops** [echasnovski/mini.nvim#411]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

hipatterns

### Description

The new anticonceal feature in neovim 0.10 opens up the possibility of displaying inlay virtual text with the hipatterns extmarks instead of (or in addition to) just highlights. That way, we could for example display a dot of the corresponding color next to a hex code rather than coloring the code itself (which can sometimes conflict with other highlights).

I don't believe this should be the default but it doesn't sound too out of scope for this plugin to offer this as an option, since it already defines extmarks anyway.

I don't know if it would be best to hold off until 0.10 is released? I don't think that part of the API will change.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is indeed planned and is already tracked in #340. It is reasonable to wait until this functionality is in stable release, as supporting Nightly feature usually comes with much maintenance burden.

**Comment by echasnovski** [comment]
@calops, this is now possible on latest `main`. There is a more general `extmark_opts` available which can utilize `virt_text_pos = 'inline'` feature.

And regarding using that to show colors: this is now possible with a new [`style = 'inline'`](https://github.com/echasnovski/mini.nvim/blob/35e29f7d680cfeb496415cadadd8c1f68db759b9/lua/mini/hipatterns.lua#L504-L505).

**Comment by calops** [comment]
@echasnovski thanks! This is looking much better now:
![image](https://github.com/echasnovski/mini.nvim/assets/4097716/c9a24966-e18c-4b9d-9789-81f950fbab43)
