### ISSUE TITLE
[mini.files] Changing filename casing doesn't work

### ISSUE THREAD

**Issue by kolyamba2105** [echasnovski/mini.nvim#412]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Thanks a lot for such a great plugin!

`mini.files` fails to update the displayed filename when a file is renamed, specifically when changing the case of the filename (e.g., from `someFile.lua` to `somefile.lua`). Although the `mini.files` correctly recognizes the changed filename after synchronizing changes, the displayed filename does not update accordingly after accepting the changes.

### Neovim version

NVIM v0.10.0-dev-562+gf0884f21f-Homebrew

### Steps to reproduce

1. Open Neovim
2. Execute the command `:lua MiniFiles.open()`
3. Enter insert mode and add a file named `someFile.lua`
4. Execute the command `:lua MiniFiles.synchronize()` and accept changes 
5. Locate the file `someFile.lua` and rename it to `somefile.lua` (changing the case to lowercase)
6. Execute the command `:lua MiniFiles.synchronize()` and accept changes 
7. Observe that the file name has not changed, despite `mini.files` correctly recognizing the updated filename

### Expected behavior

`someFile.lua` changes to `somefile.lua` after renaming, synchronizing and accepting changes.

### Actual behavior

Filename doesn't change, despite `mini.files` recognizing the updated filename.

https://github.com/echasnovski/mini.nvim/assets/33033411/a935c22e-c8f6-4f47-8430-432af1b05ec9

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce: file is renamed on both Neovim 0.9.1 and latest Nightly.

What OS do you use? If Windows or MacOS, then they ignore case and this renaming might be a problem.

**Comment by kolyamba2105** [comment]
Ah, didn't know about that. I am on MacOS 😞

**Comment by kolyamba2105** [comment]
Indeed, `ranger` does not support case changing either, it errors with `Can't rename: file already exists!`. I also tried `nvim-tree`, but it also didn't work.

**Comment by echasnovski** [comment]
Thanks for the follow up!

Then, I am afraid, 'mini.files' can't do much here due to this MacOS-specific case.
