### ISSUE TITLE
`bufdelete` on the last buffer in a tab doesn't delete the tab

### ISSUE THREAD

**Issue by mehalter** [echasnovski/mini.nvim#419]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.bufremove

### Description

When using `require("mini.bufremove").delete()` with the last buffer in a vim tab there is some undesired behavior which causes buffers from other tabs to be assigned to the current tab. This can be very confusing and disorienting.

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -nu minimal.lua` (see below)
2. open a file with any method, ex. `:e file_name`
3. open a new tab `:tabnew`
4. run `require("mini.bufremove").delete()`
5. See that a buffer from another tab will be moved into the tab rather than closing it.

`minimal.lua`

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--branch=stable",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	"echasnovski/mini.bufremove",
})
```

### Expected behavior

The expected behavior should be similar to `:bdelete` in this case in which it would delete the tab if there are no more buffers to be displayed

### Actual behavior

Another buffer from another tab is assigned to the window.

**Comment by echasnovski** [comment]
The whole point of 'mini.bufremove' is that it does not change layout after buffer unshow/delete/wipeout. Closing tabpage is a layout change so it is not aligned with 'mini.bufremove' design.

Closing as not planned.

**Comment by mehalter** [comment]
🤔 hm, a vim tab is a collection of buffers managed by the user. When removing the last buffer in a vim tab it breaks down this core vim system when relocating buffers between tabs for the user. If the user has meticulously organized their tabs to hold a specific collection of buffers then this will effectively destroy this organization. Then deleting that buffer in the new tab or even just closing that tab will then remove that buffer from the other tab that it was assigned to.

I do understand your reasoning though. I am already wrapping this functionality to add support for confirmation dialog so I can just add a hacky fix for this to check if it's the last buffer in a tab and just run `:bdelete` to get the appropriate core vim behavior.

Thanks for your time!

**Comment by echasnovski** [comment]
> thinking hm, a vim tab is a collection of buffers managed by the user. When removing the last buffer in a vim tab it breaks down this core vim system when relocating buffers between tabs for the user. If the user has meticulously organized their tabs to hold a specific collection of buffers then this will effectively destroy this organization. Then deleting that buffer in the new tab or even just closing that tab will then remove that buffer from the other tab that it was assigned to.
> 
> I do understand your reasoning though. I am already wrapping this functionality to add support for confirmation dialog so I can just add a hacky fix for this to check if it's the last buffer in a tab and just run `:bdelete` to get the appropriate core vim behavior.
> 
> Thanks for your time!

Tabpage is not a collection of buffers, it is a collection of windows. Here is an excerpt from `:h windows-intro`:

```
Summary:
   A buffer is the in-memory text of a file.
   A window is a viewport on a buffer.
   A tab page is a collection of windows.
```

Windows and buffers are more or less independent from one another. Deleting a buffer should not affect windows (hence the creation of 'mini.bufremove' and similar plugins). As tabpage is a collection of windows, deleting a buffer should also not affect tabpages.
