### ISSUE TITLE
Change cwd on open

### ISSUE THREAD

**Issue by shasherazi** [echasnovski/mini.nvim#421]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

When I open neovim like `nvim dotfiles/config/nvim` from the home directory `mini.files` opens like this
![image](https://github.com/echasnovski/mini.nvim/assets/63230301/a1c04794-74a2-4542-9d7b-739608c31b6d)

But the next time `mini.nvim` is opened, it shows this
![image](https://github.com/echasnovski/mini.nvim/assets/63230301/57a75379-c18b-4355-8294-b5c8015c640b)

I used `nvim-tree` before and it changed the working directory to whichever folder was first opened and persisted. Can I have this feature in `mini.files` as well?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

`MiniFiles.open()` by default uses current working directory as anchor (target) directory. When you open `nvim dotfiles/config/nvim`, `MiniFiles.open()` is called with `'dotfiles/config/nvim'` path, but when you later call it (probably without arguments), it is called without arguments and uses current working directory (which by default is the one Neovim was opened in; `~` in your case).

You have several options:
- Create a 'mini.files' mapping which changes current working directory to the one inside which cursor is located. Here is [an example](https://github.com/echasnovski/mini.nvim/blob/2b37c5e1d2a3f62ba4060a819f17d8d976018928/doc/mini-files.txt#L451).
- Use automated change of current working directory. For example, [`MiniMisc.setup_auto_root()`](https://github.com/echasnovski/mini.nvim/blob/2b37c5e1d2a3f62ba4060a819f17d8d976018928/doc/mini-misc.txt#L119) from 'mini.misc'.
- Manually change current working directory to the one you'd like.

Closing as not planned.

**Comment by shasherazi** [comment]
Hi, I tried the first two methods, and kinda both of them failed. For the first method, I need to open a file in that directory, and for the second method, it just selects the sensible root (the directory with `.git` in my case, where I am trying to open `nvim` in a subfolder).

Basically, what I wanted was to get the path argument when running `nvim` and change `cwd` to that. I have searched fairly long time but couldn't find a way. Guess I'll just stick to the 2nd method till a solution is found.

**Comment by echasnovski** [comment]
> For the first method, I need to open a file in that directory,

Judging by your example, you've already inside target directory, so first method (with example buffer mapping from 'mini.files') should work (assuming directory is not empty, though).

> Basically, what I wanted was to get the path argument when running `nvim` and change `cwd` to that. I have searched fairly long time but couldn't find a way. Guess I'll just stick to the 2nd method till a solution is found.

I am not sure if I understand correctly, but this basically sounds like a combination `argv()` and `chdir()` built-in functions. Try putting something like this inside your config startup files:

```lua
if vim.fn.argc(-1) > 0 then
  local path = vim.fn.argv(0)
  if vim.fn.isdirectory(path) == 0 then path = vim.fs.dirname(path) end
  vim.fn.chdir(path)
end
```

**Comment by Parsifa1** [comment]
> ### Contributing guidelines 贡献指南
> * [x]  I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md) 我已阅读 CONTRIBUTING.md
> * [x]  I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md) 我已阅读 CODE_OF_CONDUCT.md
> 
> ### Module(s) 模块
> mini.files 迷你文件
> 
> ### Description 描述
> When I open neovim like `nvim dotfiles/config/nvim` from the home directory `mini.files` opens like this当我从主目录 `nvim dotfiles/config/nvim` 打开neovim时 `mini.files` 像这样打开 ![image](https://user-images.githubusercontent.com/63230301/253785985-a1c04794-74a2-4542-9d7b-739608c31b6d.png)
> 
> But the next time `mini.nvim` is opened, it shows this但是下次打开 `mini.nvim` 时，它会显示这个 ![image](https://user-images.githubusercontent.com/63230301/253785997-57a75379-c18b-4355-8294-b5c8015c640b.png)
> 
> I used `nvim-tree` before and it changed the working directory to whichever folder was first opened and persisted. Can I have this feature in `mini.files` as well?我之前使用过 `nvim-tree` ，它将工作目录更改为首先打开并保留的文件夹。我也可以在 `mini.files` 中使用此功能吗？
```lua
    vim.keymap.set("n", "<leader>e", ":lua MiniFiles.open(vim.api.nvim_buf_get_name(0))<CR>", {noremap = true,
        silent = true,})
```
mayme you can try keymap like this(?
