### ISSUE TITLE
feat: mini-comment - different mapping for normal and visual mode

### ISSUE THREAD

**Issue by IndianBoy42** [echasnovski/mini.nvim#422]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

I want to use `gc` for commenting in normal mode and `C` for comment in visual mode. I think the only way to do this now is to disable the automatic mapping through the config and then mapping it myself. 

Could you make it so if `mappings.visual_comment` is given through setup the it is used for the visual mode mapping. For backwards compatibility if its not given then `mappings.comment` is used.

**Comment by echasnovski** [comment]
Thanks for suggestion!

At the moment, I think the current setup is sufficient. But I'll think about it, as it is indeed not that big of a change.

**Comment by IndianBoy42** [comment]
I suppose it is sufficient for most people. 

Maybe changing the doc to talk about how to map it manually works too. You mentioned that `it has a somewhat unintuitive logic` so the only way I really had to know how to map it was to go into the code and copy that.

**Comment by echasnovski** [comment]
This should be now possible on `main` branch with `config.mappings.comment_visual`.
