### ISSUE TITLE
loading nvim-tree messes up with mini.starter

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#43]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

Even with minimal configuration of https://github.com/kyazdani42/nvim-tree.lua
```lua
require("nvim-tree").setup({})
```
messes up with mini.starter

I don't see any startup screen when I load nvim-tree.lua

### Neovim version

0.6.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. install nvim-tree.lua and mini.starter
3. require("nvim-tree").setup({})
4. now mini.starter stops working

### Expected behavior

mini.starter should work even when loading nvim-tree

### Actual behavior

-

**Comment by echasnovski** [comment]
I load 'nvim-tree' lazily, so it doesn't affect 'mini.starter', so thank you for finding this! Should be fixed in `main` branch.

**Comment by zim0369** [comment]
> I load 'nvim-tree' lazily, so it doesn't affect 'mini.starter', so thank you for finding this! Should be fixed in `main` branch.

It is now fixed. Thank you!
