### ISSUE TITLE
mini.tabline not loading, possible plugin interference

### ISSUE THREAD

**Issue by armaninux** [echasnovski/mini.nvim#432]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

tabline

### Description

tabline is not loading when starting neovim, but it loads regularly when sourcing my init.vim 

### Neovim version

0.9.1-3

### Steps to reproduce

1. launch neovim with plugin itchyny/lightline.vim installed: tabline won't load.
2. source ~/.config/nvim/init.vim: tabline loads.

### Expected behavior

expected regular loading at launch

### Actual behavior

tabline loads normally provided I don't use itchyny/lightline.vim plugin - to my knowledge it's the only factor in my config preventing tabline to load.

**Comment by echasnovski** [comment]
'itchyny/lightline.vim' itself provides tabline. Probably, it sets value of 'tabline' after 'mini.tabline' does in your setup.

Disable 'itchyny/lightline.vim' managing tabline (possibly [like this](https://github.com/itchyny/lightline.vim/blob/b1e91b41f5028d65fa3d31a425ff21591d5d957f/doc/lightline.txt#L1096-L1100)) and it should work.
