### ISSUE TITLE
Hiding tabline when it's only 1 file open

### ISSUE THREAD

**Issue by vaskark** [echasnovski/mini.nvim#433]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

tabline

### Description

Hello. I wish for tabline to not show itself when I have only 1 file open. Is this possible? Not a big deal. I just don't like the way it looks, especially when using nvim as a manpager.

Thanks!

### Neovim version

0.10.0-dev (nightly)

### Steps to reproduce

Just using basic config.

### Expected behavior

Do no show when only 1 file open.

### Actual behavior

Tabline is open (especially during nvim as manpager).

**Comment by echasnovski** [comment]
Hi!

No, it is not possible within 'mini.tabline' itself. You can write custom autocommand for that. Something like this:

```lua
vim.api.nvim_create_autocmd('BufEnter', {
  callback = vim.schedule_wrap(function()
    local n_listed_bufs = 0
    for _, buf_id in ipairs(vim.api.nvim_list_bufs()) do
      if vim.fn.buflisted(buf_id) == 1 then n_listed_bufs = n_listed_bufs + 1 end
    end

    -- Use either approach: first (commented) directly hides tabline while second makes it blank
    -- vim.o.showtabline = n_listed_bufs > 1 and 2 or 0
    vim.o.tabline = n_listed_bufs > 1 and '%!v:lua.MiniTabline.make_tabline_string()' or ' '
  end),
  desc = 'Update tabline based on the number of listed buffers',
})
```

**Comment by vaskark** [comment]
Works! Many thanks.
