### ISSUE TITLE
[mini.completion] Overlapping floating window and pop-up menu

### ISSUE THREAD

**Issue by TM10YMhp** [echasnovski/mini.nvim#436]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

When the border is activated, the floating window can end up positioned behind the popup menu.

### Neovim version

0.9.1

### Steps to reproduce

1. Ensure that the floating window has the border enabled.
2. Type text until the popup menu appears.
3. Ensure that the floating window, with an enabled border, is opened near the end of the Neovim window.

### Expected behavior

I subtracted 2 from the width of the floating window to account for the 2 columns added by the border. This adjustment could be applied only when the border is active.

![after](https://github.com/echasnovski/mini.nvim/assets/91300213/540dce82-ccbd-45d0-aea1-261782142c8e)

### Actual behavior

![before](https://github.com/echasnovski/mini.nvim/assets/91300213/2543bcfd-49c4-4938-be13-d6692aa00f7d)

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce this. There is also similar issue with signature help when it is close to the top border.

I'll fix it some time shortly.

**Comment by echasnovski** [comment]
This should now be fixed in `main` branch. Thanks for using 'mini.completion'!

**Comment by TM10YMhp** [comment]
Thanks for the quick fix. I really appreciate your work on 'mini.completion'.
