### ISSUE TITLE
 Beta-testing 'mini.operators'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#439]
Please leave your feedback about new [mini.operators](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-operators.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Are configuration and function names intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by echasnovski** [comment]
> > Are default values of settings convenient for you?
> 
> Is it planned to eventually provide default values for the `func` used in `evaluate` or in `sort`? Or should each user define those on their own?

They are inferred as [`default_evaluate_func()`](https://github.com/echasnovski/mini.nvim/blob/106c8d6e83235b7a216ea56ad2ed6103ef1f3c9a/doc/mini-operators.txt#L396) and [`default_sort_func()`](https://github.com/echasnovski/mini.nvim/blob/106c8d6e83235b7a216ea56ad2ed6103ef1f3c9a/doc/mini-operators.txt#L417) if config value is `nil`. The main reason for this is that those functions are useful as exported for people to tweak evaluate and sort to their liking.

This is mentioned in the help, maybe should also mention in the comments of default config.

**Comment by TheLeoP** [comment]
@echasnovski Thanks for the reply, makes sense. Sorry for not checking the help first.

**Comment by MariaSolOs** [comment]
@echasnovski yet another amazing `mini` plugin <3

I've been playing around with it and I'm trying to figure out how to sort a word. For example, say I have a string like `'CBA'` and I want it to become `'ABC'`.

I've been trying to tweak the custom `sort_func` documented [here](https://github.com/echasnovski/mini.nvim/blob/106c8d6e83235b7a216ea56ad2ed6103ef1f3c9a/lua/mini/operators.lua#L239-L248) but I haven't been successful (in fact if `delimiter` is empty here Neovim freezes).

**Comment by kiryph** [comment]
### Default mapping `cx` instead of `gx`

I would suggest to use as default mapping for the exchange operation `cx` not `gx`. The latter is associated with open a link and similar for a long time in the vim eco system:

- netrw-gx (at least 18 years: https://github.com/vim/vim/blob/b8a7b560b1c25a059dfb57cbe40f0a3f98ed8e97/runtime/plugin/netrwPlugin.vim#L74)
- https://github.com/rmagatti/gx-extended.nvim
- https://github.com/chrishrb/gx.nvim
- https://gist.github.com/habamax/0a6c1d2013ea68adcf2a52024468752e

**Comment by kiryph** [comment]
Add to the section *Similar plugins* in https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-operators.md following plugins which have already established two operators:

- **vim-scriptease** (`g=`), https://github.com/tpope/vim-scriptease
- **ReplaceWithRegister** (`gr`), https://github.com/inkarkat/vim-ReplaceWithRegister

**Comment by echasnovski** [comment]
> ### Default mapping `cx` instead of `gx`
> 
> I would suggest to use as default mapping for the exchange operation `cx` not `gx`. The latter is associated with open a link and similar for a long time in the vim eco system and found its way into the neovim world as well:
> 
> * netrw-gx (at least 18 years: https://github.com/vim/vim/blob/b8a7b560b1c25a059dfb57cbe40f0a3f98ed8e97/runtime/plugin/netrwPlugin.vim#L74)
> 
> * https://github.com/rmagatti/gx-extended.nvim
> 
> * https://github.com/chrishrb/gx.nvim
> 
> * https://github.com/stsewd/gx-extended.vim
> 
> * https://gist.github.com/habamax/0a6c1d2013ea68adcf2a52024468752e

Yes, I know about that and consciously made the decision to use `gx` for these reasons:
- All default operator keys should start with `g`. Apart from consistency, I don't like using keys that start with `c`, `d`, or `y`, because this would introduce a 'timeoutlen' inconvenience: in order for them to activate, user has to type keys with at most 'timeoutlen' milliseconds between them. This is not that big of a problem with `g` because there are already many mappings in 'mini.nvim' that start with it.
- It can be fairly easy overridden for active `gx` users.

That said, it probably deserves a special note somewhere in the docs.

------

> Add to the section _Similar plugins_ in https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-operators.md following plugins which have already established two operators:
> 
>     * **vim-scriptease** (`g=`), https://github.com/tpope/vim-scriptease
> 
>     * **ReplaceWithRegister** (`gr`), https://github.com/inkarkat/vim-ReplaceWithRegister

Including 'tpope/vim-scriptease' is probably a bit of a stretch because it is mostly about writing Vimscript plugins. And `g=` is only about Vimscript there, while in 'mini.operators' it is about Lua by default and can be customized.

Yes, I've thought about including 'inkarkat/vim-ReplaceWithRegister', but the list already has two plugins that implement this functionality with both seeming like being more popular among Neovim users than 'vim-ReplaceWithRegister'.

**Comment by kiryph** [comment]
> All default operator keys [of this plugin] should start with `g`.

I see your point for consistency. But I do not think that they have to/should. The given operators do different things and hence do not need to have the same prefix which is the case for builtin operators and other plugins as well.

IMHO `gx` is already used by a very useful standard functionality which has its place in vim/neovim (as already said). So overwriting it is a problem for potential users.

Alternatives with `g` could be `g/` or `g!`   (`!` often means logical negation which one could associate with exchange).
However, I am not sure myself if they are interfering with other plugins.

> Apart from consistency, I don't like using keys that start with c, d, or y, because this would introduce a 'timeoutlen' inconvenience:

`c{motion}` requires always a second key. I do not think `cx` introduces a `timeoutlen` for `c`. I also do not like waiting for timeoutlen. I would not have suggested it otherwise.
https://skippi.medium.com/ideas-for-non-leader-vim-mappings-fd32a2769c87#ff57


---

I was mentioning the two plugins since they made the same default keybinding choice which supports the default choices of this plugin. In particular `gr` steps on a builtin mapping.

---

Finding good default keybindings for new plugins is always a struggle when trying to fit into the huge eco system of vim/neovim plugins. It is convenient for users (newbies or veterans alike) when popular plugins do not step onto each others toes. In particular, for newbies having good default keybindings means they do not assign them accidentally to builtin ones they do not know yet.

--- 

Anyhow the choice is up to you and it is already configurable. So a user can already change it.

Most importantly: thanks for your plugins, time to develop them and trying to [take user feedback into account](https://xkcd.com/1172/).

**Comment by kiryph** [comment]
>  But if there is a textobject starting with x (say, xi)

yes, someone has to introduce a two-or more letter text object starting with `x...` which I do not have heard of. Let me know when you encounter one. Otherwise I consider you/vim-exchange first.

Taking into account potential use cases makes a default choice even harder. `gx` clashes with existing/non-obscure mappings which is in my view a stronger argument than a potential use case.

**Comment by chrisgrieser** [comment]
In regard to similar plugins, there is also: https://github.com/smjonas/duplicate.nvim

which also leads me to a feature suggestion: duplicate.nvim does have an interesting feature, where you can provide a function which modifies the duplicated content. This can be used for "smart-duplication", e.g.:
- when duplicating a line in css, replace `margin-top` with `margin-bottom`
- when duplicating an if-condition in lua, replace `if` with `elseif`

**Comment by chrisgrieser** [comment]
An interesting option for the `evaluate` operator could be to have the output appear in a notification message (`vim.notify`), instead of replacing the given text object.

**Comment by echasnovski** [comment]
> In regard to similar plugins, there is also: https://github.com/smjonas/duplicate.nvim
> 
> which also leads me to a feature suggestion: duplicate.nvim does have an interesting feature, where you can provide a function which modifies the duplicated content. This can be used for "smart-duplication", e.g.:
> 
>     * when duplicating a line in css, replace `margin-top` with `margin-bottom`
> 
>     * when duplicating an if-condition in lua, replace `if` with `elseif`

Yeah, I've seen this plugin. As it is not on 'awesome-neovim' list, I wasn't sure how stable it is.

About feature: it can be done by introducing `MiniOperators.config.multiply.func`. Sound interesting.

------

> An interesting option for the `evaluate` operator could be to have the output appear in a notification message (`vim.notify`), instead of replacing the given text object.

I don't see this as option per se, because it can be simulated with something like this:

```lua
operators.setup({
  evaluate = {
    func = function(content)
      -- Currently needed as `content` is modified, which it shouldn't
      local input_lines = vim.deepcopy(content.lines)
      local output = MiniOperators.default_evaluate_func(content)
      vim.notify(table.concat(output, '\n'), vim.log.levels.INFO, {})
      return input_lines
    end
  }
})
```

**Comment by echasnovski** [comment]
> which also leads me to a feature suggestion: duplicate.nvim does have an interesting feature, where you can provide a function which modifies the duplicated content. This can be used for "smart-duplication", e.g.:
> 
>     * when duplicating a line in css, replace `margin-top` with `margin-bottom`
> 
>     * when duplicating an if-condition in lua, replace `if` with `elseif`

@chrisgrieser, in latest `main` there is now `config.multiply.func` which can be used for this kind of tasks. Won't be a part of 'mini.operators' itself, though, as this is too language-specific.

**Comment by chrisgrieser** [comment]
thanks a lot, works like a charm!

> Won't be a part of 'mini.operators' itself, though, as this is too language-specific.

yes, that's totally fine, since I guess duplication preferences should be pretty subjective.  Just having a function (or rather multiple language specific ones) to slot in is already great. Especially in languages like css, this is incredibly useful.

**Comment by farzadmf** [comment]
I seem to have issues with the sorting mechanism.

Let's say I have something like this:
```
hello = (
    one,
    two,
    three,
    four,
    five,
)
```
I'm gonna put screenshots so that I can talk about the line numbers, so it appears like this:
![image](https://github.com/echasnovski/mini.nvim/assets/5768792/c4262b74-1b99-44ff-b089-73402a727eb2)

If I go to line `2` and do `gs4j`, it's correctly sorted to:
![image](https://github.com/echasnovski/mini.nvim/assets/5768792/6d1ae212-90b8-4899-92e3-5f7098071f10)

But, if I go to any line inside the brackets, say, line `4` (`three`) and try to do `i<bracket>`, I get unexpected results:
- Doing `gsi(` gives me this:
![image](https://github.com/echasnovski/mini.nvim/assets/5768792/982c8c58-4061-4bcd-b230-d0f15e218c05)
- And doing `gsi)` gives me this:
![image](https://github.com/echasnovski/mini.nvim/assets/5768792/84b16ef7-7bd0-45de-9a8f-c28e97f31cb6)

Is this the expected behavior?

**Comment by echasnovski** [comment]
> I seem to have issues with the sorting mechanism.
> ...
> Is this the expected behavior?

The short answer is yes.

The slightly longer answer is that sorting approach with default sort function [depends on submode](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-operators.txt#L433-L442): charwise, linewise, blockwise (see `:h charwise`, for example). When you do `gs4j`, it performs sort linewise (as is described in `:h j`), but when you do `gsi)`, it performs charwise. This means that it takes the region and:
- Converts it to single line. In the case of `gsi(` it is a `one,\n    two,\n    three,\n    four,\n    five,`.
- Splits by appropriate separator. In this case `,` (including whitespace). **Note** that there is a trailing comma resulting into empty string being a part which will be sorted.
- Sorts parts. This results into empty string being first.
- Combines parts with separators.
- Puts text back.

In the case of `gsi)` the region goes all the way to the parenthesis and is `\n    one,\n    two,\n    three,\n    four,\n    five,\n` and gets sorted again.

So the core issues here is that you use charwise selection which sorts parts after splitting **and** there is a trailing comma producing empty/blank parts which are sorted.

**Comment by farzadmf** [comment]
Thanks @echasnovski for the answer. Makes sense.

Couple of questions:
- Is there a way (through config) to be able to use `i(` (or `i)`) for sorting? Basically use them to do line sort.
- Is there a way to for the sort to ignore case? E.g., consider `A` and `a` to be the same and not treat `A < a`?

**Comment by echasnovski** [comment]
> * Is there a way (through config) to be able to use `i(` (or `i)`) for sorting? Basically use them to do line sort.

There is currently no way of doing that for "sort" specifically. What I would suggest doing instead is force linewise mode. Try either one: `Vgsi(` (linewise Visual) or `gsVi(` (forced operator-pending linewise). Note that using `i(` is crucial here (if you are using 'mini.ai'), as it selects ignoring inner whitespace; `i)` will select one or both outer lines and sort them as well.
 
> * Is there a way to for the sort to ignore case? E.g., consider `A` and `a` to be the same and not treat `A < a`?

Not with default sorting function. It is intentionally left not complicated [suggesting to use `:sort` for more complicated tasks](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-operators.txt#L445-L446). In your case it will be `Vi(` followed by `:sort i` and `<CR>`.

**Comment by farzadmf** [comment]
> It is intentionally left not complicated [suggesting to use `:sort` for more complicated tasks](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-operators.txt#L445-L446). In your case it will be `Vi(` followed by `:sort i` and `<CR>`.

Hey @echasnovski , can you please give me an example of how I can do this? I think maybe an example in the docs could be super useful as well.

**Comment by echasnovski** [comment]
> > It is intentionally left not complicated [suggesting to use `:sort` for more complicated tasks](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-operators.txt#L445-L446). In your case it will be `Vi(` followed by `:sort i` and `<CR>`.
> 
> Hey @echasnovski , can you please give me an example of how I can do this? I think maybe an example in the docs could be super useful as well.

I am not sure how I can expand on this. Assuming [you example](https://github.com/echasnovski/mini.nvim/issues/439#issuecomment-1686857382):
- Place cursor on either line from 1 to 5.
- Type `Vi(`. This should visually select lines 1 through 5.
- Press `:`. This will start Command mode with `:'<,'>` being displayed in Command line.
- Type `sort i` and press `<CR>` (`<Enter>`). This will result into previously selected lines being sorted ignoring case.

For more information see `:h :sort`.

**Comment by farzadmf** [comment]
Ahhhh right @echasnovski , I know how to do it "manually" 😛. I was hoping to configure `mini.operators` to basically use the case-insensitive `:sort` by default

**Comment by echasnovski** [comment]
> Ahhhh right @echasnovski , I know how to do it "manually" 😛. I was hoping to configure `mini.operators` to basically use the case-insensitive `:sort` by default

Ah, I see. There is no easy general way which I can think about. `config.sort.func` takes selected content (basically, [lines and submode](https://github.com/echasnovski/mini.nvim/blob/06bf1784d88b112de14ce29aa604e2ae3fe1e359/doc/mini-operators.txt#L223-L226)) as input. You can go two routes:
- Sort `content.lines` manually ignoring case, either always or when `content.submode` is equal to `'V'` (i.e. linewise). Here is one way to do it (sorts ignoring case always):

```lua
local sort_func = function(content)
  local lines_extended = vim.tbl_map(function(l) return { l, vim.fn.tolower(l) } end, content.lines)
  table.sort(lines_extended, function(a, b) return a[2] < b[2] end)
  return vim.tbl_map(function(x) return x[1] end, lines_extended)
end
require('mini.operators').setup({ sort = { func = sort_func } })
```
- Create temporary buffer, put content lines there, apply `:sort` with necessary flags, get lines, delete buffer.

I personally would recommend resorting for manual `:sort`.

**Comment by farzadmf** [comment]
Thank you @echasnovski , the function seems to be working fine for my use case

**Comment by echasnovski** [comment]
With the release of 0.10.0, 'mini.operators' is now out of beta-testing. Huge thanks to everyone for constructive feedback and participation!
