### ISSUE TITLE
mini.nvim plugin causes issue in loading bufferline.nvim

### ISSUE THREAD

**Issue by zim0369** [echasnovski/mini.nvim#44]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.nvim

### Description

I commented out mini.tabline and configured bufferline-nvim but bufferline-nvim wouldn't start until I comment out the entire configuration for mini.nvim in init.lua

### Neovim version

0.6.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Install mini.nvim 
3. Install bufferline-nvim
4. Try loading bufferline-nvim with mini.nvim

### Expected behavior

bufferline-nvim should load fine

### Actual behavior

-

**Comment by echasnovski** [comment]
I can't reproduce. Installed 'akinsho/bufferline.nvim', replaced `require('mini.tabline').setup()` with `require('bufferline').setup({})` and everything works. Maybe the issue with your setup? Like lazy loading, etc. Could you track this down to a minimal 'init.lua'?

**Comment by zim0369** [comment]
I have been able to track it down. Issue occurs when mini.starter is enabled.

**Comment by echasnovski** [comment]
Do you mean that bufferline is not shown inside Starter buffer or it is not shown after it also? The first one is intended behavior (don't show tabline when Starter buffer is open). The second one I also can not reproduce: after Starter buffer is closed, bufferline appears.

**Comment by echasnovski** [comment]
I finally was able to reproduce, so thanks for this interesting find! It seems like you didn't explicitly set `showtabline` option to 2 (meaning "show always"), which I, for some weird reason, assumed anyone would do :) Instead, 'bufferline.nvim' sets it for you, which happens during Starter buffer being opened. I updated logic and tested, which seemed to work. Could you, please, test with latest `main` branch?

**Comment by zim0369** [comment]
> I finally was able to reproduce, so thanks for this interesting find! It seems like you didn't explicitly set `showtabline` option to 2 (meaning "show always"), which I, for some weird reason, assumed anyone would do :) Instead, 'bufferline.nvim' sets it for you, which happens during Starter buffer being opened. I updated logic and tested, which seemed to work. Could you, please, test with latest `main` branch?

I updated everything but for some reason I still face the same issue where commenting out
```
require("mini.starter").setup()
```
prevents bufferline from starting.

**Comment by echasnovski** [comment]
Ok, let's try debugging further.

First, just to be sure, could you please check that you indeed using the latest `main` branch? The best way to do this is to look at the code of 'mini.starter' module (should be in 'lua/mini/starter.lua' subdirectory of where 'mini.nvim' plugin is installed) and see that [these lines](https://github.com/echasnovski/mini.nvim/blob/6cb7cdb1cd7f111784d5d971fa41a655e11df4b3/lua/mini/starter.lua#L1209-L1213) are present.

If it is indeed latest, could you please set explicitly `vim.o.showtabline = 2` before calling `require('mini.starter').setup()` and see if it fixes this issue.

**Comment by zim0369** [comment]
> Ok, let's try debugging further.
> 
> First, just to be sure, could you please check that you indeed using the latest `main` branch? The best way to do this is to look at the code of 'mini.starter' module (should be in 'lua/mini/starter.lua' subdirectory of where 'mini.nvim' plugin is installed) and see that [these lines](https://github.com/echasnovski/mini.nvim/blob/6cb7cdb1cd7f111784d5d971fa41a655e11df4b3/lua/mini/starter.lua#L1209-L1213) are present.
> 
> If it is indeed latest, could you please set explicitly `vim.o.showtabline = 2` before calling `require('mini.starter').setup()` and see if it fixes this issue.

I'm very sorrry. I was using the stable branch. The problem is fixed. Thankyou!

**Comment by echasnovski** [comment]
Not a problem. You are not the first one and, probably, not the last:)
