### ISSUE TITLE
[mini.test] don't run a test case if there are errors in pre_case

### ISSUE THREAD

**Issue by stasjok** [echasnovski/mini.nvim#440]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.test

### Description

I usually use `pre_case` when I need to set up environment for a test case. It can be something a test can't run without (or it can even be dangerous to run it in incomplete environment, if it involves working with a filesystem for example). `mini.test` right now executes test case itself regardless if any errors was in `pre_case`. It's probably debatable, but I think this is wrong. For example in plenary `it` won't be executed in case of errors in `before_each`.

I realize that it probably won't be changed because it's backward incompatible, but maybe an option similar to `stop_on_error` (but only for `pre_case`) can be introduced?

**Comment by echasnovski** [comment]
Thanks for suggestion!

I vaguely remember thinking about this during development and something stopped me from doing this. Probably an implementation difficulty while difference in design is not huge.

I'll look into it.

**Comment by echasnovski** [comment]
After several time of back-and-forth on this, I decided to make a breaking change to indeed not call test case if there was at least one error in "pre" hooks. All "post" hooks will still be executed, though.

Thanks for your interest in 'mini.test'!
