### ISSUE TITLE
(mini.ai) Config option for operators allowed to be used in empty regions

### ISSUE THREAD

**Issue by TheLeoP** [echasnovski/mini.nvim#441]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai, mini.operators

### Description

Mini.ai currently has a [hardcoded check](https://github.com/echasnovski/mini.nvim/blob/801627023acf3c41293ac321a43de009076ba037/lua/mini/ai.lua#L991C1-L992C1) to allow `d` and `c` to be used in an empty region.

Other operators (like `gr` from mini.operators) also make sense to be used in an emtpy region, so it would be nice to be able to have a configuration option for this.

**Comment by echasnovski** [comment]
Thanks for suggestion!

This certainly won't be a configurable option. Will take a look at the best way to widen the accepted cases for empty regions.

**Comment by echasnovski** [comment]
I didn't opt-in for new config setting, but instead decided to specifically hand pick "replace" from 'mini.operators' to allow acting on empty region.

The reason for this decision is slightly technical. Basically, Neovim doesn't really allow empty selections. But as it is useful to do `ci)`/`di)`/`gri)` for empty brackets, there is a [hack](https://github.com/echasnovski/mini.nvim/blob/f32ac0a2a47298b768b6041fba30eeaabec338ba/lua/mini/ai.lua#L1018-L1026) which convert empty selection into one space selection. This means that only operators guaranteed to not essentially use selection can be acted on empty selection. From built-in those are `c` and `d` (although they do cut that text in default register). "Replace" from 'mini.operators' is another example. I don't think there is something else worth adding to this hand picked "allow list".

All that said, thanks again for suggestion! Being able to `gri)` for empty brackets is indeed quite useful.
