### ISSUE TITLE
[mini.indentscope] don't draw symbols on folded line

### ISSUE THREAD

**Issue by strash** [echasnovski/mini.nvim#444]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

<img width="152" alt="Screenshot 2023-08-19 at 01 59 30" src="https://github.com/echasnovski/mini.nvim/assets/14233263/ee3ab509-449c-42f8-a0a8-c700123e9b28">

<img width="219" alt="Screenshot 2023-08-19 at 02 06 10" src="https://github.com/echasnovski/mini.nvim/assets/14233263/3c8c0a5a-b628-42bf-8b31-506b64568cf2">

### Neovim version

0.9.1

### Steps to reproduce

1. create a fold
2. watch symbols cross the line

### Actual behavior

I think it is a bug.

**Comment by echasnovski** [comment]
Not a bug. This allows to draw a continuous line without empty spots. Plus checking if line is folded would add computation complexity.
