### ISSUE TITLE
[mini.indentscope]: cursor placed at wrong location during visual selection inside object scope

### ISSUE THREAD

**Issue by Subjective** [echasnovski/mini.nvim#445]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Indentscope

### Description

This is purely aesthetic, but when visually selecting "inside" an object scope text object, the cursor is placed at the first non-whitespace character of the last line instead of at the end of the overal selection. Selecting "around" any object scope places the cursor at the end, so it seems inconsistent for selecting "inside" to not behave the same, especially since every other text object I know of places the cursor at the end of the visual selection.

### Neovim version

NVIM v0.10.0-dev-886+gb263c73b0

### Steps to reproduce

1. Place the cursor within an object scope
2. Hit `vio` to visually select "inside" the object scope

### Expected behavior

I would expect the cursor to be placed at the end of the selection.

### Actual behavior

The cursor is placed at the first non-whitespace character of the last line of the selection.

<img width="803" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/56745535/192e1fea-1dd3-4a10-af34-acbd642cea2a">

**Comment by echasnovski** [comment]
Thanks for the issue!

I can't fully reproduce the issue:
- Yes, executing `vii` (with 'mini.indentscope' default config) does put cursor on the first non-blank character of the last line.
- No, executing `vai` also puts cursor on the first non-blank character of the last line.

So I don't see this as an inconsistency issue within 'mini.indentscope'.

Furthermore:
- Yes, built-in textobjects do seem to place cursor at the end of textobject when visually selecting. **But** this accounts for selection type: charwise, linewise, blockwise. If you use built-in charwise object (like `vi)`), then it will place cursor at the last character. If you use built-in linewise (like `vip`), then it will place on the first column of the last line.
- No, not all textobjects put cursor at the end of textobject during selection. 'mini.ai' made a conscious decision to put cursor at the start of the object to be more aligned with how cursor is treated after applying operator on textobject/motion (see second paragraph of `:h operator-doubled`).

Having this in mind, I'll revisit it later to possibly update to be more align with 'mini.ai' design.
