### ISSUE TITLE
[Mini.map] I can´t make this work. What am I missing?

### ISSUE THREAD

**Issue by vinoff** [echasnovski/mini.nvim#449]
I am using neovim:

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

and I am trying to install mini-map. This is my config with lazy.nvim:

```
return {
	"echasnovski/mini.map",
	version = false,
	lazy = false,
	config = function()
		require("mini.map").setup({
			-- Highlight integrations (none by default)
			integrations = nil,

			-- Symbols used to display data
			symbols = {
				-- Encode symbols. See `:h MiniMap.config` for specification and
				-- `:h MiniMap.gen_encode_symbols` for pre-built ones.
				-- Default: solid blocks with 3x2 resolution.
				encode = nil,

				-- Scrollbar parts for view and line. Use empty string to disable any.
				scroll_line = "█",
				scroll_view = "┃",
			},

			-- Window options
			window = {
				-- Whether window is focusable in normal way (with `wincmd` or mouse)
				focusable = false,

				-- Side to stick ('left' or 'right')
				side = "right",

				-- Whether to show count of multiple integration highlights
				show_integration_count = true,

				-- Total width
				width = 10,

				-- Value of 'winblend' option
				winblend = 25,
			},
		})
	end,
}
```

It seems to install correctly, no errors whatsoever. I do have the help pages for mini. However, I can´t make mini-map work. It doesn´t show up, nor do I have the MiniMap options in the command prompt. Am I missing something?

**Comment by echasnovski** [comment]
This module doesn't open map by default and [doesn't create mappings for it](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-map.txt#L143).

Does executing `:lua MiniMap.open()` solves the issue?

**Comment by vinoff** [comment]
> This module doesn't open map by default and [doesn't create mappings for it](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-map.txt#L143).
> 
> Does executing `:lua MiniMap.open()` solves the issue?

Ahhhh.. Yes, it does. Thank you. I will figure a way to open this by default then. Thank you!

**Comment by echasnovski** [comment]
> > This module doesn't open map by default and [doesn't create mappings for it](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-map.txt#L143).
> > Does executing `:lua MiniMap.open()` solves the issue?
> 
> Ahhhh.. Yes, it does. Thank you. I will figure a way to open this by default then. Thank you!

With reasonably structured config you can probably add `MiniMap.open()` line just after `require('mini.map').setup()`.

**Comment by vinoff** [comment]
> > > This module doesn't open map by default and [doesn't create mappings for it](https://github.com/echasnovski/mini.nvim/blob/ab94192dd36b35c6752aac7154c7130922c27af7/doc/mini-map.txt#L143).
> > > Does executing `:lua MiniMap.open()` solves the issue?
> > 
> > 
> > Ahhhh.. Yes, it does. Thank you. I will figure a way to open this by default then. Thank you!
> 
> With reasonably structured config you can probably add `MiniMap.open()` line just after `require('mini.map').setup()`.

Yes, that works.. The issue now is that, since I am using nvim-tree and I like Nvim-tree to automatically close when I close the last buffer.. that no longer works with the mini-map opened. Any suggestion or recipe for this case? Have mini-map close when I close the file?

**Comment by echasnovski** [comment]
> Yes, that works.. The issue now is that, since I am using nvim-tree and I like Nvim-tree to automatically close when I close the last buffer.. that no longer works with the mini-map opened. Any suggestion or recipe for this case? Have mini-map close when I close the file?

I don't quite remember how this is implemented in 'nvim-tree' (or maybe you are using the custom solution). 'mini.map' creates a scratch buffer which I'd argue shouldn't be taken into account when implementing "close when no buffer left" functionality. I'd suggest either update logic of when 'nvim-tree' is closed or close map as a substitute of "close the last buffer".

**Comment by vinoff** [comment]
Ya, the nvim-tree solution is quite hacky..
```

		-- Close nvim-tree if last buffer in tab is closed
		local function tab_win_closed(winnr)
			local api = require("nvim-tree.api")
			local tabnr = vim.api.nvim_win_get_tabpage(winnr)
			local bufnr = vim.api.nvim_win_get_buf(winnr)
			local buf_info = vim.fn.getbufinfo(bufnr)[1]
			local tab_wins = vim.tbl_filter(function(w)
				return w ~= winnr
			end, vim.api.nvim_tabpage_list_wins(tabnr))
			local tab_bufs = vim.tbl_map(vim.api.nvim_win_get_buf, tab_wins)
			if buf_info.name:match(".*NvimTree_%d*$") then -- close buffer was nvim tree
				-- Close all nvim tree on :q
				if not vim.tbl_isempty(tab_bufs) then -- and was not the last window (not closed automatically by code below)
					api.tree.close()
				end
			else -- else closed buffer was normal buffer
				if #tab_bufs == 1 then -- if there is only 1 buffer left in the tab
					local last_buf_info = vim.fn.getbufinfo(tab_bufs[1])[1]
					if last_buf_info.name:match(".*NvimTree_%d*$") then -- and that buffer is nvim tree
						vim.schedule(function()
							if #vim.api.nvim_list_wins() == 1 then -- if its the last buffer in vim
								vim.cmd("quit") -- then close all of vim
							else -- else there are more tabs open
								vim.api.nvim_win_close(tab_wins[1], true) -- then close only the tab
							end
						end)
					end
				end
			end
		end

		vim.api.nvim_create_autocmd("WinClosed", {
			callback = function()
				local winnr = tonumber(vim.fn.expand("<amatch>"))
				vim.schedule_wrap(tab_win_closed(winnr))
			end,
			nested = true,
		})

```
