### ISSUE TITLE
Allow custom sorting in clue window

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#454]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Think about the best way to allow custom sorting of clue window content.

**Comment by abeldekat** [comment]
Hello @echasnovski,

Thanks for creating this feature-request!

I think the current alphabetic sorting is just fine. However, group-items("git", "search") are in the same sorted list as items that directly execute an action("Harpoon UI") .

In LazyVim, when pressing the leader key, items that directly execute an action are added first, sorted alphabetically. Then, the group items are added, also sorted alphabetically.
For me personally, those two "virtual" blocks are easier to scan, as the most important keys will be on top.

Best regards!

**Comment by echasnovski** [comment]
> I think the current alphabetic sorting is just fine. However, group-items("git", "search") are in the same sorted list as items that directly execute an action("Harpoon UI") .
> 
> In LazyVim, when pressing the leader key, items that directly execute an action are added first, sorted alphabetically. Then, the group items are added, also sorted alphabetically. For me personally, those two "virtual" blocks are easier to scan, as the most important keys will be on top.

To me direct alphabetic sorting adds the smallest amount of mental overhead when trying to read clue window content. As groups and non-groups have different highlighting, this seems to be the best compromise here.

*But*, in order to achieve the sorting you describe (a valid one, I agree), there also needs to be information about that passed into custom sorter function. So not only `key` and `description` fields, but also `is_group` and, possibly, `has_postkeys`. This makes it more complicated, though :(

**Comment by echasnovski** [comment]
After debating this for a while, I don't see that benefits here outweigh increase in complexity (not only implementation, but also documentation of proper API and testing). Sorry @abeldekat.

Closing as not planned.

**Comment by abeldekat** [comment]
I understand. Thanks for the consideration!

**Comment by abeldekat** [comment]
@echasnovski,

After using the plugin for a while, I am glad you decided not to implement the request. 

>To me direct alphabetic sorting adds the smallest amount of mental overhead when trying to read clue window content. As groups and non-groups have different highlighting, this seems to be the best compromise here.

Thanks for the plugin!
