### ISSUE TITLE
`mini.animate`: `MiniAnimateNormalFloat` not working

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#461]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

I can't get `MiniAnimateNormalFloat` hlg to be respected

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:vsp`

`minimal.lua`:

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        "echasnovski/mini.animate",
        version = "*",
        config = function()
            local animate = require("mini.animate")
            animate.setup {
                open = {
                    timing = animate.gen_timing.linear({ duration = 2000, unit = 'total' }),
                    winconfig = animate.gen_winconfig.wipe({ direction = 'from_edge' }),
                    winblend = animate.gen_winblend.linear({ from = 0, to = 100 }),
                },
                close = {
                    timing = animate.gen_timing.linear({ duration = 2000, unit = 'total' }),
                    winconfig = animate.gen_winconfig.wipe({ direction = 'to_edge' }),
                    winblend = animate.gen_winblend.linear({ from = 100, to = 0 }),
                },
            }
        end
    },
}

require("lazy").setup(plugins, {
root = root .. "/plugins",
})

vim.o.termguicolors = true

vim.cmd[[hi MiniAnimateNormalFloat guibg=green]]
```

### Expected behavior

I would expect the highlight group to be respected.

It works, when I set `NormalFloat`, but I can't do this because it is used by many other floating windows.

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/16707112/624e2a66-b351-49f6-9982-a63cf05ed748

**Comment by echasnovski** [comment]
`MiniAnimateNormalFloat` highlight group is not a part of current version release (0.9.0), which this example installs (because of `version = "*"`). It is a [part of current `main` branch](https://github.com/echasnovski/mini.nvim/blob/main/CHANGELOG.md#minianimate) and will be a part of 0.10.0 release.

Changing to `version = false`, updating plugins, and restarting Neovim should work as expected.

**Comment by simonmandlik** [comment]
Oh, should have noticed, sorry about that! 🫣
