### ISSUE TITLE
[mini.comment] textobject not working

### ISSUE THREAD

**Issue by luiz00martins** [echasnovski/mini.nvim#463]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

The comment textobj mapping does not work, despite the mapping being correctly created.

### Neovim version

NVIM v0.10.0-dev-979+g794981d9b

### Steps to reproduce

Configuration used:
```
	config = function()
		require('mini.comment').setup {
			mappings = {
				comment = ';;',
				comment_line = ';;',
				textobject = ';',
			},
		}
	end
```

Output of `omap`:
```
o  ;           * <Cmd>lua MiniComment.textobject()<CR>
```

### Actual behavior

Using <kbd>;</kbd><kbd>;</kbd> in normal/visual mode works, but <kbd>c</kbd><kbd>i</kbd><kbd>;</kbd>, for example, fails.

**Comment by echasnovski** [comment]
I've tested this config and it works as expected. You supplied a `;` as textobject, not `i;`. Try using `c;` instead of `ci;`.
