### ISSUE TITLE
inconsistency of removing html tags 

### ISSUE THREAD

**Issue by mortezadadgar** [echasnovski/mini.nvim#464]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

reporting another bug which is kinda related to reproducible steps as well:
`tpope/vim-surround` removes whitespaces in place of tag and fix indentation of html tags
tpope: 
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/9f8d0782-43d8-4c06-953e-18538f58f9a8)
mini.surround:
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/bffca64b-e48f-4039-9e0e-e9823843d4de)

### Neovim version

0.9.1

### Steps to reproduce

1. open this html file: https://bpa.st/PTHQY
2. move cursor to line `<main>` and tries to remove tag using `sdt`
3. No surrounding 't' found within 20 lines and config.search_moethod = 'cover'

### Expected behavior

expected to remove `<main>` which is on the same line of cursor

### Actual behavior

produce errors

**Comment by echasnovski** [comment]
> expected to remove `<main>` which is on the same line of cursor

Although, `<main>` is on the same line, `</main>` is further than 20 lines. If you don't want to restrict how far 'mini.surround' searches for the surrounding, set [`config.n_lines`](https://github.com/echasnovski/mini.nvim/blob/3a3e19d7b7850e711485b8adde73ba44789f2cf6/doc/mini-surround.txt#L476-L477) to some big value (like 10000000).

Closing as this works as expected.

**Comment by mortezadadgar** [comment]
@echasnovski thanks for quick response, what do you think about the bug (or issue) described in description?

**Comment by echasnovski** [comment]
> @echasnovski thanks for quick response, what do you think about the bug (or issue) described in description?

Not really sure I 100% understand it. What I can say is that by default 'mini.surround' deletes *only* what it considers to be left and right surroundings, nothing more. If you want an extended behavior which affect indentation, try setting [`config.respect_selection_type`](https://github.com/echasnovski/mini.nvim/blob/3a3e19d7b7850e711485b8adde73ba44789f2cf6/doc/mini-surround.txt#L482) to `true`. It might work for your use case.
