### ISSUE TITLE
`nvim-treesitter-context` window closes when the `mini-clue` window opens

### ISSUE THREAD

**Issue by MariaSolOs** [echasnovski/mini.nvim#467]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

_Taken from the [beta issue](https://github.com/echasnovski/mini.nvim/issues/430#issuecomment-1703956093)._

When using this plugin together with [`nvim-treesitter-context`](https://github.com/nvim-treesitter/nvim-treesitter-context), the context window disappears when `mini.clue` opens:

https://github.com/echasnovski/mini.nvim/assets/62502207/66a54424-6ccf-47db-87f2-2ec43e5bc218

### Neovim version

v0.10.0-dev-1031+gc431d820e

### Steps to reproduce

1. Install both `mini.clue` and [`nvim-treesitter-context`](https://github.com/nvim-treesitter/nvim-treesitter-context).
2. Use the default settings for both plugins.
3. Navigate to a position in a file of your choice that causes the window from `nvim-treesitter-context` to be opened. Type the leader key so that `mini.clue` opens.

### Expected behavior

The window from `nvim-treesitter-context` remains opened.

### Actual behavior

The window from `nvim-treesitter-context` is closed.

As further context, this doesn't happen with `which-key` or `nvim-cmp`, since they both use `noautocmd` in their window options: https://github.com/folke/which-key.nvim/blob/7ccf476ebe0445a741b64e36c78a682c1c6118b7/lua/which-key/view.lua#L70, https://github.com/hrsh7th/nvim-cmp/blob/5dce1b778b85c717f6614e3f4da45e9f19f54435/lua/cmp/utils/window.lua#L124.

Moreover, adding `win_config.noautocmd = true` below line 1523 in this code fixes the issue.
https://github.com/echasnovski/mini.nvim/blob/3a3e19d7b7850e711485b8adde73ba44789f2cf6/lua/mini/clue.lua#L1521-L1526

**Comment by echasnovski** [comment]
Thanks for creating this!

I will get back to it at my next round of backlog cleaning.

**Comment by echasnovski** [comment]
Should be fixed in latest `main` using your suggested fix. Thanks!

**Comment by MariaSolOs** [comment]
@echasnovski amazing, thanks a lot!
