### ISSUE TITLE
Missing syntax highlighting when using mini.files plugin with preview window enabled?

### ISSUE THREAD

**Issue by OnigiriByte** [echasnovski/mini.nvim#469]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When I open a .tsx file  with the mini.files plugin having the preview window option enabled and open the file, I notice that there is missing syntax highlighting and the comment plugin behaves differently than configured. However, when I disable the preview option, the file opens normally, and the syntax highlighting + commenting works as expected.

Not sure if this is actually a mini.files issue or a treesitter plugin issue, but its behavior is unexpected for me considering it behaves as I expect it to with the preview option disabled.

I also don't encounter this issue when using telescope (find files) or oil.nvim which also have preview features.

### Neovim version

NVIM v0.9.1

### Steps to reproduce

1. Open React + Typescript project with neovim. `nvim -nu minimal.lua .` 
2. (mini.files opens) Navigate to a `.tsx` component within a `src/` directory. This should cause a preview window to pop up, showing the hovered file.
3. Open the file with by pressing the `l` key
4. Observe missing/different highlighting than when the preview option is disabled.

<details>

<summary>minimal.lua</summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
	"git",
	"clone",
	"--filter=blob:none",
	"https://github.com/folke/lazy.nvim.git",
	"--branch=stable", -- latest stable release
	lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)



require('lazy').setup({


    {
	'nvim-treesitter/nvim-treesitter',

	dependencies = {
	    'JoosepAlviste/nvim-ts-context-commentstring',
	},

	opts = {

	    ensure_installed = { 'typescript', 'tsx', 'javascript', 'html', 'css' },

	        context_commentstring = {
		 enable = true,
		 enable_autocmd = false
		    },
		highlight = {
		    enable = true
		}
	    },
	    main = "nvim-treesitter.configs"
	},



	{
	    'echasnovski/mini.comment',
	    version = '*',
	    opts = {
		options = {
		    -- use integration with nvim-ts-context-commentstring
		    custom_commentstring = function()
			return require('ts_context_commentstring.internal').calculate_commentstring() or vim.bo.commentstring
		    end,
		},
	    }

	},


	{
	    'echasnovski/mini.files',
	    version = false,

	    opts = {
		windows = {
		    -- NOTE:
		    -- Syntax highlighting is different in .tsx files when file is opened via the plugin and the preview option is enabled.
		    -- Also the comments revert back to default comment behavior instead of using the treesitter context aware comments.
		    preview = true,
		    width_focus = 30,
		    width_preview = 30,
		},
		options = {
		    use_as_default_explorer = true,
		}
	    },

	    lazy = false,

	    keys = {
		{
		    "<Leader>e",
		    function()
			print("Minus command ran!")
			require('mini.files').open(vim.loop.cwd(), true)
		    end,
		    desc = "Open mini.files at cwd"
		},
		{
		    "-",
		    function()
			require('mini.files').open(vim.api.nvim_buf_get_name(0), true)
		    end,
		    desc = "Open mini.files at current buf dir."
		},
	    },



	},


	-- No issues, when opening a file after using the "actions.preview" action


	-- {
	    --   'stevearc/oil.nvim',
	    --   lazy = false,
	    --   keys = {
		-- 	  {"-", "<CMD>Oil<CR>", desc = "Open parent directory"},
		--   },
		--   opts = {},
		--   -- Optional dependencies
		--   dependencies = { "nvim-tree/nvim-web-devicons" },
		-- }





	    })

```
</details

### Expected behavior

I expect the behavior to be consistent with the behavior when the preview option is disabled. When the preview window is enabled, the syntax highlighting should work and be detected properly.

### Actual behavior

When the preview window is enabled, the syntax highlighting is missing for .tsx files. However, when the preview option is disabled, the syntax highlighting works as expected.

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I *think* I can reproduce this. Will investigate what is causing this.

**Comment by echasnovski** [comment]
This should be now fixed on latest `main`.

The reason seemed to be that 'mini.files' was trying to highlight lines from that file (almost unrelated to the future buffer, by the way) using `vim.treesitter.start()` with "language" `typescriptreact` (which is what the correct `filetype` option) instead of `tsx` (which is the correct "language").

With this fix highlighting and commenting seem to be tree-sitter aware. Could you, please, test it on your side and tell if it also works for you? Thanks!
