### ISSUE TITLE
Module proposition: test suite

### ISSUE THREAD

**Issue by danymat** [echasnovski/mini.nvim#47]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Test module

### Description

Hello ! I would love mini.nvim to provide a mini implementation of a plugin test suite, for Lua plugins. 
Currently, I use plenary test suite, and I think this could be improved. 
What do you think ?

**Comment by echasnovski** [comment]
Oh, Daniel... This is a very, **very** big pain point for me right now. At the moment I am trying to force myself into writing at least basic tests for all of my modules. For some reason, I don't really like the current state of testing capabilities in "Neovim Lua Plugin" area. Can't quite grasp the exact thing here though (something along the lines of "no single *straightforward* way" and "unnecessarily complex").

Well, that said, I am very close to accepting that 'plenary.test_harness' is as close as it might get to simplifying the process while getting reasonably wide range of capabilities.

Also, I am very open to creating 'mini.testing' and would really like to hear your thoughts on what it should look like to be useful for you.

**Comment by danymat** [comment]
Yeah, I find it somehow bizarre, I don't quite get it.
Currently, I use the busted api that plenary provides.

I started to learn rust, and I liked the way rust finds test functions: https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html

Having this feature is somehow simpler that a whole test suite:
- Just find an annotation (like `---@test Test name`) before a function
- Provide some asserts, like assert equals, assert assert not equals
- Create a mini.test function (like mini.doc scoping mechanism) to find all test functions, and run them

**Comment by echasnovski** [comment]
Ok, so is this more for "find and run" tests and not for writing them? Because there are at least these questions:
- What is "run test file"? In which Neovim instance, under what environment, with what dependencies?
- Having `before_each` and `after_each`, as well as mocks and stubs seems to be really useful. Should they also be a part of a possible module?
- Should this also implement functionality for providing feedback about which tests failed and for what reason?

**Comment by echasnovski** [comment]
Hey, Daniel. Don't if it is still in demand, but I just pushed a 'mini.test' - module for testing Neovim plugins. All 'mini.nvim' modules are now using it. Check it out.
