### ISSUE TITLE
Allow usage of mini.clue of specified kind of non listed buffers

### ISSUE THREAD

**Issue by hbiel** [echasnovski/mini.nvim#471]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

As i understand it mini.clue currently only acts on listed buffers as no mapings are created in non-listed buffers.

I would love to use the submode feature especially for the window management functionality (e.g. resize, navigate).
For example i would like to be able to use those from within neotree- or diffview-buffers.

Would this be possible to achieve?

**Comment by echasnovski** [comment]
> I would love to use the submode feature especially for the window management functionality (e.g. resize, navigate). For example i would like to be able to use those from within neotree- or diffview-buffers.
> 
> Would this be possible to achieve?

Yes, this is possible by manually calling `enable_buf_triggers` for target buffers.

Here is an example of automatically doing this for `help` buffers:
```lua
local clue_group = vim.api.nvim_create_augroup('my-miniclue', { clear = true })
vim.api.nvim_create_autocmd('FileType', {
  pattern = 'help',
  group = clue_group,
  callback = function(data) MiniClue.enable_buf_triggers(data.buf) end,
})
```

**Comment by hbiel** [comment]
Oh, of course! Thanks for the quick hint!
