### ISSUE TITLE
Support activate.nvim setup.lua.example files

### ISSUE THREAD

**Issue by roobert** [echasnovski/mini.nvim#473]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

All modules

### Description

Hi Evgeni,

I've just released a new plugin called `activate.nvim`, it's a plugin installation system for Neovim: https://github.com/roobert/activate.nvim

I was wondering whether you'd be interested in supporting the idea of an unofficial format for `setup.lua.example` files. I think this could help lower the barrier to entry for many people looking to try Neovim and its various plugins.

If you're interested in this idea, I would be happy to open PRs for your various plugins.

If you'd like to discuss/refine the idea further, you can email me (my github username @gmail.com) or continue this thread.

Kind regards

Rob

**Comment by echasnovski** [comment]
Hi!

That is an interesting plugin, thanks for sharing!

I'd rather not create these files right away, but it is not a "no" indefinitely. I have a couple of thoughts on this, though:
- 'folke/lazy.nvim' already handles `setup()` calls for 'mini.nvim' standalone repositories automatically. There are a couple of modules that require some explicit user configuration for them to be useful ('mini.base16', 'mini.hipatterns'), but the whole point is to have user decide what they want.
    So the only reason I see now for adding 'setup.lua.example' file(s) is to automatically create a file in which users can write their config.
- I'd rather adhere to something like [neovim/packspec](https://github.com/neovim/packspec) if/when it gets properly released.

**Comment by roobert** [comment]
> * 'folke/lazy.nvim' already handles `setup()` calls for 'mini.nvim' standalone repositories automatically. There are a couple of modules that require some explicit user configuration for them to be useful ('mini.base16', 'mini.hipatterns'), but the whole point is to have user decide what they want.
>   So the only reason I see now for adding 'setup.lua.example' file(s) is to automatically create a file in which users can write their config.
> * I'd rather adhere to something like [neovim/packspec](https://github.com/neovim/packspec) if/when it gets properly released.

I agree in part that it may seem pretty pointless to create a setup file that just has something like: `return { "some/plugin" }` inside it. By default, if no `setup.lua.example` is detected, then `activate.nvim` creates a file with just that in. The problem here is that the user then has no real idea whether additional configuration is required without going to read the docs. Because of this, I have left the contents of the return block commented by default and provided a link to the plugin docs to encourage the user to investigate further. I think it would be nicer if even if no additional setup is required, the plugin can indicate that in some machine readable way.

I have been following packspec and when it gets released it'd be easy to support this, however, it doesn't seem to solve the default setup options problem which I think is one of the main barriers to entry for new and inexperienced (or just lazy!) users.

Do you think it'd be worth proposing that packspec includes some kind of optional default setup options block? If it's outside the scope of packspec, do you think this is a problem that is even worth trying to solve?

Thanks for your reply, and all the great plugins!

**Comment by echasnovski** [comment]
> The problem here is that the user then has no real idea whether additional configuration is required without going to read the docs.

My current opinion is that reading the docs is essential part of using Neovim and its ecosystem. Making it less painful for novice users and less needed for experienced users is a more preferable route for me.

> I have been following packspec and when it gets released it'd be easy to support this, however, it doesn't seem to solve the default setup options problem which I think is one of the main barriers to entry for new and inexperienced (or just lazy!) users.
> 
> Do you think it'd be worth proposing that packspec includes some kind of optional default setup options block? If it's outside the scope of packspec, do you think this is a problem that is even worth trying to solve?

I would agree that having "official" unified requirements on how to structure plugin is beneficial in long-term. However, witnessing countless lines spent on "autoload/plugin directory vs `setup()`" discussions, this will probably lead nowhere.

**Comment by roobert** [comment]
> My current opinion is that reading the docs is essential part of using Neovim and its ecosystem. Making it less painful for novice users and less needed for experienced users is a more preferable route for me.

I agree, but I think there is a balance between user experience and documentation. I think starting with a working default config for users makes sense, also, in an example config inline documentation can give enough information to the user to configure the plugin, in many cases.

> I would agree that having "official" unified requirements on how to structure plugin is beneficial in long-term. However, witnessing countless lines spent on "autoload/plugin directory vs `setup()`" discussions, this will probably lead nowhere.

I think this is probably why it's a good idea to start with something imperfect, evolve it, and try different conventions in the wild to see what survives and what people like, rather than waiting for the mythical perfect solution that everyone can agree on!

I really appreciate your insight and opinions!

**Comment by roobert** [comment]
I made a post on reddit about this, your insight I'm sure would be appreciated, I'll close this thread for now: https://www.reddit.com/r/neovim/comments/16e4y0f/introducing_activatenvim_a_neovim_plugin/
