### ISSUE TITLE
[mini.files] Command to open with a focus on a file of currently open buffer

### ISSUE THREAD

**Issue by bloznelis** [echasnovski/mini.nvim#475]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

The analogous functionality to nvim-tree's `NvimTreeFindFile`. Maybe it's possible already, but I could not find it.

**Comment by echasnovski** [comment]
Yes, [this is already possible](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/doc/mini-files.txt#L630-L631).
