### ISSUE TITLE
mini.bracketed: user-configurable [during initialization and runtime] shell prompt jumps (with sane default)

### ISSUE THREAD

**Issue by matu3ba** [echasnovski/mini.nvim#476]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bracketed

### Description

Shell prompt jumps are extremely frequent for and having a configurable way to jump between them would be very nice.
I do also miss them very much in zellij.

I dont understand the use cases of `[P [p, ]p, ]P` as they are doing the same for me as `p` and `P`:
```
["x]]p		    or					*]p* *]<MiddleMouse>*
["x]]<MiddleMouse>	Like "p", but adjust the indent to the current line.
			Using the mouse only works when 'mouse' contains 'n'
			or 'a'.

["x][P		    or					*[P*
["x]]P		    or					*]P*
["x][p		    or					*[p* *[<MiddleMouse>*
["x][<MiddleMouse>	Like "P", but adjust the indent to the current line.
			Using the mouse only works when 'mouse' contains 'n'
			or 'a'.
```
Maybe they are merely broken?

Alternatively, it would be nice to have a simple wiki for common and countable jump things.

**Comment by matu3ba** [comment]
Alternatively: Briefly describe the API/how to use jumps with and without adding to tag list to define own jumpers.
The vimscript way feels very hacky and unreadable.

**Comment by echasnovski** [comment]
> Maybe they are merely broken?

No, they are not. They do what they are describing: put text and adjust indent. Try yanking line without indent and then `:normal! ]p` inside a text with indent (and surrounded by text without indent). Probably, needs 'smartindent' or something similar.

> Shell prompt jumps are extremely frequent for and having a configurable way to jump between them would be very nice.
I do also miss them very much in zellij.

Could you please describe an example?

**Comment by matu3ba** [comment]
I'll post an example from work tomorrow.

**Comment by matu3ba** [comment]
So what I have at work is many shennanigans to workaround. As example, I need to use the shell to workaround different programs writing to stderr and stdout. However, unfortunately, for example Python buffers outputs unless in shell mode, so stuff to stdout comes after stderr or vice versa if I write it to a file.

Usually, I would use
```lua
-- repeat last command
-- r means repeat last command
map('n', ';rj', [[<cmd>lua require("harpoon.term").sendCommand(1, "!!\n")<CR>]], opts) -- r for repeat
```
after a bug fix to get the output and then ideally `[p` + `/<FAIL\>` to search from last prompt to see if a test failure occured, because the default output formatting of Python is unusable for parsing.

The prompt looks roughly like this and any other kind of line pattern jumping as lib sounds also useful to me:
```txt
lastname@domain.local@GROUP111 ~/directory (master)> ./repl.py -arg1 -tc testname_2.py
pid: blablabla
arg: -args1
arg: -tc
arg. testname_2.py
new file:   /tpm/directory/process1.log
new file:   /tpm/directory/process2.log

-------------------------------------------------------------
2023-09-12 14:21:31: ---- START ./setup.py ----

returncode:  0
name:  ./setup.py
result:  pass
2023-09-12 14:21:38: ---- END ./setup.py ----

-------------------------------------------------------------
2023-09-12 14:21:31: ---- START ./testname_2.py ----

..
sometimeline
2023-09-12 12:21:31.195306 Ipcmessage: data 2 1.000000
..

returncode:  0
name:  ./testname_2.py
result:  pass
2023-09-12 14:21:38: ---- END ./testname_2.py ----
lastname@domain.local@GROUP111 ~/directory (master)> 
```

Of course, ideally one would not need these hacks and ideally one would have languages with dense and machine+human readable file locations + stack traces usable by vim/neovim etc, which could additionally point into the shell history etc.
And yes, I know that the shell history is truncated and has no file backup for output etc, which is a shell antifeature.

**Comment by echasnovski** [comment]
I feel a bit dumb here as I still don't understand what `[p` should do. My best guess is that when it is inside terminal buffer, it should jump at the line describing start of previous shell output? If yes, then it is most certainly won't be a part of 'mini.bracketed' because it varies too much, i.e. doesn't really have more or less universally fixed rule to define "start of shell output".

'mini.bracketed' has general [`advance()`](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/doc/mini-bracketed.txt#L605) which is used in all targets. As an example for such behavior, take a look at [`conflict()` target](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/lua/mini/bracketed.lua#L362).

**Comment by matu3ba** [comment]
> If yes, then it is most certainly won't be a part of 'mini.bracketed' because it varies too much, i.e. doesn't really have more or less universally fixed rule to define "start of shell output".

Yes. Ok, thanks for the information. I'll close this and add some example configuration once implemented to this thread.

> 'mini.bracketed' has general [advance()](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/doc/mini-bracketed.txt#L605) which is used in all targets. As an example for such behavior, take a look at [conflict() target](https://github.com/echasnovski/mini.nvim/blob/f158f1905286e023d5848ab0b335a1cf5b8c692a/lua/mini/bracketed.lua#L362).

Ah, lol. Ok, thanks for the info.
