### ISSUE TITLE
[mini.completion]: only display signature help before start typing

### ISSUE THREAD

**Issue by saccarosium** [echasnovski/mini.nvim#478]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Hi,
The current behavior of the signature help is very annoying. Most of the time cover test I want to read and is very distracting. Having said that I wont get rid of it since can be useful. We could implement something that mimics the behavior of another plugin [nvim-lsp-completion](https://github.com/mfussenegger/nvim-lsp-compl).

Espected behavior:

https://github.com/echasnovski/mini.nvim/assets/96259932/bc309ab0-fd0d-4cb8-bcc3-dddf45b68140

**Comment by echasnovski** [comment]
Thanks for suggestion!

I don't think this is a good idea. Mostly because it would lead to signature help to hide and show on every typed parameter, which is a lot of unnecessary flicker.

Closing as not planned.

**Comment by saccarosium** [comment]
> I don't think this is a good idea. Mostly because it would lead to signature help to hide and show on every typed parameter, which is a lot of unnecessary flicker.

The behavior I'm describing is a little different. The signature help would show only at the beginning of the function call and we could make is showing customizable. I'll try to be more clear (`|` is the cursor):

```
local function sum(a, b)
  return a + b
end


    + - - - After typing '(' after a customizable delay
    |       should appear the signature help
    V
sum(|
   
      + - - - - After typing the first non whitespace letter 
      |         the signature help should disappear
    +-+-+
    |   |
    V   V
sum(2 , 3)|
```

This shouldn't impact normal typing. If you know the function you will type a non whitespace character before triggering the signature help. As I said the current behaviour I think is very distracting and that I consider unnecessary flicker. 

If you are open to the idea I can adventure with a PR and let you decide after trying it, if you like it or not.

**Comment by echasnovski** [comment]
Let's try this example with `local sum3 = function(a, b, c) return a + b +c end`, so that we are on the same page here.

Steps:
1. Type `sum3(`. Wait `delay.signature` milliseconds for signature window to appear.
2. Study signature help.
3. Type `1`. Signature help disappeared.
4. Type `,`. I would expect signature help to again appear (as it is a trigger character): immediately or again after `delay.signature`.
5. Type ` 2`. Signature help disappeared.
6. Type `,`. Again it should appear.
7. Type `3`. It should disappear.

It is extra two disappear/appear cycles with number growing linearly depending on number of arguments.

Is this what you have in mind?

**Comment by saccarosium** [comment]
No quite. What I've had in mind is:
1. Type `sum3(`. Wait `delay.signature` milliseconds for signature window to appear.
2. Study signature help.
3. Continue typing without any other dissapear/appear cycles.

I'm on the same page as you that having the signature help appear on every argument is annoying; but if we show it only at the begin of the function call, could be a nice middle ground between having it always there and disabled.

**Comment by echasnovski** [comment]
> No quite. What I've had in mind is:
> 
>     1. Type `sum3(`. Wait `delay.signature` milliseconds for signature window to appear.
> 
>     2. Study signature help.
> 
>     3. Continue typing without any other dissapear/appear cycles.
> 
> 
> I'm on the same page as you that having the signature help appear on every argument is annoying; but if we show it only at the begin of the function call, could be a nice middle ground between having it always there and disabled.

That is a definite "no" from me, sorry. Having signature help shown after at least trigger characters for signature help (which are usually `(` and `,`) is a must. More broadly: having it visible after ending input for current argument is a must.
