### ISSUE TITLE
[Mini.starter] issue with 'sh' files directly from the terminal - notification error

### ISSUE THREAD

**Issue by bassamsdata** [echasnovski/mini.nvim#479]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.starter

### Description

I'd like to report an issue with Mini.starter. When I attempt to open bash/zsh/sh formatted files directly using the `nvim .example` command, I encounter an error. The error message initially prompts me to "Press enter or type a command to continue." 

After pressing enter, I receive the following error: `(mini.starter) 'buf_id' in 'refresh()' is not a valid Starter buffer identifier.`

Please note that I observed a similar issue mentioned in #230, but the steps to reproduce it differ.

### Neovim version

0.9.2

### Steps to reproduce

1. create any hidden file without file ext like **(.zshrc / .bzshrc / .examplerc)**
2. copy this line to the file: `#!/bin/zsh` to tell it its sh format and write then close nvim.
3. run this command in terminal to open the file `nvim .examplerc`
4. the issue would appear

### Actual behavior

A notification is sent by mini.starter saying "buf_id in refresh() is not an identifier of valid Starter buffer". This does not occur with the any other file or if you open the file `.zshrc` after opening neovim.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce. Neither with '.examplerc' from the issue, nor from mine '.zshrc'. Also neither with Neovim 0.9.2, nor with current Nightly.

Could you try to reproduce this with only 'mini.starter'?

Also, do you happen to have any plugins installed affecting either startup or shell files (if this happens *only* for shell files)?

**Comment by bassamsdata** [comment]
Thank you for your quick response. I've already disabled all the plugins, but unfortunately, the issue remains unchanged. 

However, when I configured another Neovim instance with minimal settings using mini.starter, the problem disappeared.

 It seems the issue is related to my configuration. Therefore, I'll go ahead and close this matter. thanks again
