### ISSUE TITLE
Mini Files can't copy file to non-existent folder

### ISSUE THREAD

**Issue by BeauSLM** [echasnovski/mini.nvim#481]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Can't copy file into not-yet-existing directory

### Neovim version

0.9.2

### Steps to reproduce

1. open file explorer
2. yank a file (yy on a file)
3. press p to copy the file into the current dir
4. go to the copy
5. press capital I (insert in front of the filename) and type an arbitrary file path in front that doesn't exist yet
6. attempt to synchronize
7. no new dir and no new file

### Expected behavior

a copy of the file is placed in the directory specified, creating any folders needed.

### Actual behavior

No file or directories are created

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I can reproduce this. I'll fix tomorrow.

**Comment by echasnovski** [comment]
Thanks again for noticing this. Should be fixed in latest `main`.

**Comment by BeauSLM** [comment]
No worries, thanks for the excellent plugin(s)!
