### ISSUE TITLE
Add fallback for `setup_auto_root()` to be executed if no root is found

### ISSUE THREAD

**Issue by Verf** [echasnovski/mini.nvim#483]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.misc

### Description

setup_auto_root can set the root directory as the parent directory of the current buffer if there is no root directory found by names, which is useful for editing a single file.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Setting current working directory to be a parent of the current file is a bit extreme (and is not a good practice for my taste). However, having a way to replicate `'autochdir'` in some kind of fallback action is a good idea. I'll think about it.

**Comment by echasnovski** [comment]
This should now be possible in `main` branch using new `fallback` argument.

Your use case of emulating 'autchdir' if no root is found with `vim.fs.find()` can be addressed with this code:
```lua
-- Use `names` to your liking
MiniMisc.setup_auto_root(nil, function(path) return vim.fs.dirname(path) end)
```
