### ISSUE TITLE
bug: Enabling mini-animate occasionally causes snippets in C++ to malfunction. 

### ISSUE THREAD

**Issue by shininome** [echasnovski/mini.nvim#484]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini-animate luasnip

### Description

Most of the time, Luasnip works fine, but sometimes it appears and disappear
https://github.com/LazyVim/LazyVim/discussions/1468

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. open a cpp and use ":e" or gg to top
3. insert after
Link *L = creat_link_tail();
"for() , if or other snippet"

### Actual behavior

https://www.youtube.com/watch?v=TP9ed3mdd4s

**Comment by shininome** [comment]
> I use both 'mini.animate' and 'L3MON4D3/LuaSnip' while never experiencing this problem.
> 
> Please provide more precise reproducing example to see what is happening.
> 
> Note: in the video you seem to expand snippet using 'nvim-cmp'. This can also take part in the behavior and shouldn't be needed for minimal reproduction.


hi,this is my test code. 
after I disable mini-animate plug(by comment {import = "lazyvim.plugins.extras.ui.mini-animate"} in lazyvim config)
 the snippet become normal,

and this is my issue for lazyvim https://github.com/LazyVim/LazyVim/issues/1472

```
#include <stdio.h>
#include <stdlib.h>

struct Link {
  int value;
  Link *next;
};

void del_x(Link *&L, int x) {
  if (!L)
    return;
  Link *pre;
  if (x == L->value) {
    pre = L;
    L = L->next;
    free(pre);
    del_x(L, x);
  } else {
    del_x(L->next, x);
  }
}

Link *creat_link_tail() {
  Link *head = (Link *)malloc(sizeof(Link));
  Link *rear = (Link *)malloc(sizeof(Link));
  head = rear;
  int value;
  scanf("%d", &value);
  while (value != 9999) {
    Link *p = (Link *)malloc(sizeof(Link));
    p->value = value;
    rear->next = p;
    rear = p;
    scanf("%d", &value);
  }
  rear->next = NULL;
  return head;
}

void print_link(Link *L) {
  Link *p = L->next;
  while (p != NULL) {
    printf(" %d ", p->value);
    p = p->next;
    if (p != NULL) {
      printf("->");
    }
  }
  printf("\n");
}

int main(int argc, char *argv[]) {
  freopen("./link_in.txt", "r", stdin);
  Link *a, *b;
  Link *L = creat_link_tail();
  for (range-declaration : range-expression) {
  
  }
  print_link(L);
}
```

**Comment by echasnovski** [comment]
I tried reproducing with configuration from [this link](https://github.com/LazyVim/LazyVim/issues/1472#issuecomment-1727593449) and could not reproduce. Here is what I got:

https://github.com/echasnovski/mini.nvim/assets/24854248/9fdb3010-e563-4536-93f0-675b83fff991

Please, provide a *minimal* reproducing example. Ideally involving *only* plugins involved (presumably, 'mini.animate' and 'LuaSnip'; with possibly some others).

**Comment by echasnovski** [comment]
> I am sorry,I dont know the right way to make a minimal example, ...

No worries, we all started somewhere. Basically, try to narrow down the minimal number of plugins and configuration lines still capable to reproduce the issue when Neovim is run with that config.

> could you use :e to reload the cpp or use gg and ctrl o and then insert snippet? Perhaps it's a bug with macOS?

I tried both those steps and new config from [this comment](https://github.com/LazyVim/LazyVim/issues/1472#issuecomment-1727726169) (suggesting it is able to reproduce the issue).

Still can not reproduce, unfortunately.

**Comment by dpetka2001** [comment]
Hi @echasnovski, I was indeed able to reproduce the issue with just bare `lazy.nvim`, `nvim-cmp`, `Luasnip`, `friendly-snippets` and `mini.animate`. Quoting myself from the latest observations in the Lazyvim issue
> I noticed that the problem occurs when after pressing <C-o> the line that the jump takes you is the last line of the window. However, this is not consistent. Sometimes, the jump that <C-o> takes you, shows the line in the end of the window and other times show the line centered in the window. I could not reproduce the problem when the line was shown at the center of Neovim window. I don't know the internals of how jumplist works to render the final output of the jump on the screen. But even if you were on the last line after some jump, if you pressed zz to center the line, then the problem would not occur. It would only occur if <C-o> would take you to a jump that was shown as the last line of the window from my observations. Either way, the problem does not happen when you have mini.animate disabled.

So, if you use the [repo](https://github.com/dpetka2001/lazy_nvim) that I also linked in the Lazyvim issue, can you go to the last line by pressing `G`, then `gg` and then `<C-o>` and try to type `for` and accept the `Luasnip` autocompletion entry? Please use as reference to test the file `lua/plugins/editor.lua` as it has to be long enough (according to my observations) to exceed the size of the Neovim window.

**Comment by echasnovski** [comment]
> Hi @echasnovski, I was indeed able to reproduce the issue with just bare `lazy.nvim`, `nvim-cmp`, `Luasnip`, `friendly-snippets` and `mini.animate`. Quoting myself from the latest observations in the Lazyvim issue
> 
> > I noticed that the problem occurs when after pressing  the line that the jump takes you is the last line of the window. However, this is not consistent. Sometimes, the jump that  takes you, shows the line in the end of the window and other times show the line centered in the window. I could not reproduce the problem when the line was shown at the center of Neovim window. I don't know the internals of how jumplist works to render the final output of the jump on the screen. But even if you were on the last line after some jump, if you pressed zz to center the line, then the problem would not occur. It would only occur if  would take you to a jump that was shown as the last line of the window from my observations. Either way, the problem does not happen when you have mini.animate disabled.
> 
> So, if you use the [repo](https://github.com/dpetka2001/lazy_nvim) that I also linked in the Lazyvim issue, can you go to the last line by pressing `G`, then `gg` and then `<C-o>` and try to type `for` and accept the `Luasnip` autocompletion entry? Please use as reference to test the file `lua/plugins/editor.lua` as it has to be long enough (according to my observations) to exceed the size of the Neovim window.
> 
> Edit: I guess that also depends on the size of the monitor you use maybe (this is just a wild guess as I don't actually know)? I'm using a 15.4 inch laptop so my screen and thus Neovim window size are not that big compared to a bigger monitor. If you have a big monitor could you plz try with a file that exceeds the height of your Neovim window?

Thanks for detailed steps to reproduce. I've cloned it to `~/.config/nvim_luasnip_animate` using steps from "1. Clone".

Here is my reproduction of "2. Reproduce problem:" (`nvim_new` is a `NVIM v0.10.0-dev-c4f4c7a` version) :

https://github.com/echasnovski/mini.nvim/assets/24854248/8ec80ea3-98b1-4ce6-ba49-3152cb0d192c

So I still can not reproduce the issue, which is fairly weird.

**Comment by dpetka2001** [comment]
@echasnovski I was on Neovim commit `c3e176f` and just upgraded to latest HEAD (`23c21e7` at the moment) and can confirm I cannot reproduce the issue any more. So, I guess it was something upstream, that affected `mini.animate` somehow? Because this problem wouldn't occur when `mini.animate` was not installed.

**Comment by abeldekat** [comment]
Hello @echasnovski,

@dpetka2001 and I discovered that the issue might be related to the scrolloff setting.
When using the code fragment from this [comment](https://github.com/echasnovski/mini.nvim/issues/484#issuecomment-1727605163), a `cpp` file, the issue occurs consistently:

* G to bottom of the file
* o
* type "for"
* accept snippet
* snippet is not correct
* press u
* snippet is correct

However, when renaming the file to a `c` file, the snippet is inserted correctly. For the `c` language, the snippet contains two lines. The `cpp` version contains three lines, as does the `lua` version, which also fails. The `lua` file tested: `.repro/plugins/LazyVim/lua/lazyvim/plugins/editor.lua`. 
We tested this on `neovim` v0.9.2, `neovim` nightly and on `neovim` master.

To reproduce:

`minimal.lua`:
```
-- a minimal init using LazyVim, conditionally enabling plugins by keyword
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- stylua: ignore start
local enabled_plugins_by_lowercase_keyword = {
  "lazy", "tokyo", "animate", "snip", "nvim-cmp"
}
-- stylua: ignore end

local plugins = {
  "folke/tokyonight.nvim",
  { "LazyVim/LazyVim", version = "6.3.0", import = "lazyvim.plugins" },
  -- stylua: ignore start
  -- overwrite the explicit cond in lazyvim.plugins.lsp
  { "hrsh7th/cmp-nvim-lsp", cond = function() return false end, },
  -- stylua: ignore end
  -- adding: mini.animate
  { "echasnovski/mini.animate", event = "VeryLazy", config = true },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
  defaults = {
    cond = function(plugin)
      local plugin_name = string.lower(plugin.name)
      for _, keyword in ipairs(enabled_plugins_by_lowercase_keyword) do
        if plugin_name:find(keyword, 1, true) then
          return true
        end
      end
      return false
    end,
  },
})
vim.cmd.colorscheme("tokyonight")
```

`./repro/nvim/lazy-lock.json`:

```json
{
  "LazyVim": { "branch": "main", "commit": "a72a84972d85e5bbc6b9d60a0983b37efef21b8a" },
  "LuaSnip": { "branch": "master", "commit": "8efa4e402a24df6a4713a2ec653147c49e8f73de" },
  "cmp_luasnip": { "branch": "master", "commit": "18095520391186d634a0045dacaa346291096566" },
  "friendly-snippets": { "branch": "main", "commit": "ebf6d6e83494cdd88a54a429340256f4dbb6a052" },
  "lazy.nvim": { "branch": "main", "commit": "2a9354c7d2368d78cbd5575a51a2af5bd8a6ad01" },
  "mini.animate": { "branch": "main", "commit": "230140aa0b06af87c9d345573aab1aaf50d8b539" },
  "nvim-cmp": { "branch": "main", "commit": "5dce1b778b85c717f6614e3f4da45e9f19f54435" },
  "tokyonight.nvim": { "branch": "main", "commit": "9a01eada39558dc3243278e6805d90e8dff45dc0" }
}
```

The scrolloff setting in `LazyVim`'s `lazyvim.config.options`:
> opt.scrolloff = 4 -- Lines of context

**Comment by echasnovski** [comment]
> The scrolloff setting in `LazyVim`'s `lazyvim.config.options`:
> 
> > opt.scrolloff = 4 -- Lines of context

Yeah, with this `scrolloff` I can finally reproduce. I'll take a look, but I remember `scrolloff` being a bit troublesome to account for in 'mini.animate'.

**Comment by dpetka2001** [comment]
Hi @echasnovski, 

in my initial comment when I first tried reproducing this issue, I was using Neovim `c3e176f` and was able to reproduce it without setting `scrolloff = 4` explicitly, but rather using the default Neovim option (which was 0). That's why I thought it had nothing to do with Lazyvim's options. If my original post was in any way misleading, please bear in mind it wasn't on purpose (unfortunately my programming skills are very novice and my only experience thus far was helping people with their Lazyvim configuration specifically, since that's what I use and am comfortable with myself). I still can reproduce it in Neovim built on that commit hash (I double checked just to be sure) without explicitly setting any `scrolloff` option. So, something must have changed in between that doesn't trigger this behavior any more with default `scrolloff` option.

**Comment by echasnovski** [comment]
@dpetka2001, I was not in any way, shape, or form implying that something was your fault. Your precise steps helped tremendously!

I am in the middle of investigating this a bit. My current thoughts:
- This (probably) has nothing to do with 'scrolloff' per se, but with scrolling being triggered during snippet expansion. Having it on last line with non-zero 'scrolloff' is the most obvious way to achieve that.
- There are (probably) several issues entangled here. Text being removed is the result of some plugin placing cursor just before text triggering snippet and exiting Select mode. Placing cursor is probably [due to LuaSnip](https://github.com/L3MON4D3/LuaSnip/blob/8efa4e402a24df6a4713a2ec653147c49e8f73de/lua/luasnip/init.lua#L228-L242) (because it seems that scroll in 'mini.animate' is triggered when cursor is already moved), while I am not sure about exiting Select mode (probably, a side effect of 'mini.animate').

You can see more details with different scroll timing: `lua MiniAnimate.config.scroll.timing = function() return 1000 end`.

**Comment by echasnovski** [comment]
I've summarized results of my investigation in  L3MON4D3/LuaSnip#1010 . I *think* that if the problem there is addressed, this issue should be fixed. I don't see a reasonable way to fix this without updating LuaSnip.

**Comment by abeldekat** [comment]
Thanks for the thorough investigation, @echasnovski!
