### ISSUE TITLE
mini.files errors when combined with mini.starter

### ISSUE THREAD

**Issue by skoch13** [echasnovski/mini.nvim#485]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter, mini.files

### Description

Thank you for your work! I'm a huge fan of `mini.files`, but the only place where it doesn't work for me is for the special `Starter` file. I want to be able to browse the project files on the starting screen without opening Telescope or similar plugins.

### Neovim version

0.9.2

### Steps to reproduce

1. Use mini.files and mini.starter in your config
2. Open nvim which triggers `mini.starter`
3. Start `mini.files`

### Actual behavior

```
E5108: Error executing lua: (mini.files) `path` is not a valid path ("/Users/%USER%/.dotfiles/Starter")
stack traceback:

```

**Comment by echasnovski** [comment]
Hi! Thanks for kind words!

This is working as intended. You seem to start 'mini.files' with [something like this](https://github.com/echasnovski/mini.nvim/blob/ed7c355bbeb8939e0dfe5099aa13c8ac9709396c/doc/mini-files.txt#L630) which opens inside a directory of current file. But Starter buffer is not associated with any file. Try plain `:lua MiniFiles.open()` instead.

**Comment by skoch13** [comment]
When I tried to open it as you suggested, I received the following error:

```
Error  20:15:42 msg_show.lua_error   MiniFiles.open() E5108: Error executing lua [string ":lua"]:1: attempt to index global 'MiniFiles' (a nil value)
stack traceback:
	[string ":lua"]:1: in main chunk
```

**Comment by echasnovski** [comment]
> When I tried to open it as you suggested, I received the following error:
> 
> ```
> Error  20:15:42 msg_show.lua_error   MiniFiles.open() E5108: Error executing lua [string ":lua"]:1: attempt to index global 'MiniFiles' (a nil value)
> stack traceback:
> 	[string ":lua"]:1: in main chunk
> ```

It assumes that you ran `require('mini.files').setup()` (which creates global `MiniFiles` variable).

Try `:lua require('mini.files').open()` instead then.

**Comment by skoch13** [comment]
That works, indeed. I appreciate your help!

**Comment by akijakya** [comment]
I put together this function which toggles mini.files, assigned to a key combination:

```lua
function()
  local miniFiles = require("mini.files")
  if not miniFiles.close() then
    -- open file explorer if current buffer is not on disk, e.g. Starter
    if vim.fn.getreg("%") ~= "" then
      miniFiles.open()
    else
      -- open file explorer at current file
      miniFiles.open(vim.api.nvim_buf_get_name(0))
    end
  end
end
```

**Comment by echasnovski** [comment]
@akijakya, this will do more closely what is described in the comments (assuming `require('mini.files').setup()` was called prior; which it probably should):

```lua
function()
  -- Close explorer if it is opened
  if MiniFiles.close() then return end
  -- Compute whether current buffer is for file on disk.
  -- If yes - use it to open explorer; otherwise use cwd.
  local buf_path = vim.api.nvim_buf_get_name(0)
  local path = vim.loop.fs_stat(buf_path) ~= nil and buf_path or vim.fn.getcwd()
  MiniFiles.open(path)
end
```

**Comment by akijakya** [comment]
@echasnovski thanks a lot, that is much better! Sorry for the half-baked attempt (would have made sense (only) for the Starter buffer with this condition `vim.fn.getreg("%") == "Starter"` though)...

**Comment by echasnovski** [comment]
> @echasnovski thanks a lot, that is much better! Sorry for the half-baked attempt (would have made sense (only) for the Starter buffer with this condition `vim.fn.getreg("%") == "Starter"` though)...

No worries.

Usually the better way to tell if the buffer is for a certain plugin is to test its filetype. So here it could be `vim.bo.filetyep == 'ministarter'`. Also the `vim.fn.getreg("%")` is the same as `vim.api.nvim_buf_get_name(0)` (as far as documentation describes), so it would make sense to use one consistently.
