### ISSUE TITLE
Mini.staritfy - automatically discard missed query characters

### ISSUE THREAD

**Issue by JoseConseco** [echasnovski/mini.nvim#49]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

Rather than using <bs> to delete symbol from query, it would be great if that symbol would be automatically discarded. No need to <bs> == we save one click.
![image](https://user-images.githubusercontent.com/13521338/155856791-3ef20d70-f833-4625-9965-386a7279839e.png)

**Comment by JoseConseco** [comment]
I just noticed you are from Ukraine. I hope you are fine and Ukraine will keep it independence from Russia.

**Comment by echasnovski** [comment]
Thanks for suggestion! It does seem to be a reasonable behavior, not sure why I didn't do this originally. Should be implemented in current `main` branch.

And thank you very much for your kind words about current situation in Ukraine. I managed to more or less settle for the moment, but not quite sure what will happen in the near future. So there might be pauses in development of this plugin.

**Comment by JoseConseco** [comment]
I just tried latest update-  and I see regression - eg when I press `s` for sessions I get this message:
![image](https://user-images.githubusercontent.com/13521338/157267271-553cd6d5-9e52-4e1c-a0ae-912e78f8688b.png)
I have to press 'ret' to then open telescope - and it then works ok.
My actions:
```lua
local my_items = {
	starter.sections.builtin_actions(),
	{ name = 'Sessions', action = ":Telescope sessions_picker", section = 'Telescope' },
	{ name = 'Recent Files', action = ':Telescope oldfiles', section = 'Telescope' },
	{ name = 'File Brower', action = ':Telescope file_browser', section = 'Telescope' },
	-- starter.sections.recent_files(10, false),
	-- starter.sections.recent_files(10, true),
	-- Use this if you set up 'mini.sessions'
	starter.sections.sessions(9, true),
	{ name = 'Addons', action = ':Explore ~/.config/blender/2.82/scripts/addons', section = 'Bookmarks' },
	{ name = 'NvimPlugs', action = ':Explore ~/.local/share/nvim/site/pack/packer/start', section = 'Bookmarks' },

}
```
And I have enabled - 'autoopen'. Other actions - including sessions - also now require pressint ret. It was working ok before latest update - item would be executed immediately after pressing its key.

**Comment by echasnovski** [comment]
Fixed having to type `<CR>` even with `evaluate_single` - accidentally introduced hit-enter-prompt. Should be fixed in latest `main` commit.

About your `rv` query even if you press single `s`. This seems like a configuration issue, because I couldn't reproduce. Could you, please, post full config and reproducible steps?

**Comment by JoseConseco** [comment]
rv messages is gone now. Thx for the fix.
