### ISSUE TITLE
mini.clue: Add ability to ignore key maps for display.

### ISSUE THREAD

**Issue by dsully** [echasnovski/mini.nvim#490]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

`which-key.nvim` has functionality where if the description of a mapping is `which_key_ignore`, that map will be ignored in the display. I use this for `<leader>N` buffer switch mappings, where `N` is `0-9`.

It'd be great if `mini.clue` had something similar. In `key-menu.nvim`, this is `hidden`.

**Comment by echasnovski** [comment]
Thanks for suggestion!

I somewhat strongly believe in "show all mappings" approach. But I'll think about it.

**Comment by echasnovski** [comment]
Sorry, I think allowing ignoring some keys but not others is not a good idea long term. Both for 'mini.clue' and users who manage their own config.

Closing as not planned.

**Comment by saifulapm** [comment]
Is there any way, that can be possible right now ? Like I don;t want to show <Leader>1..10 keymaps.

**Comment by echasnovski** [comment]
> Is there any way, that can be possible right now ? Like I don;t want to show 1..10 keymaps.

Sorry, no. If there is a mapping, it will be shown.
