### ISSUE TITLE
mini.clue: allow customization of special keys

### ISSUE THREAD

**Issue by jbarap** [echasnovski/mini.nvim#491]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Hello, great set of plugins you've built!

Currently, mini.clue has a predefined behavior when pressing the "special keys". Those being `<Esc>`, `<C-c>`, `<CR>`, etc. I've found the default set of actions pretty logical, but it would be nice if the user could customize which keys do what actions. For example, I have `<Leader><CR>` mapped to `:nohl`, so instead of having the default `<CR>` execute a key query, it would be useful to remap that action to something like `<S-CR>` (or whatever the user determines to be better) instead, to avoid any conflicts with existing keymaps.

I looked around in the documentation and code, and I didn't find an easy way to do this. If I'm mistaken please let me know.

**Comment by echasnovski** [comment]
Thanks for suggestion!

Yeah, currently `<Esc>`, `<C-c>`, `<CR>`, and `<BS>` have special meaning and can't be overridden. One of the main reasons is that there are very limited number of keys which are 1) intuitive for tasks they do; *and* 2) don't usually used as part of mapping; *and* 3) can be processed by `getcharstr()` powering key query process. For example, having `<S-CR>` and `<C-CR>` seems simply impossible (at least it depends on terminal emulator), while `<M-CR>` is possible.

I am hesitant for adding too much customization to 'mini.nvim' modules. As 'mini.clue' already needs to be completely configured from ground up, I don't think this will happen. But I'll take time to think about it.

**Comment by jbarap** [comment]
Understandable, I figured the limitations of key processing would have made the feature janky.

Thank you for considering it, and for the good work with mini.nvim!
