### ISSUE TITLE
(mini.files) FEATURE: add`:w` to sync changes rather than `=`

### ISSUE THREAD

**Issue by lordvidex** [echasnovski/mini.nvim#497]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

1. It is intuitive that `:w` should save changes in (neo)vim.
2. On the QWERTY layout `=` is farther to reach compared to the "write" combo keys.

Generally, I think that the `:w` command is more convenient and is the vim way.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Closing as not planned and a duplicate of #391. See the reasoning there.
