### ISSUE TITLE
mini.move: make V and v behaviour the same

### ISSUE THREAD

**Issue by duarm** [echasnovski/mini.nvim#499]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.move

### Description

When moving a visual selection with mini.move, there are three ways of making a visual selection:

v to select character-wise
V to select line-wise
Ctrl+v to select a block

mini.move follows each visual selection accordingly, but It would be nice to have an option to make the line-wise (V) behaviour the default for every selection, since that's the default behaviour of every plugin/editor with similar functionality, and that's what I'm used to.

Thanks for working on mini.nvim!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think treating every selection type the same is a good idea. Mostly because treating them differently aligns with most of built-in behavior. And also selecting linewise is not significantly less convenient than charwise or blockwise.

Closing as not planned.

**Comment by duarm** [comment]
I understand, I'm not asking for a new default behaviour, usually other move plugins like move.nvim provide a function like MoveLineWise(-1), which also works with visual mode, so we can decide if the behaviour we want. mini.move provides the MiniMove.move_line('down'), but that doesn't work with visual mode.
