### ISSUE TITLE
"Scanning tags." when typing in insert mode

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#5]
When I'm typing something in insert mode and there's no completion available, the command line keeps saying `Scanning tags.`, which is really annoying. Would it be possible to get rid of this?

**Comment by echasnovski** [comment]
Another semi-solution that seems to "work" comes from [these comments](https://github.com/vim/vim/issues/3412#issuecomment-641041755):
- `set showmode`.
- `set shortmess+=c`.
- "Hide" mode message by defining `hi ModeMsg guifg=<your background color> guibg=NONE gui=NONE`. This way it will be shown but not seen.

**Comment by echasnovski** [comment]
After almost a year, this is finally possible in Neovim nightly. See neovim/neovim#20633. I've just tested with latest release, and doing `:set shortmess+=C` works.
