### ISSUE TITLE
Better comments in mixed-language files with treesitter

### ISSUE THREAD

**Issue by SuperCuber** [echasnovski/mini.nvim#50]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

I'm not sure whether this falls under `Configurable (from module) comment structure. Modify |commentstring| instead`, sorry if it does :)

I'm currently using https://github.com/numToStr/Comment.nvim and it has support for using the correct type of comment for each part of the file. For example
```lua
-- here it uses this prefix
vim.cmd [[
; here it uses this prefix
]]
```

I really like the `gc` text object feature from mini.comment but not having this kinda sucks, especially for files like `.vue` where the file is split pretty evenly between 3 different languages.

**Comment by echasnovski** [comment]
Unfortunately, no. Option `commentstring` is local to buffer, meaning it defines single comment structure for all lines in buffer. So mixed-language comments are not supported. At least at the moment (and, probably, for some foreseeable future).

**Comment by singlexyz** [comment]
I implemented this with nvim-ts-context-commentstring.
The commentstring should be dynamically set according to the treesitter's query.

https://github.com/tpope/vim-commentary
https://github.com/JoosepAlviste/nvim-ts-context-commentstring

**Comment by echasnovski** [comment]
I totally missed 'JoosepAlviste/nvim-ts-context-commentstring' (probably because by the name and common examples I thought that it is mostly about Typescript :) ). 
So, @SuperCuber, it *kind of* works with 'mini.comment': it updates `commentstring` option on every `CursorHold` event (triggered after cursor is idle for `updatetime` milliseconds). So it is like: position cursor, wait for `updatetime` milliseconds, comment with "appropriate" comment structure.

For full support, 'mini.comment' needs to implement "pre-comment" hook. Which I am more inclined to add, than multi-language support.

**Comment by SuperCuber** [comment]
> I totally missed 'JoosepAlviste/nvim-ts-context-commentstring' (probably because by the name and common examples I thought that it is mostly about Typescript :) ). 
> So, @SuperCuber, it *kind of* works with 'mini.comment': it updates `commentstring` option on every `CursorHold` event (triggered after cursor is idle for `updatetime` milliseconds). So it is like: position cursor, wait for `updatetime` milliseconds, comment with "appropriate" comment structure.
> 
> For full support, 'mini.comment' needs to implement "pre-comment" hook. Which I am more inclined to add, than multi-language support.

I like that idea - modular and opt-in. That plugin deserves a mention in docs if you end up implementing it imo :)

**Comment by echasnovski** [comment]
@SuperCuber, I added `config.hooks` option, so this is now (with present 'JoosepAlviste/nvim-ts-context-commentstring' API) should be possible with:
```lua
require('mini.comment').setup({
  hooks = {
    pre = function()
      require('ts_context_commentstring.internal').update_commentstring()
    end,
  },
})
```
