### ISSUE TITLE
Add keymap for toggling hidden files

### ISSUE THREAD

**Issue by dapc11** [echasnovski/mini.nvim#505]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Thanks for a great plugin. It replaced neo-tree straight off without any second thoughts. The only thing I'm missing though, is that it would be useful to have a key map for toggling hidden files in mini.files.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This [is out of scope to be coming built-in](https://github.com/echasnovski/mini.nvim/blob/25c4bf4efac51aad5393e37949e68ac3e672a73c/doc/mini-files.txt#L31-L32). There is a [documented approach](https://github.com/echasnovski/mini.nvim/blob/25c4bf4efac51aad5393e37949e68ac3e672a73c/doc/mini-files.txt#L400-L426) on how to achieve this.

Closing as not planned.
