### ISSUE TITLE
mini.files: `Getting Invalid Buffer Id` Error while starting nvim

### ISSUE THREAD

**Issue by imsaravana369** [echasnovski/mini.nvim#508]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

Recently I started using `mini.files`,  I'm using lazy.nvim as my package manager.
```
{ 'echasnovski/mini.files', version = '*' }
```

It works fine, but at every nvim startup I'm getting this error
```
Error detected while processing BufEnter Autocommands for "*":
Error executing lua callback: ...n.m/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1154: scoped variable: Invalid buffer id: 1
stack traceback:
        [C]: in function '__index'
        ...n.m/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1154: in function <...n.m/.local/share/nvim/lazy/mini.files/lua/mini/files.lua:1150>
```

I tried using the latest branch by setting `version = false`, still same issue. I even tried mini.nvim, still same issue

        

### Neovim version

NVIM v0.9.1

### Steps to reproduce

I followed the steps specified in https://github.com/echasnovski/mini.files
1. In lazy.nvim  add this dependency `  { 'echasnovski/mini.files', version = '*'}`
2. call require('mini.files').setup() in lua

### Expected behavior

Shouldn't throw any error at startup

### Actual behavior

Throwing error at startup

**Comment by echasnovski** [comment]
Thanks for the issue!

I am pretty sure that this is some misconfiguration issue or conflict with the other plugin which takes over during startup. However, there was an opportunity to simplify that function and now this shouldn't happen.
