### ISSUE TITLE
Add commented recipes `MiniColors.interactive()`

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#511]
Consider adding common recipes in `MiniColors.interactive()` buffer as comments. This would make experience a little more straightforward.

See #510.

**Comment by echasnovski** [comment]
@wroyca, I've added two examples that seem to be reasonably frequent yet different enough to be useful. Thanks for the suggestion!

**Comment by wroyca** [comment]
> @wroyca, I've added two examples that seem to be reasonably frequent yet different enough to be useful. Thanks for the suggestion!

Awesome, thanks ! 🥳
