### ISSUE TITLE
mini.bufremove: use the native `:confirm` interface when closing buffers

### ISSUE THREAD

**Issue by musjj** [echasnovski/mini.nvim#514]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bufremove

### Description

Vim provides a native `:confirm` command for operations that require confirmation, such as when closing unsaved buffers. It would be nice if `mini.bufremove` can use this to allow the user to confirm unsaved changes.

**Comment by echasnovski** [comment]
That is an interesting idea! Thanks for creating this!

I'll think about it.
