### ISSUE TITLE
[mini.files] Hope to add support for quick jump between directories

### ISSUE THREAD

**Issue by lost22git** [echasnovski/mini.nvim#515]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

something like yazi with zoxide

https://yazi-rs.github.io/docs/videos/multi-tab_zoxide.mp4

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think this is out of scope for 'mini.files'. The feature itself looks nice, but it would require too much code/tests/documentation to implement properly.
