### ISSUE TITLE
Mini Pick grep and grep_live search .git folder as well

### ISSUE THREAD

**Issue by BeauSLM** [echasnovski/mini.nvim#516]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Grep and grep live functionality will also search the .git/ folder, which isn't really useful. It also pollutes search results.

An effective solution could be passing `--glob=.git/*` to ripgrep, but there are other ways to prevent searching .git folders.

### Neovim version

nightly

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. :Pick grep some string that's in the .git folder

### Expected behavior

don't search .git folder

### Actual behavior

searches .git folder

**Comment by echasnovski** [comment]
Yeah, indeed it does that and indeed not really useful. I'll think about it.

**Comment by Keyhart** [comment]
Ripgrep also supports an rc file which you can globally ignore certain files/filetypes or folders with: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

Example how I do it in .ripgreprc:
```
# Exclude directories.
--glob=!{.git,.svn,node_modules}

# Exclude file types.
--iglob=!*.{~sql}
```

**Comment by echasnovski** [comment]
> Ripgrep also supports an rc file which you can globally ignore certain files/filetypes or folders with: https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

Oooh... I like this approach a lot more than having it hard coded in default command. Thanks so much for this!

@BeauSLM, I think I am going to close this in favor of users setting up their local `rg` configs.
