### ISSUE TITLE
How do I ensure `mini.indentscope` ignores certain buffer types?

### ISSUE THREAD

**Issue by Jarmos-san** [echasnovski/mini.nvim#52]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.indentscope

### Description

I noticed certain buffer types like help texts, "_nvim-nerd-tree file explorer_" & such shows the indent lines as well. Is there any way to disable that behaviour for a specific set of buffer types?

The behaviour would be more akin to what [lukas-reineke/indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim) does with `indent_blankline_filetype_exclude`, `indent_blankline_buftype_exclude`, `indent_blankline_bufname_exclude` set to true.

### Neovim version

0.6.1

### Steps to reproduce

Easiest way to reproduce it is to enable `mini.comment` & then open a random help text in Neovim. Following is a screenshot which shows the unintended behaviour in action.

![image](https://user-images.githubusercontent.com/31373860/159131720-1bad9cf4-d622-422e-a14f-fc6c1637d2bb.png)

### Expected behavior

Certain buffers like the terminal, help texts & such shouldn't show the indent line.

### Actual behavior

Buffers which shouldn't show the indent lines in the first place shows them (see screenshot above for reference).

**Comment by echasnovski** [comment]
To disable autodrawing, set `g:miniindentscope_disable` (globally) or `b:miniindentscope_disable` (for a buffer) to `v:true`. Considering high number of different scenarios and customization intentions, writing exact rules for disabling module's functionality is left to user. See [mini.nvim-disabling-recipes](https://github.com/echasnovski/mini.nvim/blob/b6c40f8b02221834d6dc4395ffb7431af92c18af/doc/mini.txt#L168-L179) for common recipes.
