### ISSUE TITLE
Repeat selection operation

### ISSUE THREAD

**Issue by ekiefl** [echasnovski/mini.nvim#521]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

With the default config, typing `vinf` will select inside the call signature of the next function call. And typing `inf` again will select inside the next call signature, and so on. Unlike `c` and `d` operations, the dot repeat for this doesn't work because vim doesn't have a native mechanism for "remembering" the last text-object operation.

Yet imo, this feature would be very usefu, and would be analogous to `fa;;;` for jumping to successive `a` chars within a line.

Does this feature exist, or can you think of a way to hack it?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Just to be sure I understand this clearly. You'd like that after `vinf`, typing `.` would essentially repeat `inf` keys?

**Comment by ekiefl** [comment]
Yes, exactly! Either that or the ; character

**Comment by echasnovski** [comment]
Then sorry, no, this is out of scope for 'mini.ai' for at least these reasons:
- I would like to adhere to built-in neovim definition of dot-repeat that it "repeats last change". As selection is not a change, then it should not work with dot repeat.
- Making it work with any other special key to repeat would introduce some non-trivial cache handling (on top existing non-trivial one).
- To somewhat remedy the need to type `inf` many times, it supports `v:count`, so `2inf` will work as if `infinf`.

Closing as not planned.

**Comment by ekiefl** [comment]
Makes sense.

Nevertheless, I would find the ability quite useful, as it can be hard to count how many times a pattern is found between the cursor and your target, and its inconvenient to type 'inf' and 'ilf' repeatedly (just as an example).

You're a busy person, but if you could imagine how this capability could be hacked together with the existing API, I'd greatly appreciate it. And if I find a hack myself, I'll post it here for future readers.

**Comment by echasnovski** [comment]
> You're a busy person, but if you could imagine how this capability could be hacked together with the existing API, I'd greatly appreciate it. And if I find a hack myself, I'll post it here for future readers.

General idea I would start looking is to somehow track and cache the latest used keys/function/command and then reuse it in dedicated function/key (`;` in this example).

**Comment by ekiefl** [comment]
Ok, I have a solution I think is worth sharing.

In `text_object_repeat.lua`:

```lua
local M = {}
local ai = require("mini.ai")

M.last_text_object_action = nil

M.unpack_pattern = function(pattern)
    local inner_or_outer = string.sub(pattern, 1, 1)
    local method_specifier = string.sub(pattern, 2, 2)
    local match_char = string.sub(pattern, 3, 3)
    return inner_or_outer, method_specifier, match_char
end

M.method_to_specifier = function(method)
    return method == "next" and "n" or (method == "prev" and "l" or nil)
end

M.specifier_to_method = function(specifier)
    return specifier == "n" and "next" or (specifier == "l" and "prev" or nil)
end

M.invert_method = function(method)
    return method == "prev" and "next" or (method == "next" and "prev" or nil)
end

M.invert_pattern = function(pattern)
    local inner_or_outer, method_specifier, match_char = M.unpack_pattern(pattern)
    local inverted_specifier = M.method_to_specifier(M.invert_method(M.specifier_to_method(method_specifier)))
    return inner_or_outer .. inverted_specifier .. match_char
end

M.execute_and_remember = function(pattern)
    M.last_text_object_action = pattern
    local inner_or_outer, method_specifier, match_char = M.unpack_pattern(pattern)
    ai.select_textobject(
        inner_or_outer,
        match_char,
        {vis_mode = "v", search_method = M.specifier_to_method(method_specifier) }
    )
end

M.repeat_last_text_object = function()
    if M.last_text_object_action ~= "" then
        M.execute_and_remember(M.last_text_object_action)
    end
end

M.inverse_repeat_last_text_object = function()
    if M.last_text_object_action ~= "" then
        M.execute_and_remember(M.invert_pattern(M.last_text_object_action))
    end
    M.last_text_object_action = M.invert_pattern(M.last_text_object_action)
end

return M
```

Then when I load `mini.ai`:

```lua
require("mini.ai").setup({
    -- It still works without disabling these, but good form to indicate an override is taking place
    mappings = {
        around_next = '',
        inside_next = '',
        around_last = '',
        inside_last = '',
    },

    -- How to search for object (first inside current line, then inside
    -- neighborhood). One of 'cover', 'cover_or_next', 'cover_or_prev',
    -- 'cover_or_nearest', 'next', 'previous', 'nearest'.
    search_method = 'cover',
})

local opts = { noremap = true, silent = true }
local tor = require("text_object_repeat")

local movements = { "in", "an", "il", "al" }
local characters = { "(", "[", "{", "<", ")", "]", "}", ">", "b", "\"", "'", "q", "?", "t", "f", "a" }

for _, movement in ipairs(movements) do
    for _, char in ipairs(characters) do
        local keymap = movement .. char
        vim.keymap.set('v', keymap, function() tor.execute_and_remember(keymap) end, opts)
    end
end

vim.keymap.set('v', ';', tor.repeat_last_text_object, opts)
vim.keymap.set('v', ',', tor.inverse_repeat_last_text_object, opts)
```

**Comment by nshern** [comment]
In the [helpfile](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-ai.txt) this seems to be listed as a feature, but is not working for me. Given this thread I am unsure whether this is implemented by default or not?

**Comment by echasnovski** [comment]
Support for dot-repeat means that if user does an edit using 'mini.ai' textobject (like `dif`; delete inside function call), it can be dot-repeated with textobject being recomputed at the new cursor position.

Dot-repeating visual selection is out of scope. See [this comment](https://github.com/echasnovski/mini.nvim/issues/521#issuecomment-1764618764) for more details.

**Comment by nshern** [comment]
Thank you for clarifying.
If the aim is to adhere to neovim built-in definitions shouldn't `;` then work?

So that :
`vaf` + `af`
could also be executed as:
`vaf` + `;`

**Comment by echasnovski** [comment]
> Thank you for clarifying. If the aim is to adhere to neovim built-in definitions shouldn't `;` then work?
> 
> So that : `vaf` + `af` could also be executed as: `vaf` + `;`

I think exactly the opposite, as `;` is documented as "Repeat latest f, t, F or T [count] times.". And even if it was "repeat latest motion...", it would still be not a good candidate, because `af` is not a motion (i.e. move cursor from current position), but textobject (i.e. select specific region less dependency on the exact cursor position).
