### ISSUE TITLE
mini.pick buffer deletion 

### ISSUE THREAD

**Issue by pwnwriter** [echasnovski/mini.nvim#525]
I'd like to add a bind like `C-b` to delete the buffer when toggeling `builtin.buffers()`. Is there something builtin or i need to write a custom snippet for that?

**Comment by echasnovski** [comment]
Yes, you'd have to write custom mapping for that. As you are at least third person to ask that, I'll add basic approach to `builtin.buffers()` help.

**Comment by echasnovski** [comment]
There is now an [example in `builtin.buffers()` help](https://github.com/echasnovski/mini.nvim/blob/41737e017165b6f9ea03154c56052a72d3699255/doc/mini-pick.txt#L1083-L1090) on how to call it with mapping that wipes out current buffer item.

**Comment by gegoune** [comment]
Nice! Is there a way to remove item from the list as well?

**Comment by echasnovski** [comment]
> Nice! Is there a way to remove item from the list as well?

Not the easy one, no. You can restart `builtin.buffers()` after deleting, but this might lead to some flicker. You can also get all items prior to wipe out (`MiniPick.get_picker_items()`), wipe out and modify the array accordingly, and then set it back (`MiniPick.set_picker_items()`). Either way, this is out of scope for `builtin.buffers()` and 'mini.pick' in general as it is more focused on picking and not manipulating.
