### ISSUE TITLE
feat(mini.files): handle `cc` intelligently

### ISSUE THREAD

**Issue by llllvvuu** [echasnovski/mini.nvim#528]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Right now, if you `cc` a file to try to rename it, it will actually delete the file and create a blank file with the new name. This can be shocking, especially if the file had untracked changes.

Using `C` works correctly, but it'd be nice to handle `cc` as well.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The whole idea of 'mini.files' file manipulation is to allow editing its buffers as regular text buffers as much as possible. This is powered by [having some concealed text in front of file basename](https://github.com/echasnovski/mini.nvim/blob/cff8f2bddbbc1093a9ffbf1122df918be5ff41d9/doc/mini-files.txt#L235-L244) which if deleted would mean that the file itself is assumed to later be deleted. As `cc` deletes whole line, this works as expected.

To mitigate shocking consequences, there is a confirm step which is *suggested* to be [read carefully](https://github.com/echasnovski/mini.nvim/blob/cff8f2bddbbc1093a9ffbf1122df918be5ff41d9/doc/mini-files.txt#L228).

Closing as not planned.
