### ISSUE TITLE
mini.completion: invalid tailwind class names completions after `-`

### ISSUE THREAD

**Issue by mortezadadgar** [echasnovski/mini.nvim#530]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

Hey, Thanks for your awesome plugins!
tailwind has css class names like `m-{number}` so typing m- should bring completion menu like m-1, m-2, etc instead completion is showing wrong candidates:
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/295f4dd2-b40e-498a-9aeb-82d722372dd8)
while omnifunc returns
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/83fa716a-6beb-4714-a420-798debda1f7f)
     

### Neovim version

NVIM v0.9.4

### Steps to reproduce

1. create a svelte project: `npm init svelte`
2. press enter on every prompt
3. npm install
4. initialize tailwindcss according to https://tailwindcss.com/docs/guides/sveltekit
5. `nvim --clean -u minimal.lua src/routes/+layout.svelte`
6. cursor on line 6 column 16 and type `m-`

minimal.lua:
```
for name, url in pairs({
	"https://github.com/neovim/nvim-lspconfig/",
	"https://github.com/echasnovski/mini.completion",
}) do
	local install_path = vim.fn.fnamemodify("lspconfig/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
		print("Installing " .. install_path)
	end
	vim.opt.runtimepath:append(install_path)
end

require("mini.completion").setup()

local lspconfig = require("lspconfig")
lspconfig.svelte.setup({})
lspconfig.tailwindcss.setup({})
```

### Expected behavior

to return same completion candidates as omnifunc

### Actual behavior

explained in description

**Comment by echasnovski** [comment]
Thanks for the issue!

Does the list of candidates look like that if completion is initiated with empty space to the left of cursor? It seems like `ml-` is not recognized as "base" for completion.

What does executing `:echo &iskeyword` show? For this to work, it should contain `-` as a symbol (it does not by default).

**Comment by mortezadadgar** [comment]
> Does the list of candidates look like that if completion is initiated with empty space to the left of cursor? It seems like ml- is not recognized as "base" for completion.

I'm not sure I understand what you mean by that, I'm not getting same completion with a space after `m-`

> What does executing :echo &iskeyword show? For this to work, it should contain - as a symbol (it does not by default).

Yes that makes it work though it's a not good idea to change that option globally as it will affect the vim word matching

**Comment by echasnovski** [comment]
> Yes that makes it work though it's a not good idea to change that option globally as it will affect the vim word matching

That is the whole point of this part of 'mini.completion' design: user wants to complete what is recognizable as "word". [Judging by the code](https://github.com/echasnovski/mini.nvim/blob/cff8f2bddbbc1093a9ffbf1122df918be5ff41d9/lua/mini/completion.lua#L1306), it was also the approach of built-in omnifunc. I'll take a look why these are different and revisit this.

**Comment by echasnovski** [comment]
I am not sure why built-in `vim.lsp.omnifunc` (I assume you used it in second example) give different complete word than 'mini.completion'. Here is the [code 'mini.completion' uses](https://github.com/echasnovski/mini.nvim/blob/cff8f2bddbbc1093a9ffbf1122df918be5ff41d9/lua/mini/completion.lua#L1306-L1310) and here is the [code of `vim.lsp.omnifunc`](https://github.com/neovim/neovim/blob/a8fc94a2fdd07edf0679d34f2deaacb25b3fa69f/runtime/lua/vim/lsp.lua#L2323-L2330) (one vs zero indexing is dealt with in 'mini.completion' in other place).

The suggested approach here is to indeed include `-` in 'iskeyword' option (for example, with `vim.opt.iskeyword:append('-')`), as 'mini.completion' uses keyword to the left of cursor as the base for completion.

**Comment by mortezadadgar** [comment]
@echasnovski this seems to be related https://github.com/neovim/neovim/issues/15784

**Comment by echasnovski** [comment]
Yes, indeed this might be the reason. Seems to complicate things rather severely when there is another good (not perfect, but good enough) solution.

> `.` is not part of `iskeyword` why that trigger completion menu properly

I'd suggest because language server provides proper candidates which respect that dot through cursor position (which also is sent to server).

**Comment by echasnovski** [comment]
> @echasnovski sorry for sending noise to this closed issue, but using `omnifunc` as completion source fixes this issue is there's any tradeoff in using `omnifunc`? and why it's not used by default?

I don't think it should matter, no.

What makes it look like it is fixed? Does shown completion menu definitely come from 'mini.completion' (and not from `vim.lsp.omnifunc()`)?

**Comment by echasnovski** [comment]
I am pretty sure that there shouldn't be any difference between using "omnifunc" and "completefunc" as `source_func`. What it essentially does for completion is [probably auto setup](https://github.com/echasnovski/mini.nvim/blob/f699158e6a654d2778e446d98de2881d7ab1f5fb/lua/mini/completion.lua#L559) and [emulate pressing appropriate keys](https://github.com/echasnovski/mini.nvim/blob/f699158e6a654d2778e446d98de2881d7ab1f5fb/lua/mini/completion.lua#L717).

What does `:echo &omnifunc` show in the buffer prior to getting completion?

**Comment by echasnovski** [comment]
Hmmm... I am clueless at this point. Need to look into it more.

**Comment by mortezadadgar** [comment]
@echasnovski I can still reliably reproduce this issue just opened a svelte project and typed `w-{number}` in a class
the lsp version: `tailwindcss-language-server 0.14.14-1`

I get irrelevant completion items after typing the width number
![Image](https://github.com/user-attachments/assets/8fef0986-35c0-4a68-b512-c11380e2caec)

**Comment by echasnovski** [comment]
> [@echasnovski](https://github.com/echasnovski) I can still reliably reproduce this issue just opened a svelte project and typed `w-{number}` in a class
> the lsp version: `tailwindcss-language-server 0.14.14-1`

Let's first make sure that you indeed use latest `main`. Could you navigate to the installed version of 'mini.nvim' (or standalone 'mini.completion') and look at 'lua/mini/completion.lua' file? Does it contain [these lines](https://github.com/echasnovski/mini.nvim/blob/a8b1d74f45dadf3554c0eed784c6ccd8ade67883/lua/mini/completion.lua#L1767-L1770)?

**Comment by mortezadadgar** [comment]
> > [@echasnovski](https://github.com/echasnovski) I can still reliably reproduce this issue just opened a svelte project and typed `w-{number}` in a class
> > the lsp version: `tailwindcss-language-server 0.14.14-1`
> 
> Let's first make sure that you indeed use latest `main`. Could you navigate to the installed version of 'mini.nvim' (or standalone 'mini.completion') and look at 'lua/mini/completion.lua' file? Does it contain [these lines](https://github.com/echasnovski/mini.nvim/blob/a8b1d74f45dadf3554c0eed784c6ccd8ade67883/lua/mini/completion.lua#L1767-L1770)?

This is only installation of `mini.completion` i have inside `.local/share/nvim/site/pack`, and it does include those lines
![Image](https://github.com/user-attachments/assets/8e753685-e4be-47b1-9259-6e16f6be3a93)
