### ISSUE TITLE
Jump to next/previous cursorword match

### ISSUE THREAD

**Issue by waynerv** [echasnovski/mini.nvim#531]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

cursorword

### Description

Is there any chance to implement jumping to the next/previous matching word by pressing keys like Alt+n/p? This is a very practical feature.

**Comment by waynerv** [comment]
Maybe just using  */# is enough.

**Comment by echasnovski** [comment]
Thanks for suggestion!

> Maybe just using */# is enough.

Yes, that's what I'd recommend using here.

Closing as not planned.
