### ISSUE TITLE
mini.completion: different completion candidates compared to omnifunc

### ISSUE THREAD

**Issue by mortezadadgar** [echasnovski/mini.nvim#533]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

Hey me again,
it's easily reproducible on the last issue i have sent https://github.com/echasnovski/mini.nvim/issues/530
just open a opening html tags and write `<di` and i get this menu
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/07fe3422-5f27-4d66-9c7a-84465f151939)
omnifunc only showing can
![image](https://github.com/echasnovski/mini.nvim/assets/27911493/2b65fa34-fa9c-4185-9166-c4780394dbb3)
my understanding is that mini.completion is showing candidates from typescript as well as svelte lsp while omnifunc know its context 

### Neovim version

NVIM v0.9.4

### Steps to reproduce

same as https://github.com/echasnovski/mini.nvim/issues/530

### Expected behavior

only show html completions

### Actual behavior

unrelated candidates to current text context

**Comment by echasnovski** [comment]
Does adding `<` to 'iskeyword' help here?

Sorry, I am not really keen on installing whole svelte tech stack to verify this.

**Comment by echasnovski** [comment]
> @echasnovski doing that break lsp completion and fallback to `fallback_action`

Hm, yeah, probably because candidates in list don't start with `<` so all of them got filtered out.

------

Do `dialog` and `div` indeed come from `lspconfig.tailwindcss.setup({})` and the rest is from `lspconfig.svelte.setup({})`? The most full proof way to check this is to disable each of them and see the list of candidates.

**Comment by echasnovski** [comment]
When do you press `<C-x><C-o>` to invoke 'omnifunc' (set to `vim.lsp.omnifunc`) in the original example? Is it after `<di`? If yes, could you try to press it after `<`?

Judging by the animation, first time 'mini.completion' provides results right after `<` and then filters them down. The second time it might be called at `<di`.

To see what list 'mini.completion' provides at certain points, set high delay (`MiniCompletion.config.delay.completion = 1000000`) and press `<C-Space>` after entering `<`, `<d`, and `<di`. If results are the same as with `vim.lsp.omnifunc`, then everything is fine.

**Comment by echasnovski** [comment]
> Yes but that's not actually fine
> 
> now I'm closing this issue as it will be closed anyway by you as expected/by-design decision

Not exactly because of that, but because those results seem to come from language server and completion plugin has nothing to do with this.
