### ISSUE TITLE
Multiple mappings

### ISSUE THREAD

**Issue by 9mm** [echasnovski/mini.nvim#534]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

hey,

I was wondering if there was a way to have multiple mappings?

I have muscle memory depending on the action I'm taking, where I will use both `<C-l>` and `<CR>` depending, and I wont both to be `go_in_plus` instead of one being `go_in`

```lua
        mappings = {
          go_in = '',
          go_in_plus = { '<C-l>', '<CR>' },
          go_out = '',
          go_out_plus = '<C-h>',
        }
```

**Comment by echasnovski** [comment]
Thanks for the question!

Yes, there is, inside custom autocommand for `MiniFilesBufferCreate` event. For more examples, take a look at #409.
