### ISSUE TITLE
Line number out of range

### ISSUE THREAD

**Issue by MariaSolOs** [echasnovski/mini.nvim#536]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.hippatterns

### Description

When deleting the entire code in a buffer, an out of range error coming from this plugin appears.

### Neovim version

v0.10.0-dev-1400+gbc850ba2a

### Steps to reproduce

1. Inside an empty lua file write the following code in the first (and only) line: `local foo = 0`.
2. Return to normal mode, and delete the code with `Vd`.

### Expected behavior

For there to be no errors when deleting text.

### Actual behavior

The following error appears:

<img width="1159" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/62502207/dd0fd788-e3d3-46cb-a434-d35a71947976">

**Comment by echasnovski** [comment]
Thanks for the issue!

Should be now fixed on the `main` branch (of 'mini.nvim').

(Tale as old as writing programs: introduced an issue while solving another issue).

**Comment by MariaSolOs** [comment]
@echasnovski thank you for the quick fix!
