### ISSUE TITLE
mini.pick documentation typo on '$'

### ISSUE THREAD

**Issue by fightingdreamer** [echasnovski/mini.nvim#540]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Probably a documentation typo, cause `actual behaviour` feels more correct/regex'ish.

### Neovim version

0.9.4

### Steps to reproduce

1. cd to directory with `*.lua` files
2. `:Pick files`
3. Type `$.lua` -> no results
4. Type `.lua$` -> many results

### Expected behavior

From `mini.pick` documentation: `If query starts with $, the match is exact at end`.

### Actual behavior

Actual behaviour `If query ends with $, the match is exact at end`.

**Comment by echasnovski** [comment]
Thanks for noticing this!

Yes, indeed, that is a typo. I'll fix it tomorrow.

**Comment by echasnovski** [comment]
This should be now fixed on latest `main`.
