### ISSUE TITLE
mini.files window is cleared when entering insert mode

### ISSUE THREAD

**Issue by MariaSolOs** [echasnovski/mini.nvim#544]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When inside a folder that contains a single entry, typing `o` results in the single entry to be removed (at least according to the UI).

### Neovim version

v0.10.0-dev-1425+gd2e7cc68e

### Steps to reproduce

1. Create a new folder called `foo`, inside it create another folder called `bar`, and inside `bar` create `bar.txt`.
2. Add the following configuration in `foo/config.lua`:
```lua
local install_path = vim.fn.fnamemodify('plugins/minifiles', ':p')

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({
    'git',
    'clone',
    '--depth=1',
    'https://github.com/echasnovski/mini.files',
    install_path,
  })
end
vim.opt.runtimepath:append(install_path)

local minifiles = require('mini.files')

minifiles.setup()
vim.keymap.set('n', '<C-e>', function()
  minifiles.open()
end, {})
```
3. Inside `foo` run `nvim --clean -u config.lua`.
4. Type `<C-e>` to open the `mini.files` explorer, go inside `foo`, and while the cursor is on `foo.txt` type `o`.

### Expected behavior

(Following my example above) For `foo.txt` to still be listed after pressing `o`.

### Actual behavior

`foo.txt` is gone.

<img width="1135" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/62502207/1a134b12-b78b-4796-a3c9-b6ec15fb5825">

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce this on `NVIM v0.10.0-dev-82b1a38` (latest Nightly). Neither with my usual config, nor with this repro. Judging by the version, it is built from source, right? Could you, please, check on latest Nightly build?

That said, there were recently some changes in core to how `o` works but I don't think they should matter here. The behavior described here is something that [explicitly dealt with](https://github.com/echasnovski/mini.nvim/blob/f699158e6a654d2778e446d98de2881d7ab1f5fb/lua/mini/files.lua#L1790-L1795).

**Comment by MariaSolOs** [comment]
Oh okay, I cannot reproduce this with the tippy-top of `master` anymore. I'll close this then.

Out of curiosity, which are the changes in core that you were referring to?

**Comment by echasnovski** [comment]
> Out of curiosity, which are the changes in core that you were referring to?

neovim/neovim#25808 which is a fix for the fix of the issue I opened in Vim :sweat_smile: 

Plus I noticed that some screenshot tests related to `o` have some change in cursor position view.
