### ISSUE TITLE
mini.files: Allow customizing current line highlight

### ISSUE THREAD

**Issue by JulesNP** [echasnovski/mini.nvim#545]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Is it possible to add a customizable highlight group for the current line in mini.files, similar to to the `MiniPickMatchCurrent` highlight group in mini.pick?

Some colorschemes such as gruvbox use the same shade for both `CursorLine` and `NormalFloat`, and I'd rather not change my cursorline color everywhere else as a workaround.

Example:
![image](https://github.com/echasnovski/mini.nvim/assets/44929900/68a1baf4-a696-495b-abc3-ce08ad7c2669)

**Comment by echasnovski** [comment]
Thanks for the issue!

Or should I say reminder because I wanted to add this (specifically because of this reason) but forgot. Now it will be harder to forget with an actual issue :)

**Comment by echasnovski** [comment]
This is now possible on `main` branch with `MiniFilesCursorLine` highlight group. Thanks again for the suggestion!
