### ISSUE TITLE
[Mini.Map] add search integration highlight for pure scrollbar.

### ISSUE THREAD

**Issue by bassamsdata** [echasnovski/mini.nvim#546]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Mini.Map

### Description

firstly, i want to express my gratitude for creating these awesome modules.

I'm currently relying on Mini.Map for various functions, mainly as a pure scrollbar. However, I find myself missing the integration with the search feature, especially when dealing with larger files. It would be immensely helpful to have some form of indicator or highlighting for search results within the Mini.Map pure scrollbar.

I noticed in the documentation that Mini.Map is compared with the `Satellite.nvim` plugin. Is there a way to achieve something similar for search integration, where search results are indicated by dots or small dashes?

On another note, I'm also using the `WindowsMaximize` function from `Mini.Misc`, but it seems that `Mini.Map` doesn't work when the window is maximized. Is there a way to make Mini.Map work even when the window is maximized, or does this concept go against the intended purpose of the maximize feature? :)

this is how I cconfigured minimap

```lua
local ok, map = pcall(require, "mini.map")
if not ok then
  return
end

if map then
  vim.api.nvim_create_autocmd("BufEnter", {
    callback = function()
      if vim.api.nvim_buf_get_name(0) ~= "starter" then
        map.open()
      end
    end,
  })
  -- refresh on window resize
  vim.api.nvim_create_autocmd("VimResized", {
    callback = function()
      map.refresh()
    end,
  })
end

```
thanks again for your help.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> I'm currently relying on Mini.Map for various functions, mainly as a pure scrollbar. However, I find myself missing the integration with the search feature, especially when dealing with larger files. It would be immensely helpful to have some form of indicator or highlighting for search results within the Mini.Map pure scrollbar.
> 
> I noticed in the documentation that Mini.Map is compared with the `Satellite.nvim` plugin. Is there a way to achieve something similar for search integration, where search results are indicated by dots or small dashes?

'mini.map' has the concept of [integrations](https://github.com/echasnovski/mini.nvim/blob/9b379d3bb8aac34015f27acd0e981d67e334ab12/doc/mini-map.txt#L190-L191) which are not configured by default. There are also several [integration generators](https://github.com/echasnovski/mini.nvim/blob/9b379d3bb8aac34015f27acd0e981d67e334ab12/doc/mini-map.txt#L614-L701) exported with it (including for built-in search).

Unfortunately for pure scrollbar case, those add highlights only for the map part. The suggested compromise here is to use small `window.width` and show minimum of map content.

> On another note, I'm also using the `WindowsMaximize` function from `Mini.Misc`, but it seems that `Mini.Map` doesn't work when the window is maximized. Is there a way to make Mini.Map work even when the window is maximized, or does this concept go against the intended purpose of the maximize feature? :)

I assume you mean [`MiniMisc.zoom()`](https://github.com/echasnovski/mini.nvim/blob/9b379d3bb8aac34015f27acd0e981d67e334ab12/doc/mini-misc.txt#L268). Then yes, it is possible to show map on top of it by adjusting its [config.zindex](https://github.com/echasnovski/mini.nvim/blob/9b379d3bb8aac34015f27acd0e981d67e334ab12/doc/mini-map.txt#L222-L223).

------

So I would suggest here to add the following setup after `if map then` line:
```lua
  local map = require('mini.map')
  local gen_integr = map.gen_integration
  map.setup({
    integrations = { gen_integr.builtin_search(), gen_integr.diagnostic(), gen_integr.gitsigns() },
    window = {
      width = 2,
      show_integration_count = false,
      zindex = 1000,
    },
  })

  -- Make `n`, `N`, and `*` refresh map. Not necessarily, but a good quality of life improvement.
  for _, key in ipairs({ 'n', 'N', '*' }) do
    vim.keymap.set('n', key, key .. 'zv<Cmd>lua MiniMap.refresh({}, { lines = false, scrollbar = false })<CR>')
  end
```

**Comment by bassamsdata** [comment]
thank you for the help. didn't come to my mind the z index for minimap :)
I probably write a function to toggle between 1 and 2 for the width. it'd be fun.
thanks again.
