### ISSUE TITLE
Error when canceling surround with `<C-c>`

### ISSUE THREAD

**Issue by DEliasVCruz** [echasnovski/mini.nvim#55]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

Whenever using a surround action other than `add` if the user cancels the surround character input with `<C-c>` instead of `<Esc>` the `getchar()` function returns an error

### Neovim version

NVIM v0.7.0-dev+1292-ge9b53f3fb

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Install `mini.nvim` with `packer`and run setup for `mini.surround`

```lua
  use {
    "echasnovski/mini.nvim",
    config = function()
      require("mini.surround").setup()
    end,
  }
```
3. Position cursor over a word/character/etc
4. Input the characters `sd`
5. Cancel the surround motion with `<C-c>` (Control + c)

### Expected behavior

The surround motion handles the keyboard interrupt input and the motion is aborted without any errors. User continues editing as normal

### Actual behavior

Neovim throws an error and user is forced to pres some key to dismiss the error and continue editing

Error thrown:

```
E5108: Error executing lua Keyboard interrupt
stack traceback:
        [C]: in function 'getchar'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/surround.lua:607: in function 'user_surround_id'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/surround.lua:821: in function 'get_surround_info'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/surround.lua:217: in function <...m/site/pack/packer/start/mini.nvim/lua/mini/surround.lua:215>
```

**Comment by echasnovski** [comment]
Thanks for the good catch! Should be fixed in `main` branch.

By the way, this is the prime example of a perfect issue: everything on point, more than enough information, sticking to the form. Thanks for that!
