### ISSUE TITLE
mini.trailspace: Remove highlighting features in favor of an autocommand option

### ISSUE THREAD

**Issue by yamin-shihab** [echasnovski/mini.nvim#551]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.trailspace

### Description

Right now, all the mini.trailspace module does is allow for the highlighting of trailing whitespace and removal of that and blank lines at the end of a buffer/file, through the use of Lua functions.

I think it would be better if instead the highlighting features be removed, because they can already be done with vanilla (Neo)Vim options: by using `listchars`'s `trail` setting. In addition to that, I'd also think it would be better if, similar to [tidy.nvim](https://github.com/mcauley-penney/tidy.nvim), there would be an option to automatically set up an autocommand to format the file using the Lua functions upon writing the buffer. A command (and maybe keybind) to toggle between this feature being enabled and doing it manually.

BTW thanks for this actually super cool and awesome plugin; I've managed to replace like 15+ plugins with just this one!

**Comment by yamin-shihab** [comment]
Would it be beneficial to add this comparison between mini.trailspace and `listchars` to the module's help file, the same way mini.completion and mini.indentscope does with other similar plugins/implementations?

**Comment by echasnovski** [comment]
> Would it be beneficial to add this comparison between mini.trailspace and `listchars` to the module's help file, the same way mini.completion and mini.indentscope does with other similar plugins/implementations?

I don't think so as it will mostly be the copy of [the first feature entry](https://github.com/echasnovski/mini.nvim/blob/e8a413b1a29f05bb556a804ebee990eb54479586/lua/mini/trailspace.lua#L9-L10).

**Comment by isti115** [comment]
In case someone's just looking for a quick copy-paste solution, here's an example:
```lua
vim.api.nvim_create_autocmd("BufWritePre", {
  group = 'MiniTrailspace',
  callback = function()
    MiniTrailspace.trim()
    MiniTrailspace.trim_last_lines()
  end
})
```

@echasnovski Do you think that it would be worth including this in the docs?

**Comment by echasnovski** [comment]
Although it is a pretty straightforward autocommand, I'd rather leave this to the user.
