### ISSUE TITLE
mini.base16: Hidden window separator caused by the way highlight groups are set

### ISSUE THREAD

**Issue by yamin-shihab** [echasnovski/mini.nvim#552]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.base16

### Description

The window separator character, displayed when `laststatus` is set to not show a status line everywhere, is hidden, because the `WinSeparator` and `VertSplit` highlight groups's foreground and background colors are both set to the same color (`base02`). This is in contrast to mini.hues's `randomhue` not having this issue.

The `VertSplit` highlight group should also not be used because it's deprecated.

Setting `WinSeparator` to the background still doesn't look as good because of the different color of the number line on the left side.

### Neovim version

0.9.4

### Steps to reproduce

1. Use the mini.base16 module with any palette.
2. Set the vim `laststatus` option to something like 3.
3. Open another window in a split, like with `:split` or `:vsplit`.

### Expected behavior

The foreground and background colors of both the `WinSeparator` and `VertSplit` highlight groups should be different, so that the separator in between windows can be visible when using a `laststatus` option that hides the status line in some cases.

The `VertSplit` highlight group should also not be set at all, because it's deprecated according to Neovim's documentation (`:help hl-VertSplit`).

### Actual behavior

Instead, the foreground and background colors of both the `WinSeparator` and `VertSplit` highlight groups are both set to `base02` (according to the source code of the plugin), which leads to the window separator character (default "─") being essentially invisible because both the foreground and background colors are the same.

In addition to that, the `VertSplit` highlight group shouldn't be set, as it's deprecated.

I don't know if this is a bug or a feature; it could be that it's intended to hide the window separator to compensate for the supposed inconsistency of the number line on the left side being displayed with another background color. Here's what it looks like after setting `WinSeparator` to the background:
![Here's what it looks like after setting `WinSeparator` to the background.](https://github.com/echasnovski/mini.nvim/assets/50467323/b72e17a4-34be-45cb-9742-32a2f4561c46)
Maybe this issue can be avoided by disabling the coloration of the number line and instead having it just be the background (which I, myself, would prefer) or by having this fix/feature available as a configurable option. Setting the `LineNr*` highlight groups to the background looks like this:
![Setting the `LineNr*` highlight groups to the background looks like this:](https://github.com/echasnovski/mini.nvim/assets/50467323/9c463537-5d0e-4850-a2d1-1c6300f50f5b)

**Comment by yamin-shihab** [comment]
Damn, that's quite the essay for a problem with a highlight group that could lead to a possible PR fix consisting of a few lines

**Comment by echasnovski** [comment]
Thanks for the issue!

I am aware of this issue and agree with you that it doesn't look as good as 'mini.hues' and your second example (with gutter and window separators having same background as `Normal`). However, 'mini.base16' is set to follow Base16 standard, which [has it this way](https://github.com/chriskempson/base16-vim/blob/3be3cd82cd31acfcab9a41bad853d9c68d30478d/templates/default.mustache#L230).

If any reasonable deviation to be made, it makes sense to have it patch other issues. Like adjusting `FloatBorder` to have the same background color as window itself, etc. I am not yet sure how I feel about making this deviation.

Dropping "VertSplit" is reasonable, but not an issue in itself (as it just one extra highlight group which is not used). It is there to, again, have more in common with 'base16-vim'.

I'll let this be open for a while and think about it.

**Comment by yamin-shihab** [comment]
I guess that would make sense considering the author of that Vim plugin also created Base16 and the Tomorrow themes. The official, albeit somewhat vague, [Base16 style guide](https://github.com/chriskempson/base16/blob/main/styling.md) also does suggests base16-vim as a reference, but not necessarily as a strict set of guidelines.

However there are also other Base16 (Neo)vim plugins like [this one](https://github.com/RRethy/nvim-base16/tree/master) that seem to be more popular (but unofficial) and implement things in a slightly differently way.

**Comment by echasnovski** [comment]
Thanks again for the suggestion, but I think I am going to close this one as not planned. I would like 'mini.base16' to follow upstream Vim color scheme as much as possible.

For minor adjustments there is always a way of overriding highlight groups.
