### ISSUE TITLE
The behaviour of Diagnostics picker is not consistent with other Pickers.

### ISSUE THREAD

**Issue by CeNiEi** [echasnovski/mini.nvim#553]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick, mini.extra, mini.tabline

### Description

When selecting a diagnostic, instead of opening the file (from where the diagnostic originates) in a new tab, it opens the file in the same buffer, which is not consistent with how other pickers work (they open a new tab). 

This causes problem, as when i need to switch the buffer to look at another open file, i loose the file with the error. 

Is this behaviour expected, or is it a bug?

### Neovim version

0.9.4

### Steps to reproduce

```lua
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

local lazypath = vim.fn.stdpath 'data' .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  }
end

vim.opt.rtp:prepend(lazypath)


require('lazy').setup({
  'tpope/vim-sleuth',

  {
    'neovim/nvim-lspconfig',
    dependencies = {
      { 'williamboman/mason.nvim', config = true },
      'williamboman/mason-lspconfig.nvim',

      { 'j-hui/fidget.nvim',       tag = 'legacy', opts = {} },
    },
  },

  { 'echasnovski/mini.nvim',      version = false },

  { "nvim-tree/nvim-web-devicons" },

  { "EdenEast/nightfox.nvim" },

  

}, {})


local servers = {
  rust_analyzer = {},
  hls = {},
  lua_ls = {
    Lua = {
      workspace = { checkThirdParty = false },
      telemetry = { enable = false },
    },
  },
}

local mason_lspconfig = require 'mason-lspconfig'


mason_lspconfig.setup {
  ensure_installed = vim.tbl_keys(servers),
}

mason_lspconfig.setup_handlers {
  function(server_name)
    require('lspconfig')[server_name].setup {
      on_attach =
          function(_, bufnr)
            vim.cmd [[autocmd BufWritePre <buffer> lua vim.lsp.buf.format()]]
          end,

      settings = servers[server_name],
      filetypes = (servers[server_name] or {}).filetypes,
    }
  end
}
require("mini.extra").setup()
require('mini.pick').setup({
  options = {
    use_cache = true
  },
  window = {
    config = function()
      height = math.floor(0.618 * vim.o.lines)
      width = math.floor(0.618 * vim.o.columns)
      return {
        anchor = 'NW',
        height = height,
        width = width,
        row = math.floor(0.5 * (vim.o.lines - height)),
        col = math.floor(0.5 * (vim.o.columns - width)),
        border = 'double',
      }
    end,
  }
})
```

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/52526849/7dded524-9d98-4c2f-b190-29c8030b85d5

**Comment by echasnovski** [comment]
Thanks for the issue!

That's not quite exactly what happens. Neovim has three main abstractions: buffer, window, tabpage. Quoting from `:h windows-intro`:

> Summary:
>     - A buffer is the in-memory text of a file.
>     - A window is a viewport on a buffer.
>     - A tab page is a collection of windows.

What you see as "tabs" are buffers displayed in tabline  with 'mini.tabline'. The thing is, that only listed buffers are shown there (see `:h buflisted`), as that is essentially what that option is designed for.

On the other hand, some language servers and diagnostic providers can scan not only opened buffers, but other files in the project. This leads to some buffers in diagnostic entries to be unlisted. When you such entry, buffer becomes current (visible), but still unlisted (hence not showing in the tabline). If you execute `:edit` or `setlocal buflisted`, it should appear in the tabline.

Still, should not happen and I'll look into it.

**Comment by echasnovski** [comment]
This should now be fixed on the latest `main`.

**Comment by CeNiEi** [comment]
Thanks for the explanation and for the fix. 

And thanks for this awesome library. 👍
