### ISSUE TITLE
Is it possible to have multiple jump commands with MiniJump2D?

### ISSUE THREAD

**Issue by garrett361** [echasnovski/mini.nvim#557]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

MiniJump2D

### Description

Apologies if this is possible and I'm not seeing how to do it: can I set up more than one jumping command with mini jump2d?

That is, I want to do something like
```lua
mini_jump2d.setup({
spotter = mini_jump2d.gen_pattern_spotter("pattern_s"), 
...,
mappings = {
start_jumping = "s",
}
)
```
and then also
```lua
mini_jump2d.setup({
spotter = mini_jump2d.gen_pattern_spotter("pattern_S"), 
...,
mappings = {
start_jumping = "S",
}
)
```
so that I can use `s` and `S`, say, to jump to two different patterns. When I try the above, both `s` and `S` use only the `pattern_S` pattern, rather than `pattern_s` and `pattern_S`, respectively.

**Comment by echasnovski** [comment]
No worries!

'mini.jump2d' exports [`start()`](https://github.com/echasnovski/mini.nvim/blob/8e18eb9ba849d737acac1873cd78fc8058c1700a/doc/mini-jump2d.txt#L255) function which can be used with different options inside custom mappings. Here are [examples of how it can be called](https://github.com/echasnovski/mini.nvim/blob/8e18eb9ba849d737acac1873cd78fc8058c1700a/doc/mini-jump2d.txt#L314-L328).

Here is an example of how to make mappings like you want (modify to your liking and add them to your config to make more persistent):
```lua
vim.keymap.set('n', 'S', function() MiniJump2d.start({ spotter = MiniJump2d.gen_pattern_spotter('%S+') }) end)
vim.keymap.set('n', 's', function() MiniJump2d.start({ spotter = MiniJump2d.gen_pattern_spotter('%p') }) end)
```

------

For the future, [Q&A discussions](https://github.com/echasnovski/mini.nvim/discussions/categories/q-a) is a better place to ask questions.

**Comment by garrett361** [comment]
Thank you! Did not know about this feature or the discussion section, thanks for both pointers and the quick response! Love your work
