### ISSUE TITLE
mini.animate not working in AstroNvim

### ISSUE THREAD

**Issue by cherrynoize** [echasnovski/mini.nvim#564]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

I hope this is not a silly request. I was hoping I could have `mini.animate` work out of the box like I did with other plugins in AstroNvim but it just doesn't work. As in, nothing happening (apart from the plugin being installed correctly).

Do you know if I'm doing something wrong?

### Neovim version

0.9.4

### Steps to reproduce

This is the relevant portion in my `init.lua`:

```
setup.mini = require(user_path.."plugins.mini")
...
return {
   options = setup.options,
   mappings = setup.mappings,
   colorscheme = setup.colorscheme,
   plugins = {
...
      {
         'echasnovski/mini.nvim',
         config = setup.mini,
      },
...
   },
...
}
```

And this is the `plugins/mini.lua`:

```
return function()
  require('mini.animate').setup{}
end
```

This is the same I used for other plugins such as `colorizer.nvim` and `alpha.nvim`, but just nothing happens after it completes installing `mini`.

### Expected behavior

Something.

### Actual behavior

Nothing.

**Comment by echasnovski** [comment]
I am not familiar with how AstroNvim works. Two basic steps that are enough to make 'mini.animate' work are:
- Install 'mini.nvim' (or 'mini.animate' separately). That is, download its source code in the appropriate location and make Neovim now about it. Usually plugin manager takes care of this.
- Call `require('mini.animate').setup()`. Either inside config file during startup or manually after Neovim is opened.

My first step towards solving this would be to ensure that `require('mini.animate').setup()` was properly called. This can be done checking in two places:
- Execute `:=type(MiniAnimate)`. If it prints `table`, then OK; anything else - not OK.
- Execute `:au MiniAnimate`. It should print several lines (like containing `MiniAnimate WinScrolled`) indicating that autocommands are set up correctly.

I'll close this as out of scope with an advice to try and ask somewhere with a more concentration of knowledge about AstroNvim than here.
