### ISSUE TITLE
Keep the cursor position after performing a surround action

### ISSUE THREAD

**Issue by amirhhashemi** [echasnovski/mini.nvim#565]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

surround

### Description

[`nvim-surround`](https://github.com/kylechui/nvim-surround) can keep the cursor position after performing a surround action. For example, consider this text:
(`|` represents the cursor)
```html
<h1>hea|ding</h1>
```
After performing a surround action like `srtth2` the cursor moves to the beginning of the surrounded text:
```html
<h2>|heading</h2>
```
However if I do the same thing with `nvim-surround` the cursor position doesn't change:
```html
<h2>hea|ding</h2>
```
Please refer to their docs for more information: https://github.com/kylechui/nvim-surround/blob/cfa2da7f469f1e759f2a961bc25fa4ccfe1795c2/doc/nvim-surround.txt#L612

I find this feature very usefull. Specially, when performing a surround action on multiple lines, the jump is quite distracting for me.

Would you consider adding this feature to `mini.surround`?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I've already considered this and decided to not add this. See [this comment](https://github.com/echasnovski/mini.nvim/issues/191#issuecomment-1373326731) for more details.

Closing as duplicate.
