### ISSUE TITLE
mini.files: copy relative file path

### ISSUE THREAD

**Issue by Isos9** [echasnovski/mini.nvim#567]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Hi,

First, Thank you for the file plugin, coming from nvim-tree, this seems really more intuitive.
Only thing that I saw that would be missing is to copy the relative file path of the file currently highlighted in the file system using mini.files.
I noticed that I often used this functionality with nvim-tree because it's quick to share to members of the team when working on team projects, that would be cool to have a mapping like `gY` to copy that.
So I would like to know first if that might be a functionnality that I can add as a plugin user in mini.file in the configuration? If so, how ?  
If not, does that align with the vision of mini.files to have this kind of feature? if that's the case I'm willing to contribute.

Thanks

**Comment by echasnovski** [comment]
Hi! Yes, this is possible.

There is a [`get_fs_entry()`](https://github.com/echasnovski/mini.nvim/blob/f2b89efbbad1943657e43f474fe308fceb63597e/doc/mini-files.txt#L742) function. It can be used inside buffer-local mapping to set proper text in proper register. Something like this:

```
local yank_relative_path = function()
  local path = MiniFiles.get_fs_entry().path
  vim.fn.setreg('"', vim.fn.fnamemodify(path, ':.'))
end

vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesBufferCreate',
  callback = function(args) vim.keymap.set('n', 'gY', yank_relative_path, { buffer = args.data.buf_id }) end,
})
```

**Comment by Isos9** [comment]
Thank you!

Just made a little change to use the '+' register and added a print to have visual feedback:

```
local yank_relative_path = function()
  local path = MiniFiles.get_fs_entry().path
  vim.fn.setreg('+', vim.fn.fnamemodify(path, ':.'))
  -- Print path yanked
  print(vim.fn.fnamemodify(path, ':.'))
end

vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesBufferCreate',
  callback = function(args)
    vim.keymap.set('n', 'gY', yank_relative_path, { buffer = args.data.buf_id })
  end,
})
```
