### ISSUE TITLE
@function textobjects not working for "rust"

### ISSUE THREAD

**Issue by UtkarshVerma** [echasnovski/mini.nvim#569]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

I'm working on a rust project and I noticed that I could not move between `@function` textobjects.

### Neovim version

0.9.4

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `nvim main.rs`
3. Press `[f` or `]f`.

#### Files
[minimal.lua](https://dpaste.org/UsoQA)
[main.rs](https://dpaste.org/BTKKS)

### Expected behavior

Cursor should move to the previous/next function item.

### Actual behavior

Verbose error is thrown.

```
E5108: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 5163 for language rust
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get_query'
        ...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:99: in function 'available_textobjects'
        ...r-textobjects/lua/nvim-treesitter/textobjects/shared.lua:83: in function 'get_query_strings_from_regex'
        ...ter-textobjects/lua/nvim-treesitter/textobjects/move.lua:32: in function 'move_fn'
        ...ects/lua/nvim-treesitter/textobjects/repeatable_move.lua:61: in function 'move_repeatable'
        ...ter-textobjects/lua/nvim-treesitter/textobjects/move.lua:122: in function <...ter-textobjects/lua/nvim-treesitter/textobjects/move.lua:121>
        ...r-textobjects/lua/nvim-treesitter/textobjects/attach.lua:45: in function <...r-textobjects/lua/nvim-treesitter/textobjects/attach.lua:44>
```

**Comment by echasnovski** [comment]
Judging both by the 'minimal.lua' and error message, this has nothing to do with 'mini.ai'. Both `[f` and `]f` are defined in 'nvim-treesitter/nvim-treesitter-textobjects' (in [these lines](https://dpaste.org/UsoQA#L67,68,69,70)).

Closing as not related to 'mini.nvim'.
