### ISSUE TITLE
mini.starter: Allow to choose an item via indices

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#577]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

As per its README:

> - Choosing an item can be done in two ways:
>   - Type prefix query to filter item by matching its name (ignoring case). Displayed information is updated after every typed character. For every item its unique prefix is highlighted.
>   - Use Down/Up arrows (or <C-n>/<C-p>, or <M-j>/<M-k>) and hit Enter.

I presume that a great majority of people who are using this module come from https://github.com/mhinz/vim-startify/ and are used to choosing items by index — Each item has an index and the user can simply enter the corresponding key.

Therefore I propose adding an additional, optional method which could replace the first one mentioned above in the quote for the people who prefer it.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Having this as separate way to choose an item does not fit the overall query design. If user wants to use numbers to choose an item, there are at least two options:
- Manually adding number prefix if that is for a fixed item. 
- Using [`gen_hook.indexing()`](https://github.com/echasnovski/mini.nvim/blob/05f4a49cd85a67b90328a1bcbae4d9ed2a0a417b/doc/mini-starter.txt#L427) to automatically prepend an index for generated items (like recent files, etc.).

Also, here is a [configuration similar to 'vim-startify'](https://github.com/echasnovski/mini.nvim/blob/05f4a49cd85a67b90328a1bcbae4d9ed2a0a417b/doc/mini-starter.txt#L86-L104).

Closing as not planned.

**Comment by ndavd** [comment]
Thanks!
