### ISSUE TITLE
mini.starter(NIGHTLY NVIM): Doesn't properly update when downsizing

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#578]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

Looks like it's not refreshing properly when resizing the window down.

### Neovim version

NVIM v0.10.0-dev-1603+gac1113ded

### Steps to reproduce

Just setup mini.starter with default config and scale the window up and then down.

### Expected behavior

- The screen should update properly

### Actual behavior

- It does not:
![image](https://github.com/echasnovski/mini.nvim/assets/74260683/05974a1d-9c76-4264-abbe-fb611badb63e)

**Comment by echasnovski** [comment]
Thanks for the issue.

I can reproduce. This doesn't happen on Neovim 0.9.4, though. And judging by the effects, it seems to be some issue with Nightly. I'll look into it.

**Comment by ndavd** [comment]
Perfect, thanks!

**Comment by echasnovski** [comment]
I believe the root cause here is neovim/neovim#26139. There is a fix here, but it would lead to flickering on resize. As it is not a frequent event, it is acceptable, but we'll wait a bit for that to resolve.

**Comment by echasnovski** [comment]
As upstream issue is fixed, I can no longer reproduce it *on latest Nightly* and it seems to be fixed. Apart from query message disappearing (if was shown) after resize, but that is more or less aligned with not showing message on startup. Note for future: if want to fix that, wrap `refresh`  call [here](https://github.com/echasnovski/mini.nvim/blob/05f4a49cd85a67b90328a1bcbae4d9ed2a0a417b/lua/mini/starter.lua#L1292) in`vim.schedule`. Right now this seems like an unnecessary change.
