### ISSUE TITLE
mini.starter: Add method for coloring text in the screen

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#579]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

Problem: The text in the starter screen is all the same color.
Solution: A method that we could call to color content for the screen. It would take in a string and output the colored text, as for which colors specifically I don't know, ideally it would take in any color, but realistically if we were able to pick from a set of them (out of mini's theme) it would be equally great.

**Comment by echasnovski** [comment]
Thanks for your interest in 'mini.starter'!

I'll see if this can be done relatively easily with current code. If not, then probably it won't happen. We'll see.

**Comment by ndavd** [comment]
Thanks!

**Comment by echasnovski** [comment]
I've taken another look and I don't think there is a good way to do that, unfortunately (would be cool, though).

Closing as not planned.
