### ISSUE TITLE
MiniCompletion: Any negative consequences in using `autocmd! MiniCompletion InsertCharPre *` to disable auto-popup?

### ISSUE THREAD

**Issue by da99** [echasnovski/mini.nvim#58]
I wanted to use MiniCompletion with the default config. There was just one change: prevent the pop-up menu  opening while typing. I know increasing the delay to a very high number is possible. I decided to go another way  and disable just one of the autocmds in the MiniCompletion group:

```lua
   require('mini.completion').setup({})
   vim.cmd('   autocmd! MiniCompletion InsertCharPre *  ')
```

Everything works great: No more automatic pop-ups while I type. I can still use `<C-Space>` for that lovely, elegant two-stage completion (thanks to echasnovski). Are there any negative consequences to disabling  that one `InsertCharPre` autocommand?

**Comment by echasnovski** [comment]
With current implementation, it doesn't seem like there will be negative consequences to other 'mini.completion' functionalities. However, this type of disabling is not "officially" supported and tested. The way to do it is like you said: set very high value to `config.delay.completion`. It doesn't seem like it is adding that much of an overhead on every `InsertCharPre`, if that is your concern.
