### ISSUE TITLE
mini.pick: Side previews (telescope style)

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#580]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

It would be nice if we could have side previews in pickers as opposed to the Tab ones. Not actually for an aesthetic reason, but because it's useful to preview as we're scrolling through several files. Making it easier to find what we're looking for.

**Comment by ndavd** [comment]
Closing this as I think I'm getting used to the new flow. It's 1 floating window for everything.

**Comment by echasnovski** [comment]
Yes, this is not planned.

You can scroll when preview is visible with `<C-f>`/`<C-b>` (with default mappings) and go to next/previous item with `<C-n>`/`<C-p>` while keeping preview.
