### ISSUE TITLE
mini.pick: Add options to customize prompt cursor format and prompt prefix string

### ISSUE THREAD

**Issue by ndavd** [echasnovski/mini.nvim#581]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Two new options:
- `prompt_cursor_format` string (vertical, horizontal, full, etc.)
- `prompt_prefix` string

It would be great to have these options, specially if per picker, because then someone might want to customize the prompt in certain pickers.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I am not a huge fan of adding many options and 'mini.pick' already has a lot. I'll think about it.

**Comment by echasnovski** [comment]
As in code both prompt cursor and prefix are used in a single line without (hopefully) any other major consequences, I decided to go ahead and add `window.prompt_cursor` and `window.prompt_prefix` options. So this should now be available on latest `main`.

Thanks again for the suggestion!

**Comment by ndavd** [comment]
Awesome, thanks!

**Comment by echasnovski** [comment]
@ndavd, a heads up. The `window.prompt_cursor` is renamed to `window.prompt_caret` for better consistency with other parts of config and help page. You can see more details in 7f44bca7c6f6d79185371f9187ead060eff40276 message.

**Comment by ndavd** [comment]
Hey, thanks a lot for letting me know! @echasnovski
