### ISSUE TITLE
mini.files: Allow creating files or directory in one line

### ISSUE THREAD

**Issue by mortezadadgar** [echasnovski/mini.nvim#582]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Just like the way linux command shell works for example `mkdir {1,2/1.text}` makes two directory and a file inside one of them

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think that current functionality is enough. Your example would require creating two lines: `1/` and `2/1.text`. Which is quite comparable even in number of strokes.

Closing as not planned.
