### ISSUE TITLE
mini.bracketed add option to jump to next/prev equal indent

### ISSUE THREAD

**Issue by gerazov** [echasnovski/mini.nvim#590]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.bracketed

### Description

Great plugin :sunglasses: 

I've been relying on [jeetsukumaran/vim-indentwise](https://github.com/jeetsukumaran/vim-indentwise) for the following navigation keymaps:
```lua
vim.keymap.set({"n", "v"}, "<a-m>", "<Plug>(IndentWisePreviousLesserIndent)")
vim.keymap.set({"n", "v"}, "<a-/>", "<Plug>(IndentWiseNextLesserIndent)")
vim.keymap.set({"n", "v"}, "<a-,>", "<Plug>(IndentWiseNextEqualIndent)")
vim.keymap.set({"n", "v"}, "<a-.>", "<Plug>(IndentWisePreviousEqualIndent)")
```
It would be great to be able to do the same navigation using `mini.bracketed`. The only thing missing is `EqualIndent` as an option, which in `vim-indentwise` is defined as:
> Move to next/prev line of same indent as the current line that is separated from the current line by lines of different indents.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think this fits nicely in the current implementation of `indent()` target while still not being common enough for new target. For these situations there is an [`advance()` function](https://github.com/echasnovski/mini.nvim/blob/baf17e6472b0968661dce5daa372251e934da39f/doc/mini-bracketed.txt#L604) exported.

Here is a draft of how I would implement this:

```lua
local make_nextprev_indent = function(advance_to_nonblank, increment)
  return function(cur_lnum)
    -- Correctly process initial blank line
    cur_lnum = advance_to_nonblank(cur_lnum)
    local init_indent = vim.fn.indent(cur_lnum)
    local visited_different_indent = false

    local new_lnum, new_indent = cur_lnum, init_indent
    -- Check with `new_lnum > 0` because `nextnonblank()` returns -1 if line is
    -- outside of line range
    while new_lnum > 0 do
      new_indent = vim.fn.indent(new_lnum)
      visited_different_indent = visited_different_indent or new_indent ~= init_indent
      if new_indent == init_indent and visited_different_indent then return new_lnum end
      new_lnum = advance_to_nonblank(new_lnum + increment)
    end
  end
end

local indent_same = function(direction)
  local iterator = {
    next = make_nextprev_indent(vim.fn.nextnonblank, 1),
    prev = make_nextprev_indent(vim.fn.prevnonblank, -1),
    state = vim.fn.line('.'),
  }
  local res_line_num = MiniBracketed.advance(iterator, direction, { wrap = false })
  if res_line_num == nil then return end

  -- Navigate to the first non-blank character of the target line
  vim.api.nvim_win_set_cursor(0, { res_line_num, 0 })
  vim.cmd('normal! zv^')
end

vim.keymap.set({ 'n', 'x' }, '<a-.>', function() indent_same('forward') end, { desc = 'Forward same indent' })
vim.keymap.set({ 'n', 'x' }, '<a-,>', function() indent_same('backward') end, { desc = 'Backward same indent' })
```

Closing as not planned.
