### ISSUE TITLE
how to disable mini.paris when recording or playing macros

### ISSUE THREAD

**Issue by konosubakonoakua** [echasnovski/mini.nvim#593]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

add an option to disable mini.pairs when recording or playing macro

**Comment by konosubakonoakua** [comment]
```lua
vim.api.nvim_create_autocmd({ "RecordingEnter" }, {
  group = augroup("disable_minipairs_when_using_macro"),
  callback = function(event)
    vim.g.minipairs_disable = true
    vim.notify("minipairs disabled")
  end,
})
-- this only works for recording
-- how can we disable minipairs also on playing?
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

My advice would be to press `<C-v>` prior to any pair-specific character if you want it to be inserted literally.

If you don't want to do that, having this type of autocommand is the way to go. But don't forget to  also reenable pairs on `RecordingLeave` event. As to how disable them on replaying, there is no event for that (yet, see neovim/neovim#24565).

Closing as not planned.

**Comment by konosubakonoakua** [comment]
https://github.com/windwp/nvim-autopairs/blob/0f04d78619cce9a5af4f355968040f7d675854a1/lua/nvim-autopairs.lua#L173

Thank you, found something in another repo.

**Comment by richin13** [comment]
> [windwp/nvim-autopairs@`0f04d78`/lua/nvim-autopairs.lua#L173](https://github.com/windwp/nvim-autopairs/blob/0f04d78619cce9a5af4f355968040f7d675854a1/lua/nvim-autopairs.lua#L173)
> 
> Thank you, found something in another repo.

@echasnovski hello, I've tried with the approach linked by @konosubakonoakua and it works quite good, would you re-consider this feature?

**Comment by echasnovski** [comment]
> I tried with something as simple as:

Having this logic inside `H.is_disabled()` is an interesting and reasonable approach. However, I do still stand by "My advice would be to press `<C-v>` prior to any pair-specific character if you want it to be inserted literally.".

**Comment by konosubakonoakua** [comment]
> > I tried with something as simple as:
> 
> Having this logic inside `H.is_disabled()` is an interesting and reasonable approach. However, I do still stand by "My advice would be to press `<C-v>` prior to any pair-specific character if you want it to be inserted literally.".

I'm using `<C-v>` as well now.
