### ISSUE TITLE
Emacs like search file buffer for mini.pick

### ISSUE THREAD

**Issue by iamevie** [echasnovski/mini.nvim#595]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

I'd love there to be a way to customize/ theme mini.pick for it to look like the Emacs search buffer.

![Emacs file pickers output looks somewhat like ls -l in a bottom drawer like buffer.](https://github.com/echasnovski/mini.nvim/assets/99840003/d65023be-b668-4244-a7ff-0b9e1a28025e)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is certainly possible. Take a look at [how source can be defined](https://github.com/echasnovski/mini.nvim/blob/964fab7fecd14f66a69a96162f8aa816480690fd/doc/mini-pick.txt#L210). In this particular case the easiest approach would be to precompute items yourself (maybe based on some CLI tool) and modify `choose` (and maybe `preview`).

If you want it to be a file explorer (that is, show also directories and navigate inside them on choosing), that would be a harder task. There is a [`pickers.explorer`](https://github.com/echasnovski/mini.nvim/blob/964fab7fecd14f66a69a96162f8aa816480690fd/doc/mini-extra.txt#L287) picker in 'mini.extra' to have a similar feel (but showing only basename without extra information). Or just use ['mini.files'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-files.md) :)

Closing as not planned, as this is likely won't be built-in.
