### ISSUE TITLE
mini.pick/mini.extra: picker for sessions

### ISSUE THREAD

**Issue by zahidislm** [echasnovski/mini.nvim#598]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick, mini.sessions, mini.extra

### Description

New picker:

- `MiniExtra.pickers.sessions`

I'm aware a `vim.ui.select` implementation exists in `mini.sessions` which `mini.pick` can override with its builtin implementation, but it would be nice to get a better looking one with icons, etc which would also available for those who do not have `mini.sessions` installed.

Specifically, for my intended use case, I wanted to use custom mappings for `mini.sessions` to invoke `MiniSessions.delete` from the picker itself.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> ... but it would be nice to get a better looking one with icons, etc ...

I am not sure which icons are we talking about? I'd assume all entries would have the same icon. Do you have something else in mind?

> ... which would also available for those who do not have `mini.sessions` installed.

Again, not really sure how that would work. The whole idea of 'mini.sessions' is that it stores sessions at particular paths which it knows about. Without it, how would potential `MiniExtra.pickers.session` know where to look for session files (and how the look, even)?

> Specifically, for my intended use case, I wanted to use custom mappings for `mini.sessions` to invoke `MiniSessions.delete` from the picker itself.

That is somewhat already possible with `MiniSessions.select()` as it [takes `action` argument](https://github.com/echasnovski/mini.nvim/blob/964fab7fecd14f66a69a96162f8aa816480690fd/doc/mini-sessions.txt#L207) to perform when choosing a session.
