### ISSUE TITLE
highlight words in all visible buffers

### ISSUE THREAD

**Issue by kaiphat** [echasnovski/mini.nvim#601]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

cursorword

### Description

highlight words in all visible buffers

**Comment by echasnovski** [comment]
Sorry, this is out of scope for 'mini.cursorword'. You can use `*` to highlight (and search) for current word.

Closing as not planned.
