### ISSUE TITLE
Resume latest picker with content

### ISSUE THREAD

**Issue by mvllow** [echasnovski/mini.nvim#603]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Perhaps this is out of scope, but a common hiccup I encounter is:

1. Start a picker, e.g. `:Pick grep_live`
2. Search for text
3. Close the picker
4. Muscle memory leads me to use my keymap for `:Pick grep_live` before realising I wanted to resume instead
5. Close the picker
6. Resume via `:Pick resume` which understandably resumes the empty session now

I would love if a picker is only marked as resumable if some input was given. Hope that makes sense! Thank you for the stellar plugin :)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

To be honest, I feel you. Not very often, but something similar happens to me also.

And yes, I don't think this fits overall design. It *could* track two latest pickers (one "true latest" and one "latest with at least some user input"), but that will severely increase memory usage (which is already unreasonably high for big pickers which needed to be resumed).

I'll think about it a bit.

**Comment by echasnovski** [comment]
Indeed, after thinking about it for a bit longer, I don't this feature meets the "features - maintenance" trade-off.

Closing as not planned.
