### ISSUE TITLE
Request for plugin/package manager module

### ISSUE THREAD

**Issue by yamin-shihab** [echasnovski/mini.nvim#605]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.plug

### Description

Most Neovim setups that would include plugins manage them via a plugin/package manager, mainly to ease setup, installation, and synchronization. Popular Lua plugin managers such as [lazy.nvim](https://github.com/folke/lazy.nvim) and [packer.nvim](https://github.com/wbthomason/packer.nvim) exist, but they seem to be too complex. Plugin managers like [paq-nvim](https://github.com/savq/paq-nvim) however, are much simpler (quite a bit of features for only around 500 lines of code). I think it would be beneficial if mini.nvim were to implement some form of a simple plugin/package manager that can be used to keep itself updated, along with maybe some other plugins.

In addition, a lazy-loading feature could be skipped, similar to what paq-nvim does, as plugins can be made optional and be `:packadd`-ed later on through the use of an autocommand or keybind. 

Thanks

**Comment by ElectronSutra** [comment]
Moving us ever closer to the future where the complete neovim setup to have everything you want in the whole world ends up being

```lua
require("mini.everything")
```

**Comment by echasnovski** [comment]
> Moving us ever closer to the future where the complete neovim setup to have everything you want in the whole world ends up being
> 
> ```lua
> require("mini.everything")
> ```

Yep, something like this is the goal here.

**Comment by echasnovski** [comment]
@yamin-shihab, @ElectronSutra, well this took a bit longer than couple of weeks (for various reasons), but we'll there. The ['mini.deps'](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-deps.md) module is now a part of 'mini.nvim'. Check it out and leave your feedback in #689.

**Comment by yamin-shihab** [comment]
Sweet!
