### ISSUE TITLE
Conflict between mini.animate scrolling effect and vim-cool clearing search highlights on cursor move

### ISSUE THREAD

**Issue by gitaarik** [echasnovski/mini.nvim#611]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

I'm using `mini.animate` for enabling smooth scrolling in Nvim. I also use a plugin [vim-cool](https://github.com/romainl/vim-cool) which clears search highlights when you move the cursor.

When I search for a pattern, then press "n" to go to the next result, and the next result is so far below that mini.animate will trigger a scrolling effect, then the search results are not highlighted anymore.

The problem is that I think that `mini.animate` actually moves the cursor, simulating the scrolling effect, I guess. But that clears the search highlight unintended. See the screen recording below.

![mini-animate-vim-cool](https://github.com/echasnovski/mini.nvim/assets/2470302/b078788a-114b-4b91-95e6-2395eeeb8b12)

Now I figured I could use the `MiniAnimateDoneScroll` event to execute `set hlsearch` when the scroll is done. Like this:

```lua
vim.api.nvim_create_autocmd("User", {
	pattern = "MiniAnimateDoneScroll",
	callback = function()
		vim.defer_fn(function()
			vim.cmd("set hlsearch")
		end, 0)
	end,
})
```

And that actually works (note that the `defer_fn` is necessary), but now the problem is that this is always executed after each scroll animation. And I only want to `set hlsearch` when I was actually searching, not when I scroll manually with `<Ctrl-D>` for example.

So I thought maybe I can save the current hlsearch state before the animation starts. But there doesn't seem to be an event for that. Does anybody have an idea or suggestion for this?

**Comment by echasnovski** [comment]
Yes, both [scroll and resize animations are done with side effects](https://github.com/echasnovski/mini.nvim/blob/c87d3b73d763d4222cdef19323e6a2c4bee33013/doc/mini-animate.txt#L38-L43). And yes, scroll animation actually moves cursor to show smoother cursor transition. Plus sometimes it is necessary to move cursor to show intermediate window view, as only view which contains cursor can be set.

The solution of this issue can be something along the line of [this suggestion](https://github.com/echasnovski/mini.nvim/blob/c87d3b73d763d4222cdef19323e6a2c4bee33013/doc/mini-animate.txt#L277-L292) for `n` keymap which centers current line and opens folds.

Closing as scroll and resize animation indeed need extra work to play nicely with other plugins/functionality (if at all possible).

**Comment by gitaarik** [comment]
Ok, I managed to make it work with these keybindings:

```lua
return {
  general = {
    n = {
      ["n"] = { "<cmd>let g:search_in_progress=1<cr>n", "Next search result" },
      ["*"] = { "<cmd>let g:search_in_progress=1<cr>*", "Search next match of word where cursor is" },
      ["<S-n>"] = { "<cmd>let g:search_in_progress=1<cr>N", "Prev search result" },
    },
  },
}
```

And then I check the `g:search_in_progress` variable before I do `set hlsearch`:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "MiniAnimateDoneScroll",
  callback = function()
    vim.defer_fn(function()
      if vim.g.search_in_progress == 1 then
        vim.cmd("set hlsearch")
        vim.g.search_in_progress = 0
      end
    end, 0)
  end,
})
```

Thanks for your suggestion!

**Comment by olistrik** [comment]
@gitaarik The problem with this is if a scroll does *not* occur, then the autocmd never fires to clear `search_in_progress`. 

If I perform a movement that clears `hlsearch` without scrolling, then the next scroll event will re-enable highlighting even though it shouldn't have.

What we really need is a before and after callback on the scroll event we can disable hlsearch plugins while a scroll is in progress.  Or alternatively, restore `hlsearch` to whatever it was before a scroll began. 

I've tried hooking on the `WinScrolled` event to do this, but `MiniAnimateDoneScroll` doesn't _always_ fire after `WinScrolled`, I'm guessing in cases of single line movements where no animation is necessary. 

The best I've got so far is to debounce my `auto_hlsearch`:

```lua
            local hlsearch_timer = vim.uv.new_timer()

            vim.on_key(function(char)
              if vim.fn.mode() == "n" then
                local new_hlsearch = vim.tbl_contains({ "<CR>", "n", "N", "*", "#", "?", "/" }, vim.fn.keytrans(char))

                if hlsearch_timer:get_due_in() ~= 0 then
                  if new_hlsearch then
                      hlsearch_timer:again()
                  end
                  return
                elseif new_hlsearch then
                    hlsearch_timer:start(260, 0, function() end)
                end

                if vim.opt.hlsearch:get() ~= new_hlsearch then
                  vim.opt.hlsearch = new_hlsearch
                end

              end
            end, vim.api.nvim_create_namespace "auto_hlsearch")
```

This still has edge cases though.

**Comment by olistrik** [comment]
Oh damn, it's much easier than that. The `MiniAnimate.is_active()` function is all that's needed:

```lua
vim.on_key(function(char)
  if vim.fn.mode() == "n" then
    local new_hlsearch = vim.tbl_contains({ "<CR>", "n", "N", "*", "#", "?", "/" }, vim.fn.keytrans(char))
    if vim.opt.hlsearch:get() ~= new_hlsearch then
      if new_hlsearch or not MiniAnimate.is_active("scroll") then
        vim.opt.hlsearch = new_hlsearch
      end
    end
  end
end, vim.api.nvim_create_namespace "auto_hlsearch")
```
