### ISSUE TITLE
'lazy.nvim' doesn't load 'mini.clue' config for standalone plugin

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#612]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue (but perhaps more)

### Description

When I install `mini.clue` as a standalone plugin, it is not working properly (some clues are missing and when opening new file with `:e` it stops working entirely)

### Neovim version

v0.10.0-dev-1506+g610f50dda-Homebrew

### Steps to reproduce

1. `nvim -nu repro.lua`
2. `g`
3. `:e repro.lua`
4. `g`

`repro.lua`:
```lua
print("REPRO")

local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- this works:
-- local plugins = {
--     { 'echasnovski/mini.nvim',
--     version = '*',
--     config = function()
--         local miniclue = require('mini.clue')
--         miniclue.setup {
--             triggers = { { mode = 'n', keys = 'g' } },
--             clues = { miniclue.gen_clues.g() },
--         }
--     end
--     }
-- }

-- this doesn't work:
local plugins = {
    { 'echasnovski/mini.clue',
    version = '*',
    opts = function()
        local miniclue = require("mini.clue")
        miniclue.setup {
            triggers = { { mode = "n", keys = "g" } },
            clues = { miniclue.gen_clues.g() },
        }
    end
    }
}

require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.cmd[[set termguicolors]]
```

### Expected behavior

First `g`:

<img width="950" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/16707112/bccd34c5-d752-4017-a9e4-1756be72d695">

Second `g`:

<img width="950" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/16707112/c4d21e45-020d-4ea7-8046-c7a704557cf8">

### Actual behavior

First `g` (only two clues are shown):

<img width="950" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/16707112/44d80829-2254-4f55-87c2-1b81ab05eb3d">

Second `g` (notice the "g" in the lower bar, no clues are shown):

<img width="950" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/16707112/f6fd9f64-db08-4815-b2f2-9b7e022ea3b3">

**Comment by echasnovski** [comment]
This is not an issue with 'mini.clue', but with how 'lazy.nvim' is used here to call configure 'mini.clues'. In the case of standalone plugin, executing `:=MiniClue` right after first step shows that `require('mini.clue').setup()` is called without supplied `opts`. While with 'mini.nvim' it does.

I this is because 'lazy.nvim' does [special detection of 'mini.nvim'](https://github.com/folke/lazy.nvim/commit/dab6cd50806d6a6b0e8267f628d5fd6b112b151c) which might for some reason not work here.

Using `config` key instead of `opts` key for standalone plugin solves this.

**Comment by simonmandlik** [comment]
Thank you!
