### ISSUE TITLE
[mini.pick] Customize file finder: `bfs` to replace `fd`

### ISSUE THREAD

**Issue by lost22git** [echasnovski/mini.nvim#613]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

as title

**Comment by lost22git** [comment]
In my local tests `bfs` is faster and very low memory usage

![Screenshot 2023-12-15 112405](https://github.com/echasnovski/mini.nvim/assets/65008815/3cd99a09-cb25-44a1-bacc-3c7950b56e88)

bfs:
![Screenshot 2023-12-15 112752](https://github.com/echasnovski/mini.nvim/assets/65008815/135ac012-0fe8-45e5-89c3-2fcc56fdc89a)

fd:
![Screenshot 2023-12-15 112608](https://github.com/echasnovski/mini.nvim/assets/65008815/f6d2122c-9887-474a-9011-99d1def1b8d7)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Using any custom CLI tool as an items source to pick from file system entries can be done with [`builtin.cli()`](https://github.com/echasnovski/mini.nvim/blob/333d2d1090c80ac936b960469a6e93982cbaeb21/doc/mini-pick.txt#L1129). Adding one more built-in source for `builtin.files()`, let alone replacing (even non-default) `fd` is out of scope. And at least at the moment `fd` seems to be much more widespread tool than `bfs`.

Closing as not planned.
