### ISSUE TITLE
CR does not insert new line when completion popup is visible.

### ISSUE THREAD

**Issue by pianocomposer321** [echasnovski/mini.nvim#62]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

When completion is enabled, any time the completion popup is visible, pressing <CR> closes the popup but does not go to the next line. `:imap <CR>` shows nothing.

### Neovim version

NVIM v0.7.0-dev+1376-g973e91007

### Steps to reproduce

minimal.lua:

```lua
vim.api.nvim_command("packadd! mini")
require("mini.completion").setup()
```

1. `nvim -nu minimal.lua`
2. Trigger completion (CTRL-space)
3. Press enter

### Expected behavior

Popup goes away and newline is inserted.

### Actual behavior

Popup goes away, but no newline is inserted.

**Comment by echasnovski** [comment]
That is not really a bug: built-in Neovim (and Vim) completion behaves the same way. As 'mini.completion' is designed to use built-in mechanisms as much as possible, this can indeed be solved only by remapping `<CR>` in Insert mode. In turn, this is a very popular key for mapping in Insert, so early on I decided to not make any such mappings inside plugin.

What I think is more appropriate here, is to document common code snippets used for making these mappings. I did so for `<Tab>` and `<S-Tab>`, but forgot for `<CR>`. So thank you for reminder!
