### ISSUE TITLE
mini.surround | add WhichKey hints to surround>add

### ISSUE THREAD

**Issue by JonatasAmaral** [echasnovski/mini.nvim#620]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

That's a simple one:

When adding a surround in normal mode, it expects to select what thing to wrap around in what's to come
Putting user in a state pretty much like the visual mode, as you can do any text object selection (like `iw`, `3j`, `t)`, etc)

It would be real nice if a that point, WhichKey could show what movements/selection are possible

So one can for example `sa` (WhichKey shows options) `a↓`

That one came up on a [issue on LazyVim](https://github.com/LazyVim/LazyVim/issues/2160), and i think would be really beneficial

**Comment by echasnovski** [comment]
> That's a simple one:

Unfortunately, it is not.

The only way 'mini.surround' can add those kind of hints is to provide specific mappings for all kinds of textobjects (like `saiw`, `sa3j`, etc.), which is not feasible. Other than that, adding custom 'which-key.nvim' hints for Operator-pending mode is not a 'mini.surround' responsibility, I am afraid.

LazyVim already [does have custom hints for 'mini.ai'](https://github.com/LazyVim/LazyVim/blob/879e29504d43e9f178d967ecc34d482f902e5a91/lua/lazyvim/plugins/coding.lua#L210-L253) textobjects. So if you have 'mini.ai' active from LazyVim, you can press `gs` followed by one of `a` or `i` and it should show hints for that subset of textobjects. It is also not really possible to have descriptions for its targets inside of 'mini.ai' itself for reasons described in [this comment](https://github.com/echasnovski/mini.nvim/issues/192#issuecomment-1442020792).

The reason it doesn't already have that for 'mini.surround' seems to be related to folke/which-key.nvim#469.

Closing as not planned.
