### ISSUE TITLE
mini.pairs: Doesn't respect language layout

### ISSUE THREAD

**Issue by va9abond** [echasnovski/mini.nvim#622]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

echasnovski/mini.pairs, lyokha/vim-xkbswitch

### Description

- In `lua` files, when the Russian layout is active, it is impossible to use letters that are on the same key together with '[', ']', '{', '}', \`'\`, \`"\`, '`', '~'
![image](https://github.com/echasnovski/mini.nvim/assets/90098969/f5e71f55-1e9a-474d-8eef-5858d0c35649)

- This strange behavior was noticed in `lua` files, and in the rest (`cpp`, `i3config`, `gitcommit`, `tex`) everything works fine

- **[NOTE]: this does not always happen.** I don't understand what it depends on. For example, I create a new file `file.lua` - bad behavior. Then exit vim and get back into the file again. Everything is working fine. I go to the `base.lua` configuration file in another `tmux` window, everything is broken again.

- Perhaps it depends on what `event` for lazy loading plugins I'm using

### Neovim version

0.9.4

### Steps to reproduce

[minimal reproducing config](https://github.com/va9abond/nvim-config/tree/bug/mini-pairs-lang-layout)

Using folke/lazy.nvim to manage plugins.

- `mini-pairs.lua`
```lua
return {
      "echasnovski/mini.pairs",
      event = "VeryLazy",
      opts = {},
      keys = {
          {
              "<Bslash>mp",
              function()
                  vim.g.minipairs_disable = not vim.g.minipairs_disable
              end,
              desc = "Toggle auto pairs",
          },
      },
  }
``` 

- `xkb-switch.lua`
```lua
return {
    "lyokha/vim-xkbswitch",
}
```

- `base.lua`
```lua
-- ...
vim.g.XkbSwitchEnabled = 1
vim.g.XkbSwitchNLayout = "us"
vim.g.XkbSwitchIMappings = { "ru" }
-- ...
```

- `tmux-3.3_a-7`

- `setxkbmap -print -verbose 10`
```
Setting verbose level to 10
locale is C
Trying to load rules file ./rules/evdev...
Trying to load rules file /usr/share/X11/xkb/rules/evdev...
Success.
Applied rules from evdev:
rules:      evdev
model:      pc104
layout:     us,ru
options:    ctrl:nocaps,grp:win_space_toggle
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+ru:2+inet(evdev)+ctrl(nocaps)+group(win_space_toggle):1+group(win_space_toggle):2
geometry:   pc(pc104)
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+ru:2+inet(evdev)+ctrl(nocaps)+group(win_space_toggle):1+group(win_space_toggle):2"	};
	xkb_geometry  { include "pc(pc104)"	};
};
```

### Expected behavior

`file.lua` and active russian keyboard layout:
```
Before        Input         After
------------------------------------
Лорем |         х          Лорем х
Лорем |         э          Лорем э
------------------------------------
```

### Actual behavior

`file.lua` and active russian keyboard layout:
```
Before        Input         After
------------------------------------
Лорем |         х          Лорем [|]
Лорем |         э          Лорем '|'
------------------------------------
```

**Comment by echasnovski** [comment]
I can not reproduce with the recommended way of using multiple keyboard layouts, which is `'langmap'` option. For Cyrillic layout try this:

```lua
vim.o.langmap = "ёЁ;`~,№;#,йЙ;qQ,цЦ;wW,уУ;eE,кК;rR,еЕ;tT,нН;yY,гГ;uU,шШ;iI,щЩ;oO,зЗ;pP,хХ;[{,ъЪ;]},фФ;aA,ыЫ;sS,вВ;dD,аА;fF,пП;gG,рР;hH,оО;jJ,лЛ;kK,дД;lL,жЖ;\\;:,эЭ;'\\\"
```

Closing as not an issue.

**Comment by va9abond** [comment]
Thanks for your answer! I really like this job you're doing. I will definitely replace a few plugins with yours.


1. I get an error with your command:
```
E5112: Error while creating lua chunk: [path to file]: unfinished string near '[your command]'
```
2. I have been tried other variants, but nothing works:
```lua
vim.o.langmap = "ёЁ;`~,№;#,йЙ;qQ,цЦ;wW,уУ;eE,кК;rR,еЕ;tT,нН;yY,гГ;uU,шШ;iI,щЩ;oO,зЗ;pP,хХ;[{,ъЪ;]},фФ;aA,ыЫ;sS,вВ;dD,аА;fF,пП;gG,рР;hH,оО;jJ,лЛ;kK,дД;lL,жЖ;\\;:,эЭ;'\""
vim.o.langmap = "ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz"
```
3. The problem was solved when I specified the following command relying on this [issue](https://github.com/lyokha/vim-xkbswitch#:~:text=There%20is%20a%20known%20issue)
```lua
vim.g.XkbSwitchIMappingsSkipFt = { "tex", "text", "markdown" }
```

**Comment by echasnovski** [comment]
> 1. I get an error with your command:
> 
> ```
> E5112: Error while creating lua chunk: [path to file]: unfinished string near '[your command]'
> ```

Ah, yes, sorry. I just copied 'langmap' value without accounting for proper escaping. What I actually use is this:

```lua
local langmap_keys = {
  'ёЁ;`~', '№;#',
  'йЙ;qQ', 'цЦ;wW', 'уУ;eE', 'кК;rR', 'еЕ;tT', 'нН;yY', 'гГ;uU', 'шШ;iI', 'щЩ;oO', 'зЗ;pP', 'хХ;[{', 'ъЪ;]}',
  'фФ;aA', 'ыЫ;sS', 'вВ;dD', 'аА;fF', 'пП;gG', 'рР;hH', 'оО;jJ', 'лЛ;kK', 'дД;lL', [[жЖ;\;:]], [[эЭ;'\"]],
  'яЯ;zZ', 'чЧ;xX', 'сС;cC', 'мМ;vV', 'иИ;bB', 'тТ;nN', 'ьЬ;mM', [[бБ;\,<]], 'юЮ;.>',
}
vim.opt.langmap = table.concat(langmap_keys, ',')
```
