### ISSUE TITLE
mini.pairs do trigger `InsertLeave` when typing `<CR>`

### ISSUE THREAD

**Issue by mrbeardad** [echasnovski/mini.nvim#626]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

1. type `{`
2. get `{*}`, `*` is cursor
3. type `<CR>`
4. get 
```txt
{
  *
}
```

In step 3, the `InsertLeave` will be triggered, but it is a slow event since diagnostic will be triggered. Is it possible to avoid trigger it?

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, indeed there is an extra `InsertLeave` event.

This is fixable by tweaking `'eventignore'` option to temporarily have `InsertLeave` event. However, as `<CR>` (and any other 'mini.pairs' mapping) is used quite frequently, the goal is to have them the least amount of overhead as possible. So not quite sure what is the best approach here.

Maybe, the most straightforward here is for Neovim to not update diagnostic if it comes after `<C-o>` (that is, not regular Normal mode, but slightly different).

Meanwhile, you can use the following remap:
```lua
_G.cr_noinsertleave = function()
  local cache_eventignore = vim.o.eventignore
  vim.o.eventignore = 'InsertLeave'
  vim.schedule(function() vim.o.eventignore = cache_eventignore end)
  return MiniPairs.cr()
end
vim.keymap.set('i', '<CR>', 'v:lua.cr_noinsertleave()', { expr = true })
```

**Comment by mrbeardad** [comment]
Thanks for such a detailed explanation

**Comment by echasnovski** [comment]
@mrbeardad, if it is still relevant, the issue should now be fixed on latest `main`. I decided to add temporary event ignore after figuring out that it will cause quite small overhead only when typed inside a pair, which is acceptable. Let's hope there will not be any other unwanted side effects.
