### ISSUE TITLE
feature: Set indentscope hl_group

### ISSUE THREAD

**Issue by bockel** [echasnovski/mini.nvim#63]
It would be nice if there was a way to set the highlight group of the indentscope symbol.
A quick glance of `vim.api.nvim_buf_set_extmark` looks like you can pass the hl_group option to set the group.

indent-blankline.nvim and others allow this to be set as part of the configuration.
Maybe the indentscope configuration could be updated to supplement the symbol with a highlight group name, keeping backwards compatibility:

```lua
require('mini.indentscope').setup({
  symbol = "|",
  highlight = "Whitespace",
})
```

This could just be passed through a `hl_group` in extmark_opts in `H.make_draw_function` https://github.com/echasnovski/mini.nvim/blob/09d70a2cd763c368af749840bcb2a441ea10f971/lua/mini/indentscope.lua#L1003-L1010

I would expect the mark to use the Whitespace highlight group by default, but it appears that only the default highlight is used and merged with the background. The demo shows a blue indent mark, but it is otherwise unclear of how to control the coloring.

**Comment by echasnovski** [comment]
Thank for taking time and looking at source code! You stopped one step too early, though :) `vim.api.nvim_buf_set_extmakr()` also allows `hl_group` in `virt_text` to set different highlight groups for different parts of text. That is what 'mini.indentscope' is doing via its own two dedicated highlight groups for symbol and what comes before it (prefix):

https://github.com/echasnovski/mini.nvim/blob/09d70a2cd763c368af749840bcb2a441ea10f971/lua/mini/indentscope.lua#L875-L880

The preferred way of managing highlight groups is do redefine you the way you like. [Here is a list](https://github.com/echasnovski/mini.nvim/blob/09d70a2cd763c368af749840bcb2a441ea10f971/lua/mini/indentscope.lua#L44-L48) of highlight groups of 'mini.indentscope'. So in your case putting the `vim.cmd('hi! link MiniIndentscopeSymbol Whitespace')` somewhere in the 'init.lua' should solve the issue.

**Comment by benfrain** [comment]
Came here looking for the correct way to set the indentscope character color. Is this something you would consider adding to the docs? From what I can gather, it should be possible to do something like this in my theme config:

```
MiniIndentscopeSymbol = { fg = theme.waveBlue2 },
```

**Comment by echasnovski** [comment]
> Came here looking for the correct way to set the indentscope character color. Is this something you would consider adding to the docs? From what I can gather, it should be possible to do something like this in my theme config:
> 
> ```
> MiniIndentscopeSymbol = { fg = theme.waveBlue2 },
> ```
> 
> ?

That has already been answered in [previous comment](https://github.com/echasnovski/mini.nvim/issues/63#issuecomment-1106364338).

Place `vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { fg = theme.waveBlue2 })` somewhere in your setup.

**Comment by benfrain** [comment]
Yes, see that. I guess I was more trying to understand why setting it in the Kanagawa override options like this doesn't work (where it did for IndentBlankline):

```lua
require("kanagawa").setup({
  overrides = function(colors)
    local theme = colors.theme
    return {
      IndentBlanklineChar = { fg = colors.palette.waveBlue2 },
      MiniIndentscopeSymbol = { fg = colors.palette.waveBlue2 },
    }
  end,
})

require("kanagawa").load("wave")
```

**Comment by iSplasher** [comment]
Just chiming in to say that this should be part of the docs. Thanks!

**Comment by echasnovski** [comment]
> Just chiming in to say that this should be part of the docs. Thanks!

[It is already part of the docs](https://github.com/echasnovski/mini.nvim/blob/ed7c355bbeb8939e0dfe5099aa13c8ac9709396c/doc/mini-indentscope.txt#L57-L63).

**Comment by pablopunk** [comment]
hey @echasnovski, quick Q. Where are we supposed to place the highlight fn? Here's my setup (using `lazy.nvim`):

```lua
  {
    "echasnovski/mini.indentscope",
    lazy = false,
    config = function()
      require("mini.indentscope").setup {}
      vim.cmd "hi! link MiniIndentscopeSymbol Whitespace"
    end,
  }
```

But the symbol still has the default color. I also tried `vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { fg = '#333333' })` but still nothing.

It's worth mentioning that if I just run either of those in the cmdline, it does properly highlight the symbol.

**Comment by echasnovski** [comment]
> `vim.cmd "hi! link MiniIndentscopeSymbol Whitespace"`

This looks about right. I'd guess that you have color scheme overriding it later. There are at least two possible solutions:
- Make sure that color scheme is loaded first. I.e. the `:colorscheme <name>` command is executed prior to that `vim.cmd` call.
- A more idiomatic approach is to also create an autocommand that will ensure proper `MiniIndentscopeSymbol`. So add something like this after `vim.cmd "hi! ...`:
```lua
vim.cmd('au Colorscheme * hi! link MiniIndentscopeSymbol Whitespace')
```

**Comment by pablopunk** [comment]
The `autocommand` works fine 👍🏻 , I had it setup on `CursorMoved`, but your solution makes more sense 😅. I still don't know why the colorscheme is overriding it, but I'm happy with this solution. Thanks @echasnovski !
