### ISSUE TITLE
mini.map: reliably auto open/close map for different buffer types

### ISSUE THREAD

**Issue by JeanMertz** [echasnovski/mini.nvim#630]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.map

### Description

I am having trouble coming up with a consistent way to automatically open/close the minimap depending on the buffer type.

Specifically, initially I had an autocmd for `BufEnter` as such:

```lua
function()
    local enable = {
        ["nix"] = true,
        ["rust"] = true,
        ["lua"] = true,
    }

    print(vim.bo.filetype)
    if enable[vim.bo.filetype] then
        MiniMap.open()
    else
        MiniMap.close()
    end
end
```

The `print` in there is because I noticed whenever I opened a hover window (e.g. using `vim.lsp.buf.hover()`), the minimap would close because apparently that triggers `BufEnter`, even though the cursor hasn't left the original buffer yet, and the buffer type for such a hover window is empty.

Would you have any guidance on how to best tackle this problem with the least number of surprises but also in a way in which I always have the minimap available in a list of buffer types, but have it close when I switch to other buffer types, without it closing if I move into a hover window?

**Comment by JeanMertz** [comment]
Actually, it looks like this is a bug/unwanted side effect in Neovim that will be solved in the upcoming 0.10 release. See: https://github.com/neovim/neovim/pull/25078.

I'd still welcome suggestions on how to fix this in 0.9, but at least I'm not crazy, and this _is_ unexpected behavior.

**Comment by echasnovski** [comment]
There is [`FileType` event](https://neovim.io/doc/user/autocmd.html#FileType) which is usually a better choice for filetype-specific autocommands.

So something like this should work:

```lua
local openclose = function(data)
  local enable = { nix = true, rust = true, lua = true }
  local ft = vim.bo[data.buf].filetype
  if enable[ft] then
    MiniMap.open()
  else
    MiniMap.close()
  end
end
vim.api.nvim_create_autocmd('FileType', { callback = openclose, desc = "Toggle 'mini.map' based on filetype" })
```

**Comment by JeanMertz** [comment]
Thank you for the pointer. I did try that event, but it doesn't trigger when `filetype` is unset, which happens e.g. in files for which I have no ft plugin, or when doing `:new`. 

I agree it's better than what I had, given the existing issue with `BufEnter`, so it seems like this is the best approach for now, until 0.10 rolls around.

**Comment by echasnovski** [comment]
In that case you can try to continue using `BufEnter` event but also add check for buffer's type. Something like this `if vim.bo.buftype ~= '' then return end`, i.e. only toggle map if entered "normal" buffer (and not terminal, scratch, quickfix, etc.). This should fix the issue with various temporary helper floating windows, because usually buffers there have 'buftype' equal to 'none'.
