### ISSUE TITLE
mini.trailspace highlights in LazyVim startup screen

### ISSUE THREAD

**Issue by HaleTom** [echasnovski/mini.nvim#631]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

trailspace

### Description

On starting LazyVim, it looks horrible:

![image](https://github.com/echasnovski/mini.nvim/assets/13854417/548ab43d-0c37-4007-98bd-39d4384ac6e6)

Config:

### Neovim version

NVIM v0.9.4

### Steps to reproduce

1. Install (LazyVim](https://www.lazyvim.org/installation)
2. Setup trailspace:

```
return {
  "echasnovski/mini.trailspace",
  event = "VeryLazy",
  opts = {
    only_in_normal_buffers = true,
  },
}
```
3. Start neovim

### Expected behavior

No red on screen.

### Actual behavior

See top screenshot.

**Comment by HaleTom** [comment]
Ideally, it would be great to have a way to disable / blacklist for various filetypes that commonly have trailing whitespace.

**Comment by HaleTom** [comment]
Buftype blacklist would also be great :)

**Comment by echasnovski** [comment]
Thanks for the issue!

At first glance it seems like some misconfiguration issue, but I'll look into it.

> Ideally, it would be great to have a way to disable / blacklist for various filetypes that commonly have trailing whitespace.

> Buftype blacklist would also be great :)

Precisely because of such various use cases there won't be dedicated blocklists for filetype-buftype-etc. See [disabling](https://github.com/echasnovski/mini.nvim/blob/fd5d244647cf1f37e85ba3e490d5968df33ef430/doc/mini-trailspace.txt#L35-L43) section in help file.

**Comment by echasnovski** [comment]
Here 'mini.trailspace' works as expected.

The 'dashboard-nvim' uses normal buffer to display its content (see [here](https://github.com/nvimdev/dashboard-nvim/issues/409)).

You can disable for `'dashboard'` filetype like this (autocommand should be done *before* dashboard creates its buffer):

```lua
vim.cmd('au FileType dashboard lua vim.b.minitrailspace_disable = true')
require('dashboard').setup()
```
