### ISSUE TITLE
mini.basics: termguicolors setting redundant after nvim v0.10.0 released

### ISSUE THREAD

**Issue by brotherkaif** [echasnovski/mini.nvim#632]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.basics

### Description

Version v0.10 of neovim will include a feature to automatically determine if `termguicolors` needs to be set. This means that terminals that do not feature `truecolor` support (for example, the macOS Terminal.app) will now gracefully fallback to `termguicolors` being set to `false`. Terminals that do support it will have the value set to true.

This change was recently merged into the nightly build as part of [PR 26407](https://github.com/neovim/neovim/pull/26407).

As a result, the current behaviour of mini.basics to manually set `termguicolors` to true actually breaks this new neovim feature for users who are not using a `truecolor` supported terminal.

As far as I can tell, the only change required is to [remove the following line](https://github.com/echasnovski/mini.nvim/blob/fd5d244647cf1f37e85ba3e490d5968df33ef430/lua/mini/basics.lua#L458). This will allow for neovim itself to handle the setting of `termguicolors`.

This does seem like a small change that I could raise a PR for. Although I've never actually contributed to much open source before so I'm not entirely sure of the process (my apologies! I'm still dipping my toes into the world of open source development).

Are there any other changes that are required other than that line? I suspect any references to `termguicolors` in the documentation and in the comments would also need to be removed. Also, what would the approach be for users who are on a version that is < v0.10? If we remove the setting of `termguicolors`, then users on an earlier version of neovim will unexpectedly lose this setting until they move over to v0.10.

### Neovim version

Neovim nightly v0.10.0-dev-1974+g714b07519

### Steps to reproduce

1. Install neovim v0.10.0
2. Add mini.basics with default configuration
3. Open neovim in a non-truecolor terminal (for example, macOS Terminal.app)

### Expected behavior

Neovim v0.10 should detect that it is running in a non-truecolor terminal and set `termguicolors` to `false`.

Below is a screenshot of both a non-truecolor terminal (Terminal.app on the left) and a truecolor terminal (Alacritty on the right) running Neovim nightly v0.10.0-dev-1974+g714b07519 with the mini.basics plugin **disabled**:
![Screenshot 2023-12-29 at 10 31 52](https://github.com/echasnovski/mini.nvim/assets/25749076/3795a67a-c222-4012-a5ab-82e191266729)
_left: Terminal.app (non-truecolor), right: Alacritty (truecolor)_

As can be seen, the non-truecolor terminal has fallen back to having `termguicolors` set to `false` as intended.

### Actual behavior

Below is a screenshot of both a non-truecolor terminal (Terminal.app on the left) and a truecolor terminal (Alacritty on the right) running Neovim nightly v0.10.0-dev-1974+g714b07519 with the mini.basics plugin **enabled**:
![Screenshot 2023-12-29 at 10 34 38](https://github.com/echasnovski/mini.nvim/assets/25749076/4961e7cd-527d-421c-bcd7-5668814c061f)
_left: Terminal.app (non-truecolor), right: Alacritty (truecolor)_

As can be seen, the non-truecolor terminal no features no coloring as the mini.basics plugin has overidden the default neovim behaviour and manually set termguicolors` to `true`.

**Comment by echasnovski** [comment]
Thanks for such a detailed and well prepared suggestion!

Indeed, this behavior could be better. I've been aware of this change for quite some time, but forgot to update 'mini.basic's accordingly. Even had relevant test updated yesterday and still didn't update the behavior itself.

It should now work on latest `main` branch.

> This does seem like a small change that I could raise a PR for. Although I've never actually contributed to much open source before so I'm not entirely sure of the process (my apologies! I'm still dipping my toes into the world of open source development).
> 
> Are there any other changes that are required other than that line? I suspect any references to `termguicolors` in the documentation and in the comments would also need to be removed. Also, what would the approach be for users who are on a version that is < v0.10? If we remove the setting of `termguicolors`, then users on an earlier version of neovim will unexpectedly lose this setting until they move over to v0.10.

Yes, it is indeed not an overcomplicated update, but involves several small updates here and there. You can see how I resolved this in 937386c4fab6a906fb18fe75c0d77f807d270a76 commit.

**Comment by brotherkaif** [comment]
No problem! Thanks for sharing the PR; I didn't realise there were unit tests as well, so that's really helpful.

Hopefully I can get a bit more familiar with the codebase and help out with some contributions 🙂
