### ISSUE TITLE
MiniTrailspace.trim() only on selection

### ISSUE THREAD

**Issue by HaleTom** [echasnovski/mini.nvim#634]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

MiniTrailspace

### Description

When selecting lines as a visual block with `V`, I want to only trim whitespace on those lines.

This would fulfil the law of least surprise, and supports smaller diffs.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The 'mini.trailspace' module is kept as minimal as possible by design. You can achieve the behavior you describe with the following mapping: `vim.keymap.set('x', '<Leader>w', [[:s/\s\+$//<CR>]])`

Closing as not planned.

**Comment by HaleTom** [comment]
Thanks for the mapping!

**Comment by HaleTom** [comment]
https://github.com/mcauley-penney/tidy.nvim -- supports "only modified lines" "on save"

https://github.com/thirtythreeforty/lessspace.vim -- dynamic editing
```
    -- By default, LessSpace strips whitespace after normal mode operations
    -- This is annoying, eg if pressing `D`: all indents disappear
    -- Have LessSpace only work in insert mode by setting g:lessspace_normal=0
    vim.g.lessspace_normal = 1
```
