### ISSUE TITLE
feat: continue indent guides on wrapped lines

### ISSUE THREAD

**Issue by mcauley-penney** [echasnovski/mini.nvim#635]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.indentscope

## What
Nightly now includes the ability to [display extmarks on wrapped lines](https://github.com/neovim/neovim/issues/23108). This feature has made its way into other indent guide plugins (see [here](https://github.com/lukas-reineke/indent-blankline.nvim/pull/810) and [here](https://github.com/lukas-reineke/indent-blankline.nvim/pull/812)). 

## How
Using nightly, seeing the effects of this feature only requires placing `virt_text_repeat_linebreak = true` into the `extmark_opts` table in indentscope's `make_draw_function()`. In the below example, I am using indentscope with this option on, and it is visible on the wrapped lines indicated by dashes in the number columns.

![break-with-guide](https://github.com/echasnovski/mini.nvim/assets/59481467/7f5e5267-aa51-49cc-bfe9-80c90a2fd7d5)

The bulk of the change seems like it would be adding error handling and checking the user's Neovim version (until 0.10 is released), options, and indentscope configuration.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I've just checked it, and it indeed seems to work with one line change.

As the feature is only a week old, I'd wait a bit until it is more polished. Then add it behind a version check.

**Comment by echasnovski** [comment]
This should be resolved on latest `main` thanks to @gpanders.
