### ISSUE TITLE
Mini.Files add keymap to open in split instead of current window

### ISSUE THREAD

**Issue by icyrainz** [echasnovski/mini.nvim#646]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Mini.Files

### Description

I'm following this snippet in the Help files:
```
# Create mappings to modify target window via split ~

  local map_split = function(buf_id, lhs, direction)
    local rhs = function()
      -- Make new window and set it as target
      local new_target_window
      vim.api.nvim_win_call(MiniFiles.get_target_window(), function()
        vim.cmd(direction .. ' split')
        new_target_window = vim.api.nvim_get_current_win()
      end)

      MiniFiles.set_target_window(new_target_window)
    end

    -- Adding `desc` will result into `show_help` entries
    local desc = 'Split ' .. direction
    vim.keymap.set('n', lhs, rhs, { buffer = buf_id, desc = desc })
  end

  vim.api.nvim_create_autocmd('User', {
    pattern = 'MiniFilesBufferCreate',
    callback = function(args)
      local buf_id = args.data.buf_id
      -- Tweak keys to your liking
      map_split(buf_id, 'gs', 'belowright horizontal')
      map_split(buf_id, 'gv', 'belowright vertical')
    end,
  })
```

But it's actually split the currently opened window instead of one being highlighted in the Mini.Files window.
Do we have any way to get the currently selected item to split?
Also it would be great if we can specify if the Mini.Files popup should stay or automatically close after the keymap.

Thanks.

**Comment by echasnovski** [comment]
> But it's actually split the currently opened window instead of one being highlighted in the Mini.Files window.
> Do we have any way to get the currently selected item to split?

This is an example of how to [create mappings to modify target window via split](https://github.com/echasnovski/mini.nvim/blob/e578f353d0b1d9f21a9640458d8e506c0c9acf5e/doc/mini-files.txt#L429) and not how to open file under cursor in a split. After making the split with mapping, open file as usual and it will be opened in the newly created split.

> Also it would be great if we can specify if the Mini.Files popup should stay or automatically close after the keymap.

Explorer windows are closed after `MiniFiles.close()` is called or focus is forced outside of them. In turn, `close()` is called after `mappings.close` or `mappings.go_in_plus` is pressed. Other than that, explorer stays open.

If you want explorer to be closed in custom mapping, call `close()` explicitly.
