### ISSUE TITLE
mini.animate: Text rendering on CJK line is corrupted with `predicate: () => true`

### ISSUE THREAD

**Issue by leaysgur** [echasnovski/mini.nvim#648]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

animate

### Description

See actual behavior section. 🎥 

### Neovim version

0.9.4

### Steps to reproduce

1. Setup `mini.animate`(I'm using lazy.nvim)

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"echasnovski/mini.animate",
		config = function()
			local animate = require("mini.animate")
			animate.setup({
				cursor = {
					path = animate.gen_path.line({
						predicate = function()
							return true
						end,
					}),
				},
			})
		end,
	},
})
```

2. Prepare file includes CJK languages like

```
# Cursor ~

This animation is triggered for each movement of cursor inside same windowand buffer.
Its visualization step consists from placing single extmark (see|extmarks|) at certain position.
This extmark contains single space and is highlighted with `MiniAnimateCursor` highlight group.

# カーソル

このアニメーションは、同じウィンドウとバッファ内でカーソルが移動するたびにトリガーされる。
その視覚化のステップは、1つのエクストマーク(|extmarks|を参照)を特定の位置に置くことから始まります。
このエクストマークは1つのスペースを含み`MiniAnimateCursor`ハイライトグループでハイライトされます。
```

3. Move cursor on CJK line and move around

### Expected behavior

Text rendering is not corrupted.

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/6259812/eb228885-6f7d-4691-88c3-da271b8a3d29

This can be reproduced with WezTerm and also Terminal.app.

**Comment by echasnovski** [comment]
Thanks for the issue!

This *looks* like an issue with Neovim. I was able to reproduce similar behavior without 'mini.animate' (see neovim/neovim#26949). Although it pretty much looks like an upstream issue, I'll wait a bit until updates on that opened issue.

**Comment by leaysgur** [comment]
Thank you for the investigation and quick response! 😄 

I also confirmed upstream issue. I will wait until `v0.10` is released.
