### ISSUE TITLE
inner indent indicators

### ISSUE THREAD

**Issue by bennypowers** [echasnovski/mini.nvim#65]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

indentscope

### Description

`'lukas-reineke/indent-blankline.nvim'` shows inner indent guides, meaning, visual indicators of indent levels for every line which has an indent. In this screenshot, the indicators i'm referring to are rendered in dark grey, for example, lines 14-17.
<img width="727" alt="Screen Shot 2022-04-24 at 15 40 15" src="https://user-images.githubusercontent.com/1466420/164977128-1c1f8368-cbec-4b06-b291-3ddb650e0261.png">

`mini.indentscope` can be configured to display instantly, similar to `indent-blankline`, but it only shows an indicator for the active indent level:
<img width="728" alt="Screen Shot 2022-04-24 at 15 45 03" src="https://user-images.githubusercontent.com/1466420/164977170-aa5e60d6-8a68-4379-b3ef-487e75364c97.png">

The advantage of `mini.indentscope` is the combination of indent textobjects with visual indicators. Please consider adding the same indent guides that `indent-blankline` has, to complete the package.

**Comment by echasnovski** [comment]
Thank for suggestion!

I considered implementing this for quite a while. Unfortunately, didn't find a way that is "not complicated", fast, and can be used with animation.
As you are not the first one to ask this, I'll think about it.

**Comment by echasnovski** [comment]
After a long time of having this opened, I think I am going to close this. This feels like out of scope for 'mini.indentscope'. It now works correctly with 'lukas-reineke/indent-blankline.nvim' (doesn't cover its lines), so probably best to use them both.

I plan to implement #226 as compromise.
