### ISSUE TITLE
highlighting disappears with bluz71/vim-nightfly-colors

### ISSUE THREAD

**Issue by jt4201** [echasnovski/mini.nvim#652]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick, mini.extra

### Description

In `mini.pick`, `MiniPickMatchCurrent` is linked to `CursorLine` and `MiniPickNormal` is linked to `NormalFloat`

In [bluz/vim-nightfly-colors](https://github.com/bluz71/vim-nightfly-colors/), both `CursorLine` and `NormalFloat` set `bg=dark_blue`. This makes the current line look the same as the background. 

There is already a limited Mini... highlights section in nightfly. I read the section about updating colorschemes, but since the Mini highlights already exist, some one may already "own" this.

My workaround is to set `MiniPickMatchCurrent` to `{ standout = true }`
```
vim.api.nvim_set_hl(0, "MiniPickMatchCurrent", { standout = true })
```

### Neovim version

0.9.5

### Steps to reproduce

1. create test nvim config
```
 # I use fish as a shell, but this should work with bash/zsh
mkdir ~/.config/nvim-test
cd ~/.config/nvim-test
git init
mkdir -p pack/{plugins,themes}/{opt,start}
git submodule add https://github.com/bluz71/vim-nightfly-colors pack/themes/start/nightfly
git submodule add https://github.com/echasnovski/mini.nvim pack/plugins/start/mini.nvim
```
2. create `.config/nvim-test/init.lua`
```
vim.g.mapleader = ' '
vim.opt.termguicolors = true
vim.opt.background = 'dark'
vim.cmd.colorscheme('nightfly')
require('mini.pick').setup({ })
require('mini.extra').setup({ })
vim.keymap.set('n', '<leader>ff', '<cmd>Pick explorer<cr>')
```
3. run test version with 
```
NVIM_APPNAME=nvim-test nvim
```

### Expected behavior

you can see the current line with a highlight

### Actual behavior

current line is not highlighted

**Comment by echasnovski** [comment]
The highlight group definitions which come directly from 'mini.pick' are there only as default values. This means that they are (hopefully) reasonable choices which should work with most color schemes. But not all.

Dealing with highlight groups which come from color scheme is [suggested to be done by user](https://github.com/echasnovski/mini.nvim/blob/e578f353d0b1d9f21a9640458d8e506c0c9acf5e/doc/mini-pick.txt#L131). It is perfectly appropriate to have `:colorscheme ...` call followed by some user adjustments. Like in this case followed by `vim.api.nvim_set_hl(0, "MiniPickMatchCurrent", { standout = true })`. To work with *any* color scheme, these adjustments can be put in the autocommand for `ColorScheme` event.

**Comment by echasnovski** [comment]
After bluz71/vim-nightfly-colors#61 there should be now better support for 'mini.pick'.
