### ISSUE TITLE
when statusline is disabled with neotree, after closing neotree the statusline remains inactive

### ISSUE THREAD

**Issue by Rishabh672003** [echasnovski/mini.nvim#653]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

I wanted to disable the mini.statusline on neotree, so i came around this another issue #344 ,
So i tried using that, but what issue I am facing is after i toggle neotree it disables the statusline but after closing the statusline, it doesnt get back to its previous state and instead just shows the filepath.

### Neovim version

Neovim nightly (NVIM v0.10.0-dev-2066+g1813661a6)

### Minimal Config 

```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)
vim.opt.laststatus = 3
-- install plugins
local plugins = {
	"catppuccin/nvim",
	-- add any other plugins here
	{

		"echasnovski/mini.statusline",
		enabled = true,
		version = false,
		lazy = false,
		config = function()
			local MiniStatusline = require("mini.statusline")
			local blocked_filetypes = { ["neo-tree"] = true }
			require("mini.statusline").setup({
				content = {
					active = function()
						if blocked_filetypes[vim.bo.filetype] then
							vim.cmd("highlight StatusLine guibg=NONE guifg=NONE")
							return ""
						end
						local mode, mode_hl = MiniStatusline.section_mode({ trunc_width = 120 })
						local git = MiniStatusline.section_git({ trunc_width = 75 })
						local diagnostics = MiniStatusline.section_diagnostics({ trunc_width = 75 })
						local filename = MiniStatusline.section_filename({ trunc_width = 140 })
						local fileinfo = MiniStatusline.section_fileinfo({ trunc_width = 120 })
						local location = MiniStatusline.section_location({ trunc_width = 75 })
						local search = MiniStatusline.section_searchcount({ trunc_width = 75 })

						return MiniStatusline.combine_groups({
							{ hl = mode_hl, strings = { mode } },
							{ hl = "MiniStatuslineDevinfo", strings = { git, diagnostics } },
							"%<", -- Mark general truncate point
							{ hl = "MiniStatuslineFilename", strings = { filename } },
							"%=", -- End left alignment
							{ hl = "MiniStatuslineFileinfo", strings = { fileinfo } },
							{ hl = mode_hl, strings = { search, location } },
						})
					end,
				},
				use_icons = true,

				-- Whether to set Vim's settings for statusline (make it always shown with
				-- 'laststatus' set to 2). To use global statusline in Neovim>=0.7.0, set
				-- this to `false` and 'laststatus' to 3.
				set_vim_settings = false,
			})
		end,
	},
	{
		"nvim-neo-tree/neo-tree.nvim",
		cmd = "Neotree",
		branch = "v2.x",
		-- event = "BufRead",
		enabled = true,
		dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
		config = function()
			vim.keymap.set("n", "<Space>e", "<cmd>Neotree focus toggle<cr>")
			require("neo-tree").setup({
				popup_border_style = "rounded",
				window = {
					position = "left",
					width = 27,
					mapping_options = {
						noremap = true,
						nowait = true,
					},
				},
				filesystem = {
					follow_current_file = true,
					hijack_netrw_behavior = "open_current",
				},
				source_selector = {
					winbar = true,
					content_layout = "center",
					sources = {
						{ source = "filesystem", display_name = " 󰈔 File" },
						{ source = "buffers", display_name = "  Bufs" },
						{ source = "git_status", display_name = "  Git" },
					},
				},
			})
		end,
	},
}

require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin")
-- add anything else here
```

### Steps to reproduce

1. `nvim -nu repro.lua `
2. Toggle neotree with `:Neotree focus toggle`
3. then close the neotree with `:q`

### Expected behavior

mini.statusline should return to its usual state

### Actual behavior

Instad of showing actual statusline content, it just shows the filename

![image](https://github.com/echasnovski/mini.nvim/assets/53911515/b916a892-da3c-4757-9698-38c07d2edfef)

**Comment by echasnovski** [comment]
Thanks for the issue!

I can not reproduce (both with version of nightly from the issue and 0.9.4):

https://github.com/echasnovski/mini.nvim/assets/24854248/2c7176aa-ce42-414e-93ee-60b56d11624a

Couple of follow up questions and observations:
- Did you actually reproduce with the minimal setup from the issue? If not, please do that by creating a separate config in `~/.config/nvim-neotree-statusline` and run `NVIM_APPNAME=nvim-neotree-statusline nvim` (assuming UNIX, otherwise see `:h $NVIM_APPNAME`).
- `StatusLine` highlight group is cleared inside `blocked_filetypes` conditional, but not reinstated afterwards. This might cause an unexpected issue later.
- The fact that statusline shows file path instead of `''` or normal active content means that it shows content from `config.content.inactive`. Thus this should not be an issue with "disabled" statusline, but more with that something obstructs how 'mini.statusline' decided which content to show.

**Comment by Rishabh672003** [comment]
@echasnovski wait i was wrong, it happens when you toggle off the neotree with the same command `Neotree focus toggle`, you are right when you quit with `:q` its returns back to the active state

**Comment by echasnovski** [comment]
> @echasnovski wait i was wrong, it happens when you toggle off the neotree with the same command `Neotree focus toggle`, you are right when you quit with `:q` its returns back to the active state

Yes, with this step I can reproduce. Will look into it.

**Comment by Rishabh672003** [comment]
it happens even after removing the `active = function` part, so i guess its some issue with `Neotree` and `mini.statusline` interaction

**Comment by echasnovski** [comment]
After having looked closer into this, I am mostly positive that this is not a 'mini.statusline' issue. Here is the outline:
- 'mini.statusline'  sets window-local 'statusline' options to show either `content.active` or `content.inactive` [inside `(Win,Buf)(Enter,Leave)` events](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/lua/mini/statusline.lua#L468) - active statusline is shown on enter, inactive - on leave. This is reasonable and proved to work well.
- On the other hand, when closing 'neo-tree' window with `Neotree toggle focus`, there is no `WinEnter` event for the window which is focused after that. **But** there is such event triggered if window is closed with `:quit` (which caused initial confusion in this issue).
- This is an indicator that in 'neo-tree.nvim' code implementing `:Neotree toggle focus` previous window is focused at the time when events (or only `WinEnter` in particular) can not be triggered. Usually it is either:
    - Command is executed with `noautocmd`.
    - `eventignore` is such that both `WinEnter` and `BufEnter` are ignored.
    - Window is set inside an autocommand which is configured without `nested = true` (or `++nested` in Vimscript). This seems like the most probable cause. 
- I tried to find a fix in 'neo-tree.nvim', but after about 20 minutes I was not even sure if I found a place where `toggle close` command is actually executed. So decided to just create an issue, but there is already a similar one: nvim-neo-tree/neo-tree.nvim#1211.

Closing as this is most certainly not a 'mini.statusline' issue.

**Comment by Rishabh672003** [comment]
makes sense, thanks for your time @echasnovski
