### ISSUE TITLE
mini.notify: empty notifications

### ISSUE THREAD

**Issue by lervag** [echasnovski/mini.nvim#654]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.notify

### Description

I've recently started to test mini.notify and I have a couple of questions. I noticed the beta thread, but I reckoned I might be onto a bug so I chose to open a separate issue.

I've configured mini.notify with `lazy.nvim` like this:

```lua
{
  "echasnovski/mini.notify",
  config = function()
    local mininotify = require "mini.notify"
    mininotify.setup {
      content = {
        format = function(notif)
          return notif.msg
        end,
      },

      lsp_progress = {
        duration_last = 3000,
      },

      window = {
        config = function(buf_id)
          local line_widths = vim.tbl_map(
            vim.fn.strdisplaywidth,
            vim.api.nvim_buf_get_lines(buf_id, 0, -1, true)
          )
          local width = 15
          for _, l_w in ipairs(line_widths) do
            width = math.max(width, l_w)
          end

          return {
            width = math.min(width + 1, math.floor(0.9 * vim.o.columns)),
            border = { "┏", " ", " ", " ", " ", " ", "┗", "┃" },
            title = "NOTIFICATIONS",
            title_pos = "right",
          }
        end,
        winblend = 0,
      },
    }

    vim.notify = mininotify.make_notify()
  end,
},
```

Now, the issue is that it seems I'm getting a lot of empty lines in the notifications. E.g., if I open a lua file I immediately get this notification:

![image](https://github.com/echasnovski/mini.nvim/assets/998898/e4196865-e8a3-4190-916f-fffa2a9cc291)

If I start editing, I will get notifications from the diagnostics:

![image](https://github.com/echasnovski/mini.nvim/assets/998898/35bca77a-deac-4262-861d-cfab73584999)

Again, notice the empty lines.

----

Also, I was wondering if it might be possible to filter the notifications to avoid showing the same notifications twice. I tried to do this with the `sort` config option, but in the end I gave up.

### Neovim version

NVIM v0.10.0-dev-2047+g8df3742378

### Steps to reproduce

See above description. If necessary, I can attempt to make a minimal version.

### Expected behavior

Don't show empty lines.

### Actual behavior

There are empty lines.

**Comment by echasnovski** [comment]
Thanks for issue!

> Now, the issue is that it seems I'm getting a lot of empty lines in the notifications.

Not quite a bug, but rather a current documented behavior, which don't think will change. The reason for empty lines is that window's height [is computed assuming default `width`](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-notify.txt#L191-L195). If you want to change either dimension, you'd need to adjust both height and width. This is the reason why `buf_id` is there as input.

> Also, I was wondering if it might be possible to filter the notifications to avoid showing the same notifications twice. I tried to do this with the `sort` config option, but in the end I gave up.

'mini.notify' already won't show same notification twice, but it relies on the internal concept of "sameness" meaning an identifier returned by `MiniNotify.add()`. As `vim.notify()` doesn't have a notion of "notification identifier", output of `make_notify()` treats every notification as unique.

Yes, `content.sort` is the way to [both sort and filter](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-notify.txt#L138-L139). If you want to not show notifications with duplicating messages, here the way to do this:
```lua
local filterout_duplicates = function(notif_arr)
  local res, present_msg = {}, {}
  for _, notif in ipairs(notif_arr) do
    if not present_msg[notif.msg] then
      table.insert(res, notif)
      present_msg[notif.msg] = true
    end
  end
  return MiniNotify.default_sort(res)
end
require('mini.notify').setup({ content = { sort = filterout_duplicates } })
```
Be careful though: this will not show notifications, but they will still be present until removed. This is only an issue if `MiniNotify.add()` is used directly and not through output of `make_notify()`.

**Comment by lervag** [comment]
> Not quite a bug, but rather a current documented behavior, which don't think will change. The reason for empty lines is that window's height [is computed assuming default `width`](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-notify.txt#L191-L195). If you want to change either dimension, you'd need to adjust both height and width. This is the reason why `buf_id` is there as input.

Ah, thanks! I agree, I should have read the docs more carefully.

> > Also, I was wondering if it might be possible to filter the notifications to avoid showing the same notifications twice. I tried to do this with the `sort` config option, but in the end I gave up.
> 
> 'mini.notify' already won't show same notification twice, but it relies on the internal concept of "sameness" meaning an identifier returned by `MiniNotify.add()`. As `vim.notify()` doesn't have a notion of "notification identifier", output of `make_notify()` treats every notification as unique.

Ok, I see. I believe the duplicated entries come from the LSP here, though, so not from the regular `vim.notify`?

> Yes, `content.sort` is the way to [both sort and filter](https://github.com/echasnovski/mini.nvim/blob/f54410c7f866f51711118fd82274043cf731b63d/doc/mini-notify.txt#L138-L139). If you want to not show notifications with duplicating messages, here the way to do this: …

Thanks! That was close to what I had, but not quite. I guess my Lua skill needs more work :)

I'll test and see if I like it. I realize that, if I do this, then having the time stamps present makes sense to avoid confusion if some message seems to persist longer than expected.

One more question: Is it possible to format the output with different highlight groups in the formatter? I.e., could I use a different highlight group for the time stamp? (From the docs, I believe the answer is no; if so, would it be hard/possible to add this feature?)

**Comment by echasnovski** [comment]
> Ok, I see. I believe the duplicated entries come from the LSP here, though, so not from the regular `vim.notify`?

If you are talking about several "Diagnosing ..." from `lua_ls` then those are from different progress reports which happen to have same message. I checked. Didn't manage to locate the actual issue, though. The overview is that:
- I experience this on large-ish files (1000+ lines) and usually when typing inside comment or string.
- `lua_ls` has hard coded 500ms delay after starting diagnosing buffer to start sending a progress report about it.
- It is usually triggered when Neovim makes request to update semantic tokens.

> One more question: Is it possible to format the output with different highlight groups in the formatter? I.e., could I use a different highlight group for the time stamp? (From the docs, I believe the answer is no; if so, would it be hard/possible to add this feature?)

No, that is not possible and it is deliberate choice to simplify data structures of what `format()` should/might/can return.

*In theory*, having buffer id users can set their own highlighting based on the text:
- The notify buffer has 'mininotify' filetype, so users can create a autocommand for `FileType` event.
- Inside that autocommand another buffer-local autocommand for `TextChanged` can be done to update the highlighting whenever text is changed in that buffer.

**Comment by lervag** [comment]
Oh, yes; with the `FileType` it would be trivial to just specify a simple `syntax/mininotify.vim` script. I'll consider doing it. Right now, I'm quite happy.

I like your take on this; it seems quite minimal and is still very much "just what I need". Well done!

**Comment by echasnovski** [comment]
@lervag, after reconsidering, there is now a [`config.window.max_width_share` option](https://github.com/echasnovski/mini.nvim/blob/79b1b3350f1cac7cef9e46a637f9adf2a14b4923/doc/mini-notify.txt#L122-L123) to increase maximum allowed width before notification become wrapped. Judging by initial post, you'd benefit from setting it to 0.9.

**Comment by lervag** [comment]
Cool, thanks! I'm currently specifying both the width and height and have things working very much to my liking, so I don't think I'll be using this now, though.
