### ISSUE TITLE
Leap default attributes are overridden.

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#658]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

base16, hues

### Description

By default, "LeapMatch" uses underline as visual cue to help us predict whether we'll need an additional label. This is currently overridden by both Mini.Hues and Mini.Base16, which opt to use bold green instead which is not always apparent, especially considering potential changes in hues:

![Screenshot from 2024-01-16 14-38-12](https://github.com/echasnovski/mini.nvim/assets/91024200/732ed965-ae70-4f01-9b50-0d231e2054b2)
![Screenshot from 2024-01-16 14-38-18](https://github.com/echasnovski/mini.nvim/assets/91024200/5da6be7f-28c3-4be6-8b7e-cc733f43cd00)

---

With Leap's intended default underline, it becomes much clearer:

![Screenshot from 2024-01-16 14-43-44](https://github.com/echasnovski/mini.nvim/assets/91024200/aa360297-26ea-43a3-a966-0f69b188740f)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/afd6f9e2-764e-418e-8441-030360d7e6dd)

### Neovim version

NVIM v0.10.0-dev+1974-g714b07519

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. set `highlight_unlabeled_phase_one_targets = true` in leap's options.

### Expected behavior

Preserve Leap defaults attributes.

### Actual behavior

Attributes are overwritten.

**Comment by echasnovski** [comment]
Thanks for creating this!

I am not a user of 'leap.nvim' and those highlights were created based on [their descriptions](https://github.com/ggandor/leap.nvim/blob/0c2f6a27d0706fa86f2512bb0c470b68876e55fe/doc/leap.txt#L287). To my eye screenshots look usable, but if you feel strongly about it not being visible enough, I'll look into possibly updating them.

In the meantime, you can add underline in every color scheme by creating the following autocommand **before** applying first color scheme:

```lua
vim.cmd('au ColorScheme * hi LeapMatch gui=underline')
```

**Comment by wroyca** [comment]
> Thanks for creating this!
> 
> I am not a user of 'leap.nvim' and those highlights were created based on [their descriptions](https://github.com/ggandor/leap.nvim/blob/0c2f6a27d0706fa86f2512bb0c470b68876e55fe/doc/leap.txt#L287). To my eye screenshots look usable, but if you feel strongly about it not being visible enough, I'll look into possibly updating them.
> 

I don't have a strong opinion here, though as more hours pass by, it's nice to have one less mental overhead to tire you out. ;)

> In the meantime, you can add underline in every color scheme by creating the following autocommand **before** applying first color scheme:
> 
> ```lua
> vim.cmd('au ColorScheme * hi LeapMatch gui=underline')
> ```

Thanks! I already did so prior to opening this issue. In fact, I pondered whether opening an issue was worth it. However, in the end, I concluded that color should not take precedence over plugin-intended attributes, so I decided to proceed with it-

For reference: https://github.com/ggandor/leap.nvim/blob/0c2f6a27d0706fa86f2512bb0c470b68876e55fe/fnl/leap/highlight.fnl#L82

**Comment by echasnovski** [comment]
> Thanks! I already did so prior to opening this issue. In fact, I pondered whether opening an issue was worth it. However, in the end, I concluded that color should not take precedence over plugin-intended attributes, so I decided to proceed-

No harm in opening an issue if you did spend time to think if it was worth it :)

I don't think underline *is* a plugin-intended attribute, because it is not documented. What plugins define in their code is default highlighting which would be applied if there is no definition by user or color scheme. So it is more of a reference for color scheme authors.

**Comment by wroyca** [comment]
> Thanks again for the suggestion!
> 
> `LeapMatch` on `main` branch is now updated to also have underline.

Awesome, thank!
