### ISSUE TITLE
Extend mini.files navigation

### ISSUE THREAD

**Issue by tiagovla** [echasnovski/mini.nvim#659]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Hello,

I want to change the current behavior of the navigation for my personal use. Would it be possible to expose the `H` table within the `mini.files` module?

E.g. I don't want the navigation `go_in` to open the file and also add other custom explorer manipulations without forking the project.

**Comment by echasnovski** [comment]
> Would it be possible to expose the `H` table within the `mini.files` module?

No, helper functions are private and won't get exported.

> E.g. I don't want the navigation `go_in` to open the file and also add other custom explorer manipulations without forking the project.

If you elaborate with a bit more description on what you are trying to achieve, we can try to work something out.
