### ISSUE TITLE
Transferring files to a subdirectory creates new files

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#660]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

files

### Description

Trying to transfer several files to a subdirectory will result in the creation of new files within that directory while retaining the original ones.

### Neovim version

NVIM v0.10.0-dev+1974-g714b07519

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Open MiniFiles
3. Create `world/` `hello.c` and `hello.h`
4. Move `hello.c` and `hello.h` to `world/`
5. Observe incorrect file system actions

### Expected behavior

"hello.c" and "hello.h" are effectively transferred to "world/".

### Actual behavior

[Screencast from 2024-01-17 15-57-43.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/68ef1c96-d33a-4522-8baa-52b70b1d1d53)

**Comment by echasnovski** [comment]
Judging by the video, you use blockwise selection to select the files. Moving files is [supposed to be done for whole lines](https://github.com/echasnovski/mini.nvim/blob/910e49d2d45e9d32c815d16cce6cea7c3b43cecf/doc/mini-files.txt#L298-L299), that is, with linewise (`V`) selection. This is because those lines are prepended with unique path index which is used to infer the move when it itself is moved.

Does using `V` to select files prior to deleting works for you?

**Comment by wroyca** [comment]
> Judging by the video, you use blockwise selection to select the files. Moving files is [supposed to be done for whole lines](https://github.com/echasnovski/mini.nvim/blob/910e49d2d45e9d32c815d16cce6cea7c3b43cecf/doc/mini-files.txt#L298-L299), that is, with linewise (`V`) selection. This is because those lines are prepended with unique path index which is used to infer the move when it itself is moved.
> 
> Does using `V` to select files prior to deleting works for you?

Linewise selection work as intended. :)

**Comment by echasnovski** [comment]
Closing then.

**Comment by wroyca** [comment]
> Closing then.

I have a feeling we'll see this open back again at some poimt, im fairness, tocking away that warnimg  in a 800 line help page isn't quite visible for something that important. ;)

**Comment by echasnovski** [comment]
> I have a feeling we'll see this open back again at some poimt, im fairness, tocking away that warnimg in a 800 line help page isn't quite visible for something that important. ;)

It is also [in README](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-files.md#manipulation).
