### ISSUE TITLE
Mini.clue does not show (or detect?) description from clues.

### ISSUE THREAD

**Issue by serialized-kirin** [echasnovski/mini.nvim#663]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.clue

### Description

If I try to provide the `desc` for my keymapping inside of the setup function instead of at the time I create the keymapping, mini.clue will show the mapping as a viable path, but the place where it would show the description is empty.

### Neovim version

NVIM v0.9.1

### Steps to reproduce

In init.lua:
1. create a mapping using `map` in vimL or `vim.keymap.set` in lua. do not provide the `desc`. 
2. setup mini.clue, provide the trigger for the keymap and add a `desc` in the clue for that mapping. 

In new nvim instance:
1. hit the initial trigger key. 

Example init.lua:
```lua
-- directly loading mini.nvim
local minipath = vim.fn.stdpath("data") .. "/lazy/mini.nvim"
vim.opt.rtp:prepend(minipath)

vim.g.mapleader = ' '
vim.cmd [[
  nnoremap <Leader>b :buffers<CR>
  nnoremap <Leader>l :help lsp \| only<CR>
]]

require('mini.clue').setup({ -- Register `<Leader>` as trigger
  triggers = {
    { mode = 'n', keys = '<Leader>' },
    { mode = 'x', keys = '<Leader>' },
  },

  -- Add descriptions for mapping groups
  clues = {
    { mode = 'n', keys = '<Leader>b', desc = '+Buffers' },
    { mode = 'n', keys = '<Leader>l', desc = '+LSP' },
  },
})
```
..and then pressing `<Leader>` in a new instance will just show:
![Screen Shot 2024-01-19 at 06 48 25](https://github.com/echasnovski/mini.nvim/assets/67888548/0877ea85-0471-4ef7-91e7-45c193ba3f61)

### Expected behavior

The window showing the next possible keys should show a description for the options I mapped.

### Actual behavior

The window only shows the keybinding, but not the description.

**Comment by echasnovski** [comment]
Thanks for the issue.

This works [as expected](https://github.com/echasnovski/mini.nvim/blob/910e49d2d45e9d32c815d16cce6cea7c3b43cecf/doc/mini-clue.txt#L79-L82). The reason for this is for user to always be aware that there is a mapping behind certain clues. If user is not responsible for creating the mapping but still wants to show clue about it, there is a dedicated [`set_mapping_desc()`](https://github.com/echasnovski/mini.nvim/blob/910e49d2d45e9d32c815d16cce6cea7c3b43cecf/doc/mini-clue.txt#L623) to add description to existing mapping.

**Comment by serialized-kirin** [comment]
ahh, so that's what that function is for... 😅 thanks.
