### ISSUE TITLE
mini.sessions Issue with restoring Neo-Tree

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#670]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

When Saving and Restoring a Session with Neo-Tree open, an Empty Buffer gets restored. This buffer also isn't recognized as Neotree as running :Neotree toggle, open another Neo-tree Instance.

### Neovim version

0.9.5

### Steps to reproduce

- Install mini.sessions and neo-tree
- require('mini.sessions').write('testing')
- restart neovim
- require('mini.sessions').read('testing')

### Expected behavior

The best option would be to properly restore Neo-tree to how it was. If this isn't possible, allowing the exclusion of certain buffer types from the Session might works as a workaround. I personally don't need Neo-Tree to be restored with the Session. This can be done with the existing hooks in the settings. But this means that Neo-Tree will always be closed when loading or saving a Session.
Wether properly saving and loading neo-tree status is in scope of this project, is another question.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

'mini.sessions' is [built to rely on built-in `mksession`](https://github.com/echasnovski/mini.nvim/blob/1cd8d7e8318071eddc536815f5cafe50b012ac29/doc/mini-sessions.txt#L8-L9). This type of behavior is aligned with how it operates. I am not sure about 100% accuracy here, but built-in sessions seem to work reliably only for windows currently displaying normal buffers.

For customizing that behavior there are indeed [hooks](https://github.com/echasnovski/mini.nvim/blob/1cd8d7e8318071eddc536815f5cafe50b012ac29/doc/mini-sessions.txt#L92-L99). As a more drastic but filetype agnostic measure, I'd suggest closing all windows which at the moment of writing contain non-normal buffer. With something like this:

```lua
local close_non_normal_windows = function()
  for _, win_id in ipairs(vim.api.nvim_list_wins()) do
    local buf_id = vim.api.nvim_win_get_buf(win_id)
    if vim.bo[buf_id].buftype ~= '' then vim.api.nvim_win_close(win_id, true) end
  end
end
require('mini.sessions').setup({ hooks = { pre = { write = close_non_normal_windows } } })
```

Closing as not planned.

**Comment by agboom** [comment]
I ran into this as well and used the `hook` workaround at first. Then I found out that I could also adjust the session options not to save blank buffers:

```lua
-- don't save blank buffers to sessions (like neo-tree, trouble etc.)
vim.opt.sessionoptions:remove('blank')
```

It doesn't restore Neo-Tree on session read, but it does prevent blank windows.
