### ISSUE TITLE
mini.map: left-align obscures numbers and primary buffer

### ISSUE THREAD

**Issue by junelva** [echasnovski/mini.nvim#673]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.map

### Description

Is there a way to cause "left" alignment of mini.map to indent the primary buffer, or is this a bug? Included a screenshot for comparison of default ("right") and "left" side setting on window.

Here is my nvim config in case you can't reproduce and it's a conflict with a different plugin. https://gist.github.com/junelva/fc1017ee4ea116d987f6abbcf38d3bb8

I also think that during left alignment the scroll line would look better on the right. Is that possible?

![image](https://github.com/echasnovski/mini.nvim/assets/2194619/b23c6e1a-c45b-4dd3-b3a8-5087be7d30d3)

### Neovim version

0.9.5

### Steps to reproduce

1. Configure mini.map window.side = "left".

### Expected behavior

The map creates space for the primary text buffer and number columns.

### Actual behavior

The map overlays the number columns and primary text buffer.

**Comment by echasnovski** [comment]
Thanks for the issue!

> Is there a way to cause "left" alignment of mini.map to indent the primary buffer, or is this a bug?

Both left and right alignment are implemented using floating windows which are drawn on top of normal windows. Affecting normal windows in any way (like moving them to not be shown beneath the map window) is out of scope.

> I also think that during left alignment the scroll line would look better on the right. Is that possible?

In theory it is possible to implement but, unfortunately, also outside of scope. The initial primary use case for left alignment is to temporarily move map window from right to see text beneath it. So doing any additional adjustments for text in the map window is too costly maintenance-wise for the intended use case.

Closing as not planned.
