### ISSUE TITLE
Visual selection for comment textobject

### ISSUE THREAD

**Issue by drybalka** [echasnovski/mini.nvim#675]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.comment

### Description

Standard (neo)vim textobjects work both in operator mode and in visual mode, unlike the mini.comment textobject.

### Neovim version

0.9.5

### Steps to reproduce

With the following config:
```
comment.setup {
  mappings = {
    comment = '<Space>c',
    comment_visual = '<Space>c',
    comment_line = '<Space>cc',
    textobject = 'ic',
  },
}
```

### Actual behavior

`dip` - deletes paragraph
`dic` - deletes comment block
`vip` - selects paragraph
`vic` - does nothing

### Expected behavior

`vic` should select the comment block

**Comment by echasnovski** [comment]
Thanks for the issue! Indeed, I can reproduce.

The reasoning for this was that the default mappings for both textobject and visual commenting are the same (for historical reasons). As it is not possible to implement with defaults, textobject only works in Operator-pending mode (like after `d`, `c`, etc.).

I guess the better approach would be to create Visual mode mapping for textobject if keys are different from `mappings.comment_visual`. I'll look into it.

**Comment by Susensio** [comment]
@drybalka  In case you want the best of both words, this allows me **with the same keymap** to select textobject when visual selecion is empty, and comment visual selection otherwise

```lua
function M.is_visual_selection_empty()
  -- works even without exiting visual mode
  if vim.fn.mode() == 'V' then
    -- VISUAL-LINE
    return false
  elseif vim.fn.mode() == 'v' then
    -- VISUAL (char)
    local start_pos = vim.fn.getpos('.')
    local end_pos = vim.fn.getpos('v')
    return vim.deep_equal(start_pos, end_pos)
  else
    return false
  end
end

      -- remap comment_visual for allowing textobject when empty selection
      vim.keymap.set(
        "x",
        "gc",
        function()
          if require("utils").is_visual_selection_empty() then
            return [[:<c-u>lua MiniComment.textobject()<CR>]]
          else
            return [[:<c-u>lua MiniComment.operator('visual')<cr>]]
          end
        end,
        { desc = "Comment selection", expr = true }
      )

```
