### ISSUE TITLE
mini.trailspace highlights Lazy startup screen 

### ISSUE THREAD

**Issue by KyleKing** [echasnovski/mini.nvim#677]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

trailspace

### Description

When opening the lazy.nvim buffer, the trailing spaces are highlighted. See screenshot below.

### Neovim version

NVIM v0.9.5

### Steps to reproduce

With default lazy.nvim configuration:

```lua
-- [[ Install `lazy.nvim` plugin manager ]]
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup("plugins")
```

And call:

```
:lua require("lazy").home()
```

Based on #631, I've tried adding this line *before* `lazy.setup`

```lua
vim.cmd "autocmd FileType lazy lua vim.b.minitrailspace_disable = true"
```

### Actual behavior

<img width="1228" alt="Screenshot 2024-01-31 at 06 31 01" src="https://github.com/echasnovski/mini.nvim/assets/3784339/babb48fd-8193-43a5-bc64-e6ff378d8cec">

**Comment by KyleKing** [comment]
Looks like the `autocmd` was working, but the highlights were persisted:

```txt
Note: after disabling there might be highlighting left; it will be removed after next highlighting update (see |events| and `MiniTrailspace` |augroup|).
```

This seems to be working, but I'm open to better solutions:

```lua
{
  "echasnovski/mini.trailspace",
  event = "BufRead",
  opts = {},
  init = function()
    -- Hide trailing spaces in Lazy plugin buffer
    -- Tip: check FileType with `:set filetype?`
    vim.cmd "autocmd FileType lazy lua require('mini.trailspace').unhighlight()"
  end,
}
```

From my dotfiles: https://github.com/KyleKing/nvim/commit/dbafb26cf22ea6648059adb18aa3b1c1d61fad80

**Comment by echasnovski** [comment]
> This seems to be working, but I'm open to better solutions:

Yes, this is a suggested solution. Setting buffer local variable will make sure that highlighting will not be added in the future. As 'mini.trailspace' can not track setting a buffer local variable in a reasonable way, it can not know when to automatically undo possibly present highlighting. Thus calling `unhighlight()` once is the solution here.

I would still suggest doing both buffer-local variable and unhighlighting:
```lua
vim.cmd('autocmd FileType lazy lua vim.b.minitrailspace_disable = true; MiniTrailspace.unhighlight()')
```

**Comment by KyleKing** [comment]
Thanks!
