### ISSUE TITLE
LSP rename errors, when using dressing.nvim vim.ui.input

### ISSUE THREAD

**Issue by BenjaminKern** [echasnovski/mini.nvim#68]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.cursorword mini.indentscope

### Description

 In combation with vim.ui.input from [dressing.nvim](https://github.com/stevearc/dressing.nvim) LSP renaming issues, see attached logs and gif
![bug](https://user-images.githubusercontent.com/261473/166109535-c0707d67-5dcc-4bc2-a644-cff5dcd9a4b8.gif)
[bug.log](https://github.com/echasnovski/mini.nvim/files/8597096/bug.log)

### Neovim version

v0.8.0-dev+6-gae325e627

### Steps to reproduce

Unfortunately, I am not sure if it is a issue with some mini module or with dressing.nvim (or related to vim/matchparen.vim). In order to reproduce, do a LSP rename more than once in an open buffer, with dressing.nvim, mini.indentscope and mini.cursorword enabled

### Expected behavior

I should be able to do a LSP rename more than once, with [dressing.nvim](https://github.com/stevearc/dressing.nvim) enabled.

### Actual behavior

I can only do a LSP rename once with with [dressing.nvim](https://github.com/stevearc/dressing.nvim) enabled.

**Comment by echasnovski** [comment]
I briefly had some issues with 'dressing.nvim' in my full setup, but it worked with minimal setup (only 'dressing.nvim' and some 'mini.nvim' module set up).

Could you, please, try to narrow it down to a minimal config that at least somehow indicates that the problem is indeed in some of 'mini.nvim' modules? Something like "Before adding the module it works, but not after"?

**Comment by BenjaminKern** [comment]
Sure, I will try to narrow it down. In addition, thanks for this awesome plugin collection!

**Comment by echasnovski** [comment]
Thanks. If not, I think I'll have some time tomorrow to try and find whether it is a 'mini.nvim' issue.

By the way, congratulations on your first Github issue! This helps a lot!

**Comment by BenjaminKern** [comment]
So I found the culprit, it is related to mini.completion, reproducable with the following config
```
vim.call('plug#begin', plugged_path)
Plug('echasnovski/mini.nvim')
Plug('neovim/nvim-lspconfig')
Plug('stevearc/dressing.nvim')
vim.call('plug#end')

require('mini.completion').setup()

local on_attach = function(client, bufnr)
end

require('lspconfig').clangd.setup({
  on_attach = on_attach,
})
```

now move to a symbol which you want rename and call
```
:lua vim.lsp.buf.rename()
```
twice to rename the symbol. It will fail on the second try. If you remove the line 
```
require('mini.completion').setup()
```
from the config everything works as intended.

**Comment by BenjaminKern** [comment]
> Thanks.
> 
> I think I'll have some time tomorrow to try and find whether it is a 'mini.nvim' issue.
> 
> By the way, congratulations on your first Github issue! This helps a lot!

Yay loooong time lurker 😄

**Comment by echasnovski** [comment]
> So I found the culprit, it is related to mini.completion, reproducable with the following config

Great, thanks! That helped a lot.

I seems like autocompletion from 'mini.completion' doesn't play nice with 'dressing.nvim'. I *think* it might be due to somewhat complex handling of completion in 'dressing.nvim', but will investigate further.

If you can live without completion in the input, try adding this line to your config:
```lua
vim.cmd('au FileType DressingInput lua vim.b.minicompletion_disable = true')
```

It disables completion altogether in these popups. Meanwhile, I'll try to find a possibly better solution.

**Comment by BenjaminKern** [comment]
Nice, I am completely fine with this workaround.

**Comment by echasnovski** [comment]
I looked through 'dressing.nvim' code and it seems that disabling an external completion is the preferred solution at the moment. Opened an issue there to clarify.
Thanks again for tracking this down!
