### ISSUE TITLE
(mini.starter) unnecessary slowdown while checking is_something_shown

### ISSUE THREAD

**Issue by fbuchlak** [echasnovski/mini.nvim#680]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

Opening large files directly with nvim + mini.starter causes unnecessary slowdown

### Neovim version

v0.10.0-dev-2218+ga757195a6-dirty

### Steps to reproduce

1. `yes mini | head -n 500000 > example-file`
2. `nvim example-file`

This takes starter around 30ms to check if there is something shown

### Expected behavior

run checks in reverse order to speed up process (args, buffers, lines)

### Actual behavior

processing time of M.is_something_shown is slow
with large json files (~18M, ~750000 lines) it takes around 150ms (according to lazy.nvim profiler)

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I could reproduce this. Should now be fixed on latest `main` (ended up also slightly improving check for actually shown lines, hence didn't merge #681 right away).
