### ISSUE TITLE
[mini.completion] string "MiniCompletion.signature-help" appears as type for some completion items

### ISSUE THREAD

**Issue by JSteitz** [echasnovski/mini.nvim#684]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

_**NOTE:** This can be a one-time occurrence or not, so I would not put it in high priority._

Some completion items have the type `MiniCompletion:signature-help`

I do not know how this actually happens. And for now, it only happens in one of my Files.
What I can currently see, when this happens:

* Signature Help (also correctly highlighted)
* Completion list with the keyword and only those two have the wrong type

I will update this ticket if it occurs multiple times and consistently.
Maybe you have an idea, how this could happen. 

![image](https://github.com/echasnovski/mini.nvim/assets/677821/fb6d286b-9854-4c7f-92a0-626ce78a816d)

Config
```lua
-- Plugin: mini.completion
MiniCompletion.setup({
  window = {
    info = {
      border = 'single',
    },
    signature = {
      border = 'single',
    }
  },
})
```

### Neovim version

0.9.5

### Steps to reproduce

I do not know how to reproduce

### Actual behavior

Internal buffer name is used as type.

**Comment by echasnovski** [comment]
Thanks for the issue!

This is how default fallback completion (via `<C-n>`) works: it shows as "kind" the buffer name. The steps to reproduce this is to type a word which triggers fallback completion and is present in signature help. Example for empty Lua file: `string.find(` followed by `patt`.

Closing as not an issue per se.

**Comment by JSteitz** [comment]
Just to confirm.
It is mixed into the completion list from the LSP. Is this still the same behavior?

**Comment by echasnovski** [comment]
> Just to confirm. It is mixed into the completion list from the LSP. Is this still the same behavior?

I am almost certain that it can not be mixed with candidates from LSP. If you could show that (at least on screenshot without reasonable doubt) then it would be interesting.

**Comment by JSteitz** [comment]
![image](https://github.com/echasnovski/mini.nvim/assets/677821/ea028be1-7b0d-4765-906a-6813f5b0cf9e)

Basically, it overwrites them.

**Comment by echasnovski** [comment]
> ![image](https://private-user-images.githubusercontent.com/677821/303650725-ea028be1-7b0d-4765-906a-6813f5b0cf9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODMwNjEsIm5iZiI6MTcwNzQ4Mjc2MSwicGF0aCI6Ii82Nzc4MjEvMzAzNjUwNzI1LWVhMDI4YmUxLTdiMGQtNDc2NS05MDZhLTY4MTNmNWIwY2Y5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjQ2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGQ0MmU4MWU1MTdlYjcyOTMzMzA4NjA3ZDFmOTdhNGNmZmJmNTgxZGNmNmEyZDE3NGU0MWQ3NWU3OGMyZmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vjyy894tPGL9WzfSnHXbqMuYqDYizB7OLHI5DGTItTU)
> 
> Basically, it overwrites them. Some more info:

This is the result of the default fallback action, not LSP step. If this came from LSP, the text on the right ("kind" entry of completion list) would be the one from LSP completion protocol (like "Function", "Class", etc.; taken [from here](https://github.com/neovim/neovim/blob/4788abf2da6bb5c37e880d74a73a4a7de736b6ac/runtime/lua/vim/lsp/protocol.lua#L69-L93)).
