### ISSUE TITLE
mini.statusline: Create lsp string in a separate method

### ISSUE THREAD

**Issue by abeldekat** [echasnovski/mini.nvim#687]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

Hello @echasnovski,

[Using](https://github.com/abeldekat/nvim_pde/blob/7e487eadba39dbc91d458ab99c00e07c76028c79/lua/ak/config/ui/mini_statusline.lua#L27) this plugin I could dispose of many [lualine](https://github.com/abeldekat/nvim_pde/tree/cb35cae82bf13864f2e2254e915bcf807db959b6/lualine_themes/lua/lualine/themes) theme overrides. It was a joy to work with!

I added diagnostic colors as described [here](https://github.com/echasnovski/mini.nvim/issues/337).
In order to do this, I also had to include code for the `lsp`(method `MiniStatusline.section_diagnostics`).

Currently, section `diagnostics` does not show when there is no [lsp](https://github.com/echasnovski/mini.nvim/blob/37d675dadeef2fad6aa4e7f12fde0f541a396cde/lua/mini/statusline.lua#L297) attached. Is that correct? The user could miss `diagnostics` when having a `linter` instead of an `lsp`.

Would you accept a PR where the lsp string is created in a separate method?
An outline:

```lua
H.default_content_active = function()
...
  local lsp   = MiniStatusline.section_lsp({ trunc_width = 75 }) --> new
  local diagnostics   = MiniStatusline.section_diagnostics({ trunc_width = 75 })
...
  return MiniStatusline.combine_groups({
...
    { hl = 'MiniStatuslineDevinfo',  strings = { git, lsp, diagnostics } },
...
  })
end
```

Best regards!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

> Currently, section `diagnostics` does not show when there is no [lsp](https://github.com/echasnovski/mini.nvim/blob/37d675dadeef2fad6aa4e7f12fde0f541a396cde/lua/mini/statusline.lua#L297) attached. Is that correct? The user could miss `diagnostics` when having a `linter` instead of an `lsp`.

Oh, you are completely right! This somehow slipped past me when I implemented this.

Right now, I don't particularly see much use in having separate `LSP` section (which would show server info, I presume?). Let me think about the possibly best way to resolve this.

**Comment by abeldekat** [comment]
There is not much use in having a separate `LSP` section I think. 

It would mean however that I don't have to copy the `lsp` code from `mini.statusline` into my own config. I quite like the default implementation.
The code handling the `lsp` string ( either `LSP` or an icon ) would not be changed, just [moved](https://github.com/abeldekat/nvim_pde/blob/c3977b27f6032b5e7131338370ff0d28963a4a10/lua/ak/config/mini_statusline.lua#L89).

I do think that there is a backward compatibility problem for users with a custom `content.active` method, using `strings = { git, diagnostics }`

**Comment by abeldekat** [comment]
Hello @echasnovski,

I don't mind if this issue were to be closed. The current situation is fine, and I customized some more parts.

Best regards!

**Comment by echasnovski** [comment]
Let this be open for now. I do plan a 'mini.statusline' update some time soon-ish and this will be one thing to keep in mind.

**Comment by echasnovski** [comment]
I have finally reached the first part of 'mini.statusline' refactor. The `section_diagnostics()` now depends exclusively on what data is returned by `vim.diagnostic.get()`. See [changelog entry](https://github.com/echasnovski/mini.nvim/blob/main/CHANGELOG.md#ministatusline) for more details.

It also means that the icon is not shown if there is no diagnostic entries in the buffer. Previously it served as an indicator that LSP server was attached to the buffer. Now there is a `section_lsp()` in default active content that serves this exact purpose.

**Comment by abeldekat** [comment]
Thanks @echasnovski!
