### ISSUE TITLE
Jump consumes characters when it cannot find the target

### ISSUE THREAD

**Issue by ghostbuster91** [echasnovski/mini.nvim#688]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Jump

### Description

Hi, for the context, I am the author of https://github.com/ghostbuster91/nvim-next

When trying to implement dot-repeat for my custom movements (`f`/`t`/etc) and failing miserably many times I finally came across your repository where it seems to work. Hats off to your vim-fu. 

However I noticed one bug - MiniJump consumes one character when using custom `f` motion with operator-pending and when the target does not exist. I tried fixing it myself but without luck.
I even tried deleting the whole body of the function that is being passed to the expr but the character was still being consumed.

### Neovim version

0.9.5

### Steps to reproduce

I changed `jump.lua` file so that it would invoke the setup when sourced:
```diff
diff --git a/jump.lua b/jump.lua
index d5b0c9c..d7a1959 100644
--- a/jump.lua
+++ b/jump.lua
@@ -488,4 +488,6 @@ function H.map(mode, key, rhs, opts)
     vim.api.nvim_set_keymap(mode, key, rhs, opts)
 end
 
+MiniJump.setup()
+
 return MiniJump
```

1. `nvim -nu jump.lua`
2. open any file with some text inside
3. type `dfk` on a line where there is no `k` 

### Expected behavior

Nothing should happen when there is no target in the current line.

### Actual behavior

One character is consumed. The same happens when we repeat action with `.`

**Comment by echasnovski** [comment]
Thanks for the issue!

I am not quite sure what is the essence of the issue.

'mini.jump' defines its own mappings for `f`, `F`, `t`, `T`, `;` making them work across multiple lines. Pressing `dfk` on a line where there is no "k" should delete text up until and including the next "k" in the lines below.

Would you mind clarifying what exactly you mean by "cosumes characters"? And, please, provide reproducible example which does not alters module's code.

**Comment by ghostbuster91** [comment]
Sure, here is the minimal config to reproduce the issue:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      { 'echasnovski/mini.nvim', branch = 'stable' }
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

_G.setup = function()
    require('mini.jump').setup()
end
```

and here is an example input where the issue can be observed:
```
alice bob mark
alice
```

Put your cursor on the first line, call `dfm`, this will delete all characters up to `m` included. Repeat command using `.` operator. It sometimes works as expected (nothing happens, but you can undo changes and retry the sequence and it will start consuming characters).

[Kooha-2024-02-11-10-54-08.webm](https://github.com/echasnovski/mini.nvim/assets/5662622/4d2d0538-ff13-492a-981b-d099b0b68b21)

**Comment by echasnovski** [comment]
> and here is an example input where the issue can be observed:
> 
> ```
> alice bob mark
> alice
> ```

Ah, yes, now I see what you mean. Thanks, I can reproduce! Will look into it.

**Comment by echasnovski** [comment]
Thanks again for finding this issue! It should be fixed on latest `main`.

This proved to be not a trivial fix, as it seemed right to make it dot-repeatable even if the target was not found on the first call. This forced to reside with some hackery of undoing the change if it was suspected to be done. Not really a pretty solution, but seems to work in at least most cases.
