### ISSUE TITLE
mini.jump being able to NOT ignore case

### ISSUE THREAD

**Issue by drzhivago420** [echasnovski/mini.nvim#691]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.jump

### Description

Hello, i currently have set ignorecase & set smartcase on my vimrc.
I'm enjoying the mini.jump module, but i'd prefer to keep my smartcase on / searches but not on my f/F searches.
The reasons are simple, for starters I'm already used to it functioning that way. But also, current functionality may break some custom mappings, functions or macros in my opinion.
So is it possible to configure it against my vimrc?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Respecting the values of 'ignorecase' and 'smartcase' is a [documented behavior](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-jump.txt#L21-L24) and probably won't change. It doesn't look like adding too much deal breaking functionality compared to the maintenance resulting from adding this configurability.

Closing as not planned.
