### ISSUE TITLE
mini.files navigate_to_file feature 

### ISSUE THREAD

**Issue by madushan1000** [echasnovski/mini.nvim#692]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I want to navigate to currently editing buffer path while mini.files is open and using `cwd` as anchor. 

I tried this,

```
...
  local navigate_to_cwd = function()
    buffers = vim.api.nvim_command_output("ls t")
    cbuf = tonumber(string.match(buffers, '%d+'))
    MiniFiles.open(vim.api.nvim_buf_get_name(cbuf))
  end
...
  vim.api.nvim_create_autocmd('User', {
    pattern = 'MiniFilesBufferCreate',
    callback = function(args)
      local buf_id = args.data.buf_id
      vim.keymap.set('n', '~', navigate_to_cwd, { buffer = buf_id, desc = "navigate to cwd", })
    end,
  })
...
```
But this will open mini.files using the parent of current buffers as anchor. that's not what I want to do.

would it be possible to add a new function `MiniFiles.navigate_to_file` (or some more options to `MiniFiles.refresh`) that given a path would recursively "go_out" until `cwd` or a common root under cwd is found, and then "go_in" to the file path?  I'm not sure how complex this would be to add, so I understand if you don't want to add something like this.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I think what you describing is already present: [`@` will reveal current cwd](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-files.txt#L163) with [`reveal_cwd()` being its functional alternative](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-files.txt#L732).

Opening explorer with the focus on current buffer file [has suggested solution](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-files.txt#L633-L634). Yes, it uses file's directory as anchor, but together with `reveal_cwd` I think this should be enough.

**Comment by madushan1000** [comment]
Thank you for the help, I just tried it and `reveal_cwd()` with  `MiniFiles.open(vim.api.nvim_buf_get_name(0))` works for most of my needs. 
It doesn't work very well for when I have changes in the mini.files buffer(need to sync before closing the existing mini.files buffer). but that's just a minor inconvenience.

**Comment by echasnovski** [comment]
> It doesn't work very well for when I have changes in the mini.files buffer(need to sync before closing the existing mini.files buffer). but that's just a minor inconvenience.

Not sure I am following. You don't have to sync when going outside of current 'mini.files' buffer (which is displayed inside a single pane). You can navigate inside same explorer as much as you want and sync only when you're done.

For example, you can move file from one directory to another by cutting corresponding entry in a buffer (with `dd`), navigating in the target directory, paste (with `P`), and sync (with `=`).

**Comment by madushan1000** [comment]
I think was using the wrong terminology there, 
using the config I posted in the description, workflow is like this, Open mini.files -> navigate to some directory -> open a file there -> copy a file from the selected directory -> go to  a different directory -> paste a file -> use `~` to go back to the directory of the file I opened for editing (to copy another file, etc..) mini.files asks,

```
There is at least one modified buffer

Confirm close without synchronization?
[Y]es, (N)o:
```

**Comment by echasnovski** [comment]
> ... use `~` to go back to the directory of the file I opened for editing (to copy another file, etc..) mini.files asks,

Ah, yes. The thing here is that the function uses `MiniFiles.open()`, which is not really a "navigate to" but "open an explorer at". So it tries to close the current explorer (as there can be only one explorer per tabpage).

Exporting functions to "navigate" inside particular explorer is currently not a goal.

**Comment by madushan1000** [comment]
Ah, makes sense, thanks for the help :)
