### ISSUE TITLE
"off by default" / vim.g.minipairs_disable = true & vim.b.minipairs_disable = false question

### ISSUE THREAD

**Issue by drzhivago420** [echasnovski/mini.nvim#693]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

The setup i'm trying to have is having `vim.g.minipairs_disable = true` by default, 
and then in each buffer toggle it on or off, either with a map or autocmd (`autocmd Filetype c let b:minipairs_disable=0`)

In my opinion it makes more sense to have this "off by default" setup, but it seems to clash with the way the global disable currently works.
If something is globally disabled, it doesn't matter if you turn it on in the buffer, it won't work until you enable it
globally, and that makes it "on by default"
Any workaround? Anything I'm missing?

**Comment by echasnovski** [comment]
Yes, `vim.g.minixxx_disable` disables globally and buffer-local variables won't have effect. Here is [one solution](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini.txt#L325-L326) of how to enable only in certain filetypes.

Another one would be to set `vim.b.minixxx_disable = true` for every buffer in `BufNew` and `VimEnter`, while setting it to `false` later when user needs it.
