### ISSUE TITLE
mini.files: copying does not replace files with the same name and fails silently instead

### ISSUE THREAD

**Issue by metiulekm** [echasnovski/mini.nvim#694]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When a copy operation is being done, but a file with the same name as target already exists, the operation fails silently.

Note that the docs say
```lua
--- - Copying inside same parent directory is supported only if target path has
---   different name.
```
but, if I understand this correctly, this only disallows something like `cp x x`.

### Neovim version

v0.10.0-dev-4e59422

### Steps to reproduce

No config should be needed except setting up `mini.files` (tested with `NORC`). Do

```sh
$ mkdir a b
$ echo a > a/x
$ echo b > b/x
$ nvim b
```

In mini.files, yank the `x` file, and then go to the `a` directory and paste the file there. You will see the following prompt (depending on the starting directory):

```
CONFIRM FILE SYSTEM ACTIONS

/tmp/b:
    COPY: 'x' to '/tmp/a/x'

[Y]es, (N)o:
```

Accept the prompt.

### Expected behavior

Either the operation should return an error, or `a/x` should contain `b`, like after `cp b/x a/x`.

### Actual behavior

`a/x` contains `a`, as if the operation silently failed.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, this is indeed intended: any file operation which can override currently present path is silently ignored. This includes creating a file with the already present name, copy/move/rename other file which results in the same situation. To override, first delete file you want to override, and then perform an operation.

I'll see if making this an error is a good idea.

**Comment by echasnovski** [comment]
Thanks again for the suggestion!

I opted to showing warning with `vim.notify()`. This way all "good" actions which come with the bad one are still performed without being interrupted by the error.
