### ISSUE TITLE
Add option to have cursor not animate to past the edge of the buffer when wrapping is enabled

### ISSUE THREAD

**Issue by WildRage1369** [echasnovski/mini.nvim#695]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

When wrapping is enabled, mini.animate animates the cursor as moving to past the edge of the buffer as if wrapping is disabled. An option to have a fix applied to work for wrapping would be great.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, I've noticed it too and thought about fixing it. The problem here was to compute the proper target destination and proper intermediate places. As although the line is displayed wrapped, it isn't so internally (it is still a single line). So it would need some extra work with window views which are both not trivial and might be computationally (relatively) expensive.

I'll take a second look, though.

**Comment by WildRage1369** [comment]
> The problem here was to compute the proper target destination and proper intermediate places. As although the line is displayed wrapped, it isn't so internally (it is still a single line). So it would need some extra work with window views which are both not trivial and might be computationally (relatively) expensive.

From some initial brainstorming I had the idea to do just a basic calculation where you check if the cursor position's column is 
greater than the width of the window then to do a calculation to get the displayed position rather than the internal position by subtracting the width from the column number. I am not sure exactly how this would be implemented but I hope it helps!

**Comment by echasnovski** [comment]
After having second and even third looks, I can not see an easy way to have this fixed. Computation based on the window width is bound to be problematic for various reasons (multi-byte characters, tab expansion, etc.).

So I am afraid I am going to close this issue as "would be good to fix but I don't think this is possible in reasonable way". If anyone will have a doable idea or if there will be a new Neovim function/interface to simplify this, feel free to comment here.
