### ISSUE TITLE
Complete installation instructions

### ISSUE THREAD

**Issue by horga83** [echasnovski/mini.nvim#696]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.nvim

### Description

So my rant is this:
There is no complete example of how to get your plugins running.  Maybe include an example .conf/nvim/init.lua file for those us struggling to understand all this stuff.  I tried including the mini.deps install but now how to enable a module???

I tried using vim/plug but again the module won't run, it's very frustrating when one simple example would solve the entire issue.
This seems to be a common issue with Neovim, so much assumption.  Please please provide at least one install example that also enables at least one module.  Thank you.

**Comment by echasnovski** [comment]
> So my rant is this:
> There is no complete example of how to get your plugins running. Maybe include an example .conf/nvim/init.lua file for those us struggling to understand all this stuff. I tried including the mini.deps install but now how to enable a module???
> 
> I tried using vim/plug but again the module won't run, it's very frustrating when one simple example would solve the entire issue.
> This seems to be a common issue with Neovim, so much assumption. Please please provide at least one install example that also enables at least one module. Thank you.

Module's essential functionality is enabled by calling its `setup()` function. So like `require('mini.deps').setup()`. This is done for at least two reasons:
- To provide users complete freedom as to *when* this is done. This allows a more granular startup configurations.
- As 'mini.nvim' contains more than one module and aims to allow using them independently one from another, an extra call is needed to enable plugins (if it requires any addition setup).

Here are the places you can get this information:
- Main README has [General principles](https://github.com/echasnovski/mini.nvim?tab=readme-ov-file#general-principles) section which contains the following sentence: "Each module (if needed) should be setup separately with `require(<name of module>).setup({})`...".
- [Each](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-ai.md#installation) [module](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-align.md#installation) [which](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-animate.md#installation) [needs](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-basics.md#installation) [`setup()`](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-bracketed.md#installation) [call](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-bufremove.md#installation) has the following sentence just below the "Installation" examples: "**Important**: don't forget to call `require('mini.bufremove').setup()` to enable its functionality."
- Each README near its start contains a sentence like "See more details in [Features](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-ai.md#features) and [help file](https://github.com/echasnovski/mini.nvim/blob/main/doc/mini-ai.txt)." which links to help file, where every module which needs `setup()` has this mentioned in the "Setup" section (here is an [example from 'mini.ai'](https://github.com/echasnovski/mini.nvim/blob/abe865bc11f6dfc455ffe17d1ef6a21d7dd2378b/doc/mini-ai.txt#L62-L66)).
- As you've looked at 'mini.deps', its README [contain "Overview"](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-deps.md#overview) section which links to [example 'init.lua' file](https://github.com/echasnovski/mini.nvim/blob/main/scripts/init-deps-example.lua) in its first sentence followed by instructions on how to try it safely.

I hope that is enough mentions.

------

@horga83, please, refrain from unnecessarily generalized "rants" on this platform.

**Comment by horga83** [comment]
Thank you I have it working, this is my init.lua, is this the correct
way to do it?

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
 vim.fn.system({
 "git",
 "clone",
 "--filter=blob:none",
 "https://github.com/folke/lazy.nvim.git",
 "--branch=stable",
 lazypath,
 })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
 { 'echasnovski/mini.nvim', version = '*' },
})

require('mini.pairs').setup()
require('mini.comment').setup()

Now presumably I could add options to the setup() for each plugin?
Also change keymaps?

Thank you
George

**Comment by echasnovski** [comment]
> Now presumably I could add options to the setup() for each plugin? Also change keymaps?

Configuring is done by supplying an appropriate table inside `setup()` function. Structure of the table depends on the module and is described both in the README and at the `MiniXXX.config` tag in help file.
