### ISSUE TITLE
Cmdheight not restored when exiting Mini.Pick resume

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#698]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Pick

### Description

Cmdheight is not restored when entering and exiting Mini.Pick resume.

 

### Neovim version

NVIM v0.10.0-dev+2324-g4948fa42e

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `set cmdheight=0`
3. `lua MiniPick.builtin.files()`
4. close
5. `lua MiniPick.builtin.resume()`
6. close

### Expected behavior

Restore cmdheight when exiting "resume"

### Actual behavior

[Screencast from 2024-02-13 12-48-08.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/b0034639-ba4e-4946-9af0-d1023679610f)

**Comment by echasnovski** [comment]
Thanks for the issue!

Indeed, I can reproduce. Will look into it.

**Comment by echasnovski** [comment]
Should now be fixed on latest `main`.

As per famous quote about hard things in computer science, `builtin.resume()` cleared cached after it was being used to keep track for 'cmdheight'.

**Comment by wroyca** [comment]
> Should now be fixed on latest `main`.
> 
> As per famous quote about hard things in computer science, `builtin.resume()` cleared cached after it was being used to keep track for 'cmdheight'.

Thank! :partying_face:
