### ISSUE TITLE
statusline breaks with lsp diagnostics count

### ISSUE THREAD

**Issue by Jackevansevo** [echasnovski/mini.nvim#699]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

statusline

### Description

Using `mini.statusline` in conjunction with LSP blows up when attempting to check the diagnostic count. 

This breaks regardless of whether the LSP configuration is done before or after the statusline setup()

### Neovim version

v0.10.0-dev-1805+gec3c569dd-Homebrew

### Steps to reproduce

1. `nvim -nu minimal.lua`

```lua
-- Clone 'mini.nvim' manually in a way that it gets managed by 'mini.deps'
local path_package = vim.fn.stdpath('data') .. '/site/'
local mini_path = path_package .. 'pack/deps/start/mini.nvim'
if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing `mini.nvim`" | redraw')
  local clone_cmd = {
    'git', 'clone', '--filter=blob:none',
    'https://github.com/echasnovski/mini.nvim', mini_path
  }
  vim.fn.system(clone_cmd)
  vim.cmd('packadd mini.nvim | helptags ALL')
end

-- Set up 'mini.deps' (customize to your liking)
require('mini.deps').setup({ path = { package = path_package } })
local add = MiniDeps.add

add({
  source = 'neovim/nvim-lspconfig',
  -- Use 'master' while monitoring updates in 'main'
  checkout = 'master',
  monitor = 'main',
})

require('mini.statusline').setup()


-- Can be any LSP
local lspconfig = require('lspconfig')
lspconfig.jedi_language_server.setup{}
```

### Actual behavior

```
E5108: Error executing lua ...m/site/pack/deps/start/mini.nvim/lua/mini/statusline.lua:607: attempt to call field 'count' (a nil value)
stack traceback:
        ...m/site/pack/deps/start/mini.nvim/lua/mini/statusline.lua:607: in function 'get_diagnostic_count'
        ...m/site/pack/deps/start/mini.nvim/lua/mini/statusline.lua:301: in function 'section_diagnostics'
        ...m/site/pack/deps/start/mini.nvim/lua/mini/statusline.lua:544: in function <...m/site/pack/deps/start/mini.nvim/lua/mini/statusline.lua:540>
```

**Comment by echasnovski** [comment]
Thanks for the issue!

The Neovim Nightly version "v0.10.0-dev-1805+gec3c569dd-Homebrew" is a bit too old (about 2 months, from December 9). Please update Neovim to include at least [this commit](https://github.com/neovim/neovim/commit/4ee656e4f35766bef4e27c5afbfa8e3d8d74a76c) from January 1. Or use latest stable release Neovim 0.9.5.

As 'mini.statusline' [was updated on January 30](https://github.com/echasnovski/mini.nvim/commit/449dd120616fdeb75a57c154002910c108790752) to use this function for extra performance, assuming one month for Nightly users should be enough to have it updated.

As a general rule of thumb, using Neovim Nightly assumes a frequent update and the latest available version for issue reports.
