### ISSUE TITLE
An opinionated init.lua that allow people use mini.nvim like a distro

### ISSUE THREAD

**Issue by ofseed** [echasnovski/mini.nvim#700]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

most of the modules

### Description

It should not cause conflict if we put an `init.lua` file under the `lua/` directory, and we can make mini.nvim like a distro by leveraging that.

If we implement this, we can clone mini.nvim as a nvim configuration repository to `.config/nvim`, and get all the great features provided by mini.nvim, so that we can easily get a good experience when using neovim even on a temporary machine.

And I think maybe calling `setup` to every module of mini.nvim would be enough.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, something like this *is* planned, but it will be a separate project outside of this plugin. There needs to be a couple more modules implemented to provide a solid user experience, so there is currently no time scale for when this should be expected to be done.

Closing as "planned, but not here".
