### ISSUE TITLE
Auto-yank comments

### ISSUE THREAD

**Issue by adamtabrams** [echasnovski/mini.nvim#701]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.comment

### Description

I want the text being commented to also be yanked.

Most often it's one or more lines of code that I plan to comment out, then paste and modify.
This could be an `option` or setup in `hooks`.
I've able to accomplish the same with other plugins, but only because of specific functions they provide.

Example:
```lua
    "numToStr/Comment.nvim",
    opts = {
      pre_hook = function(ctx)
        local lines = require("Comment.utils").get_lines(ctx.range)
        vim.fn.setreg("+", lines)
      end,
    },
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Having hooks take some context data seems reasonable enough to add, so it now should be in `main` branch.

Here is a [list of fields](https://github.com/echasnovski/mini.nvim/blob/14dee9cccaea6a5b4d1e085a202752517c02ce82/doc/mini-comment.txt#L142-L146) that hooks now can use. Beware that those same hooks are called both for comment toggling and computing textobject, so `line_start` and `line_end` won't always be present in `pre` hook.

Here is a snippet which achieves similar goal to the one from original comment:

```lua
local yank_lines = function(data)
  if data.action ~= 'toggle' then return end
  local lines = vim.api.nvim_buf_get_lines(0, data.line_start - 1, data.line_end, false)
  vim.fn.setreg('+', lines)
end
require('mini.comment').setup({ hooks = { pre = yank_lines } })
```
