### ISSUE TITLE
Funky highlight in picker

### ISSUE THREAD

**Issue by Susensio** [echasnovski/mini.nvim#703]
This will be a shitty bug report... I am looking for help on how to debug this.

### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Sometimes I get a red color inside picker elements.

### Neovim version

v0.9.5

### Steps to reproduce

I do not know how to reproduce this, nor how to debug it...

### Expected behavior

No funky highlights

### Actual behavior

A slash and an icon is highlighted on redish.
![image](https://github.com/echasnovski/mini.nvim/assets/11474625/d6cbb351-b3e6-4886-83bb-1f7f0ff677ca)
It does not always appear, nor it does in the same spots.

I cannot find a way to debug this, because i cannot navigate inside the picker elements.

**Comment by echasnovski** [comment]
Hm... I have not seen this in the wild.

I'd start with two steps:
- You seem to have some custom setup to update statusline when picker is active. Is it publicly available? Try to  disable it and see.
- Good old config bisecting: comment out all plugins/settings and gradually add half of what is left until you can reproduce this.

My initial intuition is that the buffer which picker is displaying got some syntax highlighting enabled (maybe Lua?).

**Comment by echasnovski** [comment]
Yeah, indeed, I can reproduce. Both in 0.9.5 and Nightly. I'll take a look, but this seems like a Vim's 'matchparen' issue.

**Comment by echasnovski** [comment]
Although I do think this is more of an issue in Neovim (neovim/neovim#25099), it had an easy fix with good side effects probably beyond 'matchparen'. Should now be fixed on `main` branch.
