### ISSUE TITLE
Separator character in mini.statusline

### ISSUE THREAD

**Issue by bdillahu** [echasnovski/mini.nvim#704]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.statusline

### Description

Any thoughts of having a separator character option between sections in mini.statusline to support some of the "angled" or "rounded" dividers you see in lualine and others?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

All sections in 'mini.statusline' are plain functions which return strings. It is left to user to combine them however they want. [Here is how it is done by default](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-statusline.txt#L81-L98). For the most common case of combining groups, there is [`combine_groups()`](https://github.com/echasnovski/mini.nvim/blob/78a4d457718060fe80480c72a7d64f6b23472d63/doc/mini-statusline.txt#L161) which is a bit smarter version of plain string concatenation. Outside of that it is expected to manipulate section strings manually.

Main reason for this kind of design is that it (like like it) would require almost as much code to configure inside `setup()` as to implement manually inside function. That is assuming configuration is kept flexible enough to allow different separators for different consecutive sections/groups.

Closing as not planned.

**Comment by pablopunk** [comment]
I had a bit of trouble getting this to work within my `combine_groups` fn. [Here's my current setup](https://github.com/pablopunk/dotfiles/blob/2db924ce73726af11d3760d68b0f0c8a95f306c9/nvim/.config/nvim/lua/plugins/mini.lua#L76-L88) in case anyone's interested, using this custom function:

```lua
function create_statusline_separator(before_hl, after_hl, char)
  local hl_name = string.format("Statusline%s%s", before_hl, after_hl)
  vim.cmd(
    string.format(
      [[ hi! %s guifg=%s guibg=%s ]],
      hl_name,
      string.format("#%06x", vim.api.nvim_get_hl_by_name(before_hl, true).background),
      string.format("#%06x", vim.api.nvim_get_hl_by_name(after_hl, true).background)
    )
  )
  return "%#" .. hl_name .. "#" .. char
end
```

<img width="900" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/4324982/cc7d6e15-a479-4b27-91c0-4e823c735cdb">

If this can be done easier or better, please ping me!

**Comment by echasnovski** [comment]
> If this can be done easier or better, please ping me!

Generally, this looks fine. However, it should be noted that this function (`config.content.active` and hence `utils.create_statusline_separator()`) will be called **very** frequently. So I'd some precomputation instead of two `nvim_get_hl_by_name` calls per `create_statusline_separator` (which is 6 calls per statusline redraw). Furthermore, I'd use this function only if either of `before_hl` or `after_hl is not known in advance, which is only for the first call.

**Comment by bdillahu** [comment]
> I had a bit of trouble getting this to work within my `combine_groups` fn. [Here's my current setup](https://github.com/pablopunk/dotfiles/blob/2db924ce73726af11d3760d68b0f0c8a95f306c9/nvim/.config/nvim/lua/plugins/mini.lua#L76-L88) in case anyone's interested, using this custom function:
> 

Thanks for this - I tried, but couldn't get there :-)

One item - if you have "mode" as one of the parameters (before_hl, after_hl) then it gets an error when you switch modes.

This may very well be a config issue on my side - it complains that 'Invalid highlight name "Insert"' or whatever

Thought I would point it out...

**Comment by pablopunk** [comment]
@bdillahu you need to pass `mode_hl`, not `mode` :)
