### ISSUE TITLE
No underlined diagnostics with coc.nvim

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#706]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

hues

### Description

[randomhue](https://github.com/echasnovski/mini.nvim/blob/main/colors/randomhue.lua) with [CoC](https://github.com/neoclide/coc.nvim) link to `DiagnosticXXX` instead of `DiagnosticUnderlineXXX`, causing it to be invisible.

https://github.com/echasnovski/mini.nvim/blob/1ad462d0c4a9c83a2202f96504aba149705485d1/lua/mini/hues.lua#L1375-L1379

### Neovim version

NVIM v0.10.0-dev+2384-g848fc8ede

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `colorscheme randomhue`
3. `highlight CocWarningHighlight`

Notice that it link to `DiagnosticXXX` instead of `DiagnosticUnderlineXXX` 

### Expected behavior

DiagnosticUnderline with Coc

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/2e64ef13-f72e-425a-a7e2-732d0092d8b2)

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/7427ed89-e93d-487d-8381-f09a346ce7d2)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Judging by [these lines](https://github.com/neoclide/coc.nvim/blob/9c079ad79d66d4ede7886cc4094a822352559502/plugin/coc.vim#L534-L556), all diagnostic related highlights from 'coc.nvim' should work out of the box.

As I don't use 'coc.nvim', would you mind testing if completely removing [these lines](https://github.com/echasnovski/mini.nvim/blob/1ad462d0c4a9c83a2202f96504aba149705485d1/lua/mini/hues.lua#L1376-L1389) give acceptable result?

**Comment by wroyca** [comment]
Hello, thank for your time!

> As I don't use 'coc.nvim', would you mind testing if completely removing [these lines from 'mini.hues'](https://github.com/echasnovski/mini.nvim/blob/1ad462d0c4a9c83a2202f96504aba149705485d1/lua/mini/hues.lua#L1376-L1390) give acceptable result?

Indeed, it does give better result, we even have proper highlight for the diagnostic float:

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/d2dc7e77-b5be-4cd5-9c5f-b8138f8f5ea4)

**Comment by wroyca** [comment]
For what it's worth, if you feel that removing them is the proper approach here, I can force the change on my PR - If however, you believe that removing them may lead to unexpected surprises, I'm also fine with just linking underline
