### ISSUE TITLE
Error E5108 in completion.lua while using typescript-tools.nvim.

### ISSUE THREAD

**Issue by adriantrunzo** [echasnovski/mini.nvim#708]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

Hello! I've been investigating switching to Neovim from regular Vim and your set of plugins has been fun to explore. Impressive work! They cover most of the functionality I am looking for.

I write a fair amount of typescript, which notoriously doesn't support LSP, but I was encouraged to find the [typescript-tools.nvim](https://github.com/pmizio/typescript-tools.nvim) plugin. I encounter the following error when trying to use typescript-tools with mini.completion:

```
E5108: Error executing lua ...m/site/pack/deps/start/mini.nvim/lua/mini/completion.lua:1307: attempt to index field 'range' (a nil value)           
stack traceback:
        ...m/site/pack/deps/start/mini.nvim/lua/mini/completion.lua:1307: in function 'get_completion_start_server'
        ...m/site/pack/deps/start/mini.nvim/lua/mini/completion.lua:1294: in function <...m/site/pack/deps/start/mini.nvim/lua/mini/completion.lua:1289>
```

I don't know if typescript-tools is constructing malformed data, nonetheless I did have a look at completion.lua. Line 1307 is:

```lua
    if type(item.textEdit) == 'table' and item.textEdit.range.start.line == line_num then
```

If I add `type(item.textEdit.range) == 'table'` after the first `and` the error goes away, but the completion is off by one character -- the `.` I typed to trigger the completion is repeated).

### Neovim version

0.9.5 (installed via hombrew)

### Steps to reproduce

Here is the init.lua I am using to reproduce the issue:

```lua
local package_path = vim.fn.stdpath('data') .. '/site'
local mini_path = package_path .. '/pack/deps/start/mini.nvim'

if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing `mini.nvim`" | redraw')

  local clone_cmd = {
    'git', 'clone', '--filter=blob:none',
    'https://github.com/echasnovski/mini.nvim', mini_path
  }
  
  vim.fn.system(clone_cmd)
  vim.cmd('packadd mini.nvim | helptags ALL')
end

require('mini.deps').setup({ path = { package = package_path } })

require('mini.completion').setup()

local add = MiniDeps.add

add({
  source = "pmizio/typescript-tools.nvim",
  depends = { "nvim-lua/plenary.nvim", "neovim/nvim-lspconfig" },
})

require("typescript-tools").setup({})

```

1. `nvim -nu init.lua`
2. Edit a new TS file like `:e problem.ts`
3. On the first line of the new file, insert `const example = { test: 1 };`.
4. On the next line, type `const problem = example.`
5. After inserting `.` on the second line, you should see the error appear.

### Expected behavior

I expect that when typing the `.`, the completion menu appears showing the available properties of the target object.

As mentioned above, if I modify line 1307 of completion.lua to the following, I see the expected behavior, but the `.` character is repeated after accepting the completion:

```lua
    if type(item.textEdit) == 'table' and type(item.textEdit.range) == 'table' and item.textEdit.range.start.line == line_num then
```

https://github.com/echasnovski/mini.nvim/assets/1218900/b1ae0079-e318-428f-b816-6231d171da06

### Actual behavior

When trying to get object completion, an error occurs:

https://github.com/echasnovski/mini.nvim/assets/1218900/d9d300ea-6c44-4966-94fc-87c431164b7b

**Comment by echasnovski** [comment]
Thanks for the issue!

Sigh... Yes, LSP specification also [allows `InsertReplaceEdit`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#insertReplaceEdit) along with `TextEdit` structure to be used in `textEdit` field. <s>That is why working with LSP is not fun.</s>

I've added changes that should fix this issue in [`completion-ts-tools`](https://github.com/echasnovski/mini.nvim/tree/completion-ts-tools) branch. This at least fixed the example in the issue, but I would like for it to be tested a bit more in the wild.

Here are the steps to try the branch:
- Add line `add({ name = 'mini.nvim', checkout = 'completion-ts-tools' })` right after `local add = MiniDeps.add`.
- Execute `:DepsUpdate`. Make sure that target state is 'completion-ts-tools' branch and confirm (`:write`).
- Restart Neovim and try to reproduce the issue.

To go back to using `main` branch:
- Remove the `add()` line for 'mini.nvim'.
- Execute `:DepsUpdate` and confirm.
- Restart Neovim.

------

Side note: Thanks for using 'mini.deps' for reproducible example!

------

Note for possible future people trying to reproduce this but have `tsserver` installed via Mason: use `require("typescript-tools").setup({ settings = { tsserver_path = '<path/to/mason>' .. '/packages/typescript-language-server/node_modules/typescript/lib/tsserver.js' } })` to have this set up in fresh '~/.config/nvim-ts-tools' config.

**Comment by adriantrunzo** [comment]
Thanks for the quick turnaround. The `completion-ts-tools` branch does solve the issue for me. I'll continue to use that branch and let you know if I run into any other issues. I appreciate the instructions.

**Comment by echasnovski** [comment]
Thanks for the confirmation!

I've merged this in `main` branch now, as it looks like it should work (at least according to LSP specification). I'd suggest to move back to `main` branch now (as described in my previous comment).

Welcome to Neovim :)
