### ISSUE TITLE
Text garbled when pasting text from OS causes scrolling with mini.animate

### ISSUE THREAD

**Issue by ctranstrum** [echasnovski/mini.nvim#709]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

If I paste from the OS using Cmd-V in iTerm2 while mini.animate is enabled, and the amount of text being pasted causes the screen to scroll part way through, mini.animate moves the cursor during the paste and causes the text to become scrambled.

Workaround is to "zt" and paste a small amount of text at a time or to disable mini.animate before pasting.

I also attempted the proposed workaround in #275, but like the original poster there, I got an error: Lua Diagnostics.: Duplicate field `paste`, and it didn't help. Using `"+p` does work, though.

Would be nice if mini.animate could tie into a system paste (neovim can detect this, since you don't have to be in insert mode to paste text with Cmd-V, so hopefully it also exposes it somehow) and temporarily disable animation for the duration of the paste.

### Neovim version

0.9.5

### Steps to reproduce

1. `nvim -nu minimal.lua`

```lua
-- Fix the janky mouse scrolling with mini.animate
local anim_loaded, animate = pcall(require, 'mini.animate')
if anim_loaded then
  local scrolled = false
  for _, scroll in ipairs({ 'Up', 'Down' }) do
    local key = '<ScrollWheel' .. scroll .. '>'
    vim.keymap.set('', key, function()
      scrolled = true
      return key
    end, { noremap = true, expr = true })
  end

  vim.api.nvim_create_autocmd('WinScrolled', {
    callback = function()
      vim.schedule(function()
        scrolled = false
      end)
    end,
  })

  animate.setup({
    scroll = {
      enabled = false,
      timing = animate.gen_timing.linear({ duration = 150, unit = 'total' }),
      subscroll = animate.gen_subscroll.equal({
        predicate = function(total_scroll)
          if scrolled then
            return false
          end
          return total_scroll > 1
        end,
      }),
    },
  })
end
```

2. Copy a large amount of text into the system clipboard.
3. Paste into neovim.

### Expected behavior

Should paste the desired text.

### Actual behavior

Moves the cursor midway through paste, jumbling the text.

**Comment by ctranstrum** [comment]
One additional note: while trying to get a screen recording for this, I was playing around a bit with the paste settings to make it a little easier to see what is going on. When I paste super slowly, it can take forever to paste, but also, mini.animate can move the cursor rapidly enough between chunks that the paste generally works. And I also found the opposite to be true, with a fast enough paste, apparently iterm can actually send all the data before mini.animate has a chance to react, so moderate sized pasting can succeed.

However, in those in-between speeds, especially speeds that are likely to be in play during ssh sessions, mini.animate moves the cursor and messes up the paste.

https://github.com/echasnovski/mini.nvim/assets/6116062/e30d6261-56d3-482a-ba39-7c04a4970ccd

**Comment by echasnovski** [comment]
Thanks for getting back with the demo!

Reading a bit more about how `vim.paste()` (and pasting from system register in general) works, this indeed might be in issue. But only if scroll animation is enabled **and** terminal emulator implements streamed paste. That is, it pastes lines at cursor position in chunks which might trigger scroll animation (if they are big enough to move window view). And as scroll animation also changes positioning of cursor, this might lead to "scrambled" text.

The reason `"+p` seems to work is because it pastes whole text at once *and* does not move cursor to the end of the pasted text.

As I don't have access to iTerm2, could you try the following wrapper for `vim.paste` and get back with whether it has fixed the issue?

```lua
vim.paste = function(_, phase)
  if phase == -1 or phase == 3 then vim.fn.feedkeys('"+p', 'nx') end
end
```

I've tested that this works in `st` and `xfce4-terminal` (both only implement non-streaming paste), `Kitty` and `Ghostty` (both implement proper streamed paste). It does not work with `WezTerm` (which does not implement proper streamed paste), so using plain `"+p` is recommended here.

**Comment by ctranstrum** [comment]
Yes, that paste function wrapper does indeed work correctly. Thanks for providing the research for that!

**Comment by ctranstrum** [comment]
I combined the two overrides into one that I think I like better:

```lua
  local original_paste = vim.paste
  local cache_enable_scroll = MiniAnimate.config.scroll.enable

  vim.paste = function(lines, phase)
    if phase == 1 then
      cache_enable_scroll = MiniAnimate.config.scroll.enable
      MiniAnimate.config.scroll.enable = false
    end

    pcall(original_paste, lines, phase)

    if phase == 3 then
      MiniAnimate.config.scroll.enable = cache_enable_scroll
    end
  end
```

**Comment by ctranstrum** [comment]
https://github.com/echasnovski/mini.nvim/assets/6116062/e877cf92-8953-43d6-9e76-d47bf3b96a46

Screencast showing a slow paste with no garbling with these settings.

**Comment by echasnovski** [comment]
> I combined the two suggested overrides into one that I think I like better:
> 
> ```lua
>   local original_paste = vim.paste
>   local cache_enable_scroll = MiniAnimate.config.scroll.enable
> 
>   vim.paste = function(lines, phase)
>     if phase == 1 then
>       cache_enable_scroll = MiniAnimate.config.scroll.enable
>       MiniAnimate.config.scroll.enable = false
>     end
> 
>     pcall(original_paste, lines, phase)
> 
>     if phase == 3 then
>       MiniAnimate.config.scroll.enable = cache_enable_scroll
>     end
>   end
> ```

Yeah, this also looks like working.

------

As I don't think having this directly in 'mini.animate' is a good idea, I'll close this. Thanks for the follow-ups!
