### ISSUE TITLE
Error when trying to use lua MiniSessions.select('read') or lua MiniSessions.select('write')

### ISSUE THREAD

**Issue by dathinaios** [echasnovski/mini.nvim#71]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.sessions

### Description

When trying to use `lua MiniSessions.select('read')` or `lua MiniSessions.select('write')` I get error:

```lua
E5108: Error executing lua ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:577: (mini.sessions) There are unsaved buffers: 44.
stack traceback:
        [C]: in function 'error'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:577: in function 'error'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:182: in function <...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:154>
        ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:371: in function 'on_choice'
        ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:122: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

I checked with `:bmodified!` and I get `E84: No modified buffer found`. I have managed to trace the issue down and it seems to be related to `Telescope`. When I disable it and use the default select method I get no issue.

### Neovim version

NVIM v0.7.0 Release

### Steps to reproduce

May be reproducible by using `Telescope` for selecting.

### Actual behavior

As described above.

**Comment by echasnovski** [comment]
Thanks for this!

Unfortunately, still can not reproduce. Couple of questions:
- What is a buffer number 44 (or whichever is displayed in error message)? You can see with `:buffers!` or by doing `:buffer 44`.
- How did you set up `vim.ui.select`? Locally I am trying 'dressing.nvim' with default `setup()`.

**Comment by dathinaios** [comment]
There is no buffer 44. Could it be the UI buffer that Telescope uses in `ui-select`? It may be that they don't close it before actioning the item. Following your suggestion I checked and I see that my setup included `require("telescope").load_extension("ui-select")` and that seems to be the culprit.

**Comment by dathinaios** [comment]
oh, I will just try `dressing.nvim` as it seems to be more up to date. Even the author of `ui-select` mentioned it in the open issues.

**Comment by echasnovski** [comment]
Hmmm... Even with [nvim-telescope/telescope-ui-select.nvim](https://github.com/nvim-telescope/telescope-ui-select.nvim) I can not reproduce this.
Everything is pointing to the "buffer 44" being from Telescope, but for me it still works. Could you execute `:buffers!` when Telescope prompt is visible? Type `<Esc>` to go in Normal mode, execute `:buffers!`, see which buffers are latest, try reading session. If error is shown, match buffer from error message to previous `:buffers!` output.

By the way, is this error from reading and writing always the same session? Maybe something is wrong with session file itself?

**Comment by echasnovski** [comment]
Very strange indeed.
- Do you have any custom telescope-related setup? Like autocommands, etc.
- Does the error persist with 'dressing.nvim'?

**Comment by dathinaios** [comment]
Ah yes sorry, it does persist with `dressing.nvim`.

My telescope setup is quite minimal:

```
-- more uses at: https://github.com/nvim-telescope/telescope.nvim#pickers
require("telescope").setup { }
require('telescope.actions')

vim.api.nvim_exec( 
[[
  nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>
  nnoremap <leader>fg <cmd>lua require('telescope.builtin').git_files()<cr>
  nnoremap <leader>fh <cmd>lua require('telescope.builtin').help_tags()<cr>
  nnoremap <leader>fr <cmd>lua require('telescope.builtin').oldfiles()<cr>
  nnoremap <leader>fc <cmd>lua require('telescope.builtin').commands()<cr>
  nnoremap <leader>fs <cmd>lua require('telescope.builtin').search_history()<cr>
  nnoremap <leader>fS <cmd>lua require('telescope.builtin').spell_suggest()<cr>
  nnoremap <leader>fd <cmd>lua require('telescope.builtin').diagnostics()<cr>
  nnoremap <leader>ft <cmd>lua require('telescope.builtin').treesitter()<cr>
  " nnoremap <leader>fb <cmd>lua require('telescope.builtin').buffers()<cr>
  nnoremap <leader>gl <cmd>lua require('telescope.builtin').git_commits()<cr>
  nnoremap <leader>gs <cmd>lua require('telescope.builtin').git_status()<cr>
  nnoremap <leader>gb <cmd>lua require('telescope.builtin').git_branches()<cr>
  nnoremap <leader>/ <cmd>lua require('telescope.builtin').live_grep()<cr>
  " -- keep for muscle memory but it should go >>>
  nnoremap <leader>pf <cmd>lua require('telescope.builtin').git_files()<cr>
]], false)

```

**Comment by echasnovski** [comment]
I pushed a change for `read()` to check for unsaved **listed** buffers (which Telescope buffer is not). This is a more logical behavior.

Could you, please, test if error persist under latest `main`?

**Comment by dathinaios** [comment]
Thank you for checking this! 🙂

Issue seems to have been resolved! Thanks!

I still get a different issue when trying to load some of my sessions. Interestingly I don't have any problem with loading these specific sessions simply using `so` or from the `mini.starter` screen. But when I use `read()` for one of them I get:

```lua
E5108: Error executing lua ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:194: Vim(normal):E490: No fold found
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:194: in function <...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:154>
        ...m/site/pack/packer/start/mini.nvim/lua/mini/sessions.lua:371: in function 'callback'
        ...er/start/dressing.nvim/lua/dressing/select/telescope.lua:58: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

Mind you I have some settings for remembering folds, custom folding etc. that I hardly remember what exactly they are. But since this doesn't happen when loading a session it is probably an indication that it is related to something extra that `mini.sessions` does inside `read()`.

**Comment by echasnovski** [comment]
> Issue seems to have been resolved! Thanks!

Finally! That is great to hear :)

Other issue is a #57. About when it appears... 'mini.starter' [uses `MiniSessions.read()`](https://github.com/echasnovski/mini.nvim/blob/fe764ecba07b16ea8c02cbd22bc467afbee399f2/lua/mini/starter.lua#L465) and `MiniSessions.read()` [uses `source`](https://github.com/echasnovski/mini.nvim/blob/fe764ecba07b16ea8c02cbd22bc467afbee399f2/lua/mini/sessions.lua#L194). At the moment I still lack the reproducible example and think that it is an issue in Vim itself (maybe how it handles restoring folds for files that changed outside of the session in question).

Closing this one then.
