### ISSUE TITLE
Question: How can I get completion type like demo video (function, variable, etc.)

### ISSUE THREAD

**Issue by toshmukhamedov** [echasnovski/mini.nvim#711]
Configuration:
<img width="397" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/79999469/fc63392f-c7b6-4e6f-8ba5-c6dd255de5c8">

what I got:
<img width="295" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/79999469/13da9bb3-7632-45e5-bba9-b4b71ff857da">
what I expect:
<img width="373" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/79999469/218e28d5-36a2-401b-b1c1-3ee30dab244e">

Second question: What can I put to `window.completion.border` instead of `none`?

**Comment by toshmukhamedov** [comment]
It was colorscheme issue.
It worked well with another colorscheme
<img width="311" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/79999469/7a5951f5-e3e8-4c61-9d15-e546af43629e">

**Comment by echasnovski** [comment]
Both questions from original issue is not the color scheme issues.

> How can I get completion type like demo video (function, variable, etc.)

It appears if there is an active LSP client which can provide completions for particular text.

> Second question: What can I put to `window.completion.border` instead of `none`?

See `:h vim.api.nvim_open_win()` and see its "border" option.
