### ISSUE TITLE
mini.jump - can not repeat jump with ";" - but "f" is working

### ISSUE THREAD

**Issue by thopaw** [echasnovski/mini.nvim#712]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.jump

### Description

When start jumping (e.g. `fe` to jump to the next `e`) and repeat the jump with `;` an error is shown instead jumping to the next occurance. Do the next jump with `f` is working. Going backward with ""F" or "," is also working.

mini.nvim is isntalled in version 0.11.0.
It is activated in LazyVim with 
> require("mini.jump").setup()

so the defaults of https://github.com/echasnovski/mini.jump/blob/main/lua/mini/jump.lua#L95 are used

### Neovim version

0.9.4

### Steps to reproduce

1. Open a buffer
2. start jumping (e.g. `fe` to jump to the next `e`)
3. when pressing `;` a error is shown 
    > Can not jump because there is no recent `target`.

### Expected behavior

After pressing `;` the cursor jumps to the next occurance of the searched character.

### Actual behavior

An error is shown
> Can not jump because there is no recent `target`.

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce. The following steps worked on Neovim 0.9.5 and Neovim Nightly, on 'mini.nvim' 0.11.0 and `main`:
- Open Neovim with some file containing letter `e`.
- Press `f`, `e`. It jumps to the `e`.
- Press `;`. It jumps again.

Besides that, I am fairly confident that should work as there is a [passing test specifically for that](https://github.com/echasnovski/mini.nvim/blob/0bc73241cd9c686d80ab28f4af2c04e626fb2304/tests/test_jump.lua#L811-L813).

I would like to ask you for the following steps:
- Execute `:map ;` to see if there is any conflicting mapping for `;`. Ideally this should show three mappings in different modes, all related to 'mini.jump'. Something like this:
![screenshot_2024-02-23_12:37:31](https://github.com/echasnovski/mini.nvim/assets/24854248/a6fe1755-0db8-4b86-93f5-be6a9aec0cc7)
- Disable all plugins except 'mini.jump' and try to reproduce the issue with this minimal setup.

**Comment by thopaw** [comment]
Here is the current mapping of `;`
![image](https://github.com/echasnovski/mini.nvim/assets/6630597/aaa821d2-78ef-4fd6-82ea-6416a83a2f12)

Yes, you are right.
After disable all Plugins but mini.jumo it is working.

When I activate the LazyVim plugins, the `;` jump is not working anymore

>     { "LazyVim/LazyVim", import = "lazyvim.plugins" },

When I only activate LazyVim without the plugins

>     { "LazyVim/LazyVim" },

it is working.

**Comment by echasnovski** [comment]
> Yes, you are right.
> After disable all Plugins but mini.jumo it is working.

Then it is not an issue with 'mini.jump', sorry. Closing as not related

------

There is some plugin conflicting with 'mini.jump'. Maybe it defines mapping for "f"? What is the output of `:map f`?

**Comment by thopaw** [comment]
f is not bind to mini.jump

> :map f                                                                                                    
o  f           * <Lua 372: ~/.local/share/nvim/lazy/flash.nvim/lua/flash/plugins/char.lua:119>            
x  f           * <Lua 367: ~/.local/share/nvim/lazy/flash.nvim/lua/flash/plugins/char.lua:119>            
n  f           * <Lua 366: ~/.local/share/nvim/lazy/flash.nvim/lua/flash/plugins/char.lua:119>  

Although jumping with `f` ,`F` ,`t` and `T` is working. Also repeating the jump with these keys and also `,` for going backwards

**Comment by echasnovski** [comment]
> f is not bind to mini.jump

Yeah, so the jump you see is from 'flash.nvim', not from 'mini.jump' If you wan to use 'mini.jump' specifically, don't load 'flash.nvim'.

**Comment by thopaw** [comment]
I will try that. I have to figure out how to disable this in LazyVim

Thanks for your help and thank you for these great mini-plugins

**Comment by thopaw** [comment]
With this setting within my Plugin Folder flash is disabled and mini.jump works as expected

> return {
  "folke/flash.nvim",
  enabled = false,
}

https://www.lazyvim.org/configuration/plugins#-disabling-plugins
