### ISSUE TITLE
Spurious "Title requires border to be set" when navigating to parent directory

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#713]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Files

### Description

Using MiniFiles will give a spurious "Title requires border to be set" on occasions, more specifically when navigating to the parent directory. This also happens consistently after opening and closing man page(s).

### Neovim version

NVIM v0.10.0-dev+2428-g7e008799a

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `Open help page (F1)`
3. `Quit help page`
4. `Open MiniFiles`
5. `Navigate to parent directory (H)`

### Actual behavior

[Screencast from 2024-02-24 10-14-25.webm](https://github.com/echasnovski/mini.nvim/assets/91024200/2d8842ea-3874-4096-ac18-c510d52b0960)

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce. Did you actually try it with minimal config, i.e. at least with `nvim -u NONE` and loading only 'mini.files'?

**Comment by wroyca** [comment]
> Thanks for the issue!
> 
> Unfortunately, I can not reproduce. Did you actually try it with minimal config, i.e. at least with `nvim -u NONE` and loading only 'mini.files'?

My bad, indeed I couldn't reproduce it with a clean setup, so I dissected everything to find the cause. It happens when using wincmd L in a filetype autocmd for help page. That is:

> after/ftplugin/help.lua
```lua
vim.api.nvim_create_autocmd({
  [[BufWinEnter]],
}, {
  desc = [[Use vertical split for help pages.]],
  callback = function(event)
    vim.api.nvim_exec2 ([[wincmd L]], {})
  end
})
```


1. `nvim -nu minimal.lua`
2. `Open help page (F1)`
3. `Quit help page`
4. `Open MiniFiles`
5. `Navigate to parent directory (H)`

**Comment by wroyca** [comment]
In this case, not a bug, just a mistake on my part, forgetting to keep the autocmd limited to "help" ft. :)
