### ISSUE TITLE
mini.pick doesn't open file paths containing HH:MM timestamps

### ISSUE THREAD

**Issue by jason0x43** [echasnovski/mini.nvim#714]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

If I open `MiniPick.builtin.files()` and choose a file with a name containing an HH:MM timestamp, such as `Feb_16_2024_10:40_PM.py`, the file is not opened.

The issue appears to be in `parse_path` in `mini/pick.lua`. This function has some special handling for paths containing patterns like `:10:5` that's being tripped up by timestamps.

### Neovim version

0.9.5

### Steps to reproduce

1. Create a file named `Feb_16_2024_10:40_PM.py`
2. Open nvim and call `MiniPick.builtin.files()`
3. Choose `Feb_16_2024_10:40_PM.py`
4. Note that the file is not opened

### Expected behavior

The selected file should be opened.

### Actual behavior

The selected file is not opened.

**Comment by echasnovski** [comment]
Thanks for the issue!

Yeah, indeed, I can reproduce. And yes, the culprit is indeed that `:x` / `:x:y` are treated as line / position in string items.

I'll spend some time thinking about the best solution here. Maybe somewhat surprisingly, but right now I think that the best course of action would be to say "Avoid using semicolons in file names" (which is a good advice in general, to be honest).

**Comment by jason0x43** [comment]
> Maybe somewhat surprisingly, but right now I think that the best course of action would be to say "Avoid using semicolons in file names" (which is a good advice in general, to be honest).

Generally I’d agree, but I didn’t name these files 😄

Maybe `parse_path`, or something higher in the chain, could check to see whether the path actually exists as a file and therefore doesn’t need to be parsed.

**Comment by echasnovski** [comment]
> Maybe `parse_path`, or something higher in the chain, could check to see whether the path actually exists as a file and therefore doesn’t need to be parsed.

I mean, it is possible to force items in `builtin.files()` to be tables with appropriate structure for plain file paths, but it will considerably reduce performance.

**Comment by jason0x43** [comment]
Hmm…true, that would be expensive.

Maybe the picker could just take an option that could indicate that the items are simple paths? Like `MiniPick.builtin.files({ process_paths=false })`? It might be generally useful to be able to tell the file picker that it’s only working with file paths, and that it shouldn’t try to interpret the paths as anything else.

**Comment by echasnovski** [comment]
> Hmm…true, that would be expensive.
> 
> Maybe the picker could just take an option that could indicate that the items are simple paths? Like `MiniPick.builtin.files({ process_paths=false })`? It might be generally useful to be able to tell the file picker that it’s only working with file paths, and that it shouldn’t try to interpret the paths as anything else.

It is not so much about the picker itself (as `builtin.files()` indeed always works with plain file paths), but more about `default_choose()` and some other helpers (which are written for a wider tasks). I'll look into it.

**Comment by echasnovski** [comment]
Thanks again for the issue!

I could not find a non-breaking after several attempts, so decided to go ahead and make a slightly breaking change. Now having `{ path = 'file:1:2' }` as an item will be recognized as file by `default_preview()`, `default_choose()`, and `default_choose_marked()` (previously they were still trying to parse this as `path:line:col` format).

This allowed modifying `builtin.files()` to use this table format only for paths which contain ":", making them work without much overhead. So this should be fixed on latest `main`.
