### ISSUE TITLE
When using `MiniFiles.go_in()` in a rust project, an error occurs due to inlay hints

### ISSUE THREAD

**Issue by Parsifa1** [echasnovski/mini.nvim#717]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [x] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

an error occurs When using MiniFiles.go_in() in a rust project with inlay hints:
```
Error in decoration provider vim_lsp_inlayhint.win:
Error executing lua: /usr/share/nvim/runtime/lua/vim/lsp/inlay_hint.lua:320: assertion failed!
```

### Neovim version

NVIM v0.10.0-dev-2457+ga4b444252

### Steps to reproduce

1. `nvim -nu minimal.lua`
2.  open an rust project with mini.files
3.  use `MiniFiles.go_in()` open one of .rs file

`minimal.lua`
```lua
---@diagnostic disable: undefined-global
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{ "echasnovski/mini.files", version = "*" },
	"williamboman/mason.nvim",
	"neovim/nvim-lspconfig",
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
require("mini.files").setup()
require("mason").setup()
require("lspconfig").rust_analyzer.setup({})
vim.api.nvim_create_autocmd("LspAttach", {
	desc = "General LSP Attach",
	callback = function(args)
		local bufnr = args.bufnr
		-- inlay hints
		local client = vim.lsp.get_client_by_id(args.data.client_id)
		if client and client.server_capabilities.inlayHintProvider then
			vim.lsp.inlay_hint.enable(bufnr, true)
		end
	end,
})
```

### Expected behavior

No error reported

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/31800073/8af3337a-37d5-4a76-88c4-1d36cf5b288c)

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce this. But only if opening with `l` (mapped to `go_in()`) and not `L` (mapped to `go_in()` plus close explorer). I'll take a look, but I have a feeling that this might be an upstream issue.

**Comment by Parsifa1** [comment]
I think this seems to be an upstream issue, because when I use `telescope` to do the same thing, an error also occurs.

**Comment by echasnovski** [comment]
> I think this seems to be an upstream issue, because when I use `telescope` to do the same thing, an error also occurs.

Yes, it is a Neovim issue, as I managed to reproduce this (essentially) without any plugins. I am working on a proper reproducible example and will open an issue upstream.

**Comment by echasnovski** [comment]
Confirmed that this is an upsteam issue: neovim/neovim#27645.

Closing as not an issue with 'mini.files'.
