### ISSUE TITLE
Automatic tag completition and end keyword completition for languages like lua

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#726]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.autotag, mini.endwise

### Description

Hello,
First of all I would like to thank you and am grateful for all the effort you put into building such high quality plugins which make my life easier :). One such plugin which I wanted to use was mini.pairs. But when using this plugin I will be missing out on autotag and endwise functionality provided by the plugin trio nvim-autopairs, nvim-ts-autotag and nvim-treesitter-endwise. I could just switch nvim-autopairs with mini.pairs but when I do nvim-ts-autotag which depends on indentation functionality from nvim-autopairs does not work properly afaik. Also currently there are only vim script based implementations for end keyword functionality and autotagging functionality like vim-ragtag and vim-endwise by tpope and no lua based ones.
Hence my proposal would be to something like mini.autotag and mini.endwise which provide this functionality.
mini.autotag can use the builtin tag completition if possible to auto complete tags and that is totally fine as well.
I truly feel like these plugins add great value to mini.nvim.

**Comment by 231tr0n** [comment]
Also just to add I can try developing the plugins in my free time as part of my journey to learn and delve deep into lua programming altough I highly doubt my ability in doing so. So it might take a long time but if you are intrested in accepting my work on these plugins and are willing to have plugins like these in mini.nvim in the first place, I can try developing one.

**Comment by echasnovski** [comment]
Thanks for the suggestion and enthusiasm!

And "endwise"-like functionality was one of the first module suggestions (#9). My point mentioned there (that to me it looks more like a job for snippets) still stands. And as Neovim added built-in snippet support only in current Nightly (0.10), it got delayed more than I anticipated.

So as 'mini.snippets' is indeed (hopefully) closer than ever, I am going to close with suggestion to adapt snippets for this kind of tasks.

**Comment by 231tr0n** [comment]
@echasnovski what about autotagging. Like are you considering that.

**Comment by echasnovski** [comment]
> @echasnovski what about autotagging. Like are you considering that.

At the moment - probably no. This is somewhat niche functionality which I personally don't use, so there is not real motivation to both implement and maintain. But this *might* change in the future.

**Comment by 231tr0n** [comment]
If you are willing to accept my work I can try getting a simple plugin developed for this.

**Comment by echasnovski** [comment]
I'd still have to maintain it, which comes with significant cost.

So I appreciate the enthusiasm, but the answer is "At the moment - no. Maybe later".
