### ISSUE TITLE
mini.clue

### ISSUE THREAD

**Issue by d3m1gd** [echasnovski/mini.nvim#727]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

`{ show_contents = true }` for `gen_clues.registers()` produces a lot of useless empty lines with a need to scroll through the window.

it would be good to not show lines that are completely empty, or are only whitespace, so that only relevant registers are shown

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was a deliberate choice to explicitly show that target register is empty.

Closing as not planned.
