### ISSUE TITLE
Add offset to tabline for sidebar

### ISSUE THREAD

**Issue by KennethAshley** [echasnovski/mini.nvim#73]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

tabline

### Description

mini.nvim is awesome! Thanks for all the hard work.

I'm currently using the tabline module with a file-tree plugin, nvim-tree. It would be awesome if tabline could accept a number offset that pushes it to the side of the sidebar.

Here are examples of other tabline plugins and their offset features
* https://github.com/akinsho/bufferline.nvim#sidebar-offset
* https://github.com/romgrk/barbar.nvim#integration-with-filetree-plugins

Thanks!

**Comment by echasnovski** [comment]
I thought about it, but didn't quite manage to end up with reasonable rules of when to apply this. I really don't want to introduce functionality that is targeted towards specified plugins. So a a rule of something like "if Nvim-tree is showed as sidebar..." is not really good at the moment. Besides, I personally don't really like the visuals of "moving tabline" on sidebar toggle.

I'll study your links and see if I can come up with something I'd like.

**Comment by echasnovski** [comment]
@KennethAshley, thanks for suggestion!

I tried several times to naturally fit this functionality into 'mini.tabline', but couldn't make it work in the way that feels *right*. So unfortunately, I don't think I'll add this feature.
