### ISSUE TITLE
Is it possible to perform an operation on the original text after duplication ?

### ISSUE THREAD

**Issue by StitiFatah** [echasnovski/mini.nvim#730]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.operators / multiply operator

### Description

A common operation I do when refactoring or whatever  is copying some piece of code, pasting it then commenting the original piece of code.

So one could for example go from `{foo="bar"}` to
 ```lua
-- {foo="bar"}
{foo = "bar"}
```
just with `gmm` rather than duplicating then going back to the original piece of code, commenting, then going all the way down to the duplicated piece of code to modify it, which takes significantly more time outside of this trivial example. 

Is it possible to do something like that ?

**Comment by StitiFatah** [comment]
Yes I was hesitating to post it here since it's a mix of the multiply operator and mini.comment and not really a minimal operator like those of this plugin. 

> For action on visual selection - not so much, but still doable. For full operator - not so much, as it should take a motion/textobject after itself.

Yes that's my main concern, it's not really that annoying for single lines,  it was just for the example but for more complex cases it takes significantly more efforts 

> I'll take a closer look, but not sure this will be made better in 'mini.operators' itself.

Looking out for this if it's possible, thanks !

**Comment by chrisgrieser** [comment]
For this particular case, I have written a small function that I use, which solved it for me:

```lua
function M.duplicateLineAsComment()
	local ln, col = unpack(vim.api.nvim_win_get_cursor(0))
	local curLine = vim.api.nvim_get_current_line()
	local indent, content = curLine:match("^(%s*)(.*)")
	local commentedLine = indent .. vim.bo.commentstring:format(content)
	vim.api.nvim_buf_set_lines(0, ln - 1, ln, false, { commentedLine, curLine })
	vim.api.nvim_win_set_cursor(0, { ln + 1, col })
end
```

**Comment by echasnovski** [comment]
So after thinking about it, I indeed don't think there is a good design to be had in 'mini.operators' itself to allow this "comment after multiply" action/mappings.

Closing as not planned.

------

That said, there is a `MiniOperators.config.multiply.func` which can be used to execute any action *before* multiplication is maid. With some dark Neovim magic of `vim.cmd()` and `vim.schedule()`, there is a (kind of) solution that looks like this:

```lua
local schedule_comment = function()
  local cur_line = vim.fn.line('.')
  vim.schedule(function()
    -- Comment multipled text (assumes `gc` as comment operator)
    vim.cmd("normal '[gc']")
    -- Put cursor on initial line on first non-blank character
    vim.api.nvim_win_set_cursor(0, { cur_line, 0 })
    vim.cmd("normal! ^")
  end)
end

local multiply_and_comment = function()
  local cur_multiply_func = MiniOperators.config.multiply.func
  MiniOperators.config.multiply.func = function(content)
    -- Comment multiplied lines (and only lines)
    if content.submode == 'V' then schedule_comment() end
    return content.lines
  end
  vim.schedule(function() MiniOperators.config.multiply.func = cur_multiply_func end)
  return 'gm'
end

vim.keymap.set({ 'n', 'x' }, 'gmc', multiply_and_comment, { expr = true, remap = true })
```

Now something like `gmc` followed by `ip` will comment multiplied inner paragraph (to be put *after* current inner paragraph, as any multiplied text) and put cursor on the first non-blank line. It is not 100% perfect (relies on `gc` being commenting operator, there might be some flicker, and in Visual mode it needs to wait 'timeoutlen' to make sure that `gm` mapping should be executed), but it works.
