### ISSUE TITLE
some user-defined keymaps may be overwritten by hard-coded keymaps in starter.mini

### ISSUE THREAD

**Issue by dubrayn** [echasnovski/mini.nvim#731]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

starter.mini

### Description

Hello, thanks for this very nice set of plugins !

In `lua/mini/starter.lua:1389`, some keymaps are hard-coded and overwrite some of mine (namely 'M-j' and 'M-k', which I use to navigate between windows, so I am "stuck" in any starter.mini window):

```lua
buf_keymap('<Up>', [[MiniStarter.update_current_item('prev')]])
buf_keymap('<C-p>', [[MiniStarter.update_current_item('prev')]])
buf_keymap('<M-k>', [[MiniStarter.update_current_item('prev')]])
buf_keymap('<Down>', [[MiniStarter.update_current_item('next')]])
buf_keymap('<C-n>', [[MiniStarter.update_current_item('next')]])
buf_keymap('<M-j>', [[MiniStarter.update_current_item('next')]])
```

Could there be a way to detect that these keymaps are in use and not overwrite them ? Or maybe give an optional possibility to not set any keymaps when loading starter.mini ?

Thanks in advance for your time spent reading this.

### Neovim version

NVIM v0.10.0-dev-2324+g4948fa42e

### Steps to reproduce

1. launch `nvim` with a keymap set for "M-j" in normal mode and load `mini.starter`
2. invoke `MiniStarter.open()`
3. press `<M-j>`

### Expected behavior

`nvim` should do whatever was initially mapped to "M-j" (in my case I would like to switch to another window in nvim)

### Actual behavior

`nvim` goes one entry down in starter.mini window

**Comment by echasnovski** [comment]
Thanks for the suggestion!

As 'mini.starter' has quite a big config already and was done quite a long time ago, it does not have designated `mappings` option for buffer local mappings. And I am hesitant about adding one.

What I would suggest doing is to override those buffer-local mappings inside Starter buffer:
```lua
require('mini.starter').setup()
local override_mappings = function(args)
  vim.keymap.set('n', '<M-j>', '<Cmd>wincmd j<CR>', { buffer = args.buf })
  vim.keymap.set('n', '<M-k>', '<Cmd>wincmd k<CR>', { buffer = args.buf })
end
vim.api.nvim_create_autocmd('User', { pattern = 'MiniStarterOpened', callback = override_mappings })
```

Or perhaps a more robust solution would be to delete them (buffer-local mappings, that is):
```lua
require('mini.starter').setup()
local delete_extra_mappings = function(args)
  vim.keymap.del('n', '<M-j>', { buffer = args.buf })
  vim.keymap.del('n', '<M-k>', { buffer = args.buf })
end
vim.api.nvim_create_autocmd('User', { pattern = 'MiniStarterOpened', callback = delete_extra_mappings })
```

Closing as not planned.

**Comment by dubrayn** [comment]
Your proposed "more robust solution" works perfectly, thanks !

**Comment by echasnovski** [comment]
> Is there no need to create an autogroup in case mini.starter is run more than once per nvim session?

Sure, wrapping in augroup is a cleaner approach.

Just to be clear, though: this does not have to depend whether `MiniStarter.open()` is run more than once per session, but whether the `vim.api.nvim_create_autocmd()` can be run more than once. As usually it is run once per session, it is fine for this example. But again, if you might resource config during same session, wrapping in augroup is better.
