### ISSUE TITLE
save pwd into detected sessions list

### ISSUE THREAD

**Issue by hornyjailfish** [echasnovski/mini.nvim#732]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

sessions

### Description

I dont like/want to use local session files but want to force load global session if pwd of session is same as openned vim pwd

**Comment by echasnovski** [comment]
I am not sure I fully understand. Would you mind elaborating a bit? Preferably in the form of steps and what you'd expect them to achieve.

**Comment by hornyjailfish** [comment]
i want autoload session if vim opened in specific folder without using local session file. 
I could create autocmd to check `mini.sessions.detected` table but it stores path to session file itself not path it `:cd` when loaded.
So i want another field in detected table with path it :cd into.

**Comment by echasnovski** [comment]
I see.

I don't think this is a good idea. Local session files are the way to use current directory specific sessions. Plus having current directory stored would not immediately prove useful for 'mini.sessions' itself, as there can be multiple sessions with the same current directory (hence, no guaranteed way to decide which session should be autoloaded).

Closing as not planned.
