### ISSUE TITLE
cmdheight=0 cause mini.statusline disappear or flicker on <cmd> keymap

### ISSUE THREAD

**Issue by tkkcc** [echasnovski/mini.nvim#733]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

set a keymap which contains `<cmd>`
set cmdheight=0

press this keymap will cause statusline to disappear,
screenshot:

https://github.com/echasnovski/mini.nvim/assets/17373509/5f0475c7-8194-4e93-81bd-5fb2c602091d

in practice, statusline flicker when i use keymap for navigation
```lua
  {
    "numToStr/Navigator.nvim",
    keys = {
      { "<a-h>", "<cmd>NavigatorLeft<cr>" },
      { "<a-k>", "<cmd>NavigatorUp<cr>" },
      { "<a-l>", "<cmd>NavigatorRight<cr>" },
      { "<a-j>", "<cmd>NavigatorDown<cr>" },
    },
    config = function()
      require("Navigator").setup()
    end,
  },
```

and lualine won't

minimal init.lua
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end ---@diagnostic disable-next-line: undefined-field
vim.opt.rtp:prepend(lazypath)

vim.keymap.set("n", "<a-l>", "<cmd><cr>", {silent=true})
vim.keymap.set("n", "<a-h>", "h", {silent=true})
vim.opt.cmdheight=0

require("lazy").setup({
--{
--	  "nvim-lualine/lualine.nvim",
--	    dependencies = { 'nvim-tree/nvim-web-devicons' },
--	    config = function()
--		    require('lualine').setup()
--	    end
--
--},
{
  "echasnovski/mini.nvim",
  config = function()
    require("mini.statusline").setup({set_vim_settings=true})
  end,
},
})
```

### Neovim version

0.9.5

### Expected behavior

no disappear

**Comment by tkkcc** [comment]
sorry, I found it appears in lualine too. but not in LazyVim. I will try to figure it out.

**Comment by tkkcc** [comment]
Ok, it's noice.nvim that make the statusline stable.

**Comment by echasnovski** [comment]
Yes, this is not an issue in any of statusline plugins but `cmdheight=0` itself, because this is reproducible even without one with this 'init.lua':

```lua
vim.keymap.set("n", "<a-l>", "<cmd><cr>", {silent=true})
vim.opt.cmdheight=0
```

'Noice.nvim' doesn't have this because it overrides how `cmdheight=0` acts under the hood.
