### ISSUE TITLE
mini.statusline: Statusline is not updated when NeoTree is toggled.

### ISSUE THREAD

**Issue by UtkarshVerma** [echasnovski/mini.nvim#736]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

When NeoTree is toggled, the statusline is not refreshed and inactive content is shown for the focused buffer.

### Neovim version

0.9.5

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Show and hide NeoTree by pressing `gfe` twice.

```lua
-- minimal.lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./root", ":p")

-- set stdpaths to use root
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
	{
		"echasnovski/mini.statusline",
                lazy = false,
		opts = {
			-- Do not override vim settings.
			set_vim_settings = false,
		},
	},
	{
		"nvim-neo-tree/neo-tree.nvim",
		dependencies = {
			"nvim-lua/plenary.nvim",
      			"nvim-tree/nvim-web-devicons",
      			"MunifTanjim/nui.nvim",
      	},
		keys = {
			{
				"gfe",
				function()
					require("neo-tree.command").execute({ toggle = true })
				end,
				desc = "Explorer",
			},
		},
		opts = {},
	},
}, {
	root = root .. "/plugins",
	defaults = {
		lazy = true,
	},
	install = {
		colorscheme = { "habamax" },
	},
})

vim.cmd.colorscheme("habamax")
```

Here's a recording.

https://github.com/echasnovski/mini.nvim/assets/31820255/25308c77-cc24-443f-a381-46c0dc1a68d9

### Expected behavior

Active content is shown for the focused buffer.

### Actual behavior

Inactive content is shown for the focused buffer.

**Comment by echasnovski** [comment]
Thanks for the issue!

This seems to be have the same culprit as #653, i.e. it is an upstream nvim-neo-tree/neo-tree.nvim#1211 issue with 'neo-tree.nvim' blocking events which 'mini.statusline' uses to detect when active/inactive content should be set. And using that type of events (`WinEnter` in particular) is indeed the best approach to do that.

Closing as not an issue with 'mini.statusline'.
