### ISSUE TITLE
mini.animate causes incorrect tab count

### ISSUE THREAD

**Issue by jgouly** [echasnovski/mini.nvim#737]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.animate

### Description

The tab count for a newly created tab is 2, not 1

### Neovim version

3e569d440b8e5a2b190a7013081d29cb7e04af01

### Steps to reproduce

1. `minimal.lua`:

      `require('mini.animate').setup({})`
2. `nvim -u minimal.lua`
3.  `:tab new`

### Expected behavior

New tab shows up with a count of 1.

### Actual behavior

New tab shows up with a count of 2.

**Comment by echasnovski** [comment]
This is not really an issue with 'mini.animate', but more with how default tabline works. It seems to count *all* windows including floating ones. As 'mini.animate' uses floating windows for "open" and "close" animation, default tabline counts them when tabpage has just opened or closed. It goes back to counting all visible windows after respective "open"/"close" animation is finished (and there is some redraw needed; like for example after starting editing buffer).

If you don't like this behavior, I'd suggest either using different implementation of tabline or disabling "open" and/or "close" animation (set corresponding `enable` value(s) to `false`).

Closing as not an issue with 'mini.animate'.
