### ISSUE TITLE
verbose autoread error message if no session file is found

### ISSUE THREAD

**Issue by kekscode** [echasnovski/mini.nvim#738]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions

### Description

I use this configuration:

```lua
      local sessions = require('mini.sessions') -- Session management (read, write, delete)
      sessions.setup({
        -- Whether to read latest session if Neovim opened without file arguments
        autoread = true,

        -- Whether to write current session before quitting Neovim
        autowrite = true,

        -- File for local session (use `''` to disable)
        file = 'Session.vim',

        -- Directory where global sessions are stored (use `''` to disable)
        directory = '',

        -- Whether to print session path after action
        verbose = { read = true, write = true, delete = true },
      })
```

and usually i create a session file everywhere i need one *or* i start neovim with `nvim .` or `nvim path/to/file.ext` so no autoloading a session happens and no error message appears.

When i start `nvim` and have no directory-local `Session.vim`, i receive a rather obtrusive error:

```
12:40:12 msg_show Error executing lua callback: ...i/.local/share/nvim/lazy/mini.nvim/lua/mini/sessions.lua:587: (mini.sessions) There is no detected sessions. Change configuration and rerun `MiniSessions.setup()`.
stack traceback:
	[C]: in function 'error'
	...i/.local/share/nvim/lazy/mini.nvim/lua/mini/sessions.lua:587: in function 'error'
	...i/.local/share/nvim/lazy/mini.nvim/lua/mini/sessions.lua:152: in function 'read'
	...i/.local/share/nvim/lazy/mini.nvim/lua/mini/sessions.lua:444: in function <...i/.local/share/nvim/lazy/mini.nvim/lua/mini/sessions.lua:443>
```

Is there a straightforward way to either surpress this message completely (maybe not a good idea), make it "nicer" (e.g. removing the tracebacks) in `mini.sessions` configuration? Or is there a configuration which could help suppress this or make it less "noisy"?

I understand this is maybe a (very) minor issue.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Having looked at it, I do agree that this might be a bit much. And as 'mini.sessions' is designed to support the workflow you describe, it is reasonable to loosen the side effect from error to a message. This should be done on latest `main` branch.
