### ISSUE TITLE
How to apply border for the completion list?

### ISSUE THREAD

**Issue by ken-futureverse** [echasnovski/mini.nvim#741]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Using the following config, but it doesn't set the border for the first completion list

<img width="787" alt="Screenshot 2024-03-09 at 20 37 02" src="https://github.com/echasnovski/mini.nvim/assets/97480229/7fe3e087-90b2-44e0-88e0-4549baac94f6">

```
      require('mini.completion').setup {
        window = {
          info = { border = 'rounded' },
          signature = { border = 'rounded' },
        },
      }
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Unfortunately, there is now way of implementing this. The completion list comes from built-in completion mechanism ("insert completion popup menu", see `:h ins-completion-menu`) which does not have the way to set borders.

Closing as (currently) impossible to resolve. If Neovim adds support for that, this should be revisited.
