### ISSUE TITLE
FR: keep cursor column when multiplying linewise

### ISSUE THREAD

**Issue by chrisgrieser** [echasnovski/mini.nvim#742]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.operators / multiply operator

### Description

First, thanks again for this plugin. As I mentioned on reddit, a multiplication operator is quite transformative for the vim experience, and I wouldn't want to use nvim without it.

---

So I noticed with linewise multiplication operations, the cursor always moved to the first non-whitespace character of the line.

```lua
-- current behavior
--                    v    cursor position before multiplication via `gmm`
   local foobar = "baz"
   local foobar = "baz"
-- ^                       cursor position after

-- expected/desired behavior
   local foobar = "baz"
--                    ^    cursor position after
```

However, it is often quite desirable to keep the cursor in the same column as before the multiplication. A real use case where that matters are for instance lua annotations: When I want to add a field by duplicating the line with `@field`, it always moves me to the beginning of the line, instead of staying on `field_name`.

```lua
---@class (exact) class_name
---@field field_name string
```

Could this behavior of the multiply operator be changed? (either by default or as an option, not sure which makes more sense)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Although I understand the premise, this is kind of tricky one to decide what is best. The current behavior is the same as if doing `p` after linewise yank. As this is the default behavior and is what I'd expect from multiply operation, that was kept as is.

What I say for sure is that this won't be a behavior behind an option. I'll take some time to think if keeping cursor on the same relative position (column and, if it is even possible, line) is worth it.

**Comment by echasnovski** [comment]
After thinking this through, I think the current behavior of "put cursor at start of pasted text" is more consistent with the built-in operators (and thus more preferable).

Closing as not planned.
