### ISSUE TITLE
Plugins to do project wide search and replace and show diagnostics.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#744]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.replace, mini.diagnostic

### Description

Hi again! I wanted to know if there are any plans on implementing project wide search and replace plugin in the mini lib. Also a diagnostics plugin like trouble.nvim combined with todo-comments.nvim.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Not at the moment, no.

> I wanted to know if there are any plans on implementing project wide search and replace plugin in the mini lib.

The project wide search and replace I'd expect to be done slightly more traditional way:
- Populate quickfix list with matches. For example, with `builtin.grep()`/`builtin.grep_live()` from 'mini.pick' after marking all matches (`<C-a>` by default) and converting them to quickfix list (`<M-CR>` by default).
- Perform operations on quickfix list. Like with `:cdo`.

That said, I have vague plans to make working with quickfix/location lists easier. Not sure yet how though.

> Also a diagnostics plugin like trouble.nvim combined with todo-comments.nvim.

The project wide diagnostics is better suited for Neovim core, in my opinion. The downside here is that I am not aware of the initiative to implement it yet, unfortunately.

The only thing from 'todo-comments.nvim' which I would like to support is highlighting which is already [implemented in 'mini.hipatterns'](https://github.com/echasnovski/mini.nvim/blob/c3b37f4afb933141a750b60b86fb6ef6b50d0e61/doc/mini-hipatterns.txt#L110-L124). Other than that, this looks similar to project wide find and replace functionality.

------

Closing as not planned / planned in slightly different form.

**Comment by Susensio** [comment]
So doing <C-a><M-CR> pushes the content to the quickfix list.
How can those keymaps be combined into one? (<C-q> for example).
I've been trying to define such keymap but I think the MiniPick actions are not public.

**Comment by echasnovski** [comment]
> edit: that was easy:
> 
> ```lua
>       mappings = {
> 
>         to_quickfix = {
>           char = "<C-q>",
>           func = function()
>             local items = MiniPick.get_picker_items() or {}
>             MiniPick.default_choose_marked(items)
>             MiniPick.stop()
>           end,
>         },
>       },
> ```

I was going to mention that using `return true` instead of `MiniPick.stop()` should be a bit better, but realized that this was never documented (although tested). [It is now](https://github.com/echasnovski/mini.nvim/blob/a683bfe8e03293e3bb079e24c94e51977756a3ec/doc/mini-pick.txt#L592-L594). So thanks for the question and solution!
