### ISSUE TITLE
Option to set line number for mini.files

### ISSUE THREAD

**Issue by ntyunyayev** [echasnovski/mini.nvim#747]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

Hi,

Thank you for your work. I just started using mini.files, and I am loving it. I was wondering if adding an option to automatically display line numbers for mini.files buffers was possible. I believe that it would make navigation easier. 

Best regards,

Nikita

**Comment by echasnovski** [comment]
Hi, Nikita!

Thanks for using 'mini.files'!

> I was wondering if adding an option to automatically display line numbers for mini.files buffers was possible. I believe that it would make navigation easier.

It is already possible. Customizing windows is expected to be done inside [dedicated events](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-files.txt#L323-L327). Here is an [example from help page](https://github.com/echasnovski/mini.nvim/blob/e025ee74705b04dd25a132a521c9c535dc78a8d8/doc/mini-files.txt#L368-L381). Note that 'number' window option is a bit special (it is disabled on every window update due to `'minimal'` style of floating windows), so it should be set in every `MiniFilesWindowUpdate` event and not `MiniFilesWindowOpen`.

Here is an example of full working config:

```lua
require('mini.files').setup()
vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesWindowUpdate',
  callback = function(args) vim.wo[args.data.win_id].number = true end,
})
```

**Comment by echasnovski** [comment]
> Adding
> ...
> Solves some of the issues when going to the parent directory, but in both cases, when the screen is too small to fit all the buffers, the line numbers are not always shown when navigating with h/l.

That autocommand **should** be added in order to display line numbers.

However, I can indeed reproduce the issue with it not always being set. Apparently, there are cases when `MiniFilesWindowUpdate` is not triggered but should. I'll look into it.

**Comment by ntyunyayev** [comment]
Thank you :)

**Comment by echasnovski** [comment]
This should be now resolved on latest `main` branch.

The reason for this was quite technical: `MiniFilesWindowUpdate` event was triggered *before* window got its target buffer assigned to it. Which was not good, so thanks for inadvertently finding this!

As 'number' is a window-local option (which are notoriously convoluted as to how they work), it got overridden after buffer was assigned to the window. But now (when event gets triggered *after* window gets its buffer) setup from [this comment](https://github.com/echasnovski/mini.nvim/issues/747#issuecomment-1995360187) seems to work for me completely.

**Comment by ntyunyayev** [comment]
Thank you again for taking the time to fix it. You are very quick :d. Indeed, it works perfectly with your suggestion :)

**Comment by onexbash** [comment]
If you want to have relative instead of absolute line numbers you can edit the autocmd a bit:

```lua
vim.api.nvim_create_autocmd('User', {
  pattern = 'MiniFilesWindowUpdate',
  callback = function(args)
    local win = vim.wo[args.data.win_id]
    win.number = true
    win.relativenumber = true
  end,
})
```
