### ISSUE TITLE
Mini.Sessions fails to load session file at start if swap file warning printed  

### ISSUE THREAD

**Issue by edshamis** [echasnovski/mini.nvim#75]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.sessions

### Description

More precisely, session script load is interrupted after the E325 (swap file warning) is printed. 
vim.g.SessionLoad remains 1

### Neovim version

v0.8.0-dev+133

### Steps to reproduce

require('mini.sessions').setup({
  autoread = true,
  autowrite = true,
  directory = '~/.config/nvim/sessions/',
  file = 'session.vim',
  force = { read = false, write = true, delete = false },
  verbose = { read = true, write = true, delete = true },
})

### Actual behavior

Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua ...local/share/nvim/plugged/mini.nvim/lua/mini/sessions.lua:194: Vim(edit):E325: ATTENTION
stack traceback:
        [C]: in function 'cmd'
        ...local/share/nvim/plugged/mini.nvim/lua/mini/sessions.lua:194: in function 'read'
        ...local/share/nvim/plugged/mini.nvim/lua/mini/sessions.lua:399: in function 'on_vimenter'
        [string ":lua"]:1: in main chunk

**Comment by echasnovski** [comment]
Thanks for the issue.

Does this error happen if you manually source session? Like with `nvim -S <path-to-session>`?

**Comment by edshamis** [comment]
This way E325 is printed but session loads without an error and vim.g.SessionLoad is nit

**Comment by edshamis** [comment]
I see, thanks for the explanation. As I understand in such case of an error at startup the session script is interrupted but mimi.sessions still thinks it has read the session file and keeps managing it. Maybe it can at least disable itself (with a notification) if it can be aware of an error?

**Comment by echasnovski** [comment]
> As I understand in such case of an error at startup the session script is interrupted but mimi.sessions still thinks it has read the session file and keeps managing it.

Correct.

I am currently thinking about how to best approach this problem. The best way is to use some native `nvim_source` from issue I've created earlier (or other comparable approach I've missed). Otherwise, not sure what "disable itself" would mean here, but some kind of reaction to error would be appropriate.

Something should be done with error handling here, that is for sure. Yet not sure what exactly :)

**Comment by echasnovski** [comment]
I stand hugely corrected. Although upstream Neovim does have inconsistency for error handling, there was a simple one-word solution to the problem: use `silent! source` instead of `source` to read session.

As far as I can tell, this should be solved on latest `main`.
