### ISSUE TITLE
(mini.map): Code highlight feature

### ISSUE THREAD

**Issue by Woynert** [echasnovski/mini.nvim#750]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.map

### Description

First of all, thanks for all the work you've done!

So recently, I've discovered neovim can have a code minimap and got very exited to try it. Then I realized it didn't have code highlighting, a feature which *to me* is essential for ease of navigation.

I had the time in my hands so I went and coded it. And it was quite the journey.

Video here:

https://github.com/echasnovski/mini.nvim/assets/61242172/007bd5b1-dcc3-42ab-95ba-35e1965fc66b

### Project vision and goals

From [CONTRIBUTING](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md):

> Code related. For example, fix a bug or implement a feature. Before even starting one, please make sure that it is aligned with project vision and goals. The best way to do so is to receive a positive feedback from maintainer on your initiative in one of the GitHub issues (existing or created by you)

I've opened this issue to get your approval on the feature before I open a pull request or write documentation for it. 

You can try it at https://github.com/Woynert/mini.map main.

### Some extra info

- The feature is functional but the code is not ready to review. There is no option to disable it, nor documentation. (proper PR on it's way)
- To extract the colors for each display character it uses the same method (and same loop) as the `mask_rescale` function. So we kinda "kill two birds with one stone" and there's little overhead.
- Finally apply the compiled colors to each char if there is a color for it in the first place. There is an optimization that can be done here on neighbor chars that have the same color to reduce the calls to `vim.api.nvim_buf_set_extmark`.
- I looks way better with the "dots" braille symbols.
- In very large files (see video) due to technical limitations the precision suffers, however there's room for a more precise algorithm at the cost of performance.
- AFAIK there's no other plugin with this feature.

**Comment by echasnovski** [comment]
Thanks for the suggestion and initial implementation! And for reading 'CONTRIBUTING.md'.

Adding code highlighting was considered at one point, but eventually was deemed to be not enough value for how much performance decrease it brings. Here are some quick benchmarks based on your version of the feature:

- Baseline time (current implementation): around 0.5 ms *per update*.
- With map highlighting and enabled built-in syntax: around 50 ms *per update*.
- With map highlighting and disabled built-in syntax (enabled from tree-sitter): around 8 ms *per update*.

So this is indeed **too much** of increase in computations. The fact that it is blocking (introduces lag) makes it even worse.

------

Another major issue with this is that using `vim.fn.synID()` will only work for built-in syntax. That is, it won't display map highlights when tree-sitter highlighting is enabled. And it doesn't even take into account LSP semantic tokens.

There is a `vim.inspect_pos()` function to get *some* information about any present highlighting in a buffer, but it returns only highlight groups, not the eventual visible highlighting.

------

> AFAIK there's no other plugin with this feature.

There is [gorbit99/codewindow.nvim](https://github.com/gorbit99/codewindow.nvim). But it works with tree-sitter and built-in LSP, which are also not quite performant.

------

For completeness, benchmarking was done in a ~1200 lines buffer in which both built-in syntax and tree-sitter can be enabled. Implementation is basically:
- Add `_G.log = {}` somewhere in the 'lua/mini/map.lua'.
- Add `local start_time = vim.loop.hrtime()` line [at the start of `H.mask_rescale()`](https://github.com/Woynert/mini.map/blob/d475eaa6f59e95fafa1033bff1d40d9598a2189f/lua/mini/map.lua#L1131).
- Add `table.insert(_G.log, 0.000001 * (vim.loop.hrtime() - start_time))` [at the end of `H.mask_rescale()`](https://github.com/Woynert/mini.map/blob/d475eaa6f59e95fafa1033bff1d40d9598a2189f/lua/mini/map.lua#L1189).
- Restart Neovim and use map for some time.
- See update times (in ms) with `:=log`.

------

Although I really appreciate the enthusiasm, in this particular case performance is more important than visuals, as map window gets updated quite frequently. Your initial implementation helped understanding the scale of the performance decrease, so huge thanks for that!

Closing as not planned.

**Comment by Woynert** [comment]
@echasnovski That makes sense, thanks for your time and the very detailed response!

To be fair I've never written a plugin before so it checks out, it was a fun exercise though. 

This let's me wondering if it's even possible to make it performant enough with the current nvim API.

**Comment by echasnovski** [comment]
> This let's me wondering if it's even possible to make it performant enough with the current nvim API.

It is not a well defined problem, unfortunately.

I *think* that currently there is no way to dramatically decrease overall time spent computing and applying map highlighting.

What is possible is to make it less disruptive for the user: spread that computation in time while inserting "check if there is anything to be done" in between. This is generally achievable with coroutines and `vim.schedule()`, which dramatically increases code complexity. This is what was done in 'mini.pick' to achieve as much responsiveness as possible ([here](https://github.com/echasnovski/mini.nvim/blob/9968f6e221ae7bdac57a910c5bf2026186aa023c/lua/mini/pick.lua#L1749C10-L1754), [here](https://github.com/echasnovski/mini.nvim/blob/9968f6e221ae7bdac57a910c5bf2026186aa023c/lua/mini/pick.lua#L3218-L3233), and in various [invocations of `H.poke_picker_throttle()`](https://github.com/echasnovski/mini.nvim/blob/9968f6e221ae7bdac57a910c5bf2026186aa023c/lua/mini/pick.lua#L2785)).
