### ISSUE TITLE
Add mini.tag to autocomplete tag similar to nvim-ts-autotag

### ISSUE THREAD

**Issue by sdhrt** [echasnovski/mini.nvim#752]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tag

### Description

nvim-ts-autotag is a great tool for web development. The functioning itself is similar to mini.pairs and I think it would be a great addition to the mini repository.

When i press ```>```after ```<html```
Hopefully it results in ```<html></html>```

Although I know lsp will provide autocomplete after typing ```</```
It is a hassle in languages like react where we need to quickly close tag and insert a new line between the tags.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Coincidentally, there was similar request quite recently: #726. The reasoning from its resolution still stands.

Closing as duplicate of #726.

**Comment by drowning-cat** [comment]
Just throwing out some code as an idea, didn’t test it though.

```lua
local MiniKeymap = require("mini.keymap")
MiniKeymap.map_combo("i", ">", function()
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  local line = vim.api.nvim_get_current_line()
  if line:sub(col + 1, col + 1) == "<" then
    return
  end
  local tag = line:sub(1, col):match("<([%w:%-]+)[^<>]*>$")
  if not tag then
    return
  end
  local close = ("</%s>"):format(tag)
  row = row - 1
  vim.api.nvim_buf_set_text(0, row, col, row, col, { close })
end)
```

**Comment by echasnovski** [comment]
> Just throwing out some code as an idea, didn’t test it though.

Oh, that's nice! Thanks for sharing!

**Comment by echasnovski** [comment]
@drowning-cat, I was just about to add this as an example for 'mini.keymap', but noticed something. It only uses `map_combo` for a single character, which is a bit of an overkill.

This seems to be possible with a regular expression mapping something like this (of course, can be set locally only in HTML-like buffers):

```lua
local set_cursor_later = vim.schedule_wrap(function(pos) vim.api.nvim_win_set_cursor(0, pos) end)

local auto_tag = function()
  local row, col = unpack(vim.api.nvim_win_get_cursor(0))
  local line = vim.api.nvim_get_current_line()

  local tag = line:sub(1, col):match('<([%w:%-]+)[^<>]*$')
  if tag == nil then return '>' end

  set_cursor_later({ row, col + 1 })
  return '></' .. tag .. '>'
end

vim.keymap.set('i', '>', auto_tag, { expr = true })
```

**Comment by drowning-cat** [comment]
I felt so smart before I read your message, but now I feel dumb again. Indeed, there is no actual reason to use `mini.keymap` here. Sorry for misleading you 😔

**Comment by 231tr0n** [comment]
```lua
			if
				vim.bo.filetype == "svelte"
				or vim.bo.filetype == "vue"
				or vim.bo.filetype == "jsx"
				or vim.bo.filetype == "tsx"
				or vim.bo.filetype == "html"
				or vim.bo.filetype == "xml"
				or vim.bo.filetype == "xsl"
				or vim.bo.filetype == "javascriptreact"
				or vim.bo.filetype == "typescriptreact"
			then
				-- HTML tag completion with >, >> and >>>
				vim.bo.omnifunc = "htmlcomplete#CompleteTags"
				Imap("><Space>", ">", "Cancel html pairs", { buffer = true })
				Imap("><CR>", "><Esc>yyppk^Dj^Da</<C-x><C-o><C-x><C-o><C-p><C-p><Esc>ka<Tab>", "Newline html pairs", {
					buffer = true,
				})
				Imap(">", "><Esc>F<f>a</<C-x><C-o><C-x><C-o><C-p><C-p><Esc>vit<Esc>i", "Sameline html pairs", {
					buffer = true,
				})
				Imap(">>", "><Esc>F<f>a</<C-x><C-o><C-x><C-o><C-p><C-p><Space><BS>", "Sameline cursor end html pairs", {
					buffer = true,
				})
			end

```
I use these in a FileType auto command, and this gets the job done very nicely.

**Comment by echasnovski** [comment]
> I felt so smart before I read your message, but now I feel dumb again. Indeed, there is no actual reason to use `mini.keymap` here. Sorry for misleading you 😔

@drowning-cat, there is nothing to feel dumb about :) The code worked and that what matters.

> I use these in a FileType auto command, and this gets the job done very nicely.

@231tr0n, please create a dedicated autocommand with `pattern` set to the array of necessary filetypes. Something like:

```lua
local autotag_ft = { 'svelte', 'vue', 'jsx', 'tsx', 'html', 'xml', 'xsl', 'javascriptreact', 'typescriptreact' }
local map_autotag = function()
  -- Code goes here
end

local au_opts = { pattern = autotag_ft, callback = map_autotag, desc = 'Map autotag' }
vim.api.nvim_create_autocmd('FileType', au_opts)
```

**Comment by 231tr0n** [comment]
> > I felt so smart before I read your message, but now I feel dumb again. Indeed, there is no actual reason to use `mini.keymap` here. Sorry for misleading you 😔
> 
> [@drowning-cat](https://github.com/drowning-cat), there is nothing to feel dumb about :) The code worked and that what matters.
> 
> > I use these in a FileType auto command, and this gets the job done very nicely.
> 
> [@231tr0n](https://github.com/231tr0n), please create a dedicated autocommand with `pattern` set to the array of necessary filetypes. Something like:
> 
> local autotag_ft = { 'svelte', 'vue', 'jsx', 'tsx', 'html', 'xml', 'xsl', 'javascriptreact', 'typescriptreact' }
> local map_autotag = function()
>   -- Code goes here
> end
> 
> local au_opts = { pattern = autotag_ft, callback = map_autotag, desc = 'Map autotag' }
> vim.api.nvim_create_autocmd('FileType', au_opts)

Well I have one big filetype autocommand which does everything from starting treesitter, setting folds, indentexpr. I taught of just sneaking this in to the same filetype autocommand so wrote in this way. But you are right. I will refactor this code in my actual config.

**Comment by echasnovski** [comment]
> I taught of just sneaking this in to the same filetype autocommand so wrote in this way.

Then at least going the following route is less painful and more performant:

```lua
local autotag_map = {
  svelte = true,
  vue = true,
  jsx = true,
  tsx = true,
  html = true,
  xml = true,
  xsl = true,
  javascriptreact = true,
  typescriptreact = true,
}

local a_big_callback = function(ev)
  -- A very big callback

  local ft = vim.bo[ev.buf].filetype
  if autotag_map[ft] then
    -- Map autotag
  end

  -- A very big callback continues
end

vim.api.nvim_create_autocmd('FileType', { callback = a_big_callback })
```
