### ISSUE TITLE
mini.clue: <c-r> and <c-x> mappings not disabled when recording macros

### ISSUE THREAD

**Issue by JulesNP** [echasnovski/mini.nvim#756]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

When recording a macro, the `<c-r>` and `<c-x>` triggers for mini.clue don't seem to be getting disabled, which is causing issues for me during macro playback.

Pasting the contents of the macro afterwards confirms that additional character codes are being inserted, so a `^R*` is actually being recorded as: `<80><fc>^DR*^R*`

Checking `:verbose imap <c-r>` while running a macro also confirms that the key is still mapped.

### Neovim version

0.9.5

### Steps to reproduce

```lua
local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    }
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
    "echasnovski/mini.nvim",
    version = false,
    config = function()
        local miniclue = require "mini.clue"
        miniclue.setup {
            triggers = {
                -- Leader triggers
                { mode = "n", keys = "<Leader>" },
                { mode = "x", keys = "<Leader>" },

                -- Built-in completion
                { mode = "i", keys = "<C-x>" },

                -- `g` key
                { mode = "n", keys = "g" },
                { mode = "x", keys = "g" },

                -- Marks
                { mode = "n", keys = "'" },
                { mode = "n", keys = "`" },
                { mode = "x", keys = "'" },
                { mode = "x", keys = "`" },

                -- Registers
                { mode = "n", keys = '"' },
                { mode = "x", keys = '"' },
                { mode = "i", keys = "<C-r>" },
                { mode = "c", keys = "<C-r>" },

                -- Window commands
                { mode = "n", keys = "<C-w>" },

                -- `z` key
                { mode = "n", keys = "z" },
                { mode = "x", keys = "z" },
            },

            clues = {
                -- Enhance this by adding descriptions for <Leader> mapping groups
                miniclue.gen_clues.builtin_completion(),
                miniclue.gen_clues.g(),
                miniclue.gen_clues.marks(),
                miniclue.gen_clues.registers(),
                miniclue.gen_clues.windows(),
                miniclue.gen_clues.z(),
            },
        }
    end,
}
```

### Expected behavior

The mappings for `<c-r>` and `<c-x>` are cleared by mini.clue when beginning to record a macro, as is done with the other mini.clue mappings.

### Actual behavior

The keys are not being unmapped as expected.

**Comment by echasnovski** [comment]
Thanks for the issue!

I *think* I can reproduce this. Not sure if there is something to be done here (as 'mini.clue' generally is quite hacky), but I'll look into it.

**Comment by echasnovski** [comment]
This is now should be resolved on latest `main`.

The issue was quite straightforward and indeed affected only "special" keys as you described (like `<C-R>`, etc.). They were not disabled properly inside `disable_all_triggers()` (which is used on the start of macro recording).
