### ISSUE TITLE
Allow using different mappings for normal and visual modes

### ISSUE THREAD

**Issue by rasulomaroff** [echasnovski/mini.nvim#757]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

Hi there! I've been using this plugin for a long time, but recently I wanted to change the `add` mapping for visual mode and realized that it's not possible. It will be the same for normal and visual modes.

For example, I have really long mapping for surroundings, like `gsa`, `gsd` etc, but when I'm in visual mode, I wanna change it to just `s`, because `s` does the same thing as `c` by default in visual mode. So, binding it to `surround` will make it more valuable.

I implemented this feature on my machine and seems to work fine, just small tweaks and that's it. I could open a PR if you don't mind and think that having such a thing is worth it :)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already discussed in #66. It resulted into documenting setup similar to 'tpope/vim-surround' which itself has the [way to customize `add` mapping in Visual mode](https://github.com/echasnovski/mini.nvim/blob/a822f42fd52952f03c7d98d50e8e56921444d699/doc/mini-surround.txt#L517-L519) (replace `'ys'` with `gsa` in your case).

So although there is precedent in 'mini.comment' to allow separate mappings for Normal and Visual mode, I think I don't really like this pattern as it adds extra complexity to the config structure without significant benefit (and in presence of a reasonable alternative solution).

Closing as not planned.

**Comment by rasulomaroff** [comment]
damn, didn't even encounter that issue when searching for "different mappings"
Anyway, I see your point, that workaround also works, but there's an additional step of deleting the mapping from visual mode that's applied from the config. Since I haven't used vim-surround, but started from mini.surround from the very beginning, I didn't even know there's such a thing in other plugins.

Thank you!
