### ISSUE TITLE
A way to get mini-starter to open in new empty tabs

### ISSUE THREAD

**Issue by gilmoregrills** [echasnovski/mini.nvim#758]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-starter

### Description

I would like to be able to have mini-starter be the start page when I create a new empty tab! If there's a way to get this to work custom that works too, but I think it could be useful.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This kind of customization is usually better to be left to the user who can implement this behavior using autocommands and dedicated events.

Here is one way of opening Starter buffer when entering new tabpage:
```lua
require('mini.starter').setup()
vim.api.nvim_create_autocmd('TabNewEntered', { callback = function() MiniStarter.open() end })
```

Closing as not planned.
