### ISSUE TITLE
mini.deps: Additional commits are not included in monitor updates.

### ISSUE THREAD

**Issue by abeldekat** [echasnovski/mini.nvim#761]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.deps

### Description

The readme of plugin [abeldekat/harpoonline](https://github.com/abeldekat/harpoonline?tab=readme-ov-file#using-minideps-and-ministatusline) contains instructions for `mini.deps` and `mini.statusline`.

The plugin supports semantic versioning, so I experimented with the `checkout` option of `mini.deps`.

I expected the output of `DepsUpdate` to contain lines of commits added after the latest stable version. I am not sure though if this expectation is justified.

### Neovim version

0.9.5

### Steps to reproduce

setup:

```sh
mkdir ~/.config/repro
cd ~/.config/repro

NVIM_APPNAME=repro nvim init.lua

# Remove:
rm -rf ~/.local/share/repro ~/.local/state/repro ~/.local/cache/repro
rm -rf ~/.config/repro
```

init.lua:

```lua

local function clone(path_to_site)
  local mini_path = path_to_site .. "pack/deps/start/mini.nvim"
  if not vim.loop.fs_stat(mini_path) then
    vim.cmd('echo "Installing `mini.nvim`" | redraw')
    local clone_cmd =
      { "git", "clone", "--filter=blob:none", "https://github.com/echasnovski/mini.nvim", mini_path }
    vim.fn.system(clone_cmd)
    vim.cmd("packadd mini.nvim | helptags ALL")
    vim.cmd('echo "Installed `mini.nvim`" | redraw')
  end
end

local path_to_site = vim.fn.stdpath("data") .. "/site/"
clone(path_to_site)
local MiniDeps = require("mini.deps")
MiniDeps.setup({ path = { package = path_to_site } })
local add, now = MiniDeps.add, MiniDeps.now

vim.g.mapleader = " "
now(function()
  vim.cmd.colorscheme("minischeme")

  add({ source = "ThePrimeagen/harpoon", checkout = "harpoon2", depends = { "nvim-lua/plenary.nvim" } })
  local Harpoon = require("harpoon")
  Harpoon:setup({ settings = { save_on_toggle = true } })

  vim.keymap.set("n", "<leader>a", function()
    Harpoon:list():append()
  end, { desc = "Harpoon append", silent = true })
  vim.keymap.set("n", "<leader>u", function()
    Harpoon.ui:toggle_quick_menu(Harpoon:list())
  end, { desc = "Harpoon ui", silent = true })

  add({ source = "abeldekat/harpoonline", checkout = "stable" })
  local Harpoonline = require("harpoonline")
  Harpoonline.setup({
    on_update = function()
      vim.wo.statusline = "%!v:lua.MiniStatusline.active()"
    end,
  })

  local MiniStatusline = require("mini.statusline")
  MiniStatusline.setup({
    set_vim_settings = false,
    content = {
      active = function()
        return MiniStatusline.combine_groups({
          { hl = "MiniStatuslineDevinfo", strings = { Harpoonline.format() } },
        })
      end,
    },
  })
end)

```
</details>

### Expected behavior

`MiniDepsUpdate`: The commits after the stable release are included in the report, below the line "Monitor updates from main".

### Actual behavior

![1711105025](https://github.com/echasnovski/mini.nvim/assets/58370433/6102d8c1-65a3-484b-aa04-0205c7a08465)

![1711105114](https://github.com/echasnovski/mini.nvim/assets/58370433/cb79fc62-2748-4950-8887-f0a13c112a8a)

`MiniDepsUpdate`: The commits after stable release `v1.2.1` are absent.

**Comment by echasnovski** [comment]
The `monitor` field is used to show *new* updates which were retrieved during the current update (`git fetch`, to be precise). This is done on purpose so as to not accumulate changes during long "freezes". Otherwise it might show wall of text if `checkout` target is frozen for a long time.

So in this case, if there is a new commit in `ThePrimagen/harpoon`, it will be shown in confirmation of the first `:DepsUpdate` run after it was pushed. During second and other runs it will not be considered as *new* change.

**Comment by abeldekat** [comment]
@echasnovski,

> if there is a new commit in ThePrimagen/harpoon

Minor clarification: The situation I described is about `abeldekat/harpoonline`

I understand that any remote updates that already have been fetched will not be displayed.


However:

```lua
  add({ source = "abeldekat/harpoonline", checkout = "v1.2.1" })
  require("ak.config.ui.mini_statusline")
```

`DepsUpdate:`

```txt
--- harpoonline ---
Path:   /home/user/.local/share/nvim/site/pack/deps/opt/harpoonline
Source: https://github.com/abeldekat/harpoonline
State:  bd060e8fb3f54b2b75b82eadcb4a6241ea3fc0e2 (v1.2.1)

Monitor updates from `main`:
<Nothing>
```

In preparation for release v1.3.0, there are now 4 commits that have not been retrieved yet.

`~/.local/share/nvim/site/pack/deps/opt/harpoonline`:

```txt
harpoonline on  main [⇣] via 🌙 v5.4.6
❯ git log --oneline | head -1
bd060e8 chore(main): release 1.2.1 (#12)
```
As a consequence, the following line is surprising:

```txt
Monitor updates from `main`: --> suggests that there are no new commits in main...
<Nothing>
```

In this situation, is there an alternative configuration that will show the new commits in main?

**Comment by echasnovski** [comment]
> `~/.local/share/nvim/site/pack/deps/opt/harpoonline`:
> 
> ```
> harpoonline on  main [⇣] via 🌙 v5.4.6
> ❯ git log --oneline | head -1
> bd060e8 chore(main): release 1.2.1 (#12)
> ```

First of all, this looks like a repository that is not completely managed by 'mini.deps', as it does does not check out to branch (and it seems that repo *is* checked out to `main`). So any inconsistency is now assumed to be on the user.

------

The 'mini.deps' uses remote branches directly without local checkout to get necessary info. Monitor log is basically computed like this:
- Get commit of `origin/main` (assuming `main` is a monitor branch).
- Fetch `origin/main`.
- Again get commit of `origin/main`.
- Show the log between current those two commits.

It looks like `origin/main` did not change what commit it points to.

**Comment by abeldekat** [comment]
I created a dummyplugin project on github
Pushed a first commit, and added a tag v1.0.0 in the terminal.
With a minimal repro, the plugin is retrieved.

```lua
add({ source = "abeldekat/dummyplugin", checkout = "v1.0.0", monitor = "main" })
```

In the project I added a second commit, and DepsUpdate works as intended.
I added a third commit, and repeated the steps, with succes:

```lua
--- dummyplugin ---
Path:   /home/user/.local/share/repro/site/pack/deps/opt/dummyplugin
Source: https://github.com/abeldekat/dummyplugin
State:  d6f05f726f1418e25a63e4dc734d396a0596592b (v1.0.0)

Monitor updates from `main`:
> 6124cce | 2024-03-22 21:07:46 +0100 | abeldekat
  third, goodbye
```

Now, I am a bit lost. Perhaps my harpoonline project does not update as expected because of the `ci` I setup, in `.github/workflows/ci.yml`.

I am going to create a new dummyproject, including the ci, to confirm.

Thanks for your time and explanation!

**Comment by echasnovski** [comment]
> Now, I am a bit lost. Perhaps my harpoonline project does not update as expected because of the `ci` I setup, in `.github/workflows/ci.yml`.
> 
> I am going to create a new dummyproject, including the ci, to confirm.

One other source of confusion for me during development of 'mini.deps' was that `lazygit` autofetched all branches it knows about. So if I open `lazygit` in the repository before `:DepsUpdate`, the monitor log will be empty (as fetching was already done beforehand).

Maybe something similar happens in this case.

**Comment by abeldekat** [comment]
Thanks!

I use lazygit often, but only to double check my changes. I will test without using lazygit.

**Comment by abeldekat** [comment]
It's indeed Lazygit. The situation occurs when I open Lazygit in `packdir/plugin`. Thanks a lot! 

Whilst testing, I found one scenario where the tag is not checked-out.

The repro, `~/.config/repro`:

<details>
<summary>init.lua</summary>

```lua
local function clone(path_to_site)
  local mini_path = path_to_site .. "pack/deps/start/mini.nvim"
  if not vim.loop.fs_stat(mini_path) then
    vim.cmd('echo "Installing `mini.nvim`" | redraw')
    local clone_cmd =
      { "git", "clone", "--filter=blob:none", "https://github.com/echasnovski/mini.nvim", mini_path }
    vim.fn.system(clone_cmd)
    vim.cmd("packadd mini.nvim | helptags ALL")
    vim.cmd('echo "Installed `mini.nvim`" | redraw')
  end
end

local path_to_site = vim.fn.stdpath("data") .. "/site/"
clone(path_to_site)
local MiniDeps = require("mini.deps")
MiniDeps.setup({ path = { package = path_to_site } })
local add, now = MiniDeps.add, MiniDeps.now

vim.g.mapleader = " "
now(function()
  vim.cmd.colorscheme("minischeme")

  add({ source = "abeldekat/dummy", checkout = "v1.0.0" })

  local MiniStatusline = require("mini.statusline")
  MiniStatusline.setup({
    set_vim_settings = false,
  })
end)

```

</details>


Steps:

1. Create a public project on github: `abeldekat/dummy`
2. Clone the project to ie `~/projects`
3. `cd dummy`
4. `touch one`
5. `git add .`
6. `git commit -m "one"`
7. `git push`
8. `git tag -a v1.0.0 -m "v1.0.0"`
9. `git push origin --tags`
10. verify on github that both the commit and tag are present
11. `cd ~/.config/repro`
12. `NVIM_APPNAME=repro nvim init.lua`

In `~/.local/share/repro/site/pack/deps/opt/dummy`:

```txt
dummy on  main
❮ git log --oneline | head -1
1a91c7c one
```
`DepsUpdate`:

```txt
--- dummy ---
Path:   /home/user/.local/share/repro/site/pack/deps/opt/dummy
Source: https://github.com/abeldekat/dummy
State:  1a91c7c1cb7f8d62dc3ff0ed917cfb55bdde760d (v1.0.0)

Monitor updates from `main`:
<Nothing>
```

**Summary**: mini.deps did not check out tag v1.0.0. The project has only one commit and one tag.

More steps:

1. Add a new commit "two" and push
2. `rm -rf ~/.local/state/repro ~/.local/share/repro ~/.cache/repro`
3. `NVIM_APPNAME=repro nvim init.lua`
4. During installation mini.deps outputs the checkout to v1.0.0

In `~/.local/share/repro/site/pack/deps/opt/dummy`

```txt
dummy (1a91c7c)
❮ git log --oneline
1a91c7c (HEAD, tag: v1.0.0) one
```

`DepsUpdate`:

```txt
--- dummy ---
Path:   /home/user/.local/share/repro/site/pack/deps/opt/dummy
Source: https://github.com/abeldekat/dummy
State:  1a91c7c1cb7f8d62dc3ff0ed917cfb55bdde760d (v1.0.0)

Monitor updates from `main`:
<Nothing>
```

**Summary**: All is well, when retrieving the plugin from scratch, and it has more than one commit.

**Comment by echasnovski** [comment]
> In `~/.local/share/repro/site/pack/deps/opt/dummy`:
> 
> ```
> dummy on  main
> ❮ git log --oneline | head -1
> 1a91c7c one
> ```
>
> `DepsUpdate`:
> 
> ```
> --- dummy ---
> Path:   /home/user/.local/share/repro/site/pack/deps/opt/dummy
> Source: https://github.com/abeldekat/dummy
> State:  1a91c7c1cb7f8d62dc3ff0ed917cfb55bdde760d (v1.0.0)
> 
> Monitor updates from `main`:
> <Nothing>
> ```
> 
> **Summary**: mini.deps did not check out tag v1.0.0. The project has only one commit and one tag.

I am confused. Both shell and 'mini.deps' confirmation buffer show that it is checked to the commit of `v1.0.0`. If you mean that It does not point to the exact hash of `v1.0.0` tag, then I don't think that should make a difference.

If you mean that "Monitor updates from `main`" is empty after initial clone, then it is to be expected as there is nothing to compare to yet.

**Comment by abeldekat** [comment]
I mean that in the first case, mini.deps does not **actually** checkout to "v1.0.0". In the second case, from scratch where two commits are present, it does checkout to "v1.0.0".

First case: Inside packdir, the branch is main
Second case: Inside packdir: `HEAD detached at 1a91c7c`

**Comment by echasnovski** [comment]
> I mean that in the first case, mini.deps does not **actually** checkout to "v1.0.0". In the second case, from scratch where two commits are present, it does checkout to "v1.0.0".
> 
> First case: Inside packdir, the branch is main Second case: Inside packdir: `HEAD detached at 1a91c7c`
> Second case: Inside packdir: `HEAD detached at 1a91c7c`

Ah, I understand what you mean. The logic here is the same as with tags: the goal is to make sure that `HEAD` *eventually* points to the commit it is supposed to point. It does not detach `HEAD` in this case because initially after clone it already points to where it needs to be pointed.

Although it is indeed a not 100% consistent "always have detached `HEAD`" behavior, it is consistent where it matters ("always make `HEAD` point to the proper target commit").

**Comment by abeldekat** [comment]
Thanks @echasnovski,

I very much appreciate the explanation!
