### ISSUE TITLE
Different highlight for each string section

### ISSUE THREAD

**Issue by yujinyuz** [echasnovski/mini.nvim#764]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-statusline

### Description

Apologies as I don't know how to properly add a title to this but what I'm asking is that

I wanted to have 2 sections where the first section contains the base dir and the last contains the filename (tail). What I want to do is to apply a bold style only to the second section.

I've somewhat achieved it but there's a gap between the first and second section
<img width="1038" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/10972027/6c25a463-120f-47d2-bd85-f25ddcf6a997">

Is it possible to remove it?

**Comment by echasnovski** [comment]
The 'mini.statusline' module is quite a thin wrapper around how statusline should be written using built-in method. You can take a look at `:h 'statusline'`. It is a lot of text and can be intimidating at first (I remember for me it was), but nothing that can not be understood given enough time and perseverance. In this particular case, useful information is
- `%t` gets expanded into file name (tail).
- `%{...}` evaluates Vimscript code inside its brackets.
- `%#XXX#` applies highlight group `XXX` to any text to the right of it.

The `combine_groups()` essentially concatenates groups of strings while wrapping them in spaces and highlight group prefix (in `%#XXX#` format). So to achieve different highlighting of two strings *without* spaces between them, this string needs to be supplied directly as an item.

Combining this together, here is how I'd do this:
```lua
local statusline = require('mini.statusline')
--stylua: ignore
local active = function()
  local mode, mode_hl = statusline.section_mode({ trunc_width = 120 })
  local git           = statusline.section_git({ trunc_width = 75 })
  local diagnostics   = statusline.section_diagnostics({ trunc_width = 75 })
  local fileinfo      = statusline.section_fileinfo({ trunc_width = 120 })
  local location      = statusline.section_location({ trunc_width = 75 })
  local search        = statusline.section_searchcount({ trunc_width = 75 })

  return statusline.combine_groups({
    { hl = mode_hl,                  strings = { mode } },
    { hl = 'MiniStatuslineDevinfo',  strings = { git, diagnostics } },
    '%<', -- Mark general truncate point
    -- Highlight directory part of file name differently
    '%#MiniStatuslineFilePrefix# %{expand("%:p:~:.:h")}/%#MiniStatuslineFilename#%t ',
    '%=', -- End left alignment
    { hl = 'MiniStatuslineFileinfo', strings = { fileinfo } },
    { hl = mode_hl,                  strings = { search, location } },
  })
end
statusline.setup({ content = { active = active } })
```

**Comment by yujinyuz** [comment]
Thanks!
