### ISSUE TITLE
Remember which motion was used and easily repeat it

### ISSUE THREAD

**Issue by nogweii** [echasnovski/mini.nvim#767]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

bracketed

### Description

It would be a handy key mapping that would repeat the last square bracket, or other motions.

Thinking about this more, what I want is [vim-space](https://github.com/spiiph/vim-space) but with a little more automatic integration, I guess? (And is maintained.)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I considered adding it for a while during beta-testing, but opted for (not created at that time) a submode functionality of 'mini.clue'. It has a [separate example for 'mini.bracketed' submodes](https://github.com/echasnovski/mini.nvim/blob/a683bfe8e03293e3bb079e24c94e51977756a3ec/doc/mini-clue.txt#L405-L426).

Closing as not planned.

**Comment by nogweii** [comment]
To clarify, I was thinking that this motion-repeat plugin would be more generic than square bracket motions, including things like `n`/`N`, the jumplist, and `f`/`t`. So it would span across mini.bracketed, mini.jump, and possibly mini.jump2d?

This is sounding more and more complicated and is probably own dedicated plugin rather than being a part of any existing one.

**Comment by echasnovski** [comment]
> To clarify, I was thinking that this motion-repeat plugin would be more generic than square bracket motions, including things like `n`/`N`, the jumplist, and `f`/`t`. So it would span across mini.bracketed, mini.jump, and possibly mini.jump2d?
> 
> This is sounding more and more complicated and is probably own dedicated plugin rather than being a part of any existing one.

Yes, this sounds a bit too complicated (if even possible at all).
