### ISSUE TITLE
mini.surround: respect_selection_type doesn't work in blockwise mode

### ISSUE THREAD

**Issue by aarondill** [echasnovski/mini.nvim#770]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

When using blockwise mode and `respect_selection_type`, multiline selections aren't properly highlighted

### Neovim version

NVIM v0.10.0-dev-2539+ga69c7206

### Steps to reproduce

1. `nvim -nu minimal.lua`
```lua
--- minimal.lua
local path_package = vim.fn.stdpath("data") .. "/site/"
local mini_path = path_package .. "pack/deps/start/mini.nvim"
if not vim.loop.fs_stat(mini_path) then
  vim.cmd('echo "Installing `mini.nvim`" | redraw')
  local clone_cmd = {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/echasnovski/mini.nvim",
    mini_path,
  }
  vim.fn.system(clone_cmd)
  vim.cmd("packadd mini.nvim | helptags ALL")
  vim.cmd('echo "Installed `mini.nvim`" | redraw')
end

require("mini.surround").setup({
  respect_selection_type = true,
  mappings = { add = "gza" },
})
```
3. Create file with this content:
```
line1
longline2
line3
longerline4
line5
```
4. `gg` go to first line
5. `<c-q>` enter blockwise
6. `G` select to last line
7. `$` Select to end of lines
8. `gza"` Surround selection with "

### Expected behavior

all lines are surrounded
```
"line1"
"longline2"
"line3"
"longerline4"
"line5"
```

### Actual behavior

Lines are surrounded at the last line's length
```
"line1"
"longl"ine2
"line3"
"longe"rline4
"line5"
```

Note that if this is done on the 4th line instead `longerline4`, then shorter lines are not even properly surrounded.
```
"line1
"longline2
"line3
"longerline4"
```

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, this (block selected with `$`) is indeed the edge case that can be made better. However, it won't be done in 'mini.surround' for the following reasons:
- Combination of `respect_selection_type = true` and blockwise selection until the end of line seems to be quite rare in practice. It can also be replicated by using macro. For example, `10|` to navigate to the target column followed by `sa$"`.
- Actual implementation of this edge case is not trivial while 'mini.surround' is already quite a big and complicated module.

Closing as not planned.

**Comment by j2kun** [comment]
FWIW, I also use this block method for stuff and ran into the same issue.

If this is not planned, could you add it to the mini.surround README as a known limitation? That would help folks like me who are evaluating the plugin.
