### ISSUE TITLE
Invisible cursor with some colorschemes

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#775]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Mini.Files

### Description

Hello!

Mini.Files doesn't provide a cursor highlight but does provide a CursorLine highlight. With some colorschemes, this leads to the Cursor foreground being invisible with some colorschemes.

### Neovim version

NVIM v0.10.0-dev+2724-ga0cbf1d8d

### Steps to reproduce

1. Download [colors.zip](https://github.com/echasnovski/mini.nvim/files/14805177/colors.zip)
2. Extract colors to ~/.config/nvim/colors
3. Add the following to mininal.lua
```lua
vim.opt.guicursor    : append [[n-v-c:block]]
vim.opt.guicursor    : append [[i-ci-ve:ver25]]
vim.opt.guicursor    : append [[r-cr:hor20]]
vim.opt.guicursor    : append [[o:hor50]]
vim.opt.guicursor    : append [[a:blinkwait700-blinkoff400-blinkon250-Cursor/lCursor]]
vim.opt.guicursor    : append [[sm:block-blinkwait175-blinkoff150-blinkon175]]
```
4. `nvim -nu minimal.lua`
5. `colorscheme atelier-cave`
6. `lua MiniFiles.open()`

### Expected behavior

MiniFiles should provide the Cursor highlight together with CursorLine.

### Actual behavior

![Screenshot from 2024-03-29 10-16-04](https://github.com/echasnovski/mini.nvim/assets/91024200/7f043eaa-b32a-454f-9f13-84d730831580)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/efddd64f-e2b4-45de-a35a-faaa6d13cb5d)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/5e8e728a-e85b-4536-96e8-8fa5554829bc)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/c531faa8-1b77-4f1b-acb8-4b774d06b2d2)

**Comment by wroyca** [comment]
> To be honest, currently this looks to me more like a misconfiguration issue.
> 
> > MiniFiles should provide the Cursor highlight together with CursorLine.
> 
> How would you expect potential `MiniFilesCursor` to be used? In order to be useful, it looks like 'mini.files' itself should somehow force that cursor inside its windows is highlighted with this new highlight group. I don't think I've seen this done somewhere. Do you happen to know about any other plugins that had this/similar issue and resolved it with custom highlight group for cursor?

> How would you expect potential `MiniFilesCursor` to be used?

I'd invert the colors, but looking more into it - having both a selection and a cursor doesn't work well together ultimately (crude example):

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/3d136fa8-5002-460b-b042-6f5bccc17348)

> Do you happen to know about any other plugins that had this/similar issue and resolved it with custom highlight group for cursor?

I'm not familiar with plugins internal, so I wouldn't know \;)

> In order to be useful, it looks like 'mini.files' itself should somehow force that cursor inside its windows is highlighted with this new highlight group.

Right, honestly I'm inclined to close this for now - this is too much of a niche case and not particularly useful in the end

**Comment by echasnovski** [comment]
> Right, honestly I'm inclined to close this for now - this is too much of a niche case and not particularly useful in the end

Yeah, I think I'd agree with this.
