### ISSUE TITLE
Automatically adding parenthesis to function types and class types when using mini.completion with mini.pairs.

### ISSUE THREAD

**Issue by 231tr0n** [echasnovski/mini.nvim#777]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion, mini.pairs

### Description

Hi! So in nvim-autopairs, there is this functionality where in after a item is completed from completion menu based on its type like if the entry is a function, a parenthesis is added automatically by nvim-autopairs using this code
```lua
local cmp_autopairs = require('nvim-autopairs.completion.cmp')
local cmp = require('cmp')
cmp.event:on(
  'confirm_done',
  cmp_autopairs.on_confirm_done()
)
```
Is there any mechanism as such available for mini.pairs with mini.completion. If not are there any plans to implement such feature.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

There was a similar issue (#252) with a [resolution](https://github.com/echasnovski/mini.nvim/issues/252#issuecomment-1464063494) that it essentially does not align with 'mini.nvim' design of trying to maintain a healthy "features/maintainability" ratio.

Closing as not planned.
