### ISSUE TITLE
mini.sessions: Default value `autoread = false` is confusing

### ISSUE THREAD

**Issue by buzbohdan** [echasnovski/mini.nvim#778]
Hello everyone!

I'm a Neovim newbie, so this might be a big factor. But personally I don't understand why `autoread` config by default is set to `false`. After setting up the `mini.sessions` with default config I've realized that my session is saved automatically, but for some reason not loaded automatically at the start of nvim. I've spent couple of hours trying to figure out why this was happening. Only then I've realized that `autoread` must be explicitly set to `true`

Partially I blame my own blindness - it is mentioned in the [default-config ](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-sessions.md#default-config) at which I've looked at least a couple of times. But partially my expectation was that sessions manager should automatically save AND load sessions

At the minimum I'd suggest that documentation more explicitly mentions the default behavior

Please let me know what you think

**Comment by echasnovski** [comment]
Hi!

The `config.autoread = true` means that the *latest* session will be loaded. As 'mini.sessions' provides functionality to save multiple sessions (with [`MiniSessions.write()`](https://github.com/echasnovski/mini.nvim/blob/6fffe2d106024c3c44cb0c686d168d3c7c0d5d80/doc/mini-sessions.txt#L144)), user might want to load some different (not latest) session. This is my personal workflow and the way it works together with default items of 'mini.starter'.

So the overall workflow of using multiple session usually goes like this:
- Start Neovim and open buffers/windows/tabpages.
- Decide that you want this to be saved as separate session.
- Execute `:lua MiniSessions.write('my-new-session')`. This will save current state in a global session named "my-new-session".
- Close Neovim.

To later restore "my-new-session" in a fresh Neovim instance, open Neovim (preferably with `autoread = false`) and execute `MiniSessions.read('my-new-session')`. To get the overview of all available sessions to read, execute `:lua MiniSessions.select()` and select the session to read (how selection is done depends on user's `vim.ui.select()` implementation). Or use 'mini.starter' with the latest 5 sessions and choose one.

Hope this helps.

**Comment by buzbohdan** [comment]
Hi, thanks a lot for such a quick and detailed response! It totally makes sense for your workflow

I'd still argue that most users would prefer to load their latest session when opening nvim, but that's just my personal unproven opinion, so feel free to ignore it 😄
