### ISSUE TITLE
Let MiniSessions.write() create new local session when there's no current session

### ISSUE THREAD

**Issue by edshamis** [echasnovski/mini.nvim#78]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions

### Description

I would expect MiniSessions.write() when run without arguments and no current session is opened to create a new local session with MiniSessions.config.file name at cwd.
What do you think?

**Comment by echasnovski** [comment]
I am currently leaning towards explicitly supplying session name. Is there a particular problem to use `MiniSessions.write('Session.vim')` (or other value of `MiniSessions.config.file`)?

**Comment by edshamis** [comment]
No problem, just felt inconsistent to my taste. Out of curiosity, what are your considerations here? If you have spare time to share

**Comment by echasnovski** [comment]
Write now: it is a breaking change without considerable benefit.

Initially:
- Explicit is better than implicit.
- It is consistent with how `MiniSessions.delete()` works in this case (no argument and no current session).
- I don't like local sessions for some reason.

Closing this then.
