### ISSUE TITLE
Add an option to disable highlighting autocmds in mini.trailspace

### ISSUE THREAD

**Issue by tristan957** [echasnovski/mini.nvim#782]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.trailspace

### Description

I can't figure out how to get it to stop in buffers that I don't care about.

```lua
vim.api.nvim_create_autocmd({ 'WinEnter', 'BufEnter', 'InsertLeave' }, {
  desc = "Stop highlighting trailing white space",
  group = group,
  callback = function(ev)
    -- If we ask for trailing whitespace, respect it
    if string.find(vim.bo[ev.buf].formatoptions, "w") ~= nil then
      MiniTrailspace.unhighlight()
    end
  end,
})
```

I'm thinking this is related to order of operations and the mini.trailspace autocommands might be running first.

**Comment by echasnovski** [comment]
Disabling in all modules is done by setting corresponding global or buffer-local boolean variable. For 'mini.trailspace' [it is `vim.b.minitrailspace_disable`](https://github.com/echasnovski/mini.nvim/blob/f3092db48dd2dfd3d32df5a5be4d56ed0c0b1ef9/doc/mini-trailspace.txt#L35-L43).

So to make it work, also add setting this variable inside autocommand callback:

```lua
vim.api.nvim_create_autocmd({ 'WinEnter', 'BufEnter', 'InsertLeave' }, {
  desc = 'Stop highlighting trailing white space',
  group = group,
  callback = function(ev)
    local should_disable = string.find(vim.bo[ev.buf].formatoptions, 'w') ~= nil
    vim.b[ev.buf].minitrailspace_disable = should_disable
    if should_disable then MiniTrailspace.unhighlight() end
  end,
})
```
