### ISSUE TITLE
[mini.starter] sessions are broken when a file named Starter is in the session

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#787]
### Discussed in https://github.com/echasnovski/mini.nvim/discussions/786

<div type='discussions-op-text'>

<sup>Originally posted by **ldelossa** April  7, 2024</sup>
I'm wondering if this is an issue.

I have auto-session working as a session manager, and I use it through mini.starter.
I don't think this has to do with what session manager is in use tho. 

I think if you're using mini.starter and you do the following with a session manager:
1. Open nvim
2. Open one or two other files
3. Create a source file in your repo called Starter
4. Save your session

When you go to restore this session in mini.starter I get this:

```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":                              
Error executing lua callback: ...nvim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:1251: Cursor p
osition outside buffer                                                                                  
stack traceback:                                                                                        
        [C]: in function 'nvim_win_set_cursor'                                                          
        ...nvim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:1251: in function 'position_cursor_o
n_current_item'                                                                                         
        ...nvim/site/pack/deps/start/mini.nvim/lua/mini/starter.lua:1319: in function <...nvim/site/pack
/deps/start/mini.nvim/lua/mini/starter.lua:1319>    
``` 

I think mini.starter may get confused in this case. Would it make more sense to use a buffer name which starts with ```starter:///``` to ensure the starter buffer does not overlap with any files?</div>

**Comment by echasnovski** [comment]
Yes, indeed 'mini.starter' does not check existing buffers for possibly duplicating names. I can reproduce an error related to having the buffer named the same as the one in 'mini.starter', but the error is different then what what you (@idelossa) report.

Does replacing [these lines](https://github.com/echasnovski/mini.nvim/blob/d0b297ab233a57bed00ab69bd66135dee111967f/lua/mini/starter.lua#L1339-L1340) with the following one line solve the issue for you?

```lua
  vim.api.nvim_buf_set_name(buf_id, 'starter://' .. H.buffer_number)
```

**Comment by ldelossa** [comment]
Yup that works.

**Comment by echasnovski** [comment]
This should be fixed on latest `main`.
