### ISSUE TITLE
Mention built-in commenting in mini.comment readme

### ISSUE THREAD

**Issue by flexagoon** [echasnovski/mini.nvim#793]
Since nvim 0.10 introduces built-in commenting support (the author of which is also the author of Mini.nvim), mini.comment is no longer necessary for users that don't need extra customisation. Perhaps this should be mentioned in the readme?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is planned after Neovim 0.10 release.

**Comment by echasnovski** [comment]
With Neovim 0.10 release, its built-in commenting is now [mentioned as "similar plugin"](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-comment.md#similar-plugins),

**Comment by yujinyuz** [comment]
@echasnovski Does this mean that this plugin is not necessary with the latest 0.10 release?

**Comment by echasnovski** [comment]
> @echasnovski Does this mean that this plugin is not necessary with the latest 0.10 release?
> 
> EDIT: Apologies. Didn't read OPs description. I'll try removing mini comment from my config and see if this is still necessary.

Indeed, built-in commenting in Neovim 0.10 can mostly be used instead of 'mini.comment' if users don't rely on its customization abilities (custom commentstring, hooks, several behavior options, etc.). Otherwise - not really.
