### ISSUE TITLE
Mini map custom symbols have no effect

### ISSUE THREAD

**Issue by alekspickle** [echasnovski/mini.nvim#796]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Map

### Description
First of all - thank you so much for this amazing project and I am really devastated I did not find it earlier, it could've save me days of time.
I am experimenting with map symbols but it appear to not take effect and I have no idea why.

![Screenshot_20240410_132012](https://github.com/echasnovski/mini.nvim/assets/22867443/ed218707-6c8e-459f-9c8f-52871786ab27)

### Neovim version

0.9.1

### Steps to reproduce

<details>
<summary>config</summary>

```
local minimap = require("mini.map")
minimap.setup {
    {
        symbols = {
            -- Scrollbar parts for view and line. Use empty string to disable any.
            -- - Line - '🮚', '▶'.
            -- - View - '╎', '┋', '┋'.
            -- scroll_line = '█',
            -- scroll_view = '┃',
            -- scroll_line = '..',
            -- scroll_view = '.',
            scroll_line = '▶',
            scroll_view = '┋',
        },
        window = {
            show_integration_count = true,
            width = 7,
            winblend = 25,
            zindex = 10,
        },
    }
}

```

</details>

### Expected behavior

map symbols are updated on nvim restart

### Actual behavior

default symbols are used after relaunch

**Comment by echasnovski** [comment]
> First of all - thank you so much for this amazing project and I am really devastated I did not find it earlier, it could've save me days of time.

:pray:

> I am experimenting with map symbols but it appear to not take effect and I have no idea why.

The config has extra nesting (`{ { symbols = { ... } } }`) where it should not (`{ symbols = { ... } }`). Remove outer pair of `{}` and it should work.
