### ISSUE TITLE
[mini.diff] E801: ID already taken: 3

### ISSUE THREAD

**Issue by xigoi** [echasnovski/mini.nvim#797]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.diff

### Description

When opening Neovim under some specific conditions which I can’t figure out, the following error message appears, possibly multiple times:

```
Error executing vim.schedule lua callback: BufWinEnter Autocommands for "*"..function <SNR>30_Highlight_Matching_Pair, line 149: Vim(call):E801: ID already taken: 3                                                                                                            
stack traceback:                                                                                                                        
        [C]: in function 'bufload'                                                                                                      
        /home/xigoi/.local/share/nvim/lazy/mini/lua/mini/diff.lua:438: in function 'enable'                                             
        /home/xigoi/.local/share/nvim/lazy/mini/lua/mini/diff.lua:989: in function ''                                                   
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Observations:

* I have only observed this happening with files written in the [xidoc](https://xidoc.nim.town/) language. **However**, what’s truly weird is that the filetype does not actually matter, only the contents. If I take a xidoc file and rename it to a different filetype, the error still occurs. If I take a non-xidoc file and give it the .xd extension, the error does not occur.
* The error only seems to occur when opening at least 3 files at once, and opening more files generally increases the number of errors, but in a non-deterministic way.
* The errors don’t show up instantly; there is a small delay between them.
* Commenting out line 438 in mini/diff.lua seems to fix the issue, though it obviously breaks the plugin.

### Neovim version

0.9.4

### Steps to reproduce

Unfortunately, as mentioned, I don’t know how to reliably create this issue. I can send some files for which it happens if needed.

The `mini.diff` setup is irrelevant, the issue still happens with an empty setup.

### Expected behavior

No errors

### Actual behavior

The mentioned errors appear.

**Comment by xigoi** [comment]
Yes, this patch solves the issue. Thanks for the detailed investigation!

**Comment by echasnovski** [comment]
Great! I plan to apply it tomorrow.

**Comment by echasnovski** [comment]
Adam, thanks again for an interesting issue and quick feedback on solution!

This patch is now part of latest `main`.
