### ISSUE TITLE
mini.pick doesn't open URI paths generated by the jdtls language server for lsp actions (definition, implementation etc.)

### ISSUE THREAD

**Issue by zydras07** [echasnovski/mini.nvim#798]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Potentially following from #714, mini.pick will not open URI paths generated by jdtls for decompiled class files from lsp actions. I am not sure whether this is specific to jdtls or more general.

### Neovim version

0.10.0-dev-2826+gf6dcc464f

### Steps to reproduce

1. Ensure mini.pick, mini.extra and the jdtls language server are installed and configured.
2. Create a new Java project.
3. In `App.java`, write
```java
package org.example;  // relevant package name

public class App {
    public static void main(String[] args) {
        System.out.println("-");
    }
}
```
4. Move the cursor to `System` and call `require("mini.extra").pickers.lsp({ scope = "definition" })`.
5. Select the first and only option in the picker.

### Expected behavior

The URI should be opened in Neovim.

### Actual behavior

The URI is not opened, and `}` is printed below the statusline.

**Comment by echasnovski** [comment]
Thanks for the issue!

I don't have Java stack installed (and don't plan to at the moment), so would you mind helping me debug this? As `MiniExtra.pickers.lsp()` uses corresponding `vim.lsp.buf` methods, could execute the following command in the same conditions as when you'd call `lsp` picker:

```
-- Execute `vim.lsp.buf.definition()` but save the result instead of acting on it
:lua vim.lsp.buf.definition({ on_list = function(...) _G.args = { ... } end })
```

Then follow up with `:lua vim.fn.append(0, vim.split(vim.inspect(args), '\n'))` which will paste `args` as text at the top of current buffer. Copy those lines and paste them here.

**Comment by zydras07** [comment]
```
{ {
    items = { {
        col = 20,
        filename = "jdt://contents/java.base/java.lang/System.class?=Test/%5C/usr%5C/lib%5C/jvm%5C/java-11-openjdk-amd64%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/=/maven.pomderived=/true=/%3Cjava.lang(System.class",
        lnum = 36,
        text = "public final class System {",
        user_data = {
          range = {
            ["end"] = {
              character = 25,
              line = 35
            },
            start = {
              character = 19,
              line = 35
            }
          },
          uri = "jdt://contents/java.base/java.lang/System.class?=Test/%5C/usr%5C/lib%5C/jvm%5C/java-11-openjdk-amd64%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/11%5C/docs%5C/api%5C/=/=/maven.pomderived=/true=/%3Cjava.lang(System.class"
        }
      } },
    title = "LSP locations"
  } }
```

**Comment by zydras07** [comment]
It's not an actual path to a file.

**Comment by echasnovski** [comment]
Then sorry, but this doesn't look like a 'mini.extra' issue. The argument to the `on_list` function is assumed to have `items` which is structured same as quickfix list (as per `:h vim.lsp.LocationOpts.OnList`). In quickfix list items can have `filename` field which is a "name of a file" (meaning full path, really). This is not the case in this example.

I am not sure where the issue here is: either in `jdtls` itself or Neovim's handling of `on_list`.

Closing as "this doesn't look like a 'mini.extra' issue, sorry".
