### ISSUE TITLE
Selecting `toggleterm.nvim` terminal with `MiniPick.ui_select()` breaks it's mappings

### ISSUE THREAD

**Issue by AlexKurisu** [echasnovski/mini.nvim#804]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Selecting ToggleTerm terminal with `:TermSelect` while `vim.ui.select` is set to `MiniPick.ui_select` breaks ToggleTerm's terminal-mode mappings (e.g. open-close mapping)

### Neovim version

v0.10.0-dev-2849+g4946489e2e

### Steps to reproduce

<details>
<summary>minimal.lua</summary>

```lua
-- Bootstrap `mini.nvim`
local path_package = vim.fn.stdpath("data") .. "/site"
local mini_path = path_package .. "/pack/deps/start/mini.nvim"
if not vim.uv.fs_stat(mini_path) then
	vim.cmd([[echo "Installing `mini.nvim`" | redraw]])
	local clone_cmd = {
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/echasnovski/mini.nvim",
		mini_path,
	}
	vim.system(clone_cmd):wait()
	vim.cmd([[packadd mini.nvim | helptags ALL]])
	vim.cmd([[echo "Installed `mini.nvim`" | redraw]])
end

-- Setup `mini.deps`
require("mini.deps").setup({ path = { package = path_package } })

require("mini.pick").setup({})
_G.vim.ui.select = MiniPick.ui_select

MiniDeps.add({ source = "akinsho/toggleterm.nvim", checkout = "v2.10.0" })
require("toggleterm").setup({
	open_mapping = "<C-\\>",
	direction = "float",
})

```

</details>

1. `nvim -nu minimal.lua`
2. Press `<C-\>` twice to open and close ToggleTerm
3. Run `:TermSelect` and select the terminal
4. Press `<C-\>` again. It will switch to normal mode instead of closing.

### Expected behavior

ToggleTerm window closes with the `<C-\>` key after opening it from `:TermSelect`

### Actual behavior

ToggleTerm window switches to normal mode. Switching back to neovim's native `vim.ui.select` fixes the problem.

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce. Although I am having hard time figuring out the actual reason why this happens, as the `<C-\>` Terminal mode mapping for 'toggleterm' is there. It might have something to do with how 'toggleterm.nvim' tracks data which is not compatible with `MiniPick.ui_select()`. I'll take a look.

**Comment by echasnovski** [comment]
After embarrassingly long time of debugging, the issue was that `ui_select()` called `on_choice(item, idx)` with `item` being a copy of original `items[idx]`. This is not *exactly* prohibited and overall relying in `on_choice()` that the item is exact one is not a good approach.

This should now be fixed on `main`. But I've also made a akinsho/toggleterm.nvim#566 PR to address this for other `ui.select()` implementations.
