### ISSUE TITLE
On replacing tag, allow presenve props

### ISSUE THREAD

**Issue by JonatasAmaral** [echasnovski/mini.nvim#808]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

It would be nice, when doing a surround replace tag, by another tag, some special char could be used on the input, to put the original tag's props back in.

Ex:
given `<div class="menu" ...>`

press `srtt`

input: `nav %`

gets `<nav class="menu" ...>`

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already discussed in #397 with resolution that it doesn't quite fits the 'mini.surround' design.

Closing as duplicate of #397.
