### ISSUE TITLE
mini.pick: auto jump with one destination

### ISSUE THREAD

**Issue by zydras07** [echasnovski/mini.nvim#809]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

For LSP type pickers, it would be useful to automatically jump to a location when there is only one location to jump to without opening the menu. This could be implemented as a picker option.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already [discussed during beta-testing](https://github.com/echasnovski/mini.nvim/issues/550#issuecomment-1792044864). My reasoning is that starting a picker should *always* result into showing a picker.

Closing as not planned.
