### ISSUE TITLE
mini.completion: client.resolved_capabilities is deprecated in 0.8

### ISSUE THREAD

**Issue by bockel** [echasnovski/mini.nvim#81]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

`vim.lsp.client.resolved_capabilities` property as used in https://github.com/echasnovski/mini.nvim/blob/ee7c02297cf95cba07f8bf8da3ecf99337a1c15e/lua/mini/completion.lua#L804 is deprecated as of nvim 0.8.

See https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

```
[LSP] Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol
```

### Neovim version

NVIM v0.8.0-dev+141-g55187de11

### Steps to reproduce

1. Upgrade to nvim nightly
2. Enable mini.completion
3. Enter insert mode
4. A message is generated by nvim

My mini.completion configuration

```
             require("mini.completion").setup({
                 lsp_completion = {
                     source_func = "omnifunc",
                     auto_setup = false,
                     mappings = {
                         force_twostep = "<C-Space>",
                         force_fallback = "<S-Space>",
                     },
                 },
             })
```

### Expected behavior

No warning message of deprecated API use

### Actual behavior

Nvim generates a warning message when initially entering insert mode.

```
[LSP] Accessing client.resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities instead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol
```

**Comment by echasnovski** [comment]
Thanks! I'll look into it.

**Comment by echasnovski** [comment]
Should work now on recent `main` without warnings. Thanks for noticing this!
