### ISSUE TITLE
Missing transparency on some elements when applying add_transparency

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#818]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Colors

### Description

Hello o/

Using add_transparency({float = true}) with MiniColors will miss some elements, (e.g. MiniFilesTitles, MiniClueNextKeys, ...)

These are not "float" if we are pedantic with the definition, but they're part (as in, elements) of Mini floats so I believe they should follow suit

### Neovim version

NVIM v0.10.0-dev+2931-g7fa24948a

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `lua MiniColors.interactive()`
3. `add_transparency({float = true})`
4. `lua MiniFiles.open()` or `lua MiniPick.builtin.grep_live()` or others.

### Expected behavior

Title, keys, and others that are on a transparent float should also have a transparent background to not look out of place.

### Actual behavior

![Screenshot from 2024-04-17 11-21-09](https://github.com/echasnovski/mini.nvim/assets/91024200/5e059757-79b5-4934-b4ae-d92f7232567c)
![Screenshot from 2024-04-17 11-21-17](https://github.com/echasnovski/mini.nvim/assets/91024200/6a4baf2d-ac19-41ab-947a-04065fcdb949)
![image](https://github.com/echasnovski/mini.nvim/assets/91024200/5b835093-0adf-4372-b9a2-6c2bcbacdc9b)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

`MiniColors.add_transparency()` is mostly designed to work [with built-in groups](https://github.com/echasnovski/mini.nvim/blob/decd729b784c4f6cb775da335f3c8eecb846250c/doc/mini-colors.txt#L418). Making exceptions for 'mini.nvim' is possible, but might be not very sustainable in the long run. I'll think about it.

**Comment by echasnovski** [comment]
I think sticking to built-in groups in this kind of functionality is better from maintenance perspective.

Closing as not planned.
