### ISSUE TITLE
Support multiple opened starter buffers

### ISSUE THREAD

**Issue by bzub** [echasnovski/mini.nvim#82]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

With an existing starter buffer open, if I make a new tab for example and try to run `lua MiniStarter.open()` I get the following errors.

```
E5108: Error executing lua ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:1240: Vim:E95: Buffer with this name already exists
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:1240: in function 'apply_buffer_options'
        ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:335: in function 'open'
        [string ":lua"]:1: in main chunk
```
```
Error detected while processing CursorMoved Autocommands for "<buffer=4>":
E5108: Error executing lua ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:1165: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:1165: in function 'position_cursor_on_current_item'
        ...im/site/pack/packer/start/mini.nvim/lua/mini/starter.lua:919: in function 'on_cursormoved'
        [string ":lua"]:1: in main chunk
```

My ultimate goal is to have starter open when I create a new tab. I used to do this with alpha using:

```lua
vim.cmd([[ autocmd TabNewEntered * Alpha ]])
```

### Neovim version

v0.7.0

### Steps to reproduce

See Description.

### Expected behavior

See Description.

### Actual behavior

See Description.

**Comment by echasnovski** [comment]
Thanks for a completely valid use case! I very rarely use tabs so almost always forget to make modules work with them.

At the moment 'mini.starter' was designed to work only with a single buffer opened. But your example is a type of behavior I would like to support. I'll work on it (not immediately, though, unfortunately).

**Comment by echasnovski** [comment]
@bzub, sorry for the long wait. This should now be possible. For your use case I'd recommend doing this: `autocmd TabNewEntered * ++nested lua MiniStarter.open()` (as there might be some autocommands involved in `open()`).

This required an order of magnitude more changes than I'd like to. This is the price of an initially and consciously lazy design :(
