### ISSUE TITLE
Can not paste a path to search in mini.pick

### ISSUE THREAD

**Issue by thieung** [echasnovski/mini.nvim#820]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

Can not paste a path to search in mini.pick (Pick File)

### Neovim version

0.9.5

### Steps to reproduce

1. Start nvim (already installed mini.pick plugin using stable version)
2. Open minipick window (using MiniPick.buildtin.files)
3. Cmd + v to paste a path I copied.
4. Refer below attachment to see the issue:
![image](https://github.com/echasnovski/mini.nvim/assets/79964592/f95b71fd-1d3f-48b6-b174-29aee18038c1)

### Expected behavior

It should paste my path into mini.pick textbox and trigger searching for that text 

### Actual behavior

It does nothing

**Comment by thieung** [comment]
Thanks @echasnovski

**Comment by theherk** [comment]
I tried both

```lua
vim.api.nvim_create_autocmd("BufEnter", {
    callback = function(args)
      if require("mini.pick").is_picker_active() then
        vim.keymap.set("n", "<d-v>", "<c-r>+", { buffer = args.buf, noremap = true, silent = true })
        vim.api.nvim_create_autocmd("BufLeave", {
          buffer = args.buf,
          callback = function() vim.keymap.set("n", "<d-v>", '"+p', { noremap = true, silent = true }) end,
          once = true,
        })
      end
    end,
  })
```

and

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "MiniPick",
    callback = function(args)
      vim.keymap.set("n", "<d-v>", "<c-r>+", { buffer = args.buf, noremap = true, silent = true })
      vim.api.nvim_create_autocmd("BufLeave", {
        buffer = args.buf,
        callback = function() vim.keymap.set("n", "<d-v>", '"+p', { noremap = true, silent = true }) end,
        once = true,
      })
    end,
  })
```

But didn't have luck. `<c-r>+` is sufficient, but it would be nice to use the same paste command within the pickers.

**Comment by echasnovski** [comment]
> But didn't have luck.

That's because 'mini.pick' doesn't operate in regular mappings as it introduces its own key query process. Use [custom actions](https://github.com/echasnovski/mini.nvim/blob/f90b6b820062fc06d6d51ed61a0f9b7f9a13b01b/doc/mini-pick.txt#L595-L614) for this. But I'd still recommend using `<C-r>+` as pasting from system clipboard provider is a bit tricky.

**Comment by theherk** [comment]
Yeah, that's actually dead easy.

```lua
  minipick.setup({
    mappings = {
      sys_paste = { char = "<d-v>", func = function() minipick.set_picker_query({ vim.fn.getreg("+") }) end },
    },
  })
```

Thanks a ton @echasnovski.

**Comment by luiseduardobatista** [comment]
I did it a bit differently. This way, it's like an alias for "<C-r>+", avoiding some issues I had, such as interpreting the pasted text as a character and clearing the search database when I try to paste again.

```lua
require("mini.pick").setup({
	options = { use_cache = true },
	window = { config = win_config },
	mappings = {
		choose_in_vsplit = "<C-CR>",
		sys_paste = {
			char = "<C-v>",
			func = function()
				vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<C-r>+", true, true, true), "n", true)
			end,
		},
	},
})
```
