### ISSUE TITLE
mini.extra - Remove visits.label within mini.pick

### ISSUE THREAD

**Issue by grierson** [echasnovski/mini.nvim#823]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.extra, mini.visits, mini.pick

### Description

When using `MiniExtra.pickers.visit_paths()`
Press `C-d` on selected item  to `MiniVisits.remove_label()`

**Comment by echasnovski** [comment]
Thanks for the suggestion!

All pickers in 'mini.pick' and 'mini.extra' are mostly designed for picking and not manipulating items. Taking into account that this should be doable in custom mapping, I don't think this is a good idea to add to `MiniExtra.pickers.visit_paths()`.

Closing as not planned.
