### ISSUE TITLE
mini.tabline: Add marker to tabs that have been modified. 

### ISSUE THREAD

**Issue by DzedCPT** [echasnovski/mini.nvim#824]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

I find it helpful when edited tabs include a marker in their file name to signify that the tab has been modified. I know that mini.tabline changes the highlight group but I often miss this and find having the marker very useful to avoid running code before saving changes. I've implemented it locally so that modified files have a little `+` suffix and it looks like this, if for example `init.lua` has been modified:

<img width="431" alt="Screenshot 2024-04-19 at 19 44 13" src="https://github.com/echasnovski/mini.nvim/assets/90834269/bfed6010-7818-4291-bbde-ae9182817267">

My suggestion is to make it configurable (ie you can pick the modified marker) and make the default be the current behaviour (ie the modified marker is the empty string `""`).

I'd be happy to upstream these changes but I'd like to first know if this is a feature people are open to or not?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Yes, the primary way of how 'mini.tabline' shows modified files is with [`MiniTablineModifiedXxx` highlight groups](https://github.com/echasnovski/mini.nvim/blob/e623d29561746637b49d30d6434338f88f44e856/doc/mini-tabline.txt#L53-L55). And in the spirit of trying to have tabline as narrow as possible, I don't think adding duplicating marker is a good design.

My suggestion is to ensure that "modified" highlight groups are very visible. Like, for example, ['mini.hues' has them inverted compared to not-modified tab](https://github.com/echasnovski/mini.nvim/blob/e623d29561746637b49d30d6434338f88f44e856/lua/mini/hues.lua#L1160-L1162).

Closing as not planned.

**Comment by DzedCPT** [comment]
Thanks for the thorough response. 

A couple of points
1. I don't want to fiddle with highlight groups because it can make changing themes a pain, plus I don't want things to get too colourful. 
2. Also, a '+' is a standard vim way to mark a buffer as edited and unsaved as this is what the default status line does, whereas with colours it's harder to remember what each colour combination means (ie is it a modified tab or the current tab?). Plus you have to relearn what the colours mean each time you change the theme.

All of that being said, I don't mean to force this, I'm happy to keep these changes local, and I understand that having multiple ways to indicate the same thing isn't necessarily the cleanest (or dare I say mini-iest) way of doing it.

**Comment by pkazmier** [comment]
I, too, wanted some marker initially, but that's because I never thought about inverting the colors as @echasnovski  does in `mini.hues`. Sample screenshot below, which makes it easy to see the three modified buffers:

<img width="762" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/747855/eb1cb81c-e80e-4055-93d6-63409a0b9017">

**Comment by echasnovski** [comment]
@DzedCPT, although I still recommend using colors to indicate modified buffers, a more general label customization is now possible [with `config.format`](https://github.com/echasnovski/mini.nvim/blob/cd3a08fbf987dabcfded35ebb612e82f8000f92a/doc/mini-tabline.txt#L104-L116). The help page has the example of how to add "+" suffix for modified buffers.

**Comment by DzedCPT** [comment]
Very cool, thanks for letting me know 😀
