### ISSUE TITLE
[mini.pick] Unable to search hidden files

### ISSUE THREAD

**Issue by thieung** [echasnovski/mini.nvim#825]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

Currently can not search hidden files, it would be nice if we can have an option to enable it.
Thank you!

**Comment by echasnovski** [comment]
If you mean something like `:Pick files` or `:Pick grep_live` does not have hidden files in the output, then [it is meant to be solved by configuring underlying CLI tool](https://github.com/echasnovski/mini.nvim/blob/e623d29561746637b49d30d6434338f88f44e856/doc/mini-pick.txt#L79-L84). They both use `rg` by default which can have `--hidden` line in [configuration file](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) to respect hidden files when searching.
