### ISSUE TITLE
mini.starter draws its buffer inside telescope's prompt on startup

### ISSUE THREAD

**Issue by GuiltiTer** [echasnovski/mini.nvim#827]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.starter

### Description

When starting NeoVim using `nvim -c "Telescope find_files"`, NeoVim opens Telescope on startup, then `starter` draws its buffer inside the Telescope's prompt.

### Neovim version

0.9.5

### Steps to reproduce

1. `mini.starter` is enabled and `autoopen=true`
2. `nvim -c "Telescope find_files"`

### Expected behavior

To `mini.starter` draw its buffer behind the Telescope's picker, or draw nothing at all.

### Actual behavior

`mini.starter` draws its buffer inside Telescope's prompt.

<img width="1578" alt="Screenshot 2024-04-20 at 21 50 20" src="https://github.com/echasnovski/mini.nvim/assets/31219852/d9b28102-9e02-4beb-b48a-19707ac09b27">

**Comment by GuiltiTer** [comment]
Assigning a priority higher than Telescope didn't work as well.

**Comment by echasnovski** [comment]
Thanks for the issue! I can reproduce. Will take a look at the best way to update how 'mini.starter' decides when it should show itself at the startup.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.

**Comment by GuiltiTer** [comment]
Awesome! works perfectly fine👌
