### ISSUE TITLE
mini.deps example doesn't load LSP client in time

### ISSUE THREAD

**Issue by bluebrown** [echasnovski/mini.nvim#829]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.deps

### Description

There is an here, including lspconfig: https://github.com/echasnovski/mini.nvim/blob/e623d29561746637b49d30d6434338f88f44e856/scripts/init-deps-example.lua#L44

When following this, the first opened buffer won't get a LSP client attached. I think lspconfig should not be called `later`, to avoid this problem. It works as expected when using `now` to set up the LSP.

### Neovim version

v0.10.0-dev-2954+g13ebfafc9

### Steps to reproduce

```lua
later(function()
  add("neovim/nvim-lspconfig")
  local lspconfig = require("lspconfig")
  local caps = vim.lsp.protocol.make_client_capabilities()
  lspconfig["lua_ls"].setup({ capabilities = caps })
  lspconfig["gopls"].setup({ capabilities = caps })
end)
```

then run:

```bash
nvim init.lua # no client
:e main.go # has client
```

If you try the other way around, you see go doesnt have a client attached, but lua does.

### Expected behavior

lsp client is attached to first buffer.

### Actual behavior

lsp client is only attached from the second buffer onwards 

It works when using it on `now`, but I am not sure if this is OK.

**Comment by echasnovski** [comment]
Thanks for pointing that out!

Yes, it indeed works like that. Mostly because I expected 'mini.nvim' to be used with 'mini.starter' (as I do right now) and `later()` leads to smaller startup time. But yeah, example 'init.lua' might be better off with `now()`.

Should be fixed on latest `main`.
