### ISSUE TITLE
Passing CLI args to mini.pick files tool

### ISSUE THREAD

**Issue by avegancafe** [echasnovski/mini.nvim#830]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.pick

### Description

I'm not sure if this is a bug or a feature request, but the "official" docs [here](https://github.com/echasnovski/mini.nvim/blob/7af4878bd0b19fcef385e45715f418165eff1218/doc/mini-pick.txt#L81) say to follow the configuration patterns for the individual tool in order to be able to configure pickers, but `fd` doesn't provide a global way to always display hidden files, and mini.pick from what I can tell has no way to set arguments that need to be forwarded to the command run powering the builtin `files` picker. This seems like both a small feature and one I'm surprised doesn't exist, given how ubiquitous it is in all of the other pickers I've tried. Is this possible in mini.pick? I am willing to add clarifying documentation if it is.

### Neovim version

v0.10.0-dev-2104+gfd2ed024c-Homebrew

### Steps to reproduce

Any mini.pick configuration using `fd` 

### Expected behavior

I am able to pass the `--hidden` argument to `fd` when using `mini.pick.builtin.files` picker

### Actual behavior

I am not able to pass any CLI arguments

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Indeed, customizing built-in picker with CLI arguments is not supported. This is mostly to avoid extra documentation for which arguments area used by default plus the way to override them. The main CLI tool used in 'mini.pick' is `rg` which does have the global way to configure how it does the search.

[Currently suggested approach](https://github.com/echasnovski/mini.nvim/blob/41487016b71506769c45afac1aee41a180e57fae/doc/mini-pick.txt#L1052-L1053) is to indeed either configure tool globally or use [`builtin.cli()`](https://github.com/echasnovski/mini.nvim/blob/41487016b71506769c45afac1aee41a180e57fae/doc/mini-pick.txt#L1143) directly with any set of arguments which will not conflict with the ones used by default.

Closing as not planned.

**Comment by avegancafe** [comment]
@echasnovski would you by any chance be able to scan over that commit I just pushed? I totally understand if not, especially 'cause it's in a LISP. But this seems like quite a lot of code needed to get the same behavior as the built in `files` picker, when I basically just wanted to add `--hidden` as an argument to the `fd` tool

**Comment by echasnovski** [comment]
> @echasnovski would you by any chance be able to scan over that commit I just pushed? I totally understand if not, especially 'cause it's in a LISP. But this seems like quite a lot of code needed to get the same behavior as the built in `files` picker, when I basically just wanted to add `--hidden` as an argument to the `fd` tool
> 
> EDIT: To clarify, a lot of the pain in this is that a lot of those functions called in the builtin files picker are not public, like that `H.cli_postprocess` or `H.show_with_icon` and such

There is no need in `cli_postprocess`. Here is the suggested approach with showing icons:

```lua
require('mini.pick').setup()
MiniPick.registry.files_fd = function()
  local command = { 'fd', '--type=f', '--no-follow', '--color=never', '--hidden' }
  local show_with_icons = function(buf_id, items, query)
    return MiniPick.default_show(buf_id, items, query, { show_icons = true })
  end
  local source = { name = 'Files fd', show = show_with_icons }
  return MiniPick.builtin.cli({ command = command }, { source = source })
end
```

Here is the approach without icons:

```lua
MiniPick.registry.files_fd = function()
  local command = { 'fd', '--type=f', '--no-follow', '--color=never', '--hidden' }
  return MiniPick.builtin.cli({ command = command })
end
```

Now using `:Pick files_fd` should use `fd` and show hidden files.

**Comment by avegancafe** [comment]
Ooh nice! I'll do that instead, thank you so much for checking it out

**Comment by jdx5c** [comment]
@echasnovski Sorry to resurrect this thread, but I have (hopefully) a quick follow-up question to this.   I am setting up mini.pick and ran into this exact situation with fd.   However I'm a bit new to lua and setting up my plugins (using lazy.nvim), so I'm not sure where to place the code snippet above (or if I need to tweak it first).  I have a **mini.lua** file where I import mini.pick like this:

``` lua
    { 
        'nvim-mini/mini.pick', 
        config = function()
            require("mini.pick").setup { }
        end
    },
```

Do I use this code snippet directly inside setup?  Do I need to use mini.builtin.files and set tool to fd?  Ultimately, my goal is to control the behavior of fd when picking files and eventually use this with my mini.starter config.

btw, using mini.nvim plugins has been a great experience and has made my journey into Neovim quite enjoyable so far!

**Comment by echasnovski** [comment]
> Do I use this code snippet directly inside setup? Do I need to use mini.builtin.files and set tool to fd? Ultimately, my goal is to control the behavior of fd when picking files and eventually use this with my mini.starter config.

Put any of the snippets from [this comment](https://github.com/nvim-mini/mini.nvim/issues/830#issuecomment-2070194302) directly after `require('mini.pick').setup()`. This will create new `files_fd` picker which you can use like `:Pick files_fd`.

You can create a mapping for it with like this: `vim.keymap.set('n', '<Leader>ff', '<Cmd>Pick files_fd<CR>')`.

> btw, using mini.nvim plugins has been a great experience and has made my journey into Neovim quite enjoyable so far!

Thanks for kind words! 🙏 Hope you'll keep enjoying it.
