### ISSUE TITLE
A way to disable default mini.starter keybinds

### ISSUE THREAD

**Issue by Mateiadrielrafael** [echasnovski/mini.nvim#831]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

A lot of people use `C-p` in order to bring up the telescope file picker, which conflicts with the buffer-local mapping introduced by `mini.starter`. I tried looking through the help file, but couldn't find a way to remove said keybind. Is there a way to do this?

**Comment by echasnovski** [comment]
Yes, there is a way to do this. All special keys are implemented as [buffer local mappings](https://github.com/echasnovski/mini.nvim/blob/41487016b71506769c45afac1aee41a180e57fae/doc/mini-starter.txt#L257). Users can use special [`MiniStarterOpened` even](https://github.com/echasnovski/mini.nvim/blob/41487016b71506769c45afac1aee41a180e57fae/doc/mini-starter.txt#L262) to delete mappings they don't like inside an autocommand. With something like this:

```lua
require('mini.starter').setup()
local disable_ctrl_np = function()
  vim.keymap.del('n', '<C-n>', { buffer = true })
  vim.keymap.del('n', '<C-p>', { buffer = true })
end
vim.api.nvim_create_autocmd('User', { pattern = 'MiniStarterOpened', callback = disable_ctrl_np })
```
