### ISSUE TITLE
Align individual sections in starter page

### ISSUE THREAD

**Issue by Mateiadrielrafael** [echasnovski/mini.nvim#832]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.starter

### Description

It would be nice if there was a way to independently align the header, footer, and items sections to the center of the screen when using `mini.starter`. From the looks of it, the provided content hook aligns them together, which looks bad when used together with a wide header.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think independently aligned header, items, and footer is visually appealing enough to add this functionality directly to 'mini.starter'. It already allows any freedom for users to modify the content of Starter buffer however they want with [custom `content_hooks`](https://github.com/echasnovski/mini.nvim/blob/41487016b71506769c45afac1aee41a180e57fae/doc/mini-starter.txt#L234-L237).

I do admit that customization beyond provided built-in generators is somewhat tricky, but that was a conscious design decision to prioritize ease of setting item content over how they are displayed. So I will not provide an actual code solution for independent aligning.

Closing as not planned.
