### ISSUE TITLE
Suggestion for mini.pairs

### ISSUE THREAD

**Issue by Sarctiann** [echasnovski/mini.nvim#835]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pairs

### Description

I strongly believe this is a much better default behavior for mini-pairs
 
 ```lua
 mappings = {
      -- Prevents the action if the cursor is just before any character or next to a "\".
      ["("] = { action = "open", pair = "()", neigh_pattern = "[^\\]%s" },
      ["["] = { action = "open", pair = "[]", neigh_pattern = "[^\\]%s" },
      ["{"] = { action = "open", pair = "{}", neigh_pattern = "[^\\]%s" },
      -- This is default (prevents the action if the cursor is just next to a "\").
      [")"] = { action = "close", pair = "()", neigh_pattern = "[^\\]." },
      ["]"] = { action = "close", pair = "[]", neigh_pattern = "[^\\]." },
      ["}"] = { action = "close", pair = "{}", neigh_pattern = "[^\\]." },
      -- Prevents the action if the cursor is just before or next to any character.
      ['"'] = { action = "closeopen", pair = '""', neigh_pattern = "%s%s", register = { cr = false } },
      ["'"] = { action = "closeopen", pair = "''", neigh_pattern = "%s%s", register = { cr = false } },
      ["`"] = { action = "closeopen", pair = "``", neigh_pattern = "%s%s", register = { cr = false } },
    },
```

However, it is just a suggestion.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

Although this does look reasonable, this might have had some not obvious issues back when deciding 'mini.pairs' defaults (I *think* I tried this kind of neighborhood patterns and evidently decided against it). Plus I don't changing this many default values is worth it for this type of change.

So let's have it as a reference for alternative useful configurations.

**Comment by Sarctiann** [comment]
## [Here is my config](https://github.com/Sarctiann/lazyvim_config/blob/main/lua/plugins/mini-pairs.lua)
(I will update this setup to get the more intuitive behavior to me)
