### ISSUE TITLE
Trying to add a newline surrounding adds carriage return (^M) instead of line feed

### ISSUE THREAD

**Issue by ElectrifyPro** [echasnovski/mini.nvim#836]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

When trying to add a newline surrounding, i.e. by typing:

```vim
sai(<CR>
```
(where `<CR>` represents actually pressing the enter key)

The result is that carriage return bytes (^M, 0x0d) are added as the surrounding character, instead of line feed (0x0a). See example images below.

I am running Neovim on WSL 2.

### Neovim version

NVIM v0.9.4

### Steps to reproduce

1. `nvim` (open blank file)
2. `30aa<Esc>` (add 30 lowercase As as test content)
3. `sav0<CR>` (add newline surrounding on entire line assuming `mini.surround` is installed, and cursor is at the last `a`)

### Expected behavior

Buffer that looks like:
![image](https://github.com/echasnovski/mini.nvim/assets/1387522/8544dd69-8dc8-481d-b516-cbdc5283b3bc)

### Actual behavior

![image](https://github.com/echasnovski/mini.nvim/assets/1387522/f4fa1b28-ca78-48d7-9a3b-f819b9bec67f)

**Comment by echasnovski** [comment]
Thanks for the issue!

This was already discussed in #321. The resolution was that [it is not (easily) possible under current design](https://github.com/echasnovski/mini.nvim/issues/321#issuecomment-1612540171). The alternatives are:
- Use [`go` and `gO`](https://github.com/echasnovski/mini.nvim/blob/04f8d6e0acd5a52d01ec1c392e3947135dbfd8ef/doc/mini-basics.txt#L234-L235) from 'mini.basics'.
- Use [custom mappings](https://github.com/echasnovski/mini.nvim/issues/321#issuecomment-1539603757).
- Use `['\r'] = { output = { left = '\n', right = '\n' } }` as custom surrounding, but that would not work for indented lines.

Closing as not planned.

**Comment by echasnovski** [comment]
One thing I noticed while revisiting adjacent functionality (in particular, #841 for 'mini.ai'), is that it is possible to do with `<C-j>` key which *indeed* represents new line character instead of `<CR>` / `'\r'` which is a carriage return. But that still won't have good support for indentation.
