### ISSUE TITLE
mini.ai: errors when using \ or CTRL-J or CTRL-M as key of textobject

### ISSUE THREAD

**Issue by thomaswuhoileong** [echasnovski/mini.nvim#841]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Using `\` or `CTRL-J` or `CTRL-M` as the key for a textobject leads to the error due to invalid lua syntax. The reason is that, in the return statement of `H.expr_textobject()`, when `tobj_id` is `'\\'`, it is not escaped when substituted in the expression, and when `tobj_id` is `'\n'` or `'\r'`, the linebreak makes the expression incomplete.

### Neovim version

0.9.5

### Steps to reproduce

1) Open nvim
2) Load `mini.ai` (by `:lua require 'mini.ai'.setup {}<CR>`)
3) Type `va<Bslash>` or `va<C-J>` or `va<CR>`

### Expected behavior

No error due to invalid lua syntax should occur. Either the corresponding textobject is searched for or a message rejecting the usage of such keys is shown.

### Actual behavior

The error message `E5107: Error loading lua [string ":lua"]:1: <message>` is shown (where `<message>` depends on the key and `mini.ai` configuration).

**Comment by thomaswuhoileong** [comment]
There is also the same problem in `H.expr_motion()` which causes the same error when typing `g[<Bslash>` etc.

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I can reproduce. And if `\` is a reasonable case, I am not sure supporting `<C-xxx>` keys is a good idea if it needs some dark magic to be done. I'll take a look.
