### ISSUE TITLE
Statusline flicker with `laststatus=3`

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#842]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

statusline

### Description

When switching between buffers, mini.statusline resets to Neovim's default statusline and then redraws itself, resulting in significant flickering. This can be solved by removing the following autocommand: https://github.com/echasnovski/mini.nvim/blob/f75b954473b11dc98a82475d8d1cf4f84560791b/lua/mini/statusline.lua#L473

### Neovim version

NVIM v0.10.0-dev+3027-gc3061a40f

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Swap with <C-W>w

### Expected behavior

No flickering should happen, redraw should be extremely fast, e.g.:

https://github.com/echasnovski/mini.nvim/assets/91024200/4d5def24-6772-4c86-aca9-71758b92328f

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/91024200/1e91f40a-2f93-4206-b5eb-d4ad432d2252

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce. Even after (what looks like a) more precise identification of a problem: temporarily shown text seems to be from inactive content. It is visible and perceived as flicker because a global statusline (`laststatus = 3`) is used.

My guess is that there is some plugin which not appropriately triggers on which 'mini.statusline' relies. Removing entirely those autocommands in a plugin is certainly not a good idea, as they power the main `laststatus = 2` case.

Could you try only with 'mini.statusline' enabled?

**Comment by echasnovski** [comment]
> If you want to stress-test a heavier component, here's one that integrates with Coc diagnostics and LSP Progress (disclaimer: not optimized):

I see. I did not test this particular case, but I just added `vim.loop.sleep(20)` to one of the components and can see slight flicker with `laststatus = 3`.

The following patch seems to fix the issue:
```patch
diff --git a/lua/mini/statusline.lua b/lua/mini/statusline.lua
index 9fc290c..f196388 100644
--- a/lua/mini/statusline.lua
+++ b/lua/mini/statusline.lua
@@ -511,9 +511,9 @@ end
 H.ensure_content = vim.schedule_wrap(function()
   -- NOTE: Use `schedule_wrap()` to properly work inside autocommands because
   -- they might temporarily change current window
-  local cur_win_id = vim.api.nvim_get_current_win()
+  local cur_win_id, is_global_stl = vim.api.nvim_get_current_win(), vim.o.laststatus == 3
   for _, win_id in ipairs(vim.api.nvim_list_wins()) do
-    vim.wo[win_id].statusline = win_id == cur_win_id and '%{%v:lua.MiniStatusline.active()%}'
+    vim.wo[win_id].statusline = (win_id == cur_win_id or is_global_stl) and '%{%v:lua.MiniStatusline.active()%}'
       or '%{%v:lua.MiniStatusline.inactive()%}'
   end
 end)
```

Would you be comfortable applying it to confirm if it works for you?

**Comment by wroyca** [comment]
> > If you want to stress-test a heavier component, here's one that integrates with Coc diagnostics and LSP Progress (disclaimer: not optimized):
> 
> I see. I did not test this particular case, but I just added `vim.loop.sleep(20)` to one of the components and can see slight flicker with `laststatus = 3`.
> 
> The following patch seems to fix the issue:
> 
> ```diff
> diff --git a/lua/mini/statusline.lua b/lua/mini/statusline.lua
> index 9fc290c..f196388 100644
> --- a/lua/mini/statusline.lua
> +++ b/lua/mini/statusline.lua
> @@ -511,9 +511,9 @@ end
>  H.ensure_content = vim.schedule_wrap(function()
>    -- NOTE: Use `schedule_wrap()` to properly work inside autocommands because
>    -- they might temporarily change current window
> -  local cur_win_id = vim.api.nvim_get_current_win()
> +  local cur_win_id, is_global_stl = vim.api.nvim_get_current_win(), vim.o.laststatus == 3
>    for _, win_id in ipairs(vim.api.nvim_list_wins()) do
> -    vim.wo[win_id].statusline = win_id == cur_win_id and '%{%v:lua.MiniStatusline.active()%}'
> +    vim.wo[win_id].statusline = (win_id == cur_win_id or is_global_stl) and '%{%v:lua.MiniStatusline.active()%}'
>        or '%{%v:lua.MiniStatusline.inactive()%}'
>    end
>  end)
> ```
> 
> Would you be comfortable applying it to confirm if it works for you?

Yes, give me a moment :+1:

**Comment by echasnovski** [comment]
> LGTM, I don't see flickering anymore 🥳

Great! I have the fix which I intend to re-review tomorrow and merge if everything is OK.

**Comment by echasnovski** [comment]
This should now be the part of `main`. Thanks for the early testing!
