### ISSUE TITLE
mini-files: press "@" again to set focus on cwd

### ISSUE THREAD

**Issue by idelice** [echasnovski/mini.nvim#844]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini-files

### Description

You can do "@" to reveal cwd, and that is nice, but what if I also want to focus on cwd? 

That's where I suggest using the same keymap "@" to focus cwd.

Example:
@ -> reveal cwd
@@ -> reveal + focus cwd

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I strangely both like it (it looks as interesting usability feature) and don't really like it (might look "too magical" and would require extra complexity in `reveal_cwd()` function which would not 100% justify its name). I'll think about it.

**Comment by echasnovski** [comment]
OK, so...

I've gone back and forth on whether it should be added at least two times already. This is *usually* a sign that I think adding a feature is not a good idea.

My reasoning for both is basically the same as described in previous comment.

Together with possible #928, unfortunately I don't think this feature will be added to 'mini.files'.

Closing as not planned.
