### ISSUE TITLE
mini.files: support paths which do not exist on disk

### ISSUE THREAD

**Issue by baod-rate** [echasnovski/mini.nvim#848]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

`MiniFiles.open` currently errors out when passed a path to a non-existent file:

https://github.com/echasnovski/mini.nvim/blob/5eb6ae150d472dd35d5ecfd933fbef2a187c71dc/lua/mini/files.lua#L669-L674

But it's very likely that a user might want to navigate a directory that doesn't exist yet. e.g.:

```
$ ls -d foo
foo/
$ ls -a foo
./  ../  bar
$ nvim foo/baz
...
```

Opening mini.files here should show `foo/`. For reference, this usage pattern is supported by [vinegar](https://github.com/tpope/vim-vinegar/).

I suggest that mini.files should allow, as a special case, a `path` pointing to a non-existent file in a directory that does exist. Something along the lines of:

```diff
  local fs_type = H.fs_get_type(path)
+  if fs_type == nil then
+    path = H.fs_get_parent(path)
+    fs_type = H.fs_get_type(path)
+    if fs_type ~= "directory" then H.error('`path` is not a valid directory ("' .. path .. '")') end
+  end
-  if fs_type == nil then H.error('`path` is not a valid path ("' .. path .. '")') end
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already discussed in #840 with resolution outlined in [this comment](https://github.com/echasnovski/mini.nvim/issues/840#issuecomment-2077068359).

Closing as not planned.
