### ISSUE TITLE
mini.cursorword: Ignore short word (single char or 2 chars)

### ISSUE THREAD

**Issue by haunt98** [echasnovski/mini.nvim#850]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cursorword

### Description

Is there a way to disable mini.cursorword when I click to short word (single char).
For example: `a-b-c`, when I move to `a` I don't want to hightlight all word `a`.

**Comment by echasnovski** [comment]
Unfortunately, no.

The whole idea of 'mini.cursorword' is to [highlight whole word under cursor](https://github.com/echasnovski/mini.nvim/blob/5eb6ae150d472dd35d5ecfd933fbef2a187c71dc/doc/mini-cursorword.txt#L9). In the same way as would built-in `*`, `#`, etc. work.

So although I do understand the appeal of not highlighting short words, this is both not easy to do with current implementation (which uses built-in matches and Vim patterns) and not aligned with built-in behavior.

> For example: `a-b-c`, when I move to `a` I don't want to hightlight all word `a`.

For this particular example I can suggest to add "-" character to a list of characters that are recognized as a part of what Neovim considers to be a "keyword". This can be done by modifying 'iskeyword' option like so: `vim.opt.iskeyword:append('-')`.

------

Closing as not planned.
