### ISSUE TITLE
limit number of items in mini.completion window/popup

### ISSUE THREAD

**Issue by gallo-s-chingon** [echasnovski/mini.nvim#861]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

I'm a prose writer, so thank you far all that you do to simplify / streamline plugins I need/use.

could you add a parameter/setting to limit the number of items in that appear in the popup window? if it's already in place where can I find the documentation to set the variable?

**Comment by echasnovski** [comment]
Thanks for kind words!

The 'mini.completion' module [uses built-in tools as much as possible](https://github.com/echasnovski/mini.nvim/blob/061379f082d6b03305b00ddd6f8f6b7b8eded6d8/doc/mini-completion.txt#L13-L14). This includes the popup menu with completion candidates (see `:h ins-completion-menu`). Its maximum height can be controlled by 'pumheight' option. You can adjust it by putting something like `vim.o.pumheight = 10` in your Lua config. An alternative is to use 'mini.basics' and its [`options.extra_ui` setting](https://github.com/echasnovski/mini.nvim/blob/061379f082d6b03305b00ddd6f8f6b7b8eded6d8/doc/mini-basics.txt#L172) with something like this: `require('mini.basics').setup({ options = { extra_ui = true } })`.
