### ISSUE TITLE
Unexpected behaviour when using mini.ai in html

### ISSUE THREAD

**Issue by francoganga** [echasnovski/mini.nvim#865]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

When using mini.ai on a html file the usual ways of interacting with html tags behave incorrectly. I noticed this with all actions that involve tags for ex: "vat", "dat", "cit", etc.

### Neovim version

NVIM v0.9.5

### Steps to reproduce

With mini.ai installed open any html file and try to select around any tag, the behaviour is very inconsistent also.
It seems to occur more  on tags that have multiple parents.

### Expected behavior

Should not alter the default behaviour of vanilla nvim

### Actual behavior

https://github.com/echasnovski/mini.nvim/assets/44908537/f9fd113b-8862-4d83-a815-9307641f04ae

This is me creating an index.html file adding a couple of tags and trying to select around a tag.

**Comment by echasnovski** [comment]
'mini.ai' works using [Lua patterns](https://github.com/echasnovski/mini.nvim/blob/5df3155218807fb6049779bb488f48f77fdd9dcb/doc/mini-ai.txt#L44-L45) which are not designed to deliver 100% compatibility with parsing structured nested data.

If there is a concrete example of something not working as expected, please provide a step-by-step reproducible example. The attached video is not reproducible for me. Also, chances are that this was already [discussed in one of the previous issues](https://github.com/echasnovski/mini.nvim/issues?q=label%3Amini.ai+tag).

If you want to disable particular built-in textobject, you can disable it by setting to `false` entry in `custom_textobjects`. [Like this](https://github.com/echasnovski/mini.nvim/blob/5df3155218807fb6049779bb488f48f77fdd9dcb/doc/mini-ai.txt#L450-L451).

Closing as there is not enough information.
