### ISSUE TITLE
tabline labels customization

### ISSUE THREAD

**Issue by arcxio** [echasnovski/mini.nvim#868]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.tabline

### Description

HI! Thought it'd be more convenient to show buffer IDs in tabline's tabs, so that I could access them directly with :b. Unfortunately, as I saw from the code tabline doesn't allow that kind of scripting right now. I realize that kind of preference may be odd, so instead of suggesting that as a feature, I think tabline would benefit more from some kind of general label customization. Something like a function argument in setup that edits tab's label and is called from H.finalize_labels. It would also allow to show custom icons, e.g. for users who don't want to install devicons.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

For a long time I was opposed on any kind of customization to 'mini.tabline', but today I think that exporting single `format` function might make sense. Together with the `default_format()` that implements current formatting this will make 'mini.tabline' more aligned with the more recent modules design (like 'mini.files', 'mini.pick', etc.).

This will also allow to solution for implement #824.

I'll take a look.

**Comment by arcxio** [comment]
@echasnovski Can I help out by submitting a PR?

**Comment by echasnovski** [comment]
> @echasnovski Can I help out by submitting a PR?

If you want to, you surely can. But beware, that it will need to have proper testing and somewhat tedious documentation update. Nothing too complicated, but a lot of moving pieces involved.

Otherwise I hope to resolve this by the end of the week.

**Comment by echasnovski** [comment]
This now should be fixed on latest `main` (as promised, by the end of the week :) ).

There is now indeed a `config.format` for formatting labels along with`default_format()` which formats the same as was done before. Thanks for again for the issue and your effort in #888.!
