### ISSUE TITLE
Idea for mini.cloak

### ISSUE THREAD

**Issue by domsch1988** [echasnovski/mini.nvim#878]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.cloak

### Description

I'm using nvim at work also to screenshare. We often work on repositories that contain some form of secrects. They are fine in there, but we are concious about showing them on a Video Call. Especially when calling with customers.
For this purpose, i've been using cloak.nvim but thought that this is the kind of "small" problemsolver that would fit mini pretty well.

The basic idea is to define certain keywords that precede a "secret" of some form, and then hide everything after that behind a cloaking character.
Ideally yanking still gets the original content, and the cloaking is toggleable.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is already more or less possible with 'mini.hipatterns' by creating pattern for characters to cover and showing virtual text on top of them. There is even a [similar example in its help](https://github.com/echasnovski/mini.nvim/blob/c333187fcc76d7e772dac32c2a440a949fe34be4/doc/mini-hipatterns.txt#L158-L176).

Toggling should also possible in separate function, albeit not as straightforward: modify directly `MiniHipatterns.config.highlighters` to toggle certain highlighter (assign to table/`nil` to enable/disable) and follow by `vim.cmd('edit')` to "restart" all highlighters.

Closing as not planned.
