### ISSUE TITLE
"i" key has been remapped, "k" remap to "i", inside = "k"

### ISSUE THREAD

**Issue by b1nhack** [echasnovski/mini.nvim#880]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.ai

### Description

Since I'm a colemak user, I remaped i to l:
```lua
vim.keymap.set({ "n", "x" }, "i", "l")
```

To use [v_iw](https://neovim.io/doc/user/motion.html#v_iw), I added the following mapping:
```lua
vim.keymap.set({ "n", "x", "o" }, "k", "i")
```

To use mini.ai, I modified the default keymap: 
```lua
				-- Main textobject prefixes
				around = "a",
				inside = "k",

				-- Next/last variants
				around_next = "an",
				inside_next = "kn",
				around_last = "ai",
				inside_last = "ki",

				-- Move cursor to corresponding edge of `a` textobject
				goto_left = "g[",
				goto_right = "g]",

```
But now I can't execute [v_iw](https://neovim.io/doc/user/motion.html#v_iw) in x-mode (using key: kw)

### Neovim version

neovim HEAD-3a82652

### Steps to reproduce

1. remap i to l
2. remap k to i
3. set mini.ai inside = "k"

### Actual behavior

[v_iw](https://neovim.io/doc/user/motion.html#v_iw) can't work

**Comment by echasnovski** [comment]
Thanks for issue!

Similar issue was discussed in #195 with suggested solution to use 'langmap' option to make proper remappings (instead of `vim.keymap.set()`).
