### ISSUE TITLE
Configure Mini Animate to not Halt Cursor Movement if Animation is not Done

### ISSUE THREAD

**Issue by xeon826** [echasnovski/mini.nvim#881]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

If I press a movement key before the animation finishes, it's ignored. I could turn down the animation time but is there a way to configure it so that the following movement is not ignored if it happens during the previous movements animation?

For example you could try (from the top of a large file) gg
G
$
In quick succession, $ will be ignored.

**Comment by echasnovski** [comment]
If I understood correctly the question, it is more about scroll animation. If that is so, then the answer is "I don't think so".

The scroll animation is [implemented with side effects](https://github.com/echasnovski/mini.nvim/blob/c333187fcc76d7e772dac32c2a440a949fe34be4/doc/mini-animate.txt#L38-L43) meaning that window view is actually changing to achieve the visual effect. As the animation is in place, it only reacts to other scrolling keys.

This also seems like a problem similar (or exactly like) the one in #715.

So all in all, I don't think it is going to get supported.
