### ISSUE TITLE
mini.completion defautl keymaps result with extra $0 at the end

### ISSUE THREAD

**Issue by alekspickle** [echasnovski/mini.nvim#882]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

completion

### Description

![Screenshot_20240516_112829](https://github.com/echasnovski/mini.nvim/assets/22867443/ab9a9bcb-ecad-4826-86e7-030c4a56e0d5)

not sure what this can be related to

### Neovim version

0.9.1

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Expected behavior

no extra $0 at the end

### Actual behavior

extra $0 at the end

**Comment by echasnovski** [comment]
This looks like an issue on LSP server side. 'mini.completion' takes completion suggestion almost verbatim and this `$0` looks like a formatting for snippet (yet an item is advertised as "Method").
