### ISSUE TITLE
Make the active column (where the cursor is) more easy to track

### ISSUE THREAD

**Issue by ammon134** [echasnovski/mini.nvim#883]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I love to have the preview column to see the content of a file before committing to get inside of it.

The issue is, I find the fact that the cursor is on the **next to last** column, and not the last column itself, pretty unintuitive, and find myself looking at the wrong column all the time when navigating. 

I could make the width of the preview column smaller, but it doesn't help much visually, while reducing the effectiveness of the preview column. 

To me personally the best solution would be pretty simple: somehow highlight the focus column, not only with width change, but perhaps also with border color change. For example it would be lovely if the border color of the focus column is tokyonight's orange 
<img width="1353" alt="SCR-20240516-tpit" src="https://github.com/echasnovski/mini.nvim/assets/113684938/c10189d5-add8-4e1e-8524-c0b8fbf7ed20">

Another idea would be to give "inactive columns" a backdrop effect where the syntax highlight colors are disabled (similar to how [flash](https://github.com/folke/flash.nvim) does it). "Inactive columns" here refer to all the columns that are not focus column or preview column. 
<img width="1358" alt="SCR-20240516-tqnw" src="https://github.com/echasnovski/mini.nvim/assets/113684938/94ad7e08-d209-48e1-a70d-f952f06d68c4">

It would make my life so much easier if one of these could be implemented or configurable somehow. 

Thank you so much for an awesome plugin!

**Comment by echasnovski** [comment]
Thanks for the suggestion!

There are at least two ways to make focused window more visible:

- Customize [`MiniFilesTitleFocused`](https://github.com/echasnovski/mini.nvim/blob/c333187fcc76d7e772dac32c2a440a949fe34be4/doc/mini-files.txt#L95) highlight group to be more visible.
- Make [width of focused window](https://github.com/echasnovski/mini.nvim/blob/c333187fcc76d7e772dac32c2a440a949fe34be4/doc/mini-files.txt#L541-L542) more noticeable.

I think these options (together with already mentioned tweaking of preview window width) should be enough to resolve this.

Closing as not planned.
