### ISSUE TITLE
Error when executing <C-w><C-d>

### ISSUE THREAD

**Issue by jwtouron** [echasnovski/mini.nvim#887]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

After updating to version 0.10, and executing the new functionality for viewing diagnostics (\<C-w\>d), I get the following error:

```
E5108: Error executing lua: .../.local/share/nvim/lazy/mini.clue/lua/mini/clue.lua:1552: Invalid 'window': Expected Lua number
stack traceback:
	[C]: in function 'nvim_win_call'
	.../.local/share/nvim/lazy/mini.clue/lua/mini/clue.lua:1552: in function 'window_scroll'
	.../.local/share/nvim/lazy/mini.clue/lua/mini/clue.lua:1321: in function 'state_advance'
	.../.local/share/nvim/lazy/mini.clue/lua/mini/clue.lua:1277: in function <.../.local/share/nvim/lazy/mini.clue/lua/mini/clue.lua:1260>
```

### Neovim version

0.10

### Steps to reproduce

1. Update to version 0.10
2. Install mini.clue
3. Place cursor over LSP diagnostic location
4. Hit \<C-w\>d

### Expected behavior

Show diagnostic popup.

### Actual behavior

Above error message.

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce: neither with my own full config nor with minimal one containing only 'mini.clue' and 'nvim-lspconfig'.

Would you mind posting a more detailed reproduction setup? With minimal config with which you can reproduce this.

**Comment by jwtouron** [comment]
Thank you for looking into this. As a minimal example, I was able to reproduce the bug with this being the only file in my nvim directory:

```
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "echasnovski/mini.clue",
  version = '*',
  config = function()
    local miniclue = require('mini.clue')
    require('mini.clue').setup {
      triggers = {
        { mode = 'n', keys = '<C-w>' },
      },
      clues = {
        miniclue.gen_clues.windows(),
      },
    }
  end
})
```

Also, it appears I misspoke earlier. I didn't get an error when hitting \<C-w\>d, but I did get the error when hitting \<C-w\>\<C-d\>.

**Comment by echasnovski** [comment]
> Also, it appears I misspoke earlier. I didn't get an error when hitting <C-w>d, but I did get the error when hitting <C-w><C-d>.

Ah, that is more like it. Yes, I can reproduce now.

The reason seems to be because `<C-d>` is a default mapping to scroll inside clue window. I'll take a look.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.

Important note: scroll keys (`<C-d>` and `<C-u>` by default) are still treated as special keys (same as `<CR>`, `<BS>`, and `<C-c>`) but only when clue window is visible. So even if they can advance key state, they will work like this:
- If window is visible - scroll it.
- If window is not yet visible - advance state.

So to use `<C-w><C-d>` (which is built-in on Neovim>=0.10), press `<C-d>` before clue window is shown. Or configure other scrolling keys.

**Comment by jwtouron** [comment]
Thank you for taking care of this!
