### ISSUE TITLE
Beta-testing 'mini.git'

### ISSUE THREAD

**Issue by echasnovski** [echasnovski/mini.nvim#898]
Please leave your feedback about new [mini.git](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-git.md) module here. Feel free to either add new comment or positively upvote existing one.

Some things I am interested to find out (obviously, besides bugs):

- Does it track smoothly the git-related data (i.e. at least no visible errors reported).
- Does `:Git` command have proper completions and intuitive split behavior?
- Is configuration intuitive enough?
- Are default values of settings convenient for you?
- Is documentation and examples clear enough?

Thanks!

**Comment by clason** [comment]
Can we support `:Git -m "foo bar"`?

**Comment by echasnovski** [comment]
> Can we support `:Git -m "foo bar"`?

What is it supposed to do? As `:Git commit -m "foo bar"`? If yes, then I don't think it is worthwhile to add this special behavior.

**Comment by clason** [comment]
Yes, sorry. It should behave exactly like `git commit -m "foo bar"`. (After all, "if it works with `git`, it should work with `:Git`"...)

**Comment by clason** [comment]
Yes. I am explicitly referring to that; I would prefer _not_ to need a special syntax.

**Comment by echasnovski** [comment]
> Yes. I am explicitly referring to that; I would prefer _not_ to need a special syntax.

Ah, I see now. No, I don't think it will be added, as the current approach feels more like how Vim user commands work.

**Comment by clason** [comment]
Ok. Then I'll just leave two more suggestions here for the record; no need to respond:
* I would suggest making the fugitive behavior (split + `scrollbind`) the default for `Git blame`
* Consider mapping `show_at_cursor` for `mini.git` buffers, e.g., to `K`.

**Comment by echasnovski** [comment]
> Ok. Then I'll just leave two more suggestions here for the record; no need to respond:

Thanks!

In case other people miss it in help file.

>     * I would suggest making the fugitive behavior (split + `scrollbind`) the default for `Git blame`

There is [an example](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L97-L111) of customizing `blame` subcommand (preferably be used inside mapping with `<Cmd>vert Git blame -- %<CR>` right hand side).

>     * Consider mapping `show_at_cursor` for `mini.git` buffers, e.g., to `K`.

I'd suggest mapping it some `<Leader>` mapping as it can be used inside regular Git-tracked file to show range history. But making buffer-local mapping is also possible (albeit a bit verbose for the most robust behavior):

```lua
local map_local = vim.schedule_wrap(function(data)
  if not vim.api.nvim_buf_is_valid(data.buf) then return end
  local buf_name = vim.api.nvim_buf_get_name(data.buf)
  if not vim.startswith(buf_name, 'minigit://') then return end
  vim.keymap.set({ 'n', 'x' }, 'K', MiniGit.show_at_cursor, { buffer = data.buf })
end)
-- Alternative is to map for `User` `MiniGitCommandSplit` event, but
-- it would not trigger when buffer is created with `show_xxx()` functions
vim.api.nvim_create_autocmd('BufNew', { callback = map_local })
```

**Comment by echasnovski** [comment]
The 'mini.git' module is not meant as a full Git client, so do not expect full feature parity with 'vim-fugitive'. Here is a [comparison to 'vim-fugitive'](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L45-L54).

> Is there a way where i can navigate through diff changes in all the files(not just current buffer) like I can using :Git command in vim-fugitive.

Not like in 'vim-fugitive', but you can use plain `:Git diff` with [enabled folding](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L345-L348). Ideally, you'd be able to navigate to diff source with `show_at_cursor()`, but `show_diff_source()` (and hence `show_at_cursor()`) does not work in that output (needs explicit commit). I'll look at how it can resolved.

> Also stage and unstage hunks like I can in vim-fugitive.

The suggested way is to use 'mini.diff' for staging hunks when inside a buffer. Interactive unstaging is not supported, only with what `git` CLI through `:Git` can offer.

**Comment by rafamadriz** [comment]
@echasnovski Thanks for your amazing work. This fits really nice within my workflow since I don't need the full feature set of fugitive (for that I use lazygit).

I just have one question so asking here to not create an issue, what's the purpose of setting foldlevel ?

https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/lua/mini/git.lua#L1120

I have a modified commit message that shows for commits, and I use folds for some parts which I'd rather start closed, for that I have `vim.opt.foldlevel = 0` in `after/ftplugin/gitcommit.lua`. It works fine when doing it from the command line `git commit` but if I do it inside neovim (`:Git commit`) then foldlevel is set to 999. So really my question is, is there anyway that options in `after/ftplugin/gitcommit.lua` are not overwritten ?

**Comment by echasnovski** [comment]
> I just have one question so asking here to not create an issue, what's the purpose of setting foldlevel ?

I am using `foldmethod=indent` (and recommending it to everyone). So output of `:Git` command in split tended to be folded when I did not expect it to (like after `:Git help commit`). As that foldlevel is set *before* manually setting filetype in output of `:Git` command, it works in most cases. It just doesn't work in `GIT_EDITOR` (like for commit). I'll fix this (probably tomorrow), as setting `vim.wo.foldlevel = 0` in 'after/ftplugin/gitcommit.lua' should work.

**Comment by tssm** [comment]
Hey @echasnovski, this is great! It covers most of what I wanted from Fugitive without its complexity, and for the rest I can create my own mappings :)

Regarding the split behavior, I miss an option to use the current window, without touching the tab layout at all, and without creating a new tab

**Comment by echasnovski** [comment]
> Hey @echasnovski, this is great! It covers most of what I wanted from Fugitive without its complexity, and for the rest I can create my own mappings :)

That's great to hear!

> Regarding the split behavior, I miss an option to use the current window, without touching the tab layout at all, and without creating a new tab

Yeah, I've thought about this one. In early prototypes it even preferred reusing window if it already showed a buffer from 'mini.git'.

There are two main reasons (aside from a convenient for implementation "there is always a new window" invariant) for not including something like `split = 'none'`:
- The buffers from 'mini.git' are cleaned up after window is closed. If not done, they will be accumulating in buffer list, which is not nice. The usual approach of setting `buftype=wipeout` so that buffer is wiped out when it is not visible is not great here, because it prevents exploring other buffers in the same window.
- There is no good user command modifier to force it. Unlike "horizontal", "vertical", and "tab". So having only one not enforceable split direction ("auto") felt more appropriate.

I'll have this mind, but not sure if this is a good idea. I *do* wonder about supporting `split = 'float'` for floating windows, but that would require exposing a `config.window.config` option, which is also not great. Maybe some time later.

**Comment by tssm** [comment]
> The usual approach of setting buftype=wipeout so that buffer is wiped out when it is not visible is not great here, because it prevents exploring other buffers in the same window.

What do you mean here? I ask because for all Git related buffers I do set `bufhidden` to `wipe`, and I wonder what workflow I'm breaking here.

Anyway, it shouldn't be hard for me to make it work as I want it. I think for now I'll set `split` to `vertical` and leverage the `MiniGitCommandSplit` event to close the previous window, and who knows, maybe after a while I want the `auto` behaviour back

**Comment by echasnovski** [comment]
> What do you mean here? I ask because for all Git related buffers I do set `bufhidden` to `wipe`, and I wonder what workflow I'm breaking here.

If you run something like `:Git log` and then want to take a quick look of previous buffer to double check something (with `[b`, for example), the 'git' buffer is wiped out now (and you have to redo `:Git log`).

**Comment by tssm** [comment]
Right, that's the behavior I expect, as I think all those buffers are temporary anyway. It's a bit annoying when `Git log` is closed by mistake, granted, but I feel the issue there is that it takes a while to generate. I wonder if it could be sped up somehow. For now, I'm used to always run `Git log main..`

Unrelated, I just noticed not all buffers have a `setlocal nomodifiable` set. Is this intended? I'm unconditionally setting it now on my `MiniGitCommandSplit` autocommand

**Comment by echasnovski** [comment]
> Unrelated, I just noticed not all buffers have a `setlocal nomodifiable` set. Is this intended? I'm unconditionally setting it now on my `MiniGitCommandSplit` autocommand

Not **intentional** intentional, but I don't really see a problem with them being modifiable. Maybe users want to modify before copying or something.

**Comment by pkazmier** [comment]
Congratulations on the new module! I quickly set it this morning before I headed to the office. Two quick questions / comments:

1. Took me longer than it should have after reading the docs to figure out that I did not have to explicitly call `enable()`. Maybe I missed it, but no where did I find it say this is enabled by default. I think the part that confused me is the first bullet item of features refers one to the `enable` function, which I took to imply I needed to explicitly enable this somehow.
2. Not really a mini.git question, but is there a way to lock two windows together so they are synchronized when moving up/down? Use case would be for the blame windows opens vertically.


Thanks again! Love the ability to use `show_at_cursor` to interactively explore. So simple and clever.

**Comment by echasnovski** [comment]
> 1. Took me longer than it should have after reading the docs to figure out that I did not have to explicitly call `enable()`. Maybe I missed it, but no where did I find it say this is enabled by default. I think the part that confused me is the first bullet item of features refers one to the `enable` function, which I took to imply I needed to explicitly enable this somehow.

Hmm... Yeah, I see how this might be confusing. This is documented in [setup()](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L214) (as it is the one that actually sets up autoenabling).

Would adding [here](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L369) a line "Note: this function is called automatically for all new normal buffers. Use it explicitly if buffer was disabled." have helped?
 
> 2. Not really a mini.git question, but is there a way to lock two windows together so they are synchronized when moving up/down? Use case would be for the blame windows opens vertically.

Yes, it can be done with 'scrollbind' option. Here is [the example of how to customize `:Git blame`](https://github.com/echasnovski/mini.nvim/blob/e94945129780fa5b43447ecc0a4b0273892043e3/doc/mini-git.txt#L97-L111) to do just that.
 
> Thanks again! Love the ability to use `show_at_cursor` to interactively explore. So simple and clever.

Thanks! It indeed felt quite intuitive for me once I had started using it.

**Comment by rchhong** [comment]
I'm using lazy package manager and I get the following error installing this plugin using the recommended install method.  I'm guessing that it might have something to do with the naming, as this plugin is the only one that uses a hypen instead of a dot.

```
Failed to run `config` for mini-git

...local/share/nvim/lazy/lazy.nvim/lua/lazy/core/loader.lua:373: module 'mini' not found:
^Ino field package.preload['mini']
cache_loader: module mini not found
cache_loader_lib: module mini not found
^Ino file './mini.lua'
^Ino file '/opt/homebrew/share/luajit-2.1/mini.lua'
^Ino file '/usr/local/share/lua/5.1/mini.lua'
^Ino file '/usr/local/share/lua/5.1/mini/init.lua'
^Ino file '/opt/homebrew/share/lua/5.1/mini.lua'
^Ino file '/opt/homebrew/share/lua/5.1/mini/init.lua'
^Ino file '/Users/ryanchhong/.luarocks/share/lua/5.1/mini/init.lua'
^Ino file '/Users/ryanchhong/.luarocks/share/lua/5.1/mini.lua'
^Ino file './mini.so'
^Ino file '/usr/local/lib/lua/5.1/mini.so'
^Ino file '/opt/homebrew/lib/lua/5.1/mini.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - vim/_editor.lua:0 _in_ **cmd**
  - /persistence.nvim/lua/persistence/init.lua:87 _in_ **load**
  - ~/.config/nvim/lua/plugins/ui/dashboard.lua:32 _in_ **action**
  - /dashboard-nvim/lua/dashboard/theme/doom.lua:29
```

**Comment by rchhong** [comment]
Ah I wasn't aware of that "main" option in lazy.  I had everything else except that.  I added that in and it works, but might want to add that to the mini.git installation instructions.

**Comment by ElectronSutra** [comment]
The new module looks great.

Is it in-scope for either `mini.git` or `mini.files` or `mini.extra` to add (a `mini.files` prefix?) (another method?) to show the Git status of the files?

**Comment by tssm** [comment]
How should I interpret `win_source` provided by `MiniGitCommandSplit`? I expected it to be the window number, but on a fresh instance, with just one window, after a command splits it, the value is always `1000` instead of `1`

**Comment by echasnovski** [comment]
> Is it in-scope for either `mini.git` or `mini.files` or `mini.extra` to add (a `mini.files` prefix?) (another method?) to show the Git status of the files?

@ElectronSutra, probably yes. As part of 'mini.extra'.



> How should I interpret `win_source` provided by `MiniGitCommandSplit`? I expected it to be the window number, but on a fresh instance, with just one window, after a command splits it, the value is always `1000` instead of `1`

It is a window identifier, as documented. See `:h window-ID`.

**Comment by echasnovski** [comment]
I've pushed several updates.

------

@rafamadriz, using `setlocal foldlevel=0` in 'after/ftplugin/gitcommit.lua' should now work.

------

@pkazmier, I added note about autoenabling in `enable()` help. Hope it will be clearer for future users.

------

@rchhong, installation instructions for 'lazy.nvim' now have `main` field.

**Comment by konosubakonoakua** [comment]
error with `nvim-ufo` after executing `:Git log --oneline`
```lua
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
...local/share/nvim/lazy/nvim-ufo/lua/ufo/provider/init.lua:36: attempt to call upvalue 'mainFunc' (a nil value)

```

**Comment by konosubakonoakua** [comment]
> > error with `nvim-ufo` after executing `:Git log --oneline`
> > ```lua
> > Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
> > ...local/share/nvim/lazy/nvim-ufo/lua/ufo/provider/init.lua:36: attempt to call upvalue 'mainFunc' (a nil value)
> > ```
> 
> I can not reproduce after installing and enabling 'kevinhwang91/nvim-ufo' with the following code:
> 
> ```lua
> add('kevinhwang91/promise-async')
> add('kevinhwang91/nvim-ufo')
> vim.o.foldcolumn = '1'
> vim.o.foldlevel = 99
> vim.o.foldlevelstart = 99
> vim.o.foldenable = true
> require('ufo').setup()
> ```

My mistake, I set `ftMap = {git={}}`, it's empty. After set `git = {"indent"}`, problem solved. Thankyou.

**Comment by tssm** [comment]
Thanks for all your help @echasnovski! As I've been using it these days as my main Git client, I found a couple of features missing that hopefully are still in scope:
1. `Git reflog` (as `Git log`)
2. `Git stash list` (same. This is not supported by Fugitive, but I think it should)

I also miss being able to use commands with the `--patch` option

**Comment by echasnovski** [comment]
> Thanks for all your help @echasnovski! As I've been using it these days as my main Git client, I found a couple of features missing that hopefully are still in scope:
> 1. `Git reflog` (as `Git log`)
> 2. `Git stash list` (same. This is not supported by Fugitive, but I think it should)

Could you elaborate on what what do you mean by "same as `Git log`"? My guess would be that you expect it to be shown in a split with highlighting.

Which subcommands show its output in a split is deligated to Git itself. It can provide a list of such subcommanda, which is used here.

To force *any* command's output to be shown in a split, explicitly use splitting command modifier: `horizontal`, `vertical`, or `tab` (each possibly abbreviated). If you want to automate things, there is a `MiniGitCommandDone` `User` event.

> I also miss being able to use commands with the `--patch` option

I am not sure about what exactly is missing.

**Comment by tssm** [comment]
> My guess would be that you expect it to be shown in a split with highlighting.

Yeah, that's what I meant, however using `:vertical` is god for now.

> Which subcommands show its output in a split is deligated to Git itself. It can provide a list of such subcommanda, which is used here.

Interesting! How can I see that list?

Regarding the `--patch` option, if I run `Git stage -p` the interactive output is echoed, so I cannot interact with it. As a workaround I'm using `:te git stage -p`, but sometimes I forget

**Comment by echasnovski** [comment]
> Interesting! How can I see that list?

`git --list-cmds=list-info,list-ancillaryinterrogators,list-plumbinginterrogators`

This provides the most complete list I could find.

> Regarding the `--patch` option, if I run `Git stage -p` the interactive output is echoed, so I cannot interact with it. As a workaround I'm using `:te git stage -p`, but sometimes I forget

Interesting. I'll take a look, but no promises.

**Comment by aikow** [comment]
Hey @echasnovski! First off, thanks for your awesome plugins.

I've noticed that getting option completions doesn't work when `MANPAGER` is set in the environment. In other words, `mini-git` reports a subprocess time-out error, and neovim is not responsive while it tries to generate completions. I currently have `MANPAGER='nvim +Man!'.

 It should be possible to remove that environment variable, or set it to whatever the expected value is, from a copy of the env, and pass that to the `vim.loop.spawn` command in `H.cli_run`. Removing it completely, by setting `vim.env.MANPAGER = nil`, or starting nvim with `MANPAGER= nvim`, does fix the timeout issue, but doesn't show any actual completions. I got the same result using `MANPAGER=cat`

**Comment by aikow** [comment]
I also just noticed that completion for nested subcommands, like `git remote get-url` also don't work. I.e. when typing `git remo`, I get suggestions for all `git remote` subcommands, like

```text
remote
remote rm
remote add
remote show
...
```

But as I soon as I type the space, I no longer get any suggested completions, nor do I get any completions for possible remotes, although that probably has to do with the completion failing for the nested subcommand.

**Comment by echasnovski** [comment]
> I've noticed that getting option completions doesn't work when `MANPAGER` is set in the environment. In other words, `mini-git` reports a subprocess time-out error, and neovim is not responsive while it tries to generate completions. I currently have `MANPAGER='nvim +Man!'`.

I don't use Neovim for man pages, so currently trying to reproduce this and can not. Even with `echo $MANPAGER` showing `nvim +Man!` I still can not get `man git` to show inside Neovim while completion works as expected (without hanging).

I believe the reason is due to [using `git help --man <command>`](https://github.com/echasnovski/mini.nvim/blob/b0b435873375c4341f2ecbcb95e9e645abe0d679/lua/mini/git.lua#L952) to manually parse manual pages for possible options. I am currently looking at what config value should I set for that particular command (so like adding `'c', '...'` arguments) to make it return help page in a basic `stdout`.

> But as I soon as I type the space, I no longer get any suggested completions, nor do I get any completions for possible remotes, although that probably has to do with the completion failing for the nested subcommand.

This is expected and (somewhat) [documented](https://github.com/echasnovski/mini.nvim/blob/b0b435873375c4341f2ecbcb95e9e645abe0d679/doc/mini-git.txt#L172-L179).

The reason is that in the case of completion for `:Git remote |` (i.e. after a space) there is no reliable way to tell if the user wants second word as completion candidates or command's targets. Thus for all commands it suggests target while still suggesting second word if cursor is as right as at the end of the command (i.e. `:Git remote| `).

The reason it doesn't provide completion candidates is because `remote` is not included in a list of "some common subcommands" that provide target completion. You can see all such commands [here](https://github.com/echasnovski/mini.nvim/blob/b0b435873375c4341f2ecbcb95e9e645abe0d679/lua/mini/git.lua#L1055-L1093) as non-commented table keys. I can probably add `remote` there too. Are there any other commands that you feel like using frequently but not on that list?

**Comment by echasnovski** [comment]
@aikow, as I still can not reproduce the pager issue, would you mind checking if the following fixes it for you?

Find your 'mini.nvim' / 'mini.git' installation and replace this [this line](https://github.com/echasnovski/mini.nvim/blob/b0b435873375c4341f2ecbcb95e9e645abe0d679/lua/mini/git.lua#L1166) with this one:

```lua
  local command = { MiniGit.config.job.git_executable, '--no-pager', unpack(args) }
```

**Comment by aikow** [comment]
I think the `--no-pager` is related to things like `git diff` or `git show`, but it looks like `git help` uses `MANPAGER` and does not respect git's actual pager setting, which is probably a good thing, since I have `git delta` configured as my git pager, and I don't think it is any good at showing man pages 😂.

**Comment by echasnovski** [comment]
Sigh... OK, lets then try a more nuclear approach. Could test on Mac (where there was an issue) if replacing [these two lines](https://github.com/echasnovski/mini.nvim/blob/b0b435873375c4341f2ecbcb95e9e645abe0d679/lua/mini/git.lua#L1166-L1167) with the following fixes the issue:

```lua
  local command = { MiniGit.config.job.git_executable, '--no-pager', unpack(args) }
  local custom_env = { NO_COLOR = 1, PAGER = 'cat', MANPAGER = 'cat' }
  local environ = vim.tbl_deep_extend('force', vim.loop.os_environ(), custom_env)
  local env = {}
  for k, v in pairs(environ) do
    table.insert(env, string.format('%s=%s', k, tostring(v)))
  end
  local res = H.cli_run(command, cwd, nil, { env = env }).out
```

**Comment by aikow** [comment]
That didn't work either. I also tried using `less -r`, `less -R`, and `gcat` as pages, none of which worked, I'm still getting output's with weird escapes. I also tried passing some git config flags directly, like `color.ui=false`, or `man.viewer`, but that didn't work either.

```text
       g\bgi\bit\bt-\b-c\bch\bhe\bec\bck\bko\bou\but\bt(1), g\bgi\bit\bt-\b-b\bbr\bra\ban\bnc\bch\bh(1)
```

At this point, it might be interesting to figure out whether anyone else on MacOS has a similar issue, or whether I somehow managed to mess up my sytstem...

**Comment by echasnovski** [comment]
So, after reading about `git help`, `man`, `groff`, and other more than I'd like, I pushed the desperate [`git-completion-man`](https://github.com/echasnovski/mini.nvim/tree/git-completion-man) temporary branch to try and fix it. Could you try it out and see if completion works?

@aikow, also would you mind:
- Clarifying what type of "doesn't work" you mean here (and in the possible future)? There are now at least "hangs when trying to complete" and "does not hang but shows no completion".
- Creating a separate issue with your findings (as much as you have free time to provide)? This is both to not clutter this issue and for future reference.

------

Those `x\bx` (and possible `_\bx`) is an "old" way to format character as bold (and italic). The origin of this on Mac seems to be [`groff`](https://linux.die.net/man/1/groff) / [`grotty`](https://linux.die.net/man/1/grotty) / or something like that. It seems to still try to format it with these symbols.

**Comment by tssm** [comment]
Hey @echasnovski, regarding how mini.git decides which sub-commands open in a split, I've been playing a bit with the command you gave me and found that `reflog` as well as `stash` are shown with `git --list-cmds=builtins` as well as `git --list-cmds=main`. I'm not sure why you are filtering by list instead, but `reflog` is listed (as well as `remote`, discussed above) if you add `list-ancillarymanipulators`, and `stash` if you add `list-mainporcelain`.

I've also found that if I run either `:Git stage -p`, or `:Git stash list` their output appears as a notification, but the buffers are added to the list, so I have to kill them manually. Any command whose output is not handled as a split will result in the same behavior, I guess

**Comment by echasnovski** [comment]
> Hey @echasnovski, regarding how mini.git decides which sub-commands open in a split, I've been playing a bit with the command you gave me and found that `reflog` as well as `stash` are shown with `git --list-cmds=builtins` as well as `git --list-cmds=main`. I'm not sure why you are filtering by list instead, but `reflog` is listed (as well as `remote`, discussed above) if you add `list-ancillarymanipulators`, and `stash` if you add `list-mainporcelain`. [Here is a list for reference](https://github.com/git/git/blob/master/command-list.txt).

Yes, I know, I've read that file. Adding either `builtins`/`main`/`list-ancillarymanipulators`/`list-mainporcelain` for the task of "get list of commands that are *intended* to show users something instead of do something" is missing the point. Hence only  "info" and "list-xxxinterrogators" are used.

> I've also found that if I run either `:Git stage -p`, or `:Git stash list` their output appears as a notification, but the buffers are added to the list, so I have to kill them manually. Any command whose output is not handled as a split will result in the same behavior, I guess

I can not reproduce this neither with 'mini.notify' nor without it. I.e. there is no extra buffer created *specifically* to show the output of `:Git stage -p`. There is always the scratch buffer from 'mini.notify' present (for performance reasons), but that is it.

What do you use for `vim.notify()`?

**Comment by mehalter** [comment]
Out of curiosity is there a reason for `mini.git`'s repo name to be `mini-git` instead of `mini.git` like all of the other separated mini plugins? It seems strange that it has a different naming convention. Is this because it is currently in a "beta" state and will be renamed to `mini.git` once it is fully released?

**Comment by tssm** [comment]
> Adding either builtins/main/list-ancillarymanipulators/list-mainporcelain for the task of "get list of commands that are intended to show users something instead of do something" is missing the point

Ah, got it. I guess my confusion comes from the fact that `log` is listed, and unless I'm missing something, it only shows something. I hope at some point you reconsider adding support for commands that only show stuff (help wanted?), as IMO that's super useful, as navigating the output can be quickly done with plain old Vim commands (the very reason I miss `reflog` and `stash`)

> I can not reproduce this neither with 'mini.notify' nor without it. I.e. there is no extra buffer created specifically to show the output of :Git stage -p

After digging a bit I realized I messed up my setup, sorry for the false alarm 🙈

**Comment by echasnovski** [comment]
> I guess my confusion comes from the fact that `log` is listed, and unless I'm missing something, it only shows something.

I'd say so too, yeah. Hence it is present in "list-info".

> I hope at some point you reconsider adding support for commands that only show stuff (help wanted?), as IMO that's super useful, as navigating the output can be quickly done with plain old Vim commands (the very reason I miss `reflog` and `stash`)

It *is* already there, at least according to how Git itself categorizes subcommands: `reflog` is [ancillarymanipulators](https://github.com/git/git/blob/3a57aa566a21e7a510c64881bc6bdff7eb397988/command-list.txt#L159C41-L159C62), `stash` is [just `mainporcelain`](https://github.com/git/git/blob/3a57aa566a21e7a510c64881bc6bdff7eb397988/command-list.txt#L184).

I think allowing explicit splitt command modifiers to force command output to be shown in a separate buffer is a robust and universal solution to the "make this subcommand show in a split" problem.

If you want a more automated approach, I'd suggest custom mappings and command line abbreviations.

**Comment by pBorak** [comment]
What are your thoughts on Fugitive's Gedit command? Does it align with the mini-git philosophy?
I often find myself wanting to see how a file looked at a specific git revision. For example, `Gedit HEAD~3:%` allows me to do this. Or maybe I can already accomplish it somehow with current mini-git functionality?

**Comment by echasnovski** [comment]
> What are your thoughts on Fugitive's Gedit command? Does it align with the mini-git philosophy? I often find myself wanting to see how a file looked at a specific git revision. For example, `Gedit HEAD~3:%` allows me to do this. Or maybe I can already accomplish it somehow with current mini-git functionality?

This particular use case of "see how a file looked at a specific git revision" can be done with `:Git show`, i.e. `Git show HEAD~3:%`. It has special treatment in that it also tries to detect the filetype of the output and thus have the proper highlighting/autocommands/etc.

It looks like `:Gedit` is indeed close to `:Git show`, but with a bit more integrations.

**Comment by aikow** [comment]
This might just deserve an issue again (just let me know, and I'll happily create a detailed issue), but I wanted to make sure whether this is in-scope for `mini.git` first.

Using `vim-fugitive` I get prompted to enter my GPG key password when doing anything that requires the key. I currently have the `pinentry-mode loopback` option set in my `gpg.conf` file. However, when doing the same tasks using `mini.git` the command just fails because the GPG key could not be unlocked.

As an unrelated note, would it be possible (or would it make sense) to add a function to `MiniGit` that automatically re-runs the command for a buffer? I found that I occasionally like to keep open a semi-complicated `git log` command, like `git log --all --decorate --graph --oneline`. Whenever I make a change, I have to rerun the command by either typing it out, or by searching through my command history. However, I noticed that the buffer name of the output buffer already seems to store the command that was run, so it should be quite easy to just add a function to refresh the output... If this is out-of-scope though, that's completely fine, although at least having a buffer scoped variable that stores the run command would be nice, so that I could easily implement a command myself.

**Comment by echasnovski** [comment]
> Using `vim-fugitive` I get prompted to enter my GPG key password when doing anything that requires the key. I currently have the `pinentry-mode loopback` option set in my `gpg.conf` file. However, when doing the same tasks using `mini.git` the command just fails because the GPG key could not be unlocked.

I also sign commits using GPG with `pinentry-program /usr/bin/pinentry-gtk-2` in my 'gpg-agent.conf'. It works for me right now. I have . If you can tell me the full GPG-Git setup, I'll try to reproduce and see if it is feasible to work with 'mini.git'.

> As an unrelated note, would it be possible (or would it make sense) to add a function to MiniGit that automatically re-runs the command for a buffer?

This looks like a bit too specific functionality. Relying on command in output buffer name is not really reliable for at least these reasons:
- It doesn't contain information about working directory inside which that command should be executed (which depends on the buffer and its Git root).
- Not all commands result in a split (thus don't have buffer name from which to extract the command).

I *think* the best suggestion here is to make it easier to repeat frequent commands using common Neovim approaches:
- Create a mapping (like `<Leader>gl` for "Git Log").
- Use `@:` to execute the latest command.
- Use smarter history search. For example, type `:Git` followed by `<C-p>` to search only through commands that start with `:Git`. Or use [`MiniExtra.pickers.history()`](https://github.com/echasnovski/mini.nvim/blob/d330f2639462084d2ef6c699ccd6219b81c45bc7/doc/mini-extra.txt#L482) like `Pick history scope=":"`.

**Comment by aikow** [comment]
> I also sign commits using GPG with `pinentry-program /usr/bin/pinentry-gtk-2` in my 'gpg-agent.conf'. It works for me right now. I have . If you can tell me the full GPG-Git setup, I'll try to reproduce and see if it is feasible to work with 'mini.git'.

I often have to sign commits from a server, so using `pinentry-mode loopback` was the only way I was able to get git to even ask for a password instead of just failing. That line is the only line in my `gpg.conf` file, and the rest of my GPG setup should be pretty standard, I just have configured git to automatically sign commits by default instead of manually using the `-s` flag. I'll try taking a look at `vim-fugitive` to see what they do differently.

> It doesn't contain information about working directory inside which that command should be executed (which depends on the buffer and its Git root).

It should be fairly simple to add the information needed to rerun a command to a buffer-scoped variable, similar to the `minigit_summary` variable (coming from someone who just briefly looked at the source code, so maybe not the case). That could include cwd, env, and the actual command in a lua list. However, for those to be useful, I guess you would also need to expose some of the helper functions...

> Not all commands result in a split (thus don't have buffer name from which to extract the command). 

I was mainly thinking of having a buffer open that has the output of `git log --...` with a bunch of format options, and being able to update the buffer automatically by using something roughly akin to `:lua MiniGit.run_cmd(vim.b.minigit_command)`.

I'll respect your decision though after this, I just felt like I might have not stated my idea clearly enough 😀 .

**Comment by echasnovski** [comment]
> I often have to sign commits from a server, so using `pinentry-mode loopback` was the only way I was able to get git to even ask for a password instead of just failing. That line is the only line in my `gpg.conf` file, and the rest of my GPG setup should be pretty standard, I just have configured git to automatically sign commits by default instead of manually using the `-s` flag. I'll try taking a look at `vim-fugitive` to see what they do differently.

I'll take a look.

> I was mainly thinking of having a buffer open that has the output of `git log --...` with a bunch of format options, and being able to update the buffer automatically by using something roughly akin to `:lua MiniGit.run_cmd(vim.b.minigit_command)`. That way, I don't have to manually close the old buffer, rerun the command, and move the buffer to the position it was previously.

Indeed, this type of workflow will not be supported in 'mini.git'. The best advice I can give is to write your own wrapper which will utilize `:Git log -- %`.

**Comment by echasnovski** [comment]
With the release of 0.13.0, 'mini.git' is now out of beta-testing. Thank you all for the early testing and useful feedback! It means a lot!

**Comment by rvyhvn** [comment]
Sorry everyone, but how can I fix the OpenPGP prompt?

**Comment by echasnovski** [comment]
> Sorry everyone, but how can I fix the OpenPGP prompt?

If it is about entering password when signing commits, then my suggestion would be to configure GPG to use a GUI version for this. I had the similar issue with LazyGit.

So following steps from something [like this](https://stackoverflow.com/q/77549879) should probably solve the problem.
