### ISSUE TITLE
mini.completion: chained completions

### ISSUE THREAD

**Issue by saccarosium** [echasnovski/mini.nvim#90]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.completion

### Description

Hi,
I think it would be very nice trying to implement some features of [mucomplete](https://github.com/lifepillar/vim-mucomplete), which is a simple wrapper around vim's completion, such as chained completions.

**Comment by saccarosium** [comment]
Yeah, I really like the plugin because is very minimal and doesn't have too many bells and whistles, but it will be nice having the option to at least have also path completion. Like implementing in a way that kicks in only when u type `/`.

But I will not insist any longer if you like the way is now.

**Comment by echasnovski** [comment]
I think I contemplated a bit about incorporating somehow a path completion into 'mini.copletion'. Found that using built-in `<C-x><C-f>` manually was enough for me because didn't use it that often. Also found using `<C-x><C-l>` (line completion) quite often.
