### ISSUE TITLE
mini.statusline: vim.diagnostic.is_enabled null reference

### ISSUE THREAD

**Issue by tommitah-heeros** [echasnovski/mini.nvim#901]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.statusline

### Description

mini.statusline attempts to use the `vim.diagnostic.is_enabled` but it seems like this is a property that doesn't exist on `vim.diagnostic`. I'm fairly unfamiliar with the diagnostic api and a quick :h vim.diagnostic didn't produce anything for `is_enabled`. Leads me to think this call is just an "inverted" version from `vim.diagnostic.is_disabled`.

source: statusline.lua:648
```lua
if vim.fn.has('nvim-0.10') == 1 then
  H.diagnostic_is_disabled = function(_) return not vim.diagnostic.is_enabled({ bufnr = 0 }) end
```

### Neovim version

0.10

### Steps to reproduce

open file and navigate it

### Expected behavior

-

### Actual behavior

statusline crashes and produces an error notification: error executing lua .../share/nvim/lazy/mini.statusline/lua/mini/statusline.lua:649 attempt to call field 'is_enabled' (a nil value)

**Comment by tommitah-heeros** [comment]
Switched it to 
```lua
if vim.fn.has('nvim-0.10') == 1 then
  H.diagnostic_is_disabled = function(_) return vim.diagnostic.is_disabled({ bufnr = 0 }) end
```
Worked, I'll see if I have time to create a PR for this.

**Comment by tommitah-heeros** [comment]
Ah, looks like I was running a neovim 0.10 build from an ancient commit, pulling that upstream fixed this for me.

**Comment by echasnovski** [comment]
> Ah, looks like I was running a neovim 0.10 build from an ancient commit, pulling that upstream fixed this for me.

Yes, `vim.diagnostic.is_enabled()` is a (very) late addition to Neovim 0.10, but it *is* present in released version.

**Comment by ngortheone** [comment]
Thanks. I had this issue after an update recently and upgrading neovim helped
