### ISSUE TITLE
[mini.test] some way to update screenshots

### ISSUE THREAD

**Issue by MagicDuck** [echasnovski/mini.nvim#908]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.test

### Description

At the moment, updating screenshots is somewhat painful.
My workaround is to add the following to my Makefile:
```
update-screenshots:
	rm -rf tests/screenshots/* 
	make test
```
Maybe one way would be to set some env var that `expect.reference_screenshot()` checks and would force re-write if true?
So you would call it like:
```
make test-file test/test_something.lua UPDATE_SCREENSHOTS=true
```

**Comment by echasnovski** [comment]
Thanks for the suggestion (and actually writing tests for the plugin)!

There is a [`force` option in `expect.reference_screenshot`](https://github.com/echasnovski/mini.nvim/blob/c32c6642f4b191138673a37dcc221c9e9afbbd38/doc/mini-test.txt#L568-L569) which you can utilize in helper. I use [this one](https://github.com/echasnovski/mini.nvim/blob/c32c6642f4b191138673a37dcc221c9e9afbbd38/tests/helpers.lua#L153-L163) and usually manually set `{ force = true }`, but you can set its default to use `UPDATE_SCREENSHOTS` environment variable.

All in all, I think this one is in a territory of taste and adaptability to specific plugin needs. So closing as not planned.
