### ISSUE TITLE
[mini.clue] configurable backspace and enter binds

### ISSUE THREAD

**Issue by Saghen** [echasnovski/mini.nvim#912]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.clue

### Description

Thanks for the great plugin! I use `<leader><backspace>` and `<leader><enter>` bindings. `mini.clue` is configured to use `<backspace>` and `<enter>` for its own funcntionality which causes the user's bindings to not work. It would be great if the plugin optionally detected the presence of a user's `<backspace>` or `<enter>` binding and disabled the functionality automatically. Or alternatively, allowed for configuring/disabling these two built-in bindings.

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This was already suggested in #491 and [was considered to be not a good idea](https://github.com/echasnovski/mini.nvim/issues/491#issuecomment-1772531253).

Closing as not planned.
