### ISSUE TITLE
mini.git: completion hangs and option completion does not work on MacOS

### ISSUE THREAD

**Issue by aikow** [echasnovski/mini.nvim#918]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.git

### Description

This is a 2 fold problem, and was [originally discussed](https://github.com/echasnovski/mini.nvim/issues/898#issuecomment-2133310915) in the beta testing thread for the mini.git module.

The first issue is that the completion hangs, and eventually times out. This is because I have the `MANPAGER` environment variable set to `nvim +Man!`, although I would assume similar behavior for other slightly more obscure pagers. This can easily be fixed by overriding the `MANPAGER` environment variable in the `envs` table that is passed to `H.cli_run`. I've copied your code snippet here for completeness’s sake.

```lua
  local command = { MiniGit.config.job.git_executable, '--no-pager', unpack(args) }
  local custom_env = { NO_COLOR = 1, PAGER = 'cat', MANPAGER = 'cat' }
  local environ = vim.tbl_deep_extend('force', vim.loop.os_environ(), custom_env)
  local env = {}
  for k, v in pairs(environ) do
    table.insert(env, string.format('%s=%s', k, tostring(v)))
  end
  local res = H.cli_run(command, cwd, nil, { env = env }).out
```

Once the first issue was fixed, the second issue that arose is what you explained in this comment.

> Those x\bx (and possible _\bx) is an "old" way to format character as bold (and italic). The origin of this on Mac seems to be [groff](https://linux.die.net/man/1/groff) / [grotty](https://linux.die.net/man/1/grotty) / or something like that. It seems to still try to format it with these symbols.

The behavior this results in using the current ([main branch](b0b435873375c4341f2ecbcb95e9e645abe0d679)) implementation of `mini.git is that regular completion of subcommands and git objects, like branches and tags works fine, but completion for options is broken.

I just tried your `git-completion-man` branch and that fixes the issue. I can now get completions on MacOS.

### Neovim version

v0.11.0-dev+g0e9c92a90

### Steps to reproduce

`minimal.lua` can theoretically be empty, it just needs to add mini.git as a module.

1. `MANPAGER='nvim +Man!' nvim -nu minimal.lua`
3. Type `:Git -`
4. Neovim hangs and eventually completion times out

Or

1. `MANPAGER=cat nvim -nu minimal.lua`
2. Type `:Git -`
3. No completion for options are shown

### Expected behavior

See completions for options

### Actual behavior

Current main branch just hangs until it times out. This is due to my custom `MANPAGER` environment variable. Without that, it still doesn't show completions _for options_, due to the way MacOS formats man pages, causing the section headers to be formatted in a way that the parsing logic for options inside `mini.git` can't pick up.

**Comment by aikow** [comment]
if I need to clarify or test anything else, just let me know :) Thanks again for for time and help!

**Comment by echasnovski** [comment]
Thank you **so much** for this!

> I just tried your `git-completion-man` branch and that fixes the issue. I can now get completions on MacOS.

This also makes me happy :) I'll try to finalize this into `main` tomorrow.

**Comment by echasnovski** [comment]
This now should be fixed on latest `main`.

Thanks for *your* time and trying to make 'mini.git' a better module!
