### ISSUE TITLE
mini.completion float window stays open after exiting

### ISSUE THREAD

**Issue by gsuuon** [echasnovski/mini.nvim#924]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.completion

### Description

The float window with additional info is staying after exiting from completion, I see this happening with both `<esc>` and `<ctrl-c>`.

[mini-completion-float.webm](https://github.com/echasnovski/mini.nvim/assets/6422188/6e67c8a9-18f7-47ec-867a-cb3ab07e2ea4)

### Neovim version

NVIM v0.10.0-dev-2889+gf064e72b9

### Steps to reproduce

1. install mini.completion with all default options
2. `<c-x><c-u>` to start completion
3. `<c-c>` or `<esc>` to leave completion

### Expected behavior

Float window also goes away

### Actual behavior

Float window sticks around

**Comment by echasnovski** [comment]
Thanks for the issue!

I can reproduce this with `<C-c>`, but not with `<Esc>`. It *should* work with `<Esc>` but *can* be an undefined behavior with `<C-c>`.

It seems to be an issue with 'InsertLeavePre' event not being triggered with `<C-c>`. I'll take a look.

**Comment by gsuuon** [comment]
Thanks for the fast response (and the plugins)! The fix on `backlog` looks good. I couldn't repro with `<esc>` again either, though it was happening consistently when I filed the issue (I hit `<esc>` in the video). Not sure if maybe that buffer just got in a weird state.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.
