### ISSUE TITLE
Toggling mini.files

### ISSUE THREAD

**Issue by 6H075T2** [echasnovski/mini.nvim#930]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

Mini.files

### Description

Is toggling this plugin possible? the one in the docs doesnt work for me any thoughts on how to do this? Im not fluent in lua yet

**Comment by echasnovski** [comment]
[This solution](https://github.com/echasnovski/mini.nvim/blob/6260c7d3d96efdaaf5dece53457584ece5cf7212/doc/mini-files.txt#L368-L370) works. You can use it to create a mapping like this:

```lua
require('mini.files').setup()
local minifiles_toggle = function()
  if not MiniFiles.close() then MiniFiles.open() end
end
vim.keymap.set('n', '<Leader>et', minifiles_toggle)
```
