### ISSUE TITLE
Open mini.starter when no files are open

### ISSUE THREAD

**Issue by j0lol** [echasnovski/mini.nvim#933]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

starter

### Description

Would make nvim feel more like a cohesive IDE imo :)

**Comment by echasnovski** [comment]
This is already the case with [default value of `config.autoopen`](https://github.com/echasnovski/mini.nvim/blob/d0494506d2e554bd3fecdc92ef8d57ea92d138cc/doc/mini-starter.txt#L210-L212). To achieve this, execute `require('mini.starter').setup()` *during* startup, i.e. not during lazy loading 'mini.starter' / 'mini.nvim'.
