### ISSUE TITLE
[mini.clue] mini.clue interferes with the complete mechanism of Julia language plugin

### ISSUE THREAD

**Issue by ronisbr** [echasnovski/mini.nvim#935]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.clue

### Description

First of all, thank you @echasnovski for these amazing set of packages!

When the `mini.clue` window opens, I see interference in the completion mechanism used by https://github.com/JuliaEditorSupport/julia-vim to replace LaTeX sequences with UTF-8 symbols. For example, in this case, you can type `\alpha<C-x><C-u>` and it is replaced by `α`. However, if the `mini.clue` window is opened, it does not work.

### Neovim version

0.10

### Steps to reproduce

1. `nvim -nu minimal.lua test.jl`
2. Type `\alpha`
3. Hit `<C-x><C-u>` fast enough so that the `mini.clue` window does not open.
4. In a new line, type `\alpha` again.
5. Hit `<C-x>` wait for the `mini.clue` window and then type `<C-x>`.

`minimal.lua`
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "JuliaEditorSupport/julia-vim",
    lazy = false,
    config = function()
      vim.g.latex_to_unicode_auto = false
    end
  },
  {
    "echasnovski/mini.clue",
    config = function()
      local miniclue = require("mini.clue")
      miniclue.setup({
        triggers = {
          -- Leader triggers
          { mode = "n", keys = "<Leader>" },
          { mode = "x", keys = "<Leader>" },
          { mode = "n", keys = "<localleader>" },
          { mode = "x", keys = "<localleader>" },
          { mode = "n", keys = "\\" },
          { mode = "x", keys = "\\" },
          { mode = "n", keys = "[" },
          { mode = "x", keys = "[" },
          { mode = "n", keys = "<cr>" },
          { mode = "x", keys = "<cr>" },
          { mode = "n", keys = "]" },
          { mode = "x", keys = "]" },

          -- Built-in completion
          { mode = "i", keys = "<C-x>" },

          -- `g` key
          { mode = "n", keys = "g" },
          { mode = "x", keys = "g" },

          -- Marks
          { mode = "n", keys = "'" },
          { mode = "n", keys = "`" },
          { mode = "x", keys = "'" },
          { mode = "x", keys = "`" },

          -- Registers
          { mode = "n", keys = '"' },
          { mode = "x", keys = '"' },
          { mode = "i", keys = "<C-r>" },
          { mode = "c", keys = "<C-r>" },

          -- Window commands
          { mode = "n", keys = "<C-w>" },

          -- `z` key
          { mode = "n", keys = "z" },
          { mode = "x", keys = "z" },
        },

        clues = {
          -- Enhance this by adding descriptions for <Leader> mapping groups
          miniclue.gen_clues.builtin_completion(),
          miniclue.gen_clues.g(),
          miniclue.gen_clues.marks(),
          miniclue.gen_clues.registers(),
          miniclue.gen_clues.windows(),
          miniclue.gen_clues.z(),
        },
        window = {
          delay = 500,
          config = {
            width = "auto",
          },
        },
      })
    end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```

### Expected behavior

After step 3 and 5, `\alpha` should be replaced by `α`.

### Actual behavior

After step 3, `\alpha` is replaced by `α`. However, after step 5, the `mini.clue` window stays open and the text is not replaced.

**Comment by echasnovski** [comment]
Thanks for the issue!

This happens because `<C-u>` is [by default a special key](https://github.com/echasnovski/mini.nvim/blob/e08626092574872cdfa7aa2e2f2a83ce1e156ccd/doc/mini-clue.txt#L194-L197) in key query process and is used to scroll clue window upwards. But only if the window is visible, as you experience.

This can be resolved with at least the following approaches:
- Disable/remap scroll upwards key globally. Here is an example of remapping:
    ```lua
    require('mini.clue').setup({
      -- ...
      window = {
        scroll_down = '<C-f>',
        scroll_up = '<C-b>',
      },
    })
    ```
- Disable/remap scroll keys only for 'julia' filetype. For that, create an 'after/ftplugin/julia.lua' file with the following content (this is an example of disabling):
    ```lua
    vim.b.miniclue_config = { window = { scroll_down = '', scroll_up = '' } }
    ```
- Remove `<C-x>` in Insert mode from `config.triggers`.

Closing as it works as expected.

**Comment by ronisbr** [comment]
Hi @echasnovski !

Thank you very much for the quick and detailed answer! It is working perfectly now. Sorry for the noise.

**Comment by echasnovski** [comment]
No problem. It *is* kind of not obvious why this might happen. Searching 'mini.clue' help for `'<C-x>'` and `'<C-u>'` might have given a clue (pun intended). 

The actual solutions are to somehow disable special treatment of  `'<C-u>'`, which this issue will now serve as reference. So it's good that you asked :)
