### ISSUE TITLE
undo in mini.files erases all file names

### ISSUE THREAD

**Issue by sid-6581** [echasnovski/mini.nvim#940]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

When I press `u` or type `:undo` when in a `mini.files` popup, all the file names are erased, and the buffer is considered modified.

### Neovim version

0.10.0

### Steps to reproduce

Open a `mini.files` popup and press `u` in it.

### Expected behavior

Expect `u` to show "Already at oldest change".

### Actual behavior

Before:

![image](https://github.com/echasnovski/mini.nvim/assets/28602336/a19bdc9b-53c9-4b04-a000-6f8db2e6a5bb)

After pressing `u`:

![image](https://github.com/echasnovski/mini.nvim/assets/28602336/ccb3314a-6d29-405b-ac3a-0c28fd6452be)

**Comment by echasnovski** [comment]
Thanks for the issue!

Yes, I am aware of this but don't think it is a huge problem. I'll take a look at if this can be solved  without much hassle.

**Comment by echasnovski** [comment]
This should now be fixed on latest `main`.

**Comment by sid-6581** [comment]
> This should now be fixed on latest `main`.

It looks good now, thanks so much!
