### ISSUE TITLE
How to change mini.notify to bottom right corner

### ISSUE THREAD

**Issue by saifulapm** [echasnovski/mini.nvim#942]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.notify

### Description

Hi, First thanks for your great works. 

I am trying to move notify window bottom right corner. But not sure how I can do it.

### Neovim version

10.0.0

### Steps to reproduce

```lua

require('mini.notify').setup({
    window = {
      config = {
        border = 'solid',
        anchor = 'SE',
      },
    },
  })

```

### Actual behavior

It always render top right side. But I want to render on bottom right size. Is it doable ?

**Comment by echasnovski** [comment]
It is indeed possible with `config.window.config`, but needs to account for [some default values used in it](https://github.com/echasnovski/mini.nvim/blob/e736fe131e6c18d39eecffb43d582c3e95550a90/doc/mini-notify.txt#L189-L202).

You were close: single `anchor` is not enough as it configures which corner of *floating window itself* should be put at `row` and `col` of window config. The following setup should work:

```lua
local win_config = function()
  local row = vim.o.lines - vim.o.cmdheight - (vim.o.laststatus >= 2 and 1 or 0)
  return { border = 'solid', anchor = 'SE', row = row }
end
require('mini.notify').setup({ window = { config = win_config } })
```

Making config callable allows for a more dynamic adjustment of `row` (like after resizing the whole instance window, changing command height, etc.).
