### ISSUE TITLE
mini.files: Keymap to open file in a split window

### ISSUE THREAD

**Issue by mrjones2014** [echasnovski/mini.nvim#943]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

In `mini.files`, I'd like an option under `mappings` that, after `mini.files` window closes, splits the window before opening the selected buffer.

**Comment by echasnovski** [comment]
This was already suggested in #646 and #760. Following [example for making a mapping that creates a split](https://github.com/echasnovski/mini.nvim/blob/e736fe131e6c18d39eecffb43d582c3e95550a90/doc/mini-files.txt#L433-L462) is the suggest approach here. Note, that examples only create a split and changes target window to be that split. Follow with actually opening a file the usual way (`l` or `L` by default).

**Comment by ddiegosr** [comment]
It seems the suggested approach doesn't work anymore. It creates the split but doesn't open the selected file.

https://github.com/user-attachments/assets/d5dbf1df-4858-45b2-877c-3d27b1c8a6c7

My configs:
```lua
local map_split = function(buf_id, lhs, direction)
  local rhs = function()
    -- Make new window and set it as target
    local new_target_window
    vim.api.nvim_win_call(MiniFiles.get_explorer_state().target_window, function()
      vim.cmd(direction .. " split")
      new_target_window = vim.api.nvim_get_current_win()
    end)

    vim.defer_fn(function()
      MiniFiles.set_target_window(new_target_window)
      MiniFiles.close()
    end, 30)
  end

  -- Adding `desc` will result into `show_help` entries
  local split_direction = vim.split(direction, " ")[2]
  local desc = "Open in " .. split_direction .. " split"
  vim.keymap.set("n", lhs, rhs, { buffer = buf_id, desc = desc })
end

local toggle = function()
  local MiniFiles = require("mini.files")
  local _ = MiniFiles.close() or MiniFiles.open(vim.api.nvim_buf_get_name(0), false)
  MiniFiles.reveal_cwd()
end

return {
  "echasnovski/mini.files",
  init = function()
    vim.api.nvim_create_autocmd("User", {
      pattern = "MiniFilesBufferCreate",
      callback = function(args)
        local buf_id = args.data.buf_id
        -- Tweak keys to your liking
        map_split(buf_id, "<C-s>", "belowright horizontal")
        map_split(buf_id, "<C-v>", "belowright vertical")
      end,
    })
  end,
  keys = {
    { "-", toggle, desc = "Toggle Mini.Files" },
  },
  version = "*",
  opts = {
    windows = {
      preview = true,
      width_preview = 50,
    },
    mappings = {
      go_in_plus = "<CR>",
    },
  },
}

```

**Comment by echasnovski** [comment]
> It seems the suggested approach doesn't work anymore. It creates the split but doesn't open the selected file.

The suggested linked approach ([this example](https://github.com/echasnovski/mini.nvim/blob/7b4d5d48b6b5a75009d63f8f3e4ef4819b7e8139/doc/mini-files.txt#L477-L502)) only makes split and keeps explorer opened. The provided code differs from the example by the `vim.defer_fn()` call inside `map_split`. It explicitly tells to change target window and *close the explorer*, which is exactly what happens.

Add the `MiniFiles.go_in()` call before closing and it should open the file under cursor.

**Comment by ddiegosr** [comment]
The `vim.defer_fn()` call was me trying to solve the problem. In the first moment I thought the code in the example would be enough to already open the file under cursor.
Adding the `MiniFiles.go_in()` call worked. Thanks a lot.
