### ISSUE TITLE
Animation for incremental search

### ISSUE THREAD

**Issue by BitPusher16** [echasnovski/mini.nvim#945]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.animate

### Description

This lovely plugin has made my neovim work much more pleasant, thank you for that.

Is it possible to add animation support for cursor jumping during incremental search? This is the last jarring behavior which I've not been able to suppress in Neovim.

**Comment by echasnovski** [comment]
Thanks for the suggestion and kind words!

Unfortunately, incremental search is meant to be as quick as possible. Thus it does not seem to trigger any events which 'mini.animate' can "hook" into (like `CursorMoved` currently used for animating cursor movement). See [this comment](https://github.com/vim/vim/issues/11628#issuecomment-1328220365) for reference as well as the whole issue discussion. Thus I am afraid it is not really possible to do that right now. And if it *is* made possible, then `CursorMoved` would trigger right away making cursor animated.

Closing as "not possible at the moment and if made possible should work out of the box".

**Comment by BitPusher16** [comment]
Thank you for the detailed reply!

Last night I found a separate plugin which does what I need it to and works well alongside mini.animate. 

https://github.com/RRethy/vim-tranquille

This plugin provides an alternative search function which can override the '/' default. It manually handles highlighting and calls the nvim search() function internally, without jumping. After a word is highlighted, mini.animate can nicely jump to the next instance on 'n'. My nvim is now free of jarring transitions!
