### ISSUE TITLE
Add module: trim trailing empty lines

### ISSUE THREAD

**Issue by stvhuang** [echasnovski/mini.nvim#95]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

https://stackoverflow.com/questions/7495932/how-can-i-trim-blank-lines-at-the-end-of-file-in-vim

### Description

There is mini.trailspace handling trailing spaces.
I hope to add another module that can handling (e.g., trimming) the trailing empty lines.

**Comment by echasnovski** [comment]
Oh, nice suggestion. Thanks!

My initial reaction is that it might be a fit for 'mini.trailspace'. All those lines do make a space, right? :)

I'll think about it.

**Comment by stvhuang** [comment]
Totally agree. It will be good to just extend the `trailspace` to support trailing empty lines!
