### ISSUE TITLE
[mini.align] Align for commas but I have commas inside strings

### ISSUE THREAD

**Issue by georgeguimaraes** [echasnovski/mini.nvim#950]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.align

### Description

What's a good modifier to align commas when I have commas in strings that should not be messed?

### Neovim version

NVIM v0.11.0-dev-3338+gd7651b27d-Homebrew

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Expected behavior

 ```
abc, "City, State",                 123
def, "Country",                     456
hij, "Another Country",             789
klm, "Another City, Another State", 012
 ```

### Actual behavior

Tks for all the plugins!

I have a piece of code something like this:

```
abc, "City, State", 123
def, "Country", 456
hij, "Another Country", 789
klm, "Another City, Another State", 012
```

Trying to align it with  `ga,` gives me

 ```
abc, "City,             State",         123
def, "Country",         456
hij, "Another Country", 789
klm, "Another City,     Another State", 012 
 ```

which is not what I wanted. 

I tried to configure the split modifier manually but with no luck. Is there a good way to achieve this?

**Comment by echasnovski** [comment]
There is an ["ignore" modifier](https://github.com/echasnovski/mini.nvim/blob/cc2f5b542c38b2af234b62196fa5a8621119fb0c/doc/mini-align.txt#L30). See more details [here](https://github.com/echasnovski/mini.nvim/blob/cc2f5b542c38b2af234b62196fa5a8621119fb0c/doc/mini-align.txt#L270-L283) and [the exported function for more control](https://github.com/echasnovski/mini.nvim/blob/cc2f5b542c38b2af234b62196fa5a8621119fb0c/doc/mini-align.txt#L850).

Its suggested application is like this:
- `gAip` to start interactive align on paragraph.
- `,` to enter split.
- `i` to ignore some common splits.
- Ensure the end result is what you'd expect and press `<CR>`.
