### ISSUE TITLE
Add mini.zenmode

### ISSUE THREAD

**Issue by AstorAyestas** [echasnovski/mini.nvim#953]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini

### Description

# Mini.zenmode
Is there any plan to add zen mode to mini? 
Something similar to:
 - https://github.com/folke/zen-mode.nvim
   
 Thanks

**Comment by echasnovski** [comment]
Thanks for the suggestion!

The 'mini.nvim' version of "zenmode" like functionality is [`MiniMisc.zoom()`](https://github.com/echasnovski/mini.nvim/blob/f1dd64cf2ac1b348bd440e59446abf680c7188d6/doc/mini-misc.txt#L268-L279). It toggles between showing and unshowing particular buffer "full screen". I have it mapped to `<Leader>oz` ("other" + "zoom") and it works for me quite well.

Closing as "already has a version that seems to be enough".
