### ISSUE TITLE
get icons based on file paths rather than display text

### ISSUE THREAD

**Issue by jason0x43** [echasnovski/mini.nvim#955]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick

### Description

I made a custom source to show git files with multiple scopes, along with the status, based on [this comment](https://github.com/echasnovski/mini.nvim/issues/550#issuecomment-1803964565). The items look like

```lua
{
  text = "H path/to/file.js",
  path = "path/to/file.js"
},
{
  text = "? path/to/untracked.js",
  path = "path/to/untracked.js"
},
```

That works great, except that file icons don't show up. The request is for `default_show` to show icons for file items based on the file path rather than the display text.

The root issue is that `get_icon` in `default_show` is passed the text of each item rather than the entire item (or the `path` for file items).

**Comment by jason0x43** [comment]
A way to specify a custom prefix in the item would also work, assuming the icon would be added onto that. Maybe something like

```lua
{
  text = "path/to/file.js",
  prefix = "H",
  path = "path/to/file.js"
}
```

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This looks like a reasonable use case. There is some work planned regarding icons in 'mini.nvim', so I think I'll revisit this feature during it.

**Comment by echasnovski** [comment]
This should be resolved on latest `main`. Getting icon data now prefers `path` (either explicit in table or implicit in string item) with fallback on using `text` field (if it is present). Overall I think this is indeed a more coherent design, thanks for the suggestion!
