### ISSUE TITLE
Can't install in Astronvim: fatal error

### ISSUE THREAD

**Issue by slacksystem** [echasnovski/mini.nvim#960]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

Entire project

### Description

When I try to install mini.nvim to my Astronvim install, it won't clone the project when trying to install with Lazy

When I do `Lazy install`, the floating window pops up and it tries to install the plugin, where I get:

### Neovim version

NVIM v0.10.0

### Steps to reproduce

1. Add AstroNvim config to neovim
2. Include put the following in `~/.config/nvim/lua/plugins/user.lua`, where all the user-added plugins go:
```
  {
    "echanovski/mini",
    version = false,
  },
```
3. Run `Lazy install`

### Expected behavior

The plugin clones successfully and installs correctly

### Actual behavior

Floating Lazy window shows:
```
  Failed (1)
    ○ mini 
        Cloning into '/home/slack/.local/share/nvim/lazy/mini'...
        fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
I have tried with both versions, I made sure there wasn't any mini folder or related already in my `~/.local/share/nvim/lazy/` folder.
I'm not getting this issue when I try to install other plugins, only mini, I can clone the folder directly into the lazy folder using the command line, but I'm not sure how to get lazy to recognize the plugin that's already there because when it's there and I include it in that `user.lua` file it tries to clone over it with the same error.
I'm happy to provide more info if there's anything that would be helpful in figuring this out..

**Comment by slacksystem** [comment]
Scratch all that. I'm such a doofus. Thought I had copied and pasted directly but apparently I misspelled the name. Closing this with my apologies.

**Comment by echasnovski** [comment]
> Scratch all that. I'm such a doofus. Thought I had copied and pasted directly but apparently I misspelled the name. Closing this with my apologies.

No worries. I get that it is not the easiest to type and visually verify for people not from Eastern Europe :)

> ETA: Not your call, but I really think Lazy.nvim should provide a much better error to indicate that there isn't any repo there, that it's a 404, because that error message is quite misleading

To be fair, my first assumption was that *somebody* mistyped the username (I thought it was maybe in Astronvim repo itself). `could not read Username for 'https://github.com'` can be better, of course, but at least it mentions username as the core of the issue.

**Comment by slacksystem** [comment]
See I thought it was for some reason trying to do something with my credentials stored, i.e. my username, it didn't occur to me that it was referring to the username of the repo. In hindsight that does seem like it makes more sense 😅
