### ISSUE TITLE
mini.files preview only for directories

### ISSUE THREAD

**Issue by sudo-tee** [echasnovski/mini.nvim#961]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I would like to be able to have the preview but only for directory.  

It would make navigating the tree easier and faster. 

Although the functionality is somewhat already there, it also displays  a preview for files which I find a bit distracting and it also clutters the screen.

It would be great to have 2 seperate config eg:

```lua
{
  windows = {
     file_preview = false,
     directory_preview = true,
     file_preview_width = 40,
     file_preview_height = 25,
     directory_preview = 25,
  }
}
```

By making it seperate config you could also change the size of the file preview seperately.

Thanks for your great plugins and awesome work

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is out of scope for 'mini.files', as it increases available config options and code complexity for already quite big 'mini.files' module.

Closing as not planned.
