### ISSUE TITLE
mini.trailspace is applied to mini.starter

### ISSUE THREAD

**Issue by assistcontrol** [echasnovski/mini.nvim#97]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

trailspace, starter

### Description

Spaces are erroneously highlighted on the start screen, even with `only_in_normal_buffers` enabled. Once any window or buffer changes occur, the highlighting disappears.

Trailspace creates an autocommand that watches for `buftype` changes. When starter loads, it sets `buftype`. Perhaps there's a race on `buftype` somewhere, where:

1. trailspace reads buftype (`''`)
2. starter sets buftype (`nofile`)
3. trailspace watches for buftype changes

### Neovim version

0.7.3

### Steps to reproduce

1. Put spaces somewhere in starter's config. I put mine in the header (https://github.com/assistcontrol/vim/blob/main/lua/aw/plugins/ministarter.lua).
2. Loading order of starter vs trailspace seems not to matter.

### Actual behavior

Trailing spaces are highlighted.

`:set buftype=nofile` turns highlighting off. So does anything that switches windows (create window, `:h`, etc.).

**Comment by echasnovski** [comment]
Thanks for noticing this!

The reason for this is that Starter buffer is designed to open as fast as possible. One of the tricks that gave a massive speedup was setting buffer filetype and all buffer options with `noautocmd` (which disables autocommands from 'mini.trailspace'). To balance this, there is a `MiniStarterOpened` custom event with which users can operate upon buffer opening.

So in your case adding `vim.cmd('autocmd User MiniStarterOpened lua MiniTrailspace.unhighlight()')` to your config should solve this.

However, I agree that this is an issue. I'll try to find a good way to solve this while preserving startup speed. So let's not close this yet.

**Comment by echasnovski** [comment]
Thanks again for bringing this up! Should be fixed in latest `main`.
