### ISSUE TITLE
Error on second navigation using mini.files when mapped to `-`

### ISSUE THREAD

**Issue by mblarsen** [echasnovski/mini.nvim#972]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.files

### Description

I've configured mini.files to open on `-` (minus).

This works great the first time but second time I get the error below.

If I us a different map, e.g. `gf` there's no issues.

```
   Error  17:16:05 msg_show.lua_error     min /min             
   Error  17:16:06 msg_show.lua_error Error executing vim.schedule lua callback: ...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:2100: attempt to compare number with nil
stack traceback:
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:2100: in function 'is_modified_buffer'
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:2277: in function 'window_update_border_hl'
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:2246: in function 'window_set_view'
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:1558: in function 'explorer_refresh_depth_window'
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:1321: in function 'explorer_refresh'
	...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:714: in function <...al/share/nvim-homebrew/lazy/mini.nvim/lua/mini/files.lua:680>
```

This is my setup (Lazy.nvim)

```lua
return {
  {
    "echasnovski/mini.nvim",
    config = function()
      require("mini.basics").setup {
        options = {
          basic = true,
          extra_ui = true,
          win_borders = "single",
        },
        silent = true,
      }
      require("mini.ai").setup()
      require("mini.diff").setup()
      vim.keymap.set("n", "ghp", require("mini.diff").toggle_overlay)
      require("mini.files").setup {
        mappings = {
          go_in_plus = "<cr>",
        },
      }
      vim.keymap.set("n", "-", require("mini.files").open, { desc = "Open parent directory" })
      require("mini.surround").setup()
      require("mini.operators").setup()
    end,
  },
```

### Neovim version

0.10.0

### Steps to reproduce

1. Open mini.files by pressing `-`
2. mini.files opens and I navigate to a file `L`
3. from that file I press `-` again
4. small mini.files opens with no content and the error

### Actual behavior

Small mini.files window opens with nothing in it

<img width="210" alt="image" src="https://github.com/echasnovski/mini.nvim/assets/247048/790bd985-6553-4d6b-a0fb-49ec6a1531a3">

**Comment by echasnovski** [comment]
Thanks for the issue!

Unfortunately, I can not reproduce. I have no error and everything opens as expected after pressing `-` again inside a file opened from the explorer.

There are some issues with reproduction steps:
- Step 2 says `I navigate to a file L` which is a bit ambiguous and contradicts the config. Do you mean you open a file with `go_in_plus` mapping inside an explorer.
- Is step 3 indeed means what I understood it means: try again open explorer by pressing `-` while inside a file opened with 'mini.files' (and there is no explorer currently opened)?

If it doesn't work with `-` but works with some other mapping, there seems to be a conflicting mappings. What does `:nmap -` show?

**Comment by mblarsen** [comment]
Hmm, after running with only mini and nothing else I don't have the issue either. Sorry for the alarm, must be some conflicting plugin.

Regarding `L` I was flipping back from `L` and and `<cr>` (coming from oil.nvim) so wrote up the wrong steps 👐

**Comment by mblarsen** [comment]
FYI -- the conflict was https://github.com/m4xshen/hardtime.nvim

Even when disabling hardtime in minifiles it still fails.

```lua
return {
  "m4xshen/hardtime.nvim",
  wnabled = true,
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disabled_filetypes = { "minifiles" },
    restriction_mode = "hint",
  },
}
```

**Comment by echasnovski** [comment]
Thanks for the follow up!

This is somewhat expected because 'hardtime.nvim' [treats `-` as special key](https://github.com/m4xshen/hardtime.nvim/blob/9a4e24fb40482dc85a93bf6cf344a030b9bf9a39/lua/hardtime/config.lua#L52). So might be doing something not compatible with `MiniFiles.open()`.
