### ISSUE TITLE
[mini.git] Can I use :G instead of :Git

### ISSUE THREAD

**Issue by haunt98** [echasnovski/mini.nvim#977]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.git

### Description

Thank for wonderful module. Just a little ask. Can I change to :G instead :Git when invoke git in mini.git ?

Because I use tpope/vim-fugitive for a long time and familiar with :G

**Comment by echasnovski** [comment]
There is no built-in way to change the command name (and most certainly won't be).

The best suggestion is to use general approaches at creating "aliases" for user commands. See [this comment](https://github.com/echasnovski/mini.nvim/discussions/929#discussioncomment-9621224) for more details.

**Comment by haunt98** [comment]
Thank @echasnovski for your suggestion!
