### ISSUE TITLE
Feature: add option jump_to_single_result to lsp picker

### ISSUE THREAD

**Issue by abeldekat** [echasnovski/mini.nvim#978]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.pick, mini.extra

### Description

Recently I started using mini.pick in my [config](https://github.com/abeldekat/nvim_pde/blob/main/lua/ak/config/editor/mini_pick.lua). Thank you for this great plugin!

Regarding the `lsp` picker, I miss the ability to jump directly to a single result, bypassing the picker.
This is standard behavior in `telescope`, and can be configured in `fzf-lua` by supplying `jump_to_single_result` is true.

I frequently use `goto definition`. For now, `fzf-lua` provides the following `lsp` pickers in my config: "definition", "reference", "implementation", "type_definition".

Would it be possible to add this behavior to mini.pick?

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This is, of course, possible. However, I don't think this is a good idea. My reasoning is that starting a picker should *always* result into showing a picker (as stated in #809 with a bit more thoughts in [this comment](https://github.com/echasnovski/mini.nvim/issues/550#issuecomment-1792044864)).

Closing as not planned.

**Comment by abeldekat** [comment]
Oops... I was just writing an apology for this duplicate issue...)

**Comment by metafates** [comment]
I've stumbled upon the same problem and implemented this function that does just that =) Hope it helps

```lua
-- Open LSP picker for the given scope
---@param scope "declaration" | "definition" | "document_symbol" | "implementation" | "references" | "type_definition" | "workspace_symbol"
---@param autojump boolean? If there is only one result it will jump to it.
function M.picker(scope, autojump)
	---@return string
	local function get_symbol_query()
		return vim.fn.input("Symbol: ")
	end

	if not autojump then
		local opts = { scope = scope }

		if scope == "workspace_symbol" then
			opts.symbol_query = get_symbol_query()
		end

		require("mini.extra").pickers.lsp(opts)
		return
	end

	---@param opts vim.lsp.LocationOpts.OnList
	local function on_list(opts)
		vim.fn.setqflist({}, " ", opts)

		if #opts.items == 1 then
			vim.cmd.cfirst()
		else
			require("mini.extra").pickers.list({ scope = "quickfix" }, { source = { name = opts.title } })
		end
	end

	if scope == "references" then
		vim.lsp.buf.references(nil, { on_list = on_list })
		return
	end

	if scope == "workspace_symbol" then
		vim.lsp.buf.workspace_symbol(get_symbol_query(), { on_list = on_list })
		return
	end

	vim.lsp.buf[scope]({ on_list = on_list })
end
```

**Comment by tgharib** [comment]
@metafates Thanks! That worked for me.

I only had to change `function M.picker(scope, autojump)` to `function picker(scope, autojump)` and then called it via `<Cmd>lua picker('definition', true)<CR>`
