### ISSUE TITLE
mini.files content.postfix

### ISSUE THREAD

**Issue by mrshmllow** [echasnovski/mini.nvim#984]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.files

### Description

I would like to be able to append text in the same manner that you can prefix text with a content.prefix function.

For an example of why this would be useful, this is currently the best git-view that I could achieve using a prefix:

![image](https://github.com/echasnovski/mini.nvim/assets/40532058/80a9dcee-2ad4-4514-9164-d5edab615571)

It would be pretty cool if we could add some extra info without breaking the columns :P

**Comment by echasnovski** [comment]
Thanks for the suggestion!

I don't think this will be a worthwhile addition. The only use case I can think about is indeed showing some custom indicator, but for that I'd recommend using extmarks with `virt_text_pos` not equal to `'overlay'` (so either `'eol'`, `'right_align'`, or `'inline'`).

Closing as not planned.
