### ISSUE TITLE
docs improvement (`mini.surround`)

### ISSUE THREAD

**Issue by simonmandlik** [echasnovski/mini.nvim#986]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.surround

### Description

Looks like `MiniSurround.user_input()` already adds "`: `", so these examples lead to double `:`:

https://github.com/echasnovski/mini.surround/blob/99eb6175801434d26496e81e47632d4e4543994a/doc/mini-surround.txt#L573
https://github.com/echasnovski/mini.surround/blob/99eb6175801434d26496e81e47632d4e4543994a/doc/mini-surround.txt#L578

**Comment by echasnovski** [comment]
Thanks for noticing this! Should be fixed on latest `main`.
