### ISSUE TITLE
[mini.sessions] Session management based on git branches

### ISSUE THREAD

**Issue by GuillaumeLagrange** [echasnovski/mini.nvim#987]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.sessions, maybe mini.git

### Description

VSCode has a neat feature described in this screenshot

![image](https://github.com/echasnovski/mini.nvim/assets/19265358/ff5ea778-dab2-4295-bee1-92691e5140a1)

What it does is automatically save and restore editors (~buffers + windows in nvim world) depending on your source control branch.  
There is also a setting for a default behavior, i.e when a new branch is opened.

Would such a feature belong to mini.sessions ? I know other plugins manage this kind of stuff, but I really like `mini.sessions`

Even if it does not, I think a snippet on how to do this could be handy in the documentation, what do you think ?

I could try and build one, but I was wondering if anyone new of a way to react to branch change events ? I would rather avoid polling a git status command every few seconds to detect that we just changed session.

### Key points of the UX I would love
- Opening nvim would re-open buffer windows and tabs (basically the native nvim session) that was previously opened in the branch
- Changing branches when nvim is opened within the repo:
    - If a session already exists for the branch, it should be loaded (or open a dialog offering the choice between loading the previous session or saving the current state as this branch's session)
    - Else, depending on configuration, it would either close all buffers and potentially show a landing page, or keep the current buffers, and save this as the branch's session

**Comment by echasnovski** [comment]
Thanks for such detailed suggestion!

I consider overall design and feature set of 'mini.sessions' complete. So I am afraid this type of functionality won't be part of 'mini.sessions'.

The 'mini.git' module *could* help, but it works for every buffer separately (gets data from that buffer's repository, and not necessarily from current working directory). And as sessions are allowed to contain buffers from several repositories, it is not clear when it should prompt the session update.

Closing as not planned.

------

My best suggestion would indeed be to make a best effort of automating this:
- Decide on naming scheme for global sessions. It should be something like "project name + branch".
- Remember to write session manually after each branch change (relatively straightforward) or indeed detect branch change in repo for the current working directory (not straightforward). For the second one take a look at [how 'mini.git' does this](https://github.com/echasnovski/mini.nvim/blob/334a2d9cfbd86ea08c4d870e39b5ba8bb354d938/lua/mini/git.lua#L1280) (quite scary code, unfortunately): basically, watch a '.git' directory for relevant changes after which asynchronously recompute branch name.
- Read session inside manual mapping which would compute project and branch names, construct global session name, and read it.

**Comment by GuillaumeLagrange** [comment]
I settled with a small autocommand on focus gain, since I generally have a terminal external to nvim were I perform any git operation.

Sharing the solution I came up with in case anyone wants the same behavior as me i.e
- Autoload session according to branch on nvim open and on branch change (triggered by focus gain)
- Autosave session per branch on nvim quit OR on branch change

Init Mini.sessions with the following options
```lua
    require('mini.sessions').setup({
      file = '',
    })
```

Then
```lua

local function get_session_name()
  local name = string.gsub(vim.fn.getcwd(), '/', '_')
  local branch = vim.trim(vim.fn.system('git branch --show-current'))
  if vim.v.shell_error == 0 and branch ~= '' then
    return name .. '_' .. branch
  else
    return name
  end
end

if vim.fn.argc(-1) == 0 then
  vim.api.nvim_create_autocmd({ 'VimEnter', 'FocusGained' }, {
    nested = true,
    callback = function()
      local session_name = get_session_name()

      -- Save session for current branch
      if vim.v.this_session ~= '' then
        MiniSessions.write()
      end

      if MiniSessions.detected[session_name] and string.find(vim.v.this_session, session_name) == nil then
        MiniSessions.read(session_name)
      else
        -- If we are opening a new branch, create a session for the new branch with current state
        MiniSessions.write(get_session_name())
      end
    end,
  })

  vim.api.nvim_create_autocmd('VimLeavePre', {
    callback = function()
      if vim.v.this_session == '' then
        return
      end

      MiniSessions.write(get_session_name())
    end,
  })
end
```

It is extremely opinionated (and will not work on Windows because I handle session paths in a very dirty way), but hopefully it could give some ideas to some people

Cheers !

**Comment by echasnovski** [comment]
Thanks for the follow up!

This looks relatively straightforward and easy to understand. Nice job!

The fact that it synchronously executes system command is not ideal, but I guess it is not a huge deal as it is executed on rather rare events.

**Comment by nikbrunner** [comment]
I wanted to have a similar feature and came up with this and have currently have no bugs. 

Just as an inspiration for others. 

```lua
local M = {}

-- ...

function M.get_session_name()
    local name = string.gsub(vim.fn.getcwd(), "/", "_")
    local branch = vim.trim(vim.fn.system("git branch --show-current"))
    branch = string.gsub(branch, "/", "_") -- Add this line

    if vim.v.shell_error == 0 and branch ~= "" then
        return name .. "_" .. branch
    else
        return name
    end
end

-- Directories that should auto-create sessions
M.auto_create_session_dirs = {
    vim.fn.expand("~/repos/"),
}

function M.sessions()
    require("mini.sessions").setup({
        -- Auto Load handled manually
        autowrite = true,
        directory = vim.fn.stdpath("config") .. "/sessions/",
        verbose = { read = true, write = true, delete = true },
    })

    vim.keymap.set("n", "<leader>ss", function()
        require("mini.sessions").write(M.get_session_name())
    end, { desc = "[S]ave" })

    vim.keymap.set("n", "<leader>sl", function()
        require("mini.sessions").select("read")
    end, { desc = "[L]ist" })

    vim.keymap.set("n", "<leader>sd", function()
        require("mini.sessions").select("delete", { force = true })
    end, { desc = "[D]elete" })

    -- no args, or if the only arg is the current directory
    if vim.fn.argc(-1) == 0 then
        -- Auto-load existing session on VimEnter event
        vim.api.nvim_create_autocmd({ "VimEnter" }, {
            nested = true,
            callback = function()
                local MS = require("mini.sessions")
                local session_name = M.get_session_name()

                if MS.detected[session_name] then
                    MS.read(session_name)
                end
            end,
        })

        -- Auto-switch sessions on TermLeave event (like closing the lazygit terminal)
        -- Currently this reacts to all term leave events, and not only when the snacks lazygit terminal closes
        vim.api.nvim_create_autocmd({ "TermLeave", "VimResume" }, {
            callback = function()
                local MS = require("mini.sessions")
                local session_name = M.get_session_name()

                if MS.detected[session_name] then
                    MS.read(session_name)
                end
            end,
        })

        -- Auto-create session on VimEnter for specified directories
        vim.api.nvim_create_autocmd({ "VimLeave" }, {
            callback = function()
                local MS = require("mini.sessions")
                local session_name = M.get_session_name()
                local cwd = vim.fn.getcwd()

                -- Check if cwd is in any of the auto_create_session_dirs
                local should_auto_create = false
                for _, dir in ipairs(M.auto_create_session_dirs) do
                    if vim.startswith(cwd, dir) then
                        should_auto_create = true
                        break
                    end
                end

                -- Only create if in specified dir and session doesn't exist
                if should_auto_create and not MS.detected[session_name] then
                    MS.write(session_name)
                end
            end,
        })
    end
end

---@type LazyPluginSpec
return {
    "nvim-mini/mini.nvim",
    version = "*",
    lazy = false,
    config = function()
        -- ...
        M.sessions()
        -- ..
    end,
}

```
