### ISSUE TITLE
[mini.ai] Allow to return a different region depending on the operator.

### ISSUE THREAD

**Issue by oblitzitate** [echasnovski/mini.nvim#989]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.ai

### Description

For example, `dd` and `yy` applies on the whole line and the newline char, and `cc` applies from the first non-whitespace character to the end of the line.

Another example is `dip`, `yip`, and `vip` applies on the whole block and the newline char, and `cip` applies from the first non-whitespace character to the end of the line.

I would like to be able to create a textobject that applies differently depending on the operator.

**Edit:** I noticed, it's often the `change` operator that has a different starting position, so if not this feature request, then maybe a feature that allows to set where the change starts?

**Comment by oblitzitate** [comment]
Nevermind. I realized what I was looking for was to force linewise mode

**Comment by echasnovski** [comment]
> Nevermind. I realized what I was looking for was to force linewise mode

Sure, this is already supported.

However, returning different region depending on the operator is also technically possible, as specification [allows callable objects](https://github.com/echasnovski/mini.nvim/blob/334a2d9cfbd86ea08c4d870e39b5ba8bb354d938/doc/mini-ai.txt#L251). Thus the returned region/pattern can be conditioned on `vim.v.operator` (see `:h v:operator`), but beware of doing so only in Operator-pending mode (not Visual).
