### ISSUE TITLE
Surround arround motion

### ISSUE THREAD

**Issue by ccolorado** [echasnovski/mini.nvim#993]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

mini.surround

### Description

On Tim Pope's vim surround `ysa$"` would surround from my cursor position to the end of the line, you'll be surprised how often this is used when refactoring code.

**Comment by echasnovski** [comment]
> On Tim Pope's vim surround `ysa$"` would surround from my cursor position to the end of the line, you'll be surprised how often this is used when refactoring code.

`sa$"` can already do that.
