### ISSUE TITLE
How to load 3rd party colour schemes to properly override default highlight rules?

### ISSUE THREAD

**Issue by suliatis** [echasnovski/mini.nvim#996]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [X] I have updated 'mini.nvim' to latest version

### Module(s)

mini.deps

### Description

I have a mini.nvim based configuration with the github-nvim-theme. When I overrode certain highlight groups of mini.nivm those doesn't seem to apply until I source my init.lua.

### Neovim version

0.10.0

### Steps to reproduce

Here is my init.lua to reproduce:

```lua
local path_package = vim.fn.stdpath 'data' .. '/site'
local mini_path = path_package .. '/pack/deps/start/mini.nvim'
if not vim.loop.fs_stat(mini_path) then
  vim.cmd 'echo "Installing `mini.nvim`" | redraw'
  local clone_cmd = {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/echasnovski/mini.nvim',
    mini_path,
  }
  vim.fn.system(clone_cmd)
  vim.cmd 'packadd mini.nvim | helptags ALL'
end

local MiniDeps = require 'mini.deps'
MiniDeps.setup { path = { package = path_package } }
local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later

add { source = 'projekt0n/github-nvim-theme' }
now(function()
  local github_theme = require 'github-theme'
  github_theme.setup {
    options = {
      transparent = true,
    },
    groups = {
      all = {
        MiniTablineHidden = { bg = 'None' },
        MiniTablineFill = { bg = 'None' },
        MiniPickNormal = { bg = 'None' },
      },
    },
  }
  vim.cmd.colorscheme 'github_light'
end)

now(function()
  require('mini.basics').setup {
    options = {
      extra_ui = true,
    },
  }
end)

now(function()
  local MiniPick = require 'mini.pick'
  MiniPick.setup {
    mappings = {
      scroll_left = '',
      delete_char = '<C-h>',
    },
  }
  vim.ui.select = vim.schedule_wrap(MiniPick.ui_select)

  vim.keymap.set('n', '<leader>f', function()
    MiniPick.builtin.cli({
      command = { 'fd', '--hidden', '--type', 'f', '--type', 'd', '--exclude', '.git' },
    }, {
      source = {
        name = 'Files & Dirs',
        show = function(buf_id, items, query)
          MiniPick.default_show(buf_id, items, query, { show_icons = true })
        end,
        choose = vim.schedule_wrap(MiniPick.default_choose),
      },
    })
  end, { desc = 'Pick file or dir' })
end)
```

### Expected behavior

If I source my init.lua again, then get the expected look.

<img width="1407" alt="Screenshot 2024-06-29 at 9 49 19 AM" src="https://github.com/echasnovski/mini.nvim/assets/6475233/a9328fe3-3075-4339-a044-7c5c01487e25">

### Actual behavior

The picker has grey background though I set it to be none. I had similar experience with mini.tabline, but overriding highlight groups for mini.hipatterns or mini.diff work as epxpected.

<img width="1407" alt="Screenshot 2024-06-29 at 9 49 02 AM" src="https://github.com/echasnovski/mini.nvim/assets/6475233/1592a278-f9b1-4fb9-9dcf-c05f83fd8281">

**Comment by echasnovski** [comment]
Thanks for the issue!

It seems that setting `{ bg = 'None' }` in `groups.all` clears highlight group, which means `require('mini.pick').setup()` creating *default* highlighting actually affects `MiniPickNormal` (links it to `NormalFloat`). I am not sure why sourcing the second time changes this behavior, but I'd guess it has something to do with ['github-nvim-theme' compiling its highlight groups](https://github.com/projekt0n/github-nvim-theme/blob/4f44a5c930372c85483d02700f332d34417e50b2/lua/github-theme/init.lua#L29-L41).

Setting up 'mini.pick' before color scheme seems to fix this behavior, but it seems that the proper fix is on color scheme side.

I am mostly positive that this has nothing to do with 'mini.deps' (completely removing it from 'init.lua' has same effect) or 'mini.pick' (creating *default* highlight groups is the proper way of setting them up). Closing as "most certainly not an issue with 'min.nvim'".

**Comment by suliatis** [comment]
Thank you. I moved setting up the colorscheme to the end of my init.lua and it works just fine.
