### ISSUE TITLE
Terminal Color Synchronization with OSC 10 and 11

### ISSUE THREAD

**Issue by wroyca** [echasnovski/mini.nvim#999]
### Contributing guidelines

- [X] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [X] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)

### Module(s)

hues - base16 - colors

### Description

Hello o/

Terminal with support for [OSC sequences 10 and 11](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands) allow Neovim to set and query terminal color values dynamically. mini.nvim could update the terminal palette by communicating the color value. For example, this can be done like so:

```lua
local hl = vim.api.nvim_get_hl(0, { name = [[Normal]] })

-- Ps = 1 0  ⇒  Change VT100 text foreground color to Pt.
-- Ps = 1 1  ⇒  Change VT100 text background color to Pt.
--
-- For more information, see:
-- https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Operating-System-Commands
--
local fg = string.format('\027]10;1;#%06x\007', hl.fg)
local bg = string.format('\027]11;1;#%06x\007', hl.bg)
      
io.stdout:write(fg)
io.stdout:write(bg)
```

And with autocommands:

```lua
local apply = function () io.stdout:write(string.format("\027]10;1;#%06x\a", vim.api.nvim_get_hl(0, { name = [[Normal]] }).bg)) end
local reset = function () io.stdout:write("\027]111;;\a") end

vim.api.nvim_create_autocmd({ [[VimEnter]],    [[VimResume]], [[ColorScheme]] }, {  callback = apply })
vim.api.nvim_create_autocmd({ [[VimLeavePre]], [[VimSuspend]]                 }, {  callback = reset })
```

The result is as follow:

#### Before

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/d5cdd248-6551-47bb-bc41-0dd07531f099)

#### After

![image](https://github.com/echasnovski/mini.nvim/assets/91024200/585377b4-5ee1-4003-b3d5-1c3cc230be7e)

**Comment by echasnovski** [comment]
Thanks for the suggestion!

This sounds interesting, however I can not really see the point of this. What is the final purpose of adding this? Is it mostly to remove possible "frame" of original terminal emulator background color or is there something more here?

**Comment by wroyca** [comment]
> Thanks for the suggestion!
> 
> This sounds interesting, however I can not really see the point of this. What is the final purpose of adding this? Is it mostly to remove possible "frame" of original terminal emulator background color or is there something more here?

That sums it up, yes. :)

It's the little things, as they say. Working day in and day out in the terminal makes you truly value anything that adds comfort. There's also a demand for that; 

https://www.reddit.com/r/neovim/comments/18rukht/how_to_get_rid_of_the_black_edges_on_the_right/
https://www.reddit.com/r/neovim/comments/18cbxu9/how_to_get_nvim_to_use_whole_screen_in_windows/
https://www.reddit.com/r/neovim/comments/tomcpl/black_lines_between_neovim_and_kitty_terminal/
https://www.reddit.com/r/KittyTerminal/comments/tcrejh/how_can_i_disable_the_padding_that_kitty_adds_in/
https://www.reddit.com/r/KittyTerminal/comments/mrkde6/remove_extra_margin_when_on_neovim/
https://www.reddit.com/r/KittyTerminal/comments/1auxxcc/how_can_i_ignore_kitty_padding_for_a_specific/
https://www.reddit.com/r/vim/comments/ofe72k/disabling_terminal_padding_while_using_vim/

From time to time, you'll see discussions and GitHub issues about this. Usually, people will tweak their terminal's background color to match their current theme or use socket addresses for control messages. Some even try adjusting padding, like making the terminal render in the top left corner. Here we can offer a much better integrated solution with OSC. :)

https://github.com/echasnovski/mini.nvim/assets/91024200/a6690f8d-c71c-4ef1-869b-9042a6ce3cc9

**Comment by wroyca** [comment]
> Yeah, this is an interesting idea even with only the background synchronization.
> 
> I think the better place for it might be something like `setup_bg_sync()` in 'mini.misc'. This way it is opt-in and there is no need for being extra clever in order to decide if terminal emulator supports this kind of stuff.
> 
> I'll take a look.

Some additional information: Terminal multiplexers may require special handling. One such example is TMUX, which uses device control strings:

```
'\ePtmux;seq\e\\'
```

I'm not sure whether it makes sense to handle such non-conformance, but it seems that TMUX is used fairly often in general.

**Comment by wroyca** [comment]
Can confirm that it work fine with Kitty (:

**Comment by wroyca** [comment]
Some more tests @echasnovski, the restore code is racy and will sometimes fail to restore the background if you quickly enter/exit.

E.g., using bg and fg in quick succession (normally Ctrl+Z).

![Screenshot from 2024-08-01 17-45-30](https://github.com/user-attachments/assets/d07c242b-189e-487d-b09c-02e38008952b)

The faulty part here seems to be the UILeave event. Can't reproduce when combining `{ "VimLeavePre", "VimSuspend" }` but I can reproduce with `{"UILeave", "VimSuspend"}` and (more rarely) with `{ "UILeave", "VimLeavePre" }`

**Comment by echasnovski** [comment]
> Some more tests @echasnovski, the restore code is racy and will sometimes fail to restore the background if you quickly enter/exit.

I can not reproduce this with regular usage of `<C-z>` followed by typing `fg<CR>` in command line. It pretty much immediately changes color both times. Even with pre-typing `fg` and pressing `<CR>` followed *as fast as I humanly can*  by `<C-z>`, it still works in all terminal emulators I've tried. The difference is that I have `zsh` and not `fish`, but I am not sure if that matters.

> The faulty part here seems to be the UILeave event. Can't reproduce when combining `{ "VimLeavePre", "VimSuspend" }` but I can reproduce with `{"UILeave", "VimSuspend"}` and (more rarely) with `{ "UILeave", "VimLeavePre" }`

The problem here is that ideally there should be single control sequence executed per actual user event. Having several Neovim events instead of a single `UILeave` will lead to several same control sequences written, which is not good. An alternative is to have some kind of complex logic to not duplicate on "same cause" events, but it is also not good.

I think the current solution is good as is.

**Comment by wroyca** [comment]
> I can not reproduce this with regular usage of `<C-z>` followed by typing `fg<CR>` in command line. It pretty much immediately changes color both times. Even with pre-typing `fg` and pressing `<CR>` followed _as fast as I humanly can_ by `<C-z>`, it still works in all terminal emulators I've tried. The difference is that I have `zsh` and not `fish`, but I am not sure if that matters.

Interesting; I will test out with zsh later today and see how it goes. :thinking: 

> The problem here is that ideally there should be single control sequence executed per actual user event. Having several Neovim events instead of a single UILeave will lead to several same control sequences written, which is not good

It's acceptable because it's transparent, and the specification does not explicitly state that it's a bad practice. In fact, it's a fail-safe method to ensure the terminal receives the sequence. That is, in the current state, there's uncertainty about whether the terminal receives it before Neovim stops (i.e. drop) execution

> I think the current solution is good as is.

Agree to disagree. \:)

**Comment by echasnovski** [comment]
> It's acceptable because it's transparent, and the specification does not explicitly state that it's a bad practice. In fact, it's a fail-safe method to ensure the terminal receives the sequence. That is, in the current state, there's uncertainty about whether the terminal receives it before Neovim stops (i.e. drop/suspend) execution

Consciously spamming more `io.write()` in the hope that some of them will work is not the solution.
Maybe replacing single `'UIEnter'` with `'VimEnter', 'VimResume'` and single `'UILeave'` with `'VimSuspend', 'VimLeave'` is a good alternative if events don't intersect. But I am not sure, maybe `UIEnter` and `UILeave` are useful in more contexts.

**Comment by wroyca** [comment]
> > It's acceptable because it's transparent, and the specification does not explicitly state that it's a bad practice. In fact, it's a fail-safe method to ensure the terminal receives the sequence. That is, in the current state, there's uncertainty about whether the terminal receives it before Neovim stops (i.e. drop/suspend) execution
> 
> Consciously spamming more `io.write()` in the hope that some of them will work is not the solution. Maybe replacing single `'UIEnter'` with `'VimEnter', 'VimResume'` and single `'UILeave'` with `'VimSuspend', 'VimLeave'` is a good alternative if events don't intersect. But I am not sure, maybe `UIEnter` and `UILeave` are useful in more contexts.

> Consciously spamming more io.write() in the hope that some of them will work is not the 

Hope is not quite the definition I would come up with, as it's a guarantee to fire at least once, whereas the other way around, we're left guessing whether it did or didn't. In short, we have two extreme ends here: one where we accept the little overhead knowing that it will at least always send the sequence, and the other end where we accept that it may not send it from time to time, leaving us in a non-restored state; if you argue the former is not a solution, then It seems to be only fair to argue that the latter is not either

Perhaps we can use a global as a lock state here and set it after we send the sequence at least once, though that'd be under the assumption that event are blocking (are they?)

**Comment by echasnovski** [comment]
> In short, we have two extreme ends here: one where we accept the little overhead knowing that it will at least always send the sequence, and the other end where we accept that it may not send it from time to time, leaving us in a non-restored state; if you argue the former is not a solution, then it seems to be only fair to argue that the latter is not either;

I am not entirely convinced that "it may not send it from time to time" is what is happening here. Because the fact that it can only be reproduced with a quick succession and in not any setup makes me first think about the race condition (i.e. not preserving the order of commands). If you'd add logging [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L312) and [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L318) (i.e. before sync and restore calls to `io.write()`) and confirm that it does not trigger the "restore" one, that would help.

> Perhaps we can use a global as a lock state here and set it after we send the sequence at least once, though that'd be under the assumption that event are blocking (are they?)

Sorry, until there is a reliably reproducible example I can at least try there will be no code complication.

**Comment by wroyca** [comment]
> > In short, we have two extreme ends here: one where we accept the little overhead knowing that it will at least always send the sequence, and the other end where we accept that it may not send it from time to time, leaving us in a non-restored state; if you argue the former is not a solution, then it seems to be only fair to argue that the latter is not either;
> 
> I am not entirely convinced that "it may not send it from time to time" is what is happening here. Because the fact that it can only be reproduced with a quick succession and in not any setup makes me first think about the race condition (i.e. not preserving the order of commands). If you'd add logging [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L312) and [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L318) (i.e. before sync and restore calls to `io.write()`) and confirm that it does not trigger the "restore" one, that would help.
> 
> > Perhaps we can use a global as a lock state here and set it after we send the sequence at least once, though that'd be under the assumption that event are blocking (are they?)
> 
> Sorry, until there is a reliably reproducible example I can at least try there will be no code complication.

Fair enough - I had plan to try my hand at a reproducer later today (or later this weekend if nothing else), will ping you back (or perhaps open a new issue?) with it

**Comment by wroyca** [comment]
> If you'd add logging [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L312) and [here](https://github.com/echasnovski/mini.nvim/blob/74e6b722c91113bc70d4bf67249ed8de0642b20e/lua/mini/misc.lua#L318) (i.e. before sync and restore calls to `io.write()`) and confirm that it does not trigger the "restore" one, that would help.


I couldn't reproduce with logging but I did notice that fish would end up with `[1;5A` and then throw spurious `Send job 2 (/usr/libexec/pk-command-not-found $argv) to foreground` on next `fg` command. I though "perhaps it's fish that's acting up" and sure enough, thus far I couldn't reproduce at all with bash.

If you have a minute to spare (or if anyone has) it'd be nice for someone else to try with `fish` as well

**Comment by echasnovski** [comment]
I did ask @gpanders earlier to reproduce with `fish`. Everything works as expected in Ghostty and iTerm2 terminal emulators (on MacOS, I believe).

**Comment by wroyca** [comment]
> I did ask @gpanders earlier to reproduce with `fish`. Everything works as expected in Ghostty and iTerm2 terminal emulators (on MacOS, I believe).

Interesting, I was able to reproduce with `st` and `fish`

**Comment by wroyca** [comment]
Was able to reproduce with `zsh`, eh. back to square one.

**Comment by pkazmier** [comment]
> Can confirm that it work fine with Kitty (:

It works on WezTerm as well.

While I don't often have different background colors between my terminal and neovim (what kind of monster do you think I am?? 😄 ), it does happen sometimes, so this new feature is quite nice as that mismatched border hurts my brain 😄  Great idea @wroyca

**Comment by wroyca** [comment]
> > Can confirm that it work fine with Kitty (:
> 
> It works on WezTerm as well.
> 
> While I don't often have different background colors between my terminal and neovim (what kind of monster do you think I am?? 😄 ), it does happen sometimes, so this new feature is quite nice as that mismatched border hurts my brain 😄 Great idea @wroyca !!

Thank! If you appears to have some time to spare, would you mind stress test the issue from https://github.com/echasnovski/mini.nvim/issues/1111? The more people test it the more we can pinpoint what's happening
